python-pillow/Pillow

PIL/ImageFilter.py
docs/releasenotes/2.7.0.rst

Changes/additions for docs and release notes.

Release notes

---

build_children.sh

For https://github.com/python-pillow/Pillow/issues/1065

Fix repo name in curl

---

PIL/PngImagePlugin.py
libImaging/Dib.c
libImaging/Geometry.c
libImaging/QuantHash.c

Including removing one commented `# FIXME: to be supported some day` from at least PIL 1.1.1 (Oct 20, 2000). 
It probably would be supported by now if needed.

Remove unreachable code (if 0)

---

PIL/FpxImagePlugin.py
PIL/PyAccess.py
Scripts/pilconvert.py
Scripts/pilprint.py
Tests/helper.py
Tests/test_image_transform.py
Tests/test_imagecms.py

A few fixes to try and improve health

Health fixes

---

PIL/FpxImagePlugin.py
Scripts/pilprint.py

#1158 generated two new health errors, one of which is a missing import.

Further health fixes

---

PIL/PcdImagePlugin.py

It's not supported, and the implementation does nothing.

pcd: minor cleanup; remove draft method

---

Tests/check_imaging_leaks.py
Tests/check_webp_leaks.py
_imaging.c

fix putdata memory leak

---

Scripts/pildriver.py

Maybe someone will just explain to me why these lines needs to be there, but I don't see it.

Removed unused import from pildriver script

---

PIL/ImageFont.py
PIL/PSDraw.py
PIL/PcxImagePlugin.py
Scripts/createfontdatachunk.py
Tests/import_all.py
Tests/make_hash.py
Tests/test_file_libtiff.py
Tests/test_file_tiff.py
Tests/test_format_hsv.py
Tests/test_imagemath.py
Tests/test_numpy.py
Tests/threaded_save.py
Tests/versions.py
mp_compile.py

Adds future print imports where they are missing, and removes them where unnecessary.

Correct future print imports

---

PIL/GifImagePlugin.py
Scripts/gifmaker.py
Tests/test_file_gif.py

This would fix #1084 and #1085.

Added duration and loop set to GifImagePlugin

---

_imagingcms.c
_imagingft.c
encode.c
libImaging/QuantOctree.c
libImaging/Resample.c
libImaging/TiffDecode.c
libImaging/Unpack.c

Hopefully this is my last one of these.

Fixed various typos

---

_imagingft.c
setup.py

FreeType 2.1 was released on April 17, 2002.
I presume that it is past the stage where FreeType 2.0 needs to be supported.

Removed support for FreeType 2.0

---

PIL/BmpImagePlugin.py

https://github.com/python-pillow/Pillow/issues/1260

Register MIME type for BMP

---

PIL/Image.py
PIL/ImageQt.py
Tests/test_image_fromqimage.py
Tests/test_image_fromqpixmap.py
Tests/test_image_toqimage.py
Tests/test_image_toqpixmap.py
Tests/test_imageqt.py

Contributing to #897 by building on the work of #905
This simply restores the ImageQt class.

Add functions to convert: Image <-> QImage; Image <-> QPixmap

---

docs/reference/Image.rst

Documentation for width and height properties

---

Tests/test_image_toqpixmap.py

The same as #1315, only the fix is for a different file.

Fixed ValueError in Python 2.6

---

PIL/DcxImagePlugin.py
PIL/FliImagePlugin.py
PIL/GifImagePlugin.py
PIL/ImImagePlugin.py
PIL/MicImagePlugin.py
PIL/MpoImagePlugin.py
PIL/PsdImagePlugin.py
PIL/SpiderImagePlugin.py
PIL/TiffImagePlugin.py
Tests/test_file_dcx.py
Tests/test_file_fli.py
Tests/test_file_gif.py
Tests/test_file_im.py
Tests/test_file_mpo.py
Tests/test_file_psd.py
Tests/test_file_spider.py
Tests/test_file_tiff.py

Resolves #1190
This adds the property `is_animated`, to check if an image has multiple layers or frames.

Added is_animated

---

setup.py

Allow Tcl/Tk frameworks to be disabled on OS X by setup arguments

---

docs/reference/ImageDraw.rst

And re-order params to match method.
[CI skip]

Add missing fill param

---

setup.py

Also removed the commenting of a blank line.

Changed indentation to be consistent

---

appveyor.yml

Added Python 3.3 to AppVeyor

---

PIL/ImageGrab.py
Tests/test_imagegrab.py
docs/reference/ImageGrab.rst

Added support for ImageGrab.grab to OS X

---

PIL/Image.py

Minor change. Fixes a flake8 line too long warning introduced in #1372

Flake8 fix

---

PIL/TiffImagePlugin.py

Fixes a health warning generated by #1391

Health fix

---

PIL/ImageMorph.py
Tests/test_imagemorph.py

Check that images are L mode in ImageMorph methods

---

mp_compile.py

Pypy3 seems to be unreliable with multiprocessing enabled builds. This pr:
* Disables multiprocessing for pypy3
* Refactors the install of mp_compile to not have a nasty long if condition.

Single threaded build for pypy3, refactor. Workaround for #1176

---

PIL/Image.py

Dedup code in image.open

---

PIL/TiffImagePlugin.py
Tests/test_file_tiff_metadata.py

Fix for UnicodeDecodeError in TiffImagePlugin

---

PIL/TiffImagePlugin.py
mp_compile.py

This makes style changes to conform to [a style that was requested](https://github.com/python-pillow/Pillow/pull/1417/files#r39264521).

Style changes

---

PIL/TiffImagePlugin.py
mp_compile.py

Reverts python-pillow/Pillow#1418
This is screwing up the changes to the Tiff IFD by making it hell to merge.

Revert "Style changes"

---

PIL/JpegImagePlugin.py

Removed trailing whitespace

---

PIL/TiffImagePlugin.py
PIL/TiffTags.py
docs/handbook/image-file-formats.rst

A few minor Tiff changes -
- Flake8 fixes
- A deprecation warning was described, so it has now been updated
- The documentation has also been updated accordingly

Minor Tiff changes

---

PIL/PdfImagePlugin.py
Tests/test_file_pdf.py
docs/handbook/image-file-formats.rst

Added PDF multipage saving

---

docs/installation.rst

Add Python 3.5

---

Tests/test_imagewin_pointers.py
display.c
libImaging/Dib.c
libImaging/ImDib.h

Use correctly sized pointers for windows handle types. 

---

PIL/Image.py
Tests/test_image.py

Fix handling of pathlib in save. Fixes #1460

---

requirements.txt

These are mentioned in `make release-test`, but not installed by the process.

Added some requirements for make release-test [ci skip]

---

setup.py

`python3.4 setup.py install` is not working on my computer. While I didn't fix the issue, I did come across another one here.

Fix Exception when installing jpeg

---

Tk/README.rst

The 'last updated' lines are only correct in spirit at best, and are only going to become less reflective of reality as time goes on.

Removed outdated Last Updated notes [ci skip]

---

appveyor.yml

I don't need to be the gatekeeper here

Moving the depends repo to the organization

---

Scripts/createfontdatachunk.py

Shebang it

---

Tests/test_numpy.py

Minor fix. Removed a shortlink that was unnecessary, given that the full URL was also given.

Removed shortlink

---

Scripts/pilprint.py

Added subprocess.Popen to pilprint script

---

PIL/Image.py
Tests/test_image_array.py

test, fix missing 'version' key value in __array_interface__

---

PIL/BdfFontFile.py

Minor fix. These lines are unused. So I have commented out the meaningful ones, and removed the one that is less meaningful.

Commented or removed unused lines

---

Tests/test_imagedraw.py
_imaging.c
libImaging/Draw.c
libImaging/Imaging.h

Changed arcs, chords and pie slices to use floats

---

Tests/test_imagefont.py

Simple test like in https://github.com/python-pillow/Pillow/issues/1540#issuecomment-157741134.
Closes https://github.com/python-pillow/Pillow/issues/1540.

Test ImageFont getters

---

PIL/FpxImagePlugin.py
PIL/ImtImagePlugin.py
PIL/McIdasImagePlugin.py
PIL/PixarImagePlugin.py
PIL/XVThumbImagePlugin.py

Apparently I missed some last time #1333

Changed register calls to use format property

---

tox.ini

The current URL redirects to the updated URL.

Updated Tox URL

---

PIL/IcoImagePlugin.py
PIL/SpiderImagePlugin.py

Updating further URLs to point to their redirects.

Updated URLs

---

docs/installation.rst

Added documentation for abusing pip to send --enable-[feature] flag to the build Ref:#1412

Added documentation for abusing pip

---

PIL/JpegImagePlugin.py

Catch the IFD error near the source

---

MANIFEST.in

Adds .editorconfig to the manifest, after #1489

Added .editorconfig to manifest

---

Tests/test_pyroma.py

Because pyroma changed their message since the last time I did this.

Forcing this one to pass

---

docs/index.rst

As noted here - https://travis-ci.org/python-pillow/Pillow/jobs/101156276#L4102

Updated redirected URL

---

PIL/Image.py

Corrected comment

---

docs/handbook/concepts.rst

Clarified YCbCr handling

---

PIL/ImageSequence.py
Tests/test_imagesequence.py

Modified ImageSequence Iterator class to be an iterator

---

PIL/ImageSequence.py
Tests/test_imagesequence.py

Allow ImageSequence to seek to zero

---

depends/fedora_23.sh
depends/freebsd_10.sh
depends/ubuntu_12.04.sh

Added some new dependency scripts:
* Ubuntu 12.04
* Fedora 23
* Freebsd 10

Additional dependency scripts

---

docs/releasenotes/3.2.0.rst

Wanted to get the api changes noted as they happen, rather than in a panic at the end.

In Progress release notes for api changes in 3.2 

---

docs/handbook/image-file-formats.rst

Description modified from the release notes - https://github.com/python-pillow/Pillow/blob/master/docs/releasenotes/3.2.0.rst#new-dds-and-ftex-image-plugins

Added FTEX documentation to Image File Formats list

---

CONTRIBUTING.md

See https://github.com/python-pillow/Pillow/issues/1658
Something like this?

How to report security vulnerabilites

---

docs/handbook/tutorial.rst

Corrected tranpose/rotate documentation

---

Tests/test_imagecms.py
_imagingcms.c
docs/reference/ImageCms.rst

Hi! We developed smc.freeimage as a fast image library when PIL was not competitive.  Now PIL has caught up a lot, but there are some features missing, and I am sending you a patch to fix one of them: A  lot of details about ICC profiles are currently inaccessible.  This patch exposes the information.  What do you think?

Give much more details about ICC profiles.

---

Scripts/pilprint.py

Added debug to available options for pilprint when viewing the command line list of options.
Also updated the version number in the command line list of options, so that it is consistent with the VERSION constant.

Added debug to available options for pilprint

---

docs/installation.rst

Install docs

---

MANIFEST.in
Makefile
docs/requirements.txt
requirements.txt

- pip freeze
- Combine docs/requirements.txt with requirements.txt (No need for separate reqs if top-level calls sub-level.)

Clean up reqs

---

LICENSE
docs/about.rst

As discussed in #1507, this PR is created for inspection and review.

Added Pillow to LICENSE

---

.github/CONTRIBUTING.md

As suggested in https://github.com/python-pillow/Pillow/issues/1660#issuecomment-204913423

Added AppVeyor to CONTRIBUTING

---

selftest.py

From my investigation, the last usage of this variable was removed in #260

Removed unused variable from selftest

---

PIL/PixarImagePlugin.py

See Background section of https://reference.wolfram.com/language/ref/format/PXR.html

Added PixarImagePlugin file extension

---

README.rst

Preview: https://github.com/python-pillow/Pillow/blob/tabulate-badges/README.rst
Inspired by https://github.com/pytest-dev/pytest-cov/blob/master/README.rst
Is this any clearer?

Tabulate badges

---

appveyor.yml

A configuration to push appveyor builds up to s3.

Appveyor builds -> s3

---

docs/conf.py

See http://www.sphinx-doc.org/en/stable/config.html#confval-texinfo_documents for documentation of this code.

Updated Sphinx project description

---

Tests/icc/LICENSE.txt

Corrected the filename listed in the license file to match the filename. See https://github.com/python-pillow/Pillow/tree/master/Tests/icc

Corrected filename

---

PIL/PngImagePlugin.py
Tests/test_file_png.py
docs/handbook/image-file-formats.rst

Pr 1840 + typo fixes

---

docs/handbook/tutorial.rst

Fixed tutorial code and added explanation

---

PIL/ImageShow.py

Added check for executable permissions to ImageShow

---

PIL/Image.py

See https://github.com/python-pillow/Pillow/blob/master/PIL/ImageShow.py

Corrected Image show documentation

---

PIL/ImageDraw.py
PIL/ImageWin.py

Replaced Exception with NotImplementedError

---

PIL/JpegImagePlugin.py
PIL/TiffImagePlugin.py
Scripts/enhancer.py
Scripts/pildriver.py
Scripts/thresholder.py
Tests/test_file_tiff.py
Tests/test_imagepath.py
profile-installed.py

Brings landscape health up to 85%.

Landscape health fixes

---

appveyor.yml
test-installed.py

Allows us to see where a test is hanging on appveyor.

Add more detail to the appveyor test runs

---

Scripts/enhancer.py
Scripts/painter.py
Scripts/thresholder.py

* Do not start Tk if only to exit
* Added missing usage text and exit on Scripts if there is an incorrect number of arguments

Scripts with an incorrect number of arguments

---

docs/handbook/writing-your-own-file-decoder.rst

Updated example decoder

---

docs/installation.rst
setup.py

Same effect as #1768, but using a command line flag to match the other disable options. 
Also includes docs.

Alternative to PR #1768

---

PIL/ImageCms.py
PIL/ImageDraw.py
PIL/ImageMath.py
PIL/ImageMode.py
PIL/ImagePath.py
PIL/ImageShow.py
PIL/ImageTk.py
PIL/ImageTransform.py
PIL/ImageWin.py

Change comments to more useful docstrings.
Plus flake8 things, like imports at the top of file, and long lines.
Replacement for PR https://github.com/python-pillow/Pillow/pull/1919.

 Comments to docstrings (+flake8)

---

.github/PULL_REQUEST_TEMPLATE.md

Just a simple one for now, let's add and change it however best suits the project.
https://github.com/blog/2111-issue-and-pull-request-templates
https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

Add simple PR template

---

Tests/test_box_blur.py
libImaging/BoxBlur.c

Box blur alpha

---

depends/alpine_Dockerfile
setup.py

Fixes #1763
* try/except around dpkg-architecture
* adds `/lib` to the library paths
* sample docker file that builds and runs tests.

Alpine setup.py fixes

---

PIL/SpiderImagePlugin.py

Changed SpiderImagePlugin register and save calls to use format property

---

Tk/tkImaging.c

change function declaration to match Tcl_CmdProc type

---

docs/handbook/image-file-formats.rst

Docs for pr#1909

---

PIL/ImageQt.py

Fixes https://github.com/python-pillow/Pillow/issues/1939 using suggested solution.

Fix for program importing PyQt4 when PyQt5 also installed

---

docs/handbook/concepts.rst

Filters comparison table

---

Tests/test_image_convert.py
libImaging/Convert.c

Fixes #1979.
* Convert P to LA without deforming image

Fix issue converting P mode to LA

---

PIL/TiffTags.py

Fixed enums for Resolution Unit and Predictor

---

Tests/test_image_convert.py

Improve test for #1986

---

Makefile

Guessing that this was meant to be plural. I thought I'd put this up for review however.

Fixed typo

---

Tests/test_file_pcx.py
libImaging/PcxEncode.c

PCX encoding fixes

---

Tests/check_j2k_overflow.py
Tests/test_file_bmp.py
Tests/test_file_libtiff.py
Tests/test_file_png.py
Tests/test_image_access.py
Tests/test_imagepath.py
Tests/test_imagesequence.py
Tests/test_imagetk.py
Tests/test_imagewin_pointers.py
Tests/test_numpy.py
Tests/test_tiff_ifdrational.py

Mainly to trigger a build to see if Travis, AppVeyor and Coveralls run for PRs.

flake8 tests

---

CHANGES.rst

The only affected file is the changelog.

Merge 3.3.1

---

docs/handbook/image-file-formats.rst

Added a table of contents to make browsing the list of file formats easier to peruse.

Summary of supported file formats

---

Tests/test_numpy.py

(Added in https://github.com/python-pillow/Pillow/pull/2092)

Remove duplicate import

---

.github/CONTRIBUTING.md

Re: https://github.com/python-pillow/Pillow/issues/1713#issuecomment-204597429

Update security email address

---

docs/handbook/image-file-formats.rst
docs/releasenotes/3.4.0.rst

Requested in #2014, concerning the changes from #2103.

Added release notes and improved documentation for append_images

---

PIL/JpegImagePlugin.py
Tests/test_file_jpeg.py

Read value when checking for JPEG progressive key

---

PIL/BufrStubImagePlugin.py
PIL/ContainerIO.py
PIL/FitsStubImagePlugin.py
PIL/GdImageFile.py
PIL/GribStubImagePlugin.py
PIL/Hdf5StubImagePlugin.py
PIL/ImageFont.py
PIL/ImageQt.py
PIL/IptcImagePlugin.py
PIL/TarIO.py
PIL/WalImageFile.py
PIL/WmfImagePlugin.py

Converted documentation

---

PIL/JpegImagePlugin.py
PIL/PngImagePlugin.py
Tests/test_file_jpeg.py
docs/handbook/image-file-formats.rst

Use truth value when checking for optimize option on save

---

docs/handbook/writing-your-own-file-decoder.rst

Trivial fix, but the docs do look messed up on that page.

Missing backtick

---

docs/handbook/image-file-formats.rst

One-character change.
[ci skip]

Typo in doc

---

docs/handbook/image-file-formats.rst
docs/releasenotes/3.4.0.rst

Release notes from the list in the release tracking issue, plus doc notes that were missing.

Release notes & docs

---

CHANGES.rst

The 3.3.3 section of the changelog is missing from the master branch.

Updated Changes.rst

---

Tests/test_image_resample.py
libImaging/Resample.c

Fix coefficients calculation

---

docs/installation.rst
docs/reference/ImageGrab.rst

e.g. before https://travis-ci.org/python-pillow/Pillow/jobs/170394881#L3453

Fix too-short title underlines and malformed table

---

docs/handbook/image-file-formats.rst

Move ICO out of the list of read-only file formats

---

PIL/Image.py

Remove redundant space in PIL.Image ImportError message

---

setup.py

Rebased version of 2074

---

setup.py

Fixes a "ResourceWarning: unclosed file" during tests.

Close file in setup.py after finished reading

---

.travis.yml
PIL/ImageQt.py
Tests/test_image_toqimage.py

Fixes #1370 .
- Retain a reference to the data passed into the QImage constructor.

Fix for ImageQt Segfault

---

PIL/ImageMorph.py
PIL/PalmImagePlugin.py
PIL/TiffImagePlugin.py

Prompted by this comment - https://github.com/python-pillow/Pillow/pull/2196#discussion_r86660305

Replaced range(len())

---

PIL/Image.py
Tests/test_image_paste.py

Changed behaviour of default box argument for paste method to match docs

---

setup.py

See #2171 
Adds Custom Exceptions rather than a cryptic error.

Raise custom exceptions when required/requested items are not found

---

PIL/Image.py
Tests/test_image_resample.py
Tests/test_image_resize.py

Cumulative pull request for the small fixes related to resizing

Resample and tests issues

---

Tests/test_imagepalette.py
libImaging/Pack.c

Fixes #2258 .
(test and fix from @pdknsk)

Fix for 2 bit palette corruption #2258

---

docs/reference/index.rst
docs/reference/internal_design.rst
docs/reference/limits.rst
docs/reference/open_files.rst

Design documentation. This needs to be somewhere other than in my head or in threads on github.
I'm planning on adding to this, bur it's useful at this point.

Design docs

---

selftest.py

This is the same as PR #2277, only for selftest.py instead of setup.py

Set executable flag on selftest.py and added shebang line

---

PIL/BdfFontFile.py
PIL/CurImagePlugin.py
PIL/FontFile.py
PIL/FpxImagePlugin.py
PIL/Image.py
PIL/ImageMorph.py
PIL/IptcImagePlugin.py
PIL/JpegImagePlugin.py
PIL/SpiderImagePlugin.py
PIL/TiffImagePlugin.py
PIL/WmfImagePlugin.py
Tests/make_hash.py
Tests/test_bmp_reference.py
Tests/test_format_hsv.py
Tests/test_image_resample.py
Tests/test_locale.py
Tests/test_numpy.py

I know this doesn't have any meaningful effect, but hey, it will save a few keystrokes for any Python 3 users who decide to use these comments.

Updated comments to use print as a function

---

CHANGES.rst

Merged two changelog entries from the 3.5.0 section, for simplicity and to avoid potential confusion.

Merged two changelog entries

---

PIL/GifImagePlugin.py
Tests/test_file_gif.py

Fixes/includes #2196 .
* Test for #2195
Test fails on master, passes on branch.
Ready to merge when CI passes.

Test for #2196

---

PIL/GifImagePlugin.py

PR #2133 changed the condition for optimizing GIFs, but it only changed it in one location out of two.
This is a suggestion for fixing #2195. Happy for any feedback, particularly from @wiredfool, since it was his PR.

Unified different GIF optimize conditions

---

PIL/SgiImagePlugin.py
Tests/test_file_sgi.py
docs/handbook/image-file-formats.rst

Fixes #2113 .
* Squashed and Rebased on top of #2324
* Added Tests
* Refactored loops to direct writes and passed tests on python3.

Tests for #2113

---

Tests/test_file_wmf.py

Fixes #2323 .
* Relax WMF similarity condition -- Rendering is different across windows platforms.

Test: Relax WMF test condition, fixes #2323

---

LICENSE
docs/COPYING
docs/conf.py

The next release will be next year.

Updated copyright year

---

docs/installation.rst

Pillow 3.5.0 became 4.0.0

---

winbuild/build.py
winbuild/build_dep.py

Fix invalid string escapes

---

MANIFEST.in

Before - https://travis-ci.org/python-pillow/Pillow/jobs/196314511#L3203
After - https://travis-ci.org/python-pillow/Pillow/jobs/196515599#L3226

Exclude .travis and contents from manifest

---

Tests/test_imagecms.py
_imagingcms.c

Fixes #1662.
* After a not-in-place CMS operation, propagate auxiliary (i.e. non-color) channel data to the result image. In practice, this preserves image alpha channel during a color space conversion.

Imagecms preserve aux channels

---

PIL/Image.py
Tests/test_image.py

More explicit error message when saving to a file with invalid extension

---

.travis.yml
Tests/helper.py
Tests/test_image_fromqpixmap.py
Tests/test_image_toqimage.py
Tests/test_image_toqpixmap.py

More Docker images. 
* Added Arch, Debian
* Removed Nightly

Additional docker builds

---

Tests/test_image_toqimage.py

Cleanup test image toqimage

---

Scripts/enhancer.py
Scripts/painter.py
Scripts/player.py
Scripts/thresholder.py
Scripts/viewer.py

Fixed scripts import of tkinter/Tkinter

---

PIL/DcxImagePlugin.py
PIL/FliImagePlugin.py
PIL/GifImagePlugin.py
PIL/ImImagePlugin.py
PIL/Image.py
PIL/ImageFile.py
PIL/MicImagePlugin.py
PIL/MpoImagePlugin.py
PIL/SpiderImagePlugin.py
PIL/TiffImagePlugin.py
PIL/XpmImagePlugin.py
Tests/test_file_jpeg.py
Tests/test_file_libtiff.py
Tests/test_file_tiff.py

Fixes #2032.
* Close any single frame files

In progress update to #2032

---

Tests/test_file_tiff.py

Added an extra test for the changes in #2330 for when there's a non-exclusive file pointer.

Added non-exclusive fd for test for #2330

---

docs/reference/ImageFont.rst

Add missing colon in :command:`...`

---

PIL/Image.py

`crop` returns a copy of the image if `box` is `None`.
This also returns a copy if `box` matches the Image dimensions.

Return copy on Image crop if crop dimensions match the image

---

_webp.c
libImaging/ImPlatform.h
path.c

https://bugs.python.org/issue29943 
Fixes #2479.
From @cgohlke https://github.com/python-pillow/Pillow/issues/2479#issuecomment-295367838

Undef PySlice_GetIndicesEx, see https://bugs.python.org/issue29943

---

CHANGES.rst
docs/releasenotes/4.1.1.rst
docs/releasenotes/index.rst

Cherry-pick changes from 4.1.1

---

appveyor.yml

Fixes #2504
* Added region for s3 deployment

Added region for s3 deployment on appveyor

---

PIL/Image.py
PIL/ImageShow.py

Update of PR 2509 -- Use PNG for Image.show()

---

docs/installation.rst

* Updated test matrix for FreeBSD
* Updated dependencies for FreeBSD
* Clarified Ubuntu and Debian shipping versions for OpenJpeg

Updated install docs for Freebsd

---

Tests/test_file_cur.py
Tests/test_image.py

* Replace deprecated assert_ with assertTrue
* Changed a file opening to use with

Minor test changes

---

PIL/Image.py

* Documentation, clarifying that draft doesn't do anything for most images.

Clarify that draft is only implemented for JPEG and PCD

---

docs/reference/ImageDraw.rst

Working on a small project, reading thru the docs and noticed this.
Fixes # .
* 
* 
*

Fixing small typo

---

Tests/test_file_png.py

The png leak tests were failing on travis randomly for a couple reasons:
1) The usage is measured in bytes on the mac, and k on linux. 
2) We could temporarily use more memory, so load once before checking. 
Test fails on 4.1.0, test succeeds OMM, and hopefully travis reliably.

Fix PNG leak tests

---

PIL/ImageDraw.py
Tests/test_imagedraw.py

* Add threshold parameter to ImageDraw.floodfill for filling of regions with non-homologous, but similar, coloring.

Added threshold parameter to ImageDraw.floodfill

---

appveyor.yml
setup.py
winbuild/appveyor_install_pypy.cmd
winbuild/build.py
winbuild/config.py

Fixes #2607
* Fixes setup.py to specify the version properly for Windows pypy
* Runs build/tests on appveyor on windows pypy

Fix 4.2.0 on Pypy/Windows 

---

Tests/test_imagefont.py

See https://github.com/python-pillow/Pillow/pull/2585#pullrequestreview-48779416

Removed debugging code

---

PIL/Image.py

Corrected alpha_composite args documentation

---

PIL/ImageDraw.py
docs/reference/ImageDraw.rst

Improved ImageDraw documentation

---

Tests/test_imagefont.py
_imagingft.c

Resolves #2614
Uses a test from @wiredfool

Added fix for font getsize on empty string

---

docs/index.rst

Remove Landscape/health badge

---

libImaging/Filter.c

Fixes #2635
For 2 cores:
```bash
$ python ./linear.py
15.2
$ python ./threaded.py  #before
15.4
$ python ./threaded.py  #after
9.4
$ python ./mp.py
9.0
```

Release GIL in filters

---

Tests/test_file_im.py

Copying [a test from test_file_dcx.py](https://github.com/python-pillow/Pillow/blob/master/Tests/test_file_dcx.py#L28)

Added test for ImImagePlugin tell()

---

Tests/test_lib_pack.py

Missed not covered BGRa mode

---

PIL/Image.py

Changes proposed in this pull request: (so far)
* Renaming a loop variable, which should be clearer, and ensures it isn't reused for a different purpose (and different type)
* Rewriting _dump to first get a good filename, and then use it; again the idea is to ensure variables have a known (more limited, often non-None) type.
These supplement #2687, but I'm keeping the code changes separate as they potentially change behaviour, whereas annotation should not.

[WIP] Code alteration supplementing annotation in #2687

---

PIL/TgaImagePlugin.py

Corrected version of #2643 
Adds a footer as part of version 2 of the specification - http://www.dca.fee.unicamp.br/~martino/disciplinas/ea978/tgaffs.pdf

Add targa version 2 footer

---

PIL/SpiderImagePlugin.py
Tests/test_file_spider.py

I'm actually not sure whether the test should be included - while it demonstrates the need for this PR, the test isn't standard for other formats.

Added file pointer save to SpiderImagePlugin

---

docs/releasenotes/4.3.0.rst

Resolves the 'Needs Release Notes' label on PR #2708.

Added release notes for #2708

---

PIL/Image.py

Changes documentation to reflect correct expected class

Fix comment about palette class in quantize method

---

docs/releasenotes/4.3.0.rst

Fixes #2697 .
* Rebased
* Reworded

Updated version of #2697

---

libImaging/Convert.c

```
Master          Optimized
RGB to L      555.16 Mpx/s    755.33 Mpx/s
RGBA to LA    489.66 Mpx/s    580.50 Mpx/s
```

Faster RGB to L and RGBA to LA conversion

---

libImaging/Geometry.c

```
Master          Optimized
Flop RGB     642.21 Mpx/s    1291.23 Mpx/s
Flip RGB    1355.41 Mpx/s    1355.41 Mpx/s  # just for comparison
Flop L       739.08 Mpx/s    1525.47 Mpx/s
Flip L      4858.56 Mpx/s    4858.56 Mpx/s  # just for comparison
```

Faster ImagingFlipLeftRight

---

_imaging.c

Alternate approach to #2775, using a comparison to create an integer, then a new PyBool

Alternate to #2775

---

docs/installation.rst

Updated tested version of libimagequant

---

PIL/ImageFile.py
PIL/PngImagePlugin.py
Tests/test_file_png.py
Tests/test_imagefile.py

Added context manager support to ImageFile.Parser and PngImagePlugin.ChunkStream (also to PngImagePlugin.PngStream since it inherits ChunkStream)

Added context manager support

---

Makefile

For https://github.com/python-pillow/docker-images/issues/11.

Add option to make and install with C coverage

---

RELEASING.md

Changed first instance of 'Create binary distributions' to match other instances of 'Create binary distributions' within RELEASING.md

Updated RELEASING.md

---

docs/reference/ImageDraw.rst

See https://github.com/pytroll/aggdraw/issues/11.
Fixes #2190.

Docs: Link to maintained version of aggdraw

---

docs/reference/PixelAccess.rst

Corrected parameter-name documentation mismatch.
* Documentation update

Corrected PixelAccess.rst documentation

---

PIL/GifImagePlugin.py
PIL/TiffImagePlugin.py
Tests/test_file_gif.py
Tests/test_file_pdf.py
Tests/test_file_tiff.py

Added support for generators when using append_images

---

docs/releasenotes/4.4.0.rst
docs/releasenotes/index.rst

Release notes for https://github.com/python-pillow/Pillow/pull/2789 and https://github.com/python-pillow/Pillow/pull/2833. Ping https://github.com/python-pillow/Pillow/issues/2832.

Add release notes for 4.4.0

---

appveyor.yml

Minor comment change

---

setup.py

Fixes https://github.com/python-pillow/Pillow/issues/2842.

Warn if trying to install for Py3.7 on Windows

---

CHANGES.rst

Restores lines deleted in https://github.com/python-pillow/Pillow/commit/eccf9f624b60e32e4f24c0afd20f172795914bd9 and https://github.com/python-pillow/Pillow/commit/db88c6c3161f174ede97910ffda66a3e08e662a1

Restored deleted lines

---

README.rst

Moved Glitter

---

.travis.yml

Renamed amazon to amazon-1, added amazon-2 and fedora-27

Docker test version updates

---

docs/reference/ImageChops.rst
docs/reference/ImageColor.rst
docs/reference/ImageEnhance.rst

Copied a few docstrings into the documentation.

Improved documentation

---

docs/releasenotes/5.0.0.rst

Release notes 5.0.0

---

src/PIL/IcnsImagePlugin.py
src/PIL/ImageShow.py
src/PIL/SpiderImagePlugin.py

A series of minor changes, none of which I felt warranted their own individual PR.
I will note that the Syntax print statements are modelled after https://github.com/python-pillow/Pillow/blob/master/src/PIL/SpiderImagePlugin.py#L290

Minor fixes

---

Tests/test_imagefont.py
winbuild/config.py

Updated freetype to 2.9

---

src/PIL/ImageCms.py

Removed __main__ code from ImageCms

---

README.rst

https://github.com/python-pillow/Pillow/blob/bfb0a94439232df52c8b8979c465e0ca9de87db8/README.rst

README: Add Twitter badge

---

MANIFEST.in

The codecov filename was changed in #2947
The Tk directory moved with #2911

Manifest changes

---

Tests/test_image_tobitmap.py

The line that I remove here is immediately rerun, split over the next two lines.

Removed duplicate line

---

Tests/helper.py
Tests/test_file_sgi.py
Tests/test_file_tiff_metadata.py
Tests/test_font_leaks.py
Tests/test_font_pcf.py
Tests/test_image_convert.py
Tests/test_imagefontctl.py
docs/reference/Image.rst
docs/reference/block_allocator.rst
docs/reference/internal_design.rst
docs/reference/open_files.rst
docs/releasenotes/4.0.0.rst
docs/releasenotes/4.1.0.rst
docs/releasenotes/4.3.0.rst
docs/releasenotes/5.0.0.rst
src/PIL/DcxImagePlugin.py
src/PIL/Image.py
src/PIL/ImageTk.py
src/PIL/MpoImagePlugin.py
src/PIL/PngImagePlugin.py
src/PIL/TiffTags.py
src/_imaging.c
src/_imagingft.c
src/libImaging/Resample.c
src/libImaging/SgiRleDecode.c
src/libImaging/Unpack.c

Trim trailing whitespace

---

winbuild/appveyor_install_msys2_deps.sh

Fixed msys64 build

---

docs/handbook/image-file-formats.rst

Added documentation for ICNS append_images

---

src/_imaging.c
src/libImaging/Bands.c
src/libImaging/Convert.c
src/libImaging/Effects.c
src/libImaging/ImagingUtils.h
src/libImaging/Unpack.c

Resolves #3030 
This uses the code change suggested in that issue, with a syntax correction.

Corrected undefined behaviour

---

Tests/test_imagemorph.py
src/_imagingmorph.c

Proof: https://github.com/python-pillow/Pillow/blob/master/src/PIL/ImageMorph.py#L202

Fix incorrect image type checking in _imagingmorph module

---

docs/reference/ImageDraw.rst

Remove 'del draw' from code example

---

Tests/test_imagecolor.py
docs/reference/ImageColor.rst
src/PIL/ImageColor.py

Added getrgb HSB/HSV color strings

---

src/PIL/Image.py

Improved Image.transform documentation

---

Tests/test_file_png.py

It now really tests the file after saving.

TestFilePng: Fix test_save_l_transparency()

---

docs/reference/open_files.rst
src/PIL/Image.py

Added file handling links in documentation

---

src/PIL/JpegImagePlugin.py

Fixes https://github.com/python-pillow/Pillow/issues/2944.
The image in the report appears to have two [APP1 (0xFFE1/65505) aka Exif](http://www.ozhiker.com/electronics/pjmt/jpeg_info/app_segments.html) segments. 
The first looks correct (you can see "Canon PowerShot" in there):
```
b'Exif\x00\x00II*\x00\x08\x00\x00\x00\n\x00\x0f\x01\x02\x00\x06\x00\x00\x00\x86\x00\x00\x00\x10\x01\x02\x00\x14\x00\x00\x00\x8c\x00\x00\x00\x12\x01\x03\x00\x01\x00\x00\x00\x01\x00\x00\x00\x1a\x01\x05\x00\x01\x00\x00\x00\xa0\x00\x00\x00\x1b\x01\x05\x00\x01\x00\x00\x00\xa8\x00\x00\x00(\x01\x03\x00\x01\x00\x00\x00\x02\x00\x00\x001\x01\x02\x00\x15\x00\x00\x00\xb0\x00\x00\x002\x01\x02\x00\x14\x00\x00\x00\xc6\x00\x00\x00\x13\x02\x03\x00\x01\x00\x00\x00\x01\x00\x00\x00i\x87\x04\x00\x01\x00\x00\x00\xda\x00\x00\x00x\x06 …
```

Only extract first Exif segment

---

src/PIL/Image.py

Suggested in https://github.com/python-pillow/Pillow/pull/3172#discussion_r199324106. Making a separate PR since this is a simple change, independent of that PR.

Simplified dictionary pop

---

src/PIL/PdfParser.py

This is captured by N804 / https://www.python.org/dev/peps/pep-0008/?#function-and-method-arguments
of PEP8

Use cls instead of klass as first argument

---

src/PIL/ImageQt.py

If a Qt version is already imported, attempt to use it first

---

Tests/test_file_tga.py

Add LA to TGA test modes

---

Tests/test_image_convert.py

Added test for converting GIF with RGBA palette to P

---

docs/releasenotes/5.3.0.rst

Removed 5.2.0 changes from 5.3.0 release notes

---

src/PIL/Image.py

Added NumPy to documentation

---

docs/_templates/sidebarhelp.html

Updated StackOverflow links

---

Tests/test_image_filter.py

Extracted and modified from #3273

Added ImageFilter tests

---

RELEASING.md

* Only update the Pillow submodule of pillow-wheels, rather than also updating multibuild
* Add the modified submodule before commiting

Improved pillow-wheels RELEASING instructions

---

src/PIL/Image.py

Alternate version of PR #3347, for the master branch instead of 5.2.x.

From KeyError to ValueError when saving image

---

Tests/make_hash.py
Tests/test_bmp_reference.py
Tests/test_format_hsv.py
Tests/test_image_resample.py
Tests/test_imagewin_pointers.py
Tests/test_numpy.py
src/PIL/BdfFontFile.py
src/PIL/CurImagePlugin.py
src/PIL/EpsImagePlugin.py
src/PIL/FontFile.py
src/PIL/FpxImagePlugin.py
src/PIL/Image.py
src/PIL/ImageMorph.py
src/PIL/IptcImagePlugin.py
src/PIL/JpegImagePlugin.py
src/PIL/SpiderImagePlugin.py
src/PIL/TiffImagePlugin.py
src/PIL/WmfImagePlugin.py

Clean up commented out debug print statements

---

winbuild/appveyor_install_msys2_deps.sh

Resolves #3363 
I don't know why the error started occurring, but this resolves it.

Create pacman package cache directory

---

src/PIL/TiffTags.py

Moving these changes from the incomplete #2288 into their own PR
See
- https://www.awaresystems.be/imaging/tiff/tifftags/primarychromaticities.html
- https://www.awaresystems.be/imaging/tiff/tifftags/referenceblackwhite.html

Corrected TIFF tags

---

Tests/test_imageqt.py
Tests/test_qt_image_toqimage.py
docs/reference/ImageQt.rst
src/PIL/ImageQt.py

Added PySide2

---

Tests/test_image_convert.py
src/PIL/Image.py

Added transparency to matrix conversion

---

depends/README.rst

Added raqm scripts and install_extra_test_images script

Updated Depends README

---

Tests/test_file_webp.py
src/PIL/Image.py
src/PIL/WebPImagePlugin.py

Add warnings if image file identification fails due to lack of support

---

Tests/test_imagegrab.py

See #1527
Credit to https://gist.github.com/andytuba/13b9fe7ea7f3405c04d338f93b399ff8 and https://stackoverflow.com/questions/27596975/how-to-copy-an-image-to-clipboard-in-powershell#27598434

Improved ImageGrab tests

---

Tests/test_file_webp.py
src/PIL/WebPImagePlugin.py

Resolves #3340 
Revised version of #3341, after being partially reverted in #3415

Only close existing fp in WebP if fp is exclusive

---

Tests/test_file_jpeg2k.py
src/PIL/Jpeg2KImagePlugin.py

Check quality_layers type

---

Tests/test_file_webp.py
src/PIL/WebPImagePlugin.py

 Change color table index background to tuple when saving as WebP

---

Tests/test_file_dcx.py
Tests/test_file_fli.py
Tests/test_file_gif.py
Tests/test_file_im.py
Tests/test_file_mpo.py
Tests/test_file_spider.py
Tests/test_file_tiff.py
src/PIL/DcxImagePlugin.py
src/PIL/FliImagePlugin.py
src/PIL/GifImagePlugin.py
src/PIL/ImImagePlugin.py
src/PIL/Image.py
src/PIL/MicImagePlugin.py
src/PIL/MpoImagePlugin.py
src/PIL/SpiderImagePlugin.py
src/PIL/TiffImagePlugin.py

Resolve __fp when closing and deleting

---

docs/reference/open_files.rst
src/PIL/Image.py

Updated open files documentation

---

README.rst

URLs taken from https://tidelift.com/lifter/pypi/Pillow/tasks/2439

Added Tidelift badge

---

Tests/test_file_libtiff.py
Tests/test_file_tiff_metadata.py
Tests/versions.py
src/PIL/TiffImagePlugin.py
src/PIL/TiffTags.py
src/_imaging.c
src/encode.c
src/libImaging/TiffDecode.c
src/libImaging/TiffDecode.h

Added custom int and float TIFF tags

---

docs/_static/js/script.js
docs/conf.py

Resolves #3318 
Demo available at https://pillow-radarhere.readthedocs.io/en/sidebar/reference/ImageGrab.html

Added functions to Read The Docs sidebar

---

src/PIL/Image.py

Corrected docstring

---

.gitattributes

Set EPS test files as binary

---

src/PIL/ImageShow.py

Fixed writing to temporary file

---

docs/releasenotes/5.4.0.rst

A few things from https://github.com/python-pillow/Pillow/blob/master/CHANGES.rst#540-unreleased.

Update 5.4.0 release notes

---

docs/releasenotes/5.4.1.rst

See https://github.com/python-pillow/Pillow/issues/3535#issuecomment-451671891

Added release notes for #3540

---

setup.py

Unused since 659e2946766017789e4254fa2e24096bd6abcca6.

Remove unused _tkinter var from setup.py

---

src/PIL/ImageCms.py

The argument is used as a bool and the docs describe it as a bool, so use an actual bool.

Use bool type for ImageCms inPlace argument (instead of int)

---

Tests/test_file_libtiff.py
src/PIL/Image.py

https://docs.python.org/3/reference/simple_stmts.html#the-del-statement

Python del is a statement not a function

---

.gitignore
RELEASING.md

Updates after doing the recent point release.

Update release checklist

---

Tests/helper.py

Slightly more concise and nicer syntax

Use bare 'raise' to re-raise exceptions

---

winbuild/build_dep.py
winbuild/config.py

Adds Ghostscript to all AppVeyor jobs except mingw32.

Added Ghostscript to AppVeyor

---

winbuild/build_dep.py

A few little things slipped in via https://github.com/python-pillow/Pillow/pull/3587 whilst Travis was temporarily disabled (https://github.com/python-pillow/Pillow/issues/3589).

Fix Flake8

---

docs/deprecations.rst
docs/releasenotes/4.3.0.rst
docs/releasenotes/6.0.0.rst
docs/releasenotes/index.rst

* Release notes and updated docs for https://github.com/python-pillow/Pillow/issues/3581.

Document removals

---

.travis.yml

Moved before_install before install

---

docs/reference/ImageDraw.rst

Added note about ImageDraw operations that exceed image bounds

---

winbuild/appveyor_install_pypy.cmd

Updated PyPy to 7.0.0

---

docs/deprecations.rst

Document the deprecations from #3628.

Document deprecated image plugin version constants 

---

src/PIL/TiffImagePlugin.py

Sequel to https://github.com/python-pillow/Pillow/pull/3513/commits/952de2ec4c3479874648754082095603b2a47e77

Use constants for TIFF tag types

---

src/PIL/ContainerIO.py
src/PIL/EpsImagePlugin.py
src/PIL/IcnsImagePlugin.py
src/PIL/ImageFile.py
src/PIL/Jpeg2KImagePlugin.py
src/PIL/PcfFontFile.py
src/PIL/PcxImagePlugin.py
src/PIL/PsdImagePlugin.py
src/PIL/TarIO.py
src/PIL/TiffImagePlugin.py

A bit more readable.
https://docs.python.org/3/library/io.html#io.IOBase.seek

Replace .seek() magic numbers with io.SEEK_* constants

---

RELEASING.md

See https://github.com/python-pillow/pillow-wheels/pull/112

Use pillow-wheels update script

---

Tests/test_file_ppm.py
src/PIL/PpmImagePlugin.py

Part of #3531.
https://en.wikipedia.org/wiki/Netpbm_format used as a reference.

Added PPM mime types

---

src/PIL/Image.py

Updated list of Unix utilities used to show an image

---

.github/CONTRIBUTING.md

See #3543 and https://tidelift.com/lifter/pypi/Pillow/tasks/2614 Option 1

Use Tidelift's security process

---

Tests/test_file_bmp.py
docs/handbook/image-file-formats.rst
docs/releasenotes/6.0.0.rst
src/PIL/BmpImagePlugin.py

Added DIB saving and loading through Image open

---

Tests/test_file_libtiff.py
src/PIL/TiffImagePlugin.py

Corrected length of Tiff BYTE tags

---

src/PIL/EpsImagePlugin.py

Sequel to #3611. See https://github.com/python-pillow/Pillow/issues/3322#issuecomment-460268603

Changed EPS subprocess stdout from devnull to None

---

Tests/test_image_load.py
src/PIL/Image.py

Only close exclusive fp on Image __exit__

---

winbuild/fetch.py

Retry on URLError

---

Tests/test_image.py
src/PIL/Image.py
src/PIL/WebPImagePlugin.py

Only close original fp in __del__ and __exit__ if original fp is exclusive

---

Tests/test_image_transpose.py
src/libImaging/Geometry.c

Added support for I;16 modes for remaining transpose operations

---

Tests/test_image.py
src/PIL/Image.py

Allow RGB and RGBA values for new P images

---

Tests/test_image_mode.py
Tests/test_image_putalpha.py
src/PIL/Image.py
src/libImaging/Convert.c

Promote P images to PA in putalpha

---

docs/releasenotes/6.0.0.rst

Release notes for #3563 and #3741

I;16 mode transpose support release notes

---

Tests/test_image_convert.py
Tests/test_image_putpalette.py
src/PIL/Image.py
src/_imaging.c
src/libImaging/Convert.c

Improvements to PA and LA conversion and palette operations

---

src/libImaging/Geometry.c

See https://travis-ci.org/python-pillow/Pillow/jobs/512100842#L2613 vs https://travis-ci.org/python-pillow/Pillow/jobs/512950377#L2507

Fixed incompatible pointer type warnings

---

Tests/test_image_quantize.py
src/PIL/Image.py
src/libImaging/Unpack.c

Update palette in quantize

---

src/PIL/GimpPaletteFile.py

I would guess that this code was taken from https://github.com/python-pillow/Pillow/blob/master/src/PIL/PaletteFile.py and then modified.

Simplified code

---

docs/releasenotes/6.0.0.rst

Added release notes for #3687

---

docs/reference/ImageDraw.rst
docs/reference/ImageFilter.rst
docs/reference/ImageFont.rst
docs/reference/ImageSequence.rst
docs/reference/ImageWin.rst
src/PIL/ImageFont.py

Improved ImageFont documentation

---

winbuild/fixproj.py

Use of winbuild/fixproj.py was removed in #3774

Removed unused file

---

depends/install_raqm_cmake.sh

Resolves #3180, by incorporating the change from https://github.com/HOST-Oman/libraqm-cmake/pull/1

Updated raqm-cmake

---

.travis.yml

Test with the latest pypy/pypy3
**Edit**: Seems blocked on Travis: https://travis-ci.community/t/add-pypy-7-support/2228

Test with the latest pypy/pypy3

---

docs/handbook/concepts.rst

Document pixel range

---

Tests/test_imagegrab.py
docs/reference/ImageGrab.rst
src/PIL/ImageGrab.py
src/display.c

Added option to include layered windows in ImageGrab.grab on Windows

---

Tests/test_image.py
src/PIL/Image.py

Fixed opening mmap image through Path on Windows

---

Tests/test_file_pdf.py
src/PIL/PdfImagePlugin.py

Fixed dimensions of 1-bit PDFs

---

README.rst

Link to https://tidelift.com/subscription/pkg/pypi-pillow.

Add info to README re: Tidelift [ci skip]

---

src/_imagingft.c
src/libImaging/Draw.c
src/libImaging/Jpeg2KEncode.c

See
- https://travis-ci.org/python-pillow/Pillow/jobs/525439588#L2444 vs https://travis-ci.org/python-pillow/Pillow/jobs/525294336#L2454
- https://travis-ci.org/python-pillow/Pillow/jobs/525439588#L2613 vs https://travis-ci.org/python-pillow/Pillow/jobs/525294336#L2648
- https://travis-ci.org/python-pillow/Pillow/jobs/529684692#L2602 vs https://travis-ci.org/python-pillow/Pillow/jobs/530078839#L2492

Fixed several warnings

---

Tests/test_file_im.py
Tests/test_file_tiff.py
Tests/test_pickle.py
docs/reference/Image.rst
src/PIL/ImImagePlugin.py
src/PIL/Image.py
src/PIL/TiffImagePlugin.py
src/_imaging.c

Resolves #1600. Sequel to #3728

Improved palette handling for LA and PA modes

---

Tests/test_image_transform.py
src/PIL/Image.py

Updated resampling filter error messages

---

docs/installation.rst

Renamed OS X reference to macOS

---

.github/ISSUE_TEMPLATE.md

* Add guidance on writing issues, as discussed in https://github.com/python-pillow/Pillow/pull/3857#issuecomment-493889987
* Point general questions towards Stack Overflow
* Point to guidelines on writing self-contained examples bug reports
* Advice is in `` comments so will be hidden if not deleted from the issue, to show the most pertinent info

Advice on general questions, bug reports and feature requests

---

docs/releasenotes/6.1.0.rst

Added release notes for #3802 and #3856

Added release notes for #3802 and #3856

---

Tests/test_features.py
Tests/test_imagefont.py
Tests/test_imagefontctl.py
Tests/test_main.py

Lint is failing at the moment - https://travis-ci.org/python-pillow/Pillow/jobs/548971434

Fixed black formatting

---

src/PIL/_binary.py

Before - https://pillow.readthedocs.io/en/latest/PIL.html#module-PIL._binary
After - https://pillow-radarhere.readthedocs.io/en/param/PIL.html#module-PIL._binary

Improved parameter documentation

---

src/libImaging/Convert.c

Fixes: 7a4af2b7671b14163f61c7f88889fad66e50d77b
@cgohlke

fix bad loop increments in p2i() and p2f()

---

setup.py

Also update author name and email
Proposed fix for #3938.
* Add license info to setup.py
* Update author name and email

Add license to setup.py for #3938

---

.travis/install.sh

Includes raqm in the non-docker Travis jobs. Suggested in https://github.com/python-pillow/Pillow/issues/3835#issuecomment-507408755

Install raqm on Travis

---

src/PIL/TiffTags.py

See https://www.awaresystems.be/imaging/tiff/tifftags/minsamplevalue.html and https://www.awaresystems.be/imaging/tiff/tifftags/exififd.html

Corrected tag type

---

docs/installation.rst

Changed MAX_CONCURRENCY description

---

src/PIL/ImageShow.py

Just cleaning up a weird result of Black reformatting.

Cleaned up strings

---

Tests/README.rst

I'm pulling this out of #3980 into a separate PR.
Thanks @kkopachev

Corrected underline

---

Tests/test_file_jpeg2k.py
src/encode.c

Resolves #3966 
The code was originally added in https://github.com/python-pillow/Pillow/commit/ac8ebccfa631a2390a5dd9cb175ae7

Return after error

---

docs/index.rst

Helps https://github.com/python-pillow/Pillow/issues/4026.
See https://pillow-radarhere.readthedocs.io/en/enterprise/ for a preview

Added Tidelift Subscription link

---

docs/handbook/concepts.rst
src/libImaging/Storage.c

Documented more limited support modes

---

docs/releasenotes/6.2.0.rst
docs/releasenotes/index.rst

Adds release notes for
- #3978
- #4031
- #4029
- https://github.com/python-pillow/pillow-wheels/pull/125

Added release notes

---

src/PIL/TiffImagePlugin.py

Do not seek if the file pointer is about to be closed

---

src/PIL/Image.py

See https://github.com/python-pillow/Pillow/pull/1730#issuecomment-533796721

Updated warning to specify time of change

---

Tests/test_file_spider.py
src/PIL/SpiderImagePlugin.py

Round Spider record count

---

docs/releasenotes/6.2.0.rst

Documented #3950 in the release notes

---

Tests/test_imageops.py
src/PIL/ImageOps.py

Do not calculate the crop width in Image.fit if it is already known

---

src/PIL/__init__.py

Removed outdated VERSION comment

---

docs/releasenotes/6.2.0.rst

Use double backticks

---

.appveyor.yml
winbuild/config.py

Helps #4110
Uses the script from https://github.com/matthew-brett/multibuild/pull/264 to add Python 3.8 rc1 to AppVeyor.

Added Python 3.8 rc1 to AppVeyor

---

docs/handbook/concepts.rst

I feel like understanding image orientation is a common problem, and Concepts was the best place I could think of for a note about that.

Added orientation note

---

tox.ini

Allows contributors to automatically test locally.

Add PyPy3 to the tox test matrix

---

docs/releasenotes/6.2.1.rst
docs/releasenotes/index.rst

Add release notes for Pillow 6.2.1

---

README.rst

Sequel to #4131 for #4081 and #4084

Added GitHub Actions badges for platform builds

---

docs/about.rst

See https://pillow-radarhere.readthedocs.io/en/gha/about.html for a preview.

Added GHA to About page

---

src/PIL/BlpImagePlugin.py
src/PIL/DdsImagePlugin.py
src/PIL/FtexImagePlugin.py
src/PIL/Image.py
src/PIL/TiffImagePlugin.py

Updated code to pass new lint requirements. Resolves #4179

Lint fixes

---

winbuild/config.py

Removed unused variable

---

docs/deprecations.rst
docs/releasenotes/7.0.0.rst
docs/releasenotes/index.rst

Ping @jdufresne, I put https://github.com/python-pillow/Pillow/pull/3577 under "Other Changes". Sound about right?

Update docs for 7.0.0

---

.appveyor.yml
winbuild/config.py

Now available: https://github.com/appveyor/ci/issues/3142#issuecomment-552049896.

AppVeyor: Test on Python 3.8

---

src/PIL/TiffImagePlugin.py

Rearrangement of code to only assign to variables once.

IFDRational init cleanup

---

Tests/test_image_thumbnail.py
src/PIL/Image.py

See https://github.com/python-pillow/Pillow/pull/4256#pullrequestreview-332422518

Allow thumbnail to accept non-integer size arguments

---

docs/releasenotes/7.0.0.rst

Added release notes for #4256

---

docs/releasenotes/7.0.0.rst

https://pillow.readthedocs.io/en/latest/releasenotes/7.0.0.html

Fix release notes syntax, add references

---

src/PIL/BlpImagePlugin.py
src/PIL/DdsImagePlugin.py
src/PIL/FtexImagePlugin.py
src/PIL/Image.py
src/PIL/TiffImagePlugin.py

* Run latest Black to fix lint

6.2.x: Fix Lint

---

.appveyor.yml
winbuild/config.py

This fixes the failing AppVeyor job.

Test 6.2.x against Python 3.8 final

---

Tests/test_lib_pack.py
winbuild/build_dep.py

* Fixes some post-Black fixes
* Found with [flake8-implicit-str-concat](https://github.com/keisheiled/flake8-implicit-str-concat)

Fix string concatenation

---

Tests/test_features.py
Tests/test_file_cur.py
Tests/test_file_fitsstub.py
Tests/test_file_gribstub.py
Tests/test_file_hdf5stub.py
Tests/test_file_iptc.py
Tests/test_file_xbm.py
Tests/test_font_bdf.py
Tests/test_image_array.py
Tests/test_image_copy.py
Tests/test_image_getcolors.py
Tests/test_image_getdata.py
Tests/test_image_getextrema.py
Tests/test_image_getprojection.py
Tests/test_image_histogram.py
Tests/test_image_load.py
Tests/test_image_mode.py
Tests/test_image_putalpha.py
Tests/test_imagecolor.py
Tests/test_imagemath.py
Tests/test_imageshow.py
Tests/test_imagewin_pointers.py
Tests/test_lib_image.py
Tests/test_psdraw.py
Tests/test_pyroma.py

Convert various tests to pytest style

---

RELEASING.md

Resolves #4345, using the suggestion from https://github.com/python-pillow/Pillow/issues/4345#issuecomment-572229441

Updated release schedule

---

Tests/bench_cffi_access.py
Tests/check_imaging_leaks.py
Tests/test_color_lut.py
Tests/test_file_eps.py
Tests/test_file_gif.py
Tests/test_file_icns.py
Tests/test_file_ico.py
Tests/test_file_jpeg.py
Tests/test_file_jpeg2k.py
Tests/test_file_libtiff.py
Tests/test_file_msp.py
Tests/test_file_png.py
Tests/test_file_spider.py
Tests/test_file_tiff_metadata.py
Tests/test_image.py
Tests/test_image_access.py
Tests/test_image_resample.py
Tests/test_imagefont.py
Tests/test_imagefont_bitmap.py

Convert some tests to pytest style

---

docs/releasenotes/index.rst

Added 7.1.0 release notes to index

---

Tests/test_bmp_reference.py
Tests/test_file_blp.py
Tests/test_file_ftex.py
Tests/test_file_pcd.py
Tests/test_file_ppm.py
Tests/test_file_sgi.py
Tests/test_file_tiff_metadata.py
Tests/test_format_hsv.py
Tests/test_image_convert.py
Tests/test_image_split.py
Tests/test_imagepalette.py
Tests/test_imagesequence.py
Tests/test_tiff_ifdrational.py
Tests/test_uploader.py

Converted various files to pytest. Helps #4193

Converted to pytest

---

Tests/helper.py
Tests/test_core_resources.py
Tests/test_file_jpeg.py
Tests/test_file_jpeg2k.py
Tests/test_file_libtiff.py
Tests/test_file_libtiff_small.py
Tests/test_file_palm.py
Tests/test_file_pcx.py
Tests/test_file_png.py
Tests/test_file_tiff.py
Tests/test_image_access.py
Tests/test_imagewin.py
Tests/test_shell_injection.py

Convert to use pytest

---

docs/handbook/tutorial.rst
docs/reference/ImageDraw.rst
docs/reference/ImageSequence.rst
docs/reference/PixelAccess.rst
docs/reference/PyAccess.rst
src/PIL/EpsImagePlugin.py
src/PIL/IcnsImagePlugin.py
src/PIL/ImageFont.py
src/PIL/ImageGrab.py
src/PIL/ImageShow.py
src/PIL/IptcImagePlugin.py
src/PIL/JpegImagePlugin.py
src/PIL/SpiderImagePlugin.py

There are a few places in Pillow where images are opened from files, but not closed. This PR addresses that situation.

Close exclusively opened images

---

Tests/test_file_pdf.py
Tests/test_file_tga.py
Tests/test_file_webp.py
Tests/test_image_reduce.py
Tests/test_image_transform.py
Tests/test_imagefile.py
Tests/test_imagefont.py
Tests/test_imagefontctl.py
Tests/test_imagegrab.py
Tests/test_imagemorph.py
Tests/test_imagepath.py
Tests/test_lib_pack.py
Tests/test_mode_i16.py
Tests/test_pickle.py

Removed use of PillowTestCase in various tests

---

.github/workflows/test-windows.yml
winbuild/config.py

Updated fribidi to 1.0.9 and harfbuzz to 2.6.4

Updated fribidi and harfbuzz

---

README.rst
docs/index.rst
setup.py

Heya Pillow folks! Hope things are well (as they can be).
We have been moving towards automation of marketing leads, so I've been reviewing the UTM parameters and marketing language for lifted projects. It looks like Pillow uses our old style params, so I'm submitting this and I've submitted https://github.com/python-pillow/python-pillow.github.io/pull/18 to the website.

Update Tidelift UTM params

---

docs/releasenotes/7.1.0.rst

Add release notes for #3907 PcfFontFile charset encodings

---

CHANGES.rst
docs/releasenotes/7.1.1.rst

For the fix for https://github.com/python-pillow/Pillow/issues/4509.

Release notes for 7.1.1

---

.ci/install.sh

Alternative to #4521. Improved fix over the previous solution from #4339
Credit to https://github.com/vidify/vidify/issues/49#issuecomment-598215649

Update pip to fix PyQt5 install

---

docs/reference/ImageDraw.rst

Suggested in https://github.com/python-pillow/Pillow/issues/4485#issuecomment-605428183

Added multiline text example

---

.github/workflows/test-docker.yml

Companion to https://github.com/python-pillow/docker-images/pull/76

Added Ubuntu 20.04 to Docker jobs

---

docs/handbook/writing-your-own-file-decoder.rst

For an example in existing code, see
https://github.com/python-pillow/Pillow/blob/bc1dc14b592dbc7d303bc7a82daa13fcdc547369/src/PIL/GifImagePlugin.py#L39-L40
and
https://github.com/python-pillow/Pillow/blob/bc1dc14b592dbc7d303bc7a82daa13fcdc547369/src/PIL/GifImagePlugin.py#L875

Use _accept function in example plugin

---

src/PIL/TiffImagePlugin.py

Resolves #2341 and https://github.com/python-pillow/Pillow/blob/97280a045cc2544ef8855dac2765e765565772cd/src/PIL/TiffImagePlugin.py#L54

Replaced TiffImagePlugin DEBUG with logging

---

Tests/test_image_thumbnail.py
src/PIL/Image.py

Fixed ZeroDivisionError in Image.thumbnail

---

docs/reference/ImageGrab.rst
src/PIL/ImageGrab.py

Updated ImageGrab documentation now that Linux is supported

---

.ci/install.sh

Resolves #4659. See the issue for my explanation of why this is the solution.

Installed libxcb-xinerama0 to fix PyQt5

---

docs/releasenotes/7.2.0.rst

Added release notes for #4646

---

docs/example/DdsImagePlugin.py
src/PIL/BlpImagePlugin.py
src/PIL/BmpImagePlugin.py
src/PIL/EpsImagePlugin.py
src/PIL/FpxImagePlugin.py
src/PIL/GdImageFile.py
src/PIL/GifImagePlugin.py
src/PIL/ImImagePlugin.py
src/PIL/Image.py
src/PIL/ImageCms.py
src/PIL/ImageFile.py
src/PIL/ImageFilter.py
src/PIL/ImageFont.py
src/PIL/ImageMath.py
src/PIL/ImagePalette.py
src/PIL/ImageSequence.py
src/PIL/IptcImagePlugin.py
src/PIL/JpegImagePlugin.py
src/PIL/MicImagePlugin.py
src/PIL/MspImagePlugin.py
src/PIL/PcxImagePlugin.py
src/PIL/PngImagePlugin.py
src/PIL/PsdImagePlugin.py
src/PIL/SpiderImagePlugin.py
src/PIL/TgaImagePlugin.py
src/PIL/TiffImagePlugin.py

@radarhere This is a continuation of #4683

Fix exception causes all over the codebase

---

.ci/install.sh

Install setuptools 47.3.1 on Python 3.9

---

docs/conf.py
docs/reference/Image.rst
src/PIL/Image.py

Helps #4775
As well as being a reasonable addition to the documentation in its own right.

Documented MAX_IMAGE_PIXELS

---

docs/conf.py
docs/handbook/image-file-formats.rst
src/PIL/ImageFile.py
src/PIL/TiffImagePlugin.py

Resolves #4775
- https://pillow--4811.org.readthedocs.build/en/4811/reference/plugins.html#PIL.TiffImagePlugin.TiffImageFile.tag
- https://pillow--4811.org.readthedocs.build/en/4811/reference/plugins.html#PIL.TiffImagePlugin.TiffImageFile.tag_v2
- https://pillow--4811.org.readthedocs.build/en/4811/reference/plugins.html#PIL.TiffImagePlugin.ImageFileDirectory_v2.tagtype
- https://pillow--4811.org.readthedocs.build/en/4811/reference/ImageFile.html#PIL.ImageFile.ImageFile.tile

Document missing attributes

---

Makefile

Remove outdated make upload-test and upload commands

---

setup.py

Helps #4796
Replacing
```python
from distutils.command.build_ext import build_ext
```
with
```python
from setuptools.command.build_ext import build_ext
```
At first, trying this fails with
```
File "setuptools/command/build_ext.py", line 213, in build_extension
if ext._needs_stub:
AttributeError: 'Extension' object has no attribute '_needs_stub'
```
`_needs_stub` is set in `finalize_options()` - https://github.com/pypa/setuptools/blob/145a78cdc1afb4ce0c0208ae86a00708eb79d27b/setuptools/command/build_ext.py#L162
So we need to have all `Extension`s created before running `finalize_options`. However, we use `self.compiler` to set some attributes of `Extension`s, and that isn't set at the time of `finalize_options()`.
Instead, this PR suggests creating all `Extension`s at the very beginning, …

Replaced distutils build_ext with setuptools

---

.github/workflows/test-windows.yml

mingw-w64-x86_64-python3-numpy is mentioned twice in test-windows.yml.
https://github.com/python-pillow/Pillow/blob/cb79b1fa8900adc1617e9518bb8a83d671dc9246/.github/workflows/test-windows.yml#L227-L229

Removed duplicate package

---

Tests/test_imagefile.py
src/PIL/ImageFile.py

A recreation of PR #4838, with a test added. The original PR had its repository deleted.

Fixed duplicate variable name

---

docs/installation.rst

Add comma and minor style changes

---

.ci/install.sh
.github/workflows/test-windows.yml

Sequel to https://github.com/python-pillow/Pillow/commit/1bb382aae0028d17d72e1e224a6f7c2f889c09e5

Update setuptools for more Python 3.8 jobs

---

.ci/install.sh

Reverts #4978 - Travis now passes without it

Revert "chown pip wheels cache on ppc64le as well"

---

Makefile

Resolves #4981. Alternative to #4990

Clean up dist in release-test

---

depends/install_raqm.sh

Updated libraqm to 0.7.1

---

requirements.txt

Required in https://github.com/python-pillow/Pillow/blob/4fd397293be7168569f966f91188cf7e6a502bc5/Tests/test_imagefont.py#L9

Added packaging to requirements.txt

---

requirements.txt

Redo of https://github.com/python-pillow/Pillow/pull/5101, due to https://github.com/python-pillow/Pillow/pull/5098#issuecomment-748376733.

Added packaging

---

.ci/after_success.sh
.ci/install.sh
.ci/test.sh
.github/CONTRIBUTING.md
.github/mergify.yml
README.md
RELEASING.md
Tests/bench_cffi_access.py
Tests/helper.py
depends/README.rst
depends/diffcover-install.sh
depends/diffcover-run.sh
docs/about.rst
docs/index.rst
requirements.txt

Redo of https://github.com/python-pillow/Pillow/pull/5050, due to https://github.com/python-pillow/Pillow/pull/5098#issuecomment-748376733.

Remove unused Travis CI config

---

docs/releasenotes/8.1.0.rst

Added release notes for #4568

---

docs/releasenotes/8.1.0.rst

See https://github.com/python-pillow/pillow-wheels/pull/175

Document addition of PyPy3.7 wheels

---

docs/releasenotes/8.1.0.rst

Added #5148 to the release notes

Added #5148 to the release notes

---

docs/releasenotes/8.1.0.rst

PySide6 support was added in #5161. Add to release notes for 8.1.0

Document #5161 in release notes

---

docs/releasenotes/8.1.0.rst

Added release notes for #5149

---

docs/reference/c_extension_debugging.rst
docs/reference/internal_design.rst

Docs for C Extension debugging. 
This is a first cut, there are additions that will come from this with the valgrind tests, but it's a good place to start.

Added docs for C-Extension debugging with valgrind

---

src/PIL/Image.py

Adds documentation to resolve #5192

getcolors() returns colors in the image mode

---

selftest.py

http://www.pythonware.com is no longer up.

Removed broken link

---

src/libImaging/GifEncode.c

Suggested in https://github.com/python-pillow/Pillow/pull/5264#discussion_r575586838

Added braces

---

docs/reference/Image.rst

Example from filter should be next to filter method docs, not in 'frombytes'

---

.github/workflows/test-valgrind.yml

Add an action to run Valgrind tests when c/h code changes are proposed.

Add Valgrind GHA

---

CHANGES.rst

CHANGES.rst: update dates

---

.ci/install.sh
.github/workflows/macos-install.sh
.github/workflows/test-windows.yml
requirements.txt

Add pytest-timeout to CI and requirements.txt

Add pytest-timeout to CI and requirements.txt

---

docs/releasenotes/8.2.0.rst

And moves ``rounded_rectangle()`` to API additions.

Added release notes for #4947

---

Tests/test_imagedraw.py

Increased use of assert_image_equal_tofile

---

docs/installation.rst

Document prerequisites and Python development libraries for Alpine

---

.appveyor.yml

Matches the GitHub Actions change from https://github.com/python-pillow/Pillow/pull/5359/commits/1105c5d5c93ce2aa2693cc94ba31ebd27d8417cb

Updated nasm to 2.15.05 in AppVeyor

---

src/PIL/ImageFont.py

Fixed bug when checking FreeType2 version if it is not installed

---

.ci/test.sh
.github/workflows/test.yml

Suggested in https://github.com/python-pillow/Pillow/pull/5533#issuecomment-860628689

Reverse test order for two CI jobs

---

src/PIL/Image.py

Removed variable

---

setup.py

Prefer command line tools SDK on macOS

---

Tests/test_imagefont.py
src/libImaging/Paste.c

Resolves #5591, in the same way that #3899 was the solution for #3747

Consider I;16 pixel size when drawing text

---

docs/releasenotes/8.3.2.rst
docs/releasenotes/index.rst

For https://github.com/python-pillow/Pillow/issues/5697.

Add release notes for Pillow 8.3.2

---

setup.py

https://github.com/termux/termux-packages/issues/7788#issuecomment-950290474
tested on my device :)
should i open a separate pr for 8.4.x branch or will you take care of that?

Fix compilation on Termux

---

src/PIL/Image.py

Resolves #5797, using the suggestion from https://github.com/python-pillow/Pillow/issues/5797#issuecomment-974383267

Do not redeclare class each time when converting to NumPy

---

docs/releasenotes/9.0.0.rst

Release notes for https://github.com/python-pillow/pillow-wheels/pull/237

Added release notes for pillow-wheels#237

---

Makefile

Replaced "setup.py --long-description"

---

.ci/after_success.sh
Makefile

Invoke pip using Python

---

README.md
docs/about.rst
docs/index.rst

Updated links to their redirected locations.

Updated links

---

src/thirdparty/raqm/COPYING
src/thirdparty/raqm/NEWS
src/thirdparty/raqm/README.md
src/thirdparty/raqm/raqm-version.h
src/thirdparty/raqm/raqm.c
src/thirdparty/raqm/raqm.h

Updated raqm to 0.8.0 on Windows

---

Tests/test_numpy.py

Cherry-picking a change out of #5878

Parametrize test

---

winbuild/build_prepare.py

* https://github.com/harfbuzz/harfbuzz/releases/tag/3.3.0
* https://github.com/harfbuzz/harfbuzz/releases/tag/3.3.1

Update harfbuzz to 3.3.1

---

docs/releasenotes/9.0.1.rst

Pointed out in https://github.com/python-pillow/Pillow/commit/4fabec36197735438c80c174d018498be606c46c#r65931593

Corrected sentence

---

winbuild/build_prepare.py

https://github.com/harfbuzz/harfbuzz/releases/tag/3.3.2

Updated harfbuzz to 3.3.2

---

src/PIL/BlpImagePlugin.py

Replaced absolute PIL import with relative import

---

.pre-commit-config.yaml
Tests/32bit_segfault_check.py
Tests/check_large_memory.py
Tests/check_large_memory_numpy.py
Tests/test_core_resources.py
Tests/test_file_libtiff.py
Tests/test_file_tiff_metadata.py
Tests/test_file_webp.py
Tests/test_image_access.py
Tests/test_image_putdata.py
Tests/test_imagecms.py
Tests/test_imageqt.py
Tests/test_imagestat.py
Tests/test_map.py
Tests/test_pdfparser.py
setup.py
src/PIL/BmpImagePlugin.py
src/PIL/GimpPaletteFile.py
src/PIL/ImImagePlugin.py
src/PIL/ImageStat.py
src/PIL/ImtImagePlugin.py
src/PIL/Jpeg2KImagePlugin.py
src/PIL/PdfParser.py
src/PIL/PngImagePlugin.py
src/PIL/PpmImagePlugin.py
src/PIL/TiffImagePlugin.py
src/PIL/XbmImagePlugin.py
winbuild/build_prepare.py

Updating to black 22.1.0 introduces formatting changes.

pre-commit autoupdate --freeze

---

src/PIL/Image.py

https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.blend
I feel like this is weird.

Removed period before colon

---

docs/example/DdsImagePlugin.py

I missed the DdsImagePlugin example in #6117

decode() should return -1 when finished

---

.appveyor.yml

Fixes warnings seen at https://ci.appveyor.com/project/Python-pillow/pillow/builds/43002524/job/ow0t07qm2yrrdida#L7257

Added pytest-timeout to AppVeyor

---

winbuild/build_prepare.py

Updated zlib to 1.2.12

---

.github/workflows/stale.yml

Follow on from https://github.com/python-pillow/Pillow/pull/6203#issuecomment-1096626330.

Stale action: skip PRs without the special label and never close PRs

---

docs/releasenotes/8.0.0.rst
src/PIL/Image.py
src/PIL/SpiderImagePlugin.py
src/libImaging/GifDecode.c

Fix some typos.
* Fix some typos in src/.
* Fix typo in docs/.

Fix some typos

---

docs/releasenotes/9.2.0.rst

Include #6178 in release notes

Include #6178 in release notes

---

winbuild/build_prepare.py

See https://github.com/harfbuzz/harfbuzz/releases/tag/4.4.1

Updated harfbuzz to 4.4.1

---

setup.py

Do not quote Pillow version for setuptools >= 60

---

RELEASING.md

Change to the RELEASING procedure for #6369

Switch to GitHub Actions artifacts for Windows wheels

---

.github/workflows/test-valgrind.yml

Resolves #6468, as seen in https://github.com/radarhere/Pillow/runs/7622689068
Related to https://github.com/python-pillow/docker-images/pull/148

Updated Valgrind job to Jammy

---

Tests/test_image_paste.py

Just changed the tests to use pytest parameters instead of looping through the parameters inside each method.

Parametrize Tests/test_image_paste.py

---

.ci/install.sh
.github/workflows/macos-install.sh

NumPy now supports Python 3.11 - https://github.com/numpy/numpy/releases/tag/v1.23.2

NumPy now supports Python 3.11

---

.github/workflows/cifuzz.yml
.github/workflows/test-cygwin.yml

Set top-level permissions for remaining GitHub Actions

---

winbuild/build_prepare.py

Updated zlib to 1.2.13

---

src/_imagingft.c

* Add `Py_DECREF` calls for `seq` and `bytes`. Fixes #6321.
* Remove duplicate `PyUnicode_Check(item)` call.
* `PySequence_Size(seq)` can be changed to faster `PySequence_Fast_GET_SIZE(seq)` because `seq` was returned from `PySequence_Fast`.

Fix memory leaks related to text features

---

docs/installation.rst
winbuild/build_prepare.py

lcms2 2.14 has been released - https://sourceforge.net/projects/lcms/files/lcms/

Updated lcms2 to 2.14

---

src/_imagingft.c

Replaced IOError with OSError

---

README.md
docs/index.rst

Adds an oss-fuzz badge to the Readme.

Add oss-fuzz badge

---

winbuild/build_prepare.py

xz 5.2.8 has been released - https://tukaani.org/xz/

Updated xz to 5.2.8

---

Tests/oss-fuzz/build.sh

Applies the changes from https://github.com/google/oss-fuzz/pull/9127 to fix [oss-fuzz build failures.](https://github.com/google/oss-fuzz/issues/9086)

Use compile_python_fuzzer

---

docs/handbook/concepts.rst

Document "transparency" info key

---

winbuild/build_prepare.py

Fix version mismatch

---

winbuild/build_prepare.py

xz 5.4.1 has been released - https://tukaani.org/xz/

Updated xz to 5.4.1

---

LICENSE

... to better match HPND wording at https://spdx.org/licenses/HPND.html

Update HPND wording in LICENSE file

---

Tests/test_qt_image_qapplication.py

After https://github.com/python-pillow/Pillow/actions/runs/4256800436/jobs/7406140055, this is a further PR for #6875

Relax roundtrip check

---

docs/installation.rst
winbuild/build_prepare.py

lcms2 2.15 has been released - https://sourceforge.net/projects/lcms/files/lcms/

Updated lcms2 to 2.15

---

winbuild/build_prepare.py

harfbuzz 7.1.0 has been released - https://github.com/harfbuzz/harfbuzz/releases/tag/7.1.0

Updated harfbuzz to 7.1.0

---

.github/workflows/cifuzz.yml

It would seem helpful to run the CIFuzz tests not only when C files change, but also when cifuzz.yml itself changes.

Run CIFuzz tests when GitHub Actions file changes

---

winbuild/build_prepare.py

xz 5.4.2 has been released - https://tukaani.org/xz/

Updated xz to 5.4.2

---

setup.py

Alternative to #6921, undoing a change from #6896

Removed unnecessary silencing of stderr

---

docs/reference/ImageEnhance.rst

Improve ImageEnhance factor documentation

---

.appveyor.yml
.github/workflows/test-windows.yml

nasm 2.16.01 has been released - https://www.nasm.us/

Updated nasm to 2.16.01

---

winbuild/build_prepare.py

harfbuzz 7.2.0 has been released - https://github.com/harfbuzz/harfbuzz/releases/tag/7.2.0

Updated harfbuzz to 7.2.0

---

Tests/test_lib_pack.py
src/libImaging/Unpack.c

Added unpacker from I;16B to I;16

---

Tests/check_jpeg_leaks.py

Building on 2d1ddcaddcd1a33aae51bf6f8c895dac693f91a9.

Test both lists and tuples as qtables arguments

---

winbuild/build_prepare.py

harfbuzz 7.3.0 has been released - https://github.com/harfbuzz/harfbuzz/releases/tag/7.3.0

Updated harfbuzz to 7.3.0

---

winbuild/build_prepare.py

xz 5.4.3 has been released - https://tukaani.org/xz/

Updated xz to 5.4.3

---

docs/reference/ImageDraw.rst

Improved documentation for the argument added in #6954

Improved documention of "corners" argument for rounded_rectangle

---

.github/CONTRIBUTING.md

https://github.com/python-pillow/Pillow/pull/7219#issuecomment-1595735056 requested that this be clarified.

Clarify that the changelog should not be updated in PRs

---

winbuild/build_prepare.py

freetype 2.13.1 has been released - https://freetype.org/

Updated freetype to 2.13.1

---

docs/releasenotes/10.0.0.rst

Added release notes for #7235

---

winbuild/build_prepare.py

xz 5.4.4 has been released - https://tukaani.org/xz/

Updated xz to 5.4.4

---

winbuild/build_prepare.py

harfbuzz 8.1.1 has been released - https://github.com/harfbuzz/harfbuzz/releases/tag/8.1.1

Updated harfbuzz to 8.1.1

---

winbuild/build_prepare.py

FreeType 2.13.2 has been released - https://freetype.org/

Updated freetype to 2.13.2

---

.github/workflows/wheels-linux.yml
.github/workflows/wheels-macos.yml

PyPy 7.3.13 has been released - https://www.pypy.org/posts/2023/09/pypy-v7313-release.html

Updated PyPy to 7.3.13

---

src/PIL/ImageFont.py
src/_imagingft.c

Suggested in https://github.com/python-pillow/Pillow/pull/7246#discussion_r1248763180

Moved getmask2 MAX_IMAGE_PIXELS check to Python

---

wheels/dependency_licenses/FREETYPE2.txt

Fixes #7506.
* Include a verbatim copy of https://gitlab.freedesktop.org/freetype/freetype/-/blob/master/docs/FTL.TXT?ref_type=heads
* Include a verbatim copy of https://gitlab.freedesktop.org/freetype/freetype/-/blob/master/docs/GPLv2.TXT?ref_type=heads
* Include the relevant sections from https://gitlab.freedesktop.org/freetype/freetype/-/blob/master/src/bdf/README?ref_type=heads
* Include the relevant sections from https://gitlab.freedesktop.org/freetype/freetype/-/blob/master/src/pcf/README?ref_type=heads

DOC: Add missing sections to FREETYPE2.txt

---

docs/conf.py
docs/installation.rst
docs/resources/js/activate_tab.js

We're also using this on the [Python Developer’s Guide](https://devguide.python.org/).

Docs: Activate tabs based on browser's operating system

---

.github/workflows/cifuzz.yml
.github/workflows/test-cygwin.yml
.github/workflows/test-windows.yml
.github/workflows/test.yml

#7618, without the failing changes to the Wheels workflow.

Update actions/upload-artifact action to v4

---

RELEASING.md

Updates RELEASING.md in light of #7616

Updated RELEASING now that Trusted PyPI publishing is in use

---

src/PIL/ImageFilter.py

This should no longer be necessary after #7666

Removed unnecessary "pragma: no cover"

---

src/PIL/Image.py
src/PIL/ImageColor.py
src/PIL/ImageOps.py
src/PIL/ImagePalette.py

Added type hints to ImageOps

---

README.md
RELEASING.md
docs/index.rst
pyproject.toml

Helps https://github.com/python-pillow/Pillow/issues/7828

Removed references to Twitter

---

.appveyor.yml
.github/workflows/test-windows.yml

Ghostscript 10.3.0 has been released - https://community.chocolatey.org/packages/Ghostscript

Updated Ghostscript to 10.3.0

---

src/libImaging/Convert.c

The combination of https://github.com/python-pillow/Pillow/pull/7918 and https://github.com/python-pillow/Pillow/pull/7209 have led to failures in main - https://github.com/python-pillow/Pillow/actions/runs/8489768689
This fixes it.

Added RGB to I;16N conversion

---

Tests/test_image_getdata.py

This test isn't actually roundtripping anything.

Rename test_roundtrip() to test_mode()

---

selftest.py

Replace ImageMath.eval with ImageMath.lambda_eval in selftest.py

---

docs/Makefile
docs/conf.py
pyproject.toml

I added this to Sphinx :)
* https://www.sphinx-doc.org/en/master/changes.html#release-7-3-0-released-apr-16-2024
* https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-versionremoved
* https://github.com/sphinx-doc/sphinx/pull/11905

Remove sphinx-removed-in, now Sphinx 7.3 adds versionremoved

---

src/libImaging/Matrix.c

Just an option for an earlier return.

Extract band count check

---

.github/workflows/test-cygwin.yml
.github/workflows/test-docker.yml
.github/workflows/test-mingw.yml
.github/workflows/test-windows.yml
.github/workflows/test.yml

Updated codecov/codecov-action to v4

---

.appveyor.yml
.github/workflows/test-windows.yml

Ghostscript 10.3.1 has been released - https://community.chocolatey.org/packages/Ghostscript

Updated Ghostscript to 10.3.1

---

Tests/test_file_gif.py
src/PIL/GifImagePlugin.py
src/PIL/Image.py
src/PIL/ImageOps.py
src/PIL/ImagePalette.py

Adds type hints primarily to GifImagePlugin, with a few other cascading changes

Added type hints to GifImagePlugin

---

.readthedocs.yml

https://docs.readthedocs.io/en/stable/config-file/v2.html#build-os
> Options: ubuntu-20.04, ubuntu-22.04, ubuntu-lts-latest

Use latest Ubuntu on Read The Docs

---

setup.py

Use pkg-config to help find libwebp and raqm

---

src/PIL/Image.py

I was previously discussing these minor type hint simplifications with @nulano over at https://github.com/nulano/Pillow/pull/40#pullrequestreview-2136409453, but the decision was made to start fresh here.

Simplified casts

---

Tests/test_util.py
src/PIL/_util.py

The last was use removed in https://github.com/python-pillow/Pillow/commit/d566c04d5b9b2f7587015b110e588b073a24cf2d / https://github.com/python-pillow/Pillow/pull/8046.

Remove unused _util.is_directory

---

.github/workflows/test-windows.yml

Corrected GitHub Actions Windows Ghostscript path

---

winbuild/build_prepare.py

harfbuzz 9.0.0 has been released - https://github.com/harfbuzz/harfbuzz/releases/tag/9.0.0

Updated harfbuzz to 9.0.0

---

Tests/test_file_ppm.py
src/PIL/PpmImagePlugin.py

Allow saving I;16 images as PPM

---

.github/workflows/wheels-test.sh

Install NumPy from PyPI when testing wheels

---

.appveyor.yml
.github/workflows/test-windows.yml

Ghostscript 10.4.0 has been released - https://community.chocolatey.org/packages/Ghostscript

Updated Ghostscript to 10.4.0

---

.github/workflows/wheels-dependencies.sh
winbuild/build_prepare.py

harfbuzz 10.0.0 has been released - https://github.com/harfbuzz/harfbuzz/releases/tag/10.0.0

Updated harfbuzz to 10.0.0

---

.github/workflows/wheels-dependencies.sh
winbuild/build_prepare.py

harfbuzz 10.0.1 has been released - https://github.com/harfbuzz/harfbuzz/releases/tag/10.0.1

Updated harfbuzz to 10.0.1

---

src/libImaging/SgiRleDecode.c

Free memory on early return

---

src/PIL/ImageMath.py

Added type hints to remaining ImageMath methods

---

setup.py

Resolves #8468 
A change was missed in #8354

Fixed disabling a feature during install

---

docs/releasenotes/11.1.0.rst
docs/releasenotes/index.rst

Added release notes for using zlib-ng instead of zlib

---

src/libImaging/Unpack.c

Added RGBX;16N to RGB unpacker

---

src/PIL/BlpImagePlugin.py
src/libImaging/Unpack.c

See https://docs.python.org/3/library/collections.html#collections.somenamedtuple._replace

Use namedtuple _replace

---

Tests/test_file_jpeg.py

Use ImageFile._Tile

---

src/PIL/PngImagePlugin.py

Support saving PNG cICP chunk

---

Tests/test_file_mpo.py

Adds coverage for the lines missing at https://app.codecov.io/gh/python-pillow/Pillow/blob/main/src%2FPIL%2FMpoImagePlugin.py

Improved MpoImagePlugin test coverage

---

.github/workflows/test-windows.yml

Ghostscript 10.5.0 is now available - https://community.chocolatey.org/packages/Ghostscript

Updated Ghostscript to 10.5.0

---

.github/workflows/test-windows.yml

Ghostscript 10.5.1 has been released - https://community.chocolatey.org/packages/Ghostscript

Updated Ghostscript to 10.5.1

---

src/_avif.c
src/_imaging.c
src/_imagingcms.c
src/_imagingft.c
src/_imagingmath.c
src/_imagingmorph.c
src/_imagingtk.c
src/_webp.c

Resolves #8982
See [PEP 489](https://peps.python.org/pep-0489/)

Use PEP 489 multi-phase initialization

---

src/PIL/ImageMath.py
src/PIL/McIdasImagePlugin.py

Running with the suggestion of https://github.com/python-pillow/Pillow/pull/8979#discussion_r2172857338

Use unpacking

---

pyproject.toml

Setup nit: "fork" should be lowercased

---

Tests/test_features.py

Adds coverage for the lines missing at https://app.codecov.io/gh/python-pillow/Pillow/blob/main/src%2FPIL%2Ffeatures.py

Improve features test coverage

---

.github/workflows/wheels-dependencies.sh
winbuild/build_prepare.py

harfbuzz 11.3.3 has been released - https://github.com/harfbuzz/harfbuzz/releases/tag/11.3.3

Updated harfbuzz to 11.3.3

---

.github/workflows/wheels-dependencies.sh
winbuild/build_prepare.py

harfbuzz 11.4.5 has been released - https://github.com/harfbuzz/harfbuzz/releases/tag/11.4.5

Updated harfbuzz to 11.4.5
