python-pillow/Pillow

Tests/test_imagefont.py

Test was erroring on windows, feature is for linux/mac only.

Restrict tests to linux/osx

---

.travis.yml
build_children.sh

The last build on a branch called "latest" at the python-pillow/pillow-wheels repo will be restarted after successful builds on the master branch at python-pillow/Pillow.
`build_children.sh` (modified from [travis-build-children](https://github.com/ajdm/travis-build-children)) finds the last build on the "latest" branch at python-pillow/pillow-wheels. It uses the encrypted AUTH_TOKEN variable, generated with `travis login`, `travis token`, `travis encrypt AUTH_TOKEN=<your_travis_token>`.
We have eight Linux build jobs for different Python versions. Because we don't want to restart the OS X build each and every time they individually finish, use the [travis_after_all helper](https://github.com/dmakhno/travis_after_all) so it's only restarted after all jobs are successful.
And restrict all …

Run OS X tests after successful Linux build

---

docs/handbook/image-file-formats.rst

`im.save(fp, "png", compress_level=1)` usually allows to write PNG images 15-50% faster than with the default compression level; the size is usually 10-15% larger (as pointed by @immerrr). I think it is worths documenting this option.
It is used here: https://github.com/python-pillow/Pillow/blob/264f5d0d96968174e7b4a815f12af6613314159a/libImaging/ZipEncode.c#L77
Default value is set here: https://github.com/python-pillow/Pillow/blob/264f5d0d96968174e7b4a815f12af6613314159a/encode.c#L471; -1 means `Z_DEFAULT_COMPRESSION`, which is documented to be equal to 6 in zlib docs.

DOC document compress_level option of Image.save for PNG images

---

PIL/JpegImagePlugin.py
Tests/test_file_jpeg.py

* The buffer size hueristic in JpegImageFile needs to take `quality=keep` into account when bumping up the buffersize. 
* Added tests that should cover known combinations where a larger buffer is necessary. Using a rather incompressible file to make the resulting jpeg as large as possible.

Adjust buffer size when quality=keep, fixes #148 (again)

---

setup.py

Seems to be necessary for some 2.7 debug builds.

Turn off zip-safe flag for debug builds

---

PIL/Image.py
Tests/test_file_png.py

Add the `_repr_png_()` method to the Image object to enable image display in iPython.

iPython display hook

---

PIL/Image.py
Tests/test_pickle.py

Fixes https://github.com/python-pillow/Pillow/issues/1093 with tests.
L mode images couldn't be pickled because they had no palette:
```
File "C:\Users\hugovk\github\Pillow\tests\test_pickle.py", line 80, in test_pickle_l_mode
self.helper_pickle_string(pickle, protocol, mode="L")
File "C:\Users\hugovk\github\Pillow\tests\test_pickle.py", line 32, in helper_pickle_string
loaded_im = pickle.loads(dumped_string)
File "C:\Python27\lib\pickle.py", line 1382, in loads
return Unpickler(file).load()
File "C:\Python27\lib\pickle.py", line 858, in load
dispatch[key](self)
File "C:\Python27\lib\pickle.py", line 1217, in load_build
setstate(state)
File "C:\Python27\lib\site-packages\PIL\Image.py", line 629, in __setstate__
self.putpalette(palette)
File …
```

Pickle L mode images

---

Tests/test_lib_pack.py
libImaging/Pack.c
libImaging/Unpack.c

This enables creating images in `RGBa` mode with `frombytes` or `frombuffer` directly, previously `raw_decoder` and `raw_encoder` would choke even on `RGBa -> RGBa` no-op transformations.
This also enables band-shuffling codecs that were readily available for `RGBA` to be used for `RGBa`.  One motivation for that is to speed-up conversion to and from `QImage` in `QImage.Format_ARGB32_Premultiplied`.

Enable basic support for 'RGBa' raw encoding/decoding

---

libImaging/Unpack.c

Avoid the expensive multiply and divide when the pixel is opaque.  On my system, this change gives a 5.76x speedup loading an opaque image with this call:
PIL.Image.frombuffer('RGBA', (1000, 1000), buf, 'raw', 'RGBa', 0, 1)

Special-case opaque pixels in RGBa unpacker

---

Tests/test_file_tiff.py

This is the failing test:
https://github.com/python-pillow/Pillow/blob/master/Tests/test_file_tiff.py#L175-184
It's asking for a string representation of a `TiffImagePlugin.ImageFileDirectory()`. The implementation turns it into a `dict` and then `str`:
https://github.com/python-pillow/Pillow/blob/master/PIL/TiffImagePlugin.py#L288-293
To fix, make the `__str__()` test less strict; just test that the return value is a str and don't test actual string contents. And instead, add a new test for `as_dict()` to verify the dict contents.
Fixes #1103, closes #1105.

Fix TIFF test for PyPy 2.5.0

---

Tests/test_file_webp_alpha.py

Just trying to be helpful, this rebases the commit from #1100, so that it passes after the PyPy fix.

Different approach to handle lossy webp alpha deviations of earlier lib versions

---

PIL/ImageFont.py

The filename parameter is marked as deprecated, but is referenced in the documentation instead of font. Anyone using named parameters is thus likely to be confused as to what the font parameter is there for.

Fix truetype() documentation

---

Tests/check_webp_leaks.py
_webp.c

- add a test that will not be run automatically: `Tests/check_webp_leaks.py`
- fix 2 memory leaks
- improve error checking when using the Mux API
This fixes issue #586.

Fix WebP memory leaks

---

PIL/_binary.py
Tests/test_binary.py

This takes the commit from #1075, adds a fix, and adds some unit tests.

let python do the endian stuff + tests

---

Tests/test_image.py
libImaging/Effects.c

`test_effect_noise()` was skipped on non-Windows because it was hanging on Linux (Travis CI) and on OS X.
It got stuck in an infinite loop here:
```C
do {
v1 = rand()*(2.0/32767.0) - 1.0;
v2 = rand()*(2.0/32767.0) - 1.0;
radius= v1*v1 + v2*v2;
} while (radius >= 1.0);
```
Documentation for `rand()` says:
> The C library function **int rand(void)** returns a pseudo-random number in the range of 0 to *RAND_MAX*.
> RAND_MAX is a constant whose default value may vary between implementations but it is granted to be at least 32767.
The code makes an assumption that RAND_MAX = 32767, which it generally is on Windows, but 2147483647 on other systems. So changing the magic number to the constant RAND_MAX fixes this. The test also made assumptions about pixel values for RAND_MAX = 32767 …

Fix ImagingEffectNoise

---

Scripts/gifmaker.py

GifImagePlugin.getheader was updated about 2 years ago and changed the API that gifmaker expects.

Make gifmaker work with the current getheader

---

PIL/ImageFont.py
Tests/test_imagefont.py

This is from the suggestion in issue #589
The original poster seemed to think it would be a complex change. I can't see why, so let me know if I have missed something.

Added copy method font_variant() and accessible properties to truetype()

---

PIL/ImageFont.py

The CI failed after merging PR #1123 with:
`TabError: inconsistent use of tabs and spaces in indentation`
https://travis-ci.org/python-pillow/Pillow/builds/55271699
The PR didn't pick it up because of the [CI skip], and I wouldn't have expected it to fail either. In general, I suppose if source code is edited at all, it's better to avoid CI skip! :)
Also did some other little flake8 fixes.

Fix TabError from PR #1123

---

docs/reference/ImageDraw.rst

This pull request:
* Adds documentation for the `start` and `end` parameters of `PIL.ImageDraw.Draw.pieslice()`
* Fixes the order of the `fill` and `outline` parameter docs for `PIL.ImageDraw.Draw.pieslice()`

Improve reference docs for PIL.ImageDraw.Draw.pieslice()

---

PIL/Image.py

HTTP response objects returned from `urllib2.urlopen(url)` or
`requests.get(url, stream=True).raw` are 'file-like' but do not
support `.seek()` operations. As a result PIL is unable to
open them as images, requiring a wrap in `cStringIO` or `BytesIO`.
This commit adds this functionality to `Image.open()` by way of
an `.seek(0)` check and catch on exception
`AttributeError` or `io.UnsupportedOperation`. If this is caught
we attempt to wrap the object using `io.BytesIO` (which will
only work on buffer-file-like objects).
This allows opening of files using both `urllib2` and `requests`, e.g.
Image.open(urllib2.urlopen(url))
Image.open(requests.get(url, stream=True).raw)
This PR addresses feature request: https://github.com/python-pillow/Pillow/issues/1148

Add support for HTTP response objects to Image.open()

---

docs/reference/Image.rst

* Fix formatting to display simplefilter examples as code blocks rather than italics
* Wrap text so it's not one incredibly long line

Tidy docs for DecompressionBombWarning

---

PIL/ImageFont.py
Tests/test_imagefont.py

After the discussion in #1115, this allows truetype() to search for extensions other than .ttf if no extension is provided.

Allow truetype() to search for extensions other than .ttf

---

PIL/ImageFile.py

```
File "/.../lib/python2.7/site-packages/PIL/Image.py", line 832, in convert
self.load()
File "/.../lib/python2.7/site-packages/PIL/ImageFile.py", line 248, in load
if not self.map and (not LOAD_TRUNCATED_IMAGES or t == 0) and e < 0:
UnboundLocalError: local variable 't' referenced before assignment
```
Steps to reproduce:
```
from PIL import Image, ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
img = Image.open(<attached gif>)
img.convert("RGB")
```
It seems like `d.setimage(self.im, e)` (https://github.com/python-pillow/Pillow/blob/master/PIL/ImageFile.py#L203) raises a ValueError so the variable `t` will never be set.
I am not 100% sure if `t = None` is the right default value, but this seems to work.

Fix UnboundLocalError in ImageFile

---

PIL/BmpImagePlugin.py
Tests/test_file_cur.py

PIL choked on perfectly valid BMP files (32 bits with Alpha). It could not handle valid RGBA masks to determine the raw format.
To clarify things, I:
- Rewrote the `BmpImagePlugin.BmpImageFile` class to be far more readable
- Made error messages more explicit (e.g. say that RLE bitmaps are unsupported)
- Made a readable dict to contain BMP header information
- Kept the existing security checks
- Instead of reading palette info by chunks of 3/4 bytes, read the whole palette info at once and parse the data.
- Now works with BMPv4/5 with Alpha (and can be exported to alpha PNG for example)
- Tested load and save with RGB24, RGB8, RGB8L, RGB32 and RGBA32.
- Tested with one bogus file. File not accepted, as expected.
- Size of header attributes is made explicit in this code
I wanted to test …

Fix 32-bit BMP loading (RGBA or RGBX)

---

PIL/Image.py

@wiredfool's proposed fix for #1163: https://github.com/python-pillow/Pillow/issues/1163#issuecomment-88736596

Catch struct.error on invalid JPEG (#1163)

---

RELEASING.md

Such updates to process! Much discussions happen! A few points for review:
- I think descriptions of git syntax can vary, as long as we achieve identical results (E.g. releasing from either master or release branch are identical, assuming hashes are identical.)
- Twine is absolutely necessary and now supports Windows executable files too!
- Should we provide Linux wheels?
- Should we consider other Pillow Wheel Builders (I.e. not just for OS X)?

Aclark releasing nits

---

CONTRIBUTING.md

Why do we ask folks to create a branch within their fork?

Aclark contributing nits

---

PIL/TiffImagePlugin.py
Tests/test_file_tiff_metadata.py

Use the inverse logic used for loading floating point tag
values to also write them out again.

Tiff: allow writing floating point tag values

---

PIL/IcoImagePlugin.py

Some consumers of icon files such as py2exe care about the order that icon sizes are added, so the user should be fully in charge of this, instead of force sorting them.

Keep user-specified ordering of icon sizes

---

PIL/IcnsImagePlugin.py
Tests/test_file_icns.py

As per #998, this adds the ability to save the .icns format on OS X using the 'iconutil' tool.

Added icns save

---

Tests/test_imagefont.py

The current test failed on SLE11SP3 so use assert_image_similar() for
the test.
This fixes issue 1202.

Fix test TestImageFont.test_textsize_equal

---

Tests/test_file_icns.py

PR https://github.com/python-pillow/Pillow/pull/1209 missed a `file` -> `test_file` change on line 28, which broke the Mac build. Let's also make the constant uppercase whilst we're at it.

Fix OS X build

---

PIL/Image.py

The behavior of paste() with regard to intermediate mask values was
unclear, so this commit clarifies how it works.
This patch addresses an issue raised in https://github.com/python-pillow/Pillow/issues/1133

Clarify docstring about mask values [ci skip]

---

Tests/test_file_icns.py

PR https://github.com/python-pillow/Pillow/pull/1215 didn't properly fix PR #1209.
The original test was:
```
file = "Tests/images/pillow.icns"
...
@unittest.skipIf(sys.platform != 'darwin',
"requires MacOS")
def test_save(self):
im = Image.open(file)
test_file = self.tempfile("temp.icns")
im.save(test_file)
reread = Image.open(test_file)
self.assertEqual(reread.mode, "RGBA")
self.assertEqual(reread.size, (1024, 1024))
self.assertEqual(reread.format, "ICNS")
```
https://github.com/python-pillow/Pillow/commit/689f28aae7c9cc3fddb73e7ec2a07f169b91d4ba#diff-d48d995756d16b9d9b8151e27377a37dR25
So with renamed variables:
```
TEST_FILE = "Tests/images/pillow.icns"
...
@unittest.skipIf(sys.platform != 'darwin',
"requires MacOS")
def test_save(self):
im = Image.open(TEST_FILE)
temp_file = …
```

Fix test according to original

---

PIL/JpegImagePlugin.py

Looking at https://github.com/python-pillow/Pillow/commit/d8f55e3f50b0df2c850d15deedb46cb0e33a4cd8#diff-42c79834cd0653b67739d44923e685ac, it would seem apparent that this variable name just wasn't updated with the rest of the change.

Fixed variable name in JpegImagePlugin

---

PIL/OleFileIO.py

Support for older Python versions is no longer required, so removing the workaround and the related TODO.

Removed pre-Python 2.3 workaround from OleFileIO

---

decode.c

This is to fix #1221. Currently the GIL is not released during image decode. This pull request releases the GIL during only the `decode()` call. I skimmed all the decoding functions and none seem to touch Python data. (In fact, I don't see how they'd even have access to any Python data.) I've tested the change in a multi-threaded program for a few hours and saw no problems, though obviously with multi-threaded code that doesn't mean much.

Release GIL during image load (decode).

---

.travis.yml

`pip install pyroma` used to be a lot slower on Python 3:
```
pypy    8s
pypy3   70s
2.6     3s
2.7     2s
3.2     111s
3.3     82s
3.4     86s
```
Because of this, we only ran the pyroma tests on Python 2. The reason for pyroma's slow installation was due to one of its dependencies -- docutils. Docutils have now created wheels for Python 3 which has now brought installation times in line for all Python versions.
So we can now remove this special case.
Ref:
https://bitbucket.org/regebro/pyroma/issue/22/installation-slow-for-python-3
https://sourceforge.net/p/docutils/bugs/279/

Pyroma installation no longer slow on Py3

---

tox.ini

I don't know if Tox is used by anyone, but Python 3.4 was missing.
Replaces PR https://github.com/python-pillow/Pillow/pull/1213 which added 3.4 to tox.ini but also added a duplicate 3.4 to .travis.yml.

Add Python 3.4 to tox.ini

---

Scripts/README.rst

These scripts don't exist.
Looks like image2py was removed in PIL 1.1.7.
olesummary doesn't even exist in PIL 1.1.1, which is as far back a record as I can find.

Removed description for missing scripts

---

PIL/features.py
Tests/test_features.py
selftest.py

#1182 suggests separating out feature checking code from selftest.py into it's own module, so that users can check the availability of features at any point.
This is a basic attempt at that idea.

Separated out feature checking from selftest

---

PIL/OleFileIO.py

Upgrades OleFileIO to from 0.30 to the current version, 0.42b.
This series of commits, completely overwriting the existing version and then applying Pillow's local changes individually, was the cleanest way that I could think of.

OleFileIO Upgrade

---

PIL/IcoImagePlugin.py

(Partial) Fix for #1204, Ico files were not saving correctly on bigendian systems.

Ico files are little endian, ref #1204

---

PIL/GifImagePlugin.py

PR #1172 rearranged GifImagePlugin code, unfortunately missing that the interlace flag is not set in the getdata method.
This fixes that, resolving the problem reported in the latter part of Issue #1085

Removed interlace flag from GifImagePlugin getdata

---

PIL/GifImagePlugin.py
Tests/test_file_gif.py

The [latest comment](https://github.com/python-pillow/Pillow/issues/1085#issuecomment-110791612) in #1085 shows that the background color index is not saved by GifImagePlugin.

Added background saving to GifImagePlugin

---

.travis.yml

On a few occasions, PyPy build jobs error because the Pyroma test hangs for over 10 minutes. 
Restarting the build and they pass, but it's an annoyance.
Closes #1250.

Skip Pyroma test on PyPy

---

PIL/GifImagePlugin.py
PIL/Image.py
PIL/ImagePalette.py
Tests/test_file_gif.py
Tests/test_imagefile.py

#718 describes how saving an image in the GIF format can modify the palette of the original.
GifImagePlugin's getheader method has the comment 'create the new palette if not every color is used'. So that's why the image passed into getheader is modified.
The solution would seem to be to copy the image before passing it in.
However, this fails a few tests, because the image instance that was being checked against is no longer modified in sync with the saved file. Essentially, these tests should have been failing. I've changed the checks to similar rather than equal.
I also modified the tests affected to use copy() to try and avoid this way of sneaking past the tests in the future.

Copy image when saving in GifImagePlugin

---

README.rst
docs/index.rst

* Shields.io badges instead of broken pypip.in, which as been down for a few weeks
* Use SVG instead of PNG for consistency
* Travis CI have fixed the badge for OS X builds, add that back too
Fixes #1264.

Fix badges

---

docs/handbook/image-file-formats.rst

This is not so since #1029 (Pillow 2.7.0).

Fix JPEG image format docs

---

PIL/DcxImagePlugin.py
PIL/EpsImagePlugin.py
PIL/FliImagePlugin.py
PIL/GbrImagePlugin.py
PIL/SgiImagePlugin.py
PIL/SunImagePlugin.py
Tests/test_image.py

PR #1165 catches the struct.error generated by _binary methods when trying to open an invalid file.
This changes the _accept methods that are calling _binary, so that it does not call unless the data is of the correct length.
The struct.error catches are quite possibly still good for defensive programming, but I thought it would be good to highlight and deal with the problem more specifically.

Fixed _binary handling in _accept methods

---

appveyor.yml

> All branches are built by default. 
http://www.appveyor.com/docs/branches

Windows: build all branches

---

README.rst

Now we have a Windows build on AppVeyor, it makes sense to include its badge in README to make sure we spot failed builds early, before releases. 
But three "build: passing" badges in a row looks a bit odd:
> ![Travis CI build status (Linux)](https://travis-ci.org/python-pillow/Pillow.svg?branch=master) ![Travis CI build status (OS X)](https://travis-ci.org/python-pillow/pillow-wheels.svg?branch=latest) ![AppVeyor CI build status (Windows)](https://ci.appveyor.com/api/projects/status/github/wiredfool/pillow?svg=true&branch=winbuild)
AppVeyor allows you to customise the right-hand side text (http://www.appveyor.com/docs/status-badges), but Travis CI doesn't.
But Shields.io allows you to override the default left-hand-side text (which makes more sense) and supports both Travis CI and …

Add Windows build badge and clarify others

---

winbuild/build.py
winbuild/build_dep.py
winbuild/config.py

Webp is now built and recognized with all the compilers in the matrix. 
* Remove multithreading from build.py script to fix race condition
* Fix webp build script to find the libraries when compiled on x86.

Windows build tweaks

---

Tk/README.rst
Tk/tkImaging.c

Tcl/Tk 8.4.0 was released on September 18, 2000. I presume it is now past the stage where earlier versions need to be supported.

Removed support for Tk versions earlier than 8.4

---

winbuild/build.py
winbuild/build_dep.py
winbuild/config.py

- lcms2 except for Python2.7 64.
- tk for Python 2.7, 3.4 is not recognized yet (but the libraries are available)

Winbuild updates

---

CHANGES.rst

Credit where it's due. I may have finished off the change, but I wasn't the one who started it.

Updated changes

---

Scripts/gifmaker.py

The gifmaker script has a very close copy of the ImageSequence class. This removes that duplicate code, and imports it instead.
This also fixes a Python 3 bug.

Remove duplicate code in gifmaker script

---

README.rst

[wiredfool/pillow-b17vj](https://ci.appveyor.com/project/wiredfool/pillow-b17vj) appears to have been discontinued, so this switches the badge over to [Pythonpillow/pillow](https://ci.appveyor.com/project/Pythonpillow/pillow)

Update Windows badge [ci skip]

---

PIL/Image.py
Tests/test_image.py

As per the suggestion in #1279
This adds width and height properties to Image, so that in addition to `im.size`, users can also call `im.width` and `im.height`

Added width and height properties

---

tox.ini

Resolves #1307
`Tests/run.py` has been removed. The documentation lists either `test_installed.py` or `Tests/test_*.py`. Tox does not accept the wildcard format, so `test_installed.py` is the solution.

Fixed tox test script path

---

Tests/test_image_toqimage.py

```
ERROR: TestToQImage.test_sanity
----------------------------------------------------------------------
File "Tests\test_image_toqimage.py", line 22, in test_sanity
tempfile = self.tempfile('temp_{}.png'.format(mode))
ValueError: zero length field name in format
----------------------------------------------------------------------
```

TST: fix ValueError on Python 2.6

---

PIL/FliImagePlugin.py
PIL/GifImagePlugin.py
Tests/test_file_dcx.py
Tests/test_file_fli.py
Tests/test_file_gif.py
Tests/test_file_im.py
Tests/test_file_mpo.py
Tests/test_file_psd.py
Tests/test_file_tiff.py

When some formats seek to a non-existent frame and raise EOFError, tell() then reports the non-existent frame position.
A side effect of this is n_frames reporting an incorrect value.
I've added tests for other formats, except for SPIDER. This is because the test file matches the condition `self.istack == 0` on [this line](https://github.com/python-pillow/Pillow/blob/master/PIL/SpiderImagePlugin.py#L169) which means that seek has no effect.

Frame position when seeking past the end of file

---

.travis.yml

Run `check-manifest` after the tests. Anything missing will cause a build failure. This'll help avoid having to fix up MANIFEST.in right before each release.
Closes #1313.
(Replaces PR https://github.com/python-pillow/Pillow/pull/1314)

Check manifest on Travis CI

---

PIL/GifImagePlugin.py
PIL/Image.py
Scripts/gifmaker.py
Tests/test_file_gif.py

Resolves #1271
This is the first step in saving multiframe images (#733), by merging the functionality of the gifmaker script into GifImagePlugin.
Happy to accept other ideas about how to do `save_all`. In this pull request, I'm imagining `im.save('test.gif', save_all=True)`

Merged gifmaker into GifImagePlugin

---

docs/handbook/image-file-formats.rst

- missing closing brackt
- EOFError mentioned

gif doc improved

---

PIL/Image.py

Minor cleanup. The original code was EAFP, but the effect of that structure was some duplicate lines.

Rearranged format handler fetching

---

PIL/Image.py
PIL/ImageFile.py
PIL/PcxImagePlugin.py
PIL/PngImagePlugin.py
PIL/PyAccess.py
PIL/TiffImagePlugin.py
Scripts/pilfile.py
Scripts/player.py
Tests/test_file_libtiff.py
Tests/test_file_tiff.py
Tests/test_imagesequence.py

cf. #1191, #1205 (recreated because I apparently can't reopen the previous PR).
Only TiffImagePlugin and OLEFileIO still rely on (their own) DEBUG flag.
I left TiffImagePlugin as it is because I hope #1059 gets merged in
first, and OLEFileIO because it uses its own logic.

Use logging instead of print.

---

Tests/test_imagefont.py

Brings ImageFont.py coverage up from 83% to 87%.
Helps towards https://github.com/python-pillow/Pillow/issues/722.

More ImageFont tests

---

appveyor.yml

Fail fast: All build jobs are run, but if one fails, immediately report the whole build as a failure.

AppVeyor: Report failures sooner

---

RELEASING.md
appveyor.yml

There's a version number in appveyor.yml we should remember to update.
It's used for numbering the builds here:
https://ci.appveyor.com/project/Pythonpillow/pillow/
(Should RELEASING.md be a bit more consistent with the 2.9.x, 2.9.0, 2.9.1, 2.5.x, 2.5.3 examples?)

Update AppVeyor build number

---

setup.py

Minor change. Since support for Tcl 8.4 has been removed, this updates the example version numbers in setup.py

Updated example Tcl version numbers

---

README.rst

coveralls.io displays a warning -
`We detected this repo isn’t badged! Grab the embed code to the right, add it to your repo to show off your code coverage, and when the badge is live hit the refresh button to remove this message.`
The only difference is adding `&service=github` to the image URL.

Added service argument to coveralls image URL

---

Tests/test_file_tiff.py

To potentially offset the drop in coverage from #1343, here are some additional tests for TiffImagePlugin.

Added additional tests for TiffImagePlugin

---

.landscape.yaml

Our standard is to use a max-line-length of 80, as is the default for flake8. However, on our current medium strictness setting, landscape.io has a max-line-length of 160 - https://docs.landscape.io/configuration.html. This changes the setting to 80.

Set landscape max-line-length

---

Tests/test_file_gif.py

It looks like that test was working not as expected, it was checking input data instead of output file.

Fixing typo to have proper testing

---

PIL/EpsImagePlugin.py
PIL/ImageFile.py
PIL/PSDraw.py
Tests/test_psdraw.py

If no file pointer is provided, PSDraw uses `sys.stdout`. This causes some bugs in Python 3.
To demonstrate, I've added a test.

Fixed PSDraw stdout Python 3 compatibility

---

PIL/CurImagePlugin.py
PIL/DcxImagePlugin.py
PIL/FliImagePlugin.py
PIL/GbrImagePlugin.py
PIL/IcnsImagePlugin.py
PIL/IcoImagePlugin.py
PIL/ImImagePlugin.py
PIL/IptcImagePlugin.py
PIL/Jpeg2KImagePlugin.py
PIL/JpegImagePlugin.py
PIL/MicImagePlugin.py
PIL/MpegImagePlugin.py
PIL/MpoImagePlugin.py
PIL/MspImagePlugin.py
PIL/PcdImagePlugin.py
PIL/PcxImagePlugin.py
PIL/PngImagePlugin.py
PIL/PpmImagePlugin.py
PIL/PsdImagePlugin.py
PIL/SgiImagePlugin.py
PIL/SpiderImagePlugin.py
PIL/SunImagePlugin.py
PIL/TgaImagePlugin.py
PIL/TiffImagePlugin.py
PIL/WebPImagePlugin.py
PIL/XbmImagePlugin.py
PIL/XpmImagePlugin.py

When the format plugins call `Image.register_*`, they need to pass in the format type.
[Some formats](https://github.com/python-pillow/Pillow/blob/master/PIL/TiffImagePlugin.py#L1265) simply have the format retyped, but [others](https://github.com/python-pillow/Pillow/blob/master/PIL/GifImagePlugin.py#L643) call the refer to the format property of the plugin's ImageFile class.
This PR changes the plugins to refer to the format property in the register methods wherever possible, to avoid duplicating the format.

Changed register calls to use format property

---

PIL/Image.py
Tests/test_image.py

Added support for pathlib Path objects to open and save

---

PIL/Image.py
Tests/test_image_rotate.py
_imaging.c

Resolves #1369 
If certain filters are used, for 90 or 270 degree rotation operations, a faster algorithm is used. However, these faster algorithms ignore the expand option.
So this creates a change so that those fast operations are only used if the expand flag is in use, or if the image is square.

Fix fast rotate operations

---

.travis.yml

I noticed Travis CI now supports nightly and dev releases of Python:
> **Nightly build support**
> Travis CI supports a special version name `nightly`, which points to a recent development version of CPython build.
> **On-demand installations**
> For a limited number of Python development releases, on-demand installation is available.
> Currently, these are: 3.5.0b2, 3.5.0b3, and 3.5-dev (built nightly).
http://docs.travis-ci.com/user/languages/python/#Nightly-build-support
Right now, `nightly` is Python 3.6.0a0. I'd suggest the 3.5 betas aren't as useful as `3.5-dev`, but let's include `3.5-dev` and `nightly`. It could help us identify breaking changes in new Python versions before main releases. Of course, we don't want them to actually break our builds, so they are in the …

Test on Python 3.5 dev and 3.6 nightly

---

.travis.yml

The Travis CI Python 3.6 build fails with -
`AttributeError: module 'inspect' has no attribute 'getargspec'`
This is a known issue with coverage - https://bitbucket.org/ned/coveragepy/issues/391. It has been fixed, but presumably won't take effect at least until 4.0, whenever that is released.
Until then, to make Travis CI Python 3.6 builds more meaningful, this change disables the coverage script for `nightly`

Disabled Travis coverage script for nightly

---

docs/handbook/tutorial.rst

Using an RGBA image as its own mask is a common question.  It shows up in a dozen Stack Overflow questions, e.g.,  (http://stackoverflow.com/questions/5324647/how-to-merge-a-transparent-png-image-with-another-image-using-pil).    Adding a sentence to the tutorial gives people a chance of noticing this.

In tutorial of pasting images, add to mask text.

---

PIL/PpmImagePlugin.py
Tests/test_file_ppm.py

Resolves #1399
A truncated ppm file will result in an infinite loop. This PR raises a ValueError if the EOF is reached.

Fixed infinite loop on truncated file

---

setup.py

Perhaps this was the correct path in earlier versions, but now it would seem to exclude several of the scripts.

Corrected scripts path

---

libImaging/Convert.c

Disable compiler optimizations for topalette and tobilevel functions for all msvc versions

---

Tests/test_image_quantize.py
_imaging.c

Resolves #1377 
https://github.com/python-pillow/Pillow/commit/c8ce29c23903b5145ed0e1a23804e7e99faa5eb8 "gets the putdata test case to run correctly under 2.6/2.7. It fixes an
issue where the value 0xFFFFFFFF (which is long in old Python) isn't
recognized and putdata tries to parse it as a tuple."
However, it only fixed it for a specific portion of the code, not for 1 band images, or Int32 or Special image types.
This generalises that the code change from that commit.

Improved handling of getink color

---

setup.py

This is a simple patch that enables Pillow to build cleanly from Pypi on Solaris/SmartOS

Fix setup.py for Solaris/SmartOS

---

PIL/Image.py
_imaging.c

* Fixes documentation complaint in http://engineering.khanacademy.org/posts/making-thumbnails-fast.htm from @wchargin that has made it from PIL through all of the releases of Pillow. 
* Fixes formatting of convert_matrix in _imaging.c so that the indentation actually matches the code flow.

Correct convert matrix docs

---

PIL/GifImagePlugin.py
Tests/test_file_gif.py
docs/handbook/image-file-formats.rst

Train of thought started by #1355. Combines PR #1378 and #1379
GifImagePlugin currently uses only the params passed directly into Image's `save` method. It doesn't retrieve any params from the image itself. It effectively does not roundtrip properties. The reason that this has gone unnoticed is that `duration` and `loop` have only started to be saved recently, there is no test to roundtrip `transparency` that I can see, `version` has been fixed when saving and `background` is the one exception to this rule.
So this PR merges the params passed in with those of the image itself, with the parameters passed in having priority.
***
The second part of this is the GIF version. GifImagePlugin has the output version number fixed as 87a, but may use features that are only valid for 89a. …

GIF parameters

---

docs/plugins.rst

Fixed a few sphinx build warnings.  Now the only warnings are for docs that aren't linked from any of the TOCs.

Fix sphinx build warnings

---

PIL/Image.py
PIL/PyAccess.py

When converting to the logging infrastructure, these logs were enabled (when previously commented out) at the default debugging level.
* The inner code of Image._open_core is designed to fail over and over until one of the image formats matches. When there is an actual error in a test, it's totally buried in thousands of lines of extraneous errors. 
* PyAccess debugging is low level debugging only useful for hacking on PyAccess. It's not of general interest, and It also shows up in totally extraneous contexts, since it's hit on module load. 
e.g.: 
```
FAIL: Test writing arbitrary metadata into the tiff image directory
----------------------------------------------------------------------
Traceback (most recent call …
```

Removing spammy debug logging

---

.travis.yml

> The latest version is coverage.py 4.0, released 20 September 2015. It is supported on Python versions 2.6, 2.7, 3.3, 3.4, and 3.5, as well as PyPy 2.4 and 2.6, and PyPy3 2.4.
https://coverage.readthedocs.org/en/latest/
3.7.1:
> Coverage.py runs on Pythons 2.3 through 3.3, and PyPy 1.9.
https://pypi.python.org/pypi/coverage/3.7.1
From the Coveralls issue tracker:
> Coverage.py 4.0 no longer supports Python 3.2. Keep using version 3.7.1 on Python 3.2. ... ython 3.2 doesn't support u"" strings, which makes it difficult to get Unicode right across a wide span of versions. You can pip installs 3.7.1 by pinning that version number in your requirements.
https://bitbucket.org/ned/coveragepy/issues/407/coverage-failing-on-python-325-using

Coveralls 4.0 doesn't support Python 3.2

---

.travis.yml

Pyroma has started timing out on Python 2.6 two days ago. Skip it.
Examples:
* https://travis-ci.org/python-pillow/Pillow/builds/81346086
* https://travis-ci.org/python-pillow/Pillow/builds/81256118
* https://travis-ci.org/python-pillow/Pillow/builds/81583748
(This was the last working one:
* https://travis-ci.org/python-pillow/Pillow/builds/81247414 )

Skip Pyroma on Python 2.6

---

docs/installation.rst
setup.py

It's now 2015, and imaging libraries should, by default, support jpeg and png. If the user doesn't want them, they need to be explicitly disabled. 
This should reduce the number of questions that ask why something isn't working, only to find that none of the external libraries were compiled into pillow. 
Following the resoundingly quiet discussion of #1412.

Require zlib and libjpeg

---

Scripts/diffcover-install.sh

The diff-cover repository has moved, as reported in the README here - https://github.com/edx/diff-cover

Updated repository URL

---

docs/reference/ImageGrab.rst

Re: https://pillow.readthedocs.org/en/latest/reference/ImageGrab.html
It'd be good to mention when exactly OS X support was added for `ImageGrab`To try and avoid confusion like http://stackoverflow.com/q/32799143/724176
Is this the best way to do it?

Docs: Mention when OS X support was added

---

CHANGES.rst
Makefile
README.rst

- Add Makefile target ``make readme`` to run ``viewdoc``
- Reorg "More Info" sections
- Docs to the top
- Less doc links (folks can find more than installation & guides from documentation link)
- Add link to PRs
- Reorg link to pre-fork changes

README fixes [ci skip]

---

PIL/ImageQt.py

Fixes various TestFromQImage failures on Python 3.x

Py3 fixes for ImageQt.align8to32

---

CHANGES.rst
PIL/EpsImagePlugin.py
PIL/IcnsImagePlugin.py
PIL/ImageFile.py
PIL/PalmImagePlugin.py
PIL/PdfImagePlugin.py
PIL/PngImagePlugin.py
PIL/TiffImagePlugin.py

Some file-like objects (example, on which we ran into this issue, is ``Gridfs.GridOut``) does not have a ``flush`` method.

Check flush method existence for file-like object in tiffplugin setup

---

Tests/test_numpy.py

Some suggestions from https://github.com/python-pillow/Pillow/issues/947#issuecomment-61641247
A couple of small fixes to make tests more robust:
* The first assumed the image was square and mixed up width and height
* Second to crop the image to non-square to make sure no other assumptions are made
Closes #947.

Make tests more robust

---

README.rst

Resolves #1471
In the README section of the base repository - https://github.com/python-pillow/Pillow - the Installation and Handbook links do not work. This change fixes that issue.

Fixed README links

---

Scripts/painter.py

In addition to being helpful, this prevents an error from being generated if the script is run without the required number of arguments.

Added Usage message to painter script

---

winbuild/get_pythons.py

Not all the latest Python releases at https://www.python.org/ftp/python/ have .msi files, but these do.

Windows build: Update Pythons to latest with .msi

---

PIL/Image.py

Reqorded Pr #1470

---

PIL/Image.py

Every time I try to get in-memory PNG or JPEG data I tend to spend half an hour fighting with tobytes until I remember it is not going to work and I'm supposed to use `im.save(fp, format='png')`.
#985 makes me think I'm not alone, and a clear warning in the documentation can only help others (and future-me).
I don't actually know what tobytes is for, so I went with something along the lines of @wiredfool's comment in #985, they note that it's
>  only used for a couple very close to raw formats

Warn that tobytes is not for compressed image data

---

docs/installation.rst

* Reorg the installation docs so that there's Install and Build sections. 
* Reference xcode and the pip cache in the appropriate sections
* Reference the `depends` scripts
ping #1461, #1275

installation docs reorg

---

PIL/ImageGrab.py
_imaging.c
setup.py

`git log -- _imagingtiff.c` (and `git log -1 -- _imagingtiff.c` should show when it was deleted, but I don't get anything when I run it.
I also don't see the file in any of the PIL 1.1.1 to 1.1.7 releases: https://github.com/hugovk/PIL/commits/master
Fixes #1498.

Remove old _imagingtiff.c stuff from setup.py

---

CHANGES.rst

The following URL - http://bitbucket.org/effbot/pil-2009-raclette/changesets/ - tries to redirect to - https://bitbucket.org/effbot/pil-2009-raclette/commits/all/ - except that the trailing slash causes the URL to fail.
So this change is just skipping the BitBucket's incorrect redirect.

Corrected outdated URL

---

CONTRIBUTING.md

At some point in the past, I made a PR where I changed a docstring with a `[ci skip]`. This was merged because it looked trivial, but it turned out that I had actually made an indentation change that broke the script.
The point is - contributions using `[ci skip]` need to be documentation changes, not trivial ones.

Documentation contributions

---

Tests/test_image_point.py

Considering that the bug is no longer open - https://bitbucket.org/pypy/pypy/issues/1779/impoint-4000x-slower-than-cpython - and the test is no longer skipped, this comment is outdated and can be removed.

Removed comment

---

docs/build.rst
docs/reference/ImageGrab.rst

When running `make html` in the `docs` directory, Sphinx generates the following warnings -
Pillow/docs/build.rst:14: WARNING: Title underline too short.
Prerequisites
------------
Pillow/docs/reference/ImageGrab.rst:5: WARNING: Title underline too short.
:py:mod:`ImageGrab` Module (OS X and Windows only)
=========================================
This fixes these warnings.

Fixed length of title underlines

---

.travis.yml

Workaround to close https://github.com/python-pillow/Pillow/issues/1571.
Adding `sudo apt-get update` before installing fixes it.
[Travis say](https://github.com/travis-ci/travis-ci/issues/5221#issuecomment-162256556):
> The apt lists are currently being wiped at the end of the image-baking process, although this step was added prior to GCE and the space savings aren't as big of a deal on GCE, so I can see leaving the apt lists in place as a decent fix.
If they leave the lists in place we can remove this later, but it only takes about 10s to do the updates.

Travis CI: sudo apt-get update

---

PIL/TiffTags.py
Tests/test_file_tiff.py

According to http://www.awaresystems.be/imaging/tiff/tifftags/extrasamples.html, this tag should be a short, not a byte. Seems to be a regression from the TIFF metadata rewrite in 3.0.0. See #1524 (only affects RGBA and RGBX formats, which are the only formats that try to write the ExtraSamples tag).

ExtraSamples tag should be a SHORT, not a BYTE

---

Tk/tkImaging.c

`atol` returns a 32 bit C long on win-amd64.
Fixes #1549

Fix crash in ImageTk.PhotoImage on win-amd64

---

PIL/ImageQt.py

Alternative to PR #1558, as a fix for Issue #1557
This PR uses `from PIL import Image` rather than the `import PIL.Image` in #1558, simply for consistency, as that is what is used elsewhere.

Changed ImageQt import of Image

---

PIL/EpsImagePlugin.py
Tests/test_file_eps.py

When attempting to work with an eps file, ghostscript fails to run. For example, this happens when trying to open and resize an eps image:
```python
image = Image.open("somefile.eps")
newSize = (targetWidth, targetHeight)
print "Resizing to {}...".format(newSize)
image.resize(newSize)  <-- gs fails here
```
This PR seems to fix the problem by dividing a couple of the parameters to the gs command into separate array elements.

Fix command to invoke ghostscript for eps files.

---

Tests/test_imagedraw.py

I presume that this FIXME is not referring to the test itself, but to the `arc` method.
Since the general attitude here is not to change APIs unnecessarily, I figure that this can be removed.

Removed FIXME from ImageDraw test

---

PIL/Image.py
PIL/ImageDraw.py
PIL/ImageFont.py

Five files in the repository import `warnings`. Two of them check that there isn't an ImportError when doing so.
I'm not sure why there is a check, since it is a standard Python module as far as I can see. However, since three files work without it, I presume it is unnecessary.

Removed warnings check

---

PIL/WalImageFile.py

The file that it is referring to does not exist within this repository.

Removed __main__ code from WalImageFile

---

PIL/ImageFile.py

In Issue #1550, it is reported that Python 2 prints 'No handlers could be found for logger "PIL.ImageFile"'.
In PR #1588, it is argued that this exception should be removed.

Removed logger exception

---

PIL/JpegPresets.py
PIL/WalImageFile.py
docs/build.rst
docs/reference/ImagePath.rst

Some fixes for things found when running `cd docs && make linkcheck`.
---
The output of the command *after* these fixes is:
```bash
$ make linkcheck
sphinx-build -b linkcheck -d _build/doctrees   . _build/linkcheck
Running Sphinx v1.3.3
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [linkcheck]: targets for 44 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] reference/index                                                                                              
/Users/hugo/github/Pillow/docs/reference/index.rst:4: WARNING: toctree contains reference to nonexisting document u'reference/TiffTags'
looking for now-outdated files... none found
pickling environment... …
```

'make linkcheck' fixes

---

CHANGES.rst
PIL/Image.py
Tests/test_numpy.py

Added an HSV entry in the conversion table in Image.py. Analogous to RGB it contains unsigned ints, and the dimensions for each entry are 3 values.
Added an HSV entry in the respective test.
Resolves #1559 .

Enabled conversion to numpy array for HSV images. #1559

---

PIL/TiffImagePlugin.py
Tests/test_file_libtiff.py

TiffImagePlugin incorrectly strips RowsPerStrip from the metadata prior to saving with libtiff. This fixes #1561.

Allow saving RowsPerStrip with libtiff. 

---

Tests/test_file_tiff.py
Tests/test_file_tiff_metadata.py

When running these tests, I get `DeprecationWarning: Please use assertTrue instead.`
These are the changes from #1582 that pass without issue.

Updated deprecated asserts

---

Tests/test_scipy.py

I feel like it's ambiguous whether the original form of this comment refers to Pillow 2.6 or scipy 2.6.
The fact that there isn't a scipy 2.6 helps, but I thought I'd clarify.

Clarified comment

---

docs/installation.rst

- libjpeg is now up to 9a. I, along with others, would have been testing against it for a while.
- LittleCMS2 is now up to 2.7.
- LibWebP 0.5 was just released. I presume that it also supports transparency.

Updated installation docs

---

setup.py

The install was failing on FreeBSD because shared libraries and includes were not found.
On FreeBSD, shared libraries and includes are installed in `/usr/local/lib` and `/usr/local/include`.
The `libjpeg-turbo` files are in these directories but `setup.py` was not aware of this.
So the install was failing with the output:
running install
running bdist_egg
running egg_info
creating Pillow.egg-info
writing Pillow.egg-info/PKG-INFO
writing dependency_links to Pillow.egg-info/dependency_links.txt
writing top-level names to Pillow.egg-info/top_level.txt
writing manifest file 'Pillow.egg-info/SOURCES.txt'
reading manifest file 'Pillow.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'Pillow.egg-info/SOURCES.txt'
installing library code to …

add include and library directories for freebsd

---

docs/handbook/image-file-formats.rst

In #1185, ICNS save was added for OS X only.
By my count, there are 34 formats listed as supporting read in `docs/handbook/image-file-formats.rst`
- BMP
- EPS
- GIF
- IM
- JPEG / JPEG 2000
- MSP
- PCX
- PNG
- PPM
- SPIDER
- TIFF
- WebP
- XBM
- XV Thumbnails
- CUR
- DCX
- FLI, FLC
- FPX
- GBR
- GD
- ICO
- ICNS
- IMT
- IPTC/NAA
- MCIDAS
- MIC
- MPO
- PCD
- PSD
- SGI
- TGA
- WAL
- XPM
- PIXAR

Updated documentation

---

PIL/TiffImagePlugin.py
PIL/TiffTags.py
Tests/test_file_tiff.py
Tests/test_file_tiff_metadata.py
Tests/test_tiff_ifdrational.py
docs/handbook/image-file-formats.rst

Not quite complete version of #1492 which preserves the semantics of 0/0 when that's what's actually in the file. It passes the existing test suite, with the exception of python 2.6.
Please try this PR and let me know if it works for your use case.

Divide by zero in Exif

---

PIL/ImageDraw.py

The default spacing for `multiline_text` was changed to 4 in PR #1574
This changes the default spacing for `multiline_textsize` to be consistent with that.

Updated spacing to be consistent between multiline methods

---

.editorconfig

EditorConfig is built in to several popular editors, and many others have a plugin. It lets you define some simple common code standard things regarding text formatting and takes care of them automatically in the editor.
Get your plugin here: http://editorconfig.org

Let EditorConfig take care of some basic formatting

---

PIL/JpegImagePlugin.py
Tests/test_file_jpeg.py

More complete version of #1619, rolling back all exif support to be compatible with 2.9 and prior.

Rolling back exif support to pre-3.0 format

---

Tests/test_image_getim.py
Tests/test_imagewin_pointers.py

These two tests now succeed on Py2.6 on Windows.

Fixing test failures on python 2.6/windows

---

encode.c

The conditional
(!PyType_Ready(&ImagingEncoderType) < 0)
will always be false. This commit fixes this, also silencing the compiler warning
encode.c: In function 'PyImaging_EncoderNew':
encode.c:57:43: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
if(!PyType_Ready(&ImagingEncoderType) < 0)

Fix incorrect conditional

---

.travis.yml

Install pillow before running sphinx

---

Tests/test_file_tiff.py

A test to throw the error at https://github.com/python-pillow/Pillow/blob/master/PIL/TiffImagePlugin.py#L426

Added TIFF IFD test

---

PIL/ImageDraw.py
Tests/test_imagefont.py
docs/reference/ImageDraw.rst

Allowed text method to pass on multiline_text method specific arguments

---

PIL/Image.py

When calling `alpha_composite(im1, im2)`, both images must be of mode RGBA
- An error is thrown at https://github.com/python-pillow/Pillow/blob/master/libImaging/AlphaComposite.c#L36 if the mode of the first image is not RGBA.
- The modes of the two images must also match, or an error will be thrown at https://github.com/python-pillow/Pillow/blob/master/libImaging/AlphaComposite.c#L43
It is #1695 that points out that the documentation could be improved.

Improved alpha_composite documentation

---

winbuild/README.md

@wiredfool should feel free to correct me, but I would think that Python 3.3 is actually tested on AppVeyor.
The simplest explanation is that this documentation was written before 3.3 testing was setup there.

Corrected AppVeyor testing status documentation

---

docs/installation.rst

I have retested all of the listed Python versions with Pillow 3.1.0.

Updated El Capitan tested Pillow version

---

Tests/test_image_resample.py
_imaging.c
libImaging/Resample.c

Overflow in resample.c, with tests

---

PIL/Image.py

Image.py has a comment - 'see docs/porting-pil-to-pillow.rst'
The filename is 'porting.rst'

Corrected documentation reference

---

setup.py

Sends the correct error when faced with a condition like #1763
Hard to test on travis -- but:
```
(vpy27)erics@builder-1204-x64:~/Pillow$ sudo mv /usr/include/zlib.h /usr/include/zlib.h-disabled
[sudo] password for erics: 
(vpy27)erics@builder-1204-x64:~/Pillow$ make clean && make install
python setup.py clean
running clean
removing 'build/temp.linux-x86_64-2.7' (and everything under it)
rm PIL/*.so || true
rm: cannot remove `PIL/*.so': No such file or directory
rm -r build || true
find . -name __pycache__ | xargs rm -r || true
rm: missing operand
Try `rm --help' for more information.
python setup.py build_ext install
running build_ext
File "setup.py", line 768, in <module>
zip_safe=not debug_build(),
File "/usr/lib/python2.7/distutils/core.py", line …
```

Fix the error reported when libz is not found

---

PIL/Image.py

Apparently recent some OSX pythons are compiled with wide characters, and they're returning a different missing symbol. This catches that symbol, as well as likely any others that would trigger the same error.

Provide a more general error check to catch #1753

---

PIL/Image.py
_imaging.c

We're getting a warning that we're using an uninitialized variable, and it appears that it can lead to logic errors, and it not, it's really confusing c code. 
* fixes the uninitialized variable issue
* Clarifies the flow of control in the getink method
* Fixes a case where we're passing a 3-tuple into putpixel in a 'P' mode image.
There are still some issues, as if we return NULL out of the function without setting a Python Exception, then we're going to cause an error higher up in the stack.

Fixes uninitialized variable warning in _imaging.c:getink

---

PIL/Image.py
Tests/test_image_crop.py

Round the x0, y0, x1, y1 box arguments to the nearest integer before cropping. 
This is what ImageMagick does.
Fixes #1744.

Round crop's arguments to nearest integers

---

PIL/Image.py
Tests/test_image.py

Fixed bug when saving to a non-existent path using pathlib

---

PIL/JpegPresets.py

Throwing this idea out there - http://www.jpegcameras.com/libjpeg/libjpeg-3.html no longer works as a URL, so I thought I'd replace it with a link to the Wayback Machine version.

Changed no longer found URL to archive URL

---

RELEASING.md

I feel like this version is clearer.
Also, if the current 3.1.x branch is anything to go by, branches are typically named along the lines of 3.1.x, rather than 3.0.0.

Clarified documentation

---

setup.py

I know folks don't universally agree on using yapf, but I've been using it a lot lately elsewhere & propose we start using it on a file-by-file basis here.

yapf-formatting for setup.py

---

Tests/test_imagepath.py
path.c

This issue was found by @nedwill .  Thanks for the notification and the test case. 
In all versions of Pillow and at least in PIL 1.1.7, there is a possibility for integer overflow in a malloc in path.c which can lead lead to memory corruption or a segfault. This does not appear to be a remote code execution bug, as this is triggered by python code, not a loaded image which would be attacker controlled. 
This patch checks the size calculation for overflow prior to the malloc, and returns a memory error if there is an overflow. 
ref #1715

Fix for integer overflow in path.c

---

docs/handbook/image-file-formats.rst

This might be less black-and-white than I think, but the docs list `icc-profile` as a JPEG argument, rather than `icc_profile`.
The same doc provides a sample line of code that demonstrates it's usage as `icc_profile` - `im.save(filename, 'jpeg', icc_profile=im.info.get('icc_profile'))`

Changed documented name of JPEG property

---

PIL/TiffTags.py

Using https://partners.adobe.com/public/developer/en/tiff/TIFF6.pdf as a reference.

Corrected Tiff tag names

---

PIL/OleFileIO-README.md

So that it is consistent with the main LICENSE file.

Updated PIL license in OleFileIO README

---

PIL/Image.py
Tests/test_image_copy.py

Added __copy__ method to Image

---

PIL/SpiderImagePlugin.py
Tests/test_file_spider.py

Copy of PR #1741, with a test added.
Using ImageSequence.Iterator on a non-stack SPIDER image leads to infinite loop.
EOFError (which stops the iteration) is never raised because when the image isn't
a stack, seek() returns gently without error.

SpiderImagePlugin: raise an error when seeking in a non-stack file

---

PIL/PngImagePlugin.py
Tests/test_file_png.py

Convert to SyntaxErrors. fixes #1755

Catch struct.errors when verifying png files

---

.travis.yml
Makefile

Installed the requirements, which were missing after a reorg. 
Also, only building docs on python 2.7 to get our CI runs to complete faster.

Fix docs building on travis

---

docs/installation.rst
setup.py

So, I'm trying to track down a compile error on one of my machines and the hood came off setup.py and I nearly threw up a little. 
So. 
* Dir and file are not valid variable names. 
* We were accepting --enable-want and such as valid flags due to sloppy metaprogramming.
* Debug logging is added, not using the logger, since we're spewing stuff to the console anyway. 
Some continuing WTFs:
* ~~We're not actually checking for the tiff or freetype headers.  ~~
* ~~It's not finding libopenjp2 on my machine, and searching for the libraries is something that's down in the compiler. Which sucks. ~~ -- It was looking for openjp2_d.so. 
The debug logging isn't complete, and it's still not answering my compile question. Comments welcome. 
Fixes #679

Setup cleanup

---

Tests/test_file_iptc.py

It was added as part of https://github.com/python-pillow/Pillow/pull/832/commits/4c5a5c1f0eddef0d384f18d46657c92e954b5075 on #832, but then removed as part of https://github.com/python-pillow/Pillow/pull/832/commits/a0aff1a87faa72373010d0e5c71667c7dcc34e19 on that same PR.

Removed unused test helper

---

docs/installation.rst

`zlib-devel` is needed, but not `libzip-devel`.

Fix Fedora prerequisites in installation docs

---

Makefile
PIL/OleFileIO.py
docs/handbook/concepts.rst
docs/reference/ImageMath.rst

Runs the docs linkcheck, but doesn't fail it if one of the remote docs isn't responding within the short timeout. 
Also fixes keyword and term warnings, and updates the links in OleFileIO.    (Should they change upstream, I'll manually merge them)

Fix Docs failures. 

---

PIL/JpegImagePlugin.py
Tests/test_file_jpeg.py

fixed issue from using signed char instead of unsigned char. added test

Valid range for baseline jpeg qtables 0 to 255

---

.github/CONTRIBUTING.md
README.rst
Tests/test_psdraw.py
docs/index.rst
setup.py

https://blog.readthedocs.com/securing-subdomains/
> **Securing Subdomains** 
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
> Changes to provide security against broader threats have been in place for a while, however there are still a few scenarios that can only be addressed by migrating to a separate domain.
> We implemented session hijacking detection and took precautions to limit cookie usage, but there are still a number of scenarios utilizing XSS and CSRF attacks that we aren’t able to protect against while hosting documentation from subdomains on the …

Update to RTD.io links

---

.github/CONTRIBUTING.md

Since CONTRIBUTING.md was moved into .github, this link needs to be updated.

Corrected link

---

PIL/ImageFile.py

Hello, here's a pull request to mmap images in read-only mode. I tested it on linux, but the patch is cross-platform. BTW, my use case was an infinite loop caused by using PIL with inotify. I monitored new images with inotify CLOSE_WRITE event, then opened it with PIL. Since PIL opened the image in write mode, I received another CLOSE_WRITE event.
The code path for mmapped files unnecessarily loaded images in
read-write mode and had a long standing FIXME message. This patch
uses mmap.ACCESS_READ, which is platform independent to fix this
issue.

Make ImageFile load images in read-only mode

---

docs/installation.rst
setup.py

Includes a bit of a refactor of #1861 + docs.

Disable-platform-guessing in setup.py

---

setup.py

Removes the theoretical need to escape the path argument.

Replaced os.system with subprocess.call

---

PIL/Image.py

In the file Image.py.
This will not affect users who already catch the "Exception" type since it is a base class of "NotImplementedError".

Deprecated function will no longer raise "Exception" but "NotImplementedError".

---

Tests/test_imagecms.py

Applied patch from #1887. Thanks @doko42

Skip test when icc profile is not available, fixes #1887

---

winbuild/build.py

We were suppressing stdout in the appveyor builds, it's useful for debugging when windows builds fail. (re: #1881)

Print stdout in appveyor logs

---

PIL/TiffTags.py

Regarding 'RBG Palette' vs 'RGB Palette', see page 117 of https://partners.adobe.com/public/developer/en/tiff/TIFF6.pdf

Fixed typo

---

PIL/Image.py

This code has been there since the forking of PIL. It's function is to read in a list form of the info attribute, rather than the current dictionary form.
While the person who wrote this would have had a reason, I can't imagine under what circumstances Pillow would be interacting with an object like that. If others think that it should be kept, I would then suggest adding a warning.

Removed support for list form of Image info

---

PIL/GifImagePlugin.py
Tests/test_file_gif.py

Added support for GIF comment extension

---

_imagingcms.c

Fixes https://github.com/python-pillow/Pillow/issues/1850
---
https://github.com/python-pillow/Pillow/issues/1850#issuecomment-218428866:
> We figured out what the real problem is. What happens is:
> First will `wchar.h`be included which will pull in `string.h` without `_GNU_SOURCE` set. Later will `Python.h` explicitly set `_GNU_SOURCE` (via `pyconfig.h`) and after that is `string.h`pulled in again but this time with `_GNU_SOURCE` set.
> This (rightfully) confuses the fortify-headers. You cannot really include some system headers with without _GNU_SOURCE and some with. It will cause problem.
> Either `Python.h` should not set `_GNU_SOURCE` (eg bug in python) or it is required to be included first, before any system headers, (eg bug is in Pillow). Workaround/fix is trivial:
````diff
diff …
```

Include Python.h before wchar.h so _GNU_SOURCE is set consistently

---

PIL/JpegImagePlugin.py
Tests/test_file_jpeg.py
libImaging/JpegEncode.c

Found edge cases with custom qtables  …
And there was a lingering bug since the previous qtable unsigned char fix
(#1814) since the call to array.array was in another place, the roundtrip was no
longer equivalent.
That was a minor change, but the revised test wouldn't pass because saving an image
with one custom qtable automatically adds a second to it by the call to
jpeg_set_defaults.
With 1 or >2 custom tables, there is extra work we have to do due to that call.

More fixes related to custom jpeg qtables

---

appveyor.yml
winbuild/build.py

A couple of enhancements for appveyor:
* Commented out commands to get an RDP console on Appveyor's servers. These block, so we can't leave them in, but they can be useful to figure things out for people who don't have a windows machine they want to fire up.
* S3 deployment is only on the master branch. I'd like to make it just from python-pillow, but I don't see that in the docs. This prevents deployment failure stopping the test runs for everyone else. 
* Added wheel builds as in #1815 by @techtonik, but with a specific option for it, uploads to s3, and less intrusive changes to the build script.

Appveyor Upgrades

---

Tests/test_image_resample.py
libImaging/Resample.c

This change speeds up resampling up to 60% and eliminates ugly `i2f` hack.
Source    | Operation               | Filter  | Before | After 
----------|-------------------------|---------|--------|-------
7712×4352 | **Resize to 16x16**     | Bilinear| 210    | 330   
|                         | Bicubic | 109    | 177   
|                         | Lanczos | 73.5   | 120   
| **Resize to 320x180**   | Bilinear| 154    | 241   
|                         | Bicubic | 88.6   | 139
|                         | Lanczos | 60.4   | 96.5   
| **Resize to 2048x1155** | Bilinear| 83.9   | 105   
|                         | Bicubic | 55.3   | 75.1   
|                         | Lanczos | 38.9   | 57.3
I'll add tests for other modes and maybe return old implementation for `IMAGING_TYPE_INT32` and …

Fixed point integer resample

---

.travis.yml
PIL/Image.py
Tests/test_image_quantize.py
depends/README.rst
depends/debian_8.2.sh
depends/install_imagequant.sh
depends/ubuntu_12.04.sh
depends/ubuntu_14.04.sh
docs/installation.rst
libImaging/Quant.c
libImaging/QuantPngQuant.c
libImaging/QuantPngQuant.h
setup.py
winbuild/README.md

Implements issue #554
Manual test results:
```
Image.open("in.png").convert("RGBA").quantize(method=2).save("out.png")
```
> ![out](https://cloud.githubusercontent.com/assets/1045476/15054920/2d603010-130a-11e6-99fe-cd809e39cd42.png)
```
Image.open("in.png").convert("RGBA").quantize(method=3).save("out.png")
```
> ![out](https://cloud.githubusercontent.com/assets/1045476/15054927/38900e9c-130a-11e6-97c2-bf062d5aa91f.png)
Tested manually: `L`, `P`, `RGB` and `RGBA` mode. Tested transparent and opaque images.
Not tested animated GIFs but they should hardly matter. Not implemented the above tests in the code - the automated test I've added is based on existing quantization tests, which aren't very exhaustive.
---
I haven't done anything special to make custom palettes work, but:
1. There's …

Add libimagequant support for quantize()

---

docs/installation.rst
docs/releasenotes/3.3.0.rst
docs/releasenotes/index.rst

Notes on libimagequant:
* license
* windows (non)build
* Also release notes started for 3.3.0

Additional docs for libimagequant

---

PIL/ImageMode.py
Tests/test_image_resample.py
libImaging/Resample.c

This PR implements separate vertical pass of resampling instead of two transposes.
Originally [I've replaced](https://github.com/python-pillow/Pillow/commit/40f9f48) two passes with transpose for the following reasons:
1. It was harder to heavily change the code in two branches simultaneously.
2. It makes downscaling faster, although upscaling became slightly slower.
Since then there are many tests for resampling were written and many optimizations were implemented. Now it is time to return upscaling performance.
Result on aws ec2 c4.large with 1920×1280 RGB image. Megapixels of source image per second.
| Destination   | Filter  | 3.2    | FPI    | Vertical pass
------------|---------------|---------|--------|--------|--------------
Downscaling | **16x16**     | Bilinear| 229.31 | 381.97 …

Resample vertical pass

---

_imagingft.c
map.c

PyObject_Del() should only be called on the self object in a dealloc call, not after failing to make a new object. Replace with Py_DECREF, which eventually calls PyObject_Del()
http://bugs.python.org/issue3299#msg78740
https://mail.python.org/pipermail/python-dev/2003-February/033258.html

Fix "Fatal Python error: UNREF invalid object" in debug builds

---

PIL/Image.py
_imaging.c
libImaging/Geometry.c
libImaging/Imaging.h

Internal transform API was very confusing. For example, `rotate` method was calling `self.transform` or `self.im.rotate` depends on `expand` argument, but `self.im.rotate` internally also calls `ImagingTransformAffine`, so it was excessive.
* First of all, this PR fixes rotations bug #1917 in two ways:
* It really uses very cheap `transpose` operations if it is possible regardless of filter. https://github.com/python-pillow/Pillow/pull/1941/commits/8203a43d262d349f71bcfa3da46e5f3e30fe99e0
* It rounds coefficients in the transform matrix, so even if we are not using cheap transpose, we still get right dimensions because `cos(90°)` now is exactly 0, not 6.123e-17. https://github.com/python-pillow/Pillow/pull/1941/commits/7687ce829e50635838707f5153079fb4 …

Cleanup transforms

---

PIL/_tkinter_finder.py
Tk/_tkmini.h
Tk/tkImaging.c
_imagingtk.c
setup.py

Discover Tcl / Tk functions at run-time by looking in libs loaded by
Tkinter Python module.
Use header excerpts from Tcl / Tk so we don't need an installed Tcl / Tk
to build.

RF: run-time loading of Tcl / Tk functions

---

docs/installation.rst

This reverts commit da62f7c25b8a01a87a8e18b3a483c27927a9d1e3.

Revert "docs for new --disable-osx-tclck-frameworks option"

---

PIL/Image.py
PIL/PngImagePlugin.py
selftest.py

y = x['test']
del x['test']
can be replaced with
y = x.pop('test')
This applies to lists as well as dictionaries.

Replaced del with pop

---

PIL/Image.py

Made equals method on Image class short circuit, simpler than PR #1965 
Also placed getpalette() and tobytes() last because they are the slowest operations to make.

Changed equals method on Image so it short circuits.

---

_imaging.c
decode.c
encode.c
libImaging/Dib.c
libImaging/Draw.c
libImaging/Geometry.c
libImaging/GifEncode.c
libImaging/Imaging.h
libImaging/Incremental.c
libImaging/Jpeg2KDecode.c
libImaging/Palette.c
libImaging/Quant.c
libImaging/QuantHeap.c
libImaging/QuantOctree.c
libImaging/RankFilter.c
libImaging/Resample.c
libImaging/Storage.c
libImaging/TiffDecode.c
libImaging/ZipDecode.c
libImaging/ZipEncode.c
path.c

I'd like feedback on this. 
i think this is a good approach -- it follows the other changes that we've made to check for overflow on the mallocs. The biggest change is switching to calloc(n,size) instead of malloc(size) in some cases -- calloc does the multiplication, (is supposed to) check for overflow, and zeros the memory. I don't think that the zeroing is ever a bad thing, and there are some reports of the performance of calloc zeroing the memory faster than the memset that we use in a few places. 
i will probably rebase/squash this prior to merging.

Various checks on malloc

---

_imagingcms.c

Fixes #1973  .
* Use PyLong_FromUnsignedLongLong on all platforms to get 64bit unsigned attribute value from lcms.

Fix integer overflow on ILP32 systems (32-bit Linux).

---

depends/install_openjpeg.sh
depends/install_webp.sh

Fixes travis errors. 
* Changed urls in install_openjpeg.sh and install_webp.sh to point to the cached copies in the pillow-depends repo.

Changed urls to point to githup pillow-depends repo

---

PIL/PngImagePlugin.py
Tests/check_png_dos.py

Sometimes large text block is just large text block while the image is still valid. We can safely ignore this blocks and still read the image. Because we are losing some information, I do this only when the `LOAD_TRUNCATED_IMAGES` flag is enabled.

Ignore large text blocks in PNG if LOAD_TRUNCATED_IMAGES is enabled

---

PIL/TiffImagePlugin.py
PIL/TiffTags.py
Tests/test_file_tiff.py
Tests/test_file_tiff_metadata.py
docs/releasenotes/3.3.0.rst

Fixes #1910, #1462, #1834, #1831 .
* API change to byte type metadata to treat as a string like object, rather than a tuple of integers. j
* Tests for saving a png from a tiff image w/type binary or undefined type icc profile

Binary Tiff Metadata/ICC profile. 

---

Tests/test_imagecms.py

Fixes (partially) https://github.com/python-pillow/Pillow/issues/1859 .
* Reduce precision in some tests that seem to be failing in 32bit.
In 32bit computers(When making wheels) it was found that the
precision of the extended information in test_extended_information() was
found to be lesser than what was being tested. This commit adds a helper
function which reduces the precision using `round()` and testing the
rounded numbers rather than the original numbers.

test_imagecms: Reduce precision of extended info

---

Tests/test_image_resample.py
libImaging/Resample.c

This is a relatively rare case, but why not?
From some point of view, this breaks the consistency because resampling filter is applied to one pass and isn't for another. But Pillow already returns a copy of the image if both dimensions are the same, and there is no way to apply resampling filter to the image from python code without affecting dimension.

Do not do unnecessary passes on resizing

---

docs/installation.rst

Xcode command line tools are required.

Clarified OSX build instructions, fixes #1980

---

PIL/PngImagePlugin.py
Tests/test_file_png.py

I encountered that some PNG files could not be open with Pillow since  they have crc mismatch for iTXt chunks. 
Browsers and imagemagick can open them just fine (though imagemagick shows a warning)
libpng defines a way to set it's behavior to throw an error or warning for ancillary chunks.
So I am proposing use of `LOAD_TRUNCATED_IMAGES` to skip crc checks for ancillary chunks. No need to calculate if we're going to ignore an error.

Ability to skip crc checks for ancillary chunks

---

libImaging/Jpeg2KDecode.c

With this patch:
```
--------------------------------------------------------------------
PIL SETUP SUMMARY
--------------------------------------------------------------------
version      Pillow 3.3.0.dev0
platform     win32 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40)
[MSC v.1500 64 bit (AMD64)]
--------------------------------------------------------------------
--- JPEG support available
--- OPENJPEG (JPEG2000) support available (2.1)
--- ZLIB (PNG/ZIP) support available
*** LIBIMAGEQUANT support not available
--- LIBTIFF support available
--- FREETYPE2 support available
--- LITTLECMS2 support available
--- WEBP support available
--- WEBPMUX support available
--------------------------------------------------------------------
To add a missing option, make sure you have the …
```

Fix msvc9/10 compile error

---

PIL/Image.py
Tests/test_image_resample.py
Tests/test_image_resize.py
docs/handbook/concepts.rst
libImaging/Imaging.h
libImaging/Resample.c

This adds two new filters to `resize` method.
BOX is event faster than LINEAR because it has a smaller window (0.5) and produces very sharp images. Applicable for significant downscaling.
HAMMING costs like LINEAR, also produces very sharp images and applicable for downscaling at any range. Doesn't look good for upscaling, though.

New filters! ⭐⭐⭐

---

PIL/ImageDraw.py
PIL/ImageShow.py
PIL/ImageTransform.py

Fix documentation warnings, convert params to correct format

---

PIL/Image.py
Tests/test_image_rotate.py

This fixes image rotation in cases when `angle % 360.0 == 0` and image is not loaded yet.

Fix image loading when rotating by 0 deg

---

PIL/__init__.py

Fixes this:
```
>>> import PIL
>>> from PIL import ImageGrab
File "/usr/lib/python2.7/dist-packages/PIL/ImageGrab.py", line 22, in <module>
raise ImportError("ImageGrab is OS X and Windows only")
ImportError: ImageGrab is OS X and Windows only
>>> PIL.version
AttributeError: 'module' object has no attribute 'version'
>>> PIL.__version__
AttributeError: 'module' object has no attribute '__version__'
>>> PIL.get_version()
AttributeError: 'module' object has no attribute 'get_version'
>>> 
```

Expose Pillow package version as PIL.__version__

---

PIL/Image.py
PIL/ImageOps.py
Tests/test_imageops.py

Add the scale function to provide an easy way to expand and contract image by a certain factor given in parameter.
This function "only" calculate the target size, and call the PIL.Image.Image.resize() function.

Add a scale function to expand or contract a PIL image by a factor 

---

Tk/tkImaging.c

Tk stuff introduced a warning about compilation of new Tk code, and thence an error.   Slight rephrase of C code to fix.
Should fix
https://github.com/python-pillow/Pillow/issues/2017

FIX: fix C90 compilation error for Tcl / Tk stuff

---

docs/installation.rst

Fixes #1981 
* Added installations instructions of Pillow on Fedora Python3

Installation instructions  on Fedora Python3

---

PIL/Image.py
Tests/test_image_array.py
Tests/test_numpy.py

Numpy cannot form arrays from bits.  To convert bit images to numpy,
convert bits to bytes, using numpy.
Fixes gh-350.

BF: fix conversion of bit images to numpy arrays

---

PIL/JpegImagePlugin.py
Tests/helper.py
Tests/test_file_jpeg.py

Fixes https://github.com/python-pillow/Pillow/issues/2005

Show warning when trying to save RGBA image as JPEG

---

Tests/test_numpy.py

Fixes #2076
Just ignore the numpy tests on PyPy

Ignore PyPy numpy errors

---

PIL/FpxImagePlugin.py
PIL/Jpeg2KImagePlugin.py
Tests/test_file_jpeg2k.py

Fixes #2059 .
Also fixes fpx files, but we have no actual tests for it so,  no new tests here.

Added return for J2k (and fpx) Load to return a pixel access object

---

Tests/test_file_tiff.py
Tests/test_numpy.py

Moved tiff save / load of uint16 to test_file_tiff.
Saving a numpy generated image as a tiff will save in native endian, and comparing it to a
little endian tiff will fail on bigendian machines.

Test fix for bigendian machines

---

PIL/ImageColor.py
Tests/test_imagecolor.py

Support of [hexadecimal RGBA](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#rgba) notations.

ImageColor.getrgb hexadecimal RGBA

---

PIL/Image.py

* Allow using `pathlib.Path` for `Image.open` on Python 2.7
Although the pathlib backport for Python 2.7 may be deprecated:
https://pypi.python.org/pypi/pathlib/
It is still used by many projects. Therefore, changing to a
Try/Except pattern for checking for pathlib is not any more
obtrusive that the current >= Python 3.4 check and allows users
to use the backport without issue.

Allow pathlib.Path in Image.open on Python 2.7

---

PIL/TiffImagePlugin.py
Tests/test_file_tiff.py

Fixes #1760; see discussion there.
* Don't incorrectly set the tag type to None if it was originally missing.

Fix saving originally missing TIFF tags.

---

_imaging.c

Argument r is a PY_LONG_LONG
This fixes test failures on powerpc for "LA" images

Fix PyArg_ParseTuple format in getink()

---

PIL/GifImagePlugin.py
Tests/test_file_gif.py
docs/handbook/image-file-formats.rst

Attempt to resolve #2098
The request was to create an animated GIF from scratch. This change is a bit more general, providing a mechanism to add different images when saving a GIF. Usage is
im.save(out, save_all=True, append_images=[im1, im2, ...])
The `append_images` parameter will not be used unless `save_all` is true.
Please provide any feedback.

Added append_images parameter to GIF saving

---

PIL/JpegImagePlugin.py
Tests/test_file_jpeg.py

Fixes #2077. Alternative to PR #2084.
Uses the test suggested in the issue.

Convert DPI to ints when saving as JPEG

---

PIL/ImageFile.py

Since #1242 replaced old-style classes, this comment is now outdated.

Removed outdated comment

---

.travis.yml
CHANGES.rst
PIL/IcnsImagePlugin.py
PIL/Image.py
PIL/ImageGrab.py
README.rst
RELEASING.md
Tests/test_file_tiff.py
Tests/test_imagefont.py
Tests/test_imagegrab.py
docs/handbook/image-file-formats.rst
docs/index.rst
docs/installation.rst
docs/reference/ImageGrab.rst

Thought I'd suggest this. With the release of macOS Sierra, OS X has been renamed to macOS.

Renamed references to OS X to macOS

---

README.rst

Renamed reference to OS X to macOS

---

docs/handbook/image-file-formats.rst
docs/handbook/tutorial.rst

* The PCD `draft` method was removed in #1169
* Added note in the docs about format support for the `draft` method.
* Added an `import` statement to a docs example. Considering that there is another `import` statement there, it felt to me like it should be a bit more self-contained.

Documentation notes

---

PIL/ImageColor.py
PIL/ImageShow.py
Tests/test_file_jpeg.py
Tests/test_file_jpeg2k.py
Tests/test_file_png.py
Tests/test_imagecms.py
Tests/test_imagefont.py
setup.py

http://bugs.python.org/issue27364

Fix "invalid escape sequence" warning in Python 3.6

---

docs/COPYING

Keeping it up to date with the changes from #1793, and in sync with the rest of the LICENSE file.

Added reference to Pillow to COPYING

---

PIL/Image.py
Tests/test_image_crop.py

Fixes #1077 .
* `Image.crop` is now immediate, and returns a new image object
* All the important fields are copied over, using the _new function, including the palette
* `_ImageCrop` is now gone.
* Fixes an access violation that looks like a use after free on windows.
((probably should have release notes))

Make Image.crop an immediate operation, not lazy.

---

PIL/ImageCms.py
Tests/test_imagecms.py
_imagingcms.c

Fixes #2037 .
* Check the type of objects passed into ImageCms.ImageCmsCmsProfile.
* Added CmsProfile type to _imagingcms module. 
Note that I'm not classifying this as a security issue because it's triggered by a programming error, not an image.

Fix for ImageCms Segfault

---

PIL/GifImagePlugin.py
Tests/test_file_gif.py

Fixes #2093 .
* Only optimize a gif's palette if: 
- We have to (L mode)
- It's got less than 128 colors (otherwise, we're just padding with zeros anyway)
- It changed
- The image is smaller than 1/4 mpix. (otherwise, the potential savings is lost in the noise)
* Do it in C, using the existing conversion machinery, and some monkeying with palettes and convert.

Speed up GIF save optimization step

---

.travis.yml

The build has started failing (e.g. https://travis-ci.org/python-pillow/Pillow/jobs/164608656#L2452) due to https://github.com/eliben/pycparser/issues/147. 
Perfectly timed for release day :)
Let's temporarily work around it, we can remove this later when pycparser's fixed.
The workaround passes: https://travis-ci.org/hugovk/Pillow/builds/164623368

Work around pycparser issue failing our builds

---

PIL/Image.py
PIL/TiffImagePlugin.py
Tests/test_file_tiff.py

Fixes #733 .
* Open files for reading in addition to writing in Image.save
* Add AppendingTiffWriter to TiffImagePlugin.py (this code is from @vashek)
* Add _save_all support to TiffImagePlugin.py.
Note that the resulting multipage tiff files may be mmappable by PIL, requiring #2139 to be loaded correctly after saving.

Add TIFF save_all writer.

---

.travis.yml

Reverts PR #2143 because https://github.com/eliben/pycparser/issues/147 is now fixed.

Revert "Work around pycparser issue failing our builds"

---

PIL/Image.py
Tests/test_image.py

Fixes the broken backward compatibility introduced in #2146
I believe that this breaks is A LOT of code and the fix should be released as 3.4.1.
@aclark4life @hugovk @wiredfool

CRITICAL: Allow lists as arguments for Image.new()

---

map.c

Fixes 3.3.2, 3.4.0 test failures on build for x86 linux builds. 
(windows doesn't define SSIZE_MAX, but python defined PY_SSIZE_T_MAX, which is more exact anyway)

Check should be against PY_SSIZE_T_MAX

---

PIL/Image.py

When running python 2.x with the [`-3`](https://docs.python.org/2/using/cmdline.html#cmdoption-3) flag the following warning occurs
> .../PIL/Image.py:48: DeprecationWarning: classic int division
MAX_IMAGE_PIXELS = int(1024 * 1024 * 1024 / 4 / 3)
~~Simply changing the 4 and 3 to be floats instead eliminates the warning
and, because the result is cast, the resulting `int` stays the same for
python 2 and 3.~~ 
Using floor division eliminates the warning.

Divide floats to eliminate deprecation warning.

---

PIL/GifImagePlugin.py
PIL/ImtImagePlugin.py
PIL/PngImagePlugin.py
Tests/test_file_gif.py
Tests/test_file_tiff.py

Fixes warnings that look like: "BytesWarning: Comparison between bytes and string"
Discovered using the command:
python -b -m nose -vx Tests/test_*.py

Fix BytesWarning discovered while running tests

---

Tests/test_file_fli.py
Tests/test_file_icns.py
Tests/test_file_ico.py
Tests/test_file_png.py
Tests/test_file_ppm.py
Tests/test_file_psd.py

The data read from the file was unused. The files remained opened and
were never explicitly closed.
Fixes some instances of warnings during tests:
"ResourceWarning: unclosed file ..."

Remove unused, open files at top level of tests.

---

PIL/Image.py
PIL/ImageDraw.py
PIL/TiffImagePlugin.py
PIL/features.py
Tests/test_features.py
Tests/test_file_png.py
Tests/test_file_tiff_metadata.py
Tests/test_image.py
Tests/test_imagemath.py
Tests/test_olefileio.py
setup.py

- Use more Pythonic "isinstance()" in places where a variable's type is being checked.

Replace type() equality checks with isinstance

---

Tests/check_j2k_overflow.py
Tests/check_libtiff_segfault.py
Tests/test_file_jpeg2k.py
Tests/test_image_access.py
Tests/test_image_resample.py
Tests/test_imagepath.py

Replace pattern with the builtin support for asserting exceptions.

Replace try/except/fail pattern with TestCase.assertRaises()

---

Tk/tkImaging.c

Python compiled from Python.org source builds the tkinter module as a
built-in module, not an external module, as is the case for the packaged
builds of Debian etc:
>>> Tkinter.tkinter
<module '_tkinter' (built-in)>
This breaks the current algorithm for searching for tkinter symbols,
which loaded the external module .so file to get the symbols.
Try searching in the main program namespace for the tkinter symbols,
before looking for the extermal module .so file.
Thanks to github user ettaka for reporting : see
https://github.com/matplotlib/matplotlib/issues/7428

FIX: search for tkinter first in builtins

---

.travis.yml

Revert https://github.com/python-pillow/Pillow/pull/1376, as the [fix](https://bitbucket.org/ned/coveragepy/issues/391) to allow Coverage to works with the Python nightly build (now Python 3.7.0a0) has now been released.

Build: Reinstate coverage tests on nightly

---

PIL/ImagePalette.py

Fixes some "ResourceWarning: unclosed file ..." when running tests with warnings enabled.

Close file after reading in ImagePalette.load()

---

PIL/GifImagePlugin.py
PIL/ImageMorph.py
PIL/JpegImagePlugin.py
PIL/TiffImagePlugin.py
Tests/helper.py
Tests/test_file_gif.py
Tests/test_font_pcf.py
Tests/test_imagemorph.py
setup.py

Avoids unnecessary temporary lists in memory.

Use generator expressions instead of list comprehension

---

PIL/ImageFont.py

Fixes some "ResourceWarning: unclosed file ..." when running tests with warnings enabled.

Close file after finished reading in ImageFont._load_pilfont()

---

PIL/Image.py
Tests/test_image.py

Resolves bug reported in https://github.com/python-pillow/Pillow/pull/1372#discussion_r87914471

Fixed bug in saving to fp-objects in Python >= 3.4

---

PIL/GimpPaletteFile.py
PIL/PngImagePlugin.py
PIL/XbmImagePlugin.py

Fix "invalid escape sequence" bytestring warnings in Python 3.6

---

PIL/JpegImagePlugin.py
Tests/test_image_draft.py

This fixes `.draft()` when requested aspect ratio doesn't match the original one.
```python
im = Image.open('dice_illusion.jpg')
im.draft(None, (150, 45))
im = im.resize((150, 45), Image.BICUBIC)
im.save('_out.jpg', quality=90)
```
Source image
Results before/after

Use minimal scale for jpeg drafts

---

PIL/WalImageFile.py

If a file pointer is passed in to the method, leave it open.
If the method opens the file pointer itself, then close when it is no longer needed.

If WalImageFile opens a file pointer, close

---

PIL/ImageOps.py

I've changed the description of the deform method's resample parameter to match the description of the scale method's resample parameter.

Improved description of method parameter

---

PIL/TiffImagePlugin.py
Tests/test_file_tiff.py

In the TIFF code saving icc_profile is conditional on tag_v2 being set which doesn't make sense to me. I believe this is merely an indentation typo.
I've been trying to save TIFFs with im.info['icc_profile'] set and compression=raw, but unfortunately this results in TIFFs without ICC color profiles.
With the attached patch TIFFs with said conditions will be saved with the profile set in im.info['icc_profile'].
Note: There are a number of different conditions that need to be met for code to succeed in saving with the profile since it branches between using libtiff and ImageFile._save(..), and the libtiff code does not currently save the ICC color profile.
For instance setting compression=tiff_lzw will result in using libtiff and no profile will be saved.

Fixes TIFFImagePlugin ICC color profile saving.

---

Tests/test_tiff_ifdrational.py

A boolean wrapped in parentheses is still a boolean, not a tuple.
The comma makes this an actual tuple so it can be iterated on in
the for loop that follows.
Simple reproducer:
```python
t = (False)
type(t)
>>> <class 'bool'>
for x in t:
print(x)
>>> TypeError: 'bool' object is not iterable
t = (False,)
type(t)
>>> <class 'tuple'>
for x in t:
print(x)
>>> False
```

Fix bug in test_idf_rational_save

---

PIL/TiffImagePlugin.py
Tests/test_file_libtiff.py

When using libtiff reader, the ICCPROFILE from the tags is not copied to .info.  This fixes it by moving the code from _decoder to _setup.
Tests included.

Update info.icc_profile when using libtiff reader.

---

PIL/JpegImagePlugin.py
Tests/test_file_jpeg.py

Fixes #2272 .
* Update heuristic for Maxblock scaling to account for CMYK jpegs.

Update Maxblock heuristic Fixes #2272

---

Tests/test_file_libtiff.py
Tests/test_file_tiff.py

Moves tests requiring libtiff to test_file_libtiff.
Tests now all pass using 
`python setup.py build_ext --disable-tiff install && make test`

Moving tests requiring libtiff to test_file_libtiff

---

Tests/test_file_libtiff.py
libImaging/TiffDecode.c

Fixes #2206 .
Writing large tiff images using libtiff to a BytesIO would fail if there was a need to increase the memory buffer size. This would not happen in the case of a file, since the file pointer was passed into libtiff for direct writing. 
The overflow check for buffer size had a sign error, so that any comparison was against a negative number, so it failed every attempt to realloc.

Fix for writing Tiff to BytesIO using libtiff.

---

PIL/ImageFile.py
decode.c

There are no users of decoder.handles_eof. 
It has been superseded by the decoder cleanup method.

Removed the handles_eof flag in the decoder, as there are no users of it

---

Tests/test_imagefont.py

Fixes #2116.
* The text weight looks a bit different with FreeType 2.7 compared to the test images created with an older version
* Increase the epsilon value so tests pass
Here's how the newly-generated `im` look (macOS Sierra, Python 2.7.12, Pillow master badbff1b99a939c05b3651db7e4aea11181e5bd7, FreeType 2.7) compared to the pre-generated `target_img` from the test suite.
Test | im  | target_img
--- | --- | ---
test_multiline_spacing | ![test_multiline_spacing-im](https://cloud.githubusercontent.com/assets/1324225/21098303/3e003f40-c071-11e6-8395-2ba6e8adb33d.png) | ![test_multiline_spacing-target_img](https://cloud.githubusercontent.com/assets/1324225/21098304/40e6dc32-c071-11e6-963c-44bdea98db82.png)
test_render_multiline_text | …

Increase epsilon for FreeType 2.7

---

.travis.yml
Makefile
_imaging.c

Includes/Replaces/Fixes #2289 
Pypy in versions 5.4.1 and 5.6 fail prepatch, but 5.3.1 is successful (on both precise and trusty, it's a pypy thing, not a ubuntu version thing, even though it's coming up because we're looking at updating the testing distro).
Specifically, in _imaging.c, this line:
```
if (PyObject_CheckBuffer(buffer)) {
return PyObject_GetBuffer(buffer, view, PyBUF_SIMPLE);
}
```
Returns a failure when passed a string buffer, e.g. 
```
arr = array.array("f", [0.1, 0.1])
p = ImagePath.Path(arr.tostring())   # < this argument is passed as the buffer parameter.
Breakpoint 1, PyPath_Create (self=0x0, args=0x7794b0) at path.c:253
253	    if (PyArg_ParseTuple(args, "n:Path", &count)) {
(gdb) c
Continuing.
Breakpoint 2, PyPath_Flatten (data=0x69c4f0, pxy=0x7fffffffd758) at …
```

Pypy buffer interface workaround

---

.travis.yml

Possible fix for #2299.
`pip install -e .` causes problems with the collection of C+Python coverage.
Removing it and instead installing olefile explicitly on Travis CI fixes it.

Reinstate Python+C coverage and send to Coveralls

---

depends/download-and-extract.sh
depends/install_imagequant.sh
depends/install_openjpeg.sh
depends/install_webp.sh

* Refactor common stuff from install_openjpeg.sh and install_webp.sh into a new download-and-extract.sh: means updating new version numbers in fewer places.
* Use this new download-and-extract.sh in install_imagequant.sh to get libimagequant from pillow-depends instead of cloning from its Git repo
* Instead of using a URL like https://github.com/python-pillow/pillow-depends/blob/master/pngquant-2.6.0.tar.gz?raw=true which resolves to https://github.com/python-pillow/pillow-depends/raw/master/pngquant-2.6.0.tar.gz and then resolves to https://raw.githubusercontent.com/python-pillow/pillow-depends/master/pngquant-2.6.0.tar.gz just use the latter. Shaves a second or two.

Build: Refactor dependency installation

---

PIL/GifImagePlugin.py
Tests/test_file_gif.py
docs/handbook/image-file-formats.rst

* Squashed and removed whitespace changes from #2298
* Added option for passing a tuple into duration
* Cleaned up the documentation so that we only have one duration entry for open, list all options for save.

Updated PR#2298

---

docs/installation.rst

libjpeg 9b has been a part of Pillow since PR #1673 and https://github.com/python-pillow/pillow-wheels/pull/29

Updated tested versions of libjpeg

---

PIL/Image.py
Tests/test_image.py
Tests/test_image_access.py
Tests/test_image_convert.py
Tests/test_image_copy.py
Tests/test_image_crop.py
Tests/test_image_resize.py
Tests/test_image_rotate.py

Fixes #2259 .
* Allow 0x0 images to be created. Restores pre 3.4 behavior

Allow 0 size images, Fixes #2259

---

PIL/ImageFile.py
PIL/PcdImagePlugin.py

* Move single purpose hack in imagefile.load to PcdImagePlugin.load_end()

Refactor out postprocessing hack to load_end in PcdImageFile

---

PIL/JpegImagePlugin.py
PIL/_binary.py

Resolves a TODO in _binary to replace `from struct import ...` with `import struct`
Cherry-picks an isolated commit from #2339 that achieves the same goal in JpegImagePlugin.

Removed unnecessary import

---

depends/install_imagequant.sh

As pointed out in https://github.com/python-pillow/Pillow/pull/2319#discussion_r96023214, after that PR updated pngquant, there is now an error when running `make`.
This is because libimagequant has now split from pngquant to become standalone, seen in this commit - https://github.com/pornel/pngquant/commit/17f587b991a0550586a9ffafabc90c055011f60b. It now resides at https://github.com/ImageOptim/libimagequant
This PR uses the new standalone version. The new archive in pillow-depends comes from https://github.com/ImageOptim/libimagequant/archive/2.8.2.tar.gz
Before - https://travis-ci.org/python-pillow/Pillow/jobs/187814764#L2251
Broken - https://travis-ci.org/python-pillow/Pillow/jobs/187587442#L2240
After - https://travis-ci.org/python-pillow/Pillow/jobs/191874057#L2248

Changed from pngquant to libimagequant

---

PIL/ImageMode.py

Initializing mode descriptor cache in-place is racy and may cause a thread to
observe a partially constructed cache if another thread is pre-empted while
it's still constructing the cache. In this change, the mode descriptor cache is
constructed into a local variable instead and then set globally in a single
atomic operation, preventing any possibility of observing an incomplete cache.

Make mode descriptor cache initialization thread-safe.

---

PIL/Image.py
Tests/test_image.py

This is a copy of #1968. The changes made are the ones suggested by @hugovk
- to ensure that the new `init()` line is called from tests
- to check for some expected extensions in the returned dictionary
- to simplify `assertEqual` to `assertTrue`.

Expose registered file extensions in Image

---

Tests/helper.py

Before:
```
TestFileDcx.test_seek_too_far ... ok
TestFileDcx.test_tell ... ok
Check invalid prefix ... ok
Check valid prefix ... ok
Check DX10 images can be opened ... ok
Check DXT1 images can be opened ... ok
Check DXT3 images can be opened ... ok
Check DXT5 images can be opened ... ok
Check that the appropriate error is thrown for a short file ... ok
Check a short header ... ok
TestFileEps.test_bytesio_object ... ok
TestFileEps.test_cmyk ... ok
```
After:
```
TestFileDcx.test_seek_too_far ... ok
TestFileDcx.test_tell ... ok
TestFileDds.test__validate_false ... ok
TestFileDds.test__validate_true ... ok
TestFileDds.test_dx10_bc7 ... ok
TestFileDds.test_sanity_dxt1 ... ok
TestFileDds.test_sanity_dxt3 ... ok
TestFileDds.test_sanity_dxt5 ... ok
TestFileDds.test_short_file ... ok …
```

Prevent `nose -v` printing docstrings

---

.travis.yml
.travis/after_success.sh
.travis/install.sh
.travis/script.sh
Tests/test_numpy.py
Tests/test_scipy.py

Fixes #2152.
This is a big, in progress refactor and addition. 
* I've added 4 new test items in the matrix, Alpine, Precise (12.04), Xenial (16.04), and Trusty X86 (14.04). They're all testing py2.7 for now. I particularly want the x86 part of the matrix, because we've tripped over that recently. (and there's a pr requiring x86 testing: #2359) Precise and Xenial wind up testing different library versions, also useful and necessary for the tiff metadata pr #2288.
* I've added a repo of docker files, so they can be pulled from the dockerhub.  I'm not convinced that it's tons faster to do that rather than just install from bare images.
* ~I've converted a few random test docstrings so that the -v listing shows all the test names that have been run.~ 
* I've re-orged the .travis.yml file, …

Docker images for additional travis runs

---

PIL/TiffImagePlugin.py
Tests/test_file_tiff.py

* Default to inch-interpretation for Tiff images missing ResolutionUnit tag, thus creating an im.info['dpi'] attribute.
* Keep old im.info['resolution'] attribute in such cases for compatibility.
* Test case for this.

Default to inch-interpretation for missing ResolutionUnit in TiffImagePlugin

---

PIL/PngImagePlugin.py
Tests/test_file_png.py

Moved iCCP chunk before PLTE chunk when saving as PNG

---

.travis/after_success.sh

Before:
```
.travis/after_success.sh: line 47: syntax error: unexpected end of file
```
https://travis-ci.org/python-pillow/Pillow/jobs/196494746#L4663

Fix after_success.sh syntax error

---

Tests/test_image.py
libImaging/Storage.c

Hey,
This is a simple fix for this interpreter crashing bug:
```
>>> Image.new('', (640,480))
Floating point exception
```
After the change:
```
>>> Image.new('', (640,480))
File "/home/lukasz/code/python/pillow/Pillow/PIL/Image.py", line 2061, in new
return Image()._new(core.fill(mode, size, color))
ValueError: empty mode
```
It would be nice to move the check to ImagingNewPrologueSubtype, where many other mode related checks are, but the empty string leads to division by zero in `THRESHOLD / bytes`.

BUG fix: '' in image mode no longer causes a crash

---

CHANGES.rst
PIL/SpiderImagePlugin.py
PIL/SunImagePlugin.py
PIL/WalImageFile.py
Tests/test_image.py
Tests/test_numpy.py
_imagingcms.c
docs/_templates/sidebarhelp.html
docs/handbook/image-file-formats.rst
docs/installation.rst
libImaging/SunRleDecode.c
mp_compile.py
setup.py
winbuild/config.py

Fixes these:
```
(line  514) redirect  http://www.wadsworth.org/ - permanently to https://www.wadsworth.org/
(line  514) redirect  http://spider.wadsworth.org/spider_doc/spider/docs/spider.html - permanently to https://spider.wadsworth.org/spider_doc/spider/docs/spider.html
...
(line  245) redirect  http://brew.sh/ - permanently to https://brew.sh/
```
https://travis-ci.org/python-pillow/Pillow/jobs/201197416#L3852
Also update some other `http:` to `https:`.

Docs: Update http to https

---

Tests/test_psdraw.py

Just to be more helpful by specifying the section.

Added anchor to readthedocs URL

---

PIL/EpsImagePlugin.py
PIL/JpegPresets.py

http://partners.adobe.com/public/developer/en/ps/5002.EPSF_Spec.pdf no longer works, so this PR replaces it with a web.archive.org URL.
Also replaces a http URL with https, in the spirit of #2403

Replaced broken URL

---

PIL/Image.py
Tests/test_numpy.py
map.c

Fixes #2259.
* Avoid [division by zero](https://github.com/python-pillow/Pillow/blob/badc3ec1f37096ebf959524b4bcf2c14db2d7936/map.c#L345) when creating a 0x0 image from a numpy array: `stride` is zero
* Add test case using numpy
* Update an error message from #2262

Fix division by zero when creating 0x0 image from numpy array

---

PIL/EpsImagePlugin.py
PIL/GifImagePlugin.py
PIL/IcnsImagePlugin.py
Tests/helper.py

Avoids unnecessary creation of temporary files as well as unnecessarily storing process output in memory. The temporary files would sometimes remain and not be cleaned up.

Send unwanted subprocess output to /dev/null

---

PIL/TiffImagePlugin.py
Tests/test_file_tiff.py

The discussion in #1087 indicates that this is not to be merged yet, to avoid skipping over deprecation warnings.
However, I thought I'd put this up with a 'Do Not Merge' label, so that it can be merged in the future.

Removed use of spaces in TIFF kwargs, deprecated in 2.7

---

Tests/test_image_fromqpixmap.py
Tests/test_image_toqpixmap.py

Arch qpixmap is fixed on on the docker side with the environment variable QT_QPA_PLATFORM=offscreen

Reenable QPixmap tests on arch

---

CHANGES.rst

As a general rule, the end of a changelog entry refers to PR numbers.
This is a minor correction of a changelog entry to adhere to that general rule.

Changelog reference fix

---

README.rst

Let's comment out the downloads badge whilst it's broken and showing 0 downloads/month.
See also https://github.com/python-pillow/Pillow/issues/2396 and https://github.com/badges/shields/issues/716.

Comment out broken PyPI downloads badge

---

README.rst

The commenting out of https://github.com/python-pillow/Pillow/pull/2432 didn't work, so let's just remove it until the badge is fixed.
---

Remove commented download-count badge

---

PIL/ImageTk.py

Do not try to import the `tkinter` module on Python 2.x. `tkinter` is part of the `tkinter3000` package (Widget Construction Kit for Tkinter).

Fix import of tkinter/Tkinter

---

PIL/Image.py

The `_imaging` module does not link against libtcl/libtk.
`FixTk` is imported by `import Tkinter` if necessary.
The `FixTk` module is for Python 2.x on Windows only.

Remove superfluous import of FixTk

---

.gitattributes

Fixes two test errors when cloning the master branch on Windows:
```
--------------------------------------------------------------------
PIL SETUP SUMMARY
--------------------------------------------------------------------
version      Pillow 4.1.0.dev0
platform     win32 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36)
[MSC v.1900 64 bit (AMD64)]
--------------------------------------------------------------------
--- JPEG support available
--- OPENJPEG (JPEG2000) support available (2.1)
--- ZLIB (PNG/ZIP) support available
*** LIBIMAGEQUANT support not available
--- LIBTIFF support available
--- FREETYPE2 support available
--- LITTLECMS2 support available
--- WEBP support available
--- WEBPMUX support available
<snip> …
```

Set ContainerIO test file as binary

---

Tests/test_image_access.py
libImaging/Access.c

Fixes Access to be reloaded if the python interpreter is restarted when embedded. Fixes #2268.
Test from cgohlke

Fix Access to be reloadable -- Issue #2268

---

docs/installation.rst
docs/releasenotes/4.1.0.rst

Escape asterisk, update name, some other little typos.

Docs typos

---

docs/index.rst

Let's remove the downloads badge as it's broken and showing 0 downloads/month.
---
---
https://pillow.readthedocs.io/en/4.1.x/index.html
See also https://github.com/python-pillow/Pillow/issues/2396 and https://github.com/badges/shields/issues/716.

Remove broken downloads badge

---

appveyor.yml

No need to clone the whole pillow-depends repo with full git history, or even with any git metadata. Multiply these times by six for the six CI jobs per build.
---
Original: **1m38s**
```
git clone https://github.com/python-pillow/pillow-depends.git c:\pillow-depends
```
---
Only clone the most recent commit to reduce download size: **0m57s**
```
git clone --depth 1 https://github.com/python-pillow/pillow-depends.git c:\pillow-depends
```
---
Download and extract zip instead of cloning dependencies, no need for git history: **0m55s**
```
curl -fsSL -o pillow-depends.zip https://github.com/python-pillow/pillow-depends/archive/master.zip
7z x pillow-depends.zip -oc:\
mv c:\pillow-depends-master c:\pillow-depends
```

Speed up AppVeyor build

---

.travis.yml

Run the faster Docker jobs last (which are all under two minutes), so the slower ones don't hold up the build.
Similarly, this is why the slow PyPy jobs are first.
This PR:
* Ran for 9 min 40 sec https://travis-ci.org/python-pillow/Pillow/builds/215293752
* Ran for 9 min 55 sec https://travis-ci.org/hugovk/Pillow/builds/215289384
Older master builds:
* Ran for 10 min 8 sec https://travis-ci.org/python-pillow/Pillow/builds/215172329
* Ran for 12 min 32 sec https://travis-ci.org/python-pillow/Pillow/builds/214990466
* Ran for 9 min 58 sec https://travis-ci.org/python-pillow/Pillow/builds/214990372
* Ran for 11 min 45 sec https://travis-ci.org/python-pillow/Pillow/builds/214012098 
* Ran for 10 min 35 sec https://travis-ci.org/python-pillow/Pillow/builds/214011829

Run faster Dockers last so slower jobs don't hold up the build

---

docs/releasenotes/3.3.2.rst

Looking at https://github.com/python-pillow/Pillow/blob/master/docs/releasenotes/3.3.2.rst, part of it is rendered as `xsize``*``ysize``*``bytes_per_pixel`
So this PR adds appropriate spaces.

Corrected syntax in release notes

---

Makefile
RELEASING.md

Updates the release process:
* Different Wheel URL
* Pypy takes one source archive
* Coordinated upload

Release Process Changes

---

CHANGES.rst

Cherry-pick of #2507 after a change was accidentally reverted.

Updated references to point to existing files

---

Tests/test_file_webp.py
_webp.c

This fixes (issue #2514) error handling for when functions are called with an invalid number of arguments or invalid types of arguments.
As for the tests, I've used the test provided in the issue.

Fix for issue #2514 - error handling mistake in _webp.c

---

_imaging.c

The internal im.save_ppm is potentially hidden behind a WITH_DEBUG flag, which has been set for all of Pillow's life.
Image._dump relies on that interface existing, and it is used in non-debug contexts.

Remove WITH_DEBUG compilation flag

---

.travis/after_success.sh
codecov.yml

Because Coveralls has sometimes been a bit iffy and they rarely respond to support requests (eg. ["Changes Unknown when pulling X on branch into ** on master**"](https://github.com/lemurheavy/coveralls-public/issues/351) / ["First build on master"](https://github.com/lemurheavy/coveralls-public/issues/610)), I'd like to trial using Codecov for a while.
For example: https://codecov.io/gh/python-pillow/Pillow
We could use both Coveralls and Codecov in parallel for a while, to make sure they agree, and fine tune Codecov's notifications, and then decide which one to keep.
Here's some example PRs:
* https://github.com/hugovk/Pillow/pull/17: increase coverage
* https://github.com/hugovk/Pillow/pull/18: decrease coverage
* https://github.com/hugovk/Pillow/pull/19: increase and decrease
Thoughts?

Use Codecov for coverage

---

path.c

This code was added in PIL 1.1.4 on May 10, 2003 and has remained unimplemented for the past 14 years. 
https://github.com/hugovk/PIL/blame/master/path.c#L315-L329
http://effbot.org/zone/pil-changes-114.htm
These two functions aren't called from any other C or Python files. Their chances of being implemented is slim, so let's just remove them. (As ever, PRs are welcome to add new functionality.)
Helps a bit towards #722.

Remove code 'not yet implemented' since May 10, 2003

---

setup.py

When openjpeg 1.5 is installed (Calligra 2.x, for example) and OpenJPEG
2.1 is installed, the subdirectory is added twice.
Since the 2nd time is ignored, it is ranked after the more general
/usr/local/include and openjpeg.h from the 1.5 version is picked up.
Fix this in a more general way:
- If a directory is added that already is in path
- But where is specified
Then remove the subdir from path and insert it at the spot requested.
A FIXME is added to the code bit explaining the real issue, but lack
investigative spirit / time to dive down the rabbit hole.
* See above

Freebsd compat

---

PIL/ImageShow.py

Closes #2529.
* Fix typo in option, should be `compress_level` rather than `compress-level`. It was using default 6 rather than 1 
* > **compress_level** 
> ZLIB compression level, a number between 0 and 9: 1 gives best speed, 9 gives best compression, 0 gives no compression at all. Default is 6. When `optimize` option is True `compress_level` has no effect (it is set to 9 regardless of a value passed).
* https://pillow.readthedocs.io/en/4.1.x/handbook/image-file-formats.html?highlight=compress_level#png

Fix Image.show compress_level typo

---

PIL/ImageMorph.py

Fixes the failure of  the mrl round trip test in https://github.com/python-pillow/Pillow/pull/2554 .
* 
* 
*

Fixed wrong expected size of mrls read from disk.

---

docs/reference/limits.rst

Clarifying that after 3.4, zero size images were allowed again.

Updated limits documentation

---

.travis.yml
.travis/install.sh
mp_compile.py

Travis CI now has updated PyPy versions: https://github.com/travis-ci/travis-ci/issues/6727#issuecomment-307186234
* This updates to the latest available PyPy (`pypy-5.7.1`).
* The latest PyPy3 (`pypy3.3-5.5-alpha`) results in a [segmentation fault](https://travis-ci.org/hugovk/Pillow/jobs/240935588#L2465), so instead this PR includes the one before that (`pypy3.3-5.2-alpha1`) which has no segfault.
Updating these means we can use multithreaded builds for PyPy3 and install pyroma for both PyPys.
---
Before, the logs showed these versions:
`pypy`:
```
Python 2.7.10 (c95650101a99, Sep 06 2016, 11:10:29)
[PyPy 5.4.1 with GCC 4.8.2]
```
`pypy3`:
```
Python 3.2.5 (b2091e973da69152b3f928bfaabd5d2347e6df46, Oct 24 2014, 12:08:04)
[PyPy 2.4.0 with GCC 4.8.2]
```
---
And after:
`pypy-5.7.1`:
``` …
```

Travis CI: Update PyPy

---

.travis/install.sh
PIL/features.py
Tests/test_features.py
_webp.c
selftest.py

Fixes detection of webp transparency, adds detection of webpmux, and splits out the modules from features.  Also actually tests the results.
This should now agree with the similar items that are printed during setup. 
Edit:
* python-tk is now installed on travis, since apparently the trusty images don't have it. 
* Keying off of PIL._tkinter_finder to discover if tkinter is available. 
* This is a stepping stone to the complex font PR: #2284

Features detection

---

PIL/IcoImagePlugin.py
PIL/Image.py
PIL/IptcImagePlugin.py
Tests/test_file_jpeg.py
Tests/test_file_libtiff.py
Tests/test_imagecolor.py
winbuild/build.py
winbuild/config.py

`iter(dict)` is equivalent to `iter(dict.keys())`, so simply act on the dict instead of adding the extra call.
Inspired by Lennart Regebro's PyCon 2017 presentation "Prehistoric Patterns in Python". Available at:
<https://www.youtube.com/watch?v=V5-JH23Vk0I>

Remove unnecessary calls to dict.keys()

---

_imaging.c

Remove an unused C function.
Replaces and closes #2539.
Helps a little bit towards #722.

Remove unused function

---

Tests/test_image_resample.py
libImaging/Resample.c

The Initial idea: while resizing we are excluding zero coefficients on the edges. For example, if `xmin = 103` and `xmax = 103 + 7` and we have coefficients `[0, -0.15, -0.3, 0,5, 0.53, -0.34, 0]`, it is equivalent of `xmin = 104`, `xmax = 104 + 5`, `[-0.15, -0.3, 0,5, 0.53, -0.34]`.
Currently, the following code is responsible for this:
https://github.com/python-pillow/Pillow/blob/5a359fbf287d6962def2d0d482d2570625c90bf6/libImaging/Resample.c#L183-L195
But it is possible mathematically prove, that we can just do not calculate these coefficients, instead of excluding them.
```
We need to find:
w = filterp->filter((x + xmin - center + 0.5) * ss)
, where xmin = (int) floor(center - support)
let center - support == n + λ, where 0.5 <= λ < 1
, then xmin == floor(center - support) == n
, then …
```

Replace the truncating of zero coefficients with math power

---

PIL/TiffImagePlugin.py
Tests/test_file_tiff.py

This is a quick solution that will allow to save tiff stacks from separate images, _e.g._ from Numpy arrays. Previously, tiff stacks could be saved only from multiframe images.
This behavior is similar to what is possible now with GIFs. Note however, that for correct results, all the appended images should have the same ```encoder{info,config}``` properties.
Example:
```python
import numpy as np
a = np.ones((100,100,100), dtype=np.uint8)
imlist = []
for m in a:
imlist.append(Image.fromarray(m))
imlist[0].save("test.tif", compression="tiff_deflate", save_all=True,
append_images=imlist[1:])
```
...This should result in a 100-frame, 100x100 tiff stack. (Previously: would save only the first frame, despite ```save_all``` and ```append_images```.)
Please see the …

Allow to save tiff stacks from separate images

---

PIL/ImageFile.py

Called ``image = image.convert("RGB")``
Unfortunately I cannot retrieve the actual image that causes this to occur, but there is a scenario where the ``err_code`` variable is not initialized.
```
File "PIL/Image.py", line 841, in convert
File "PIL/ImageFile.py", line 238, in load
UnboundLocalError: local variable 'err_code' referenced before assignment
```
- Pillow 3.3.3
- Python 2.7.12

Ensure that the `err_code` variable is initialized before using.

---

PIL/GifImagePlugin.py
PIL/Image.py
Tests/test_decompression_bomb.py

Fixes #2402 .
* Add decompression bomb check for image.crop, since it can enlarge images.
* Refactor out checks to _crop, so that we can apply them to any core image object.
* Gif disposal is where the bug in #2402 was, it was requesting a 1GP dispose_extents.
Still need to: 
~- [ ] Generate a gif with extra large extents~

Crop decompression

---

PIL/PngImagePlugin.py
Tests/test_file_png.py
decode.c
libImaging/Imaging.h
libImaging/JpegDecode.c
libImaging/ZipDecode.c

This PR fixes two problems:
Pillow can't open some truncated PNG images even with `ImageFile.LOAD_TRUNCATED_IMAGES = True`.
`SyntaxError: broken PNG file (chunk '\x00\x00\x00\x00')`
Example image: https://ucarecdn.com/99b9dc77-abd0-4077-887b-2b7a0a753d76/587593.png
This is general memory leak while loading truncated PNG files regardless of LOAD_TRUNCATED_IMAGES flag. The reason is `inflate` operates normally if source stream is truncated and returns no errors. For `ImagingZipDecode` function this look like normal behavior. But on the python level we see than the file if over and we should call `inflateEnd` and free `context->previous` somehow. This PR adds `ImagingZipDecodeCleanup` function for this.

Fix truncated png loading

---

README.rst

Because the last run was four months ago -- see https://github.com/python-pillow/Pillow/issues/2532.

Remove Landscape/health badge

---

.travis.yml

Change the owner of the TRAVIS_BUILD_DIR to match the UID in the container owner.  Fixes #2586

Change the owner of the TRAVIS_BUILD_DIR

---

README.rst

At https://github.com/python-pillow/Pillow, you will see a link to `|health|` in the README. This is because #2584 removed the Landscape badge.

Removed reference to Landscape badge

---

PIL/Image.py
PIL/__init__.py
PIL/version.py
_imaging.c
appveyor.yml
setup.py

* Improves the release process by having one place to change the version number for Pillow, then including that value elsewhere, when required. 
* Does not update the appveyor version number. I'm wondering if just a build is ok there.

RFC: Specify Version in one place

---

PIL/EpsImagePlugin.py

Resolves #2559 
The parameter is described at https://www.ghostscript.com/doc/current/Use.htm#Interaction_related_parameters -
> Causes Ghostscript to exit after processing all files named on the command line, rather than going into an interactive loop reading PostScript commands. Equivalent to putting -c quit at the end of the command line.

Added dBATCH parameter to ghostscript command

---

PIL/Image.py
Tests/test_image.py
docs/reference/Image.rst

See #1911 
* Adds an alpha_composite instance method on Image that does the composition 'in place', rather than returning a whole new image. 
* Specifies a bounding box in the destination/background image, and a source point in the overlay.
* Currently done in python, but this is an initial implementation that could be pushed into the C layer to eliminate copies and crops.
I'm doing this as a test to see if the interface makes sense as a companion of Image.Image.paste, and Image.alpha_composite.

RFC: Image.Image.alpha_composite

---

.travis.yml
Tests/test_imagefont.py

This is test support on docker for centos/amazon linux.
It's parameterizing changes in test_imagefont.py, but unfortunately that is a really messy diff built from the complex text changes. So this has #2576 as a dependency.

Test support for centos/amazon linux

---

docs/handbook/image-file-formats.rst

Issues #2191 and #2511 arose because users did not understand that `append_images` was only available for GIF. While we have added support now for the relevant formats, this improves the documentation to try and avoid similar confusion in the future.

Improved append_images documentation

---

PIL/PdfImagePlugin.py

* Fix the built-in name "dict" to "dict_" in PIL/PdfImagePlugin.py
It can be seen an error when: python -c "from Cython.Build import cythonize; cythonize(['PIL/PdfImagePlugin.py'])"

[etc] Fix built-in name.

---

docs/reference/Image.rst

Images created with `open` have a filename attribute, but the documentation does not mention it. This lead to a short, but interesting discussion on [Stackoverflow](https://stackoverflow.com/questions/45087638/get-image-filename-from-image-pil/).

Docs: added the description of the filename attribute to images.rst

---

PIL/Image.py

Also remove a space and lowercase "version" for sentence case.
Before:
```
/Users/hugo/github/Pillow/PIL/Image.py:77: RuntimeWarning: The _imaging extension was built for another version of Pillow or PIL: Core Version: 4.3.0.dev0Pillow Version:  4.2.0
warnings.warn(str(v), RuntimeWarning)
File "/tmp/Downloads/2639.py", line 1, in <module>
from PIL import Image, ImageDraw, ImageFont
File "/Users/hugo/github/Pillow/PIL/Image.py", line 62, in <module>
PILLOW_VERSION))
ImportError: The _imaging extension was built for another version of Pillow or PIL: Core Version: 4.3.0.dev0Pillow Version:  4.2.0
```
After:
```
/Users/hugo/github/Pillow/PIL/Image.py:78: RuntimeWarning: The _imaging extension was built for another version of Pillow or PIL:
Core version: …
```

Add newlines to error message for clarity

---

PIL/ImageFont.py
Tests/test_imagefont.py

Fixes #2639.
In Pillow 4.2.0 and 4.2.1 (but not 4.1.0):
```python
im = Image.new('RGB', (300, 100), 'white')
draw = ImageDraw.Draw(im)
ttf = self.get_font()
line = "some text"
draw.text((100, 40), line, (0, 0, 0), font=ttf, align='left')
del draw
```
Causes:
```
File "/usr/local/lib/python2.7/site-packages/PIL/ImageDraw.py", line 217, in text
mask, offset = font.getmask2(text, self.fontmode, *args, **kwargs)
TypeError: getmask2() got an unexpected keyword argument 'align'
```
Can be fixed by adding `*args, **kwargs` into:
```python
def getmask2(self, text, mode="", fill=Image.core.fill, direction=None, features=None):
```

Fix unexpected keyword argument 'align'

---

PIL/SgiImagePlugin.py

When throwing an error on save, I would imagine it is better to do so before any write operations, as opposed to leave a corrupt file behind.
It would also be faster in the instances where the error is thrown.

Moved SgiImagePlugin save error to before the start of write operations

---

libImaging/Resample.c

Not a big deal, but why not )
```
Scale 2560×1600 RGB image
to 2048x1280 bil    71.30 Mpx/s    77.93 Mpx/s
to 2048x1280 bic    50.37 Mpx/s    54.74 Mpx/s
to 2048x1280 lzs    37.40 Mpx/s    39.01 Mpx/s
to 5478x3424 bil    15.03 Mpx/s    16.56 Mpx/s
to 5478x3424 bic    11.63 Mpx/s    12.50 Mpx/s
to 5478x3424 lzs     9.27 Mpx/s     9.84 Mpx/s
```

Speed up resampling a bit again

---

libImaging/BcnDecode.c

BC5 decoding uses only 2 channels instead of 4. The current algorithm did not initialize the RGBA struct which resulted in random values in the output image. This commit should initialize the decoded RGBA struct, thus setting B and A values to default (0).
* Initialize target buffer to zero before filling.

Fixed bc5 decoding

---

Tests/test_image.py
libImaging/Imaging.h
libImaging/Storage.c
map.c

This is a small cleanup before the further work on storage module.
* Tests for different modes for `Image.new`
* Fixed memory leak if no available memory for allocating new image
* Fixed memory leak if `xsize > (INT_MAX / 4) - 1`
* Use accurate `im->linesize` value instead of `strlen(mode)` approximation
Side effect: removed ImagingNewEpilogue

Storage cleanup

---

_imaging.c
libImaging/AlphaComposite.c
libImaging/Bands.c
libImaging/Blend.c
libImaging/BoxBlur.c
libImaging/Convert.c
libImaging/Copy.c
libImaging/Crop.c
libImaging/Fill.c
libImaging/Imaging.h
libImaging/Matrix.c
libImaging/Negative.c
libImaging/Offset.c
libImaging/Resample.c
libImaging/Storage.c

The Pillow's `ImagingNew` function always creates images filled with zeroes (black color). While this is fine for some operations, for others this is absolutely not required and can affect performance, especially for operations which does not required intensive computation.
Zeroing is required if:
* operation depends on initial pixels values and expects zeroes
* operation can be applied on the part of the image
* operation can be applied partially, for example loading corrupted image
In other cases zeroing can be avoided.
This PR provides new `ImagingNewDirty` function which makes no warranties about the content of created images. Also, this PR uses `ImagingNewDirty` for many operations, such as resize, crop.

Fast image allocation

---

PIL/Image.py
PIL/ImageEnhance.py
Tests/test_file_png.py
Tests/test_format_hsv.py
Tests/test_image.py
Tests/test_image_convert.py
Tests/test_imagecms.py
Tests/test_imageenhance.py
Tests/test_numpy.py
docs/reference/Image.rst
docs/releasenotes/4.3.0.rst
docs/releasenotes/index.rst

Sometimes you need to get just one channel from the image. Of course, there is `split()` method which will return all bands but this is extra computations. Also `Image.getchannel()` method can accept channel name alongside with index.
Benchmarks:
```
im.split()[band]
get R channel of RGB        0.00834 s   491.18 Mpx/s
get A channel of RGBA       0.01109 s   369.21 Mpx/s
im.getchannel(band)
get R channel of RGB        0.00287 s  1429.15 Mpx/s
get A channel of RGBA       0.00287 s  1429.15 Mpx/s
```

New Image.getchannel method

---

Tests/test_file_sgi.py

While I have added a test for it, I'm skeptical about the error raised at https://github.com/python-pillow/Pillow/blob/master/PIL/SgiImagePlugin.py#L136. In the current state of the plugin, it's impossible to trigger without breaking the image as I do here - from what I can see, the number of modes are static values retrieved from https://github.com/python-pillow/Pillow/blob/master/PIL/Image.py#L211.
Any thoughts from @wiredfool, who added it in https://github.com/python-pillow/Pillow/pull/2325/commits/31c204eae4e158bbaa6cda4afe7a2f8e2fcabe6e?

Added tests for SgiImagePlugin

---

PIL/Image.py
_imaging.c
libImaging/Bands.c
libImaging/Imaging.h

This introduces `im.split()` core function and also speedups old `im.getband()` core function.
There are two sets of benchmarks: for current master and for conjunction with #2655
```
Slow allocation
Master            Fast GetBand      im.split()
split LA      647.17 Mpx/s      804.72 Mpx/s      997.79 Mpx/s
split RGB     427.97 Mpx/s      538.45 Mpx/s      691.43 Mpx/s
split RGBA    331.82 Mpx/s      405.38 Mpx/s      519.33 Mpx/s
Fast allocation
Fast allocation   Fast GetBand      im.split()
split LA      739.13 Mpx/s      961.76 Mpx/s     1364.44 Mpx/s
split RGB     492.85 Mpx/s      617.69 Mpx/s      981.31 Mpx/s
split RGBA    373.55 Mpx/s      486.30 Mpx/s      713.16 Mpx/s
```

Fast split()

---

.travis.yml

Uses https://github.com/python-pillow/docker-images/pull/8
TravisCI test runs in docker for Fedora 24 and 26.

Test Fedora 24 and 26 in Docker

---

PIL/Image.py
Tests/test_numpy.py
libImaging/Unpack.c

Fixes #2044
* Add a new rawmode 1;8, for b/w image in bytes. 0 == 0, >0 == 255
* Add the mapping in Image._fromarray_typemap
* Tests for the numpy integration, fixes old boolean tests, adds specific one for this issue.
This should allow boolean arrays in numpy to be pulled into Pillow.  e.g.:
```
a = np.array((x,y), dtype=np.bool)
img = Image.fromarray(a)
```

Test/fix for issue #2044

---

depends/termux.sh
setup.py

Fixes #1957 .
Basic support for termux (android) support (tested on chromeos/x86). The goal here is that we should be able to `pip install pillow` with at least the basic zlib and jpeg libraries 
* Look for ANDROID_ROOT in setup.py
Still need to test this off my own machine. Should be possible in a docker chroot, but that's going to take some research.

Basic support for Termux (android) 

---

PIL/PyAccess.py
Tests/test_lib_pack.py
Tests/test_mode_i16.py
libImaging/Pack.c
libImaging/Unpack.c

Decided to implement all and improved tests for packing and unpacking.
Added many missed tests. At the end all possible modes should be covered. Most tests improved, for example with line interleave.

Packing tests

---

PIL/JpegImagePlugin.py
PIL/JpegPresets.py
Tests/test_file_jpeg.py
docs/handbook/image-file-formats.rst
libImaging/JpegEncode.c

Fixes #2063
`.save(subsampling=2)` actually sets sampling factor `4:2:0`. As of `.save(subsampling="4:1:1")` is just alias to `.save(subsampling=2)`, it also meant `4:2:0`.
Fixed all documentation and comments to correct sampling factor.
Allow new `.save(subsampling="4:2:0")` value which actually means `4:2:0`.
Leave old `.save(subsampling="4:1:1")` value as alias to `4:2:0`.

Fix sampling factor for subsampling=2 while JPEG saving

---

_imaging.c
_imagingft.c
_webp.c

* The parameter for _putpallettealphas should not have any unicode conversion on py3. Use the PY_ARG_BYTES_LENGTH macro instead of the py2 's#'

Fixed type to be byteslike object.

---

libImaging/Convert.c

There is no easy way to convert CMYK to RGB without complicated color management. But there are some approximations. Pillow used to use the simplest one, which, for example, could be [found there](http://www.rapidtables.com/convert/color/rgb-to-cmyk.htm). It is not too accurate and produces very dark images. On the other hand, I found [this formulas](https://www.easyrgb.com/en/math.php) which produces far better result.
```
C = ( C * ( 1 - K ) + K )
M = ( M * ( 1 - K ) + K )
Y = ( Y * ( 1 - K ) + K )
R = ( 1 - C ) * 255
G = ( 1 - M ) * 255
B = ( 1 - Y ) * 255
```
or in one equation:
```
R = 255 - K - C * ( 255 - K ) / 255
G = 255 - K - M * ( 255 - K ) / 255
B = 255 - K - Y * ( 255 - K ) / 255
```
Original CMYK image opened in Safari (and probably how it should looks like with correct …

Convert CMYK to RGB like Google Chrome

---

PIL/Image.py
Tests/test_image_convert.py

`info['transparency]` was not removed when an RGB or L image
was converted to RGBA. This could result in unexpected behavior
when saving the resulting image.
Other image conversions already delete or update the transparency
info. There is a shortcut for RGB/L to RGBA which missed this.

Delete transparency info when img.convert'ing RGB/L to RGBA

---

PIL/Image.py
Tests/test_image.py
Tests/test_image_convert.py

Fixes #2702
* Only copy the palette if new mode is in P, PA
* Tests.
(note, making a 'PA' image via putalpha fails, so tests are somewhat incomplete)

Remove palettes from non-palette modes in _new #2702

---

Tests/test_image_resample.py
_imaging.c
libImaging/Resample.c

I found many errors with box argument when x0 & y0 coordinates are 0. In all following cases result resolution should be 400x400:
```python
>>> im.size
<<< (1034, 1280)
>>> im.resize((400, 400), Image.LANCZOS, (0, 0, 400, 400)).size
<<< (1034, 1280)
>>> im.resize((400, 400), Image.LANCZOS, (0, 0, 400, 1024)).size
<<< (1034, 400)
>>> im.resize((400, 400), Image.LANCZOS, (0, 0, 1024, 400)).size
<<< (400, 403)
```
I'm opening PR just to let know what the problem exists and I'm working on the fix.

Fix resize with box when no resize required

---

docs/installation.rst
docs/reference/ImageCms.rst

* Added a blank line in 'installation.rst' - See https://github.com/python-pillow/Pillow/blob/master/docs/installation.rst#building-on-macos vs https://github.com/radarhere/Pillow/blob/docs/docs/installation.rst#building-on-macos
* Changed single backticks surrounding None to double backticks surrounding None in 'ImageCms.rst' - see the text above and below it

Fixed documentation syntax

---

PIL/ImageGrab.py
display.c

This is `debugging; will be removed in future versions` since PIL.
It doesn't have a Python interface, so it seems like it can be removed.

Removed debugging interface for Image.core.grabclipboard

---

Tests/helper.py
Tests/test_file_png.py
Tests/test_font_leaks.py
_imaging.c
_imagingft.c

Fixes #2629 .
* Fix for memory leak in PILfont getsize
* Fix for memory leak in truetype getsize

Fix for memory leaks in font handling

---

Tests/test_imagefont.py
_imagingft.c

Fixes #2666 .
* Fix  "SystemError: error return without exception set" when rendering an empty string.

Fix for crash drawing empty strings

---

.travis.yml

This updates pypy and pypy3 with no need to specify exact versions.
pypy:
* From PyPy 5.7.1 (Python 2.7.13)
* To PyPy 5.8.0 (Python 2.7.13)
pypy3:
* From PyPy 5.2.0-alpha0 (Python 3.3.5)
* To PyPy 5.8.0-beta0 (Python 3.5.3)

Travis CI: Use default pypy/pypy3

---

PIL/Image.py

* Combined duplicate lines from a try-except, by moving it after the block
* Removed `self.pyaccess = None` in one location, as it is performed a line above by `_copy`, as pointed out by @homm in https://github.com/python-pillow/Pillow/pull/1891#discussion_r133421874

Removed unnecessary lines

---

PIL/TgaImagePlugin.py

Add the footer that is part of the version 2 spec. Some applications don't like images without the footer. Such as perforce's p4merge tool.
Fixes # .
* 
* 
*

Add targa version 2 footer

---

docs/handbook/image-file-formats.rst

Code was fixed in https://github.com/python-pillow/Pillow/pull/2267 but not the docs: 
default max size for ICO is (256, 256) not (255, 255).

Fix docs to match code

---

libImaging/Filter.c
libImaging/ImagingUtils.h

I think this is fine to have in .h files the small inline functions which could be used in several modules. At least there are a lot in [SSE headers](https://github.com/gcc-mirror/gcc/blob/master/gcc/config/i386/emmintrin.h).

Cleanup Filter.c

---

Scripts/player.py

The original code -
```
self.im = im[1:]
im = self.im[0]
```
presumably intended to remove the first image from the list, displaying it initially before loop through the rest.
However, it actually discards the first image, and selects the next image to display initially.
This PR fixes this.

Fixed bug where player script was skipping the first image

---

PIL/ImageFilter.py
PIL/ImageOps.py
Tests/test_box_blur.py
Tests/test_image_filter.py
Tests/test_imageops_usm.py
docs/reference/ImageFilter.rst
docs/releasenotes/4.3.0.rst

Todo: add release notes for ImageFilter.BoxBlur

Deprecate ImageOps undocumented functions

---

PIL/PyAccess.py
_imaging.c

Some of this properties are already available through `im` properties. In general, there is no need to expose internals like `destroy` or `block` pointers to python. `depth` is unused even in C code.

Export only required properties in unsafe_ptrs

---

PIL/Image.py
Tests/test_image.py

The pathlib backport module is no longer maintained. The development
has moved to the pathlib2 module instead.
Quoting from the pathlib's README:
"Attention: this backport module isn't maintained anymore. If you want
to report issues or contribute patches, please consider the pathlib2
project instead."
Other projects have already switched to pathlib2, most notably IPython
and its dependencies.

Use pathlib2 for Path objects on Python < 3.4

---

appveyor.yml
setup.py
winbuild/appveyor_build_msys2.sh
winbuild/appveyor_install_msys2_deps.sh

Fixes #2731, Fixes #2688.
* Turn off zipsafe in setup.py
* Use the posix/gcc branch for version literal
* test on appveyor

Changes to cleanly compile on windows/msys2

---

docs/reference/ImageDraw.rst

https://pillow.readthedocs.io/en/4.2.x/reference/ImageDraw.html shows the arguments for `multiline_text`, `textsize` and `multiline_textsize` in a different way to the other methods.
This PR removes the line breaks that presumably cause this.

Corrected docs syntax

---

PIL/EpsImagePlugin.py
PIL/FitsStubImagePlugin.py
PIL/FliImagePlugin.py
PIL/FtexImagePlugin.py
PIL/Hdf5StubImagePlugin.py
PIL/Image.py
PIL/Jpeg2KImagePlugin.py
PIL/JpegImagePlugin.py
PIL/MpegImagePlugin.py
PIL/PpmImagePlugin.py
PIL/SgiImagePlugin.py
PIL/TiffImagePlugin.py
PIL/WmfImagePlugin.py
Tests/test_image.py

Rather than having multiple calls to `register_extension` from the same image plugins, I suggest a `register_extensions` method.

Added register_extensions method

---

PIL/Image.py

- Avoid unnecessarily loading an image twice
- In Image's convert method, if image is already in the destination mode, do not convert

Avoid unnecessary Image operations

---

PIL/GifImagePlugin.py
PIL/TiffImagePlugin.py
Tests/test_file_gif.py
Tests/test_file_tiff.py

For some plugins, `is_animated` seeks within the image to determine whether or not an image is 'animated'. However, if the number of frames in the image is already known, then this is unnecessary.

If n_frames is known, then use when determining is_animated

---

Tests/helper.py
Tests/test_image.py
Tests/test_numpy.py

Closes #835.
These are tests that were failing in #835, cherry-picked onto latest master.
Something along the way means they now pass, so they can go into the test suite to guard against regressions, and the issue can be closed.

ResourceWarning tests

---

Tests/test_scipy.py

Fixes one test error when using scipy release candidate:
```
ERROR: Failure: ValueError (invalid version number '1.0.0rc1')
----------------------------------------------------------------------
File "X:\Python36\lib\site-packages\nose\failure.py", line 39, in runTest
raise self.exc_val.with_traceback(self.tb)
File "X:\Python36\lib\site-packages\nose\loader.py", line 418, in loadTestsFromName
addr.filename, addr.module)
File "X:\Python36\lib\site-packages\nose\importer.py", line 47, in importFromPath
return self.importFromDir(dir_path, fqname)
File "X:\Python36\lib\site-packages\nose\importer.py", line 94, in importFromDir
mod = load_module(part_fqname, fh, filename, desc)
File …
```

Fix ValueError: invalid version number '1.0.0rc1'

---

docs/reference/Image.rst

Adds a note about aspect ratio's into the docs for the thumbnail example. This is described in the main function description further down but isn't noted in the example which can lead to panic attacks when you're skim reading :)

Add note about aspect ratio to documentation

---

PIL/DcxImagePlugin.py
PIL/FliImagePlugin.py
PIL/GifImagePlugin.py
PIL/ImImagePlugin.py
PIL/ImageFile.py
PIL/MicImagePlugin.py
PIL/MpoImagePlugin.py
PIL/PsdImagePlugin.py
PIL/SpiderImagePlugin.py
PIL/TiffImagePlugin.py
Tests/test_file_dcx.py
Tests/test_file_fli.py
Tests/test_file_gif.py
Tests/test_file_im.py
Tests/test_file_mpo.py
Tests/test_file_psd.py
Tests/test_file_tiff.py

When seeking, some of the multiframe image formats check that the destination frame is not the current frame, or that the destination frame is not out of range.
This moves those checks into ImageFile, also making the behaviour more consistent between formats.

Common seek frame position check

---

libImaging/Bands.c

Fixes
```
libImaging/Bands.c:76:9: warning: expression result unused [-Wunused-value]
(Imaging) ImagingError_ModeError();
^         ~~~~~~~~~~~~~~~~~~~~~~~~
```
by removing the cast.
Introduced in https://github.com/python-pillow/Pillow/pull/2676/files#diff-7dd4690995a96a7444dfaff941412c02R83

Fix expression result unused warning

---

libImaging/Storage.c

Fixes https://github.com/python-pillow/Pillow/issues/2772 (Image.new segfaults on win-amd64). 
Tested on Windows with Python 2.7 and 3.6, 32-bit and 64-bit.

Fix bulletproof code from libc

---

_imagingcms.c

Fix potential issue on 64-bit Windows.
Fixes compiler warnings:
```
_imagingcms.c(613): warning C4312: 'type cast': conversion from 'int' to 'HDC' of greater size
_imagingcms.c(615): warning C4312: 'type cast': conversion from 'int' to 'HWND' of greater size
_imagingcms.c(617): warning C4312: 'type cast': conversion from 'int' to 'HWND' of greater size
```

Use correct Windows handle type

---

_imaging.c

Maybe I am missing something, but it looks like the `isblock` function should return a `bool`. 
This also fixes a compiler warning and a potential issue on 64-bit Windows:
```
_imaging.c(1759): warning C4311: 'type cast': pointer truncation from 'char *' to 'long'
```

Return bool from isblock function

---

Tests/test_imagedraw.py
_imaging.c
_imagingft.c

Fixes #2783 .
* Don't return NULL without an error set.
* Don't handle 0 length strings differently.

Fix for return without none set

---

appveyor.yml

Fixes #2810 .
Underlying issue appears to be the path modification that we do to allow PIL to be imported from the work directory when we're doing an installed, not an in place build.  So it's not finding _imaging in the PIL directory. 
I haven't gone through to figure out why this is the case, but it's enough to move the PIL directory out of the way during the selftest and test runs.

Quick and Dirty fix for msys2 on appveyor

---

Tests/test_file_eps.py

Required for a new Docker image build to pass.
I've validated the images visually that they're close.

Relaxing similarity on showpage test, Arch has rendering differences

---

PIL/PpmImagePlugin.py

Updated version of and closes https://github.com/python-pillow/Pillow/pull/2820.
* Use a fixed list of whitespace according to the spec, rather relying on the locale
* Fixes `UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 6: invalid start byte` on SmartOS base-64 17.3.0

PPM: Use fixed list of whitespace, rather relying on locale

---

Tests/test_file_fpx.py
Tests/test_file_mic.py
requirements.txt
setup.py

Support for plugins requiring olefile will not be loaded if it is not installed. Allows library consumers to avoid installing this dependency if they choose. Some library consumers have little interest in the format support and would like to keep dependencies to a minimum.
* olefile support is no longer a required dependency
* if it is exists, image support requiring olefile continues to be available

Allow the olefile dependency to be optional

---

PIL/PdfImagePlugin.py
Tests/test_file_pdf.py

Fixes #2804 
Seeing that saving as a TIFF before saving as a PDF fixed the problem (see issue #2804 for more details), I tried to copy some of the _save_all method in TiffImagePlugin.py into the _save_all method of PdfImagePlugin.py and it seems to work.

Fix #2804: sets encoderinfo for images when saving multi-page PDF

---

PIL/OleFileIO.py

The vendored version was removed in #2199, on 13 Dec 2016, in favour of the olefile Python package and replaced with a deprecation warning that PIL.OleFileIO would be removed in a future version.
We've had four quarterly releases since then (4.0.0, 4.1.0, 4.2.0, 4.3.0), shall we now ~finish this off~ replace it with an import error that says the same thing and then remove it at a later date?
See https://github.com/python-pillow/Pillow/pull/2784 for removal at a future date.
cc: @decalage2 @jdufresne

Replace PIL.OleFileIO warning with descriptive ImportError

---

.travis/after_success.sh
requirements.txt

See https://github.com/PyCQA/pycodestyle/issues/466.

pep8 is now pycodestyle

---

PIL/TiffImagePlugin.py
PIL/WebPImagePlugin.py
Tests/test_file_webp_animated.py

I'm converting the generator to a list for WEBP, rather than using itertools, since `append_images` is called twice.
I also have a commit changing TIFF saving to using a list rather than itertools as well, in order to use single frame save if it is given a single frame image and an empty generator.

Added support for generators when using append_images for WEBP

---

docs/reference/ImageDraw.rst

The first parameter of several functions is described as "four points". It should be "two points" or "four coordinates".

Correct error in ImageDraw documentation

---

setup.py

Fixes #2851 .
Apparently Debian strips out all the platform detection code when building .debs, and we're missing support for some arm variants. But since that support is missing, we pop an error when we don't detect the linux version. 
* Promote the add_multiarch_paths to run before the manual detection, if we know we're on a debian derivative. This is going to continue to fail on non-ubuntu/non-debian debian derivatives. 
* Refactor a series of elifs into a data structure.

Fix setup.py on debian

---

setup.py

Fixes https://github.com/python-pillow/Pillow/pull/2853#discussion_r152495000 .
* Use a filesystem check instead of the useful, but deprecated platform.dist.
(note that there is a pypi module for this, but I'd rather not pull in a dependency for what is essentially a quick check to see if it's reasonable to try running a configuration app)

Replace deprecated platform.dist with file existence check

---

.travis.yml

Python 3.7.0 is due out on 2018-06-15, or after two Pillow releases.
https://www.python.org/dev/peps/pep-0537/#schedule
One 3.7 incompatibility has been caught in https://github.com/python-pillow/Pillow/pull/2869, but shall we start testing against 3.7-dev already to make sure nothing else sneaks in there before it's out?
We don't test setup.py, so this doesn't didn't actually catch `platform.dist`'s removal, but the good news is all the existing tests pass.

Test 3.7-dev ahead of 3.7.0's expected 2018-06-15 release

---

PIL/ImageShow.py

*  As a Ubuntu user, ```~PIL.Image.Image.show``` method shows the image, but the default Image Viewer of Ubuntu using the command ```eog``` in the terminal. By default, Pillow looking for the commands ```xv``` and ```display``` .
*  Add ```eog``` support for the Ubuntu. 
*  Now Ubuntu user can see the image and it is very handy for debugging and tests.

Add eog support for Ubuntu Image Viewer

---

setup.py

* Add a licence classifier.
Pyroma has been updated and now complains about "You should specify license in classifiers.", failing a test ([eg.](https://travis-ci.org/hugovk/Pillow/jobs/308874822#L3843)).
The PIL licence isn't available as a classifier. Would something like "Free To Use But Restricted" or another be better than "Other/Proprietary License"?
Here's the full list from https://pypi.python.org/pypi?%3Aaction=list_classifiers:
```
License :: Aladdin Free Public License (AFPL)
License :: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
License :: CeCILL-B Free Software License Agreement (CECILL-B)
License :: CeCILL-C Free Software License Agreement (CECILL-C)
License :: DFSG approved
License :: Eiffel Forum License (EFL)
License :: Free …
```

Add licence classifier

---

.travis/install.sh
Tests/helper.py
Tests/test_uploader.py

I've been thinking about something like this since we had the issue that was non-reproducable on any of my machines. 
What this does is push all test failures for `assert_image_equal` and `assert_image_similar` to a webservice, where it displays those images and the difference. 
```
FAIL: TestUploader.test_upload_equal
----------------------------------------------------------------------
File "/home/travis/build/wiredfool/Pillow/Tests/test_uploader.py", line 10, in test_upload_equal
self.assert_image_equal(result, target)
File "/home/travis/build/wiredfool/Pillow/Tests/helper.py", line 104, in assert_image_equal
self.fail(msg or "got different content")
AssertionError: got different …
```

RFC: Display differences

---

PIL/Image.py
Tests/test_image_transform.py
_imaging.c

Fixes #2837 .
* Adds fillcolor parameter to transform to fill the target image prior to the transform
* Pipes through the existing fill parameter in `_imaging.transform2` rather than hardwiring it to true.
Note: This _extends_ the api and retains the currently mostly ignored `fill` parameter. This `fill` parameter is currently passed into the ImageTransformHandler api, which has user supplied code that we don't control. If we repurpose that parameter, we risk breaking existing code.

Fillcolor parameter for Transform

---

PIL/Image.py
Tests/helper.py
Tests/test_image.py

Can use truthy values in boolean expressions without first coercing to a `bool`. Removes unnecessary calls to `bool()`.

Remove unnecessary bool() calls throughout project

---

Tests/test_file_webp_alpha.py
depends/install_webp.sh
winbuild/config.py

A test failed after the update with an average pixel value different of 21.3764, so I increased the threshold to 25.

 Updated libwebp to 0.6.1

---

PIL/PngImagePlugin.py
Tests/check_png_dos.py
Tests/test_file_png.py

Always used as a `bool`, but was previously defined as 0/1. Use modern idiomatic Python by using the `bool` type for `bool` arguments.

Make PngImagePlugin.add_text() zip argument type bool

---

Tests/test_file_eps.py

Fixes https://travis-ci.org/python-pillow/docker-images/jobs/318621566
* Bump the epsilon for test_showpage in test_file_eps.py due to arch linux.

Bumped epsilon -- arch is showing 5.6 rather than <5

---

.travis.yml

Fedora 25 went EOL on 2017-12-12:
As of https://github.com/python-pillow/Pillow/pull/2895 we now test on all the supported Fedora versions (26 and 27).

Don't test on EOL Fedora 25

---

Tests/helper.py
Tests/test_image.py

Just occasionally (e.g. the [last master build](https://travis-ci.org/python-pillow/Pillow/jobs/318081653#L3650)) `test_effect_noise` will fail because the random noise will put the same value in these pixels:
```python
self.assertNotEqual(im.getpixel((0, 0)), im.getpixel((0, 1)))
```
* Roll again if we get the same value, 5 attempts 
* flake8
(The randomness comes from libImaging/Effects.c. If it were Python code we could do `from random import Random; random = Random(1538)`.)

Test: avoid random noise failure

---

PIL/Image.py
Tests/test_decompression_bomb.py

Noted in #2410.
*  Added a DecompressionBombError for if the requested size is 2*Image.MAX_PIXELS
Note that this will cause new exceptions, so we should make sure we really want to do this.

RFC: Decompression bomb error

---

PIL/PngImagePlugin.py
Tests/test_file_png.py
docs/handbook/image-file-formats.rst

Fixes #2790, #2782  .
* Added tests to #2790
* Added support in PngInfo for sRGB and cHRM chunks.

#2790 + tests

---

PIL/EpsImagePlugin.py
Tests/images/zero_bb_emptyline.eps
Tests/test_file_eps.py

Allow for an empty line in EPS header data

---

MANIFEST.in

Since https://github.com/python-pillow/Pillow/pull/2901, Scripts now live in their own repo at https://github.com/python-pillow/pillow-scripts.

Scripts no longer part of this package

---

PIL/ImageFont.py
_imagingft.c
docs/installation.rst
libImaging/raqm.h
setup.py

We can't currently distribute a binary of Pillow with support for raqm due to license incompatibility, because while libraqm is MIT licensed, it links to GPL libraries. Unfortunately, this means that nearly no one gets support for complex text, as we're providing binaries on the big three platforms now. 
This PR replaces the build dependency on libraqm with an attempt to dynamically load the dll, should it be installed by the user. To do this, we're shipping the header from the libraqm project (which is MIT licensed), using this for types, and then dynamically resolving the function addresses at runtime. 
To Do:

Dynamically link libraqm

---

docs/index.rst

This page doesn't exist anymore so...
* Remove the broken Gratipay link from the documentation.

Remove the broken Gratipay link

---

.github/CONTRIBUTING.md
docs/installation.rst

Suggesting this as a way of making it clearer that Python 2.6 is no longer supported.

Changed documentation references to 2.x to 2.7

---

docs/releasenotes/5.0.0.rst

Before:
After:
Ref:
http://www.sphinx-doc.org/en/stable/rest.html#inline-markup

Docs: Escape the s next to inline code formatting

---

setup.py

Fix "TypeError: 'NoneType' object is not iterable" for PPC and CRUX

---

winbuild/README.md
winbuild/build.rst

Changed `docs/build.rst` to `winbuild/build.rst`, to better point towards https://github.com/python-pillow/Pillow/blob/master/winbuild/build.rst

Corrected winbuild documentation

---

appveyor.yml

Enable pip cache in the appveyor build so packages are cached.

Enable pip cache in appveyor build

---

src/PIL/IcnsImagePlugin.py

In `.icns` saving, `last_w` is not currently set within the loop, meaning that it doesn't serve it's purpose. This PR fixes that.
The bug has been there since the method was added in #1185

Fixed efficient saving

---

Tests/check_imaging_leaks.py
Tests/check_j2k_leaks.py
Tests/check_jpeg_leaks.py
Tests/helper.py
Tests/test_file_icns.py
Tests/test_file_png.py
Tests/test_font_leaks.py
Tests/test_imagefont.py
Tests/test_shell_injection.py
src/PIL/IcnsImagePlugin.py

Suggestion for #2513 
To set the scaled images within `.icns`, include them in an `append_images` parameter, to match with the `save_all` functionality of other formats. The order of the images does not matter - which image is which can determined by their size.

Allow append_images to set .icns scaled images

---

src/PIL/GifImagePlugin.py

Follow up to 505eb799. Tested by building docs and checking output doesn't changed.

Fix "invalid escape sequence" warning on Python 3.6+

---

Tests/helper.py
src/PIL/EpsImagePlugin.py
src/PIL/Image.py
src/PIL/ImageShow.py
src/PIL/ImageTk.py
src/PIL/TiffImagePlugin.py
src/PIL/_tkinter_finder.py

* Named version attributes are available from Python 2.7+.
* Because 3.4 is our minimum supported 3.x, we can simplify these:
* `sys.version_info >= (3, 4, 0)`
* `sys.version_info >= (3, 3)`
* Into:
* `sys.version_info.major >= 3`

Simplify version checks

---

Tests/test_file_jpeg2k.py
src/PIL/Jpeg2KImagePlugin.py

Fixes #3006, see https://github.com/python-pillow/Pillow/issues/3006#issuecomment-373359618 for details.
Note: adding `p.image.show()` shows just a blank image, whereas this shows the test card:
```python
im = Image.open('Tests/images/test-card-lossless.jp2')
im.show()
```
However, this is also the case in Python 3.2.0 and so another issue.

Fix TypeError for JPEG2000 parser feed

---

docs/reference/Image.rst

Allows hotlinking to include relevant intro:
https://pillow.readthedocs.io/en/latest/reference/Image.html#create-thumbnails

Docs: Move intro text below its header

---

Tests/test_image.py
src/libImaging/File.c

Minor fix for resource leak found by cppcheck.

Fix a resource leak: close fp before return (found by cppcheck)

---

src/libImaging/ImagingUtils.h

This should fix #2956:
https://twitter.com/mraleph/status/980803221718478849

Fix _i2f compilation on some GCC versions

---

setup.py

After https://github.com/python-pillow/Pillow/issues/2940#issuecomment-358326331, python-pillow.org redirects to http://pillow.readthedocs.io/en/latest/

Updated URL

---

Tests/test_imagepath.py
src/path.c

Compiler warning appeared as:
```
src/path.c:574:22: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
Py_TYPE(&item)->tp_name);
^~~~~~~
```
As item is already of type `PyObject*`, and the `Py_TYPE` macro is
equivalent to `(((PyObject*)(o))->ob_type)`, no need for the dereference.
https://docs.python.org/3/c-api/structures.html#c.Py_TYPE

Fix dereferencing type-punned pointer will break strict-aliasing

---

src/PIL/ImagePath.py

The class is always overridden by the C implementation. The Python implementation is unused.

Remove unused Python class, Path

---

src/libImaging/Draw.c

The preprocessor directive `#if 1` always evaluates as true, so the enclosed code is always compiled.
The directive has existed since the original fork from PIL, 9a640e3157150e35f17354517e8c6304fc428060.

Remove unnecessary `#if 1` directive

---

RELEASING.md
setup.py
src/PIL/__init__.py
src/PIL/_version.py

Partially fixes #3082.
It is really confusing for people to find three different constants in PIL module: `VERSION`, `PILLOW_VERSION`, `__version__` and `version`. While `VERSION` is here for historical reasons and does matter, `version` is module is not required to end user at all. My suggestion is to hide it from users by removing from namespace:
```python
In [1]: from PIL import _version
ImportError: cannot import name _version  # Python 2 only
In [2]: import PIL
In [3]: PIL._version
AttributeError: 'module' object has no attribute '_version'
```

Rename PIL.version to PIL._version and remove it from module

---

Tests/test_color_lut.py
src/_imaging.c

From [`PyInt_AsLong()`](https://docs.python.org/3/c-api/long.html#c.PyLong_AsLong) and [`PyFloat_AsDouble()`](https://docs.python.org/3/c-api/float.html#c.PyFloat_AsDouble) docs:
```
Returns -1 on error. Use PyErr_Occurred() to disambiguate.
```
```
This method returns -1.0 upon failure, so one should call PyErr_Occurred() to check for errors.
```

Raise error if it is occurred during conversion in getlist

---

Tests/test_color_lut.py
docs/reference/ImageFilter.rst
src/PIL/ImageFilter.py

This adds the new method `Color3DLUT.transform()` which allows altering table values with a callback.
This also improves the performance in three times of `Color3DLUT.generate()` in two ways: First, using future division instead of direct `float` function call. Second, avoid of extra copying of the table in the constructor.
Also, PR adds autogenerated docs for `Color3DLUT`.

Transforming LUTs

---

README.rst
RELEASING.md
docs/about.rst
docs/index.rst
docs/installation.rst

The new PyPI (Warehouse) has been launched, with redirected links.
https://pypi.org/
https://wiki.python.org/psf/WarehouseRoadmap

Update links to new PyPI

---

winbuild/.gitignore

This would have been necessary before the addition of https://github.com/python-pillow/pillow-depends as a separate repository.
The only relevant line left is `__pycache__`, and that is covered by the base directory .gitignore.

Removed winbuild gitignore

---

docs/reference/ImageDraw.rst

Fixes #3029.
* These functions only work if these requirements are met
* If not, nothing is drawn; there's a silent return
* Rather than changing a 20-year-old API, let's clarify the docs

Clarify bounding box for arc, chord, ellipse, pieslice

---

Tests/test_imagedraw.py
Tests/test_numpy.py
winbuild/appveyor_install_pypy.cmd

It was released in April 2018:
https://morepypy.blogspot.com/2018/04/pypy27-and-pypy35-v60-dual-release.html
We can also re-enable some tests which were a problem with older versions of PyPy.

AppVeyor: upgrade to PyPy 6.0.0

---

Tests/test_file_tiff.py

Instead of raising the `Exception` at https://github.com/python-pillow/Pillow/blob/master/src/PIL/TiffImagePlugin.py#L484 as intended, this test was raising a `NameError` because `ImageFileDirectory_v2` is not imported.

Corrected test

---

winbuild/appveyor_install_msys2_deps.sh

For https://github.com/python-pillow/Pillow/issues/3156.
mingw32 builds fail like this:
```
Collecting pytest
c:\msys64\usr\bin\bash :   Cache entry deserialization failed, entry ignored
At line:3 char:3
+   c:\msys64\usr\bin\bash -l -c c:\\pillow\\winbuild\\appveyor_install ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (  Cache entry d..., entry ignored:String) [], RemoteException
+ FullyQualifiedErrorId : NativeCommandError
Using cached https://files.pythonhosted.org/packages/d3/75/e79b66c9fe6166a90004bb8fb02bab06213c3348e93f3be41d7eaf625554/pytest-3.6.1-py2.py3-none-any.whl
Collecting pytest-cov
Cache entry deserialization failed, entry ignored
Using cached https://files.pythonhosted.org/packages/30/7d/7f6a78ae44a1248 …
```

Temporarily use --no-cache-dir for pip on mingw32

---

Makefile
docs/reference/Image.rst

Python 3 docs are more actively maintained and are the future.

Update Python 2 doc URLs to Python 3

---

.travis.yml
.travis/after_success.sh
MANIFEST.in
build_children.sh

The stuff done in https://github.com/python-pillow/Pillow/pull/1067 to trigger a python-pillow/pillow-wheels build after a successful python-pillow/Pillow (non-PR, master) build hasn't been working for quite some time.
Let's just remove it.
Instead, I propose we enable a [cron job](https://docs.travis-ci.com/user/cron-jobs/) on pillow-wheels.
How about daily, but not if there's been a build in the last 24h?

Remove redundant travis_after_all stuff

---

docs/releasenotes/5.2.0.rst

Alternative to #3188, if 5.1.1 is not released.

Add 5.1.1 release notes into 5.2.0

---

.travis.yml

Just occasionally a single build job fails and I hit the rebuild button and it passes.
Recently `docker pull` failed for a single job:
```console
$ if [ "$DOCKER" ]; then docker pull pythonpillow/$DOCKER:$DOCKER_TAG; fi
Error response from daemon: Get https://registry-1.docker.io/v2/pythonpillow/debian-stretch-x86/manifests/pytest: Get https://auth.docker.io/token?scope=repository%3Apythonpillow%2Fdebian-stretch-x86%3Apull&service=registry.docker.io: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
The command "if [ "$DOCKER" ]; then docker pull pythonpillow/$DOCKER:$DOCKER_TAG; fi" failed and exited with 1 during .
Your build has been stopped.
```
https://travis-ci.org/python-pillow/Pillow/jobs/389764869
---
Let's use the …

Use travis_retry for docker pull to avoid occasional network timeouts

---

src/PIL/BlpImagePlugin.py
src/PIL/Jpeg2KImagePlugin.py
src/PIL/MspImagePlugin.py
src/PIL/_binary.py

tiny bit faster
struct.unpack_from just doesn't read the memory further if input data is too long, so slice stops were unneeded
for non-zero slice starts, struct.unpack_from just adds to the memory offset instead of copying like slices
(was 2 commits, rebased to 1 after changing 3 more files)

unpack_from is faster than unpack of slice

---

src/PIL/Image.py
src/PIL/TiffImagePlugin.py

Fixes #3122.
* Prefer `collections.abc` (new in [Python 3.3](https://docs.python.org/3.7/library/collections.abc.html)) over `collections` for abstract base classes
* "In Python 3.8, the abstract base classes in `collections.abc` will no longer be exposed in the regular `collections` module. This will help create a clearer distinction between the concrete classes and the abstract base classes."
* https://docs.python.org/3.7/whatsnew/3.7.html#deprecated

Fix collections ABCs DeprecationWarning in Python 3.7

---

src/Tk/tkImaging.c

Similar to https://github.com/python-pillow/Pillow/pull/3072, this code is never compiled.
It's been like that since at least PIL 1.1.1, from October 2000, so we get to use the "Hasn't worked in 20 years" label.
https://github.com/hugovk/PIL/blame/master/Tk/tkImaging.c#L107

Remove unnecessary '#if 0' code

---

Tests/test_imagedraw.py
src/libImaging/Draw.c

Resolves #1913
The float values calculated by Pillow create a symmetric ellipse.
However, the issue is converting those float values to ints. Since PIL, `FLOOR` and `+ 0.5` have been used. This produces ellipses that may not be symmetric, since a 0.5 values are consistently rounded up, which has the effect of leaning the ellipse towards the bottom and right.
Instead, I suggest using `FLOOR` when the point is towards the bottom or right, and `CEIL` when it is towards the top or left. This should have the effect of leaning the ellipse towards it's center instead, producing a more symmetric shape.

Changed ellipse point calculations to be more evenly distributed

---

src/PIL/ImageFile.py

Resolves #3184 
Also stops specifying size to `mmap.mmap` explicitly, since is 0 is supplied, it uses the length of the file. It does raise an exception on Windows if the file is empty, but that sounds reasonable.

Changed mmap file pointer to use context manager

---

Tests/test_file_jpeg.py
Tests/test_file_pixar.py
Tests/test_imagefile.py
src/PIL/ImageFile.py

This is a suggestion for #2065, but also allows users to retrieve the mimetype in more general situations.

Added ImageFile get_format_mimetype method

---

Tests/test_imagefont.py
docs/reference/ImageFont.rst
src/PIL/ImageFont.py

New feature: getsize_multiline in PIL.ImageFont to return multiline textsize
* src/PIL/ImageFont.py: Added getsize_multiline() 
* Tests/test_imagefont.py: Added test for multiline textsize
* docs/reference/ImageFont.rst: Added documentation for getsize_multiline

Added getsize_multiline support for PIL.ImageFont

---

Tests/test_imagefont.py
src/PIL/ImageDraw.py

Fixes bug in ImageDraw.multiline_textsize()
* ImageDraw.multiline_textsize() previously returns a multiline_textsize height value includes one extra 'spacing' value than required. Fixed to ignore last added spacing
* Added necessary test to ensure ImageDraw.multiline_textsize() returns the same value as ImageFont.getsize() for single line text

Fixed bug in ImageDraw.multiline_textsize()

---

Tests/test_file_icns.py

Resolves #3138 
Relaxes the failing assert at https://github.com/python-pillow/Pillow/blob/master/Tests/test_file_icns.py#L47 from `assert_image_equal` to `assert_image_similar` with an epsilon of 1.
After that change, the assert at https://github.com/python-pillow/Pillow/blob/master/Tests/test_file_icns.py#L52 fails. For the image being compared, it appears that when the alpha value is 0, the RGB values are turned into 0, 0, 0 on OS X 10.11. I don't think I blame it for that. I have increased the alpha value.

Changed ICNS format tests to pass on OS X 10.11

---

src/libImaging/QuantOctree.c

[QuantOctree.c] Remove erroneous attempt to average over an empty range

---

Tests/test_image_rotate.py
src/PIL/Image.py

This is a small code change to fix missing parameters when the `transform` function recurses.  Without this, alpha images (LA and RGBA) always have a transparent background regardless of the passed in fill color.
* Pass through the `fillcolor` parameter when recursing
Tests all pass on Python 2.7 and 3.5.

Fix transform fill color for alpha images

---

Tests/test_file_pdf.py
src/PIL/PdfImagePlugin.py

This is mirroring the logic from https://github.com/radarhere/Pillow/blob/3bbd0a58109c840a8895f364ffc7127cee04a30b/src/PIL/PdfImagePlugin.py#L96, so that this loop, which uses the values in the `image_refs` array, operates the same as the previous loop, which set the values in the array.

Fixed saving a multiframe image as a single frame PDF

---

Tests/test_file_eps.py
src/PIL/EpsImagePlugin.py

<s>Instead, use [io.open()](https://docs.python.org/2/library/io.html#io.open) wrapper to handle universal newlines for all Python versions.</s> (Different approach taken, see below.)
Fixes warning "DeprecationWarning: 'U' mode is deprecated" in tests.

Avoid deprecated 'U' mode when opening files

---

docs/PIL.rst

The skipping originally applied to ImageFileIO (#375), and ImageFileIO was later removed (#1343) but this line was missed.
(It wasn't obvious as the skipping line comes before the module.)

Docs: Remove redundant module skipping

---

RELEASING.md

5.2.0 wasn't added as a release to https://github.com/python-pillow/Pillow/releases until I did it just now - so this PR adds it to the release checklist.

Added GitHub release to release checklist

---

Tests/test_imagegrab.py

`test_grab` and `test_grab2` are identical. They were added in https://github.com/python-pillow/Pillow/commit/3ec505958ed6225c7d0d6481bf4a6bad#diff-d59b7969d2bd745759553300e6227e73

Removed duplicate test

---

.github/CONTRIBUTING.md

https://github.com/python-pillow/Pillow/blob/master/.github/ISSUE_TEMPLATE.md originally mirrored CONTRIBUTING. It has since received updates - https://github.com/python-pillow/Pillow/commits/master/.github/ISSUE_TEMPLATE.md - so this PR copies those changes back to CONTRIBUTING.

Update CONTRIBUTING from ISSUE_TEMPLATE

---

src/_imaging.c

The surrounding code suggests this should only be freed if it was allocated locally.

Avoid invalid free if out of memory

---

docs/installation.rst

Resolves #3275 
Since #1932, the build flags to enable/disable tk/tcl have no longer been relevant.

Removed old build flags from documentation

---

docs/handbook/image-file-formats.rst

Resolves #3255 by improving documentation regarding the default value of 'loop' when saving. Also improves documentation for other options when reading and saving GIFs.

Improved GIF documentation

---

.appveyor.yml

A temporary fix for #3284, but let's keep that open until this workaround can be removed.
The new pytest 3.7.1 (and 3.7.0) now depends on pathlib2 for Python < 3.4, which depends upon scandir, which doesn't build for PyPy on Windows.
* Temporarily pin `pytest<3.7` on AppVeyor to prevent scandir non-compilation.

CI: Temporarily pin pytest to prevent scandir non-compilation

---

.appveyor.yml

Reverts python-pillow/Pillow#3285
Fixes https://github.com/python-pillow/Pillow/issues/3284
Re: https://github.com/pytest-dev/pytest/issues/3750#issuecomment-412093501

Revert "CI: Temporarily pin pytest to prevent scandir non-compilation"

---

RELEASING.md

Looks like this was missed in https://github.com/python-pillow/Pillow/commit/937443f2a64564335b6e7439160742bc5939fd0c

Update RELEASING example

---

winbuild/build_dep.py

I know this was considered in #2095. It was declined at the time because SourceForge wasn't working, but that is no longer the case.

Download lib if not present in pillow-depends

---

Tests/test_imagechops.py

* `ImageChops` has just two tests in [test_imagechops.py](https://github.com/python-pillow/Pillow/blob/master/Tests/test_imagechops.py):
* `test_logical` tests `logical_* methods
* `test_sanity` only checks methods can run
* This PR adds cases to test the output of methods

Test ImageChops

---

depends/install_extra_test_images.sh

Running the following commands -
```
svn checkout https://github.com/python-pillow/pillow-depends/trunk/test_images
rm -r test_images
```
I get asked if I want to override for .svn files. This PR changes it to `rm -rf` to fix this.

Changed rm command to use force

---

src/_imaging.c
src/_imagingft.c

* _imaging.c exposes:
* `_draw_line` as `draw_line`
* `_draw_lines` as `draw_lines`
* `_draw_point` as `draw_point`
* `_draw_points` as `draw_points`
* However, ImageDraw.py only uses `draw_lines` and `draw_points`
* _imagingft.c exposes `font_getabc` as `getabc`, but unused by the Python layer
* This PR removes the unused functions
* Helps a bit towards #722

Remove unused draw_line, draw_point and getabc

---

Tests/test_qt_image_fromqpixmap.py
Tests/test_qt_image_toqimage.py
Tests/test_qt_image_toqpixmap.py

There are a few tests which call `PillowQtTestCase.setUp`. However, this is unnecessary in these cases, as those test classes inherit from `PillowQtTestCase`, and so the `setUp` method is already called.
The best evidence that this is unnecessary is that this PR passes, as most of the test environments do not have Qt installed.

Removed unnecessary setUp calls

---

RELEASING.md

I was wrong in #3320 - `git add Pillow` is not necessary, as the following line - `git commit -m "Pillow -> 5.2.0" Pillow` lists `Pillow` as it's last argument, meaning that it will add Pillow.

Revert "Add updated submodule in pillow-wheels [ci skip]"

---

Tests/test_image_filter.py
src/PIL/ImageFilter.py

Changed Kernel to subclass BuiltinFilter, instead of the other way around.
Before, BuiltinFilter overrides Kernel's init method with a simple pass statement -
```
class Kernel(MultibandFilter):
name = "Kernel"
def __init__(self, size, kernel, scale=None, offset=0):
...
def filter(self, image):
...
class BuiltinFilter(Kernel):
def __init__(self):
pass
```
After, Kernel adds an init method -
```
class BuiltinFilter(MultibandFilter):
def filter(self, image):
...
class Kernel(BuiltinFilter):
name = "Kernel"
def __init__(self, size, kernel, scale=None, offset=0):
...
```
This should have no effect, it just seems like a nicer way to organise the code.

Changed Kernel to subclass BuiltinFilter

---

Tests/test_imagedraw.py
src/PIL/ImageDraw.py

As evidence that ValueError is required - https://ci.appveyor.com/project/Python-pillow/pillow/build/4127/job/4nr0goie5hrk18q6#L3573

Catch ValueError when processing the edge of an image in ImageDraw.floodfill

---

docs/handbook/writing-your-own-file-decoder.rst

With regards to the blank line, here is what it currently looks like -

Fixed typos

---

.travis.yml
Tests/test_image_access.py
Tests/test_imagefont.py
src/PIL/ImageDraw.py
src/PIL/ImageTk.py
src/PIL/__init__.py

Fixes #3231.
* Fix bug introduced by https://github.com/python-pillow/Pillow/pull/3218 with `PYTHONOPTIMIZE=2`, because that level strips away docstrings resulting in '`NoneType' object has no attribute 'format'`
---
https://ziade.org/2015/11/25/should-i-use-pythonoptimize/ says:
> So yeah, **even if you don't use yourself those options, it's good practice to make sure that your python code is tested with all possible values for PYTHONOPTIMIZE.**
> 
> It's easy enough, just run your tests with **-O** and **-OO** and without, and make sure your code does not depend on docstrings or assertions.
---
* Test two build jobs (chosen arbitrarily) with the two different `PYTHONOPTIMIZE` levels to ensure this stays fixed
* Running `PYTHONOPTIMIZE=1` (same as …

Fix code for PYTHONOPTIMIZE

---

Tests/test_file_libtiff.py
src/PIL/TiffImagePlugin.py

Resolves #1765
#2288 is a PR to significantly improve writing libtiff metadata. This PR is a quick fix for #1765, if we would like to resolve that issue in the short term.

Convert int values of RATIONAL TIFF tags to floats

---

Tests/test_file_tga.py
src/PIL/TgaImagePlugin.py

Added orientation, compression and id_section as TGA save keyword arguments

---

Tests/test_file_webp.py
src/PIL/WebPImagePlugin.py

Close existing WebP fp before setting new fp

---

mp_compile.py
setup.py

Python 3.5's distutils added support for parallel builds, which means
that we don't need to monkeypatch it anymore. But more importantly, this
monkeypatch made build fail (hang in fact) whenever `--parallel` was
passed to `python setup.py build`.
This commit fixes the problem by not applying the monkeypatch on
python 3.5+ and preserve the old behavior (parallel build by default) by
injecting a `parallel` option when it's not specified.

Fix builds with --parallel

---

src/PIL/Image.py

When saving an image, if the extension is not determined it raises a ValueError (while internally it manages a KeyError) so I propose this change
* Image.save raises a ValueError and not a KeyError

From KeyError to ValueError when saving image

---

src/PIL/ImageDraw.py

- Feature improvement: improved performance of `ImageDraw.floodfill()` with  Python built-in `set()` datatype. reduce run time while maintaining memory consumption.
* under `ImageDraw Module`: `ImageDraw.floodfill()`
- changed original *list* datatype to *set* in order to handle pixels in a more efficient manner.
by implementing this change, the floodfill() method is around 40% faster on both of the test cases. The result highly depends on the amount of the pixels to fill. The pixels to be filled are only iterated once, rather than 4 times with original method.
[PR-testcases.zip](https://github.com/python-pillow/Pillow/files/2262254/PR-testcases.zip)
run test.sh to see comparison between methods.

Performance improvement of ImageDraw.floodfill() 

---

.github/ISSUE_TEMPLATE.md

* Add OS version to the issue template
* Prompt for it and Python and Pillow versions
* This might encourage people to fill in the info in bug reports

Issue template: add prompts for versions

---

docs/reference/ImageDraw.rst
docs/reference/ImageFont.rst

Found in https://github.com/python-pillow/Pillow/issues/3125#issuecomment-422330767.
* Raqm doesn't support `btt`
* https://github.com/HOST-Oman/libraqm/search?q=btt&unscoped_q=btt
* https://github.com/HOST-Oman/libraqm/search?q=btt&unscoped_q=ttb
* Update our docs

Docs: 'btt' (bottom to top) is not supported by libraqm

---

src/PIL/Image.py

If we `import numpy as np`, use `np` not `numpy`

Fix docstring typo

---

depends/install_extra_test_images.sh

Alternate suggestion for #3367 
As a way of demonstrating what this code does on failure, here is a test script -
```sh
test_count=-1
svn_checkout()
{
if [ ! -z $1 ]; then
echo ""
echo "Retrying svn checkout..."	
echo ""
fi
test_count=$(( $test_count + 1 ))
if [ $test_count = 2 ]; then
svn checkout https://github.com/python-pillow/pillow-depends/trunk/test_images
else
svn checkout blah
fi
}
svn_checkout || svn_checkout retry || svn_checkout retry || svn_checkout retry
```

Retry svn checkout on failure up to 3 times

---

src/PIL/EpsImagePlugin.py

Usage and this pattern is discussed in Python bug: https://bugs.python.org/issue21363
[detach() docs](https://docs.python.org/3/library/io.html#io.BufferedIOBase.detach)

Use TextIOWrapper.detach() instead of NoCloseStream

---

Tests/test_file_jpeg.py
Tests/test_file_libtiff.py
Tests/test_file_tiff.py
Tests/test_file_tiff_metadata.py

Instead, allow exceptions to bubble up to the unittest exception handler.
Prevents replacing the exception trace with a less informative message. As the exceptions are always unexpected, should not need to catch them explicitly in tests.

Avoid catching unexpected exceptions in tests

---

Tests/test_decompression_bomb.py
Tests/test_image_crop.py
src/PIL/Image.py

Issue being fixed:
DecompressionBombWarning/Error caused by wrong values passed to it in Image._crop
_bomb_decompression_check checks if the size of the image is larger than a certain value.
In Image._crop which is called from Image.crop x1 and y1 are passed to check the size of the crop.
abs(x1 - x0) and abs(y1-y0) should be passed instead, since that represents the size of the crop not just x1 and y1.
* Use absolute value of (x1-x0) and (y1-y0) instead of the existing check
* Pas those values which represent the width and height instead just the location of x1, y1, which is not correct in the context of _decompression_bomb_check
Pull request is solving this issue: https://github.com/python-pillow/Pillow/issues/3312

Fix _crop and tests

---

docs/handbook/tutorial.rst

* Changed `show` note to be more generic - https://pillow.readthedocs.io/en/latest/handbook/tutorial.html#using-the-image-class - firstly, because `xv` is only relevant to Linux, with Mac and Windows using different viewers. Secondly, because `eog` and `display` are also options that can be used in Linux.
* Changed https://pillow.readthedocs.io/en/latest/handbook/tutorial.html#rolling-an-image as crop is no longer lazy

Improved tutorial

---

src/PIL/Image.py

Resolves #1186, while adding in a similar but unrelated note about the `dither` argument.

Improved convert documentation

---

src/_imaging.c

When I compile on macOS, I get
```
src/_imaging.c:555:22: warning: implicit conversion from 'int' to 'char' changes value from 255 to -1
[-Wconstant-conversion]
ink[0] = CLIP8(r);
~ ^~~~~~~~
src/libImaging/ImagingUtils.h:33:52: note: expanded from macro 'CLIP8'
#define CLIP8(v) ((v) <= 0 ? 0 : (v) < 256 ? (v) : 255)
^~~
src/_imaging.c:575:22: warning: implicit conversion from 'int' to 'char' changes value from 255 to -1
[-Wconstant-conversion]
ink[0] = CLIP8(r);
~ ^~~~~~~~
src/libImaging/ImagingUtils.h:33:52: note: expanded from macro 'CLIP8'
#define CLIP8(v) ((v) <= 0 ? 0 : (v) < 256 ? (v) : 255)
^~~
src/_imaging.c:576:22: warning: implicit conversion from 'int' to 'char' changes value from 255 to -1
[-Wconstant-conversion]
ink[1] = CLIP8(g);
~ ^~~~~~~~ …
```

Fixed implicit conversion warnings

---

Tests/test_file_pdf.py
Tests/test_pdfparser.py
docs/handbook/image-file-formats.rst
src/PIL/PdfImagePlugin.py
src/PIL/PdfParser.py

Using https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/pdf_reference_archives/PDFReference.pdf as a reference, this PR suggests two changes -
- By default, set the 'title' field to the filename, minus the extension.
- Add creation and modification dates. Defaults to the current time. This can be read and written as a time.struct_time object

Improve PDF document info

---

Tests/test_file_gif.py
src/PIL/GifImagePlugin.py

Resolves #3315
That issue calls `is_animated` on a GIF, and finds that afterwards, `im.info` now has `comment` with value `None`. `is_animated` should not mutate the value of `im.info` in this way. It happens because the `EOFError` 'frame' has `comment` with value `None`, and it is not removed when `is_animated` seeks back to original frame.
So this PR solves the more general case - subsequent GIF seeks should not just accumulate `info` items.
Note: The following code currently reports `0` loops after the `seek`, but with this PR, it raises a `KeyError`.
```python
im = Image.open('Tests/images/iss634.gif')
print(im.info['loop'])
im.seek(1)
print(im.info['loop'])
```

Changed GIF seek to remove previous info items

---

Tests/test_file_libtiff.py
src/PIL/TiffImagePlugin.py

Resolves #3308
That issue points out that `None` is listed as a `compression` value at https://pillow.readthedocs.io/en/5.2.x/handbook/image-file-formats.html#saving-tiff-images
A commented test for this was added in https://github.com/python-pillow/Pillow/pull/1011

Fixed None as TIFF compression argument

---

src/libImaging/QuantOctree.c

Continuation of and closes #3197.
* Same as #3197 but incorporating review comment to re-use an existing variable
* And rebased on master

Avoid undefined behaviour due to division by zero

---

src/PIL/EpsImagePlugin.py

Fixes #3371.
Replaces and closes #3373.
* Set `startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW` on Windows to prevent the gs dialog popup

Hide the Ghostscript progress dialog popup on Windows

---

docs/releasenotes/5.3.0.rst

To try to keep the headings consistent with recent releases:
https://pillow.readthedocs.io/en/5.2.x/releasenotes/index.html

Move "Image size" under "API Changes"

---

src/PIL/Image.py

The cutoff when converting an image to bilevel (mode "1") is 128.
Fixes #3394.
* Document the correct threshold used to convert to a bilevel image in ```Image.convert()```.

Fixed documentation on bilevel conversion

---

src/PIL/ImageDraw.py

Removes the space between 'non-' and 'homogeneous' - while this looks fine in it's raw form, on Read The Docs is rendered as -

Minor ImageDraw documentation improvement

---

Tests/test_file_webp.py
src/PIL/WebPImagePlugin.py

```python
from PIL import Image, ImageOps
with open('input/256.webp', 'rb') as blob:
Image.open(blob).load()
Image.open(blob).load()
```
```
/home/homm/Code/Pillow/src/PIL/Image.pyc in open(fp, mode)
2611 
2612     try:
-> 2613         fp.seek(0)
2614     except (AttributeError, io.UnsupportedOperation):
2615         fp = io.BytesIO(fp.read())
ValueError: I/O operation on closed file
```

Quick fix: revert #3341 due to regression

---

docs/releasenotes/5.4.0.rst
docs/releasenotes/index.rst
src/PIL/ImageOps.py

This optimises crop+resize operations sequence by using `box` parameter of `resize` function. This gives us:
1. Performance. Results for [lilliput-bench](
https://github.com/discordapp/lilliput-bench):
Before:
```
JPEG 256x256 => 32x32:  1109 Bytes,     avg: 1.43 ms    min: 0.92 ms    max: 4.43 ms
PNG 256x256 => 32x32:   2603 Bytes,     avg: 3.70 ms    min: 3.62 ms    max: 7.14 ms
WEBP 256x256 => 32x32:  654 Bytes,      avg: 2.77 ms    min: 2.48 ms    max: 6.30 ms
GIF 256x256 => 32x32:   1897 Bytes,     avg: 4.89 ms    min: 4.51 ms    max: 11.58 ms
JPEG 1920x1080 => 800x600:      107480 Bytes,   avg: 26.28 ms   min: 24.90 ms   max: 37.08 ms
PNG 1920x1080 => 800x600:       810489 Bytes,   avg: 282.60 ms  min: 277.43 ms  max: 377.78 ms
WEBP 1920x1080 => 800x600:      84960 Bytes,    avg: …
```

Optimise ImageOps.fit by combining resize and crop

---

src/libImaging/TiffDecode.c

JPEG-related tiff pseudo-tags are registered only when tiff image has jpeg compression. Trying to set TIFFTAG_JPEGCOLORMODE on non jpeg-compressed file prints error "Unknown pseudo-tag 65538".
Fixes #3413 .
* Only set `TIFFTAG_JPEGCOLORMODE` pseudo-tag for jpeg-compressed TIFF images.

Only ask for YCbCr->RGB libtiff conversion for jpeg-compressed tiffs

---

Tests/test_features.py
Tests/test_format_hsv.py
Tests/test_pyroma.py

* test_features.py: Some tests were named `check_*` so aren't run. Probably a mistake, as they were bookended by `test_check` and `test_check_features`. Switch to `test_*` so they're run.
* test_features.py: `@unittest.skipUnless` takes a condition and _reason_.
* test_format_hsv.py: Remove unused helper method and redundant parentheses.
* test_pyroma.py: Simplify skipping and remove `setUp`.

Fix some tests

---

.readthedocs.yml

Possible solution for #2763 
Given the intermittent nature of the problem, I can't say anything definitively, but here is my evidence that it might solve it - testing builds of the 5.3.x branch against this, 5.3.x fails 3 out of 6, and this fails 0 out of 6.

Install project using pip in ReadTheDocs build

---

Tests/test_file_gif.py
src/PIL/GifImagePlugin.py

Suggestion for #2949
WebP sets `im.info['background']` to an RGBA tuple. However, GIF uses background as an ['Index into the Global Color Table'](https://www.w3.org/Graphics/GIF/spec-gif89a.txt). This PR converts the value from the tuple to a global color table index when saving as a GIF.
I will note that this isn't perfect - `ImagePalette.getcolor` ignores the alpha part of the RGBA tuple, and I think there a few things wrong with the way that we are handling GIF backgrounds. However, I don't think there is anything wrong with the code that I am adding in.

Change tuple background to global color table index when saving as GIF

---

README.rst
docs/index.rst

* The downloads badge is fixed at Shields.io: https://github.com/badges/shields/pull/2131
* 4 million downloads per month!

Re-add the downloads badge

---

Tests/test_bmp_reference.py
src/PIL/Image.py

If the image cannot be identified, the exclusive fp is closed - https://github.com/python-pillow/Pillow/blob/master/src/PIL/Image.py#L2656
This PR closes the exclusive fp if an uncaught exception is thrown.

Close exclusive fp on open exception

---

Tests/test_imagegrab.py

This PR changes the ImageGrab test to run screencapture silently. Without it, a sound plays when running the test.

Do not play sound when running screencapture command

---

.travis.yml
.travis/after_success.sh
depends/diffcover-install.sh
depends/diffcover-run.sh

* Fix diff-cover checks: 
* Fix install `no such option: --use-wheel`
* It tried to use the old pep8 tool, which is now pycodestyle
* Move the linting to its own job, but do it inside `after_success` so it won't fail the build. This makes it easier to find. I chose 3.6 as the base Python, as it's the newest that doesn't need to download the Python archive, so is faster. It runs first to get fast feedback.
* Name the non-Docker build jobs, so we can clearly see which are Trusty and which are Xenial.

CI: Fix diff-cover, move linting to own job, name the jobs

---

winbuild/build_dep.py

`msbuild_openjpeg` is unused. Also, `nmake_openjpeg` and `msbuild_openjpeg` are identical, so removing the function is not losing any information.

Removed unused function

---

.travis.yml

* Travis CI is removing the `sudo` config option and all builds will soon be on VM-based infrastructure
* https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
* In December, `sudo` won't have any affect
* Now, `sudo: required` is no longer needed
* Now, `sudo: false` can already be removed
* It's only used for the lint job and can already be safely removed

Travis CI: Remove 'sudo' config

---

winbuild/config.py

As per https://github.com/python-pillow/Pillow/pull/3442#issuecomment-433849065, It's fine to wait until #3441 is resolved.
Also changes it to use .tar.gz instead of .zip, in order to use the same pillow-depends file as pillow-wheels

Updated libtiff to 4.0.10

---

Tests/test_imageshow.py
src/PIL/ImageShow.py

* Added UnixViewer implementation of the `get_command` method
* Supply filename through stdin instead of inline in Mac and Unix viewers. This is for the sake of security - rather than simply being quoted through shlex/pipes, the filename is now a variable. Feel free to tell me that this is more convoluted than necessary though, given that the filename being passed in does not originate externally.

ImageShow improvements

---

src/PIL/Image.py

_imagingmodule.c no longer exists. However, some of the definitions can be found at https://github.com/python-pillow/Pillow/blob/master/src/libImaging/Imaging.h#L242

Updated comments

---

src/PIL/features.py
src/_imaging.c

Resolves #3492, by allowing the following code to check for libjpegturbo.
```python
from PIL import features
features.check_feature('libjpegturbo')
```

Added libjpegturbo to check_feature

---

.travis.yml
Tests/createfontdatachunk.py
Tests/helper.py
Tests/test_imagemath.py
mp_compile.py
setup.cfg
src/PIL/Image.py
src/PIL/ImageFilter.py
src/PIL/ImageFont.py
src/PIL/ImageQt.py
src/PIL/ImageTk.py
src/PIL/Jpeg2KImagePlugin.py
src/PIL/JpegImagePlugin.py
src/PIL/PdfParser.py
src/PIL/PngImagePlugin.py
src/PIL/PyAccess.py
src/PIL/SpiderImagePlugin.py
src/PIL/TiffImagePlugin.py
src/PIL/_util.py
winbuild/build.py
winbuild/build_dep.py
winbuild/config.py

* The lint job can now fail the build
* Fix remaining flake8 findings
Here's what `flake8 --statistics --count` reports for master:
```
44    E501 line too long
21    E722 do not use bare 'except'
3     E741 ambiguous variable name 'I'
1     F401 'sys' imported but unused
10    F821 undefined name 'unicode'
```
For each these, we can fix them, ignore on a case-by-case basis (with `noqa`), or exclude the whole check in setup.cfg.
The main decision is:
* do we want to ignore this rule globally but allow new ones in, 
* or let a in a few old exceptions now (possibly fix them later) and prevent new ones coming in
I've gone for the latter, but let me know if there's any you really don't like and would prefer globally ignored.
* E501 line too long: I've …

CI: Allow lint job to fail

---

CHANGES.rst
docs/deprecations.rst
docs/index.rst

* Pytest has a [page for deprecations and removals](https://docs.pytest.org/en/latest/deprecations.html)
* It makes it clear what is going away, what has gone away, and what to use instead, without trawling through release notes
* [Preview](https://pillow-hugovk.readthedocs.io/en/add-deprecations-and-removals-docs/deprecations.html)

Docs: Add page of deprecations and removals

---

Tests/test_file_gif.py
src/PIL/GifImagePlugin.py

When saving a GIF, any values in `im.info` are added to `im.encoderinfo` if the key does not already exist there - https://github.com/python-pillow/Pillow/blob/master/src/PIL/GifImagePlugin.py#L460
In #2803, an RGB image is saved to GIF. GifImagePlugin has a method, `_normalize_mode`, that converts an RGB mode to P. For the image in that issue, Image's `convert` method runs `del(new.info['transparency'])` - https://github.com/python-pillow/Pillow/blob/master/src/PIL/Image.py#L973, deleting the transparency info for the converted image. However, GifImagePlugin has already copied the transparency value from `im.info` to `im.encoderinfo` for later use, so the `del` operation does not have the intended effect.
To fix this, this PR postpones the merging of `im.info` into `im.encoderinfo` until …

Wait until mode is normalized to copy im.info into encoderinfo

---

src/Tk/tkImaging.c
src/_imaging.c
src/encode.c
src/libImaging/Histo.c
src/libImaging/Palette.c
src/libImaging/Quant.c
src/libImaging/QuantOctree.c
src/libImaging/Resample.c
src/path.c

Hello.
With our instance of static analysis software, we found some issues which may cause some troubles with un-terminated buffers and potential leaked storage.
Pages with problems description:
* [CWE-120: Buffer Copy without Checking Size of Input ('Classic Buffer Overflow')](https://cwe.mitre.org/data/definitions/120.html)
* [CWE-772: Missing Release of Resource after Effective Lifetime](https://cwe.mitre.org/data/definitions/772.html)
This PR contains fixes for almost all of the reported issue (some were false-positives) and it doesn't change any functionality. Also, all test should pass.

Fixes for issues reported by static code analysis

---

src/PIL/TiffTags.py

Very few tags have an enum, and for those who don't, computing the hash value can be very expensive, e.g. instances of `fractions.Fraction` as mentioned in [the source](https://github.com/python/cpython/blob/master/Lib/fractions.py#L543).
Using [sigal](https://github.com/saimn/sigal) with a collections of 2000 JPEG images with EXIF leads to a performance improvement of 8% (`Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz` with an SSD).
I used `cProfile` and [snakeviz](https://github.com/jiffyclub/snakeviz) to track down this to calling `__hash__` of `fractions.Fraction` from `TagInfo.cvt_enum`.

Don't try to hash value if enum is empty

---

Tests/test_file_png.py
docs/handbook/image-file-formats.rst
src/PIL/PngImagePlugin.py

Resolves #2908 
The issue requires reading text from chunks located after the main image data. Rather than loading the entire image during `open`, this PR instead uses a decorator to call `load()` when the text data is accessed.
There is also a commit to correct a type in the documentation as noted in the initial issue comment - https://github.com/python-pillow/Pillow/issues/2908#issue-284636458

Read textual chunks located after IDAT chunks for PNG

---

setup.py

Fix pkg-config call: If there is multiple spaces between pkg-config output elements the indexing is not correct ([1] can be an empty string and the value is in [2])
The second commit allow to define *_ROOT using environment variables

Improve configuration

---

setup.py

Fixes #3244
* Search library dirs in `/etc/ld.so.cache` instead of hardcoded assumptions;
* The `_find_strings_in_binary()` parses the cache and extract directories. 
It worked on my Fedora 28 workstation, but with little or even no modification it can works on FreeBSD, NetBSD and Android. Darwin architecture also has the `dyld` command that is similar to `ldconfig` on Linux.

Lookup ld.so.cache instead of hardcoding search paths

---

Tests/test_image_access.py
docs/reference/PixelAccess.rst
src/PIL/Image.py
src/PIL/PyAccess.py

Allow RGB and RGBA values for P image putpixel

---

RELEASING.md

Less RTD work!
Fixes #3391 
* No longer require RTD updates when releasing Pillow, rely on ``stable`` and ``latest`` automated builds.

Update release docs; exclude RTD changes

---

setup.py

Now `_find_library_dirs_ldconfig` returns an empty list when `ldconfig` is missing, then `setup.py` can continue guessing library directories.
Fixes #3526.

Fix build for Termux

---

docs/releasenotes/5.4.1.rst
docs/releasenotes/index.rst

For https://github.com/python-pillow/Pillow/issues/3535. PR intentionally against master, will be cherry-picked into the release branch.

Add 5.4.1 release notes

---

.travis.yml

* Run `check-manifest` on the CI
During 5.4.0 release, `make release-test` failed on:
```
...
1183 passed, 86 skipped in 27.28 seconds
check-manifest
lists of files in version control and sdist do not match!
missing from sdist:
.readthedocs.yml
suggested MANIFEST.in rules:
include *.yml
make: *** [release-test] Error 1
```
The fix was easy (https://github.com/python-pillow/Pillow/commit/d2d438794cdd80bdbc852c884f0473c86fb72ab3), but let's find these sooner, before release day.
Example of a failure without the https://github.com/python-pillow/Pillow/commit/d2d438794cdd80bdbc852c884f0473c86fb72ab3 fix: https://travis-ci.org/hugovk/Pillow/jobs/474177112.

CI: Run check-manifest in lint job

---

Tests/helper.py

With the move to pytest, the class's string method is unused. pytest has its own test progress outputter.

Remove unused PillowTestCase.__str__

---

tox.ini

Improves local test coverage by reducing skipped tests when testing through tox.

Install optional dependencies in tox environment

---

docs/installation.rst

Now available at https://pypi.org/project/Pillow/#history since the PyPI (aka Warehouse) redesign.

Docs: Release history is visible at PyPI

---

.travis.yml

WIP, fixes all build jobs except one: `2.7_with_system_site_packages Xenial`.
---
* Only start Xvfb for Qt, and Qt is only available with the system site packages installs
---
Yesterday Travis CI released a new build image for Xenial:
https://changelog.travis-ci.com/ubuntu-xenial-16-04-build-environment-update-86123
Unfortunately that broke our Xenial builds. Trusty still works.
* Last master pass: https://travis-ci.org/python-pillow/Pillow/builds/479135721
* First master error: https://travis-ci.org/python-pillow/Pillow/builds/479763270
The Travis changelog says:
> The Xenial build environment now comes with PhamtomJS2, a new way to define headless browser testing, via `services: xvfb`, and improved Java language support. …

Fix Travis CI: Only start Xvfb for Qt builds

---

Tests/helper.py

Revert #3575
Now that the PR is merged to master, '2.7_with_system_site_packages Trusty' is failing.
Investigating, I find that the following script raises `NameError: name 'first' is not defined` on Python 3, but  `NameError: name 'second' is not defined` on Python 2. So the original code was not identical to the new code.
```
try:
first
except Exception:
try:
second
except Exception:
pass
raise
```

Revert "Use bare 'raise' to re-raise exceptions"

---

src/PIL/OleFileIO.py

For https://github.com/python-pillow/Pillow/issues/3581.
The vendored version was removed in #2199, on 13 Dec 2016, in favour of the olefile Python package and replaced with a deprecation warning that PIL.OleFileIO would be removed in a future version.
We've had nine quarterly releases since then (4.0.0, 4.1.0, 4.2.0, 4.3.0, 5.0.0, 5.1.0, 5.2.0, 5.3.0, 5.4.0), let's remove the deprecation.

Remove deprecated PIL.OleFileIO in favour of olefile Python package

---

Tests/test_imageops_usm.py
src/PIL/ImageOps.py

For https://github.com/python-pillow/Pillow/issues/3581.
* Remove undocumented functions that were deprecated in https://github.com/python-pillow/Pillow/pull/2735 (4.3.0/2017-10)

Remove deprecated ImageOps functions

---

.travis.yml
tox.ini

Allows contributors to easily run the lint stage with a single command: `tox -e lint`. This creates shorter round trips with CI in case of an error.
Update the Travis configuration to use the new environment to run lint.This allows using a single/common source of truth to reduce differences between Travis and local testing.
The tox environment uses the skip_install feature as static analysis doesn't requiring install the Pillow package itself to run. This feature requires tox 1.9 (2015-02-24), so a minimum tox version was added to the configuration.
https://tox.readthedocs.io/en/latest/config.html#conf-skip_install

Add linting to the tox matrix

---

Tests/test_util.py

Before, the test called the isStringType utility, which has its own,
separate test.
* `test_is_path` unit test calls the correct function

test_is_path calls the correct function

---

Tests/test_file_libtiff.py
src/PIL/PdfParser.py
winbuild/build_dep.py

There's a new release of Flake8 (3.7.1), including a new release of pyflakes (2.1.0), which brings in some new tests which fail:
https://travis-ci.org/python-pillow/Pillow/jobs/486309539#L224
```
./winbuild/build_dep.py:310:9: E117 over-indented (comment)
```
Simple comment indentation.
```
./Tests/test_file_libtiff.py:196:9: F723 syntax error in type comment 'dummy value'
```
It now checks mypy type comments. This one isn't a real mypy type comment, so change `type:` to `Type:`.
```
./src/PIL/PdfParser.py:396:9: F821 undefined name 'file'
./src/PIL/PdfParser.py:396:9: F821 undefined name 'Union'
```
The `Union` one can be fixed with `from typing import Union`, but that introduces a dependency on the mypy `typing` module. We have issue https://github.com/python-pillow/Pillow/issues/2625 …

Fix Flake8

---

src/PIL/Image.py

In the event of a `SystemExit` or `KeyboardInterrupt`, file resources should still be cleaned up before re-raising the exception.
https://docs.python.org/3/library/exceptions.html#exception-hierarchy

Catch BaseException for resource cleanup handlers

---

src/PIL/EpsImagePlugin.py

See #3322
This change is discussed in that issue. However, where the issue suggests changing both stdin and stdout, this PR only changes stdin. Changing stdout as well should not be necessary to resolve the issue, and so it is not done here, to avoid potential output.
As for why this code exists in the first place, the duplicate `devnull`s were added in #2253, replacing two `PIPE`s. The reason for the stdin pipe was removed in #506. I look at these series of changes and would believe that the current code is an accident, rather than deliberate. So this PR is a minor cleanup from that angle.
Also, now that #3587 has added Ghostscript to AppVeyor, this PR can said to not cause a failure in Windows CI.

Changed EPS subprocess stdin from devnull to None

---

Tests/test_file_png.py
src/PIL/PngImagePlugin.py

Resolves #3557
This copies the logic for handling unknown PNG chunks in `_open` - https://github.com/python-pillow/Pillow/blob/7bf5246b93cc89cfb9d6cca78c4719a943b10585/src/PIL/PngImagePlugin.py#L581-L583

Allow for unknown PNG chunks after image data

---

.travis.yml

* Test Python 3.8-dev on Travis CI
* Python 3.8.0 is due out on 2019-10-20, or after three Pillow releases.
* https://www.python.org/dev/peps/pep-0569/#release-schedule

Test Python 3.8-dev ahead of 3.8.0's expected 2019-10-20 release

---

src/PIL/Image.py

Two identical types can be compared using the `is` operator. Object identity is slightly faster than a string comparison as well.

Slightly simplify Image.__eq__

---

Tests/test_util.py
src/PIL/_util.py

Now, for functions which accept either a path or file object, the
predicate will pass on Paths and not attempt to call .read on them
before opening.
The pathlib module was added in 3.4 but os.path functions did not start
accepting path-like objects until 3.6, so that is the version after
which this implementation is defined.
Added a unit test to make sure isPath accepts Path objects. The unit
test is skipped if python version is not 3.6 or later.

_util.isPath returns True for pathlib.Path objects

---

src/PIL/TiffImagePlugin.py

Windows binaries are linked to a libtiff library, which has LZMA (Python >=3.5), WebP, and ZStd compression codecs enabled. However, Pillow currently fails to open TIFF files that use these compressions.

Add TIFF compression codecs: LZMA, Zstd, WebP

---

Tests/test_imageqt.py
docs/deprecations.rst
docs/reference/ImageQt.rst
docs/releasenotes/6.0.0.rst
src/PIL/ImageQt.py

* Qt 4 reached end-of-life on [2015-12-19](https://blog.qt.io/blog/2015/05/26/qt-4-8-7-released/). Its Python bindings are also EOL: PyQt4 since [2018-08-31](https://www.riverbankcomputing.com/news) and PySide since [2015-10-14](https://en.wikipedia.org/wiki/PySide).
* Deprecate support for PyQt4 and PySide
* Please upgrade to PyQt5 or PySide2

Deprecate support for PyQt4 and PySide

---

Tests/test_image_transpose.py
src/libImaging/Geometry.c

Added support for I;16 modes for more transpose operations

---

Tests/test_file_container.py
src/PIL/ContainerIO.py

Better follows the interface of `IOBase.isatty`:
https://docs.python.org/3/library/io.html#io.IOBase.isatty

Make ContainerIO.isatty() return a bool, not int

---

src/PIL/PdfParser.py

When bytes warnings are enabled with the `-b` argument, the `PdfDict` class would emit a warning.
https://docs.python.org/3/using/cmdline.html#miscellaneous-options
> -b
>
> Issue a warning when comparing `bytes` or `bytearray` with `str` or `bytes` with `int`.
Object attributes are always type str, so can safely encode them without a type check. Observe:
```
$ python3
>>> o = object()
>>> setattr(o, b'foo', b'bar')
TypeError: attribute name must be string, not 'bytes'
```

Fix 'BytesWarning: Comparison between bytes and string' in PdfDict

---

Tests/test_000_sanity.py
Tests/test_file_libtiff.py
src/PIL/Image.py
src/PIL/ImageCms.py
src/PIL/PdfParser.py
src/PIL/__init__.py
winbuild/build_dep.py

For https://github.com/python-pillow/Pillow/issues/3581.
* Includes PR https://github.com/python-pillow/Pillow/pull/3623 to fix unrelated lint warnings
* Remove deprecated `VERSION`, the old forked PIL version number 1.1.7

Remove deprecated VERSION

---

src/PIL/Image.py

instead of importing again from io (lgtm suggestion)
Fixes # .
* remove an import from io, as io is globally imported on top of the module
* 
*

Use the already imported io

---

src/PIL/Image.py

* Since #2527, macOS saves to a temp PNG before showing, not a temp BMP

Update docs: macOS saves to a temp PNG before showing

---

src/PIL/ImageFile.py

This has no practical value at the moment, this is just allowing for the possibility of an image having a `custom_mimetype` without having a `format`.

Improved get_format_mimetype logic

---

Tests/test_image_quantize.py
docs/releasenotes/6.0.0.rst
src/PIL/Image.py

Default the option to `1`, as per original setting
* Allow `Image.quantize` to supply it's own `dither` keyword argument. 
* Defaults to `1`, to ensure backward compatibility.

Add option to set dither param on quantize

---

src/libImaging/QuantHash.c
src/libImaging/QuantHash.h

Fixes #3546.
Alternative to and closes https://github.com/python-pillow/Pillow/pull/3550.
* https://github.com/python-pillow/Pillow/issues/3546 points out a suspicious expression which checks the same thing twice:
`if (h->keyDestroyFunc || h->keyDestroyFunc) {`
* One option is to fix it. See PR #3550 for:
`if (h->keyDestroyFunc || h->valDestroyFunc) {`
* However, the expression can never be True (and [isn't covered by tests](https://codecov.io/gh/python-pillow/Pillow/src/7447b44edfe152a8c6857f417f85219a3c450625/src/libImaging/QuantHash.c#L318)), because the only place these functions are set are in `hashtable_set_value_destroy_func` and `hashtable_set_key_destroy_func`
* These functions are never called, and aren't exposed to the Python layer, so can …

Remove unused C hashtable functions

---

Tests/test_numpy.py

When running Python with the `-b` command line argument, fixes warnings:
Tests/test_numpy.py::TestNumpy::test_1bit
Pillow/Tests/test_numpy.py:118: BytesWarning: Comparison between bytes and string
arr_bool = numpy.array([[1, 0, 0, 1, 0], [0, 1, 0, 0, 0]], 'bool')
Tests/test_numpy.py::TestNumpy::test_point_lut
Pillow/Tests/test_numpy.py:170: BytesWarning: Comparison between bytes and string
lut = numpy.array(data, dtype='uint8')
Tests/test_numpy.py::TestNumpy::test_to_array
Pillow/Tests/test_numpy.py:146: BytesWarning: Comparison between bytes and string
self.assertEqual(np_img.dtype, numpy.dtype(dtype))

Fix BytesWarning in Tests/test_numpy.py

---

docs/reference/open_files.rst
src/PIL/ImageFile.py

`handles_eof` was removed in 90760a5f3020ada06bf752ae6e98dbfafc0aeb48.

Remove additional references to removed handles_eof

---

Tests/test_file_gif.py
src/PIL/GifImagePlugin.py

Seen in #3629
```python
im = Image.open("Tests/images/iss634.gif")
im.seek(2)
im.seek(1)
```
Expected
Result without the fix

Fixed GIF bug when rewinding to a non-zero frame

---

docs/releasenotes/6.0.0.rst

Release notes for the MIME type changes from #3525, #3688 and #3520, and the TIFF compression codec changes in #3555.

MIME type and TIFF compression codec release notes

---

src/_imaging.c
src/_imagingcms.c
src/_imagingft.c
src/decode.c
src/encode.c

The [Python 3.8 Travis job](https://travis-ci.org/python-pillow/Pillow/jobs/510918029) has started failing. A test for no unclosed file warning is failing on a deprecation warning that was recently added - https://github.com/python/cpython/pull/12473/commits/0895793194cd5f1153d2a286ed3a4fc876149b16 
This PR fixes the situation.

Fixed deprecation warnings

---

winbuild/appveyor_install_pypy.cmd

* PyPy 7.1.0 is out, let's use it on AppVeyor 
* https://morepypy.blogspot.com/2019/03/pypy-v71-released-now-uses-utf-8.html

AppVeyor: Upgrade to PyPy 7.1.0

---

src/PIL/JpegImagePlugin.py

In case we need to call _getexif from the outside, since it's already called while parsing.
This give a great improvement in my test using [sigal](saimn/sigal): parsing a library of 379 photos (without resizing, only metadata reading) went from 2.36295 seconds down to 1.92881 (mean time over 3 rounds).
Caching costs memory though. But this small PR is here to start the discussion.

Cache EXIF information

---

Tests/test_file_tiff.py
src/PIL/TiffImagePlugin.py

Resolves #3712
Currently, `__next` is the position of the next frame after the current one. If a backwards seek has been made, then when `_seek` skips past all the frame positions it knows about, [it goes to the next frame](https://github.com/python-pillow/Pillow/blob/3e9457a034736cd4e320cfcddbc2de7cd4f4d7e5/src/PIL/TiffImagePlugin.py#L1050) after the frame it started at, instead of the next frame at the end.
This PR changes `__next` to be the position of the next frame after the furthest frame that has been seeked to, fixing this bug.

 Fixed TIFF bug when seeking backwards and then forwards

---

src/PIL/Image.py

This is incorrect. It should be 256, not 255.
```python
>>> from PIL import Image, ImagePalette
>>> im = Image.open("Tests/images/hopper.gif")
>>> im.load()
<PixelAccess object at 0x10eee3790>
>>> original = im.palette.palette
>>> new = im.remap_palette(list(range(255))).palette.palette
>>> print("same" if new == original else "changed")
changed
>>> new = im.remap_palette(list(range(256))).palette.palette
>>> print("same" if new == original else "changed")
same
```
Just to demonstrate that 257 is too far -
```python
>>> new = im.remap_palette(list(range(257))).palette.palette
File "PIL/Image.py", line 1715, in remap_palette
new_positions[oldPosition] = i
IndexError: list assignment index out of range
>>> 
```

Corrected remap_palette documentation

---

Tests/test_image.py
src/PIL/Image.py

Resolves #3496
In that issue, a bus error occurs when opening an image and saving it back to the same location. It was described as relating to mmap. Investigating, I find that the bus error occurs at https://github.com/python-pillow/Pillow/blob/d1f865e02ae1731eb41a981ea9a45613e0b91ddc/src/libImaging/Pack.c#L459
So presumably that is conflicting with mmap.
The same block of code that sets up mmap also marks the image as readonly.
https://github.com/python-pillow/Pillow/blob/d1f865e02ae1731eb41a981ea9a45613e0b91ddc/src/PIL/ImageFile.py#L185-L191
https://pillow.readthedocs.io/en/5.4.1/releasenotes/3.3.2.html
> The image was marked readonly, so Pillow would not ordinarily write to that memory without duplicating the image first.
Given the general testing requirement of operating on temp …

Ensure image is mutable before saving

---

Tests/test_file_jpeg.py
src/PIL/IptcImagePlugin.py
src/PIL/JpegImagePlugin.py

Helps #2817 by allowing the Photoshop resolution data to be read directly.
References -
- https://sno.phy.queensu.ca/~phil/exiftool/TagNames/JPEG.html
- https://sno.phy.queensu.ca/~phil/exiftool/TagNames/Photoshop.html

Read Photoshop resolution data

---

docs/installation.rst

pillow-wheels now tests LCMS 2.9 - https://github.com/python-pillow/pillow-wheels/blob/0070db36ee8ef06aa9d3adc2296241bf1cafb01f/config.sh#L14

Updated lcms tested versions

---

Tests/test_file_tiff.py
src/PIL/TiffImagePlugin.py

* Because `__next` reveals if there is a next frame or not, `_is_animated` can be determined on the initial seek. That also means that the tests can be simplified slightly, because `is_animated` no longer interacts with `_n_frames`. You might think that this means that the `is_animated` decorator can be replaced with just a variable. However, `MicImageFile` inherits `TiffImageFile`, and `is_animated` can't be set directly in that circumstance.
* Because `__next` reveals if there is a next frame or not, `_n_frames` can be populated automatically if seeking to the last frame.
* The search in `n_frames` for the last frame can be made faster by starting from the last frame ever seeked, rather than just from the current position.

Improvements to TIFF is_animated and n_frames

---

src/PIL/JpegImagePlugin.py
src/PIL/MpoImagePlugin.py

* Multiply the performance of opening an MPO file by two.
Before:
```py
%timeit Image.open('Tests/images/frozenpond.mpo')
1000 loops, best of 5: 1.51 ms per loop
```
After:
```py
%timeit Image.open('Tests/images/frozenpond.mpo')
1000 loops, best of 5: 779 µs per loop
```
I thought about multiple strategies to avoid a double call to `JpegImageFile._open` that is costly in this use case:
* `__init__` with JpegInstanceFile object. This is the cleanest, by very difficult to achieve, since an instance has at least three inherited classes with many attributes that can be initialized.
* Delegate. Same as above. A delegate is nice, but it should be done in `ImageFile` itself, and it renders every method call more costly.
* Downcasting. This is maybe the …

Fast MPO open

---

docs/handbook/image-file-formats.rst

Changes proposed in this pull request, all documentation changes:
* TIFF: describe num_frames and seek()/tell()
* Link methods to PIL.Image class instead of the Python file object
* It doesn't seem like the Spider plug-in actually has an 'nimages' attribute
* Fix markup for exception name
* Remove reference link for two modules that no longer exist

Describe multiframe features for TIFF/GIF

---

.github/CONTRIBUTING.md
README.rst
docs/index.rst

Codecov is our primary coverage tool.

Docs: Link to Codecov rather than Coveralls

---

Tests/test_file_mpo.py
Tests/test_imagefile.py
src/PIL/ImageFile.py
src/PIL/JpegImagePlugin.py
src/PIL/PngImagePlugin.py
src/PIL/TiffImagePlugin.py
src/PIL/WebPImagePlugin.py

Resolves #520
In addition to the methods described in that issue, I have also added `get_ifd()`, for reading specified subdirectories -
* The Interop EXIF subdirectory, to help #3270. Reference documentation -https://www.awaresystems.be/imaging/tiff/tifftags/interoperabilityifd.html
* The Makernote subdirectory, to resolve #2081
---
Regarding #2081 -
MPO files can have EXIF data for separate images (Page 9 of http://www.cipa.jp/std/documents/e/DC-007_E.pdf). This PR changes `im.info["exif"]` to be specific to the current MPO frame.
Within the EXIF data of the second image in files in #2081, there is a Makernote EXIF tag containing parallax data. However, the MakerNote tag does not have consistent structure across MPO images - it is manufacturer specific. See …

Added EXIF class

---

Tests/test_imageops.py
docs/handbook/image-file-formats.rst
docs/releasenotes/6.0.0.rst
src/PIL/Image.py
src/PIL/ImageFile.py
src/PIL/ImageOps.py
src/PIL/JpegImagePlugin.py
src/PIL/PngImagePlugin.py
src/PIL/WebPImagePlugin.py

Sequel to #3687, incorporating #3625 
Now that Pillow can modify EXIF information, change the `exif_transpose` method to not just record internally that a transposition has occurred, but actually remove it from the EXIF data that specified it in the first place.

Improve exif_transpose

---

RELEASING.md

Updating the release checklist after the default ReadTheDocs was changed to stable in https://github.com/python-pillow/Pillow/issues/3391#issuecomment-451302427

Stable is now the default ReadTheDocs version

---

.appveyor.yml
winbuild/build.py
winbuild/build_dep.py
winbuild/config.py

* Added Freetype to all AppVeyor builds except Mingw
* Removed use of Python 3.4
* Updated Ghostscript to 9.27
* Changed Visual Studio 2008 to 2010, as Visual Studio 2008 reached end of support on April 10, 2018 - https://support.microsoft.com/en-au/help/4043450/products-reaching-end-of-support-for-2018

AppVeyor improvements

---

.travis.yml
Tests/test_numpy.py
azure-pipelines.yml
docs/installation.rst

* Trusty is EOL this month https://linuxlifecycle.com/
* Remove from CIs
* Switch `PYTHONOPTIMIZE` jobs to Xenial
* We no longer need the `before_script:` section, Xenial uses `services: xvfb` instead of explicit `xvfb start` https://blog.travis-ci.com/2018-11-08-xenial-release
* Remove a NumPy workaround for Trusty and already dropped Precise
Related: https://github.com/python-pillow/docker-images/pull/54 and https://github.com/python-pillow/pillow-wheels/pull/115.

Drop support for EOL Ubuntu 14.04 (Trusty Tahr)

---

.travis.yml
azure-pipelines.yml

Docker images were updated in https://github.com/python-pillow/docker-images/pull/54.
* Add Docker image for Ubuntu 18.04 Bionic
* Update Docker filename for Ubuntu 16.04 Xenial
* For both Travis CI and Azure Pipelines

Add Ubuntu 18.04 Bionic, update 16.04 Xenial filename

---

docs/deprecations.rst

* The source code makes it clear when it will be removed (see below).
* Do the same in documentation.
https://github.com/python-pillow/Pillow/blob/e8b2da587f721e9e7fee7135dee159b9330098f4/src/PIL/__init__.py#L20
https://github.com/python-pillow/Pillow/blob/e8b2da587f721e9e7fee7135dee159b9330098f4/src/PIL/Image.py#L28

Document clearly PILLOW_VERSION removal

---

src/PIL/ImageCms.py

I was getting the following error when trying to use `ImageCms` when using `pillow` in a Miniconda insallation (i.e. a minimal version of Anaconda):
```
In [1]: from PIL import ImageCms                                                                                           
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~/mc37/lib/python3.7/site-packages/PIL/ImageCms.py in <module>
22 try:
---> 23     from PIL import _imagingcms
24 except ImportError as ex:
ImportError: cannot import name '_imagingcms' from 'PIL' (/Users/warren/mc37/lib/python3.7/site-packages/PIL/__init__.py)
During handling of the above exception, another exception occurred:
ModuleNotFoundError …
```

Make import from _util a relative import.

---

Tests/test_numpy.py
src/libImaging/Unpack.c

Fixed numpy bool bug

---

docs/installation.rst

Our docs currently state that 'Windows support: Libimagequant requires VS2013/MSVC 18 to compile'.
However, https://pngquant.org/lib/ instructs users to 'Use Visual Studio 2015', so I have changed it to 'VS2015/MSVC 19'. The updated MSVC number comes from looking up Visual Studio 2015 in https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B#Internal_version_numbering

Correct libimagequant installation requirements

---

src/libImaging/BoxBlur.c
src/libImaging/UnsharpMask.c

* Removes Python.h header from a couple of python-free libImaging files.

Remove Python.h where not needed

---

docs/reference/ImageStat.rst

Fixes #1606.
* Document format limitations of `ImageStat.Stat.extrema`
* And recommend more efficient `Image.getextrema`

Document format limitations of ImageStat.Stat.extrema

---

Tests/test_imagefont.py
src/PIL/ImageFont.py

Resolves #3145 by loading fonts from non-Unicode paths on Windows into memory before passing them to FreeType.

Fixed loading font with non-Unicode path on Windows

---

Tests/check_large_memory.py
src/decode.c
src/libImaging/BcnDecode.c
src/libImaging/BitDecode.c
src/libImaging/FliDecode.c
src/libImaging/GifDecode.c
src/libImaging/HexDecode.c
src/libImaging/Imaging.h
src/libImaging/Jpeg2KDecode.c
src/libImaging/JpegDecode.c
src/libImaging/PackDecode.c
src/libImaging/PcdDecode.c
src/libImaging/PcxDecode.c
src/libImaging/RawDecode.c
src/libImaging/SgiRleDecode.c
src/libImaging/SunRleDecode.c
src/libImaging/TgaRleDecode.c
src/libImaging/TiffDecode.c
src/libImaging/XbmDecode.c
src/libImaging/ZipDecode.c

Fixed bug in decoding large images

---

Tests/test_imagetk.py
src/PIL/ImageTk.py
src/Tk/tkImaging.c

Fixed ImageTk getimage

---

.github/CONTRIBUTING.md
.github/SECURITY.md

* GitHub have a new way to show the security policy under a dedicated "Security" tab
* Move the info to the new file (avoid duplication)
* Link from the old place to the new place
* More info:
* https://github.blog/2019-05-23-introducing-new-ways-to-keep-your-code-secure/#open-source-security
* https://help.github.com/en/articles/adding-a-security-policy-to-your-repository

Move security policy to show up more clearly in the GitHub UI

---

.github/ISSUE_TEMPLATE.md

While Pillow currently has an issue template, the community profile checklist is not detecting this.
https://help.github.com/en/articles/about-issue-and-pull-request-templates
> To be included in the community profile checklist, issue templates must be located in the .github/ISSUE_TEMPLATE folder and contain valid name: and about: YAML front matter.
So this PR adds those variables. I've based the values here on one of the standards.

Update issue template for community profile checklist

---

src/PIL/Image.py

Remove unnecessary numeric placeholders from format strings

---

.github/FUNDING.yml

GitHub has new ways to sponsor open-source projects, including making Tidelift more visible.
This is the config for Tidelift, which also needs a checkbox ticking under settings (I don't have access) like this:
https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository#displaying-a-sponsor-button-in-your-repository
More info:
* https://github.blog/2019-05-23-announcing-github-sponsors-a-new-way-to-contribute-to-open-source/
* https://blog.tidelift.com/tidelift-partners-with-github-funds-4000-open-source-projects
* https://tidelift.com/subscription/how-to-connect-tidelift-with-github

Set up GitHub Sponsors with Tidelift

---

docs/handbook/overview.rst

Changes a reference at https://pillow.readthedocs.io/en/latest/handbook/overview.html to link to the method, rather than just being highlighted text.

Link method in docs

---

Tests/test_pyroma.py

PR https://github.com/python-pillow/Pillow/pull/3752 relaxed a Pyroma test because (https://github.com/python-pillow/Pillow/pull/3752#issuecomment-476852312):
> Pyroma was failing because "Your package does not have license data". When there's a known Trove licence, `licence` can and should be omitted, according to https://github.com/pypa/packaging.python.org/pull/492.
> 
> I've reported this to pyroma (https://github.com/regebro/pyroma/issues/38) and relaxed our test in the meantime.
Pyroma has now fixed https://github.com/regebro/pyroma/issues/38 and released it in version 2.5, which means Pillow again scores a 10.
Let's undo the workaround (also fixes the build eg. https://travis-ci.org/python-pillow/Pillow/builds/540460207).

Tighten fixed pyroma test

---

src/PIL/ImageShow.py

Resolves #3895
In the issue, it is reported that macOS 10.15 moves Preview from /Applications to /System/Applications. We could instruct Pillow to test for the operating system version, and use the relevant path, but I think it would be simpler to just stop using an absolute path.

Changed Preview application path so that it is no longer static

---

Tests/test_file_psd.py
Tests/test_imagesequence.py
src/PIL/ImageSequence.py
src/PIL/PsdImagePlugin.py

* PSD frames start from 1, not 0. This PR changes `ImageSequence` to use this.
* PSD was closing the file pointer after load. This is not correct, as it is a multiframe format. This is because it was missing `_close_exclusive_fp_after_loading = False`.

Improve handling of PSD frames

---

Tests/test_image_mode.py
Tests/test_imageshow.py
src/PIL/ImageMode.py
src/PIL/ImageShow.py

Resolves #3868. ImageShow converts images to their base mode, unless they are 1 or RGBA. The issue reports that LA images lose their transparency - this is because the base mode is L. This PR resolves the issue by adding an exception for LA, adding to the existing exceptions for 1 and RGBA - although only if the output image format is PNG, since BMP cannot save in LA.
Unrelated to that problem, but around the same code, ImageShow has a condition to test for 'I;16' modes, stating that L is to be used instead of the base mode in those cases. However, `Image.getmodebase("I;16")` is L, so there is no difference. I have added a commit to add more mode descriptors to cover all I;16 modes, so that the ImageShow condition can be removed.
In doing that, I did find that ImageMode was listing the …

Do not down-convert if image is LA when showing with PNG format

---

src/PIL/ImageFont.py

This gave me encoding warnings when running pytest on Python 2.7.

Replace non-ascii quotes from docstring

---

Tests/test_features.py
Tests/test_main.py
src/PIL/__main__.py
src/PIL/features.py

I recently came across a scenario where Pillow was installed in a VM
with limited OS libraries. To help debug, I was curious what formats
were supported. I think the following feature be useful for such scenarios:
If you like the idea, but want some alterations in the output format, let me know. I'm happy to adjust it.
---
To help debug and show supported formats, users can run:
$ python -m PIL
to get basic format and support information about the installed version
of Pillow.
The new feature works as follows:
$ python -m PIL
Pillow 6.1.0.dev0
Platform linux 3.7.3 (default, May 11 2019, 00:38:04)
[GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]
Supported formats:
BLP
Extensions: .blp
Features: open
BMP (image/bmp)
Extensions: .bmp
Features: open, save
BUFR
Extensions: .bufr
Features: open, save
…

Add __main__.py to output basic format and support information

---

Tests/test_lib_pack.py
src/libImaging/Unpack.c

Added CMYK;16B and CMYK;16N unpackers

---

src/libImaging/Pack.c
src/libImaging/Unpack.c

Fixes #3408 
Unpacking and packing code is not valid for SPARC CPUs as it is working with 32bit integers on unaligned addresses. This fix reverts some 'optimizations' so that access is aligned properly.
It seems to me that other platforms can benefit from this as well (e.g. ARM will not be faster with unaligned access), but I cannot test it elsewhere and this works for us. I can however improve as needed.

Fix SPARC memory alignment issues in Pack/Unpack functions

---

Tests/test_imagefont.py
src/PIL/ImageFont.py
src/_imagingft.c

Resolves #3853, alternative to #3854
The issue reports that loading a non-font as bytes into `ImageFont.truetype` causes a crash. The alternative PR concludes that it is because of memory being free twice - one in `getfont`, and once in `font_dealloc`.
https://github.com/python-pillow/Pillow/blob/9d5a50a0fd12f6ed0feae39d5602d33857febaa5/src/_imagingft.c#L316-L318
https://github.com/python-pillow/Pillow/blob/9d5a50a0fd12f6ed0feae39d5602d33857febaa5/src/_imagingft.c#L1034-L1041
The alternative PR solves this by removing the `PyMem_Free` from `getfont`. This PR suggests instead setting `self->font_bytes` to null after the memory is freed the first time.
Also, the alternative PR points out that once the error is raised, `os.path.basename(font)` is called - which doesn't work if `font` is a …

Fixed crash when loading non-font bytes

---

Tests/32bit_overflow_check.py
Tests/test_core_resources.py
src/_imaging.c

* Fixing a potential integer overflow in ImagingMemorySetBlocksMax
The integer blocks_max is properly sanitized before being used in an arithmetic operation.
This PR should fix this issue by adding an upper limit to this variable.
If the error message is not appropriate, please do let me know and I will fix it accordingly.

Adding an upper limit for blocks_max in _set_blocks_max

---

src/_imagingft.c
src/encode.c

`Py_ssize_t` uses the 'n' specifier, not 'i'. If `Py_ssize_t` is bigger than `int`, this can be fine on little-endian systems but is very broken on big-endian systems as values end up 2**32 times bigger.
The previous change was a bit inconsistent and only changed `src/encode.c`, but not `src/decode.c`, so I'm not sure if I should have gone the other way and reverted the `int`->`Py_ssize_t` change instead.
Fixes #3841.
Fixes #3840.

Pass the correct types to PyArg_ParseTuple

---

.travis/script.sh

The next time that the Python 3.8 job is run, it will fail with
> ERROR: usage: pytest.py [options] [file_or_dir] [file_or_dir] [...]
> pytest.py: error: unrecognized arguments: -vx
This is connected to the recent release of pytest 5.0.
Splitting 'vx' into separate flags, I find that it passes again.

Split pytest flags

---

Tests/test_image_entropy.py
selftest.py
src/PIL/Image.py
src/_imaging.c

This calculates the entropy for the image, based on the histogram.
Because this uses image histogram data directly, the existing C function underpinning the `image.histogram()` method was abstracted into a static function to parse extrema tuple arguments, and a new C function was added to calculate image entropy, making use of the new static extrema function.
The extrema-parsing function was written by @homm, based on the macro abstraction I wrote, during the discussion of [my first entropy-method pull request](https://github.com/python-pillow/Pillow/pull/3530): https://github.com/python-pillow/Pillow/pull/3530#discussion_r245379871
The original PR had code with issues with `log2` and the use of the standard math library – @radarhere corrected these: …

Added an `image.entropy()` method (second revision)

---

Tests/test_file_libtiff.py
src/PIL/TiffImagePlugin.py

Updated TIFF tile descriptors to match current decoding functionality

---

setup.py

* This adds CPPFLAGS to the list of environment variables (currently CFLAGS and LDFLAGS) searched when looking for includes and library directories, as CPPFLAGS may also include `-I` options.

Include CPPFLAGS when searching for libraries

---

src/decode.c
src/libImaging/TiffDecode.c
src/libImaging/TiffDecode.h

Use unsigned int to store TIFF IFD offsets

---

Tests/test_imagesequence.py
docs/releasenotes/6.1.0.rst
src/PIL/ImageSequence.py

Resolves #3758 
Adds a new method to apply a supplied function to all frames of an image at once. So, for example,
```python
from PIL import Image, ImageSequence
im = Image.open('Tests/images/g4-multi.tiff')
ims = ImageSequence.all_frames(im, lambda im_frame: im_frame.rotate(180))
ims[0].save('out.tiff', save_all=True, append_images=ims[1:])
```

Added ImageSequence all_frames

---

Tests/test_file_tiff.py
src/PIL/TiffImagePlugin.py

Continuation of #3924, if that's okay by @cgohlke

Add TIFFTAG_SAMPLEFORMAT to blocklist

---

src/_imaging.c
src/libImaging/Access.c
src/libImaging/Bands.c
src/libImaging/ColorLUT.c
src/libImaging/Convert.c
src/libImaging/Draw.c
src/libImaging/Filter.c
src/libImaging/Geometry.c
src/libImaging/GetBBox.c
src/libImaging/Histo.c
src/libImaging/Pack.c
src/libImaging/Point.c
src/libImaging/Resample.c
src/libImaging/SgiRleDecode.c
src/libImaging/Unpack.c

Fixes #3213.
This replaces casts of incoming memory with explicit memcpy(). Some platforms, especially Sparc, but also ARM and Itanium, do not like unaligned memory accesses and may lack from slowdowns or crashes as result of those if the incoming memory is not aligned to the expected access type. Using memcpy() will avoid this: the compiler will optimize this to direct unaligned accesses on platforms that support those operations, and will do whatever copy operation is needed on platforms that do not.

Use explicit memcpy() to avoid unaligned memory accesses

---

setup.py

This variable is commonly used by other build systems and using it can help with cross-compiling. Falls back to `pkg-config` as before.

Respect the PKG_CONFIG environment variable when building

---

docs/deprecations.rst
docs/releasenotes/6.1.0.rst

Docs: Add deprecation of Image.__del__

---

Tests/test_imagefont.py

Potential fix for https://github.com/python-pillow/Pillow/issues/3835#issuecomment-507260313:
> Some new failures on pillow-wheels, `TestImageFont.test_unicode_extended` failed:
> 
> * Mac MB_PYTHON_VERSION=2.7
> * Linux MB_PYTHON_VERSION=2.7 UNICODE_WIDTH=16
> * Linux MB_PYTHON_VERSION=2.7 PLAT=i686 UNICODE_WIDTH=16
> 
> With:
> 
> * `AssertionError:  average pixel value difference 14.7190 > epsilon 6.2000`
> * `AssertionError:  average pixel value difference 14.7190 > epsilon 6.2000`
> * `AssertionError:  average pixel value difference 14.7280 > epsilon 6.2000`
> 
> https://travis-ci.org/python-pillow/pillow-wheels/builds/552752918
>

Update epsilon for FreeType 2.10 with eg. Unicode width 16

---

Tests/test_imagefont.py
src/_imagingft.c

Should fix the PyPy3 build failure introduced in 8d4bb339a6ec55ff5ddfc61aafc2dc50bb4cbf6c.
This disables the fix for #3777 for PyPy3, as PyPy's cpyext module hasn't been updated to support the new PyUnicode functions yet.
From [#3835 (comment)](https://github.com/python-pillow/Pillow/issues/3835#issuecomment-507408755):
> Our tests didn't pick it up because ... whilst we do test PyPy3 on Travis CI, there is a ["implicit declaration of function ‘PyUnicode_AsUCS4Copy’" warning](https://travis-ci.org/python-pillow/Pillow/jobs/552842796#L2596) we didn't notice as all the [`test_imagefont` tests are skipped because there's no FreeType (or RAQM)](https://travis-ci.org/python-pillow/Pillow/jobs/552842796#L4209) on PyPy3. We should improve these testing gaps.
The FreeType library was probably …

Revert #3780 for PyPy3 as it hasn't been updated yet.

---

src/libImaging/Draw.c

See warning - https://travis-ci.org/python-pillow/Pillow/jobs/552697865#L2627

Added explicit braces

---

.travis/install.sh
.travis/script.sh

check-manifest already exists as part of the lint tox target "lint"
which is run by Travis CI. There is no need to re-run the same check as
part of each test run.

Remove check-manifest from .travis/script.sh

---

.travis/script.sh

The make target 'install-coverage' already runs selftest.py. Avoid
running the same script a second time to slightly speed up builds.

Remove duplicate run of selftest.py

---

MANIFEST.in

It is considered good practice to include test files in the source
distribution, as well as the files used to run them. It allows packagers
and users to run the tests locally to ensure the package is complete and
working.

Include tox.ini in sdist

---

.landscape.yaml
MANIFEST.in

Unused since af4d830ce963241d7ff6ca7b5c3c1d0bba43278c and a2f873c66149e6aa0fa034903265a3ca1a720d89 removed the health badges.

Remove unused landscape.yml configuration file

---

winbuild/build.py

Before: https://ci.appveyor.com/project/Python-pillow/pillow/builds/25757495/job/t36i34fncfksisx3?fullLog=true#L5829
After: https://ci.appveyor.com/project/nulano/pillow/builds/25759303/job/2d5cy0hle6whgaau?fullLog=true#L5808

Print winbuild compile output properly in Python 3.x

---

setup.cfg

* Show a summary of skipped tests, helps identify gaps in testing
* Add as config so no need to modify lines in several CI scripts
For example:
```
=========================== short test summary info ===========================
SKIPPED [2] ..\pypy2.7-v7.1.1-win32\lib-python\2.7\unittest\case.py:60: Numpy is not installed
SKIPPED [2] ..\pypy2.7-v7.1.1-win32\lib-python\2.7\unittest\case.py:60: images are not collected
SKIPPED [7] C:\vp\pypy2\site-packages\_pytest\unittest.py:94: olefile package not installed
SKIPPED [2] ..\pypy2.7-v7.1.1-win32\lib-python\2.7\unittest\case.py:60: netpbm not available
SKIPPED [2] ..\pypy2.7-v7.1.1-win32\lib-python\2.7\unittest\case.py:60: requires macOS
SKIPPED [1] …
```

Report reason for pytest skips

---

Tests/test_imagefont.py

I suspect [#3835 (comment)](https://github.com/python-pillow/Pillow/issues/3835#issuecomment-507260313) is actually a real failure. When I tried the test on Windows without the #3780 fix, I got the same values:
`E AssertionError: 2.5 not greater than or equal to 14.728 : average pixel value difference 14.7280 > epsilon 2.5000`
https://ci.appveyor.com/project/nulano/pillow/builds/23676028/job/jjd897m8b68sx96a#L6647.
Reverts python-pillow/Pillow#3931
Skips test_unicode_extended on all platforms when running Python 2.

Revert "Update epsilon for FreeType 2.10 with eg. Unicode width 16" and skip test_unicode_extended on Python 2.x instead

---

docs/reference/ImageDraw.rst
docs/reference/ImageStat.rst

Appeared as:
Pillow/docs/reference/ImageDraw.rst:137: WARNING: Unexpected indentation.
Pillow/docs/reference/ImageDraw.rst:164: WARNING: Unexpected indentation.
Pillow/docs/reference/ImageDraw.rst:177: WARNING: Unexpected indentation.
Pillow/docs/reference/ImageDraw.rst:208: WARNING: Unexpected indentation.
Pillow/docs/reference/ImageStat.rst:24: WARNING: Explicit markup ends without a blank line; unexpected unindent.

Clean up several Sphinx warnings

---

docs/Guardfile
docs/_templates/.gitignore
docs/_templates/sidebarhelp.html
docs/conf.py

The only file, `sidebarhelp.html`, applies to the sphinx-better-theme which is unused and was removed in
02f3685b2d0f96cbe7028d45c0564efb0c5349ad.

Remove unused docs/_templates directory

---

Tests/test_map.py
src/map.c

Resolves #3963
The check was added in https://github.com/python-pillow/Pillow/commit/c50ebe6459a131a1ea8ca531f10da616d3 to fix #2105. This PR should be updating the range for 64-bit systems.

Changed overflow check to use PY_SSIZE_T_MAX

---

.travis/install.sh
docs/installation.rst

Resolves #1757, together with https://github.com/python-pillow/docker-images/pull/67 - used package OpenJPEG instead of compiling it.
Also updates the Ubuntu version in the documentation from 14.04 to 16.04 - partly because 14.04 is now rather old, and partly because 'libopenjp2-7-dev' can't be found in 14.04.
Also adds 'harfbuzz-devel' and 'fribidi-devel' to the Fedora prerequistes, as seen in https://github.com/python-pillow/Pillow/blob/master/depends/fedora_23.sh

Use OpenJPEG package

---

.travis/after_success.sh

For https://github.com/python-pillow/Pillow/issues/3934.
The `2.7_with_system_site_packages` build has outdated or missing dependencies when installing `coveralls-merge`. From the latest `master` build:
```
Collecting coveralls-merge
Downloading https://files.pythonhosted.org/packages/1f/4a/af2413b78ba9361a3e18a58788e745c89772325b100d62a3bc217c295f15/coveralls-merge-0.0.3.tar.gz
Collecting coveralls>=0.4.2 (from coveralls-merge)
Downloading https://files.pythonhosted.org/packages/7c/f0/80c6957c3e88981d608681568460972156b5b2b870c76ab976b909e0003f/coveralls-1.8.1-py2.py3-none-any.whl
Requirement already satisfied: requests>=1.0.0 in /usr/lib/python2.7/dist-packages (from coveralls-merge) (2.9.1)
Requirement already satisfied: coverage<5.0,>=3.6 in …
```

Skip broken install of coveralls-merge on 2.7_with_system_site_packages

---

docs/reference/ImageFont.rst
src/PIL/ImageFont.py

See https://pillow.readthedocs.io/en/latest/reference/ImageFont.html for the current version
This PR
- fixes the documentation for the `getmask` and `getsize` methods of the ImageFont class. Comparing with the source code - https://github.com/python-pillow/Pillow/blob/master/src/PIL/ImageFont.py#L112 - the current documentation is incorrect regarding the arguments for those methods. The new docstrings I've added are copied and altered from the FreeTypeFont `getmask` and `getsize`.
- adds the TransposedFont class to the documentation
See https://pillow-radarhere.readthedocs.io/en/imagefont_docs/reference/ImageFont.html for the improved version.

Improved ImageFont documentation

---

docs/reference/ImageStat.rst

Before: https://pillow.readthedocs.io/en/stable/reference/ImageStat.html#PIL.ImageStat.PIL.ImageStat.Stat.extrema
After: https://pillow-radarhere.readthedocs.io/en/imagestat/reference/ImageStat.html#PIL.ImageStat.PIL.ImageStat.Stat.extrema

Corrected note syntax

---

requirements.txt

This is mostly just to create a new PR to see if the Codecov checks are now working, and we don't explicitly use `six` anyway.

Remove indirect dependencies from requirements.txt

---

docs/handbook/image-file-formats.rst

Resolves #4013, which reports that the `dpi` argument in TIFF saving doesn't support '(numerator, denominator)' values as the documentation claims.
The documentation was added in #369
Looking at code, this functionality was removed in #1419, where 'A tuple of more than one rational tuples' 'flatten to floats' was removed, along with `ifd[X_RESOLUTION] = _cvt_res(dpi[0])` being changed to `ifd[X_RESOLUTION] = dpi[0]`.
While updating this, I also note that we round the dpi - that was added in #3709
Also removed in #1419 was the use of "inch", "cm" and "centimeter" for `resolution_unit`, so I'm fixing that as well.

Corrected documentation of TIFF saving arguments

---

setup.py
winbuild/appveyor_install_msys2_deps.sh

Suggestion to resolve #4018
The mingw32 job is currently failing with
```
if self.ld_version >= "2.10.90":
TypeError: '>=' not supported between instances of 'NoneType' and 'str'
```
Searching, I found that in 'C:/msys64/mingw32/lib/python3.7\\distutils\\cygwinccompiler.py', there is a part where it stops searching for a simple 'ld' executable, instead searching for the path specified by gcc.
```python
ld = 'ld'
out = Popen(gcc+' --print-prog-name ld', shell=True, stdout=PIPE).stdout
try:
ld = test=str(out.read(),encoding='utf-8').strip()
```
However, I think this path then ends up being /usr/lib/gcc/x86_64-pc-msys/9.1.0/../../../../x86_64-pc-msys/bin/ld.exe
So this PR uses pacman versions of pytest and pytest-cov instead of compiling from source, and adds a fallback when compiling …

Added fallback for finding ld on MinGW Cygwin

---

src/PIL/ImageFont.py

Resolves #3730
The issue reports `OSError: cannot open resource` when opening many fonts on Windows. This is a FreeType error that is thrown, presumably because on Windows, ['The C run-time libraries have a 512 limit for the number of files that can be open at any one time.'](https://docs.microsoft.com/en-us/cpp/c-runtime-library/file-handling?view=vs-2017)
This PR suggests resolving this situation by simply documenting the limitation.
Also improved some other FreeType documentation while I'm here.

Note a Windows limit on opening fonts

---

src/PIL/Image.py

ImageShow uses PNG for Unix platforms - see #2527 and https://github.com/python-pillow/Pillow/blob/master/src/PIL/ImageShow.py#L167

Updated ImageShow documentation

---

setup.py

* Fix for Python 3.10
* Inspired by https://github.com/pypa/setuptools/pull/1824
```python
Python 3.7.4 (default, Jul  9 2019, 18:13:23)
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.version
'3.7.4 (default, Jul  9 2019, 18:13:23) \n[Clang 10.0.1 (clang-1001.0.46.4)]'
>>> sys.version[:3]
'3.7'
>>> v310 = '3.10.4 (default, Jul  9 2019, 18:13:23) \n[Clang 10.0.1 (clang-1001.0.46.4)]'
>>> v310[:3]
'3.1'
```

Fix for Python 3.10

---

src/PIL/IcoImagePlugin.py

https://github.com/python-pillow/Pillow/issues/3773#issuecomment-509160651
> it should also mention that the current Pillow implementation saves ICOs internally as PNGs, not DIBs (support was only added in Windows Vista).
See https://github.com/python-pillow/Pillow/blob/cb7d8d622a3c17aea55d2f989f89300532161120/src/PIL/IcoImagePlugin.py#L72
and
https://en.wikipedia.org/wiki/ICO_(file_format)
> The ability to read PNG images from ICO and CUR format images was introduced in Windows Vista.

Documented OS support for ICO saved files

---

Tests/test_file_libtiff.py
src/PIL/TiffImagePlugin.py

Fixes #3996.
* There is an existing fp value that is safely created before the call to Image._getdecoder. The same value should just be used again in the logic surrounding the actual decode.
* For the case of "we have something else" (no getvalue or fileno) it should seek to the beginning as it does in other cases.

Fix bug in TIFF loading of BufferedReader

---

Tests/test_file_gif.py
src/PIL/GifImagePlugin.py

Fixes #4002
* copy `duration` from `im_frames` to `im.encoderinfo`

Fix bug when merging identical images to GIF with a list of durations

---

src/PIL/ImageFont.py

Resolves #3345 by listing more encoding values, and adding a note that the `encoding` parameter does not change the encoding of text from later operations.
See https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#ft_encoding for the list of encoding values added.

Documented more encoding values

---

Tests/test_file_tiff_metadata.py
src/PIL/TiffTags.py

Helps #3677. An error is still caused for that issue, but at least it is not a segfault.
Correct tag counts for
- https://www.awaresystems.be/imaging/tiff/tifftags/xmp.html and https://www.awaresystems.be/imaging/tiff/tifftags/photoshop.html - 'Count N'
Add
- https://www.awaresystems.be/imaging/tiff/tifftags/iptc.html

Corrected tag counts

---

winbuild/build.py
winbuild/build.rst

`bdist_wininst` (`.exe` installers) has been deprecated in Python 3.8, and `bdist_wheel` (wheel packages) should be used instead:
* https://discuss.python.org/t/deprecate-bdist-wininst/1929?u=hugovk
* https://github.com/python/cpython/pull/14553
As far as I can see in the codebase, it's only used in `build.py --dist` to create Windows installers for testing dev builds. There's already a `build.py --wheel` option for `bdist_wheel` packages. So let's remove `--dist`.
---
In https://discuss.python.org/t/deprecate-bdist-wininst/1929/12?u=hugovk, @cgohlke pointed out:
> > PyPI doesn’t even allow you to upload bdist_wininst (See [PEP 527 ](https://www.python.org/dev/peps/pep-0527/)) anymore
>
> Maybe a bug: [Pillow](https://pypi.org/project/Pillow/#files) still uploads `bdist_wininst` …

No more deprecated bdist_wininst .exe installers

---

Tests/test_image_convert.py
src/libImaging/Convert.c

Resolves #3997
The issue reports that you can't convert from P to HSV, whereas this previously worked.
If a direct conversion from a mode to another is not possible, then Pillow attempts to convert the image to its base mode first, and then convert from that intermediate image.
https://github.com/python-pillow/Pillow/blob/f3f45cfec50a44970f325e6ef1a2e4eaf2caa89e/src/PIL/Image.py#L1050-L1056
PR #3726 changed the base mode of P from RGB to P. So while Pillow previously worked around the absence of a direct method for converting from P to HSV, it now throws an error.
This PR fixes that by assigning direct methods for conversion from P to HSV, as well as 1 to HSV, L to HSV, LA to HSV, I to HSV, RGBA to HSV, RGBX to HSV and CMYK to HSV.

Improved HSV conversion

---

README.rst

The old one has stopped working. 
See https://forum.tidelift.com/t/new-urls-for-project-badges/288

Update Tidelift badge

---

Tests/test_imagefile.py
src/PIL/Image.py
src/PIL/JpegImagePlugin.py
src/PIL/MpoImagePlugin.py

ImageFileDirectory_v1 is lazy, [performing operations when a value is accessed](https://github.com/python-pillow/Pillow/blob/cb7d8d622a3c17aea55d2f989f89300532161120/src/PIL/TiffImagePlugin.py#L968).
However, [accessing all of those values to create a dictionary](https://github.com/python-pillow/Pillow/blob/cb7d8d622a3c17aea55d2f989f89300532161120/src/PIL/Image.py#L3152) when [loading the data](https://github.com/python-pillow/Pillow/blob/cb7d8d622a3c17aea55d2f989f89300532161120/src/PIL/Image.py#L3184) undoes that speed increase.
#3663 set out to fix this by adding a new class - however, it had conflicts once #3625 was merged and a different class was added to deal with Exif data. This PR takes a different approach towards the original goal, for the new context.
It also uses this change …

Lazily use ImageFileDirectory_v1 values from Exif

---

Tests/test_imagedraw.py

Since merging #3978, I've been seeing some intermittent failures from Travis and Azure.
For example,
- https://travis-ci.org/python-pillow/Pillow/jobs/583125917 - but if you rerun the build, there is a decent chance it will pass.
- https://dev.azure.com/python-pillow/pillow/_build/results?buildId=806
- https://dev.azure.com/python-pillow/pillow/_build/results?buildId=812
- https://dev.azure.com/python-pillow/pillow/_build/results?buildId=817
This PR increases the tolerance of that test.

Increased tolerance for stroke test comparison

---

CHANGES.rst
docs/handbook/image-file-formats.rst
docs/handbook/tutorial.rst
docs/reference/Image.rst
docs/reference/ImageCms.rst
docs/reference/ImagePath.rst
docs/releasenotes/2.7.0.rst
docs/releasenotes/2.8.0.rst
docs/releasenotes/3.0.0.rst
docs/releasenotes/3.1.0.rst
winbuild/build.rst

reStructuredText uses double backticks for code. Markdown uses single backticks.

Use double backticks in RST

---

.github/workflows/lint.yml

Fixes #4060.
This reverts commit f6eb0f77027bb105ae99d87759acbcee262bc03f.
> A workflow that specifies a pull_request as the event will always run in the repository that contains that pull_request.  So when I raise a pull_request to the upstream repo from a fork of that repo the workflow run will be in that upstream repo.  
https://github.community/t5/GitHub-Actions/Run-a-GitHub-action-on-pull-request-for-PR-opened-from-a-forked/td-p/15426
> **Pull request events for forked repositories**
>
> When you open a pull request from a forked repository, the pull request opens on the base repository by default. In this scenario, GitHub sends the `pull_request` event to the base repository and no pull request events occur on the forked repository because the webhook configuration of the original …

GitHub Actions: include `pull_request` so PRs from forks run

---

Tests/test_file_jpeg.py
Tests/test_imagefile.py
src/PIL/ImageFile.py
src/PIL/PngImagePlugin.py

Resolves #3863, and see also #2977, two issues that find it strange that Pillow is inconsistent between the first `load()` of a truncated image, and the second.
After `load()` is called on a truncated image, an error is raised and there is a line - `self.tile = []`. This means that when `load()` is called a second time, [it thinks there is nothing to do](https://github.com/python-pillow/Pillow/blob/1c57a41ececc4529520a423b9bec13c78927cb25/src/PIL/ImageFile.py#L148) and does not return the same truncated error. This logic has been present since the fork.
Instead, this PR removes that line, causing the same error to be raised on subsequent loads. It also resets an internal variable of PngImagePlugin, to fix an error that was raised when changing the tests for this, also providing …

Raise the same error if a truncated image is loaded a second time

---

Tests/helper.py
Tests/test_imageshow.py

This PR adds a test that actually runs the `ImageShow.show` method, opening the image. However, to be neat, it only runs on the CIs, where the shown images won't bother users.

Test ImageShow.show on CIs

---

src/PIL/Image.py
src/PIL/ImageShow.py

Changed WindowsViewer format to PNG

---

winbuild/build.py
winbuild/build_dep.py

While trying to add PyPy3 to AppVeyor, I found and fixed several winbuild issues, including these:
Log changes:
* `SetEnv.Cmd` and `vcvarsall.bat` both disable `echo`. Turning it back on improves readability of the build log.
* `nmake` copyright message was messy (around 30 lines long). Adding `-nologo` turns it off.
Compare before: https://ci.appveyor.com/project/Python-pillow/pillow/builds/27337992/job/ni8rcc28utx9baq6?fullLog=true#L367
Compare after: https://ci.appveyor.com/project/nulano/pillow/builds/27571987/job/cojejreprth4khia?fullLog=true#L367
Build changes:
* Build libjpeg in release mode, not debug mode, by adding `nodebug=1`. See `jpeg-9c\makefile.vc` line 9 for more info.
* Build openjp2 in release mode, not default mode, by adding `-DCMAKE_BUILD_TYPE=Release`. See e.g. …

AppVeyor build improvements

---

Tests/test_locale.py

https://bitbucket.org/pypy/pypy/issues/3079/systemerror-in-timestrptime-with-non#comment-54017374 notes that Pillow does not reset the locale at the end of one of our tests.

Cleanup by resetting locale

---

docs/releasenotes/6.2.0.rst

Release notes for #4086

---

Tests/test_imagegrab.py
docs/reference/ImageGrab.rst
src/PIL/ImageGrab.py
src/display.c

Resolves #1547
~~Provides workaround for #2438, #3432, #3626:
For some reason grabbing a screenshot of the whole screen with the new `ImageGrab.grab(multimonitor=True)` ignores DPI scaling properly.~~
Edit: I didn't look at the screenshot closely enough.

Add option to capture all monitors on Windows

---

Tests/test_file_libtiff.py
Tests/test_file_tiff.py

Move a test that requires libtiff from test_file_tiff.py to test_file_libtiff.py, where libtiff is required for all the tests.

Moved libtiff test into libtiff test file

---

RELEASING.md

Added dash to regex in command for downloading wheels, so that
- Pillow-6.2.0-cp37-cp37m-manylinux1_x86_64.whl
is matched, while
- Pillow-6.2.0.dev0+20190902192556-cp27-cp27mu-manylinux1_x86_64.whl
is not.

Do not download dev wheels

---

src/PIL/TiffTags.py

As per https://github.com/python-pillow/Pillow/pull/3981#issuecomment-514552819

Corrected tag types

---

src/PIL/Image.py

The comment suggests changing the default values post 1.1.6, so that they are in line with the warning displayed to the user.
Sounds reasonable.

Changed default frombuffer raw decoder args

---

docs/deprecations.rst
src/PIL/Image.py
src/PIL/__init__.py

* `PILLOW_VERSION` was deprecated in 5.2.0 (https://github.com/python-pillow/Pillow/pull/3090) and is removed in 7.0.0

Remove deprecated PILLOW_VERSION

---

src/PIL/TiffImagePlugin.py

TiffImagePlugin sets `DEBUG` to `False` initially, and checks for a truthy value in various places, except for
https://github.com/python-pillow/Pillow/blob/59153f5e125bf677b257b0310e710583a62506cf/src/PIL/TiffImagePlugin.py#L857
This is an  artifact of #1207, when `DEBUG` changed from `0` by default to `False`. This PR changes it to just check for a truthy value.

Changed condition to use DEBUG as a boolean

---

Tests/test_file_tiff.py
docs/deprecations.rst
src/PIL/TiffImagePlugin.py

Setting TIFF image size was deprecated in Pillow 5.3.0 (https://github.com/python-pillow/Pillow/pull/3203/commits/6f44ae1d27fa89a9e313e0da9dbfe3d129bb0763). This PR removes it for 7.0.0.

Removed deprecated setting of TIFF image sizes

---

docs/handbook/image-file-formats.rst

Resolves #4095
That issue saw a mistaken understanding that https://pillow.readthedocs.io/en/latest/handbook/image-file-formats.html#saving applied to all image formats, not just GIF. This PR tries to clarify that, and also for https://pillow.readthedocs.io/en/5.1.x/handbook/image-file-formats.html#saving-sequences

Clarified image format documentation

---

Tests/test_decompression_bomb.py

The same cleanup is done in the teardDown() method. There is no need to do it a 2nd time.

Remove duplicate cleanup in test_decompression_bomb.py

---

Tests/check_icns_dos.py
Tests/check_j2k_dos.py

Bytes literals are available on all supported Python versions. Rather
than convert strings literals to bytes at runtime, simply use a bytes
literal.

Use bytes literals instead of bytes(str)

---

Tests/helper.py
Tests/test_file_libtiff.py
Tests/test_file_libtiff_small.py
Tests/test_file_tiff.py
Tests/test_file_webp_metadata.py
Tests/test_file_xbm.py
Tests/test_image.py
Tests/test_image_access.py
src/PIL/EpsImagePlugin.py
src/PIL/GifImagePlugin.py
src/PIL/IcnsImagePlugin.py
src/PIL/Image.py
src/PIL/ImageFont.py
src/PIL/ImageGrab.py
src/PIL/JpegImagePlugin.py

This better follows PEP 8 style guide:
https://www.python.org/dev/peps/pep-0008/#imports
> Imports are always put at the top of the file, just after any module
> comments and docstrings, and before module globals and constants.
This also avoids duplicate import code within the same file.

Move several imports to the top-level of the file

---

docs/reference/ImageOps.rst

* Add functions to the documentation
* 'Only bug fixes have been added since the Pillow fork.' - This is no longer true. There is at least #3687 and #3364,

Updated ImageOps documentation

---

.github/workflows/test-docker.yml

For https://github.com/python-pillow/Pillow/issues/3606. 
* Run Docker tests using GitHub Actions
* GitHub Actions testing now identical to Azure Pipelines, 13 jobs
* Main difference: 
* AZP 10 parallel jobs, so 3 wait. Whole run ~6 mins
* GHA [20 parallel jobs](https://help.github.com/en/articles/about-github-actions#usage-limits), so none wait. Whole run ~3 mins
Shall we remove the AZP tests now or have both enabled for a while to compare and evaluate?
(Coverage still needed before removing Docker from Travis, can follow.)

Test Docker with GitHub Actions

---

.appveyor.yml
.travis.yml

For #3642 
* Whilst https://github.com/python-pillow/Pillow/pull/4109 is still in review, minimal changes to stop testing Python 2.7 and benefit immediately from CI time saved
* Savings:
* Travis CI: ~9 minutes
* AppVeyor: ~16 minutes

CI: Stop testing Python 2.7

---

.codecov.yml
.github/workflows/lint.yml
.github/workflows/macos-install.sh
.github/workflows/test.yml
.travis.yml
.travis/build.sh
.travis/test.sh

For #3606.
* This does the same tests as the "native" (ie. non-Docker) builds on Travis CI:
* pypy3
* ~pypy2~
* 3.7
* 3.6 `PYTHONOPTIMIZE=1`
* 3.5 `PYTHONOPTIMIZE=2`
* ~2.7~
* Not available on GitHub Actions:
* ~`"2.7_with_system_site_packages" # For PyQt4`~
* `3.8-dev`
* Also rename some variables in `lint.yml` for consistency
Happily GitHub Actions runs the `.travis/*.sh` scripts with no problems. There's an `if [ "$TRAVIS_PYTHON_VERSION" == "2.7" ]; then make doccheck; fi` in one, I've added the same doccheck as its own step here for GHA.
This only runs on `ubuntu-latest`, currently `ubuntu-18.04` Bionic. `ubuntu-16.04` Xenial is also available.
* https://help.github.com/en/articles/virtual-environments-for-github-actions#supported-virtual-environm …

Test Linux and macOS with GitHub Actions

---

.github/workflows/test-windows.yml
winbuild/appveyor_install_pypy3.cmd

PyPy v7.2 has been released:
* https://morepypy.blogspot.com/2019/10/pypy-v72-released.html
* Replace nightly with 7.2 on AppVeyor and GitHub Actions
* GHA: seems you can't refer to a matrix var whilst also defining a var so `pypy3.6-v7.2.0-win32` comes twice

Test pypy3.6-v7.2.0 on Windows

---

CHANGES.rst
docs/releasenotes/6.2.0.rst
docs/releasenotes/6.2.1.rst

Pillow 6.2.1 is the last to support Python 2.7

---

RELEASING.md

This check is in the main release checklist, but not for point releases.
Noticed during https://github.com/python-pillow/Pillow/issues/4152.

Add a check for point releases

---

Tests/helper.py

As the test suite always runs with pytest now, self.currentResult is
always None. Using this, can remove unused code.

Simpilify PillowTestCase.delete_tempfile for pytest

---

.github/workflows/test-windows.yml

Fixes #4167
* The default Windows shell changed from `cmd` to `powershell`. Adding `shell: cmd` to every step which doesn't specify a shell fixes this.
* https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#using-a-specific-shell

GHA Windows: Explicitly use cmd shell, as GH changed the default to powershell

---

.github/workflows/macos-install.sh
.travis/build.sh

Replaced macOS Command Line Tools install with miniconda path

---

winbuild/build_dep.py
winbuild/config.py
winbuild/fetch.py

#4127 attempts to solve the problem of retrieving a dependency blocked by a lack of User-Agent by adding a User-Agent.
This PR instead retrieves the file from pillow-depends on User Agent failure.

Use pillow-depends on HTTPError

---

src/_imagingft.c

Fix segfault in `_imagingft.font_render` during `TestImageDraw::test_stroke`.
Fixes #4156 .
Do not destroy glyph while its bitmap is used.

Fix segfault: do not destroy glyph while its bitmap is used

---

Tests/test_file_tiff.py

For consideration, here's an alternative way to accomplish #4184
See https://docs.pytest.org/en/latest/warnings.html#pytest-mark-filterwarnings for documentation.

Ignore UserWarnings in TestFileTiff::test_string_dimension

---

Tests/test_features.py
Tests/test_main.py
selftest.py
src/PIL/features.py
src/_imaging.c

From https://github.com/python-pillow/Pillow/pull/4084#issuecomment-535702633
* Add libimagequant to `features.py`
* Remove code duplication from `selftest.py` introduced in #3870

Add libimagequant to features.py

---

src/PIL/Image.py

`deferred_error` is a general implementation of `_imaging_not_installed`. Can reuse rather than repeating the same logic.

Reuse deferred_error instead of _imaging_not_installed

---

Tests/conftest.py

This change will print version, installation directory, and features of the Pillow installation being tested. I found this helpful when building and testing Pillow locally. For example:
```
> py -3.8 -m pytest Tests
================================================================= test session starts ==================================================================
platform win32 -- Python 3.8.0, pytest-5.2.2, py-1.8.0, pluggy-0.13.0
--------------------------------------------------------------------
Pillow 6.2.1
--------------------------------------------------------------------
Python modules loaded from X:\Python38\lib\site-packages\PIL
Binary modules loaded from X:\Python38\lib\site-packages\PIL
--------------------------------------------------------------------
--- PIL CORE …
```

Report details about Pillow when running tests

---

.github/workflows/lint.yml
.github/workflows/test.yml

Python 3.8 is finally available on GitHub Actions, 21 days after release.
(Travis CI was available 21 hours after release.)

GHA: Test Python 3.8 on Linux/macOS

---

.appveyor.yml
.github/workflows/test-windows.yml

Suggested in https://github.com/python-pillow/Pillow/issues/3618#issuecomment-478872426
Helps prevent https://github.com/python-pillow/Pillow/issues/4152#issuecomment-544619189
Used https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/example-12---using-page-heap-verification-to-find-a-bug
As a demonstration, this will fail until #4160 is merged.

Enabled page heap verification

---

Tests/test_file_psd.py

Fixed context manager test to actually use a context manager.
This also brings the test into line with https://github.com/python-pillow/Pillow/blob/ce8c944525083c6629b08c7b1dc3f8b7cce1982c/Tests/test_file_tiff.py#L64-L69
https://github.com/python-pillow/Pillow/blob/ce8c944525083c6629b08c7b1dc3f8b7cce1982c/Tests/test_file_gif.py#L52-L57
https://github.com/python-pillow/Pillow/blob/ce8c944525083c6629b08c7b1dc3f8b7cce1982c/Tests/test_file_dcx.py#L40-L45
and others.

Corrected context manager test

---

.github/workflows/test-windows.yml
winbuild/lcms2_patch.ps1

Fixes #4188
* Run Windows tests on `windows-2019`
* Use official prebuilt Ghostscript binary
* Patch LCMS2 build scripts to work with VS2019 (1)
* Use `DISTUTILS_USE_SDK=1` to help Python 3.5 and 3.6 find the compiler (1)
* Fix PyPy3.6 pip warning causing early failures; FIXME PyPy can't find the compiler
(1) These two changes should probably be reverted once VS2017 is added to `windows-2019` as promised in https://github.com/actions/virtual-environments/issues/68#issuecomment-548534537

GitHub Actions: Update to windows-2019

---

.github/workflows/test.yml

* Looks like macOS-10.14 is being removed, 4 have "This check failed", 1 has "This check was neutral" and no further info:
* https://github.com/python-pillow/Pillow/pull/4195/checks?check_run_id=288243449
* In https://github.com/actions/virtual-environments/issues/53, GitHub said it would be replaced with macOS 10.15
* Using `-latest` will use whatever the latest version is
* For macOS, GitHub say "at this point in time don't have enough VM capacity to support multiple versions of macOS" https://github.com/actions/virtual-environments/issues/53#issuecomment-549954507
Should we use explicit versions or implicit `-latest` versions? At least if we test on multiple Ubuntu versions, using explicit versions would be clearer.

Test on latest available macOS and Ubuntu

---

Tests/test_image_transform.py
src/PIL/Image.py

```python
im = Image.open("Tests/images/hopper.gif")
print(im.rotate(180).info)  # {'version': b'GIF89a', 'background': 0, 'duration': 0, 'comment': b'File written by Adobe Photoshop\xa8 4.0'}
print(im.rotate(181).info)  # {}
```
This inconsistency is because for some angles, `rotate` will `copy` or `transpose` for the sake of efficiency
https://github.com/python-pillow/Pillow/blob/8c94f01842ba3f0c473e3279df2425c0683bffe2/src/PIL/Image.py#L1924-L1932
instead of its usual `transform`.
https://github.com/python-pillow/Pillow/blob/8c94f01842ba3f0c473e3279df2425c0683bffe2/src/PIL/Image.py#L2001
`transpose` uses `_new` to create the new image, while `transform` uses `new`.
This PR resolves the inconsistent behaviour by ensuring that `info` is copied into `transform` …

Copy info in Image.transform

---

Tests/test_image_resample.py
src/libImaging/Resample.c

Resolves #4115
#3393 added two `free` lines that should not be present. `bounds_vert` and `kk_vert` are assigned by `precompute_coeffs`. If `precompute_coeffs` returns `0`, then they were not assigned, and should not be freed.
I have added a test that fails without this PR to demonstrate.

Fixed freeing unallocated pointer when resizing with height too large

---

setup.py

For issues like https://github.com/python-pillow/Pillow/issues/4204, would it help to have the Pillow version number in the warning message?
Currently:
```
Pillow\setup.py:29: RuntimeWarning: Pillow does not yet support Python 3.8 and does not yet provide prebuilt Windows binaries. We do not recommend building from source on Windows.
```

Include Pillow version in Windows wheel warning

---

setup.py

Warehouse now uses the `project_urls` provided to display links in the sidebar, as well as including them in API responses to help automation tool find the source code for Pillow. For example, see Django's [setup.cfg](https://github.com/django/django/blob/master/setup.cfg) and [PyPI listing](https://pypi.org/project/Django/).

Add Documentation and Github URLs for PyPi

---

.github/workflows/test-windows.yml
.github/workflows/test.yml
Tests/helper.py

As GitHub Actions allows direct artifact uploads, failed image comparisons can now be uploaded directly, instead of using an external server (unlike in #2862).
The failed comparisons are saved in a randomly named directory (from `tempfile.mdktemp`), which is then uploaded in an artifact named `errors.zip`.
Test Docker is not included in this, as this is a bit more complicated there.
Sample commit with failing test: https://github.com/nulano/Pillow/commit/165d457b67de4f4dcdc39880fa3439969376c62c
Test (Ubuntu and macOS): https://github.com/nulano/Pillow/runs/257598825
Test Windows: https://github.com/nulano/Pillow/runs/257598798

Upload image errors to GitHub Actions

---

Tests/test_file_gd.py
Tests/test_image.py
docs/releasenotes/7.0.0.rst
src/PIL/GdImageFile.py
src/PIL/Image.py
src/PIL/__init__.py

Resolves #3892
See how this goes. Pillow 7.0.0 seems like a good time for such changes.
As suggested there, this is a custom error, that inherits from the previous type for backwards compatibility.
See also the related issues #1643 and #2339

Added UnidentifiedImageError

---

.github/workflows/test-windows.yml
winbuild/config.py

Adds Python 3.8 to Windows build matrix on GitHub Actions.
Edit: Also adds PyPy3.6-7.2.0 to Windows build matrix on GitHub Actions.

Test Python 3.8 and PyPy3.6 on Windows with GitHub Actions

---

.github/workflows/test-windows.yml
Tests/test_imagefont.py
src/_imagingft.c

Depends on #4109.
Reinstates #3780 changes reverted by #3935 for PyPy 7.2.0+.
This change also fixes Raqm support on PyPy (from https://github.com/python-pillow/Pillow/pull/4084#issuecomment-536663835).
There is a bug in PyPy that causes a failure of the test for #3777 when using Raqm, reported here: https://bitbucket.org/pypy/pypy/issues/3095/pyunicode_asucs4copy-fails-with-extended

Fix Unicode support for PyPy

---

src/PIL/JpegPresets.py

Mention why this information is not available in the EXIF tag specified for this purpose.
* Fix mismatched function name
* Add explanation why current subsampling value is not set to the EXIF tag for this purpose.

Fix mismatched function name, add explanation

---

.appveyor.yml
winbuild/build_dep.py
winbuild/config.py

#4201 changed to using official prebuilt GhostScript binaries on GitHub Actions (instead of compiling it), as it is hard to compile on `windows-2019`.
This PR does the same for AppVeyor to speed it up significantly.
Also see https://github.com/python-pillow/Pillow/issues/4188#issuecomment-551155313 for a (brief) discussion.

Use prebuilt GhostScript on AppVeyor

---

.github/workflows/test.yml
.travis/after_success.sh

Fix split out from https://github.com/python-pillow/Pillow/pull/4216.

GHA: Install lcov on macOS to report coverage

---

.github/workflows/test-windows.yml

Depends on https://github.com/python-pillow/pillow-depends/pull/31.
* Use NASM and GhostScript from `pillow-depends`
* Switch to using `actions/checkout` to fetch `pillow-depends`, instead of `ps curl`
These two changes should decrease the amount of intermittent network errors encountered in tests.
See build using https://github.com/python-pillow/pillow-depends/pull/31 here: https://github.com/nulano/Pillow/runs/312459799

Fetch binary dependencies from pillow-depends on GitHub Actions

---

Tests/test_image_array.py
src/PIL/Image.py

* Add the type of data that fromarray cannot handle to the error message.

Better error messaging in PIL.Image.fromarray

---

.codecov.yml
.github/workflows/test-windows.yml
.github/workflows/test.yml
.travis/after_success.sh

* Codecov GitHub Action is now available for all three operating systems
* https://github.com/codecov/codecov-action
* There was a problem including the Pillow token in `.codecov.yml`: some of the build jobs in my fork were sent to Pillow's Codecov, not mine
* ~Plus fix so GHA macOS coverage is collected: needed to install lcov properly~ Done in https://github.com/python-pillow/Pillow/pull/4217

Use Codecov's GitHub Action

---

.appveyor.yml

For https://github.com/python-pillow/Pillow/issues/3606.
Since 13th November, GitHub Actions is now out of beta and hopefully more stable.
Let's make a first step in reducing AppVeyor testing. The **10 jobs** currently take around **40 minutes in serial**.
| Python  | AppVeyor | GitHub Actions |
| --------| :-------:|:--------------:|
| 3.5 x86 | ✅       | ✅             |
| 3.5 x64 | ✅       | ✅             |
| 3.6 x86 | ✅       | ✅             |
| 3.6 x64 | ✅       | ✅             |
| 3.7 x86 | ✅       | ✅             |
| 3.7 x64 | ✅       | ✅             |
| 3.8 x86 | ✅       | ✅             |
| 3.8 x64 | ✅       | ✅             |
| MinGW   | ✅       | ❌             |
| PyPy3   | ✅       | ✅             |
To begin, how about removing 3.6 and 3.7 from AppVeyor? We'll then still be …

CI: Python 3.5 and 3.6 are tested by GHA, remove from AppVeyor

---

docs/installation.rst

* Update table of tested versions to reflect current GHA / AppVeyor status
* Update note about raqm support on Windows - it is supported, but not shipped in wheels

Update tested versions table

---

depends/termux.sh
docs/installation.rst

Termux does not have -dev packages any more(https://wiki.termux.com/wiki/No_more_-dev_packages) and pkg install -y instead of pkg -y install should be used
* Use the right package name
* Change pkg -y install (which doesn't work) to pkg install -y

Update the out-dated termux.sh

---

.github/workflows/lint.yml
.github/workflows/system-info.py
.github/workflows/test-docker.yml
.github/workflows/test-windows.yml
.github/workflows/test.yml

* Unlike Travis CI, GitHub Actions doesn't print out build system information at the top of the logs
* That means it's not clear what `macos-latest` or `windows-latest` really are, especially during rollout of new versions (eg. https://github.com/actions/virtual-environments/issues/53#issuecomment-550405295) or the docs saying one thing and the build another (eg. https://github.com/python-pillow/Pillow/pull/4228#discussion_r355053699, https://github.com/actions/virtual-environments/issues/81#issuecomment-562761489)
* See https://github.com/actions/virtual-environments/issues/79 for a request for this to be added to GitHub Actions
* In the meantime, let's add some basics ourselves

GHA: Print some basic system information for the logs

---

Tests/test_image_thumbnail.py
src/PIL/Image.py

If the source image is 256×162, it's aspect ratio is 1.58. Before, after thumbnailing, for example, the resulting image had 33×20 size, which aspect ratio is 1.65. Now thumbnail returns 33×21 image, with aspect ration 1.57, which is much closer.

Better thumbnail aspect ratio preservation

---

Tests/test_image_resample.py
src/libImaging/Resample.c

Fixes #4258. Explanations in [the comment](https://github.com/python-pillow/Pillow/issues/4258#issuecomment-567263707).

Define box filter equal 1.0 on (-0.5, 0.5] range instead of [-0.5, 0.5)

---

Tests/test_file_bmp.py
src/PIL/BmpImagePlugin.py

Resolves #4274, by throwing an error if the file size is too large to fit into 4 bytes.
I set the size artificially in the test to avoid using a large amount of memory.
Also fixes up the comments, which were out of sync. Reference http://www.ece.ualberta.ca/~elliott/ee552/studentAppNotes/2003_w/misc/bmp_file_format/bmp_file_format.htm

Raise an error if BMP file size is too large when saving

---

.github/workflows/test.yml
.travis/install.sh
docs/Makefile
docs/installation.rst
src/PIL/Image.py
src/PIL/ImageOps.py

* Catch issues like https://github.com/python-pillow/Pillow/pull/4271 and https://github.com/python-pillow/Pillow/pull/4282 on the CI, by turning the warnings from sphinx-build into errors
For example, a build of an commit before those two fixes, with normal warnings, has exit code 0 so the CI passes:
```
⌂90% [hugo:~/github/Pillow] 52113a82+* ± make doccheck
/Library/Developer/CommandLineTools/usr/bin/make -C docs html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v2.1.2
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 72 source files that are out of date
updating environment: 72 added, 0 changed, 0 removed
reading sources... [100%] releasenotes/index …
```

make doccheck: turn warnings into errors

---

.travis/install.sh
.travis/test.sh

We're currently using [3.7 for Travis](https://github.com/python-pillow/Pillow/blob/master/.travis/test.sh#L8) and [3.8 for GHA](https://github.com/python-pillow/Pillow/blob/master/.github/workflows/test.yml#L87)

Use the same Python version to build docs in Travis and  GHA

---

src/PIL/Image.py

The PCD `draft` method was removed in #1169.
Meanwhile, MpoImageFile has a `draft` method because it inherits from JpegImageFile - https://github.com/python-pillow/Pillow/blob/fafeeefccda1d24f8ee33d2f2fd4e339ea2d64a3/src/PIL/MpoImagePlugin.py#L38

Updated draft documentation
