- src/PIL/GifImagePlugin.py
If a `subprocess.CalledProcessError` is thrown, then the tempfile would not be unlinked. this PR ensures that whatever error is thrown, the tempfile will be unlinked.
> Ensure tempfile is unlinked

- src/PIL/PngImagePlugin.py
https://github.com/python-pillow/Pillow/blob/fafeeefccda1d24f8ee33d2f2fd4e339ea2d64a3/src/PIL/PngImagePlugin.py#L885 is a duplicate of https://github.com/python-pillow/Pillow/blob/fafeeefccda1d24f8ee33d2f2fd4e339ea2d64a3/src/PIL/PngImagePlugin.py#L829
`info` isn't modified in the middle, so the second line can be removed.
> Removed duplicate line

- .azure-pipelines/jobs/test-docker.yml
- .travis.yml
- azure-pipelines.yml
I've created a [6.2.x branch for docker-images](https://github.com/python-pillow/docker-images/tree/6.2.x), which has [pushed to docker hub](https://hub.docker.com/repository/docker/pythonpillow/debian-10-buster-x86).
This PR allows the Pillow 6.2.x branch to use that, so that it does not miss out on Python 2 Docker testing (which has been removed from the master branch of docker-images)
> Use dedicated docker tag for 6.2.x

- .travis.yml
- azure-pipelines.yml
I have added Python 2.7 to Fedora 31 on the docker-images 6.2.x branch - https://github.com/python-pillow/docker-images/commit/0b97670b452e23216f3d00f626c8d317f739b7d3
> Added Fedora 31 to 6.2.x

- src/PIL/Image.py
Follow up to #4182
Rather than saying that an `IOError` is raised by `Image.open`, I think it is more helpful to say that an `UnidentifiedImageError` is raised.
Also an `IOError` is not raised by `Image.open("blah")`, `FileNotFoundError` is.
> Updated exception documentation

- Tests/test_image.py
- src/PIL/Image.py
Resolves #4097 
The conclusion of discussion in the issue is that StringIO can't be used to pass bytes into Image.open.
```python
import io
im = Image.open(io.StringIO("'\x89\x50\x4E\x47\x0D"))
```
```
OSError: cannot identify image file <_io.StringIO object at 0x104ecdd70>
```
A ValueError with a clearer message with now be raised in this situation, explaining that byte data is required instead of StringIO.
> Raise ValueError for io.StringIO in Image.open

- Tests/test_main.py
[pypy#3081](https://bitbucket.org/pypy/pypy/issues/3081/operationerror-cp65001-is-only-available) is fixed in pypy3.6-7.3.0, restore the related test `test_main`.
> Restore test fixed in PyPy 7.3.0

- .github/workflows/test-docker.yml
- .travis/after_success.sh
> Added coverage for Docker GHA

- Tests/test_file_libtiff.py
- src/PIL/TiffImagePlugin.py
- src/_imaging.c
Resolves #4211
This PR is another version of #3552, again the goal of removing distutils in order to resolve problems external to Pillow. That PR was not accepted, so I understand if this one is not either.
This time, I'm suggesting moving the Python-level version check into C.
It then duplicates the version check performed in TiffDecode.c -
https://github.com/python-pillow/Pillow/blob/661ceac71739023b55c2849bb80dd46b7ef586bd/src/libImaging/TiffDecode.c#L556-L561
However, the two checks are not for exact the same purpose. The check in TiffDecode.c is for ease of compilation because of the different return types between libtiff versions, whereas this one is about functionality.
> Replaced distutils with C version check

- Tests/test_file_wmf.py
Fix two deprecation warnings in `test_file_wmf` introduced in #4311.
From https://github.com/python-pillow/Pillow/runs/369013311#step:24:1469:
```
============================== warnings summary ===============================
Tests/test_file_wmf.py::TestFileWmf::test_load_set_dpi
d:\a\Pillow\Pillow\Tests\test_file_wmf.py:58: DeprecationWarning: Please use assertEqual instead.
self.assertEquals(im.size, (82, 82))
Tests/test_file_wmf.py::TestFileWmf::test_load_set_dpi
d:\a\Pillow\Pillow\Tests\test_file_wmf.py:62: DeprecationWarning: Please use assertEqual instead.
self.assertEquals(im.size, (164, 164))
-- Docs: https://docs.pytest.org/en/latest/warnings.html
```
> Fix deprecation warnings in test_file_wmf

- Tests/test_file_gif.py
- src/PIL/GifImagePlugin.py
Resolves #4325 
The issue reports that saving a GIF with a string comment results in an error. A simple reproduction would be -
```python
im = Image.new("L", (100, 100))
im.save("test.gif", comment="comment")
```
This PR fixes it by encoding the comment into bytes, if it is a string.
> Allow string comment when saving GIF

- docs/releasenotes/6.2.0.rst
Helps to resolve confusion regarding the CVE fixed in Pillow 6.2.0 - see #4123
> Added security changes to past release notes

- .coveragerc
`Image.DEBUG` was removed in #1207, so it can be removed from .coveragerc
> Removed unnecessary coverage line

- CHANGES.rst
- docs/releasenotes/6.2.2.rst
For the fixes already released in Pillow 6.2.2 and 7.0.0.
> Add assigned CVE numbers

- .travis.yml
- .travis/after_success.sh
For https://github.com/python-pillow/Pillow/issues/3606.
* PR https://github.com/python-pillow/Pillow/pull/4316 added coverage to Docker on the faster GitHub Actions
* We can now remove Docker builds from Travis CI
* Ran for 13 min 5 sec
* Total time 50 min 59 sec
* Ran for 9 min 9 sec
* Total time 19 min 45 sec
> Remove Docker from Travis CI, they're run on GHA

- .travis/install.sh
PyQt5 5.14.1 was released 9 hours ago - https://pypi.org/project/PyQt5/5.14.1/#history
Since then, tests have been failing in master. This is presumably a temporary measure until PyQt5 5.14.2 is released.
> Do not install PyQt5 5.14.1

- LICENSE
* Word wrap `LICENSE` file
When generating a LICENSE report using [`pip-licenses`](https://github.com/raimon49/pip-licenses), Pillow is one of the very few projects in the dependency graph that does not word wrap its LICENSE file. This causes a very large rightward drift when the license report is generated and shown to the user.
This PR simply wraps the LICENSE file lines to make it match most other LICENSE files and display better to a user reading a LICENSE report.
> Word wrap LICENSE file

- .travis/after_success.sh
> Coverage and quality reports on just the latest diff.
If 'latest' refers to the latest Python version, then this should be updated from 3.7 to 3.8.
> Updated Python version

- docs/installation.rst
libtiff 4.1.0 is now tested, as of #4195
> Updated tested libtiff versions

- Tests/helper.py
- Tests/test_file_spider.py
- Tests/test_file_tga.py
- Tests/test_file_webp_animated.py
- Tests/test_file_xbm.py
- Tests/test_image_resample.py
- Tests/test_imagegrab.py
Some commits simplifying test code, some commits adding new tests.
I think the only commits that need commentary are -
- Removed print: Removes a `print` statement that doesn't look necessary or helpful
- Removed unnecessary code: Removes code if `__version__` contains 'rc'. Pillow doesn't use 'rc' versions.
> Various test changes

- docs/reference/ImageDraw.rst
Resolves #4367 
Updates the defaults for `spacing` in the documentation, so that [`text`](https://github.com/python-pillow/Pillow/blame/master/docs/reference/ImageDraw.rst#L258) and [`multiline_text`](https://github.com/python-pillow/Pillow/blame/master/docs/reference/ImageDraw.rst#L309)
matches https://github.com/python-pillow/Pillow/blob/a520a435d6b6534a3db2c9457328b6a90733a793/src/PIL/ImageDraw.py#L263-L270 and https://github.com/python-pillow/Pillow/blob/a520a435d6b6534a3db2c9457328b6a90733a793/src/PIL/ImageDraw.py#L353-L360
For reference, itooks like #1574 just forgot to update the documentation.
> Updated spacing defaults documentation

- .ci/after_success.sh
- .github/workflows/test-docker.yml
- .github/workflows/test.yml
- requirements.txt
Removes coveralls, since codecov is now used for assessing coverage.
As evidence that codecov is not affected by this, compare [before](https://codecov.io/gh/python-pillow/Pillow/commit/a520a435d6b6534a3db2c9457328b6a90733a793) with [after](https://codecov.io/gh/python-pillow/Pillow/tree/8dee4c2ceed04dace04ad0930eee4996d078fd81).
> Removed coveralls

- docs/handbook/tutorial.rst
Updates the tutorial in light of #4302, and in light of the fact that `StringIO.StringIO` doesn't exist in Python 3.
> Use BytesIO instead of StringIO

- .github/workflows/test-windows.yml
Fixes #4382.
* Instead of downloading and installing PyPy ourselves, use the one now available from GHA: https://github.com/marketplace/actions/setup-python-environment
* Saves about a minute of download/install time from the build
```
Python 3.6.9 (1608da62bfc7, Dec 23 2019, 12:38:24)
[PyPy 7.3.0 with MSC v.1911 32 bit]
...
================ 1357 passed, 76 skipped in 161.27s (0:02:41) =================
```
https://github.com/python-pillow/Pillow/runs/407161674?check_suite_focus=true#step:24:16
```
Python 3.6.9 (1608da62bfc7, Dec 23 2019, 12:38:24)
[PyPy 7.3.0 with MSC v.1911 32 bit]
...
================ 1357 passed, 76 skipped in 162.05s (0:02:42) =================
```
https://github.com/hugovk/Pillow/runs/408857182?check_suite_focus=true#step:23:16
> Use GHA-installed PyPy3

- .github/workflows/test-windows.yml
- .github/workflows/test.yml
Saw this in a failed test in #4378 
```
2020-01-25T02:08:26.0031734Z ##[error]Process completed with exit code 1.
2020-01-25T02:08:26.0213052Z ##[group]Run actions/upload-artifact@v1
2020-01-25T02:08:26.0213188Z with:
2020-01-25T02:08:26.0213274Z   name: errors
2020-01-25T02:08:26.0213352Z   path: Tests/errors
2020-01-25T02:08:26.0213415Z env:
2020-01-25T02:08:26.0213494Z   pythonLocation: d:\a\Pillow\pypy3.6
2020-01-25T02:08:26.0213574Z ##[endgroup]
2020-01-25T02:08:26.2089374Z ##[error]Path does not exist d:\a\Pillow\Pillow\Tests\errors
2020-01-25T02:08:26.2448668Z ##[error]Exit code 1 returned from process: file name 'c:\runners\2.164.0\bin\Runner.PluginHost.exe', arguments 'action "GitHub.Runner.Plugins.Artifact.PublishArtifact, Runner.Plugins"'.
2020-01-25T02:08:26.2467880Z Cleaning …
```
> Ensure that errors directory exists before trying to upload from it

- src/PIL/Image.py
- src/PIL/ImageFile.py
- src/map.c
`extents` does not need to be passed into `Image.core.map_buffer`, as the corresponding variable. `bbox` is not used in `PyImaging_MapBuffer`.
> extents are not used by map_buffer

- .appveyor.yml
- .ci/after_success.sh
- .github/workflows/test-docker.yml
- .github/workflows/test-windows.yml
- .github/workflows/test.yml
* Add flags for each upload of coverage to Codecov
* flags must match pattern `^[\w\,]+$`
* This allows us to easily filter by group (see top-right corner), to see which groups cover different bits of code, or if one is missing
* For example, we can see there's no GHA Windows coverage, and that only Travis CI has Qt coverage
* https://codecov.io/gh/hugovk/Pillow/src/b55e5b6d5f8c3bdf0c24f7cf06140ef3104ff569/Tests/test_imageqt.py
cc @nulano @radarhere
> Add flags to Codecov for easier coverage checking/debugging

- Tests/test_000_sanity.py
- Tests/test_binary.py
- Tests/test_box_blur.py
- Tests/test_core_resources.py
- Tests/test_file_bufrstub.py
- Tests/test_file_container.py
- Tests/test_file_gd.py
- Tests/test_file_gimppalette.py
- Tests/test_file_wal.py
- Tests/test_format_lab.py
- Tests/test_image_getbands.py
- Tests/test_image_getbbox.py
- Tests/test_image_getim.py
- Tests/test_image_getpalette.py
- Tests/test_image_putpalette.py
- Tests/test_image_tobytes.py
- Tests/test_imagestat.py
- Tests/test_locale.py
- Tests/test_main.py
- Tests/test_util.py
To better follow conventional pytest style, this removes the outer
wrapper class in favor of a function for some tests. These tests were
picked as they are relatively simple and presented no barriers to a
quick port. The assert* methods are replaced with assert statements.
When necessary, a fixture is used to create a temporary directory.
This commit does not convert the entire test suite to this style as some
test classes use methods or other advanced features that are difficult
to automatically convert. The goal is to address these issues in
followup commits.
Refs #4193
---
To reviewers, I'm happy expand or shrink the scope of this change as desired. If there is a preference for this to be split up over multiple commits, let me know. I'm happy to make adjustments.
> Convert some tests to pytest style

- .github/codecov-upstream.yml
- codecov.yml
Codecov comments have started showing up again, for example: https://github.com/python-pillow/Pillow/pull/4384#issuecomment-578510771.
In their [22 Sept 2019 docs](https://web.archive.org/web/20190922233407/https://docs.codecov.io/docs/pull-request-comments):
```yml
comment: off
```
But in the next one, on [17 Jan 2020 docs](https://web.archive.org/web/20200117175353/https://docs.codecov.io/docs/pull-request-comments) and [today](https://docs.codecov.io/docs/pull-request-comments), it's changed:
```yml
comment: false
```
> Re-disable Codecov PR comment

- src/PIL/PdfImagePlugin.py
- src/PIL/PdfParser.py
The function was introduced in 65112bad7e4a692ea01980a642e540ec4c0a2fcb
to handle the differences between Python 2 & 3 byte handling. Now that
Python 3 supports byte formatting, can drop the unnecessary
compatibility shim in favor of native features.
> Remove unnecessary make_bytes() function

- Makefile
- setup.cfg
- setup.py
The pytest-runner package is deprecated and its use is discouraged. See:
https://github.com/pytest-dev/pytest-runner/
> pytest-runner depends on deprecated features of setuptools and relies
> on features that break security mechanisms in pip. For example
> 'setup_requires' and 'tests_require' bypass pip --require-hashes. See
> also https://github.com/pypa/setuptools/issues/1684.
>
> It is recommended that you:
>
> - Remove 'pytest-runner' from your 'setup_requires', preferably
>   removing the setup_requires option.
> - Remove 'pytest' and any other testing requirements from
>   'tests_require', preferably removing the setup_requires option.
> - Select a tool to bootstrap and then run tests such as tox
Running tests should go through the tox entrypoint.
> Remove deprecated pytest-runner support

- src/PIL/PdfParser.py
In Python 3, `__str__` should not return bytes.
> Remove leftover Python 2 compatibility shim

- docs/Makefile
Link checking is is run as part of `make doc`, and calls `make -C docs linkcheck` which calls `sphinx-build`.
```
$ console
sphinx-build --help
...
general options:
...
-j N              build in parallel with N processes where possible (special value "auto" will set N to cpu-count)
```
Before, three runs of `make -C docs linkcheck` took:
* 1m35s
* 1m38s
* 1m29s
After:
* 19s
* 23s
* 15s
> Docs: Speed up linkcheck by checking in parallel

- docs/porting.rst
Porting from PIL to Pillow will require the rest of your code to be ported from Python 2 to 3.
> Unlike PIL, Pillow does not support Python 2

- src/libImaging/ImagingUtils.h
The clangs UndefinedBehaviorSanitizer complains about signed overflow in the `(255 << 24)` expression:
```
Pillow/libImaging/Unpack.c:491:21: runtime error: left shift of 255 by 24 places cannot be represented in type 'int'
```
But the unsigned left shift is completely defined.
> Avoid undefined signed overflow

- .ci/test.sh
- .github/workflows/test-windows.yml
- Tests/test_file_jpeg.py
- Tests/test_file_tiff_metadata.py
- tox.ini
Appeared in the form:
ResourceWarning: unclosed file <_io.BufferedReader name='Tests/images/invalid-exif-without-x-resolution.jpg'>
Enable all warnings to always display during tests to help catch these
warnings earlier.
> Fix ResourceWarning emitted during tests

- Tests/helper.py
Use the builtin shutil.which() instead of reimplementing.
For the single use that used the output of the command, use
subprocess.run().
> Simplify command discovery with stdlib shutil.which()

- Tests/test_imagedraw.py
master has started failing tests after the merging of #4333, as it was not updated for the pytest changes.
> Updated test

- src/libImaging/QuantHeap.c
- src/libImaging/QuantOctree.c
Fixes sign comparison warnings in QuantHeap.c and QuantOctree.c when compiling - https://travis-ci.org/python-pillow/Pillow/jobs/629766167#L2174-L2200
> Fixed Quant sign comparison warnings

- Tests/test_file_container.py
- src/PIL/ContainerIO.py
Alternative to #4192 
That PR changes ContainerIO to return bytes instead of strings.
This PR changes ContainerIO to return strings if the file object is a string object, and bytes if the file object is a bytestring object.
> Change ContainerIO return type to match file object mode

- src/PIL/ImageCms.py
If not on Windows, the ImageCms `get_display_profile` function checks for `_imagingcms.get_display_profile`. That method does not exist. It wasn't in PIL 1.1.17, and hasn't existed since the fork. So this PR cleans up the code, returning quickly on non-Windows platforms, rather than performing a failing check.
> get_display_profile is only supported on Windows

- src/PIL/IcnsImagePlugin.py
When using the `__main__` functionality of IcnsImagePlugin, I found a bug.
> $ python IcnsImagePlugin.py in.icns
> Traceback (most recent call last):
>   File "IcnsImagePlugin.py", line 373, in <module>
>     im.save("out-%s-%s-%s.png" % size)
> AttributeError: 'ImagingCore' object has no attribute 'save'
https://github.com/python-pillow/Pillow/blob/29fee8fc43d59dd65b7c533def44548aa5b9bc12/src/PIL/IcnsImagePlugin.py#L372-L373
This PR fixes that bug, and also ensures that the file pointer that is opened is closed again.
> Fix saving bug in IcnsImagePlugin __main__

- Tests/conftest.py
The `%s` placeholder already coerces arguments to a string.
> Remove redundant str() call

- Tests/test_pickle.py
In Python 3, cPickle and pickle have been merged to a single module.
From https://docs.python.org/3/whatsnew/3.0.html#library-changes
> A common pattern in Python 2.x is to have one version of a module
> implemented in pure Python, with an optional accelerated version
> implemented as a C extension; for example, pickle and cPickle. This
> places the burden of importing the accelerated version and falling
> back on the pure Python version on each user of these modules. In
> Python 3.0, the accelerated versions are considered implementation
> details of the pure Python versions. Users should always import the
> standard version, which attempts to import the accelerated version and
> falls back to the pure Python version. The pickle / cPickle pair
> received this treatment.
Can now move the …
> Remove testing of Python-2-only cPickle module

- Tests/conftest.py
- Tests/test_file_gimpgradient.py
- Tests/test_file_jpeg.py
- Tests/test_file_jpeg2k.py
- Tests/test_file_libtiff.py
- Tests/test_image.py
- Tests/test_image_mode.py
- Tests/test_imagedraw2.py
These modules are safe to import and this better follows PEP 8.
From https://www.python.org/dev/peps/pep-0008/#imports
> Imports are always put at the top of the file, just after any module
> comments and docstrings, and before module globals and constants.
> Move safe imports to the top of test files

- Tests/test_imagefont.py
The class more or less duplicates the features of the mock module. Can avoid the duplication by using the stdlib.
> Replace SimplePatcher with builtin unittest.mock module

- Tests/check_j2k_leaks.py
- Tests/helper.py
- Tests/test_features.py
- Tests/test_file_eps.py
- Tests/test_file_gif.py
- Tests/test_file_jpeg.py
- Tests/test_file_jpeg2k.py
- Tests/test_file_libtiff.py
- Tests/test_file_mic.py
- Tests/test_file_mpo.py
- Tests/test_file_png.py
- Tests/test_file_tar.py
- Tests/test_file_webp.py
- Tests/test_file_webp_animated.py
- Tests/test_file_webp_lossless.py
- Tests/test_file_webp_metadata.py
- Tests/test_font_leaks.py
- Tests/test_font_pcf.py
- Tests/test_image_draft.py
- Tests/test_image_split.py
- Tests/test_imagedraw.py
- Tests/test_imagedraw2.py
- Tests/test_imagefile.py
- Tests/test_imagefont.py
- Tests/test_imagefontctl.py
- Tests/test_imageops.py
- Tests/test_imagesequence.py
- Tests/test_tiff_ifdrational.py
- Tests/test_webp_leaks.py
This adds a new test decorator: `skip_unless_feature()`. The argument is the same as passed to `features.check()`. If the feature is not supported, the test will be skipped.
This removes several kinds of boilerplate copied and pasted around tests so test feature checking is handled and displayed more consistently.
Refs #4193
> Streamline test skipping based on supported features

- docs/installation.rst
* To use Pillow's Python 3.8 wheels on Windows, pip >= 19.2 is needed
* I realised https://github.com/python-pillow/Pillow/pull/4214 missed the `--upgrade` switch so never actually recommended upgrading pip, as intended
* So do it here
> Docs: Recommend upgrading pip and Pillow

- Tests/test_file_fpx.py
- Tests/test_file_mic.py
- Tests/test_file_webp_alpha.py
- Tests/test_file_webp_animated.py
- Tests/test_file_webp_lossless.py
- Tests/test_file_webp_metadata.py
- Tests/test_map.py
- Tests/test_numpy.py
- Tests/test_pyroma.py
For #4193.
* First commit: Use pytest.importorskip to skip on a missing import dependency
* https://docs.pytest.org/en/latest/skipping.html#skipping-on-a-missing-import-dependency
* Second commit: Also convert the touched files to use pytest
> Use pytest.importorskip to skip on a missing import dependency

- docs/index.rst
See https://pillow.readthedocs.io/en/latest/ vs https://github.com/python-pillow/Pillow/blob/master/README.rst ... vs https://pillow-radarhere.readthedocs.io/en/docs_badges/
> Changed docs badges to be closer to README badges

- .github/workflows/test.yml
* Use the Codecov bash uploader for macOS and Linux, because the Action was times out on macOS after 12 minutes
* Fixes macOS coverage
---
Recently, the Codecov Action for uploading coverage has been timing out after about 12 minutes on macOS. Most recent master build:
```
2020-02-21T22:12:07.4228970Z [0;90m==>[0m Uploading reports
2020-02-21T22:12:07.4230580Z     [0;90murl:[0m https://codecov.io
2020-02-21T22:12:07.4231890Z     [0;90mquery:[0m branch=master&commit=20d6b6271ce329870e1fab7f6b750838eb56510e&build=&build_url=http%3A%2F%2Fgithub.com%2Fpython-pillow%2FPillow%2Factions%2Fruns%2F&name=macOS-latest%20Python%20pypy3&tag=&slug=python-pillow%2FPillow&service=github-actions&flags=GHA_macOS&pr=&job=
2020-02-21T22:12:07.4336250Z …
```
> Use Codecov bash because the Action times out on macOS

- Tests/test_file_jpeg.py
- docs/handbook/image-file-formats.rst
- docs/releasenotes/7.1.0.rst
- src/PIL/JpegImagePlugin.py
- src/libImaging/Jpeg.h
- src/libImaging/JpegEncode.c
Resolves #4439
Since PIL, a JPEG quality of 0 has been used to indicate default quality. This PR changes that indicating value from 0 to -1, so that JPEG images of actual 0 quality can be produced.
> Allow saving of zero quality JPEG images

- src/_imagingft.c
- src/_webp.c
Use [METH_NOARGS](https://docs.python.org/3/c-api/structures.html#METH_NOARGS ) when no arguments are being used, rather than always using [METH_VARARGS](https://docs.python.org/3/c-api/structures.html#METH_VARARGS).
Also removes `has_more_frames` since it is not referenced anywhere.
> Use METH_NOARGS when no arguments are required

- Tests/test_features.py
- src/PIL/features.py
If the feature isn't one of the recognized types, a UserWarning is emitted.
> Warn on typos passed to features.check()

- Tests/test_image_getbbox.py
- docs/releasenotes/7.1.0.rst
- src/libImaging/GetBBox.c
Resolves #4453 
Changes `getbbox` for modes RGBA, RGBa, PA, LA and La.
Testing, I find that the current functionality is to trim black transparent pixels. This PR changes it to trim any transparent pixels, regardless of color.
> If present, only use alpha channel for bounding box

- Tests/test_image_thumbnail.py
- src/PIL/Image.py
The current size calculation is fine if only one axis is smaller or if the image is wide, but it trips up when both axes are smaller and the image is tall. Here's an example:
```py
im = Image.new("L", (145, 100))
im.thumbnail((50, 50))
assert im.size == (50, 34)  # This is fine, the image is wide.
im = Image.new("L", (100, 145))
im.thumbnail((100, 50))
assert im.size == (34, 50)  # Also fine, only one axis is smaller.
im = Image.new("L", (100, 145))
im.thumbnail((50, 50))
assert im.size == (34, 50)  # Oh no! It returned (35, 50)!
```
Someone made a [pull request](https://github.com/python-pillow/Pillow/pull/2089) that fixed this in 2016, but it looks like he closed it shortly after due to a CI failure.
> Fix size calculation of Image.thumbnail()

- Tests/test_file_jpeg.py
- docs/handbook/image-file-formats.rst
- docs/releasenotes/7.1.0.rst
- src/PIL/JpegImagePlugin.py
Resolves #4450 
Adds JPEG comment to the `info` dictionary, in the same way that [GIF](https://github.com/python-pillow/Pillow/blob/1c1ad65a9646f73d80ce8f77894a447b03f203a6/src/PIL/GifImagePlugin.py#L213) and [GBR](https://github.com/python-pillow/Pillow/blob/1c1ad65a9646f73d80ce8f77894a447b03f203a6/src/PIL/GbrImagePlugin.py#L78) do.
> Add JPEG comment to info dictionary

- docs/installation.rst
https://github.com/python/pythondotorg/issues/1549 details someone's difficulty pip installing Pillow.
Whilst it's more a general Python issue than a Pillow issue, one reply is (https://github.com/python/pythondotorg/issues/1549#issuecomment-583545173):
> Thanks for the report. I think the main issue here is the continuing confusion between Python 2 and Python 3 command names and scripts, something not unique to macOS installations of Python. The confusion here could have been avoided by better documentation of the differences between using the command nanes`python`, `python2`, and `python3` and similarly `pip`, `pip2`, and `pip3`. Yes, use of virtual environments is one way to avoid the differences, in that an active Python 3 virtual environment provides a `python` and `pip` _alias_ to …
> Docs: Avoid ambiguity by explicitly invoking python3

- Tests/README.rst
- docs/deprecations.rst
As in the likes of #4214 and #4459, invoke pip from Python to avoid possible confusion.
> Invoke pip using python3

- .github/workflows/test-docker.yml
If one job fails, keep running the others.
This will allow us to see if the others pass, and whether the failure was unique to a given job.
We have this set for the other two, test.yml and test-windows.yml, and we have the build capacity.
Docs: https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
> GHA Docker: Don't cancel all jobs if any another fails

- docs/installation.rst
At https://pillow.readthedocs.io/en/latest/installation.html#building-on-macos, I find the lack of symmetry between the `python` invocations odd.
So this PR switches it and another situation to use `python3`, like the `pip` commands.
> install using Python 3

- .github/workflows/lint.yml
- .pre-commit-config.yaml
- .travis.yml
- MANIFEST.in
- tox.ini
[pre-commit](https://pre-commit.com)  can be used locally to check files when committing. If problems are found, it stops the commit with an error message. Some tools (like Black and isort) also fix the problems they find.
Fail fast, fail early.
pre-commit is not for everyone, and it's not mandatory to run it locally. I didn't used to be keen, but now I find it really helpful. It's important it doesn't take too long to run.
Even if you don't run it locally, and there's absolutely no requirement to do so, it's handy for grouping together and pinning many linters, and running on the CI.
Here are the main commands for local use:
```bash
pip install pre-commit
pre-commit install
git commit -m "something"
git commit -m "something" -n
pre-commit run all-files
pre-commit autoupdate  # and then …
```
> Run lint with pre-commit

- src/map.c
Resolves #4329 
In `PyImaging_MapBuffer`, [`Py_Buffer view`](https://github.com/python-pillow/Pillow/blob/d33d467169250d1277b32167eb184623c61c34c7/src/map.c#L313) is [set up](https://github.com/python-pillow/Pillow/blob/d33d467169250d1277b32167eb184623c61c34c7/src/map.c#L353), and [when the image is destroyed](https://github.com/python-pillow/Pillow/blob/d33d467169250d1277b32167eb184623c61c34c7/src/map.c#L378), it is [released](https://github.com/python-pillow/Pillow/blob/d33d467169250d1277b32167eb184623c61c34c7/src/map.c#L298-L302). However, if the function returns before that, then `view` is not released.
The setup [calls `PyObject_GetBuffer`](https://github.com/python-pillow/Pillow/blob/d33d467169250d1277b32167eb184623c61c34c7/src/_imaging.c#L247-L250), which is documented to require …
> Release buffer if function returns prematurely

- src/PIL/ImageCms.py
Building and running Pillow tests in a Windows Server Docker instance fails for two tests `test_imagecms.test_display_profile` and `test_imagegrab.test_grab` because it is run headless.
While I think the `test_grab` failure is reasonable, the other test fails with a TypeError raised from `ImageCms.get_display_profile`, which is confusing at best. This is caused by [`ImageCms.core.get_display_profile_win32` returning None](https://github.com/python-pillow/Pillow/blob/3aa5d56bae3b9cee79fa88ed6e5be7bb28fc96e4/src/_imagingcms.c#L622), which is obviously not accepted by the `ImageCmsProfile` constructor. This PR proposes returning None instead (in accordance with the functions docs).
> Return None if display profile not found in ImageCms.get_display_profile

- Tests/test_image_getextrema.py
- src/libImaging/GetBBox.c
Helps #4213
Using the endian handling in https://github.com/python-pillow/Pillow/blob/b73e3dddcc9e6b3039db366b202254f693ccd13d/src/libImaging/Unpack.c#L1042-L1046 as inspiration, fixes `getextrema` I;16 operations for big-endian.
> Fixed endian handling for I;16 getextrema

- src/_webp.c
Changes proposed in this pull request: release GIL in WEBP encoding.
I don't know if the patch is the right way to do it, but it works for me and it makes webp encoding in threads scale, so even if the patch is bad, please do the feature.
> Release Python GIL during WEBP encode

- src/_imagingft.c
Add missing brackets to if clause to avoid possible undefined behaviour.
> Add missing if brackets

- Tests/bench_cffi_access.py
- Tests/check_fli_overflow.py
- Tests/check_imaging_leaks.py
- Tests/check_j2k_leaks.py
- Tests/check_j2k_overflow.py
- Tests/check_jpeg_leaks.py
- Tests/check_large_memory.py
- Tests/check_large_memory_numpy.py
- Tests/check_libtiff_segfault.py
- Tests/check_png_dos.py
- Tests/helper.py
- Tests/test_decompression_bomb.py
- Tests/test_file_wmf.py
- Tests/test_font_pcf.py
- Tests/test_image_fromqimage.py
- Tests/test_image_paste.py
- Tests/test_image_resize.py
- Tests/test_imagefont.py
- Tests/test_imageops_usm.py
- Tests/test_imageqt.py
- Tests/test_qt_image_fromqpixmap.py
- Tests/test_qt_image_toqimage.py
- Tests/test_qt_image_toqpixmap.py
- codecov.yml
Helps #4193
Converts all uses of PillowTestCase to pytest, so that PillowTestCase is no longer needed.
> Removed PillowTestCase helper class

- Tests/test_file_jpeg2k.py
- Tests/test_image_reduce.py
- src/PIL/Image.py
- src/PIL/Jpeg2KImagePlugin.py
Resolves #4343. Alternative to #4344
The new Image `reduce` method does not work for Jpeg2K images, as [Jpeg2KImagePlugin has a `reduce` variable that masks it](https://github.com/python-pillow/Pillow/blob/ef4a0b2f4c9346db37140f102e80068abc280167/src/PIL/Jpeg2KImagePlugin.py#L179). The variable is not purely internal, but is actually tested behaviour -
https://github.com/python-pillow/Pillow/blob/ef4a0b2f4c9346db37140f102e80068abc280167/Tests/test_file_jpeg2k.py#L112-L116
PR #4344 tried to address this by treating the setting of `reduce` as an integer, and the use of `reduce` as a method, as two different scenarios that were not to interact.
So instead, this PR changes Pillow so that if you set `reduce` as an integer, the user will then see `reduce` as an integer.
```python
with …
```
> Prevent masking Image reduce method in Jpeg2K

- Tests/test_imagechops.py
- docs/reference/ImageChops.rst
- src/PIL/ImageChops.py
- src/_imaging.c
- src/libImaging/Chops.c
- src/libImaging/Imaging.h
Add the channel operations Soft Light, Hard Light and Overlay, using the algorithms defined here: http://www.pegtop.net/delphi/articles/blendmodes/
> Added three new channel operations

- docs/releasenotes/7.1.0.rst
> Document new channel operations

- CHANGES.rst
- docs/deprecations.rst
- docs/releasenotes/7.1.0.rst
- src/PIL/Image.py
- src/PIL/__init__.py
`PILLOW_VERSION` was deprecated in Pillow 5.2.0 in July 2018 (https://github.com/python-pillow/Pillow/pull/3090, https://github.com/python-pillow/Pillow/pull/3782) and removed in 7.0.0 in January 2020 (https://github.com/python-pillow/Pillow/pull/4107).
However, it didn't raise a deprecation warning. The removal has caused problems for users of torchvision.
torchvision had already updated to use `__version__ ` in October 2019 (https://github.com/pytorch/vision/pull/1501) but when Pillow 7.0.0 came out on 2020-01-02, had not yet released it (https://github.com/pytorch/vision/issues/1712).
The fixed [torchvision 0.5.0](https://github.com/pytorch/vision/releases/tag/v0.5.0) was released on 2020-01-16.
However, some people are still having difficulties using torchvision 0.5.0 and Pillow 7.0.0 …
> Re-add deprecated PILLOW_VERSION to give projects more time to upgrade

- Tests/test_imagegrab.py
- docs/reference/ImageGrab.rst
- setup.py
- src/PIL/ImageGrab.py
- src/PIL/features.py
- src/_imaging.c
- src/display.c
Partially resolves #2028
Alternative to #4198
* Add `ImageGrab.grab()` support for X11 (Linux) using the XCB library (only screenshots for now, clipboard can be added in the future)
There is also support for taking X11 screenshots on Windows and macOS (where X11 can be installed as a separate window manager). This proposed implementation uses the old methods if `xdisplay=None` is passed, but if `xdisplay=""` is passed (or on Linux), it will grab the default X11 screen (likely from the DISPLAY envvar). A different value can be passed in the `xdisplay` parameter to override the default X11 screen address.
Unlike [mss](https://github.com/BoboTiG/python-mss) which uses Xlib, this uses XCB. This provides more resilient error handling at the cost of …
> ImageGrab.grab() for Linux with XCB

- docs/installation.rst
- docs/releasenotes/7.1.0.rst
Release notes for #4260 
Update installation docs for #4260 and #4029 
I'm assuming Windows and macOS don't need (and will not have) XCB support in distributed wheels, as this is quite an unusual (although valid) scenario; please correct this if necessary. (I don't think XCB even supports Windows outside MinGW.)
> Update install docs and release notes for #4260

- Tests/test_file_png.py
- src/PIL/PngImagePlugin.py
Fixes #4509.
* Initialise `__frame` to 0 to fix `seek` after open
> Fix PNG seek

- Tests/test_file_png.py
- docs/reference/plugins.rst
- src/PIL/PngImagePlugin.py
Resolves #4518
Looking at PngImagePlugin, there's no need for `n_frames` or `is_animated` to use property decorators - they can just be regular properties.
You might think this is just a simplification of the code, and that it would have no effect on behaviour. This is not the case - the common [`_seek_check` method](https://github.com/python-pillow/Pillow/blob/8c9100e267f40a63081b344220abaa57325a3d6d/src/PIL/ImageFile.py#L294-L306) changes behaviour. If `_n_frames` is present, and `None`, then it doesn't check the upper limit on the frame number, because that would potentially require seeking all the way to the end of the file. Now that there is no `_n_frames`, it checks the upper limit, and throws an `EOFError`.
I've added a test to ensure that an EOFError is thrown moving forward. …
> Raise an EOFError when seeking too far in PNG

- .ci/install.sh
Helps #4508 
The issue reports that `apt-get update` is failing sometimes. This PR attempts to help by running the command up to two more times if there is a warning or error.
However, when I did manage to see `apt-get update` fail on this branch, the command ran again, but it also failed on the subsequent attempts. So be aware of that.
> Retry on apt-get update problems

- docs/conf.py
https://travis-ci.org/github/python-pillow/Pillow/jobs/671584849#L4879-L4880
> /home/travis/build/python-pillow/Pillow/docs/conf.py:292: RemovedInSphinx40Warning: The app.add_javascript() is deprecated. Please use app.add_js_file() instead.
>   app.add_javascript("js/script.js")
This change is documented at https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_js_file
> Updated deprecated method

- docs/releasenotes/7.1.0.rst
* CVE-2020-10177 #4503 Fix multiple OOB reads in FLI decoding
* CVE-2020-10378 #4506 Fix bounds overflow in PCX decoding
* CVE-2020-10379 #4507 Fix two buffer overflows in TIFF decoding
* CVE-2020-10994 #4505 Fix bounds overflow in JPEG 2000 decoding
* CVE-2020-11538 #4504 Fix buffer overflow in SGI-RLE decoding
> Update 7.1.0 release notes with CVEs

- .github/workflows/test.yml
* Revert https://github.com/python-pillow/Pillow/commit/fbb14f67a30b612454bc7cf9a5f73d6b35e7eb14 from https://github.com/python-pillow/Pillow/pull/4284 as `make doccheck` is now possible on GitHub Actions
* Do it only for Python 3.8 on Ubuntu
> GHA: Check docs

- .github/workflows/test-docker.yml
- .github/workflows/test-windows.yml
- .github/workflows/test.yml
Some steps in the GHA have the condition `if: success()`.
[This may not actually change the default behaviour](https://github.com/python-pillow/Pillow/pull/4524#discussion_r405058257). So this PR removes it for simplicity.
> Removed success conditions

- docs/reference/Image.rst
Adds `getexif` method to Image documentation.
Inspired by https://github.com/python-pillow/Pillow/issues/4537#issuecomment-612008156
> Document getexif

- MANIFEST.in
- Tests/helper.py
* "The GitHub Actions runner now sets the CI=true environment variable by default"
* https://github.blog/changelog/2020-04-15-github-actions-sets-the-ci-environment-variable-to-true/
* We also removed Azure Pipelines in https://github.com/python-pillow/Pillow/pull/4387
> GitHub Actions now sets CI=true

- src/PIL/ImageFile.py
- src/PIL/TiffImagePlugin.py
Minor rearrangement of code, so that `OSError("cannot load this image")` can be thrown before calling `Image.load`.
`Image.load` doesn't affect the `self.tile` check that leads to the error, so this is just faster.
> Throw image loading error faster

- Tests/test_pickle.py
- src/PIL/WebPImagePlugin.py
Fixes #4559. 
* Fix pickling and unpickling WebP
* Refactor some similar tests to use `pytest.mark.parametrize` to reduce duplication and make tests independent
> Fix pickling WebP

- Tests/test_pickle.py
After #4561, these default arguments are not used anymore.
> Removed default arguments from pickle test helper functions

- Tests/test_pickle.py
- src/PIL/TiffImagePlugin.py
Resolves #3690
When trying to load an unpickled TIFF, an error is currently thrown because `self.use_load_libtiff` is not defined.
https://github.com/python-pillow/Pillow/blob/529e1135059f76d3ba3733d18fe7f8ea82e3c679/src/PIL/TiffImagePlugin.py#L1068-L1071
Now, one solution could be to set that variable on initialisation, but there is another way that I think is simpler (in the end. It might require some explanation first)
The only place that `self.use_load_libtiff` is set is in `_setup`.
https://github.com/python-pillow/Pillow/blob/529e1135059f76d3ba3733d18fe7f8ea82e3c679/src/PIL/TiffImagePlugin.py#L1289
`_setup` is called when seeking, and there is an initial seek upon opening. So we don't need to worry about this variable for any seeking of an unpickled image, just the load operation …
> Fixed bug when unpickling TIFF images

- src/PIL/DcxImagePlugin.py
- src/PIL/FliImagePlugin.py
- src/PIL/MicImagePlugin.py
- src/PIL/MpoImagePlugin.py
- src/PIL/PsdImagePlugin.py
- src/PIL/TiffImagePlugin.py
- src/PIL/WebPImagePlugin.py
* Replaced property methods for n_frames and/or is_animated with normal properties
* Use the common `_seek_check` method in WebP
* Since WebP has `__logical_frame` set to zero on initialisation now, thanks to #4561, the initial seek to zero has no effect, and can be removed
> Simplified animation code

- Tests/test_imagefile.py
Should be `pytest.warns(DeprecationWarning)` not `pytest.raises(DeprecationWarning)`
```console
$ pytest Tests/test_imagefile.py -k raise_ioerror
========================================================= test session starts =========================================================
<snip>
Tests/test_imagefile.py .                                                                                                       [100%]
========================================================== warnings summary ===========================================================
Tests/test_imagefile.py::TestImageFile::test_raise_ioerror
/Users/hugo/github/Pillow/src/PIL/ImageFile.py:69: DeprecationWarning: raise_ioerror is deprecated and will be removed in a future release. Use raise_oserror instead. …
```
> Don't show own deprecation warning in test logs

- src/PIL/Image.py
We link to the [Filters concept](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#concept-filters) when mentioning filters in the parameters for `Image.resize` and `Image.rotate`:
* https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.resize
* https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.rotate
But not for `Image.thumbnail` or `Image.transform`:
https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.thumbnail
https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.transform
Let's add it to those two too.
> Link to Filters concept from methods' parameters

- .github/workflows/test-docker.yml
Fedora 30 will be EOL on 2020-06-03, before the next scheduled Pillow 7.2.0 on 2020-07-01.
* https://fedorapeople.org/groups/schedule/f-30/f-30-all-tasks.html
See also https://github.com/python-pillow/docker-images/pull/78.
> Remove soon-EOL Fedora 30

- Tests/test_file_wmf.py
Resolves #4583
Suggestion. The difference between an epsilon of 2 and an epsilon of 2.1 seems minor to me.
> Increased epsilon to pass on Windows

- .travis.yml
Adds Python 3.9 Travis job.
Python 3.9 is still in alpha.
> Added Python 3.9

- Tests/test_imagefile.py
- src/PIL/Image.py
test_imagefile.py checks exif instead of reloaded_exif; making the tests pass when they should not.
> Fixes default offset for Exif

- .pre-commit-config.yaml
- CHANGES.rst
- depends/install_extra_test_images.sh
- docs/handbook/writing-your-own-file-decoder.rst
- docs/reference/Image.rst
- docs/reference/ImageCms.rst
* Replace spaces with tabs in non-C files
* Check for tabs in linting
PR https://github.com/python-pillow/Pillow/pull/4600 replaced the tabs with spaces in the .c and .h files. :tada: Let's keep them out with a lint checker.
Now, there are some test images (like .eps) that contain valid tabs and also makefiles must use tabs.
We've a couple of options:
* Only check certain file types (for example: .c .h .py .md .rst .txt ...?)
* Check all but exclude certain file types (Makefile .bat .cmake .eps .fits .opt)
This PR does the latter to keep the net wider. It's possible it could find a valid tab in another file in the future, and we could adjust the exclusion list then. Or, as the `exclude:` is a regex, we could also exclude directories now.
But the …
> Replace spaces with tabs and add to pre-commit linting

- docs/installation.rst
I suppose people will just try it either way but it's good to know that it still works with the same libs all the way through to 20.04
* Update the docs to mention Ubuntu versions younger than 16.04
> Mention Ubuntu versions younger than 16.04

- src/PIL/ImageChops.py
Many methods were incorrectly documented as requiring mode "1". The remaining
ones require *both* images to be mode "1".
Documentation only, [ci skip]
Fixes #2571
> Fix ImageChops documentation

- Tests/test_image_reduce.py
Hasn't cropped up because the test is passing :)
```python
average_diff = 2
max_average_diff = 1
band = "R"
msg = "average pixel value difference {:.4f} > expected {:.4f} "
"for '{}' band".format(average_diff, max_average_diff, band)
print(msg)
msg = (
"average pixel value difference {:.4f} > expected {:.4f} "
"for '{}' band".format(average_diff, max_average_diff, band)
)
print(msg)
```
```
average pixel value difference {:.4f} > expected {:.4f}
average pixel value difference 2.0000 > expected 1.0000 for 'R' band
```
> Fix broken string in test error message

- Tests/test_file_jpeg.py
* Test fails with `libjpeg-turbo` and `libjpeg-progs` on Ubuntu 16.04
* Epsilon reported is 4.18... - This PR sets it to 5.0
The test test_load_djpeg fails if the djpeg decoder is different from the one Pillow is compiled against.
> Fixes djpeg load test

- Tests/test_file_gbr.py
- src/PIL/GbrImagePlugin.py
.gbr files are not usable since on each `load()` we try to load the image from the file buffer.
This lead to an error on the second `load()` since the buffer is empty (we reached the end of the file).
* read from the file only if `self.im is None`
* a basic test doing 2 `crop` in a row that would crash without the fix
> Fix repeatedly loading .gbr

- setup.cfg
A small optimisation for when running bare `pytest` locally.
> **testpaths**
> 
> Sets list of directories that should be searched for tests when no specific directories, files or test ids are given in the command line when executing pytest from the rootdir directory. Useful when all project tests are in a known location to speed up test collection and to avoid picking up undesired tests by accident.
https://docs.pytest.org/en/stable/reference.html?highlight=testpaths#confval-testpaths
Like running `pytest Tests`, but saves a bit of typing.
Demo using `--collect-only` as this affects the test collection phase:
```console
$ # master
$ pytest --collect-only | grep " in "
============================ no tests ran in 3.18s =============================
$ pytest --collect-only | grep " in " …
```
> Add testpaths to tell pytest where to search for tests

- setup.py
```
Python 3.9.0b1 (tags/v3.9.0b1:97fe9cf, May 19 2020, 09:02:07) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
X:\Python39\lib\site-packages\PIL\Image.py:114: RuntimeWarning: The _imaging extension was built for another version of Pillow or PIL:
Core version: "7.1.2"
Pillow version: 7.1.2
warnings.warn(str(v), RuntimeWarning)
File "X:\Python39\lib\site-packages\PIL\Image.py", line 96, in <module>
raise ImportError(
ImportError: The _imaging extension was built for another version of Pillow or PIL:
Core version: "7.1.2"
Pillow version: 7.1.2
```
> Fix ImportError on Python 3.9.0b1 for Windows

- docs/reference/ImageFont.rst
Fixes https://github.com/python-pillow/Pillow/issues/4635.
> Link pilfont to its new home in pillow-scripts

- src/_imagingft.c
For #4651 
> I would assume the advance value only depends on hinting, which should probably run without the FT_LOAD_RENDER flag. In fact, the FreeType docs mention the flag FT_LOAD_BITMAP_METRICS_ONLY which seems appropriate here and conflicts with FT_LOAD_RENDER. https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#ft_load_xxx
~~While the `FT_LOAD_BITMAP_METRICS_ONLY` will likely be ignored due to `FT_LOAD_NO_BITMAP`, it should serve as a reminder for when #891 is resolved properly. *(I know the solution, I intend to submit a PR later. Essentially, Pillow should check the bitdepth of the returned bitmap instead of guessing.)*~~ Edit: Removed for now as it is not supported on all FreeType versions.
Testing I get the following results (in s) on my Windows 10 laptop …
> Do not render glyphs during text layout

- src/libImaging/Chops.c
The C function `CHOP` takes two arguments, `operation` and `mode`.
`mode` is always set to `NULL` though, so this PR just removes the argument.
> Removed unused argument from CHOP

- Tests/test_numpy.py
- src/PIL/Image.py
Resolves #4606
`fromarray` presumes that a NumPy array has a shape of at least 2 dimensions. This PR changes it so that if there is only 1 dimension, the other size dimension is 1, using the code suggestion from the issue.
> Added support for 1-D NumPy arrays

- Tests/test_imagedraw.py
- src/PIL/ImageDraw.py
Resolves #4579
The issue reports that
```python
draw.line(((400, 200), (300, 280), (100, 280)), 0, 50, joint='curve')
```
works, but
```python
draw.line((400, 200, 300, 280, 100, 280), 0, 50, joint='curve')
```
does not.
> Fixed drawing a jointed line with a sequence of numeric values

- docs/reference/ImageDraw.rst
https://pillow.readthedocs.io/en/latest/reference/ImageDraw.html
* Double quotes for strings in code examples to follow project style
* Change things like multiline_text() to `multiline_text()`
* And things like 'ltr' to `'ltr'`
* And fix the "BCP 47 language code" links. Before:
I've also flipped the switch for ReadTheDocs to "Build pull requests for this project":
https://readthedocs.org/dashboard/pillow/advanced/
Let's see how it goes. Docs about this feature: https://docs.readthedocs.io/en/latest/guides/autobuild-docs-for-pull-requests.html
> Update ImageDraw docs formatting and links

- Tests/test_file_webp_metadata.py
- src/PIL/Image.py
Resolves #4676 
`Image.Exif` currently assumes that EXIF data starts with b"Exif\x00\x00". This is not the case though, with the "Raw profile type exif" in the issue's image, or with the EXIF data in [Tests/images/flower2.webp](https://github.com/python-pillow/Pillow/blob/master/Tests/images/flower2.webp).
This PR removes that assumption.
> Corrected reading EXIF metadata without prefix

- docs/reference/ImageDraw.rst
Before - https://pillow.readthedocs.io/en/latest/reference/ImageDraw.html#PIL.ImageDraw.PIL.ImageDraw.ImageDraw.line
After - https://pillow--4679.org.readthedocs.build/en/4679/reference/ImageDraw.html#PIL.ImageDraw.PIL.ImageDraw.ImageDraw.line
> Fixed formatting

- .pre-commit-config.yaml
- Tests/test_image_filter.py
- Tests/test_imagecms.py
- src/PIL/JpegPresets.py
- src/PIL/PalmImagePlugin.py
- winbuild/build_prepare.py
* Add https://github.com/asottile/yesqa to pre-commit to remove redundant `noqa` markers
* Run pre-commit hooks which can edit code first, they may fix things later hooks would fail on
* `pre-commit autoupdate`: only updated `pre-commit/pre-commit-hooks`
> Remove redundant noqa

- Tests/test_file_jpeg.py
- src/PIL/Image.py
The `Image.Exif` class currently uses the legacy `ImageFileDirectory_v1`. This PR changes it to use `ImageFileDirectory_v2`.
Aside from the good practice of moving away from a legacy class, it also changes RATIONALs to be [read as IFDRationals, instead of a tuple with (numerator, denominator)](https://github.com/python-pillow/Pillow/blob/75716a310a1ebc965d793492a2d65a918c412180/src/PIL/TiffImagePlugin.py#L686).
A warning when saving tags [282](https://www.awaresystems.be/imaging/tiff/tifftags/xresolution.html) and [283](https://www.awaresystems.be/imaging/tiff/tifftags/yresolution.html) has been reported [here](https://github.com/python-pillow/Pillow/issues/4537#issuecomment-612008156) and [here](https://github.com/python-pillow/Pillow/issues/4238#issuecomment-624300805), that the tags …
> Use ImageFileDirectory_v2 in Image.Exif

- .pre-commit-config.yaml
This prevents owners of repos used in pre-commit from force updating an
existing tag to contain malicious code.
The changes here were created simply by running
pre-commit autoupdate --freeze
> Use --freeze feature of pre-commit autoupdate

- docs/reference/ImageGrab.rst
- src/PIL/Image.py
- src/PIL/ImageCms.py
- src/PIL/ImageWin.py
All changes should be obvious from the diff, except for the ImageGrab change, which fixes the formatting from this screenshot.
> Improved formatting

- src/PIL/ImageQt.py
In ImageQt, there is a 'workaround for earlier versions'. It's been there since the fork, so it's not clear what it's referring to.
However, Qt 5 was released in 2012, after the fork, and we've dropped support for earlier Qt. So whatever these earlier versions are, they are no longer in use.
> Removed ImageQt workaround for earlier versions

- src/PIL/PyAccess.py
Current docs are missing due to ImportError for cffi: https://pillow.readthedocs.io/en/stable/reference/PyAccess.html?highlight=pyaccess#pyaccess-class
```
WARNING: autodoc: failed to import class 'PyAccess.PyAccess' from module 'PIL'; the following exception was raised:
No module named 'cffi'
```
---
This PR fixes the docs using `deferred_error`: https://pillow--4694.org.readthedocs.build/en/4694/reference/PyAccess.html#PIL.PyAccess.PyAccess
> Fix PyAccess docs using deferred_error

- docs/reference/ImageGrab.rst
- docs/reference/features.rst
- docs/reference/index.rst
- src/PIL/Image.py
- src/PIL/ImageFont.py
- src/PIL/features.py
This PR adds [documentation for the features module](https://pillow--4688.org.readthedocs.build/en/4688/reference/features.html). The only other reference to it before was in the [5.4.0 release docs](https://pillow.readthedocs.io/en/stable/releasenotes/5.4.0.html?highlight=features#check-for-libjpeg-turbo).
> Add docs for features module

- Tests/test_imageshow.py
- src/PIL/ImageShow.py
Suggested by https://github.com/python-pillow/Pillow/issues/4643#issuecomment-645868757
If you set `order` to zero when registering an ImageShow viewer, like so, `ImageShow.register(viewer, order=0)`, the viewer is silently ignored.
This PR changes that to treat it as a negative number instead, inserting it at the beginning of the list of viewers.
> Do not ignore viewer if ImageShow.register order is zero

- .github/workflows/test-windows.yml
Before: https://github.com/python-pillow/Pillow/runs/771448368#step:22:1806
```
SKIPPED [4] d:\a\Pillow\Pillow\Tests\test_imagetk.py:29: TCL Error: Can't find a usable init.tcl in the following directories: 
C:/hostedtoolcache/windows/PyPy/3.6.9/x86/lib_pypy/lib/tcl8.5 C:/hostedtoolcache/windows/PyPy/3.6.9/lib/tcl8.5 C:/hostedtoolcache/windows/PyPy/lib/tcl8.5 C:/hostedtoolcache/windows/PyPy/3.6.9/library C:/hostedtoolcache/windows/PyPy/library C:/hostedtoolcache/windows/PyPy/tcl8.5.2/library C:/hostedtoolcache/windows/tcl8.5.2/library
```
After: https://github.com/nulano/Pillow/runs/774933672?check_suite_focus=true#step:23:1395
```
Tests/test_imagetk.py::test_kw PASSED                                    [ 93%]
Tests/test_imagetk.py::test_photoimage PASSED                            [ 93%] …
```
> Fix TCL in Windows PyPy tests

- Tests/test_file_webp.py
- src/PIL/WebPImagePlugin.py
- src/_webp.c
Resolves #4042
The issue reports that a `method` argument is documented for saving in WebP, but it has no effect for single frame images. This PR adds that feature.
Uses #1263 as a starting point, but really uses more of the [existing Pillow Webp code](https://github.com/python-pillow/Pillow/blob/0ee089be8f495dce1f1fd682d279419595364206/src/_webp.c#L203).
See https://developers.google.com/speed/webp/docs/api#advanced_encoding_api for documentation outlining most of this.
> Added method argument to single frame WebP saving

- src/libImaging/Jpeg.h
- src/libImaging/Jpeg2KEncode.c
- src/libImaging/QuantPngQuant.c
- src/libImaging/QuantPngQuant.h
* JpegEncode.c [before](https://travis-ci.org/github/python-pillow/Pillow/jobs/673981863#L2357-L2361) and [after](https://travis-ci.org/github/python-pillow/Pillow/jobs/674229403#L2275)
* Jpeg2KEncode.c [before](https://travis-ci.org/github/python-pillow/Pillow/jobs/673981863#L2432-L2440) and [after](https://travis-ci.org/github/python-pillow/Pillow/jobs/674229403#L2346)
* QuantPngQuant.c [before](https://travis-ci.org/github/python-pillow/Pillow/jobs/673981863#L2442-L2449) and [after](https://travis-ci.org/github/python-pillow/Pillow/jobs/674229403#L2348)
> Fixed comparison warnings

- Tests/test_file_libtiff.py
- Tests/test_file_tiff_metadata.py
- src/PIL/TiffImagePlugin.py
- src/encode.c
Resolves #3677
This PR has two changes.
Firstly, Pillow currently treats BYTE tags of count N as if they might have N strings. I do not believe this should be the case. To look at count values for character-related tags, [the BYTE tag GPSAltitudeRef](https://www.awaresystems.be/imaging/tiff/tifftags/privateifd/gps/gpsaltituderef.html) has count 1 for 1 character, [the ASCII tag GPSDateStamp](https://www.awaresystems.be/imaging/tiff/tifftags/privateifd/gps/gpsdatestamp.html) has count 11 for 11 characters, and [the UNDEFINED tag Flashpix Version](https://www.awaresystems.be/imaging/tiff/tifftags/privateifd/exif/flashpixversion.html) has count 4 for 4 characters. So, I think BYTE tags of count N have N characters, and are only single strings.
Secondly, this PR changes the following current …
> Writing TIFF tags: improved BYTE, added UNDEFINED

- Tests/test_file_libtiff.py
- src/PIL/TiffImagePlugin.py
Resolves #3786
In this issue, the user opens an image with 'tiff_jpeg' compression, and then tries to save it. libtiff throws an error though - 'OJPEGSetupEncode: OJPEG encoding not supported; use new-style JPEG compression instead.'
For a longer explanation of this error message, see the text at the beginning of the libtiff file that contains the error - https://gitlab.com/libtiff/libtiff/-/blob/master/libtiff/tif_ojpeg.c
According to https://www.awaresystems.be/imaging/tiff/tifftags/compression.html - 6 is old-style JPEG (Pillow [tiff_jpeg](https://github.com/python-pillow/Pillow/blob/4634eafe3c695a014267eefdce830b4a825beed7/src/PIL/TiffImagePlugin.py#L114) compression), 7 is new-style JPEG (Pillow [jpeg](https://github.com/python-pillow/Pillow/blob/4634eafe3c695a014267eefdce830b4a825bee …
> Replaced tiff_jpeg with jpeg compression when saving TIFF images

- Tests/test_file_jpeg.py
- src/libImaging/JpegEncode.c
Resolves #3328
Pillow has some C code that sets `density_unit`, `X_density` and `Y_density`. However, [libjpeg](https://github.com/LuaDist/libjpeg/blob/master/libjpeg.txt) states that
> UINT8 density_unit
> UINT16 X_density
> UINT16 Y_density
> 	The resolution information to be written into the JFIF marker;
> 	not used otherwise.
So this code should tell libjpeg to [write the JFIF marker](https://github.com/LuaDist/libjpeg/blob/6c0fcb8ddee365e7abc4d332662b06900612e923/jcmarker.c#L528).
> Write JFIF header when saving JPEG

- src/libImaging/QuantOctree.c
Resolves #3031 
Mentioned in that issue is the undefined behaviour of dividing by zero - this has already been fixed by #3388.
Left is the undefined behaviour of assigning an int to an unsigned char. So this PR uses `CLIP8` to resolve that, in much the same way that #3107 resolved #3030.
> Corrected undefined behaviour

- Tests/test_file_tiff_metadata.py
- src/PIL/TiffImagePlugin.py
Resolves #4360
If STRIPBYTECOUNTS is specified to be SHORT, a valid type for the tag [according to documentation](https://www.awaresystems.be/imaging/tiff/tifftags/stripbytecounts.html), but Pillow calculates a STRIPBYTECOUNTS value too large for SHORT when saving, then an error is thrown.
This PR fixes the situation by changing STRIPBYTECOUNTS to LONG if necessary when saving.
> Change STRIPBYTECOUNTS to LONG if necessary when saving

- src/PIL/PdfParser.py
I recently went over [Matplotlib](https://github.com/matplotlib/matplotlib/pull/16706), [Pandas](https://github.com/pandas-dev/pandas/pull/32322) and [NumPy](https://github.com/numpy/numpy/pull/15731), fixing a small mistake in the way that Python 3's exception chaining is used. If you're interested, I can do it here too. I've done it on just one file right now. 
The mistake is this: In some parts of the code, an exception is being caught and replaced with a more user-friendly error. In these cases the syntax `raise new_error from old_error` needs to be used.
Python 3's exception chaining means it shows not only the traceback of the current exception, but that of the original exception (and possibly more.) This is regardless of `raise from`. The usage of `raise from` tells Python to put a …
> Fix exception causes in PdfParser.py

- .github/workflows/macos-install.sh
GHA macOS PyPy is currently failing on master. This fixes it by installing NumPy with OpenBLAS.
> Install NumPy with OpenBLAS

- docs/deprecations.rst
- docs/releasenotes/7.2.0.rst
Added release notes for #4605 and #4536
> Updated release notes

- src/PIL/Image.py
It's not clear why there is a need for users to do this. They should be able to change behaviour using `ImageShow.register`. This PR doesn't change any functionality, it just stops pointing users in that direction.
> Removed comments suggesting users override functions

- Tests/test_imagegrab.py
- src/PIL/ImageGrab.py
- src/display.c
Helps #4611
Adds support for the following clipboard formats on Windows in addition to the already supported `CF_DIB`:
* `CF_DIBV5`
* `'PNG'` used by e.g. MS Word 2016 and Paint.NET,
* `CF_HDROP` used by most browsers (except Chrome), file explorers, etc.
*Support for `CF_HDROP` was already hinted at in the documentation, but there was merely a FIXME in place of the code.*
Used format is selected out of available formats based on the priority specified by the clipboard owner.
While I could see the argument that CF_HDROP is more complicated and should therefore only be a fallback, based on my testing, it is almost always the preferred format, and preserves the original image data (e.g. transparency, tags, ...), unlike bitmaps.
> Improve ImageGrab.grabclipboard() on Windows

- Tests/test_features.py
- Tests/test_file_icns.py
- Tests/test_file_jpeg.py
- Tests/test_file_jpeg2k.py
- Tests/test_file_libtiff.py
- Tests/test_file_png.py
- Tests/test_file_webp.py
- Tests/test_imagecms.py
- Tests/test_imagefont.py
- docs/reference/features.rst
- src/PIL/IcnsImagePlugin.py
- src/PIL/features.py
- src/_imaging.c
- src/_imagingcms.c
- src/_imagingft.c
- src/_webp.c
- src/libImaging/QuantPngQuant.c
- src/libImaging/ZipEncode.c
Continuation of #4688.
Helps issues such as #4686, #3833.
* Add access to library version numbers to public API in `features` module. Update tests to use this instead of private APIs.
* Use run-time version numbers where available; libjpeg apparently makes it [unnecessarily hard to retrieve the version number](https://stackoverflow.com/a/19116612/1648883).
* Add version numbers to `pilinfo`. Example from https://github.com/nulano/Pillow/runs/772850897?check_suite_focus=true:
```
--------------------------------------------------------------------
--- PIL CORE support ok, compiled for version 7.2.0.dev0
--- TKINTER support ok
--- FREETYPE2 support ok, loaded version 2.8.1
--- LITTLECMS2 support ok, loaded version 20.90
--- WEBP support ok, loaded …
```
> Add library version numbers to public API

- src/PIL/BmpImagePlugin.py
- src/PIL/DcxImagePlugin.py
- src/PIL/FliImagePlugin.py
- src/PIL/GifImagePlugin.py
- src/PIL/JpegImagePlugin.py
- src/PIL/MspImagePlugin.py
- src/PIL/PixarImagePlugin.py
- src/PIL/PngImagePlugin.py
- src/PIL/PsdImagePlugin.py
- src/PIL/SgiImagePlugin.py
- src/PIL/SunImagePlugin.py
`_open` sometimes contains the same check as `_accept`. This PR changes some plugins to call `_accept` directly, instead of just duplicating the code.
This is already done by some other plugins. For example,
https://github.com/python-pillow/Pillow/blob/2456601e6b15849c5a4a72548a73d29647771a37/src/PIL/CurImagePlugin.py#L38-L45
> Call _accept instead of duplicating code

- Tests/test_image.py
- docs/deprecations.rst
- src/PIL/Image.py
For #4643 
* Deprecate the `Image.show(command="...")` parameter and remove its documentation, because it hasn't been implemented since the PIL fork, and implementing it is non-trivial.
> Deprecate Image.show(command="...")

- Tests/test_file_libtiff.py
- src/PIL/TiffImagePlugin.py
- src/PIL/TiffTags.py
- src/encode.c
Taking a part of #2288
At the moment, `COLORMAP` is the TiffImagePlugin `blocklist`, tags that are blocked when saving.
https://github.com/python-pillow/Pillow/blob/a78de17346da722bc015cf35af0189adcdc0e2b9/src/PIL/TiffImagePlugin.py#L1520-L1524
This PR adds that validation, throwing an error if it does not have length 768.
The tag is treated as special when writing because libtiff handles it specially - https://gitlab.com/libtiff/libtiff/-/blob/master/libtiff/tif_dir.c#L374-379
> Allow libtiff to write COLORMAP tag

- docs/handbook/image-file-formats.rst
- docs/reference/Image.rst
- src/PIL/ImageDraw2.py
Splitting up #4715.
Add docs for functions omitted from `Image`, and sort them. There are still a few more missing functions, but most of them seem to be quite obscure.
Also fix a typo in `ImageDraw2` docs.
<details><summary>Fixes 15 nitpicky warnings: (click to expand)</summary><p>
```
-c:\git\pillow\src\PIL\ImageDraw2.py:docstring of PIL.ImageDraw2.Draw.chord:1: WARNING: py:meth reference target not found: PIL.ImageDraw2.ImageDraw.arc
-C:\Git\Pillow\docs\handbook\image-file-formats.rst:11: WARNING: py:meth reference target not found: PIL.Image.Image.open
-C:\Git\Pillow\docs\handbook\image-file-formats.rst:28: WARNING: py:meth reference target not found: PIL.Image.Image.open
-C:\Git\Pillow\docs\handbook\image-file-formats.rst:77: WARNING: py:meth reference target not found: …
```
> Fix documentation references: omitted Image functions

- docs/reference/ImageCms.rst
- docs/reference/ImageFile.rst
- src/PIL/ImageCms.py
- src/PIL/ImageFile.py
Splitting up #4715.
Add autodocs for missing types `ImageFile`, `StubImageFile`, and fix references to `PyCMSError`. Also replace code references to `PyCMSError` with actual references.
I had to remove the `:noindex:` in `ImageCMS.rst` to let sphinx find the missing types. Unfortunately this conflicts with the `:module:` at the top of the file, and removing `:module:` would cause a (mildly) confusing scroll target, so I replaced `automodule` with several `autofunction`s.
<details><summary>Fixes 55 nitpicky warnings: (click to expand)</summary><p>
```
-c:\git\pillow\src\PIL\GdImageFile.py:docstring of PIL.GdImageFile.GdImageFile:1: WARNING: py:class reference target not found: PIL.ImageFile.ImageFile
-C:\Git\Pillow\docs\handbook\image-file-formats.rst:564: WARNING: py:meth reference target …
```
> Fix documentation references: missing types

- docs/reference/Image.rst
- docs/reference/ImageCms.rst
- docs/reference/ImageMath.rst
Splitting up #4715.
`:type:` should be directly following an attribute/data to give a cleaner (modern) output. It automatically treats the value as a `:py:class` reference. I used `Optional` from builtin `typing` to fix the resulting reference errors where applicable.
I added `:noindex:` to `ImageMath` functions as some (`int` and `float`) were being picked up by as the target instead of builtin Python types. There were 3 references to them that were already broken, I'm not sure what is the best way to fix these.
Also add `Image.` prefix to Image attributes to fix several more references.
<details><summary>Fixes 69 nitpicky warnings: (click to expand)</summary><p>
```
-C:\Git\Pillow\docs\handbook\concepts.rst:66: WARNING: py:attr reference target not found: PIL.Image.Image.mode …
```
> Fix documentation references: :type:

- docs/handbook/concepts.rst
- docs/reference/Image.rst
- docs/releasenotes/2.7.0.rst
- docs/releasenotes/4.2.0.rst
- src/PIL/Image.py
Splitting up #4715.
Add Image constants to docs. Most have a simple note for now, can be expanded if necessary. Filters are linked to concepts as before, I just listed them in `Image` for completeness.
<details><summary>Fixes 81 nitpicky warnings: (click to expand)</summary><p>
```
-c:\git\pillow\src\PIL\Image.py:docstring of PIL.Image.Image.resize:5: WARNING: py:attr reference target not found: PIL.Image.NEAREST
-c:\git\pillow\src\PIL\Image.py:docstring of PIL.Image.Image.resize:5: WARNING: py:attr reference target not found: PIL.Image.BOX
-c:\git\pillow\src\PIL\Image.py:docstring of PIL.Image.Image.resize:5: WARNING: py:attr reference target not found: PIL.Image.BILINEAR
-c:\git\pillow\src\PIL\Image.py:docstring of PIL.Image.Image.resize:5: WARNING: py:attr reference target not found: …
```
> Fix documentation references: Image constants

- src/PIL/PngImagePlugin.py
* This looks like a bug: should assign, rather than a comparison that has no effect
* I don't have a test, but they pass before and after
* https://github.com/python-pillow/Pillow/issues/4725 isn't fixed by this 
cc @pmrowla
> APNG: Fix setting disposal

- Tests/test_file_icns.py
- src/PIL/IcnsImagePlugin.py
Resolves #4732
The scenario from the issue is
```python
fp = io.BytesIO()
im.save(fp, format="ICNS")
```
It fails for ICNS due the use of the `iconutil` command line tool, rather than the usual writing to `fp`. This resolves it by creating a temporary file.
> Fixed ICNS file pointer saving

- src/PIL/ImageShow.py
Resolves #4729
As explained in https://github.com/python-pillow/Pillow/issues/4729#issuecomment-650178611, PNG can save I;16 images. Since Pillow has flawed I;16 conversion, avoiding conversion in this case fixes incorrect displaying of the image.
> Do not convert I;16 image when showing PNG

- src/_imagingft.c
This causes compilation to (correctly) fail on Clang because this isn't the correct assignment type.
* Swaps dlsym/GetProcAddress cast for raqm_version_string from t_raqm_version_atleast to t_raqm_version_string.
> Use correct function type for raqm_version_string

- RELEASING.md
Adding the step to run `update-pillow-tag.sh` in docker-images to the RELEASING checklist.
> Update Docker Images repository as part of releases

- docs/handbook/writing-your-own-file-decoder.rst
- src/PIL/JpegImagePlugin.py
A few changes to `writing-your-own-file-decoder.rst`, and standardise on the most-common "plugin" over "plug-in".
```console
$ git grep plugin | wc -l
106
$ git grep plug-in | wc -l
7
```
There's a few places that mention `.c` files:
```console
$ grep "\.c" docs/handbook/writing-your-own-file-decoder.rst
complete list, see the table in the :py:mod:`Unpack.c` module. The following
and PackBits. For details, see the :file:`decode.c` source file, and the
``PyImaging_[Decodername]DecoderNew`` and defined in ``decode.c``. The
from within the ``_imaging.c`` file in the codecs section of the
decoder may use the functions in ``codec_fd.c`` to read directly
```
Is there a good way to link to those files on GitHub and retain `code formatting`?
> Docs: Use 'plugin', fix formatting and typos

- src/PIL/TiffImagePlugin.py
Some environments have strict mode to catch potential str<>bytes error. This is triggered by this line:
```
TiffImagePlugin.py3", line 996, in _open
logger.debug("- ifh: {}".format(ifh))
BytesWarning: str() on a bytes instance
```
> Minor fix: remove str(bytes) call

- Tests/test_imageops.py
- src/PIL/ImageOps.py
Fixes #4731 
Added the ability to change the hi and low cutoff separately without causing backwards comparability issue
The user should be allowed to change the values of the left and right side of the histogram separately so:
* added a tuple to control the high and low values separately (cutoff[0] is for low end and cutoff[1] is for hi end)
* to ensure backwards comparability I added a way to turn integer to a tuple so the program works both ways
> Allow ImageOps.autocontrast to specify low and high cutoffs separately

- src/libImaging/Imaging.h
There's no other reference to these in the codebase, except this one in the changelog:
```
(0.3a2 released)
...
+ Removed bogus references to the crack coder (ImagingCrack).
```
> Remove unused externs from Imaging.h

- .github/workflows/test.yml
- docs/conf.py
- docs/deprecations.rst
- requirements.txt
* Use the `sphinx_removed_in` extension for the `.. versionremoved::` directive
* Re-document deprecated versions of removals, it could be useful to know
> Use sphinx_removed_in and re-document deprecated versions of removals

- CHANGES.rst
- docs/handbook/tutorial.rst
- docs/reference/PSDraw.rst
- src/PIL/EpsImagePlugin.py
- src/PIL/PSDraw.py
Didn't bother changing this one, to prevent surprising API changes:
```
src/PIL/EpsImagePlugin.py:    format_description = "Encapsulated Postscript"
```
> Fix PostScript typos

- docs/conf.py
- docs/handbook/image-file-formats.rst
- docs/handbook/writing-your-own-file-decoder.rst
- docs/reference/Image.rst
- docs/reference/ImageDraw.rst
- docs/reference/ImageGrab.rst
- docs/releasenotes/5.3.0.rst
- docs/releasenotes/7.0.0.rst
- docs/releasenotes/7.1.0.rst
- src/PIL/PSDraw.py
* Add `intersphinx_mapping` for standard library. A good place to check it out is the [attribute types in `ImageCms.CmsProfile`](https://pillow--4774.org.readthedocs.build/en/4774/reference/ImageCms.html#cmsprofile).
* Fix typo in PSDraw
* Use cross-reference instead of code for `None`. I used a grep to replace all instances in rst files, but I can see there are still a lot of references which are neither code or cross-reference. I also did not update docstrings due to line length limit. While linking to the docs for None might be a bit too much, it would be good to decide on a consistent standard to use for all standard library types. There are likely other types that I missed that should be replaced if this is the agreed-upon style. …
> Fix documentation references: standard library

- .travis.yml
We should figure out https://github.com/python-pillow/Pillow/issues/4769, but shall we not let pre-releases fail PRs?
* https://docs.travis-ci.com/user/customizing-the-build#jobs-that-are-allowed-to-fail
(For some visibility we could use a conditional: so PRs can pass but `master` would still fail?)
* https://docs.travis-ci.com/user/customizing-the-build#conditionally-allowing-jobs-to-fail
> Travis CI: Allow 3.9-dev to fail

- src/PIL/ImageFilter.py
nit - typo fix:
`the` -> `The`
[ci skip]
> Nit typo fix

- docs/PIL.rst
- docs/handbook/image-file-formats.rst
- docs/reference/plugins.rst
- src/PIL/PngImagePlugin.py
* Document PNG constants
* Fix references in headings for `iTXt` and `PngInfo` classes
<details><summary>Fixes 9 nitpicky warnings: (click to expand)</summary><p>
```diff
-C:\Git\Pillow\docs\PIL.rst:96: WARNING: py:class reference target not found: PngImagePlugin.iTXt
-C:\Git\Pillow\docs\PIL.rst:110: WARNING: py:class reference target not found: PngImagePlugin.PngInfo
-C:\Git\Pillow\docs\handbook\image-file-formats.rst:649: WARNING: py:data reference target not found: PIL.PngImagePlugin.APNG_DISPOSE_OP_NONE
-C:\Git\Pillow\docs\handbook\image-file-formats.rst:651: WARNING: py:data reference target not found: PIL.PngImagePlugin.APNG_DISPOSE_OP_BACKGROUND
-C:\Git\Pillow\docs\handbook\image-file-formats.rst:654: WARNING: py:data reference target not …
```
> Fix documentation references: PngImagePlugin

- docs/handbook/image-file-formats.rst
- docs/handbook/tutorial.rst
- docs/handbook/writing-your-own-file-decoder.rst
- docs/porting.rst
- docs/reference/Image.rst
- docs/reference/ImageFilter.rst
- docs/reference/ImageFont.rst
- docs/reference/ImageQt.rst
- docs/reference/TiffTags.rst
- docs/reference/internal_modules.rst
- docs/releasenotes/4.1.0.rst
- docs/releasenotes/4.2.0.rst
- docs/releasenotes/4.3.0.rst
- src/PIL/Image.py
- src/PIL/ImageChops.py
* Fix several typos related to references
* Use code formatting instead of cross-references for removed methods (e.g. `ImageDraw.setink`) and local variable methods (e.g. `file.read`)
* Document `Image.ImagePointHandler`, `Image.ImageTransformHandler`, `Image.Exif`, `ImageFilter.Filter`, `ImageFilter.MultibandFilter`, `TiffTags.LIBTIFF_CORE`
* Add a one-line description for `_imaging` and `Image.core`
Adds 1 nitpicky warning fixed by #4774:
```diff
+c:\git\pillow\src\PIL\Image.py:docstring of PIL.Image.Exif:1: WARNING: py:class reference target not found: collections.abc.MutableMapping
```
<details><summary>Fixes 34 nitpicky warnings: (click to expand)</summary><p>
```diff
-c:\git\pillow\src\PIL\ImageTransform.py:docstring of …
```
> Fix some documentation references

- docs/conf.py
- docs/releasenotes/4.2.0.rst
Enable nitpicky warnings in the config to find them earlier on CIs.
This will fail until #4739, ~#4771, #4773, #4774~ are merged.
I added the warnings mentioned in #4775 to `nitpick_ignore` for now until they are resolved to allow the build to pass (once the above PRs are merged). I will remove relevant lines if someone resolves them before this is merged.
> Docs: Enable nitpicky warnings

- Tests/test_imagecms.py
- docs/deprecations.rst
- docs/reference/ImageCms.rst
- src/_imagingcms.c
* These have been deprecated since Pillow 3.2.0 (April 2016)
* and given `DeprecationWarning` since 6.0.0 (April 2019)
* and can be removed in 8.0.0 (October 2020)
> Remove ImageCms.CmsProfile attributes deprecated since 3.2.0

- docs/conf.py
- docs/handbook/image-file-formats.rst
- docs/handbook/writing-your-own-file-decoder.rst
- docs/reference/ImageMath.rst
- src/PIL/ImageWin.py
Suggestions for #4775 
- Corrected reference
- Replaced 'PIL.Image.Image.convert2byte' with 'PIL.SpiderImagePlugin.SpiderImageFile.convert2byte'
- Removed domain references from image expressions
- 'convert()', 'float()' and 'int()' are not Python methods in this context
- Removed domain references when referring to hypothetical code
- In the context of writing your own file decoder, `_open` and `tile` are only hypothetical.
- Removed domain reference for external method
- `CDC.GetHandleAttrib()` is in PythonWin, not Pillow
> Updated references

- winbuild/build_prepare.py
For #4746 
* Use f-strings in winbuild
The use of format strings in the winbuild script is somewhat complicated and I doubt an automated script could upgrade all uses properly, so I did it manually. Do not merge before #4746.
> Use f-strings in winbuild

- docs/releasenotes/index.rst
Resolves #4750 
This is not intended as a change to our current release behaviour, just a documentation of it.
> Added description of release cycle

- .github/workflows/lint.yml
- .github/workflows/test-windows.yml
- .github/workflows/test.yml
Simplify some GitHub Actions config:
* Don't need a matrix of one version for linting
* Since pip 20.1, we can use `pip cache dir` to combine macOS/Ubuntu cache config ([example](https://github.com/actions/cache/blob/master/examples.md#using-pip-to-get-cache-location))
* Also update some actions to v2
> Simplify GHA config

- src/PIL/_version.py
For https://github.com/python-pillow/Pillow/issues/4764
* A major bump because the next release will drop EOL Python 3.5 (#4746).
> 8.0.0.dev0 version bump

- Tests/test_file_jpeg2k.py
- Tests/test_file_png.py
- Tests/test_file_webp_animated.py
* remove `on_ci` checks from endianess related `xfail` decorators. It doesn't matter whether tests are running on CI or not for those tests to fail (we are running those tests without CI).
> Fix expected failures on big endian systems without CI

- Tests/test_file_psd.py
- src/PIL/PsdImagePlugin.py
Fixes #4787
* Register "image/vnd.adobe.photoshop" as PsdImageFile MIME type
> Add MIME type to PsdImagePlugin

- .github/workflows/test-windows.yml
- .github/workflows/test.yml
GHA now provides Python 3.9 beta 4 ~if the full version number `3.9.0-beta.4` is specified~, add it to the matrix.
(https://github.com/actions/setup-python/issues/20#issuecomment-660026867)
~Or perhaps this can wait until beta 5 is available (possibly later this week?).~
Edit: Actually, specifying `3.9-dev` also seems to work fine.
> GHA: Test Python 3.9-dev

- Tests/test_imagefont.py
For https://github.com/python-pillow/Pillow/issues/4796.
* distutils will eventually be removed from the stdlib
* Replace `distutils.version` with `packaging.version.parse`
* > `packaging.version.parse` is a third-party utility but is used by [setuptools][4] (so you probably already have it installed) and is conformant to the current [PEP 440][5]; it will return a `packaging.version.Version` if the version is compliant and a `packaging.version.LegacyVersion` if not. The latter will always sort before valid versions.
* https://stackoverflow.com/a/11887885/724176
[4]: https://pypi.python.org/pypi/setuptools
[5]: https://www.python.org/dev/peps/pep-0440/
> Replace distutils.version with packaging.version.parse

- Tests/test_image.py
- Tests/test_image_frombytes.py
- docs/deprecations.rst
- docs/reference/Image.rst
- src/PIL/Image.py
Our [current approach](https://pillow.readthedocs.io/en/latest/deprecations.html) has been to deprecate for at least a year, and then remove in the next major version. I think this has been working fine (except for `PILLOW_VERSION` which didn't raise deprecation warnings; so we reinstated it with warnings).
`Image.tostring` and `fromstring` were deprecated in 2013, and `Image.offset` in 2001. They've raised either a `DeprecationWarning`, `Exception` or `NotImplementedError` for a long time. Let's remove them.
---
`Image.tostring`, `im.tostring` and `im.fromstring` date back to at least PIL 1.1.1 (Oct 2000), probably earlier.
In Pillow 2.0.0 (March 2013), when adding support for Python 3, `tobytes` was added, and `tostring` was deprecated, raising `DeprecationWarning: tostring() is …
> Remove long-deprecated Image.py functions

- setup.py
For #4796.
`setup.py` does:
```python
from distutils import sysconfig
prefix = sysconfig.get_config_var("prefix")
```
https://github.com/python/cpython/blob/master/Lib/distutils/sysconfig.py
`get_config_var("prefix")` calls `get_config_vars().get("prefix")`, which initialised it as 
`_config_vars['prefix'] = PREFIX`, where `PREFIX = os.path.normpath(sys.prefix)`
There's also a `sysconfig` module in the stdlib: 
* https://docs.python.org/3/library/sysconfig.html
This is almost identical to the one in `distutils`:
`get_config_var("prefix")` calls `get_config_vars().get("prefix")`, which initialised it as 
`_CONFIG_VARS['prefix'] = _PREFIX = _PREFIX`, where `PREFIX = os.path.normpath(sys.prefix)`
https://github.com/python/cpython/blob/master/Lib/sysconfig.py
I tried our `setup.py` with: …
> setup.py: Get prefix directly from sys instead of distutils

- setup.py
Helps #4796
In setup.py, there is
```python
PLATFORM_MINGW = "mingw" in ccompiler.get_default_compiler()
```
Looking at `ccompiler.get_default_compiler()` on MinGW -
```python
def get_default_compiler(osname=None, platform=None):
...
if get_platform().startswith('mingw'):
return 'mingw32'
```
```python
def get_platform():
if os.name == 'nt':
TARGET_TO_PLAT = {
'x86' : 'win32',
'x64' : 'win-amd64',
'arm' : 'win-arm32',
}
return TARGET_TO_PLAT.get(os.environ.get('VSCMD_ARG_TGT_ARCH')) or get_host_platform()
else:
return get_host_platform()
```
```python
def get_host_platform():
...
if os.name == 'nt':
if 'GCC' in sys.version:
return 'mingw'
```
Note that I find the code on MinGW slightly different to the one on my machine - mine does not include the MinGW lines.
So then the setup.py line …
> Removed distutils from MinGW detection

- Tests/test_image_access.py
For #4796, similar to #4809
Replaces
```python
from distutils import sysconfig
```
with
```python
import sysconfig
```
and
```python
sysconfig.get_python_inc()
```
with
```python
sysconfig.get_config_var("INCLUDEPY")
```
Also removes a `print` statement.
However, this test is skipped on CIs, so this PR passing is not good evidence that my changes are correct. Instead, I created https://github.com/radarhere/Pillow/commit/73f8d40df22f1203c01f9103c978835234d9c36d to check that the values with and without distutils are the same - passing on [AppVeyor](https://ci.appveyor.com/project/radarhere/pillow/builds/34296603) and [MSYS2 MINGW32](https://github.com/radarhere/Pillow/runs/909551283).
> Replaced distutils in test_image_access.py

- winbuild/build_prepare.py
The default path is currently ignored with the [`build/` line](https://github.com/python-pillow/Pillow/blob/b4e7202dcb7235642f6e6a050c9485070ae6ea4f/.gitignore#L13), but this would be removed by #3062. Additionally, the directory is configurable with a parameter.
Adding a `*` gitignore to the generated build directory prevents it from being committed by accident in these cases.
> Add gitignore to winbuild build directory

- docs/handbook/writing-your-own-file-decoder.rst
- Combine two `register_extension` calls into `register_extensions`
- Added an example importing SpamImagePlugin, to help #4818
> Improved example plugin documentation

- .github/workflows/test-windows.yml
Removes 32-bit MinGW in light of https://www.msys2.org/news/#2020-05-17-32-bit-msys2-no-longer-actively-supported
> Removed 32-bit MinGW job

- .ci/install.sh
- .github/workflows/macos-install.sh
- .github/workflows/test-windows.yml
- .github/workflows/test.yml
The setuptools fix https://github.com/pypa/setuptools/pull/2249 for python-pillow/Pillow#4769  has been released in [setuptools v49.1.3](https://github.com/pypa/setuptools/releases/tag/v49.1.3), so we can require that version or newer.
Created as draft as there are further build problems from new changes in setuptools, will add comments.
> 3.9-dev: Upgrade setuptools

- docs/handbook/image-file-formats.rst
- docs/handbook/writing-your-own-file-decoder.rst
- docs/reference/ImageChops.rst
- docs/reference/ImageFile.rst
- docs/reference/ImageFont.rst
- docs/reference/ImagePath.rst
- src/PIL/Image.py
- src/PIL/ImageChops.py
- src/PIL/ImageCms.py
- src/PIL/ImageFile.py
- src/PIL/ImageFilter.py
- src/PIL/ImageFont.py
- src/PIL/ImageOps.py
- src/PIL/ImageTk.py
- src/PIL/ImageWin.py
- src/PIL/JpegPresets.py
- src/PIL/PSDraw.py
- src/PIL/TiffImagePlugin.py
Followup to https://github.com/python-pillow/Pillow/pull/4774#discussion_r452840274
Replace instances of `**code**` with ``` ``code`` ```, and fix various code formatting related typos.
Document `ImageFile.LOAD_TRUNCATED_IMAGES`, `ImageFile.ERRORS`, `ImageFileDirectory_v1.tagtypes` and `ImageFont.LAYOUT_*` which are now linked to.
> Docs: Use code formatting instead of emphasis where applicable

- winbuild/build_prepare.py
Fixes error from #4857:
> had to modify winbuild\build\lcms2-2.11\Projects\VC2017\lcms2_static\lcms2_static.vcxproj to point to the installed windows SDK version (10.0.19041.0) for it to compile, but otherwise, everything worked fine
Also make sure all patches are actually applied to avoid this happening again.
> Fix LCMS2 patch

- RELEASING.md
Companion to https://github.com/python-pillow/pillow-wheels/pull/158
> Pillow Wheels has changed to use GitHub releases

- docs/conf.py
- docs/deprecations.rst
- docs/reference/ImageChops.rst
- docs/releasenotes/8.0.0.rst
- docs/releasenotes/index.rst
- docs/releasenotes/template.rst
* Add release notes for 8.0.0
* Add a release note template for future copy/paste, with the sections in the usual order
* Exclude the template from `make doc`, to silence a `make doc` error as it's not linked in the toctree
* Put `PIL.ImageChops.offset` as `autodoc`, as it has a good docstring
* A few other minor doc updates related to autolinking to classes, methods or functions
> Add release notes for 8.0.0 and a template

- winbuild/build.rst
Alternative to #4680, documents how to install Pillow in develop mode using the winbuild scripts.
> Add develop instructions for winbuild

- Tests/test_file_jpeg.py
- Tests/test_tiff_ifdrational.py
- src/PIL/TiffImagePlugin.py
Variation on #4813
At the moment,
```python
from PIL.TiffImagePlugin import IFDRational
print(IFDRational(2,2) == IFDRational(2, 2))  # False
```
This also causes problems in `im._getexif()`. The changes in this PR fix that.
#4813 has that fix, as well as making `IFDRational(1, 0) == IFDRational(1, 0)`. I'm not convinced of that part, since standard behaviour dictates that NaN != NaN. So this PR removes the NaN change, to try and get the less controversial part merged in at least.
> Fix IFDRational __eq__ bug

- setup.cfg
See:
https://pycodestyle.pycqa.org/en/latest/intro.html#error-codes
> In the default configuration, the checks E121, E123, E126, E133, E226,
> E241, E242, E704, W503, W504 and W505 are ignored because they are not
> rules unanimously accepted, and PEP 8 does not enforce them.
> Remove W503 from flake8 ignore list (ignored by default)

- docs/about.rst
Helps #4881
While it's unclear in that issue where to send users who are interested in the PIL commit history, there is no longer a place to create new PIL issues. So the instructions for creating new PIL issues can be removed.
> Without the Bitbucket repo, there is no place for PIL issues

- Tests/test_image_access.py
- src/_imaging.c
Fixes #4876:
* The existing code silently ignores an `OverflowError` for 8bpp images, hoping that the int will become a tuple in the next few lines.
* It also fails to check that the given parameter is a tuple before trying to unpack it, giving the less than useful message `SystemError: new style getargs format but argument is not a tuple`.
* Last but not least, passing a non-int value for non-8bpp non-float images (e.g. `I;16`) gives an even less useful message `SystemError: <method 'putpixel' of 'ImagingCore' objects> returned NULL without setting an error`.
This PR resolves all of these issues by explicitly raising a TypeError if the parameter can't be converted to an int, or a tuple for an 8bpp image.
> Raise proper TypeError in putpixel

- docs/releasenotes/8.0.0.rst
Add `ImageDraw.regular_polygon` to release notes. 
[Reference](https://github.com/python-pillow/Pillow/pull/4846#issuecomment-687366543)
> Add `ImageDraw.regular_polygon` to release notes

- docs/installation.rst
* Right now, linking to the table is really a link to "Notes":
https://pillow.readthedocs.io/en/stable/installation.html#notes
* It's important enough to deserve its own header, not just "Notes"
* I think keeping it near the top is good
* This was the only "Note" under "Notes". If we get more notes in the future, they can be back after "Warnings"
https://pillow--4905.org.readthedocs.build/en/4905/installation.html#python-support
> Docs: Give supported Python versions its own header

- Tests/test_image.py
- src/libImaging/Effects.c
Resolves #4906
https://github.com/python-pillow/Pillow/blob/9e6dabf0e51b96146e4fa53642d3f8bf4a1ca460/src/PIL/Image.py#L2505-L2507
If you supply a `distance` of zero to `im.effect_spread`, then mod zero is attempted.
https://github.com/python-pillow/Pillow/blob/9e6dabf0e51b96146e4fa53642d3f8bf4a1ca460/src/libImaging/Effects.c#L136-L137
This PR resolves that. Afterwards, a `distance` of zero simply copies the pixels. This makes sense to me - if you are spreading the pixels by a distance of zero, nothing changes.
> Fixed effect_spread bug for zero distance

- docs/handbook/concepts.rst
I misunderstood this section of the documentation the first time I read it. I hope this change will clarify how to request a mode such as from Image.new("RGBA", size).
* Add that modes are strings, as opposed to constants used like tkinter.NW
> Clarify that modes are strings, not constants

- src/PIL/Image.py
Updated the docstring of PIL.Image.thumbnail to include PIL.Image.BOX filter as a resampling option, which was not previously listed in the documentation.
> Image.thumbnail docstring: added missing filters

- Tests/test_imagecms.py
- Tests/test_imagefont.py
- src/PIL/ImageCms.py
Resolves #4897 - in the same way that #3785 resolved #3145, by loading data from a non-Unicode path on Windows into memory.
Also corrects a message in the test suite from that PR.
> Fixed loading profile with non-ASCII path on Windows

- .appveyor.yml
- .github/workflows/test-windows.yml
Also, having added the binary to pillow-depends - https://github.com/python-pillow/pillow-depends/commit/02e38f069935603a7f83b071b2281f304637d261 - there is a curl command in .appveyor.yml that is not needed.
> Updated Ghostscript to 9.53.1

- .ci/install.sh
The TravisCI Python 3.8 s390x job has started failing - https://travis-ci.org/github/python-pillow/Pillow/jobs/727457309
```
Building wheels for collected packages: black, regex, typed-ast, MarkupSafe
WARNING: Building wheel for black failed: [Errno 13] Permission denied: '/home/travis/.cache/pip/wheels/95'
WARNING: Building wheel for regex failed: [Errno 13] Permission denied: '/home/travis/.cache/pip/wheels/c1/d2'
WARNING: Building wheel for typed-ast failed: [Errno 13] Permission denied: '/home/travis/.cache/pip/wheels/90'
WARNING: Building wheel for MarkupSafe failed: [Errno 13] Permission denied: '/home/travis/.cache/pip/wheels/0c'
Failed to build black regex typed-ast MarkupSafe
ERROR: Could not build wheels for black which use PEP 517 and cannot be installed directly
```
This PR …
> chown pip wheels cache in Travis

- winbuild/build_prepare.py
I have finally figured out how to resolve the circular dependency between FreeType and HarfBuzz on Windows.
From `ftoption.h`:
> FreeType uses the HarfBuzz library to improve auto-hinting of OpenType fonts.  If available, many glyphs not directly addressable by a font's character map will be hinted also.
>
>Define this macro if you want to enable this 'feature'.
While I was not able to find a font and text combination that shows a difference, if such a combination exists, someone using these scripts locally or downloading GHA artifacts could benefit from this.
The difference to compile times is imperceptible, `_imagingft.cp37-win_amd64.pyd` is 0.6MB larger, the GHA artifact increases from 13MB to 15.2MB (17%). I don't expect this to go over the (unspecified) GHA limit, but there is an …
> Winbuild: Enable FT_CONFIG_OPTION_USE_HARFBUZZ

- README.md
- docs/index.rst
Resolves #4933
The issue reports that the [ReadTheDocs Pillow index page](https://pillow.readthedocs.io/en/latest/) and the [GitHub README](https://github.com/python-pillow/Pillow/blob/master/README.md) don't describe what Pillow is in much detail.
This PR copies the 'Overview' section from https://pillow.readthedocs.io/en/latest/handbook/overview.html
> Added overview to README and ReadTheDocs index

- .github/mergify.yml
- .github/workflows/test-docker.yml
- .github/workflows/test-windows.yml
- .github/workflows/test.yml
Fixes https://github.com/python-pillow/Pillow/issues/4900.
* Approval, label and Travis CI rules like in Like https://github.com/python-pillow/docker-images/pull/84 and https://github.com/python-pillow/pillow-wheels/pull/161
* AppVeyor rule is similar
* GHA: https://doc.mergify.io/conditions.html#github-actions
> GitHub Actions works slightly differently. To match a status check when using GitHub Action, only the job name is used.
> 
> ![image](https://user-images.githubusercontent.com/1324225/93938734-600edb80-fd32-11ea-9621-b086f304efc1.png)
>
> In the example above, it would be `A job to say hello`:
>
```yml
conditions:
- status-success=A job to say hello
```
So it's a bit more maintenance for GHA. We could rename the jobs so they don't include …
> Add Mergify config

- CHANGES.rst
Suggestion for #4881. Replaces the link to https://bitbucket.org/effbot/pil-2009-raclette/commits/all with http://svn.effbot.org/public/pil/
> Updated PIL repository link

- Tests/test_imagetk.py
For https://github.com/python-pillow/Pillow/issues/4937.
* Temporarily skip the `test_photoimage` on MinGW, it otherwise causes a segmentation fault
> Skip test_photoimage on MinGW due to segmentation fault

- Tests/test_imagetk.py
- src/Tk/tkImaging.c
Fixes #4937, reverts #4944.
No need to check for `_MSC_VER`, `_WIN64` is sufficient. Otherwise would need to check for whatever the MSYS2/MinGW64 version is as well.
No idea why this didn't crash earlier. If I had to guess, MSYS2 probably fixed or improved 64-bit support in Tk.
MSYS2 installs really slowly today, but this has fixed the issue for me: https://github.com/nulano/Pillow/runs/1206474319?check_suite_focus=true#step:6:1511
*PS: If anyone knows how to build a Python extension with debugging symbols on MSYS2/MinGW64 that can be read by either GDB or WinDbg, please let me know. This was really hard to track down without it.*
> Fix crash in ImageTk.PhotoImage on mingw64

- Tests/test_image.py
- src/PIL/Image.py
In `Image.Exif`, `_info` refers to the `ImageFileDirectory_v2` instance. `_data` is the dictionary into which `_info` data is moved when it is accessed.
At the moment in `__delitem__`, if a key hasn't been moved from `_info` to `_data`, it is deleted from `_info`, but it then goes on to try and delete the key from `_data` as well, causing a `KeyError`, despite a successful deletion.
This PR changes it to only delete the key from one or the other.
> Fixed bug in Exif __delitem__

- Tests/test_file_png.py
- docs/handbook/image-file-formats.rst
- src/PIL/PngImagePlugin.py
Resolves #4265
Private PNG chunks can now be read as
```python
im = Image.open("Tests/images/exif.png")
im.private_chunks #  [(b'orNT', b'\x01')]
```
The issue states that the spec doesn't exclude writing unknown chunks - but I find it actually describes how private chunks are to be used.
From https://www.w3.org/TR/PNG/#5Chunk-naming-conventions, if the second letter is lowercase, the chunk is private.
From https://www.w3.org/TR/PNG/#14Ordering
> When copying an unknown safe-to-copy ancillary chunk, a PNG editor shall not move the chunk from before IDAT to after IDAT or vice versa.
Pillow doesn't automatically save private chunks, but it should give users the ability to keep the ordering. So I have set it so that `private_chunks` may have a third value to specify if …
> Added reading and writing of private PNG chunks

- .github/workflows/test-windows.yml
Fixes #4949
Update the relevant lines based on https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files
> Replace deprecated add-path and set-env

- setup.py
- tox.ini
For https://github.com/python-pillow/Pillow/issues/4953.
* Add the 3.9 Trove classifier
* Update the version check for Windows in `setup.py`
* Add to `tox.ini`
> 3.9: Add Trove classifier, update setup.py version check, add to tox.ini

- Tests/test_decompression_bomb.py
- docs/releasenotes/8.0.0.rst
- src/PIL/BmpImagePlugin.py
Resolves #4939
At the moment, a very large BMP file does not raise a DecompressionBombError, but instead an OSError. This PR changes it so that the more standard DecompressionBombError is raised.
> Removed OSError in favour of DecompressionBombError for BMP

- Tests/test_image.py
- Tests/test_image_access.py
- src/_imaging.c
Resolves #4925
Normally, a user would run `Image.new('F', (100,100), 255)` and `Image.new('I', (100,100), 255)`, providing a single value for `color` for those modes.
This PR allows users to also provide that single value inside a tuple, `Image.new('F', (200,100), (255,))` and `Image.new('I', (200,100), (255,))`, which would have previously thrown an error.
> Allow tuples with one item to give single color value in getink

- .ci/install.sh
- .travis.yml
- Tests/test_imagefont.py
- src/_imagingft.c
Is it time to remove compatibility code for PyPy3<7.2.0 [released a year ago on 2019-10-14](https://morepypy.blogspot.com/2019/10/pypy-v72-released.html)? See also https://github.com/python-pillow/Pillow/pull/4145#discussion_r335667230.
* Remove compatibility code in `_imagingft.c` for PyPy3<7.2.0.
* Pin Travis to `pypy3.6-7.3.1`. The simple `pypy3` is currently pointing to the over-year-and-a-half-old 7.1.1-beta0 version, see https://docs.travis-ci.com/user/languages/python/#pypy-support. This version also needs the setuptools update.
Travis does not yet support 7.3.2 released two weeks ago, see https://travis-ci.community/t/add-pypy-7-3-2-support/10007.
* PyPy3.6-7.3.2 is now available on GHA and fixes the issue in …
> Drop support for old PyPy versions

- Makefile
- Tests/test_imagecms.py
- src/PIL/features.py
- src/_imagingcms.c
Should help avoid issues such as https://github.com/python-pillow/Pillow/issues/3835#issuecomment-507408755.
Helped find an issue from #4700 linking with LCMS<2.7.
Another one almost snuck in in #4955 (fixed in https://github.com/python-pillow/Pillow/pull/4955/commits/39ae5d62f0293738a5f697cc87a20a2c7c2bda83).
* Build Pillow on CIs with the `-Werror=implicit-function-declaration` compiler flag.
Failed build example: https://github.com/nulano/Pillow/runs/1239867650?check_suite_focus=true#step:5:40
* Fix issue introduced in #4700, restoring support for LCMS<2.7. Also fix version format string for LCMS.
> CI: Fail compilation on implicit function declaration warnings

- docs/releasenotes/8.0.0.rst
Adds release notes for the following PRs released in 8.0.0 (#4764):
* **Refactor font_getsize and font_render (#4910)**; "Other Changes" section; for issues #4553, #4569, #2293
* **Implement anchor for TrueType fonts (#4930)**; "API Changes" section; for issues #4511
* **Add `getlength` and `getbbox` functions for TrueType fonts (#4959)**; "API Additions" section; for issues #4651, #3977, #4483, #3921, #4789; brief mention in "Other Changes" section for issue #4553
* **Add support for CBDT and COLR fonts (#4955)**; "API Additions" section; for issues #3346, #891
* **Drop support for old PyPy versions (#4964)**; "Backwards Incompatible Changes" section
I also listed the related issues for easier search.
> Release notes for TrueType functions and PyPy support

- docs/releasenotes/8.0.0.rst
For https://github.com/python-pillow/Pillow/issues/4764.
Add #4523's ellipse-drawing algorithm changes to release notes.
> Add #4523 ellipse-drawing algorithm changes to release notes

- .ci/install.sh
master has started failing on [the ppc64le job](https://travis-ci.org/github/python-pillow/Pillow/jobs/735677534). This fixes it, as with #4924 for s390x.
> chown pip wheels cache on ppc64le

- src/PIL/features.py
- src/_imagingcms.c
Instead of using `pkg_resources`, which AFAICT is [part of `setuptools`](https://setuptools.readthedocs.io/en/latest/pkg_resources.html#parsing-utilities), check the LCMS version (check added in #4963) manually.
While `setuptools` is very likely to already be installed, Pillow doesn't actually require it for runtime, only compilation and testing. Additionally, the `pilinfo` function is useful for finding configuration issues and should have as few external dependencies as possible.
Since this version string is being set in the C code, it is safe to break it back into ints and perform a tuple comparison instead.
This PR also adds a comment to make sure the two checks don't get out of sync.
> Avoid using pkg_resources in PIL.features.pilinfo

- setup.py
Resolves #4973 by using ([as suggested](https://github.com/python-pillow/Pillow/issues/4973#issuecomment-707686733)) `xcrun --show-sdk-path` to add the SDK install path for library and include directories.
This same solution was also very popular in https://github.com/python-pillow/Pillow/issues/3438#issuecomment-575161585
> Added macOS SDK install path to library and include directories

- docs/conf.py
- docs/resources/css/dark.css
Dark mode is the new thing!
Not only that, it can improve accessibility, ease eye strain, and save battery power.
The `prefers-color-scheme` media query allows the theme to detect whether the user has requested a dark or light mode, often via an operating system toggle or time-of-day trigger.
* https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme
* https://web.dev/prefers-color-scheme/
* https://caniuse.com/?search=prefers-color-scheme
We're using the [Read the Docs Sphinx Theme](https://github.com/readthedocs/sphinx_rtd_theme), but it doesn't support dark theme:
* https://github.com/readthedocs/sphinx_rtd_theme/issues/224
Checking some other themes, they don't support dark mode yet:
* https://github.com/python/python-docs-theme/issues/43 (PR: …
> Docs: Add dark mode

- src/libImaging/TiffDecode.c
For #4586 
* `rows_per_strip` and `tile_length` are already checked to be less than `INT_MAX`, so it is safe to cast them to `INT32`
* add a check for `tile_width` to make sure `row_byte_size` does not overflow and make it safe to cast to `INT32`
* `x`, `y`, `tile_y`, and `strip_row` are compared with signed ints or the values above only, it is safe to change their type to `INT32`
Before: https://travis-ci.org/github/python-pillow/Pillow/jobs/704275379#L2399-L2419
After: https://travis-ci.org/github/nulano/Pillow/jobs/704337888#L2314
> Fix TiffDecode comparison warnings

- src/Tk/tkImaging.c
When using image mode "1" or "L" block.offset[3] is never initialized. In some use cases the block is passed to Tk_PhotoPutBlock (https://github.com/tcltk/tk/blob/master/generic/tkImgPhoto.c#L2752) and block.offset[3] is stored in alphaoffset which is later referenced.
This change initializes block.offset[3] to 0 when using mode "1" or "L".
> Initialize offset memory for PyImagingPhotoPut

- .github/workflows/test-windows.yml
Missed this as part of #4964.
* Revert #4702 now that the fix is released in PyPy 7.3.2.
The tests now pass without the workaround:
https://github.com/python-pillow/Pillow/pull/4984/checks?check_run_id=1262633517#step:27:1628
```
Tests/test_imagetk.py::test_kw PASSED                                    [ 94%]
Tests/test_imagetk.py::test_photoimage PASSED                            [ 94%]
Tests/test_imagetk.py::test_photoimage_blank PASSED                      [ 94%]
Tests/test_imagetk.py::test_bitmapimage PASSED                           [ 94%]
```
> GHA: Remove obsolete code for old PyPy

- docs/handbook/image-file-formats.rst
- docs/releasenotes/4.2.0.rst
Fixes linkcheck warnings:
handbook/image-file-formats.rst:563: [broken] ../installation.html:
releasenotes/4.2.0.rst:7: [broken] ../installation.html:
> Fix internal Sphinx link to installation doc

- CHANGES.rst
- docs/releasenotes/8.0.1.rst
- docs/releasenotes/index.rst
For https://github.com/python-pillow/Pillow/issues/4764.
* Release notes for the FreeType security update.
> Add release notes for 8.0.1

- .appveyor.yml
- .github/workflows/test-windows.yml
For https://github.com/python-pillow/Pillow/issues/4764#issuecomment-714547692:
> [GHA Window CI](https://github.com/python-pillow/Pillow/actions/runs/322256390) failed with "Overwrite D:\a\Pillow\Pillow\Tests\images\string_dimension.tiff (Yes/No/All)?", will be because of #4993 / [python-pillow/pillow-depends#34](https://github.com/python-pillow/pillow-depends/pull/34), so will include that too: [f886bc9](https://github.com/python-pillow/Pillow/commit/f886bc973bb972a796756d9c0a728795d203dd97).
Do not prompt to overwrite when copying test images from pillow-depends on Windows CIs so the above will not be needed for future point releases or when working on an old branch.
Successful test from my repo (does not include #4993): https://github.com/nulano/Pillow/runs/1293222859?check_suite_focus …
> CI: Replace test images from pillow-depends

- RELEASING.md
A couple of minor fixes after doing the 8.0.1 release.
---
Add an explicit `git push` after the cherry pick.
---
This bit renders fine in https://github.com/python-pillow/Pillow/blob/master/RELEASING.md:
```md
[Travis CI](https://travis-ci.org/github/python-pillow/Pillow) and
[AppVeyor](https://ci.appveyor.com/project/python-pillow/Pillow) to confirm
passing tests in `master` branch.
```
But not so well when pasted into release issues (https://github.com/python-pillow/Pillow/issues/4764):
[Travis CI](https://travis-ci.org/github/python-pillow/Pillow) and
[AppVeyor](https://ci.appveyor.com/project/python-pillow/Pillow) to confirm
passing tests in `master` branch.
So stick it all on one line:
> Releasing: Add a 'git push' to point release, adjust MD formatting

- docs/reference/ImageDraw.rst
Resolves #5005, where a user attempted to use an integer for the `text` argument of https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.ImageDraw.text
> Clarified that "text" must be a string

- .travis.yml
For #4953.
* Travis CI now has Python 3.9 final available
> Travis CI: Test on Python 3.9 final

- docs/handbook/image-file-formats.rst
Alternative to #5011.
At the moment in https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#saving-sequences, it doesn't actually describe what `save_all` does - it just mentions it.
> Describe effect of WebP save_all

- .appveyor.yml
Fixes #4953.
* AppVeyor now supports Python 3.9 final
* It requires the Visual Studio 2019 image (also works for 3.6)
* And the setuptools bump
* https://github.com/appveyor/ci/issues/3541
(It's like buses. You wait for ages and then [two](https://github.com/python-pillow/Pillow/pull/5010) come along at once.)
> AppVeyor: Test on Python 3.9 final

- .appveyor.yml
- .ci/install.sh
- .github/workflows/macos-install.sh
- .github/workflows/test-windows.yml
- .github/workflows/test.yml
- .travis.yml
- depends/diffcover-install.sh
- docs/releasenotes/6.0.0.rst
- tox.ini
- winbuild/build.rst
Another PR in the vein of #4465
> Invoke pip using Python

- .github/workflows/test-docker.yml
* Fedora 33 was released on Tuesday, 27 October 2020
* Partner to https://github.com/python-pillow/docker-images/pull/92
> Add Fedora 33

- .github/CONTRIBUTING.md
- .github/mergify.yml
- README.md
- RELEASING.md
- docs/about.rst
- docs/index.rst
For https://github.com/python-pillow/Pillow/issues/5020.
> Update Travis CI links for .com

- LICENSE
- docs/about.rst
Resolves #5017
Updating LICENSE was suggested in https://github.com/python-pillow/Pillow/issues/5017#issuecomment-718056327. This PR also updates [docs/about.rst](https://pillow.readthedocs.io/en/stable/about.html#license) to be in sync.
> Refer to "HPND License" instead of "PIL Software License"

- Tests/fonts/LICENSE.txt
Resolves #4995 
According to https://en.wikipedia.org/wiki/GNU_FreeFont, FreeMono is licensed under GPLv3, with the GPL font exception.
> Document FreeMono license

- .gitignore
Updated extra test images list in `.gitignore` to match recent additions to https://github.com/python-pillow/pillow-depends/tree/master/test_images
> Updated extra test images list

- docs/reference/ImageFont.rst
> Link directly to pilfont script

- docs/handbook/image-file-formats.rst
PNG support for `append_images` was added in #4243
> PNG supports append_images

- src/PIL/Image.py
Resolves #5036 
```python
im = Image.open('Tests/images/hopper.webp', formats=('WEBP',))
```
`Image.open` calls `preinit()` first and then expects to loop through them. However, `formats` overrides this, and so `WEBP` is checked, which throws a `KeyError` because `init()` has not been called yet, as `Image.open()` only calls it if the `preinit()` formats do not match.
This PR resolves that.
> init() if one of the formats is unrecognised

- src/PIL/ImageFont.py
At https://pillow.readthedocs.io/en/latest/reference/ImageFont.html, 'BCP 47 language code' is not shown as a link. This PR fixes that.
> Fixed link formatting

- .ci/install.sh
- .github/workflows/test.yml
- .travis.yml
- Tests/test_image_quantize.py
For https://github.com/python-pillow/Pillow/issues/5028.
* Remove jobs which are already run on GitHub Actions
* Check coverage drops and see what's tested on Travis that's not in GHA
* Ideally add to GHA
* Or keep a single Travis job for a bit longer
* Or take the drop
* There's some redundant bits of scripts that can be removed now or later, e.g. `TRAVIS_PYTHON_VERSION` checks
> Remove excess Travis CI jobs

- src/display.c
I can't find any use of ImagingDisplay fromstring/tostring.
> Removed unused C methods

- .github/workflows/test-windows.yml
Fixes #5051 by resetting the cache.
* Add extra line breaks to improve readability.
* This changes the cache key and fixes the build.
* I'll try to have a look at whether it is possible to include the compiler version in the cache key hopefully tomorrow.
> Add line breaks in test-windows

- setup.py
Suggestion to help https://github.com/python-pillow/Pillow/issues/4960#issuecomment-706528502
To make the `RuntimeWarning` (that future versions of Python are not supported by a given Pillow release) more obvious, this PR raises it within the context of `atexit`, so that the warning is shown at the end of the output.
> Moved warning to end of execution

- .github/workflows/test-windows.yml
Fixes #5051 for the future.
Adding the VS version to the cache key should automatically clear the cache when there is an update. This might ignore compatible cache entries (when VS is updated but VC isn't), but that is better than the opposite (using incompatible cache entries). A cache delay would also be mitigated by adding a weekly cron trigger as mentioned in https://github.com/python-pillow/Pillow/issues/5028#issuecomment-728869632.
> GHA: Make windows cache depend on VS version

- .github/workflows/macos-install.sh
Before: https://github.com/python-pillow/Pillow/runs/1447978107#step:10:34
```
*** RAQM (Bidirectional Text) support not installed
```
After: https://github.com/python-pillow/Pillow/runs/1452096925?check_suite_focus=true#step:10:34
```
--- RAQM (Bidirectional Text) support ok, loaded 0.7.0
```
> GHA: Install Raqm on macOS

- winbuild/build_prepare.py
- winbuild/fribidi.cmake
- winbuild/raqm.cmake
> This version fixed various compilation problems and symbol exports necessary for proper compilation under Windows
> Update FriBiDi to 1.0.10

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
I've not been updating [CHANGES.rst](https://github.com/python-pillow/Pillow/blob/master/CHANGES.rst) for a while partly because it became too big/unwieldy to be editable on mobile. Also it's the sort of manual work that could and should be automated.
Let's automate it!
[Release Drafter](https://github.com/release-drafter/release-drafter) is a GitHub Action which runs when PRs are merged and I've been happily using it on other projects.
It takes the titles of PRs merged since the last release, and puts them into a *draft* release at https://github.com/python-pillow/pillow/releases
Drafts are only visible to maintainers, until they're published.
The idea is the draft will fill up, then on release day, the draft is published as usual.
If we still value putting the list into `CHANGES.rst` …
> Add Release Drafter to draft releases

- RELEASING.md
#5058 means that when releasing, we may not be creating GitHub releases from scratch, but instead publishing draft releases.
This PR changes the instructions accordingly. My hope is that saying 'publish the release' is more generic than 'create a new release', but that's my interpretation.
> Updated instructions now that draft releases may exist

- docs/handbook/writing-your-own-file-decoder.rst
https://pillow.readthedocs.io/en/latest/handbook/writing-your-own-file-decoder.html#the-raw-decoder
This PR fixes the problem where 'code-block' is not correctly understood - https://pillow--5068.org.readthedocs.build/en/5068/handbook/writing-your-own-file-decoder.html#the-raw-decoder
> Corrected documentation syntax

- .github/release-drafter.yml
Follow on from #5058.
* Looking at the PRs listed at the [8.1.0 draft](https://github.com/python-pillow/Pillow/releases), they mainly fall into three categories:
* Dependencies
* Documentation
* Testing
* Let's configure Release Drafter to group PRs with these labels into categories with these titles
* "Deprecations" and "Removals" would be useful for the future, to make those changes clear
* Everything else falls into the blanket "Changes" section
* By design, if a PR falls into multiple categories, it'll be listed in both. If we want to avoid it, we can use explicit `changelog: foo` labels
* It is possible to have multiple labels per category too
> Add categories to Release Drafter

- docs/deprecations.rst
- src/PIL/Image.py
- src/PIL/ImageFile.py
- src/PIL/__init__.py
* Pillow 9 is likely due in Q1 2022, after [Python 3.6's scheduled EOL on 2021-12-23](https://devguide.python.org/#status-of-python-branches)
* The four remaining deprecations from https://github.com/python-pillow/Pillow/issues/4764#issuecomment-656080258 have warned since 7.1.0 (April 2020) or 7.2.0 (June 2020), long enough for removal in January 2022
* Let's document the expected removal dates for increased clarity
> Document when deprecations will be removed

- README.md
- setup.py
* We got some good feedback for having a link to the changelog prominently on [PyPI](https://pypi.org/project/Pillow/): https://twitter.com/jugmac00/status/1334136469364088832
* Let's also add a link to the more-distilled release notes; the README is used as the PyPI long description
* We can also add them both as "Project URLs" so they appear in the PyPI project sidebar (and can also be accessed programmatically through the PyPI API)
> Docs: Add 'Release notes' and 'Changelog' links to PyPI

- .github/mergify.yml
Travis has been (temporarily?) disabled to conserve credits whilst we await more (https://github.com/python-pillow/Pillow/issues/5028#issuecomment-743359683), so remove it from the required automerge checks.
By the way, GitHub will have automerge in a week or two, we can check it when it's out.
https://github.blog/2020-12-08-new-from-universe-2020-dark-mode-github-sponsors-for-companies-and-more/#%e2%9c%a8-improved-daily-experience
> Disable Travis CI from automerge requirements

- Tests/helper.py
- Tests/test_file_libtiff.py
- Tests/test_image_quantize.py
The first part of #5088, to unblock the "latest" jobs in https://github.com/python-pillow/docker-images/pull/98.
* Add xfail to libtiff tests that are failing on big-endian (see also https://github.com/python-pillow/Pillow/issues/4213#issuecomment-721425032).
* Add xfail to `test_libimagequant_quantize` failing on ppc64le (not sure why).
See passing run targeting this branch: https://github.com/nulano/docker-images/runs/1542638808?check_suite_focus=true#step:5:5021
> Mark new test failures on non-x86 as xfail

- .github/workflows/test-windows.yml
- .github/workflows/test.yml
GHA just added support for PyPy3.7 (https://github.com/actions/setup-python/pull/168), add it to the matrix.
Also put the slower Windows PyPy jobs first.
It currently takes ~1m to install, but this is supposed to be resolved on the next GHA image rollout, see https://github.com/actions/setup-python/pull/168#issuecomment-747546240.
> GHA: Add PyPy3.7

- .ci/after_success.sh
- .ci/install.sh
- .ci/test.sh
- .github/CONTRIBUTING.md
- .github/mergify.yml
- README.md
- RELEASING.md
- Tests/bench_cffi_access.py
- Tests/helper.py
- depends/README.rst
- depends/diffcover-install.sh
- depends/diffcover-run.sh
- docs/about.rst
- docs/index.rst
- requirements.txt
Follow up to https://github.com/python-pillow/Pillow/pull/5029, for https://github.com/python-pillow/Pillow/issues/5028.
* Remove some unused Travis config after reducing testing in #5029 
* Removes the diffcover stuff, not run since #5029, and I've not checked it in a while, so let's just remove it (unless anyone else wants it), and we have linting on the CI anyway
PS Due to a git mistake I accidentally pushed this change directly to `upstream/master`, so I reset and force-pushed.
> Remove unused Travis CI config

- Tests/test_imagepath.py
For https://github.com/python-pillow/Pillow/issues/722.
* Adds some extra tests for `ImagePath.Path`
* Bumps `path.c` coverage from 64.52% to 75.63%
* ["Pillow (PIL) examples"](https://hhsprings.bitbucket.io/docs/programming/examples/python/PIL/ImagePath.html) was handy to check some example calls
> Add tests for ImagePath.Path

- docs/releasenotes/7.1.1.rst
- docs/releasenotes/7.1.2.rst
These code blocks represent Python console sessions, not Python source
code. The pycon lexer understands the ">>>" prompt and output (e.g. a
traceback).
> Update some doc code blocks to the 'pycon' lexer

- .github/workflows/test.yml
- Makefile
- Tests/test_imagefont.py
- docs/Makefile
- docs/conf.py
- docs/deprecations.rst
- docs/releasenotes/3.1.1.rst
- docs/releasenotes/3.1.2.rst
- docs/releasenotes/6.2.0.rst
- docs/releasenotes/6.2.2.rst
- docs/releasenotes/7.1.0.rst
- docs/releasenotes/8.0.1.rst
- docs/releasenotes/8.1.0.rst
- docs/releasenotes/index.rst
- requirements.txt
- src/PIL/ImageFont.py
Fixes #5075.
* Add deprecation warning when using ImageFont with FreeType older than 2.8
* Autolink CVEs with https://github.com/sloria/sphinx-issues
* :cve:`CVE-2020-15999` becomes https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-15999
* Autolink a PEP with https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-pep
* :pep:`527` becomes https://www.python.org/dev/peps/pep-0527
* Update Makefile docs command for Python 3
> Deprecate FreeType 2.7

- docs/reference/ImageCms.rst
*  an color -> a color in ImageCms.rst
> Fix use of a versus an in ImageCms.rst

- src/_imaging.c
- src/decode.c
- src/encode.c
- src/path.c
In several locations,
- Replaced PyErr_NoMemory with ImagingError_MemoryError
https://github.com/python-pillow/Pillow/blob/c1707d5d55c80255fec3fa671cda313f1a3cbfad/src/_imaging.c#L279-L283
- Simplified
```c
ImagingError_MemoryError();
return NULL;
```
into
```c
return ImagingError_MemoryError();
```
> Replaced PyErr_NoMemory with ImagingError_MemoryError

- RELEASING.md
- docs/releasenotes/index.rst
- docs/releasenotes/versioning.rst
Resolves #5003, by essentially adding a restructured version of https://github.com/python-pillow/Pillow/issues/5003#issuecomment-715501191 to RELEASING.md.
> Added versioning documentation

- Tests/test_file_tiff.py
- src/PIL/TiffImagePlugin.py
Resolves #5119
The image from the issue is crashing when trying to set [TIFFTAG_SUBIFD](https://www.awaresystems.be/imaging/tiff/tifftags/subifds.html) - specifying offsets to more data.
However, given that we aren't writing data to these arbitrary locations, we might as well as just block the tag.
> Block TIFFTAG_SUBIFD

- CHANGES.rst
- Tests/test_file_ico.py
- src/PIL/IcoImagePlugin.py
This adds support for the append_images parameter when saving .ICO files. Its behavior is much the same as for .ICNS files, and can be used to provide alternative sprites for particular icon sizes instead of simply resizing the main image to fit that size.
> Add append_images support for ICO

- src/_imagingft.c
- src/libImaging/GetBBox.c
Resolves #4586
Current warnings - https://github.com/python-pillow/Pillow/runs/1595213891#step:9:25 and https://github.com/python-pillow/Pillow/runs/1595213891#step:9:94
These changes are both for `im->image`. Casting from `im->image` to `UINT8*` is done multiple times in Convert.c, so this PR casts here as well.
https://github.com/python-pillow/Pillow/blob/ce3d80e7136710ea81b206fd160484013f913c2e/src/libImaging/Convert.c#L1427
https://github.com/python-pillow/Pillow/blob/ce3d80e7136710ea81b206fd160484013f913c2e/src/libImaging/Convert.c#L1681
https://github.com/python-pillow/Pillow/blob/ce3d80e7136710ea81b206fd160484013f913c2e/src/libImaging/Convert.c#L1754
> Fixed warnings assigning to "unsigned char *" from "char *"

- src/libImaging/TiffDecode.c
(triggered in Tests/test_file_libtiff.py::TestFileLibTiff::test_custom_metadata)
Valgrind output: 
```
**88** **********************************************************************
**88** Tests/test_file_libtiff.py::TestFileLibTiff::test_custom_metadata
**88** **********************************************************************
==88== Invalid read of size 1
==88==    at 0x890596C: _TIFFSetupFields (in /usr/lib/x86_64-linux-gnu/libtiff.so.5.5.0)
==88==    by 0x8904EEC: TIFFDefaultDirectory (in /usr/lib/x86_64-linux-gnu/libtiff.so.5.5.0)
==88==    by 0x890504C: TIFFCreateDirectory (in /usr/lib/x86_64-linux-gnu/libtiff.so.5.5.0)
==88==    by 0x8912141: ??? (in /usr/lib/x86_64-linux-gnu/libtiff.so.5.5.0)
==88==    by 0x89126EF: TIFFRewriteDirectory (in …
```
> Fix OOB Read when writing TIFF with custom Metadata

- docs/releasenotes/8.1.0.rst
Documents the updating of OpenJPEG 2.3.1 to 2.4.0 in https://github.com/python-pillow/pillow-wheels/pull/179, fixing security problems in that dependency
Suggested in https://github.com/python-pillow/Pillow/pull/5151#issuecomment-751903072
> OpenJPEG has been updated in pillow-wheels

- Tests/test_image_putpalette.py
- src/PIL/Image.py
Resolves #4941
At the moment, `Image.putpalette` can only accept 256 RGB values. As the issue found, this means that alpha values cannot be included. This PR allows 256 RGBA values as well, by stripping out every 4th value for `info["transparency"]` in `load()`.
> Allow putpalette to accept 1024 integers to include alpha values

- src/PIL/Image.py
Helps #4926
The unaddressed part of that issue is that there is a chain of three ValueErrors raised by the following code.
```pycon
>>> img = Image.new('F', (200,100), 1.0)
>>> img.putalpha(Image.new('L', (200,100), 255))
File "PIL/Image.py", line 1620, in putalpha
self.im.setmode(mode)
ValueError: image has wrong mode
During handling of the above exception, another exception occurred:
File "PIL/Image.py", line 1623, in putalpha
im = self.im.convert(mode)
ValueError: conversion from F to LA not supported
The above exception was the direct cause of the following exception:
File "PIL/Image.py", line 1630, in putalpha
raise …
```
> Do not catch a ValueError only to raise another

- docs/reference/ImageFont.rst
Helps #5124
When saving, `FontFile` only saves 256 characters.
https://github.com/python-pillow/Pillow/blob/b48cfa747cecd02ee4d76d12f7bbf64e186982af/src/PIL/FontFile.py#L102-L111
This PR notes this when discussing converting from other font formats.
> Document limited number of characters in FontFile

- Tests/test_file_png.py
- src/PIL/Image.py
Resolves #5116, in the absence of better solutions
The issue requests a clearer error message when an image fails to display in IPython. This PR catches any error raised when saving to PNG for display, and states "Could not save to PNG for display".
> Added exception explaining that _repr_png_ saves to PNG

- src/PIL/BmpImagePlugin.py
- src/PIL/CurImagePlugin.py
- src/PIL/EpsImagePlugin.py
- src/PIL/FliImagePlugin.py
- src/PIL/FpxImagePlugin.py
- src/PIL/GbrImagePlugin.py
- src/PIL/GdImageFile.py
- src/PIL/GifImagePlugin.py
- src/PIL/GribStubImagePlugin.py
- src/PIL/IcnsImagePlugin.py
- src/PIL/IcoImagePlugin.py
- src/PIL/ImImagePlugin.py
- src/PIL/Image.py
- src/PIL/IptcImagePlugin.py
- src/PIL/JpegImagePlugin.py
- src/PIL/MspImagePlugin.py
- src/PIL/PcdImagePlugin.py
- src/PIL/PcxImagePlugin.py
- src/PIL/PixarImagePlugin.py
- src/PIL/PngImagePlugin.py
- src/PIL/PsdImagePlugin.py
- src/PIL/SgiImagePlugin.py
- src/PIL/SunImagePlugin.py
- src/PIL/TgaImagePlugin.py
- src/PIL/TiffImagePlugin.py
- src/PIL/XVThumbImagePlugin.py
- src/PIL/XpmImagePlugin.py
> Better _binary module use

- src/libImaging/TiffDecode.c
- winbuild/build_prepare.py
- winbuild/tiff.opt
Resolves #5157
Updated libtiff to 4.2.0, adding a setting to 'winbuild/tiff.opt' because of https://gitlab.com/libtiff/libtiff/-/commit/58b16f47a82323c05ec81f0a821700beb8c2c5a0 (later [simplified](https://gitlab.com/libtiff/libtiff/-/commit/7a335a32ebbce103d429c82a8d60d25ead1ccf0e)).
However, from the first commit here, you can see that a test fails.
Investigating, it is failing specifically because of https://github.com/python-pillow/Pillow/blob/18ee51a5a80592bf9a09e9fd9b0674e4f58a5d15/Tests/test_file_libtiff.py#L256
libtiff 4.2.0 added the ['Rational2Double' block in this code](https://gitlab.com/libtiff/libtiff/-/blob/v4.2.0/libtiff/tif_dir.c#L563-566) (if you're interested, it was part of https://gitlab.com/Su_Laus/libtiff/-/commit/6df997c786928757caea0dd68d26ea5f098f49df) -
```c …
```
> Updated libtiff to 4.2.0

- .github/workflows/test-windows.yml
https://github.com/pypa/wheel/issues/354 has been closed.
Reverts part of #4980
> Revert "skip wheels on 3.10-dev due to wheel#354"

- Tests/test_decompression_bomb.py
https://docs.pytest.org/en/stable/xunit_setup.html#class-level-setup-teardown shows
```python
@classmethod
def teardown_class(cls):
```
whereas we have
https://github.com/python-pillow/Pillow/blob/01cee38b9b02b4be85a1c38cd746e40aa6ed05e1/Tests/test_decompression_bomb.py#L13-L14
This PR replaces `self` with `cls`.
> Corrected argument

- Tests/test_imageqt.py
- Tests/test_qt_image_qapplication.py
- src/PIL/ImageQt.py
Fixes https://github.com/python-pillow/Pillow/issues/5145.
There are two sets of Python bindings for Qt, called PyQt and PySide. 
> Why are there two packages?
>
> PyQt has been developed by Phil Thompson of Riverbank Computing Ltd. for a very long time — supporting versions of Qt going back to 2.x. Back in 2009 Nokia, who owned the Qt toolkit at the time, wanted to have Python bindings for Qt available under the LGPL license (like Qt itself). Unable to come to agreement with Riverbank (who would lose money from this, so fair enough) they then released their own bindings as PySide (also, fair enough).
https://www.learnpyqt.com/tutorials/pyqt5-vs-pyside2/
We support:
* PySide2 for Qt 5
* PyQt5 for Qt 5
Qt 6 has been recently released: https://www.qt.io/blog/qt-6.0-released
* PyQt6 is still …
> Add support for PySide6

- Tests/test_file_gif.py
- src/libImaging/GifEncode.c
Triggered in Tests/test_file_gif.py::test_optimize
There is a OOB read of size 1 when the width of the image is 1. 
Valgrind output:
```
Tests/test_file_gif.py::test_optimize **70** 
**70** **********************************************************************
**70** Tests/test_file_gif.py::test_optimize
**70** **********************************************************************
==70== Invalid read of size 1
==70==    at 0x87A7194: ImagingGifEncode (GifEncode.c:237)
==70==    by 0x877D519: _encode (encode.c:141)
==70==    by 0x64BF47: method_vectorcall_VARARGS (descrobject.c:300)
```
> Fix Out of bounds read when saving GIF of xsize=1

- Makefile
- docs/releasenotes/8.1.0.rst
> Add #5159 to the release notes

- docs/releasenotes/8.1.0.rst
Release notes for https://github.com/python-pillow/pillow-wheels/pull/180, similar to #5152.
Based on http://simplesystems.org/libtiff/v4.2.0.html#highlights
I'm not sure if it is important to mention every dependency update with security fixes in the release notes, but it seems reasonable to me.
> Release notes for LibTIFF update in pillow-wheels

- Tests/oss-fuzz/fuzz_pillow.py
- setup.py
In-tree support for https://github.com/google/oss-fuzz/. 
Includes 
* an updated version of the fuzz-pillow script that enables decompression bomb errors
* sets zipsafe to false when building for the fuzzer to make custom builds far better. 
There will be a corresponding PR to the oss-fuzz repo that should be merged after this.
> Oss fuzz support

- docs/reference/Image.rst
Minor. Changes example image file name to be 'hopper.jpg', for consistency with the other examples.
> Changed example image file name

- .appveyor.yml
- .ci/test.sh
- .github/workflows/test-windows.yml
- src/_imaging.c
- src/_webp.c
Resolves #5193
The first commit adds `python3 -c "from PIL import Image"` to .ci/test.sh - for whatever reason, this fails in Python 3.10, while our pytest command does not.
The second commit replaces instances like
```c
#ifdef HAVE_XCB
PyModule_AddObject(m, "HAVE_XCB", Py_True);
#else
PyModule_AddObject(m, "HAVE_XCB", Py_False);
#endif
```
with
```c
PyObject *have_xcb;
#ifdef HAVE_XCB
have_xcb = Py_True;
#else
have_xcb = Py_False;
#endif
Py_INCREF(have_xcb);
PyModule_AddObject(m, "HAVE_XCB", have_xcb);
```
This is per the example in https://docs.python.org/3/c-api/module.html#c.PyModule_AddObject, which calls `Py_INCREF` before `PyModule_AddObject`.
> PyModule_AddObject fix for Python 3.10

- Tests/conftest.py
- Tests/test_file_eps.py
- Tests/test_file_jpeg.py
- Tests/test_file_libtiff.py
- Tests/test_file_pdf.py
- Tests/test_file_png.py
- Tests/test_file_webp_metadata.py
- Tests/test_image.py
- Tests/test_image_resample.py
- Tests/test_image_thumbnail.py
Before we can add valgrind as an experimental docker test target, we need to have all of the tests passing or known ignored.
This adds:
* a pytest configuration for ignoring the error when pytest-valgrind isn't installed. 
* Ignores the tiff_additional_metadata test, because we're sending some illogical values to it. 
WIP -- there are more tests to investigate.
> Support for ignoring tests when running valgrind

- setup.py
Do fuzzing linking in setup.py options, rather than post-hoc manually linking.
This links all of the extensions with the fuzzer, rather than just _imaging.so
This is a prerequisite for changing the build script upstream.
> Link OSS-Fuzz in setup.py

- src/PIL/PcxImagePlugin.py
The PCX vulnerability was https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-35653, not https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-35655 as a comment currently states.
> Corrected CVE number

- docs/reference/features.rst
- src/PIL/_tkinter_finder.py
- src/PIL/features.py
Changes pilinfo from
```
--- PIL CORE support ok, compiled for 8.1.0
--- TKINTER support ok
--- FREETYPE2 support ok, loaded 2.10.4
```
to
```
--- PIL CORE support ok, compiled for 8.2.0.dev0
--- TKINTER support ok, loaded 8.6
--- FREETYPE2 support ok, loaded 2.10.4
```
> Added tk version to pilinfo

- src/PIL/Image.py
Fixes #5222
* Corrected documentation for conversion method: threshold is 127, not 128
See #5222 for more information
> Documentation error: Wrong threshold in conversion from L to 1

- .github/workflows/test-windows.yml
Fixes an error that has started appearing on MSYS jobs. Seen in #5230 (https://github.com/python-pillow/Pillow/pull/5230/checks?check_run_id=1779961003#step:6:32) and #5232, and will presumably be seen in master with the next merge.
```
Running selftest:
--- 58 tests passed.
File "C:/msys64/mingw64/lib/python3.8/runpy.py", line 185, in _run_module_as_main
mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
File "C:/msys64/mingw64/lib/python3.8/runpy.py", line 144, in _get_module_details
return _get_module_details(pkg_main_name, error)
File "C:/msys64/mingw64/lib/python3.8/runpy.py", line 111, in _get_module_details
__import__(pkg_name)
File "C:/msys64/mingw64/lib/python3.8/site-packages/pytest/__init__.py", line 5, in <module>
from …
```
> Install pytest and pytest-cov using pip rather than pacman

- .appveyor.yml
Tests now pass without it.
While the line was added in #5014, see #4784 for the story behind why that setuptools version is a necessary minimum.
> Removed specific setuptools version from AppVeyor

- src/PIL/Image.py
The current `close()` docstring mentions that `load()` closes images
https://github.com/python-pillow/Pillow/blob/b35cf8bddaddd7c77ec0f99baf2c5963c3671854/src/PIL/Image.py#L589-L592
However, https://pillow.readthedocs.io/en/stable/reference/open_files.html#proposed-file-handling mentions that this is not the case for images with multiple frames.
> - Image.Image.load() should close the image file, unless there are multiple frames.
...
> - Users of the library should use a context manager or call Image.Image.close() on any image opened with a filename or Path object to ensure that the underlying file is closed.
This PR updates the `close()` docstring to be mention that as well.
> Improved close() docstring

- Tests/test_file_libtiff.py
- Tests/test_file_tiff.py
Helps #5229
[Removing libtiff from our GHA Windows jobs](https://github.com/radarhere/Pillow/commit/4ce30cd10e7cf6f89f79a46f7da60609dcae7870) causes [a failure from the TestFileTiff::test_subifd](https://github.com/radarhere/Pillow/runs/1782858485?check_suite_focus=true#step:26:664).
So this PR moves that test into test_file_libtiff, so that [it is skipped if libtiff is not available](https://github.com/python-pillow/Pillow/blob/d79c656fe75c5de2916b9889a726c33b11dab020/Tests/test_file_libtiff.py#L24) - [the change](https://github.com/radarhere/Pillow/commits/no_libtiff_with_fix) fixes the [failing test](https://github.com/radarhere/Pillow/actions/runs/517609733)
> Moved test that requires libtiff

- docs/deprecations.rst
- docs/releasenotes/8.2.0.rst
- docs/releasenotes/index.rst
- src/PIL/_tkinter_finder.py
Tk/Tcl 8.4.0 was released Sep 18, 2000
Tk/Tcl 8.5.0 was released Dec 20, 2007
Tk/Tcl 8.4.20, the most recent version of 8.4, was released Jun 1, 2013
Support for Tk/Tcl < 8.4 was removed in #1288
> Deprecate Tk/Tcl 8.4, to be removed in Pillow 10 (2023-01-02)

- Tests/test_file_png.py
I noticed this at https://github.com/python-pillow/docker-images/pull/103/checks?check_run_id=1814049272#step:4:4966
> Tests/test_file_png.py::TestFilePng::test_read_private_chunks
>  /vpy3/lib/python3.8/site-packages/_pytest/python.py:183: ResourceWarning: unclosed file <_io.BufferedReader name='Tests/images/exif.png'>
>    result = testfunction(**testargs)
> Fixed unclosed file warning

- Tests/test_image.py
- src/PIL/Image.py
* Make `formats` parameter in `Image.open` accept aNy cAsE.
Before this commit
```python
Image.open("Tests/images/hopper.png", formats=['png'])
```
would fail, because the format is not upper case (`'PNG'`). This PR makes `'PNG'`, `'Png'`, `'pNG'` and all other variants equivalent in the `formats` list (or tuple).
> Changed Image.open formats parameter to be case-insensitive

- docs/reference/limits.rst
https://github.com/python-pillow/Pillow/blob/master/docs/reference/limits.rst
> * Any call to internal python size functions for buffers or strings are currently returned as int32, not py_ssize_t. This limits the	maximum buffer to 2GB for operations like frombytes and frombuffer.	
>
> * This also limits the size of buffers converted using a decoder. (decode.c:127)
#3791 replaced `int`s with `py_ssize_t`, so this is no longer correct.
For clarity, 'decode.c:127' was https://github.com/python-pillow/Pillow/blob/937199e54556dae5882e3d2a65d804365a8cca67/decode.c#L127 at the time.
> Removed outdated limits documentation

- src/PIL/ImageColor.py
The `ImageColor.getrgb()` docstring states that it results in "an RGB tuple" - but later it mentions it might also return alpha values, and indeed, RGBA support was added in #309.
This PR updates it to "Convert a color string to an RGB or RGBA tuple."
https://github.com/python-pillow/Pillow/blob/f118a21d557c0446e4d0b7730105d0fd0f55f045/src/PIL/ImageColor.py#L25-L34
> Updated ImageColor.getrgb docstring

- Tests/test_imageqt.py
- Tests/test_qt_image_qapplication.py
- docs/releasenotes/8.2.0.rst
- src/PIL/ImageQt.py
> Added PyQt6 support

- docs/reference/ImageColor.rst
Updates the docs with an example how to specify hexadecimal rgb color values with an alpha channel / opacity.
Related code:
https://github.com/python-pillow/Pillow/blob/d374015504df2c7f0316154deade1bc1fa5075df/src/PIL/ImageColor.py#L48-L65
> Docs: add alpha channel to supported hex color specifiers

- docs/reference/ImageQt.rst
- src/PIL/ImageQt.py
- Added PyQt6 and PySide6 to list of modules
- Corrected `ImageQt.fromqimage()` docstring. It currently states that it takes "A PIL Image object, or a file name", but then calls `hasAlphaChannel()`.
https://github.com/python-pillow/Pillow/blob/fdd8b68b83fd1afdbbe5d0a0460ac1413299dcc5/src/PIL/ImageQt.py#L74
This is a `QImage` method - https://doc.qt.io/qt-5/qimage.html#hasAlphaChannel - not a PIL method or something that you can call on a file name. So this PR updates the docstring to state that it takes a `QImage` or `ImageQt.ImageQt` object (a subclass of `QImage`).
> Improved ImageQt documentation

- Tests/test_bmp_reference.py
- Tests/test_file_dcx.py
- Tests/test_file_fli.py
- Tests/test_file_gif.py
- Tests/test_file_icns.py
- Tests/test_file_im.py
- Tests/test_file_jpeg.py
- Tests/test_file_mpo.py
- Tests/test_file_png.py
- Tests/test_file_psd.py
- Tests/test_file_spider.py
- Tests/test_file_tar.py
- Tests/test_file_tiff.py
- Tests/test_file_webp.py
- Tests/test_image.py
- Tests/test_numpy.py
The following test is intended to check that no warnings are raised when opening and closing an image.
https://github.com/python-pillow/Pillow/blob/cc4ed21f191760fbf36417d79eca3ed3555245ea/Tests/test_file_fli.py#L40-L46
If I [change it like so](https://github.com/radarhere/Pillow/commit/418069e0ecce94c29c0e5cd5d2195d45e2b11d68)
```python
def test_closed_file():
def open():
Image.open(static_test_file)
pytest.warns(ResourceWarning, open)
```
It [passes (except in PyPy).](https://github.com/radarhere/Pillow/actions/runs/554673724) So we know that a ResourceWarning is raised by my modification.
But if I [change it back to assert that there are no warnings,](https://github.com/radarhere/Pillow/commit/e7ebc16499d32e4bf0774b8cca968a68beac9013)
```python
def test_closed_file():
def open(): …
```
> Fixed asserting that no warnings were raised

- Tests/test_numpy.py
Replaces `np.bool` with `bool` and `np.float` and `float`, as per https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
Warnings about this can currently be seen at https://github.com/python-pillow/Pillow/runs/1968656801#step:10:1890
> Tests/test_numpy.py::test_numpy_to_image
>   /home/runner/work/Pillow/Pillow/Tests/test_numpy.py:34: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
>   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
>     assert_image(to_image(numpy.bool, 1, 1), "1", TEST_IMAGE_SIZE)
> 
> …
> Migrated from deprecated numpy bool and float

- docs/reference/Image.rst
- docs/reference/ImageDraw.rst
- docs/reference/ImageMath.rst
- docs/reference/c_extension_debugging.rst
Updating documentation to use context managers, per https://pillow.readthedocs.io/en/stable/releasenotes/7.0.0.html#image-del
> Implicitly closing the image’s underlying file in Image.__del__ has been removed. Use a context manager or call close() instead to close the file in a deterministic way.
> Added context managers to documentation

- src/libImaging/Jpeg2KEncode.c
The suspicious type casting is: `memsize -> 32-bit integer -> memsize`
> Fix suspicious sequence of types castings

- docs/releasenotes/8.1.1.rst
The release notes for 8.1.1 currently read
> A crash with the feature flags for libjpeg and WebP on unreleased Python 3.10 has been fixed (#5193).
Except if you look at the code for the fix - #5194 - this list should be libjpeg**turbo**, WebP, libimagequant and XCB.
> Corrected list of relevant dependencies

- docs/releasenotes/8.1.1.rst
Tidelift reported the existence of
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-27921
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-27922
and
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-27923
This PR adds them to the 8.1.1 release notes
> Added more CVE numbers to 8.1.1 release notes

- Tests/test_imageshow.py
- docs/reference/ImageShow.rst
- docs/releasenotes/8.2.0.rst
- src/PIL/ImageShow.py
Resolves #5286 by adding a new `ImageShow.Viewer` - `IPythonViewer`. It calls the `display()` method to allow `ImageShow` to work with IPython... and Google Colab.
Here is my demonstration of it working in Google Colab.
```python
from PIL import Image, ImageShow
im = Image.new("RGB", (100, 100))
im.show()
```
```python
from PIL import ImageShow
class IPythonViewer(ImageShow.Viewer):
def show_image(self, image, **options):
display(image)
return 1
try:
from IPython.display import display
except ImportError:
pass
else:
ImageShow.register(IPythonViewer)
im = Image.new("RGB", (100, 100))
im.show()
ImageShow._viewers = [v for v in ImageShow._viewers if v.__class__ != IPythonViewer]
```
> Added IPythonViewer

- .github/workflows/test-windows.yml
- .github/workflows/test.yml
I recently pushed a [commit](https://github.com/radarhere/Pillow/commit/adf125309e789f5a9568f212d4676010a6852c63) to GitHub Actions. It failed for a perfectly valid reason, but when failing, [test-windows reported](https://github.com/radarhere/Pillow/runs/1751631505?check_suite_focus=true) -
The '-p' flag is meant to [prevent this error](https://github.com/python-pillow/Pillow/pull/4379), but I guess this doesn't work on Windows (https://en.wikipedia.org/wiki/Mkdir#Options)
So instead, this PR replaces 'mkdir' with a Python command. It also changes test.yml, just for symmetry.
See https://github.com/radarhere/Pillow/runs/1751747364?check_suite_focus=true for my failing case combined with this commit to produce a correct 'Prepare to upload errors'
> Replaced mkdir command with Python

- Tests/test_imageqt.py
- src/PIL/ImageQt.py
If the `ImageQt.ImageQt` class is passed a path, it opens the file - but it doesn't close it with `close()` or a context manager. This PR fixes that, closing `im` within `_toqclass_helper`.
`_toqclass_helper` previously returned `im`, but only for so that `ImageQt.ImageQt` could extract the size from it. So I've changed that to just return the size directly, and keep `im` within `_toqclass_helper`. This should be fine in terms of backwards compatibility, as the method is indicated to be for private use by the leading `_`.
> Ensure file is closed if it is opened by ImageQt.ImageQt

- src/libImaging/TiffDecode.c
When building under an environment with -Werror=format, TiffDecode.c no longer builds:
```
src/libImaging/TiffDecode.c: In function ‘_tiffReadProc’:
src/libImaging/TiffDecode.c:59:58: error: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘toff_t’ {aka ‘long unsigned int’} [-Werror=format=]
src/libImaging/TiffDecode.c:59:67: error: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘toff_t’ {aka ‘long unsigned int’} [-Werror=format=]
```
> Fix -Wformat error in TiffDecode

- Tests/test_qt_image_qapplication.py
- src/PIL/ImageQt.py
Resolves #5266. A workaround suggested in that issue is to change the user code. This PR causes the original code mentioned there to work.
https://github.com/python-pillow/Pillow/blob/fdd8b68b83fd1afdbbe5d0a0460ac1413299dcc5/src/PIL/ImageQt.py#L203-L205
This 'strange bug' is because at https://doc.qt.io/qt-5/qimage.html
> QImage::Format_RGB32... is stored using a 32-bit RGB format (0xffRRGGBB).
QImage is expecting the 4th channel to be populated with 0xff (255). Calling `convert("RGBA")` in Pillow does this.
https://github.com/python-pillow/Pillow/blob/fdd8b68b83fd1afdbbe5d0a0460ac1413299dcc5/src/libImaging/Convert.c#L421-L431
Without 255 values, as seen in the issue, the display in Qt is very washed out.
This PR just documents the fix slightly better, and moves it from `toqpixmap()` to …
> Moved RGB fix inside ImageQt class

- Tests/test_file_png.py
- Tests/test_file_tiff.py
- src/PIL/TiffImagePlugin.py
Resolves #5225
As #1909 allowed `im.save("out.png", icc_profile=icc_profile)`, so this PR allows `icc_profile` to be specified through arguments for TIFF.
> Save ICC profile from TIFF encoderinfo

- docs/handbook/image-file-formats.rst
- docs/releasenotes/8.2.0.rst
`icc_profile` is now a keyword argument when saving TIFF files
> Document #5321

- docs/handbook/image-file-formats.rst
Resolves #5335, that states that the "compression" list at https://pillow.readthedocs.io/en/latest/handbook/image-file-formats.html#saving-tiff-images is incorrect.
I've added "tiff_lzw", "jpeg", "packbits", "lzma", "zstd" and "webp" from https://github.com/python-pillow/Pillow/blob/8064e04e963e3061918564d3c5fff35074577f29/src/PIL/TiffImagePlugin.py#L109-L128
and removed "tiff_jpeg" (since it is obsolete, see #4627, let's stop advertising it).
> Updated list of TIFF compression methods

- Tests/test_file_libtiff.py
- src/PIL/TiffImagePlugin.py
Suggested in https://github.com/python-pillow/Pillow/issues/5335#issuecomment-801742691
> Also, I suggest taking out `tiff_deflate` from this doc list while you're at it, as it should not be used for writing, [see this TIFF tech note](https://www.adobe.io/content/dam/udp/en/open/standards/tiff/TIFFphotoshop.pdf):
> 
> > A proprietary ZIP/Flate compression code (0x80b2) has been used by some software vendors. This code should be considered obsolete. The compression used by the obsolete code is identical to that defined above. We recommend that TIFF implementations recognize and read the obsolete code, but only write the official compression code (8).
Similar to #4627
> Replaced tiff_deflate with tiff_adobe_deflate compression when saving TIFF images

- src/PIL/GifImagePlugin.py
Two changes.
1. Do not call `self.im.copy()`, only to then call `self._crop` - `self._crop` already creates a copy of the image.
2. Instead of creating a solid color image of `self.size` and then cropping it, just create the solid color image at the necessary size.
> Improved efficiency when creating GIF disposal images

- Tests/test_file_png.py
Line 1189 is currently untested
https://github.com/python-pillow/Pillow/blob/8064e04e963e3061918564d3c5fff35074577f29/src/PIL/PngImagePlugin.py#L1187-L1189
> Added test for saving PNG with bits keyword

- Tests/test_file_webp.py
- src/PIL/WebPImagePlugin.py
Helps #4313
When saving GIF, if `duration` is not passed in through a keyword argument, it defaults to the duration from the `info` dictionary - https://github.com/python-pillow/Pillow/blob/9dcb1f402cf0921b22e456eeb2ac0ad1ebbdee6d/src/PIL/GifImagePlugin.py#L426
This PR adds that behaviour to WebP.
> Use duration from info dictionary when saving WebP

- Tests/test_file_png.py
- src/PIL/PngImagePlugin.py
Resolves #2202
Currently when saving a PNG in P mode, Pillow sets the number of bytes in the palette at two to the power of the bit depth, times 3 for the colors.
https://github.com/python-pillow/Pillow/blob/8064e04e963e3061918564d3c5fff35074577f29/src/PIL/PngImagePlugin.py#L1272-L1274
As pointed out in the issue, https://www.w3.org/TR/PNG/#11PLTE states that
> It is permissible to have fewer entries than the bit depth would allow.
So this PR changes `palette_byte_number` to the number of colors times 3 instead.
The length of the tRNS chunk is also changed, as https://www.w3.org/TR/PNG/#11tRNS
> The tRNS chunk shall not contain more alpha values than there are palette entries
> Allow fewer PNG palette entries than the bit depth maximum when saving

- .github/CONTRIBUTING.md
* As suggested https://github.com/python-pillow/Pillow/pull/5349#issuecomment-804281592, ask contributors to include release notes as needed or appropriate.
* Similar to the info at https://github.com/python-pillow/Pillow/blob/master/docs/releasenotes/index.rst
> Contributing docs: Include release notes as needed or appropriate

- docs/installation.rst
Resolves #3671, by specifically listing the Debian Pillow packages.
> Listed Debian packages

- docs/reference/Image.rst
- src/PIL/Image.py
Alternative to #5251. The same information is added, just arranged differently.
> Document quantize method defaults and mode support

- src/libImaging/Quant.c
`build_distance_tables` only ever returns 1 - https://github.com/python-pillow/Pillow/blob/9b69d940827289e806cc19baca4d5291386ef195/src/libImaging/Quant.c#L792-L815
So this PR removes the return value.
> Removed build_distance_tables return value

- src/PIL/Image.py
Instead of using `0`, `2` and `3` in `im.quantize`, use the more meaningful `MEDIANCUT`, `FASTOCTREE` and `LIBIMAGEQUANT`.
> Use quantization method attributes

- Tests/test_image_transform.py
- src/PIL/Image.py
Fixes #5300.
Test is based on the previous tests that make sure premultiplied alpha is used with BILINEAR resampling.
From https://pillow.readthedocs.io/en/stable/handbook/concepts.html#PIL.Image.NEAREST:
> Pick one nearest pixel from the input image. Ignore all other input pixels.
I would interpret that as meaning that each pixel in the output will be equal to one of the original pixels, i.e. not introducing new values.
> Do not premultiply alpha when resizing with Image.NEAREST resampling

- Tests/test_image.py
- docs/deprecations.rst
- docs/reference/Image.rst
- docs/releasenotes/8.2.0.rst
- src/PIL/Image.py
- src/PIL/MicImagePlugin.py
Images have a ``category`` property. It is set to ``Image.NORMAL``
https://github.com/python-pillow/Pillow/blob/aa35f6b572c3491976e2336b28f481dad0a2a353/src/PIL/Image.py#L538
Unless the image format is MIC and there are multiple frames, in which case it is ``Image.CONTAINER``.
https://github.com/python-pillow/Pillow/blob/aa35f6b572c3491976e2336b28f481dad0a2a353/src/PIL/MicImagePlugin.py#L70-L71
There is also the unused attribute ``Image.SEQUENCE``.
https://github.com/python-pillow/Pillow/blob/aa35f6b572c3491976e2336b28f481dad0a2a353/src/PIL/Image.py#L190-L193
This minimal support across formats shows the feature has clearly not kept up with our other changes around multi-frames images, and can be deprecated in favour of `is_animated`.
> Deprecated categories

- .gitignore
- Tests/oss-fuzz/build.sh
- Tests/oss-fuzz/build_dictionaries.sh
- Tests/oss-fuzz/fuzz_font.py
- Tests/oss-fuzz/fuzz_pillow.py
- Tests/oss-fuzz/fuzzers.py
- Tests/oss-fuzz/test_fuzzers.py
* Delegate build.sh, build-dictionaries to Pillow. This requires a further commit in oss-fuzz after this merges to master
* Add a fuzzer for font files. This opens truetype files and performs some basic operations with them. 
* Refactor and add tests for the fuzzers. This should catch any cases of the fuzzers totally failing with unexpected errors, but we are still expecting that there are a reasonable number of exceptions thrown due to attempting to load broken input. 
* Lint fixes
> More OSS-Fuzz support

- Tests/test_image.py
- src/libImaging/Fill.c
Resolves #5272
`Image.linear_gradient("I")`, `Image.linear_gradient("F")`, `Image.radial_gradient("I")` and `Image.radial_gradient("F")` all currently segfault. This fixes them.
> Fixed linear_gradient and radial_gradient I and F modes

- src/PIL/ImageFilter.py
Resolves #5320
Moves `ImageFilter` numpy import into the `ImageFilter.Color3DLUT` constructor, so that numpy is not imported only to be unused.
> Only import numpy when necessary

- Tests/test_imageops.py
- docs/releasenotes/8.2.0.rst
- src/PIL/ImageOps.py
* Added **preserve_tone** option to the autocontrast function.
As already have been discussed [here](https://github.com/python-pillow/Pillow/pull/1246) **autocontrast** function changes the tone of the image because of the usage of separate histograms for each channel.
@broxeph, @wiredfool
Example:
> Add preserve_tone option to autocontrast

- docs/installation.rst
- docs/releasenotes/8.2.0.rst
- src/thirdparty/fribidi-shim/fribidi.c
- winbuild/build.rst
Release notes & documentation for #5062.
I've also noticed that `@cgohlke`'s website includes `fribidi-0.dll`, so this PR adds support for that filename to avoid hassle for users when upgrading.
Also correct information about xcb being included on macos.
> Document Raqm/FriBiDi linking changes

- Tests/test_image_access.py
- src/_imaging.c
Resolves #5048
The issue reports that
```python
px = im.load()
px[numpy.int32(5), numpy.int32(5)]
```
returns
```
TypeError: an integer is required
```
This PR calls `__int__()` on the object passed in, which should provide support for other kinds of objects as well.
> Allow PixelAccess to use Python __int__ when parsing x and y

- Tests/test_image_quantize.py
- src/libImaging/Quant.c
When `quantize()` converts an RGBA image to P mode, it currently translates two pixels with full transparency as different if they have different RGB values. This PR sets all transparent pixels to have the same RGB values as the first transparent pixel, so that they all end up with the same P value.
This improvement is also helpful when it comes to GIFs, which can only mark one color in the palette as transparent. This resolves the second part of #3603
> Set all transparent colors to be equal in quantize()

- src/libImaging/TiffDecode.c
It's duplicated inside following call of TIFFReadTile
Since adding tiff reading using libtiff's TIFFReadRGBA* functions got extracted into it's own code path, there is no need to double check tiles. For more context https://github.com/python-pillow/Pillow/pull/5364#discussion_r603494127
Original commit to fix the CVE added a test image as well: https://github.com/python-pillow/Pillow/commit/cbdce6c5d054fccaf4af34b47f212355c64ace7a
> Remove redundant check (addition to #5364)

- Tests/helper.py
- Tests/test_file_palm.py
- docs/reference/ImageShow.rst
- docs/releasenotes/8.2.0.rst
- src/PIL/ImageShow.py
GraphicsMagick[0] is a "stable/conservative" fork of ImageMagick[1]. It provides the same commands and is almost always interchangable with the corresponding imageMagick command. The ImageMagick command `<im-command> <arguments>` becomes `gm <im-command> <arguments>`, e.g. `convert file.jpg file.png` becomes `gm convert file.jpg file.png`.
This pull request does two things:
* Update the test suite to run with either ImageMagick or GraphicsMagick (only `test_file_palm.py` seems to use it)
* Update `ImageShow` to support `gm display`
[0] http://www.graphicsmagick.org/
[1] http://www.graphicsmagick.org/mission.html
> Add ImageShow support for GraphicsMagick

- Tests/conftest.py
Potential fix for pytest-valgrind mark not defined for non-valgrind docker tests.
> Fix pytest valgrind warnings

- Tests/test_file_jpeg.py
- Tests/test_image_getxmp.py
- docs/releasenotes/8.2.0.rst
- src/PIL/Image.py
- src/PIL/JpegImagePlugin.py
Follow up to #5144
Moved `getxmp()` from Image to JpegImageFile, since the method fetches data from `applist`, which is a JpegImageFile property. Calling this method on a non-JPEG image would have caused an error.
> Move getxmp() to JpegImageFile

- Tests/test_file_dds.py
- src/PIL/BlpImagePlugin.py
- src/PIL/DdsImagePlugin.py
- src/PIL/FtexImagePlugin.py
- src/PIL/IcnsImagePlugin.py
Most Pillow plugins call an `_accept` method as the last argument to `Image.register_open`.
https://github.com/python-pillow/Pillow/blob/ee079ae67e7e24ec789d3cc7d180820a70d32fe6/src/PIL/JpegImagePlugin.py#L823
This PR changes four plugins that don't do that, for consistency.
> Changed register_open calls to be consistent

- Tests/32bit_segfault_check.py
- Tests/check_fli_oob.py
- Tests/check_imaging_leaks.py
- Tests/check_jp2_overflow.py
- Tests/createfontdatachunk.py
- Tests/test_sgi_crash.py
- docs/Guardfile
- selftest.py
- setup.py
Replaces `#!/usr/bin/env python` with `#!/usr/bin/env python3` in shebang lines.
And removes a shebang line from the only `Tests/test_*.py` file that has it.
> Use python3 in shebang line

- Tests/test_file_pdf.py
Fixes https://github.com/python-pillow/Pillow/issues/5392.
* Add a test to check the ReDoS fixed in CVE-2021-25292
* The raised exception isn't relevant
* The important thing is it doesn't timeout aka trigger the ReDoS
> Add test for CVE-2021-25292 ReDoS

- Makefile
- Tests/conftest.py
- Tests/helper.py
- Tests/oss-fuzz/python.supp
- Tests/oss-fuzz/test_fuzzers.py
- Tests/test_file_eps.py
- Tests/test_file_jpeg.py
- Tests/test_file_libtiff.py
- Tests/test_file_pdf.py
- Tests/test_file_png.py
- Tests/test_file_webp_metadata.py
- Tests/test_image.py
- Tests/test_image_resample.py
- Tests/test_image_thumbnail.py
- requirements.txt
- src/decode.c
- src/encode.c
- src/libImaging/Jpeg2KDecode.c
Fixes most of the valgrind XFAILs that we've had, including fixing the non-xfailed test_fuzzers.
> Valgrind fixes

- docs/handbook/image-file-formats.rst
Made sure it is documented that both the `append_images` and `save_all` params must be set. Just setting `append_images` does not work.
Documentation only, [ci skip]
Fixes #5398.
* Updated documentation about the `append_images` param for saving PDFs
* Also made it clear that PIL.Image.Image objects must be pass in as the image list for `append_images`
> Fix PDF file format documentation

- Tests/test_file_gif.py
- src/PIL/GifImagePlugin.py
Resolves #4418. Takes a part of #3434
In `_seek()` in GifImagePlugin,
https://github.com/python-pillow/Pillow/blob/e2ac1d1c3473294c13786c5dc3bc7441dd842215/src/PIL/GifImagePlugin.py#L150-L152
`self.im` is only `None` before the first frame is loaded. After that, there is `self.im` - the image at the time.
So this current code only checks that the image has been loaded at some point in the past. It doesn't check that the previous frame was loaded.
Instead, `self.tile` can be used as an indicator if there is data waiting to be decoded.
> Fixed ensuring that GIF previous frame was loaded

- docs/handbook/concepts.rst
If you look through the types in [Storage.c](https://github.com/python-pillow/Pillow/blob/9b6fe1b039e4a70d59a4f0115df813090bb230f6/src/libImaging/Storage.c#L66), you will find that LA, PA, RGBX, RGBa and La are not IMAGING_TYPE_SPECIAL.
However, in https://pillow.readthedocs.io/en/latest/handbook/concepts.html#modes, these modes are listed as "special modes". 
This PR changes that text to "additional modes" to avoid confusion with IMAGING_TYPE_SPECIAL.
> Changed wording to avoid confusion with IMAGING_TYPE_SPECIAL

- Tests/test_image_resize.py
- src/PIL/Image.py
Helps #4402
#4255 changed the default `resample` argument for `resize()` to BICUBIC, with the goal of being more user-friendly. However, it turned out to not be more user-friendly for IMAGING_TYPE_SPECIAL modes, where we [don't currently support resampling](https://github.com/python-pillow/Pillow/blob/9b6fe1b039e4a70d59a4f0115df813090bb230f6/src/libImaging/Resample.c#L569-L570), except [for NEAREST](https://github.com/python-pillow/Pillow/blob/9b6fe1b039e4a70d59a4f0115df813090bb230f6/src/_imaging.c#L1808-L1822) - leading to the "image has wrong mode" in the issue.
This PR switches back to NEAREST if the image is IMAGING_TYPE_SPECIAL, so that the default `resample` value once again works for those modes.
Looking at the [code](https://github.com/python-pillow/Pillow/blob/9b6fe1b039e4a70d59a4 …
> For special image modes, revert default resize resampling to NEAREST

- src/libImaging/Quant.c
Changed quantize and quantize2 to static, since they are only called from Quant.c
Separated from #5264, because it is independent of that PR. See also https://github.com/python-pillow/Pillow/pull/5367#issuecomment-811616009.
> Changed quantize and quantize2 to static

- Tests/test_imagemorph.py
- src/PIL/ImageMorph.py
ImageMorph features these two lines three times.
https://github.com/python-pillow/Pillow/blob/28eb57888d6906fa57da101d33206daf38553903/src/PIL/ImageMorph.py#L223-L224
`Exception` is very generic, and L is not the only black and white mode that we have - [there is also '1'.](https://pillow.readthedocs.io/en/latest/handbook/concepts.html#modes)
This PR suggests changing it instead to
```python
raise ValueError("Image mode must be L")
```
> Changed ImageMorph incorrect mode errors to ValueError

- src/PIL/IcoImagePlugin.py
Resolves #3773
The report is a user saving an ICO from an RGB image, and it not appearing in Windows. The solution turned out to be saving an RGBA image instead.
This adds a note about that to the docstring.
> Added info about mode when saving ICO for Windows

- Tests/test_file_tiff_metadata.py
- src/PIL/TiffTags.py
Resolves #2278
The issue reports that a TIFF image cannot be opened and saved - `AttributeError: 'tuple' object has no attribute 'ljust'`. The problem comes from tag 33723 - https://www.awaresystems.be/imaging/tiff/tifftags/iptc.html
https://github.com/python-pillow/Pillow/blob/ab8955b48e84b18c578d165e7d10868794311ce2/src/PIL/TiffTags.py#L181
Loading and saving existing test image hopper.Lab.tif currently triggers the same bug.
This PR changes the tag length to 1, allowing the image to save without an error.
It also produces nicer values for the tag.
```python
im = Image.open("00000001.tif")
print(im.tag_v2[33723])
im = Image.open("Tests/images/hopper.Lab.tif")
print(im.tag_v2[33723])
```
Currently gives
``` …
```
> Changed TIFF tag 33723 length to 1

- Tests/test_file_pdf.py
- src/PIL/PdfImagePlugin.py
Resolves #1775 - the remaining part of that issue is a request for compression when saving 1-bit PDFs.
The issue reports that
```python
img = Image.new("1", (1400, 2000))
img.save("out.pdf")
```
generates a 5mb file.
Changing the filter to "DCTDecode", it becomes 34kb instead.
I've modified a test to ensure that saving `hopper("1")` as a PDF, that currently creates a 34kb file, stays below 15kb.
> Switched to saving 1-bit PDFs with DCTDecode

- .ci/install.sh
- .github/workflows/macos-install.sh
- .github/workflows/test.yml
Fix the failures on Python 3.10 in master - https://github.com/python-pillow/Pillow/runs/2431607308 - by changing the Python 3.10 version to be static at alpha.7
The failures do not come from Pillow, but from pytest - https://github.com/pytest-dev/pytest/issues/8539
> Fixed Python 3.10 at alpha.7

- docs/handbook/image-file-formats.rst
- src/PIL/WebPImagePlugin.py
Resolves #4786
When #4547 added the "method" argument to single frame WebP saving, it used our existing "method" default for multiple frame WebP saving - 0.
However, WebP sets "method" to 4 by default - https://chromium.googlesource.com/webm/libwebp/+/refs/heads/master/src/enc/config_enc.c#34 - so we changed the "method" that was used if none was specified by the user.
This PR changes it to 4 to line up with WebP's default.
> Changed WebP default "method" value to 4

- .github/workflows/test-windows.yml
* `pypy-3.7` is now 64-bit, update matrix to reflect this
* `include` PyPy instead of `excluding` it to simplify matrix
* remove unused matrix variables `platform-vcvars` and `platform-msbuild`
> GHA: Update test-windows for 64-bit PyPy 7.3.4 release

- .ci/install.sh
- .github/workflows/macos-install.sh
- .github/workflows/test.yml
Reverts python-pillow/Pillow#5447.
I wrote at https://github.com/pytest-dev/pytest/issues/8539#issuecomment-829943392:
---
Good news, the GitHub Actions weirdness has been resolved and latest pytest is working with `3.10-dev` ([example build from today](https://github.com/python-pillow/Pillow/runs/2474120077?check_suite_focus=true)). 🎈 
What happened:
Something caused a premature Python-3.10.0b1.tgz to be released on the Python FTP servers (now removed): https://www.python.org/ftp/python/3.10.0/Python-3.10.0b1.tgz.
GitHub Actions' automation integrated this into `3.10-dev`. This has also been removed and `3.10-dev` now points to the latest 3.10 alpha, in advance of next week's real 3.10 beta release.
More details:
* https://github.com/actions/setup-python/issues/207
* …
> Revert "Fixed Python 3.10 at alpha.7": use 3.10-dev

- src/decode.c
https://github.com/python-pillow/Pillow/blob/256372724b6648a94234fcb989bf696285edd3a0/src/decode.c#L298-L301
https://github.com/python-pillow/Pillow/issues/4818#issuecomment-725201654 suggests that "unknown raw mode" is not completely descriptive here. This is a fair comment - it's not that the raw mode is unknown, it's that our list of unpackers doesn't have a mapping from the raw mode to the mode. The particular raw mode may be valid for other modes.
So this PR changes the text, mostly using the suggestion from the comment.
> Clarified error message

- Tests/test_imageops.py
- docs/reference/ImageOps.rst
- docs/releasenotes/8.3.0.rst
- docs/releasenotes/index.rst
- src/PIL/ImageOps.py
Resolves #5415
Adds a `contain()` method to ImageOps. I would describe it as the inverse of `fit()`.
Running this code for each method in turn for comparison -
```python
from PIL import Image, ImageOps
im = Image.open("Tests/images/hopper.png")
ImageOps.fit(im, (200, 300))
```
|       | Fit                                                                                                        | Pad                                                                                                        | Contain                                                                                                        |
| ----- | ---------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------- …
> Added ImageOps contain()

- Tests/test_file_pdf.py
- src/PIL/PdfImagePlugin.py
- src/PIL/PdfParser.py
Resolves #3565
The issue reports that the `resolution` argument when saving PDFs does not appear correctly when opening the resulting PDF in commercial software.
[Crunching the numbers](https://github.com/python-pillow/Pillow/issues/3565#issuecomment-830484468), this is because of rounding that is used by Pillow when saving a PDF.
https://github.com/python-pillow/Pillow/blob/676f4dbefb22c349c2f78f4f6aabf26e00d5efc2/src/PIL/PdfImagePlugin.py#L202-L217
Searching for whether rounding needs to be used, I'm able to use GIMP to export a PDF with MediaBox float values, and I see an example at https://books.google.com.au/books?id=JJN_BAAAQBAJ&pg=PA102#v=onepage&q&f=false. As for `page_contents`, I see float values on page 287 of https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/pdf_referen …
> Do not round dimensions when saving PDF

- Tests/test_file_tiff_metadata.py
- src/PIL/TiffImagePlugin.py
```python
im = Image.open("Tests/images/hopper.tif")
im.tag_v2[45059] = b"test"
print(im.tag_v2[45059])  # (b'test',)
im.tag_v2[45059] = im.tag_v2[45059]
print(im.tag_v2[45059])  # ((b'test',),)
```
I would maintain that this should not be the case, so this PR fixes that.
What is special about this tag is that it is UNDEFINED with length 0.
https://github.com/python-pillow/Pillow/blob/ab8955b48e84b18c578d165e7d10868794311ce2/src/PIL/TiffTags.py#L192
The value of an UNDEFINED tag is always turned into a list in `_setitem` - meaning that if it is already a sequence, it gets wrapped again.
https://github.com/python-pillow/Pillow/blob/ab8955b48e84b18c578d165e7d10868794311ce2/src/PIL/TiffImagePlugin.py#L566-L569
And because the length is 0, at the end of `_setitem` it …
> Fixed UNDEFINED TIFF tag of length 0 being changed in roundtrip

- Tests/test_file_png.py
- Tests/test_psdraw.py
- docs/handbook/tutorial.rst
- docs/reference/ImageDraw.rst
- src/PIL/EpsImagePlugin.py
- src/PIL/Image.py
- src/PIL/ImageFile.py
- src/PIL/PSDraw.py
Resolves #5436
https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#example-draw-a-gray-cross-over-an-image
```python
from PIL import Image, ImageDraw
with Image.open("hopper.jpg") as im:
draw = ImageDraw.Draw(im)
draw.line((0, 0) + im.size, fill=128)
draw.line((0, im.size[1], im.size[0], 0), fill=128)
im.save(sys.stdout, "PNG")
```
However, running this example code gives
```
File "<stdin>", line 6, in <module>
File "PIL/Image.py", line 2172, in save
save_handler(self, fp, filename)
File "PIL/PngImagePlugin.py", line 1223, in _save
fp.write(_MAGIC)
TypeError: write() argument must be str, not bytes
```
This PR suggests fixing this by changing `im.save` so that if it is passed `sys.stdout` (`sys.stdout.mode` is 'w'), then it is replaced with …
> Replace sys.stdout with sys.stdout.buffer when saving

- src/_imagingft.c
gcc's cpp doesn't short-circuit when RAQM_VERSION_ATLEAST is undefined
so building fails on systems with old libraqm (e.g. Debian 10 for
raspberry pi where wheels w/libraqm support may not be available).
RAQM_VERSION_ATLEAST was introduced with 0.7.0, so the test is
effectively equivalent.
> Fix build with libraqm < 0.7.0

- src/PIL/TiffImagePlugin.py
`Self.legacy_api` and `_Tags_v2` are incorrect code due to capitalisation, and `tags_v1` is missing a leading underscore.
> Corrected code references in docstring

- Tests/test_file_libtiff.py
- src/PIL/TiffImagePlugin.py
https://github.com/python-pillow/Pillow/blob/56730906f2e0262cb2528287635c03c3fab128cf/src/PIL/TiffImagePlugin.py#L1062-L1064
This code is currently not run when seeking backwards. Moving it so that it is, I find that it fixes #5440
> Reset handle when seeking backwards in TIFF

- src/decode.c
- src/libImaging/TiffDecode.c
- src/libImaging/TiffDecode.h
When [compiling on macOS](https://github.com/python-pillow/Pillow/runs/2474943233#step:9:52), deprecation warnings for TIFF have started appearing.
```
In file included from src/decode.c:491:
src/libImaging/TiffDecode.h:35:5: warning: 'uint32' is deprecated [-Wdeprecated-declarations]
uint32 ifd; /* offset of the ifd, used for multipage
^
/usr/local/Cellar/libtiff/4.3.0/include/tiff.h:84:45: note: 'uint32' has been explicitly marked deprecated here
typedef TIFF_MSC_DEPRECATED uint32_t uint32 TIFF_GCC_DEPRECATED;
^
/usr/local/Cellar/libtiff/4.3.0/include/tiff.h:66:44: note: expanded from macro 'TIFF_GCC_DEPRECATED'
#define TIFF_GCC_DEPRECATED __attribute__((deprecated))
^
```
This is because of https://gitlab.com/libtiff/libtiff/-/merge_requests/205
This PR resolves the warnings by …
> Replaced uint16 and uint32 with uint16_t and uint32_t to resolve TIFF deprecations

- Tests/test_file_png.py
- Tests/test_psdraw.py
Fixes errors introduced by #5437
In the PNG test for example,
https://github.com/python-pillow/Pillow/blob/8354fa4929ffd55b01ee78353f15917e1a0a1425/Tests/test_file_png.py#L718
is followed by
https://github.com/python-pillow/Pillow/blob/8354fa4929ffd55b01ee78353f15917e1a0a1425/Tests/test_file_png.py#L734-L735
This does not restore the original setting correctly.
> Corrected errors in restoring sys.stdout in tests

- Tests/test_file_webp.py
- src/_webp.c
Resolves #5461
Provides more information to the user on a WebP encoding error by including the error code - changing from "encoding error" to "encoding error 6", for example.
> Include code in WebP error

- .ci/install.sh
It is no longer necessary to manually upgrade setuptools on GitHub Actions Ubuntu to allow tests to pass.
> Removed GitHub Actions Ubuntu setuptools version requirement

- README.md
- docs/index.rst
At the moment, one of our badges is 'macOS build'. It links to Travis CI, which does not contain our macOS jobs.
Instead, this PR adds in a 'Wheels' badge for pillow-wheels GHA and renames the Travis CI badge to 'aarch64 wheels'.
> Updated badges for wheels

- Tests/test_imagedraw.py
- src/libImaging/Draw.c
> Remove spikes when drawing thin pieslices

- .github/workflows/test.yml
- docs/conf.py
- docs/installation.rst
- requirements.txt
* Add a couple of useful Sphinx plugins, as recommended by https://pradyunsg.me/furo/recommendations/
* [sphinxext-opengraph](https://github.com/wpilibsuite/sphinxext-opengraph): adds OpenGraph metadata (https://ogp.me), makes previews better on Facebook and Twitter (probably helps Google results too)
* [sphinx-copybutton](https://github.com/executablebooks/sphinx-copybutton): adds a copy button to code snippets, to make it easy to copy them and try them out
* Plus use code formatting for some text on the installation page
For example, These tags are inserted into the tutorial page:
```html
<meta property="og:title" content="Tutorial" />
<meta property="og:type" content="website" />
<meta property="og:url" …
```
> Build docs with sphinx_copybutton and sphinxext.opengraph

- src/PIL/TiffTags.py
> Added CFAPattern, ExifVersion and FlashpixVersion UNDEFINED tags

- Tests/test_image_array.py
- src/PIL/Image.py
Resolves #5084
The following code runs without raising an error.
```python
import numpy as np
im = Image.open("Tests/images/truncated_jpeg.jpg")
np.array(im)
```
Even though an OSError is raised if `__array_interface__` is accessed directly.
```python
im = Image.open("Tests/images/truncated_jpeg.jpg")
im.__array_interface__
```
This is a [bug in numpy](https://gitter.im/numpy/numpy?at=6067b4ef3153ce63a3b6dcad).
This PR works around that bug by replacing `__array_interface__` with `__array__`.
> Allow converting an image to a numpy array to raise errors

- Tests/test_image_access.py
- src/_imaging.c
Resolves #5503
The issue requests that the error if `ink` has an incorrect number of bands be clearer than the default "TypeError: function takes exactly 1 argument (3 given)".
This PR adds error messages similar to https://github.com/python-pillow/Pillow/blob/16b9cadd419b0554c604bfc20a888cc55a78f12a/src/_imaging.c#L519
not just for 1 band images as mentioned in the issue, but also for other similar situations in the same C function.
While I'm here, I'm also replacing
https://github.com/python-pillow/Pillow/blob/16b9cadd419b0554c604bfc20a888cc55a78f12a/src/_imaging.c#L501
with `PyTuple_Check(color) && PyTuple_GET_SIZE(color) == 1`, since we have already performed the [error checking](https://docs.python.org/3/c-api/tuple.html#c.PyTuple_Size) with `PyTuple_Check`.
> Added specific error messages when ink has incorrect number of bands

- src/PIL/ImageShow.py
First of all, thanks for maintaining Pillow all these years!
When Image.show() displays an image on Linux using eog, there's a race condition where the file can get deleted before eog opens it.
To reproduce this, you'll need a Linux system without imagemagick or graphicsmagick installed.  Then you can make it happen pretty reliably, just by calling Image.show() several times:
```python
im = Image.new('RGB', (400, 300), 'green')
for i in range(4):
im.show()
```
With imagemagick installed, this correctly displays four green boxes.  But if you're using eog, usually several of the images will give error messages like "No images found in file:///tmp/tmprt8btbpr.PNG" instead.
This happens because Image.show() expects its display command to run synchronously, but in fact …
> Avoid race condition when displaying images with eog

- winbuild/build_prepare.py
Fixes CI failures for Windows
For some unknown reason the "Build" target is indeed non-existant for the lcms2_static project, but VC2017 only (even when specified)! `msbuild Projects\VC2019\lcms2.sln /t:lcms2_static ` works :/
> Fix lcms2_static target for msbuild

- Tests/test_file_ico.py
- docs/handbook/image-file-formats.rst
- docs/releasenotes/8.3.0.rst
- src/PIL/IcoImagePlugin.py
Resolves #2512
ICO can either be a container for [PNG or BMP](https://en.wikipedia.org/wiki/ICO_(file_format)).
Pillow has been saving ICOs only in the PNG format. This PR adds support for saving ICOs with the BMP format, largely by reversing the process that we use to load the BMP format. It would be called with ``im.save("out.ico", bitmap_format="bmp")``
> Added ICO saving in BMP format

- Tests/test_imagefont.py
- src/PIL/ImageDraw.py
Resolves #5506 by raising a specific error if `textbbox()` is used without a TrueType font.
> Raise an error if ImageDraw.textbbox is used without a TrueType font

- docs/resources/css/dark.css
Fixes differently colored blocks in the right sidebar in the dark mode docs.
For comparison, see the following two images:
Before fix (current situation):
After fix:
Change proposed in this pull request:
* Make the `background-color` of the top part of the right sidebar in the docs darker when in dark mode to match the rest of the right sidebar
> Fix differing background colors in right sidebar in dark mode docs

- src/libImaging/Imaging.h
Pointed out in #5526. Currently, for `a`,
https://github.com/python-pillow/Pillow/blob/61b9065a25aaeefdca19940448b21b02f1e6766a/src/libImaging/Imaging.h#L364-L375
does not match
https://github.com/python-pillow/Pillow/blob/61b9065a25aaeefdca19940448b21b02f1e6766a/src/libImaging/Geometry.c#L1126-L1137
This PR fixes that, updating the declaration.
> Updated declaration to match definition

- docs/handbook/image-file-formats.rst
Resolves #5527
The issue is from a user expecting a copy of an image instance to retain the format of the original - as has happened before in #4571. This PR documents that this is not the case.
> Copies of an image do not retain the format

- src/libImaging/TiffDecode.c
Helps #5526
In master at the moment, there is a warning at https://github.com/python-pillow/Pillow/runs/2757774272?check_suite_focus=true#step:9:112
```
src/libImaging/TiffDecode.c:59:60: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 3 has type ‘toff_t’ {aka ‘long unsigned int’} [-Wformat=]
59 |         TIFFError("_tiffReadProc", "Invalid Read at loc %llu, eof: %llu", state->loc, state->eof);
```
If I try to fix that by changing it to '%lu', it fixes [that job](https://github.com/radarhere/Pillow/runs/2792080183?check_suite_focus=true#step:9:108), but [starts failing in another -](https://github.com/radarhere/Pillow/runs/2792080454?check_suite_focus=true#step:9:123)
```
src/libImaging/TiffDecode.c:59:73: warning: format specifies type 'unsigned …
```
> Fixed format warning

- Tests/oss-fuzz/fuzz_font.py
- Tests/oss-fuzz/fuzz_pillow.py
- Tests/oss-fuzz/fuzzers.py
- Tests/oss-fuzz/test_fuzzers.py
- Tests/test_decompression_bomb.py
Helps #5526
With pytest-randomly installed, Tests/test_decompression_bomb.py can fail, because we are currently setting `Image.MAX_IMAGE_PIXELS` in three methods, and not resetting it until the tests in TestDecompressionBomb are done in `teardown_class`.
This PR instead resets it after each method.
> Fixed errors when running tests in random order

- Tests/test_file_jpeg2k.py
- Tests/test_imagefile.py
- src/libImaging/Jpeg2KEncode.c
Resolves #3161
A simple version of the problem in that issue is
```python
image = Image.new("RGB", (1, 1))
image.save("test.j2k")
```
At the moment, it gives "OSError: encoder error -2 when writing image file".
Debugging, OpenJPEG is trying to say that the ["Number of resolutions is too high in comparison to the size of tiles"](https://github.com/uclouvain/openjpeg/blob/cc1919b183f76d5ac79cc9927fb899b47700d925/src/lib/openjp2/j2k.c#L8648-L8653).
So this PR decreases the number of resolutions to work - unless the user explicitly set `num_resolutions` through a save argument.
If you're wondering where `numresolution` is set if Pillow's Python code isn't setting it, the default value for `numresolution` is [6 in …
> Fixed default numresolution for small JPEG2000 images

- Tests/test_imageops.py
- src/PIL/ImageOps.py
Resolves #5546
The instance points out that in [`exif_transpose()`](https://github.com/python-pillow/Pillow/blob/384a4bf01ec8d631dcde2c3246bd08e37fa1b7cd/src/PIL/ImageOps.py#L560-L584),
```python
exif = image.getexif()
...
del exif[0x0112]
transposed_image.info["exif"] = exif.tobytes()
```
we're deleting the orientation data from the original image's EXIF object (and then, as intended, saving it to the new image instance).
Instead, this PR changes it to
```python
exif = image.getexif()
...
transposed_exif = transposed_image.getexif()
del transposed_exif[0x0112]
transposed_image.info["exif"] = transposed_exif.tobytes()
```
so that we are deleting the orientation data from the new image's EXIF object only, leaving the original image unaffected.
> Do not modify EXIF of original image instance in exif_transpose()

- Tests/test_file_tga.py
- src/PIL/Image.py
- src/_imaging.c
Resolves #4830
The image from that issue has a [BGR;15 palette](https://github.com/python-pillow/Pillow/blob/384a4bf01ec8d631dcde2c3246bd08e37fa1b7cd/src/PIL/TgaImagePlugin.py#L115-L117). So when PngImagePlugin tries to calculate the number of colors to use when saving for `show()`,
https://github.com/python-pillow/Pillow/blob/384a4bf01ec8d631dcde2c3246bd08e37fa1b7cd/src/PIL/PngImagePlugin.py#L1195
the assumption, that it can divide by 3 because this is RGB, is false.
This PR adds a change to Image, so that when it sets the palette mode to RGB, there is actually RGB data in the palette string.
> Ensure palette string matches RGB mode

- Tests/test_imageops.py
- src/PIL/ImageOps.py
Helps #5375
`ImageOps.expand()` returns a new image instance, to allow for the larger size.
However, it doesn't copy the palette, causing the image to become grayscale.
> Copy palette to new images in ImageOps expand

- Tests/test_file_tiff_metadata.py
- src/PIL/TiffImagePlugin.py
Resolves #5555
In [TiffImagePlugin](https://github.com/python-pillow/Pillow/blob/70ef50cf72992ab6c9330412d6f1340c593e2d8f/src/PIL/TiffImagePlugin.py#L823), `values` might not be defined when it is comes to be used in logging.
```python
if is_ifd:
...
else:
values = value if isinstance(value, tuple) else (value,)
...
...
msg += " - value: " + (
"<table: %d bytes>" % len(data) if len(data) >= 16 else str(values)
)
```
This PR fixes it by ensuring that `values` is always defined.
> Fixed undefined variable in logging

- Tests/test_file_gif.py
If you look at this code
https://github.com/python-pillow/Pillow/blob/3d2f3baa4c8258aeb3dac3a124f5ee5ab4bfa9c1/Tests/test_file_gif.py#L411-L420
it is apparent that the comments are not accurate - `circles` is not the background color of the image, and the circle being drawn in the middle is not always red.
This PR updates the comments to fix that.
> Corrected comments

- Tests/test_file_tiff.py
- Tests/test_image.py
- src/PIL/Image.py
Helps #4940
The issue expected "To be able to access exif tags of my tiff files".
https://en.wikipedia.org/wiki/Exif#Technical
> When Exif is employed in TIFF files (also when used as "an embedded TIFF file" mentioned earlier), the TIFF Private Tag 0x8769 defines a sub-Image File Directory (IFD) that holds the Exif specified TIFF Tags. In addition, Exif also defines a Global Positioning System sub-IFD using the TIFF Private Tag 0x8825, holding location information, and an "Interoperability IFD" specified within the Exif sub-IFD, using the Exif tag 0xA005.
So at top level, there are two IFDs - Exif and GPS.
Then what should existing method `getexif()` do for a TIFF image?
One could argue that it should just get the Exif IFD... but then how do users get to the GPS IFD?
One could then argue …
> Allow getexif() to access TIFF tag_v2 data

- Tests/test_file_tiff.py
- Tests/test_tiff_ifdrational.py
- src/PIL/TiffImagePlugin.py
This one is up for debate.
Consider this behaviour.
```pycon
>>> 7 / 5
1.4
>>> from PIL.TiffImagePlugin import IFDRational
>>> IFDRational(7, 5) == 1.4
False
```
I feel like this is unexpected. Why is this happening? Well,
```pycon
>>> IFDRational(7, 5)._val
Fraction(7, 5)
>>> from fractions import Fraction
>>> Fraction(7, 5) == 1.4
False
```
So despite the fact that
```pycon
>>> float(Fraction(7, 5)) == 1.4
True
```
`Fraction(7, 5)` is not equal to 1.4.
This isn't the case for all values.
```pycon
>>> Fraction(5, 4) == 1.25
True
```
This PR 'fixes' this behaviour in `IFDRational` by casting `Fraction` to `float` when comparing in `IFDRational.__eq__()`.
As I said, open for debate.
> Convert to float for comparison with float in IFDRational __eq__

- Tests/test_file_jpeg.py
- Tests/test_file_png.py
- Tests/test_file_tiff.py
- src/PIL/Image.py
- src/PIL/ImageFile.py
- src/PIL/JpegImagePlugin.py
- src/PIL/PngImagePlugin.py
- src/PIL/TiffImagePlugin.py
Resolves #5454 by correcting how JPEG getxmp() descends into XML
Resolves #5531 by adding `getxmp()` methods for PNG and TIFF
> Improved getxmp()

- Tests/test_file_dds.py
- docs/handbook/image-file-formats.rst
- src/PIL/DdsImagePlugin.py
Helps #4864 by adding DDS saving. https://docs.microsoft.com/en-us/windows/win32/direct3ddds/dds-header was used as a reference.
Also, a minor cleanup change. Uses this existing line
https://github.com/python-pillow/Pillow/blob/45003b78ed4003f6bf68e3a921b78539a64c7337/src/PIL/DdsImagePlugin.py#L50
to make
https://github.com/python-pillow/Pillow/blob/45003b78ed4003f6bf68e3a921b78539a64c7337/src/PIL/DdsImagePlugin.py#L130-L131
clearer.
```python
if pfflags & DDPF_RGB:
```
> Add DDS saving

- Tests/test_file_apng.py
- Tests/test_file_gif.py
- Tests/test_image.py
- Tests/test_image_convert.py
- Tests/test_imageops.py
- Tests/test_imagepalette.py
- src/PIL/GifImagePlugin.py
- src/PIL/Image.py
- src/PIL/ImageDraw.py
- src/PIL/ImageOps.py
- src/PIL/ImagePalette.py
- src/PIL/PyAccess.py
- src/PIL/WebPImagePlugin.py
This PR has several changes
- the ImagePalette `colors` dictionary is currently empty when the object is created, rather than being filled with palette entries. This fixes that
- it changes the palette to be empty by default. This means that new colors can be appended more easily, rather than finding that all 256 entries are already occupied
- if a new color is added when 256 entries are taken, search through the image. If there is a palette index that isn't actually used, use that for the new color
- helps #5375 by determining the border palette index on the new image only after the palette has been attached
Edit: Thanks to later commits, resolves #2803
> Improved ImagePalette

- Tests/test_file_tiff_metadata.py
- src/PIL/TiffImagePlugin.py
- src/PIL/TiffTags.py
Resolves #5553
At the moment, our [list of tag data](https://github.com/python-pillow/Pillow/blob/70ef50cf72992ab6c9330412d6f1340c593e2d8f/src/PIL/TiffTags.py#L74) is 1 dimensional. It doesn't account for the fact that tags actually exist in different groups - see https://exiftool.org/TagNames/EXIF.html
This PR adds `TAGS_V2_GROUPS`, which is used when the tag in question is part of a group.
#5553 mentions that the wrong type is used for InteropVersion, part of the InteropIFD. The type information for that tag is added here.
> Added tag data for IFD groups

- src/PIL/ImageFilter.py
* The argument for `GaussianBlur` is `radius`. The canonical name for the parameter is standard deviation. The value for the standard normal distribution at a given radius is a function of standard deviation.
* `GaussianBlur` doesn't convolve the image with a Gaussian kernel. It uses a kernel that when applied iteratively approximates a Gaussian kernel.
The changes improve the precision of the documentation.
> Modified docstring for GaussianBlur

- Tests/test_imageops.py
- src/PIL/ImageOps.py
Resolves #5375
After #5552, running the code from that issue, there is a unintended line on the right and bottom of the image.
https://github.com/python-pillow/Pillow/blob/28330c2f9db518f8c8eccd394cc2990e3ffec2e3/src/PIL/ImageOps.py#L402
I would have just forgotten that
https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.ImageDraw.rectangle
> The second point is just outside the drawn rectangle.
Fixing that, I get
> Corrected border position for P mode in ImageOps.expand()

- setup.py
Will show it in the sidebar at https://pypi.org/project/Pillow/:
> Add Twitter to PyPI project URLs

- .ci/install.sh
- .github/workflows/macos-install.sh
- .github/workflows/test-windows.yml
- Tests/test_file_jpeg.py
- Tests/test_file_png.py
- Tests/test_file_tiff.py
- docs/releasenotes/8.3.0.rst
- requirements.txt
- src/PIL/Image.py
- src/PIL/JpegImagePlugin.py
- src/PIL/PngImagePlugin.py
- src/PIL/TiffImagePlugin.py
https://docs.python.org/3/library/xml.etree.elementtree.html
> Warning The xml.etree.ElementTree module is not secure against maliciously constructed data. If you need to parse untrusted or unauthenticated data see XML vulnerabilities.
`xml.etree.ElementTree` is in use in `getexif()` and now `getxmp()`. So the earliest Pillow version affected is 7.2.0
The Python docs later recommend defusedxml.
> **The defusedxml Package**
> defusedxml is a pure Python package with modified subclasses of all stdlib XML parsers that prevent any potentially malicious operation. Use of this package is recommended for any server code that parses untrusted XML data.
So this PR replaces `xml.etree.ElementTree` in `getxmp()` with `defusedxml.ElementTree`. If it is not installed, an empty dictionary is returned …
> Replaced xml.etree.ElementTree

- Tests/test_imagepalette.py
- src/PIL/ImagePalette.py
Resolves #4202
When the code from that issue calls `getcolor()` to find a new color to draw with, it picks 255. However, the image from that issue has an `info["transparency"]` of 255. So Pillow draws with the transparency index, which produces unexpected results.
This PR skips the background and transparency index when calling `getcolor()` to prevent this.
> Do not use background or transparency index for new color

- Tests/test_file_libtiff.py
- src/PIL/TiffImagePlugin.py
Adresses #5370 partly.
Doesn't really "fix" the loading of any existing >2GB single strip images (would need to handle specially by buffered read in decoder), but reduces their incidence as recommended by the TIFF spec.
> Limit TIFF strip size when saving with libtiff

- Tests/test_image_array.py
- src/PIL/Image.py
This is required by the numpy protocol.
Fixes #5571
> Make Image.__array__ take optional dtype argument

- src/PIL/ImageFile.py
Resolves #5583
Catches an OSError raised by mod_wsgi.
> Catch OSError when checking if fp is sys.stdout

- Tests/test_file_apng.py
- src/PIL/PngImagePlugin.py
Resolves #5608 
This issue is caused by the 'duration' variable being overwritten.
https://github.com/python-pillow/Pillow/blob/83c05aaf8daa930086257eb38b254f06808d13e5/src/PIL/PngImagePlugin.py#L1120
After being overwritten, the duration variable is not updated.
https://github.com/python-pillow/Pillow/blob/83c05aaf8daa930086257eb38b254f06808d13e5/src/PIL/PngImagePlugin.py#L1083-L1084
> Fixed error saving APNG with duplicate frames and different duration times

- Tests/test_file_libtiff.py
- src/PIL/TiffImagePlugin.py
> Ensure TIFF RowsPerStrip is multiple of 8 for JPEG compression

- Tests/test_imageops.py
- src/PIL/ImageOps.py
https://github.com/python-pillow/Pillow/pull/5552/commits/b6b362c80718eeee122e9d346758d18335d66b2a changed `expand()` so that for a P image in `ImageOps.expand()`, the border color is only filled after attaching the palette.
Instead, this PR create a copy of the palette (to avoid modifying the original), calculates the new palette index from that, and then sets the new palette index as the background of the image.
This brings the logic for P and non-P images in `ImageOps.expand()` closer together, and resolves #5614 in the process. In that issue, drawing a single rectangle wasn't able to accomodate a multiple border widths being passed in a tuple. This PR removes the rectangle drawing altogether, fixing that.
> Fixed ImageOps expand with tuple border on P image

- src/PIL/ImagePalette.py
Helps #5636
The documentation for the ImagePalette `size` parameter hasn't been correct since it was added in #1381.
> Corrected ImagePalette size parameter documentation

- Tests/test_file_libtiff.py
- src/PIL/TiffImagePlugin.py
- src/encode.c
Resolves #5589
Ensures that tags 530 and 532 are present when saving a YCbCr TIFF.
> Added tags when saving YCbCr TIFF

- Tests/test_file_webp.py
- src/PIL/WebPImagePlugin.py
Resolves #5600
The issue found that `im.save("out.webp", icc_profile=None)` failed with an error. This PR allows a `None` value.
> Allow saving WebP with icc_profile None

- Tests/test_imagepalette.py
- docs/deprecations.rst
- src/PIL/ImagePalette.py
Resolves #5636
The `size` parameter was originally added in #537. Before #5552, it was there to override a default length check.
https://github.com/python-pillow/Pillow/blob/10615a7da7a5254de9696f4f3f14d229098b67cc/src/PIL/ImagePalette.py#L45-L48
Afterwards though, the default length check was gone, so `size` is now just adding an arbitrary constraint on the user - if provided, it throws an error if `palette` parameter is not the length of the `size` parmeter.
https://github.com/python-pillow/Pillow/blob/3462b5fd74e5e86539e7fa639adf4a52d53bf57c/src/PIL/ImagePalette.py#L43-L44
> Deprecate ImagePalette size parameter

- Tests/test_file_sgi.py
- src/PIL/SgiImagePlugin.py
* SGI save handler should not close output stream
> Do not close file pointer in SGI save handler

- Tests/test_image_convert.py
- src/PIL/Image.py
Helps #5593, fixing the first problem in that issue.
If calling `convert()` without specifying the mode on a P image, the mode chosen is [either the palette mode or RGB.](https://github.com/python-pillow/Pillow/blob/5fe583598fd7a96514abec669b1bf5f7676aeb57/src/PIL/Image.py#L917-L922)
This PR detects if the image has `info["transparency"]`, and if it does, chooses RGBA instead.
> If default conversion from P is RGB with transparency, convert to RGBA

- Tests/test_image.py
- src/PIL/Image.py
Resolves #5632
As #3825 did for `open()`, this fixes detecting pathlib.Path in `save()`.
https://github.com/python-pillow/Pillow/blob/68c5f2dce11768e5334a97d17feb2a85a0fd0590/src/PIL/Image.py#L2183-L2188
The above code will never execute the second block, because `isPath` returns true for `Path` instances.
https://github.com/python-pillow/Pillow/blob/68c5f2dce11768e5334a97d17feb2a85a0fd0590/src/PIL/_util.py#L5-L6
So this PR swaps the order.
> Corrected pathlib.Path detection when saving

- src/libImaging/Access.c
Companion to https://github.com/python-pillow/pillow-scripts/pull/6
> Updated location of make_hash script

- .ci/install.sh
- CHANGES.rst
Wheel now works on Python 3.10 so we can install PyQt5 there.
We can also install `wheel` early on in the CI. This avoids legacy 'setup.py install' for packages that only have sdists and no wheels, and then stores the wheel in the cache for the next run.
```
Using legacy 'setup.py install' for cffi, since package 'wheel' is not installed.
...
Using legacy 'setup.py install' for olefile, since package 'wheel' is not installed.
```
The cache isn't there for new branches, but will help `master` and updates to feature branches.
---
NumPy is also buildable for 3.10 now, so we _could_ remove this:
```sh
if ! [ "$GHA_PYTHON_VERSION" == "3.10-dev" ]; then python3 -m pip install numpy ; fi
```
But it takes about 5-6 minutes to build from sdist (3.10 only, others have wheels). It will be stored in …
> CI: Install PyQt5 on Python 3.10

- docs/installation.rst
https://github.com/python-pillow/Pillow/blob/master/docs/installation.rst#freebsd-installation
> pkg install py36-pillow
The way that I read https://www.freshports.org/graphics/py-pillow/, py36-Pillow only has Pillow 5.0, and py37-Pillow only has Pillow 7.0. py38-Pillow is the most up-to-date, with Pillow 8.2.
This PR updates our documentation to list py38-Pillow as the FreeBSD package. Also helpful as we're planning to drop Python 3.6 support at the end of the year.
> Updated FreeBSD package install command to Python 3.8

- Tests/test_image_transform.py
- src/PIL/Image.py
> Copy palette to new image in transform()

- Tests/test_image_convert.py
- src/PIL/Image.py
Resolves #5593, fixing the second problem in that issue.
At the moment, there is code in `convert()` to keep transparency when going from P to RGBA.
https://github.com/python-pillow/Pillow/blob/be30792714bbea84d21335350f4cd71146491532/src/PIL/Image.py#L1008-L1017
This PR expands the condition to do the same if going from P to LA or PA as well.
> Keep transparency when converting from P to LA or PA

- src/PIL/Image.py
Resolves #1280 by better documenting the range of raw modes that `im.putpalette()` can accept. It does not only accept RGB or RGBA, but also [any raw mode that can be unpacked to RGB](https://github.com/python-pillow/Pillow/blob/68c5f2dce11768e5334a97d17feb2a85a0fd0590/src/libImaging/Unpack.c#L1516-L1544).
This means that the limit for the length of `data` is not just 768 or 1024. Since the limit is the number of channels multiplied by 256, for "R", it is 256.
```python
>>> im = Image.new("L", (1, 1))
>>> im.putpalette((1,)*256, "R")
>>> im.putpalette((1,)*257, "R")
File "PIL/Image.py", line 1776, in putpalette
self.load()  # install new palette
File "PIL/Image.py", line 838, in load …
```
> putpalette() rawmode may be modes that can be unpacked to RGB

- Tests/test_file_gif.py
- src/PIL/GifImagePlugin.py
Resolves #3788
At the moment,
```python
im.save("output.gif", save_all=True, palette=palette.palette)
```
will include the palette with each frame of the GIF. This PR instead includes the palette in the global header, and none of the frames. This is a measure to reduce the filesize, so it helps #617
> For GIF save_all with palette, do not include palette with each frame

- Tests/test_file_tiff.py
- src/PIL/TiffImagePlugin.py
Resolves #4804
TIFF tag 262 is [PhotometricInterpretation](https://www.awaresystems.be/imaging/tiff/tifftags/photometricinterpretation.html). Pillow currently does not allow this value to be set when saving. Changing the value for mode 1 images means that white becomes black and vice versa, so to keep the output the same, we need to invert the pixel values.
This PR allows for that specific scenario, inverting the values when saving.
> Allow saving 1 and L mode TIFF with PhotometricInterpretation 0

- docs/handbook/image-file-formats.rst
Resolves #5677 by correctly referring to https://github.com/python-pillow/Pillow/blob/a352c18fe92692aaff3676ec6e0bdb672d91c622/src/PIL/TiffImagePlugin.py#L1052-L1053
> Corrected property name

- Tests/test_file_apng.py
- src/PIL/PngImagePlugin.py
Two changes here.
1. Fixed using info dictionary when writing multiple APNG frames.
`duration` can come from `encoderinfo` or `info` when saving multiple frames.
https://github.com/python-pillow/Pillow/blob/696b82e44032500197734c4dc4669d7c3f8b9371/src/PIL/PngImagePlugin.py#L1062
The `duration` variable is only part of the individual frame's `encoderinfo` when it is a list or tuple though, or if it was part of the actual image's `encoderinfo`.
https://github.com/python-pillow/Pillow/blob/696b82e44032500197734c4dc4669d7c3f8b9371/src/PIL/PngImagePlugin.py#L1082-L1084
So when it comes to fetch it for writing, it is ignored.
https://github.com/python-pillow/Pillow/blob/696b82e44032500197734c4dc4669d7c3f8b9371/src/PIL/PngImagePlugin.py#L1153
The same applies to `disposal` and `blend`.
2. …
> Fixed using info dictionary when writing multiple APNG frames

- src/thirdparty/fribidi-shim/fribidi.c
- src/thirdparty/fribidi-shim/fribidi.h
Fixes #5637
In #5637, when Gtk is imported, the FriBiDi library gets loaded which replaces the shim symbols due to dynamic linking. Trying to load `_imagingft` then calls `load_fribidi` which attempts to overwrite its symbols and segfaults. Hiding the symbols prevents them from being replaced by the real library and segfaulting. Hiding is the default with MSVC.
> Hide FriBiDi shim symbols to avoid conflict with real FriBiDi library

- src/libImaging/FliDecode.c
FliDecode.c had a check in the head of the frame where it was checking a variable against the value that was just set.
This updates the check to check the bytes in the buffer vs the framesize. 
Note that there are potentially single bytes of padding, such that all the sizes should be even.  This isn't necessarily reflected in the file size (e.g. `hopper.fli`) especially on the last chunk.
> Actually check the framesize in FliDecode.c

- .ci/install.sh
I think I just missed this in https://github.com/hugovk/Pillow/pull/71 / #5666
> Install numpy on Python 3.10

- Tests/test_image_quantize.py
- src/PIL/Image.py
Resolves #5695
[quantize()](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.quantize) accepts `palette` as an argument, but only applies the palette to the C layer.
https://github.com/python-pillow/Pillow/blob/d50052a75c4d0d17d3d37c24a4558c9e0736f0e8/src/PIL/Image.py#L1123-L1133
This PR copies the palette into the Python layer as well.
> Copy Python palette to new image in quantize()

- requirements.txt
Bullet points are missing at https://pillow.readthedocs.io/en/stable/releasenotes/8.3.2.html and on other pages.
This is due to sphinx_rtd_theme not working properly with latest docutils 0.17.
sphinx_rtd_theme issue and fix:
* https://github.com/readthedocs/sphinx_rtd_theme/issues/1115
* https://github.com/readthedocs/sphinx_rtd_theme/pull/1185
Build with 0.16:
Build with 0.17:
Let's pin to docutils 0.16 until the sphinx_rtd_theme fix is out.
> Docs: Temporarily pin docutils to fix bullets in sphinx_rtd_theme

- src/PIL/TiffImagePlugin.py
Before: https://pillow.readthedocs.io/en/latest/reference/plugins.html#PIL.TiffImagePlugin.ImageFileDirectory_v2
After: https://pillow--5708.org.readthedocs.build/en/5708/reference/plugins.html#PIL.TiffImagePlugin.ImageFileDirectory_v2
> Updated docstring

- .github/mergify.yml
- .github/workflows/test-mingw.yml
- .github/workflows/test-valgrind.yml
- .github/workflows/test-windows.yml
A couple of minor improvements spotted during last release cycle.
* Split MINGW out from `test-windows.yml` into its own workflow
* makes each yml file shorter
* there's not much overlap/re-use, and it's now easier to diff the files to compare
* I happened to hit some network timeouts during the release, GHA still only allows re-starting the _whole workflow_ (not a single job), so this allows wasting less time/electricity/resources
* Remove the final "Valgrind Test Successful" job from `test-valgrind.yml`
* redundant: not used by Mergify
* avoids the CI waiting and running a job for this, however quick
* workflow reports success sooner
cc @nulano about the MINGW stuff.
> CI: Split MINGW to own workflow, remove redundant job

- Tests/oss-fuzz/fuzz_font.py
- Tests/oss-fuzz/fuzz_pillow.py
* Make use of the latest version of Atheris (the python fuzzer): atheris_no_libfuzzer is now aliased to atheris, so no need to use it
* Use the new instrumentation syntax, with `with`
* Use `pass` instead of multiple `return`
> Improve the fuzzer wrt. the current atheris version

- selftest.py
In selftest.py, the shell commands in the docstring refers a number of times to an earlier function, `_info`. This PR suggests merging that function into the docstring as a lambda instead.
This should help give users the impression that they can just be up-and-running from shell, rather than "Wait, I run these shell commands from the example... but they refer to an external function?"
I also removed the `load()` command from `_info`, as I found it wasn't necessary.
> Moved _info function into docstring

- winbuild/build_prepare.py
The commit is up to date with the latest tag, with minor changes needed for MSVC: https://github.com/ImageOptim/libimagequant/compare/f41ee301ff3a407b16991af3dbe03910919bbdc3...2.16.0
The patches need to be updated to fix an issue with the provided CMakeLists.txt.
> Update winbuild libimagequant to 2.16.0

- .appveyor.yml
For https://github.com/python-pillow/Pillow/issues/5569.
* Test Python 3.10 on AppVeyor
* Released yesterday
* https://github.com/appveyor/ci/issues/3741#issuecomment-958837889
> Test Python 3.10.0 final on AppVeyor

- requirements.txt
This reverts commit 9509a73ed9080640d8d6b95f514b77329d123fa1.
* Undo PR https://github.com/python-pillow/Pillow/pull/5704 now Sphinx 1.0.0 has been released
* https://github.com/readthedocs/sphinx_rtd_theme/releases/tag/1.0.0
* https://github.com/readthedocs/sphinx_rtd_theme/tags
> Docs: Remove docutils pin

- .appveyor.yml
#5014 added `- '%PYTHON%\%PIP_DIR%\pip.exe install -U "setuptools>=49.3.2"'`. See https://github.com/python-pillow/Pillow/pull/4784#issuecomment-668002511 for more context.
#5234 intended to revert this, but did not do so properly - `- '%PYTHON%\%EXECUTABLE% -m pip install -U setuptools'`
This PR removes the line altogether.
> Removed setuptools install from AppVeyor

- setup.py
Resolves #5827
#5624 changed setup.py on macOS to prefer the command line tools SDK over `xcrun --show-sdk-path`. Apparently that was too far however, as conda-forge would like to specify the SDK path.
So instead, this PR scales back #5624 to only use the command line tools SDK when `xcrun --show-sdk-path` returns the default path of `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk`
> Only prefer command line tools SDK on macOS over the default

- Tests/test_pickle.py
- docs/releasenotes/9.0.0.rst
- src/PIL/ImageFont.py
Fixes https://github.com/python-pillow/Pillow/issues/5825.
* TrueType fonts can now be pickled and unpickled
> Add support for pickling TrueType fonts

- src/decode.c
- src/encode.c
Python getters are supposed to take a `void* closure` argument.
I am coming from Pyodide. Web assembly has no native support for function pointer casting -- a function declared with a certain signature must be called with the same signature, or it will fail with `RuntimeError: function signature mismatch`. Emscripten has support for emulating function pointer casts which we are currently using, but it imposes a significant performance and stack space cost and we are trying to remove the pointer cast emulation pyodide/pyodide#1677. To do this, we need to patch Python packages so that they have function signatures that match the calling conventions they declare.
> Fix pushes_fd method signature

- .github/workflows/lint.yml
- .github/workflows/test-windows.yml
- .github/workflows/test.yml
The https://github.com/actions/setup-python action can now take care of the pip cache, meaning we can remove a bunch of `actions/cache` config.
Re: https://github.com/actions/setup-python/releases/tag/v2.3.0
> GHA: Use actions/setup-python's pip cache

- Tests/test_file_libtiff.py
- src/PIL/TiffImagePlugin.py
Resolves #5838
It is [suggested in that issue](https://github.com/python-pillow/Pillow/issues/5838#issuecomment-972714494) that Pillow should automatically remove tile TIFF tags - rather than having [both tile and strip tags saved to the same image](https://github.com/python-pillow/Pillow/issues/5838#issuecomment-972699979).
So this PR removes TILEWIDTH, TILELENGTH, TILEOFFSETS and TILEBYTECOUNTS.
> Block tile TIFF tags when saving

- Tests/test_file_icns.py
- src/PIL/IcnsImagePlugin.py
Resolves #5590
https://en.wikipedia.org/wiki/Apple_Icon_Image_format#Header states that the second value is
> Length of file, in bytes, msb first
Saving images pre-#4526, I find that this is the case.
Since that PR however, this is no longer the case. This PR fixes it and adds a test.
> Corrected ICNS file length in header

- docs/reference/ImageDraw.rst
- docs/releasenotes/9.0.0.rst
Adds release notes for #5829 and #5694 - as well as updating the documentation for ``polygon`` as a result of #5694.
> Documentation for #5829 and #5694

- src/PIL/Image.py
Resolves #2856
In that issue, and in others like #5465, the `fromarray` "mode" parameter is misunderstood.
See https://pillow--5849.org.readthedocs.build/en/5849/reference/Image.html#PIL.Image.fromarray for a preview.
> Improved explanation of fromarray "mode" parameter

- Tests/test_file_jpeg.py
- Tests/test_file_ppm.py
- src/PIL/ImageFile.py
Fixes #5657.
The removed block of code is bad for the following reasons:
1. The return statement makes the function write nothing when fp is stdout, which is obviously unwanted.
2. The fp.flush() statement is duplicate of the line below, and is therefore useless.
> Do not return in ImageFile when saving to stdout

- docs/handbook/image-file-formats.rst
- docs/handbook/tutorial.rst
- docs/handbook/writing-your-own-file-decoder.rst
- docs/reference/ImageDraw.rst
- docs/reference/PixelAccess.rst
- docs/reference/PyAccess.rst
- docs/reference/c_extension_debugging.rst
- docs/reference/open_files.rst
- Apply black formatting to various code examples
- At https://pillow.readthedocs.io/en/latest/handbook/writing-your-own-file-decoder.html#the-raw-decoder, "raw mode" is listed as two words. If this is Python code, it should be one word.
> Improved example code

- src/_webp.c
When creating the `WebPAnimDecoder` object, we create a `WebPAnimDecoderObject` and populate its data using `WebPDataCopy()`.
Subsequently, if either `WebPAnimDecoderNew()` or `WebPAnimDecoderGetInfo()` fails, data is not currently deallocated, which may cause memory leaks.
This PR clears the decoder object's data in that situation.
> WebP: Fix memory leak during decoding on failure

- .github/workflows/cifuzz.yml
- .github/workflows/lint.yml
- .github/workflows/release-drafter.yml
- .github/workflows/test-docker.yml
- .github/workflows/test-mingw.yml
- .github/workflows/test-valgrind.yml
- .github/workflows/test-windows.yml
- .github/workflows/test.yml
* This will add a button to allow us to manually trigger a new build for a (whole) workflow, similar to Travis CI
* https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#manual-events
> GHA: Add workflow_dispatch to enable manually triggering builds

- Tests/test_imagefile.py
- src/PIL/ImageFile.py
Resolves #5871
I have contrived a test so that BmpImagePlugin will try to call `ImageFile._safe_read` with a `size` greater than `ImageFile.SAFEBLOCK` on a truncated file.
Without this PR, a truncation error is not raised [as advertised.](https://github.com/python-pillow/Pillow/blob/c5d9223a8b5e9295d15b5a9b1ef1dae44c8499f3/src/PIL/ImageFile.py#L537)
With this PR, it is.
> Fixed raising OSError in _safe_read when size is greater than SAFEBLOCK

- docs/releasenotes/9.0.0.rst
I thought it would be a nice gesture to dedicate the next release to Fredrik's memory. Guido said it was okay to quote part of his post.
@python-pillow/pillow-team
Preview:
* https://pillow--5885.org.readthedocs.build/en/5885/releasenotes/9.0.0.html
> Dedicate the next release to Fredrik Lundh

- .github/workflows/test.yml
* This repo has switched from `macos-10.15` to `macos-11` for `macos-latest`, but it's failing the build
* The quick fix to get the CI back to green is to explicitly use `macos-10.15`
---
For reference, here's logs from the last pass and first fail:
* [last pass](https://github.com/python-pillow/Pillow/runs/4497134031?check_suite_focus=true): [logs_16004.zip](https://github.com/python-pillow/Pillow/files/7712892/logs_16004.zip)
* [first fail](https://github.com/python-pillow/Pillow/runs/4518959612?check_suite_focus=true): [logs_16005.zip](https://github.com/python-pillow/Pillow/files/7712893/logs_16005.zip)
Last pass:
```
2021-12-12T09:46:43.0437590Z Processing dependencies for Pillow==9.0.0.dev0
2021-12-12T09:46:43.0460460Z Finished processing …
```
> GHA: Use macos-10.15 to fix build

- Tests/test_imageqt.py
- src/PIL/ImageQt.py
Steps to reproduce:
```python
from PIL import Image, ImageQt
image = Image.open("test.tif")  # test.tif is a 16-bit grayscale image
imageqt = ImageQt.ImageQt(image)
```
Expected behavior: A valid QImage is created.
Behavior without this code change: `ValueError: unsupported image mode 'I;16'`
I verified that a valid QImage is created with this change. Sorry I cannot share the test image I am using.
> Support 16-bit grayscale ImageQt conversion

- .github/workflows/test.yml
Taking a step back from #5886, so that macOS 10.15 is only used for PyPy jobs.
> GHA: Still use macos-latest for non-PyPy builds

- .github/workflows/test-mingw.yml
- .github/workflows/test.yml
- Makefile
- docs/installation.rst
Replaces `setup.py install` with `pip install .`, as per https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html
As worked out by https://github.com/pypa/setuptools/issues/2929, this also fixes the problem found in #5886. So this PR reverts #5886 and #5888.
> Switched from deprecated "setup.py install" to "pip install ."

- docs/reference/ImageShow.rst
- src/PIL/ImageShow.py
`xdg-open` is reliable way to open image with preferred application.
It works on linux and BSD with any desktop environment.
Debugging process should be comfortable.
> Added ImageShow support for xdg-open

- tox.ini
Continuing the work started with #5896, since [invoking setup.py directly is deprecated.](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html)
> Replaced further direct invocations of setup.py

- Tests/test_image_convert.py
- Tests/test_image_quantize.py
- Tests/test_imagegrab.py
The `assert_image` helper method is useful to assert an image's mode and size.
https://github.com/python-pillow/Pillow/blob/9d0703a8a82d00ec01303d8b7f7d408964e9fb9f/Tests/helper.py#L77-L86
However, I think that
```python
assert_image(im, "P", im.size)
```
could be more clearly expressed as
```python
assert im.mode == "P"
```
Similarly,
```python
assert_image(im, im.mode, (40, 60))
```
should be changed to
```python
assert im.size == (40, 60)
```
And
```python
assert_image(im, im.mode, im.size)
```
seems redundant.
> Do not compare properties to themselves

- Tests/test_imagedraw.py
- src/libImaging/Draw.c
The following code will crash when trying to free a pointer.
```python
>>> from PIL import ImageDraw
>>> o = ImageDraw.Outline()
>>> o.line(0, 0)
>>> o.transform((0, 0, 0, 0, 0, 0))
```
This PR fixes it.
> Fixed freeing pointer in ImageDraw.Outline.transform

- src/PIL/Image.py
In Image.py, we have
https://github.com/python-pillow/Pillow/blob/11c536b6d49b6d354157329643d1a58c7e1bf74d/src/PIL/Image.py#L159-L160
https://github.com/python-pillow/Pillow/blob/11c536b6d49b6d354157329643d1a58c7e1bf74d/src/PIL/Image.py#L170-L171
and
https://github.com/python-pillow/Pillow/blob/11c536b6d49b6d354157329643d1a58c7e1bf74d/src/PIL/Image.py#L139-L141
I can't see any use for the last one, so this PR suggests removing it. This does not change any functionality, since the other two code blocks still define `Image.NONE`.
> Image.NONE is only used for resampling and dithers

- Tests/test_file_pdf.py
- src/PIL/PdfParser.py
Like https://github.com/python-pillow/Pillow/commit/3bce145966374dd39ce58a6fc0083f8d1890719c and #5393, except with `\r` instead of `\n`.
> Exclude carriage return in PDF regex to help prevent ReDoS

- Tests/test_image_putdata.py
- src/PIL/Image.py
- src/_imaging.c
Resolves #5858
1. Clarify that `putdata()` should receive a flattened sequence, rather than the 2D sequence that the user is trying in the issue.
I have drawn inspiration from the docstring for `getdata()`
https://github.com/python-pillow/Pillow/blob/11c536b6d49b6d354157329643d1a58c7e1bf74d/src/PIL/Image.py#L1277-L1282
2. Raise an error if the sequence is not flattened.
3.
```python
>>> im = Image.new("L", (1, 1), 0)
>>> im.putdata([2.0])
>>> print(im.getpixel((0, 0)))
```
At the moment, in Python 3.9, this returns 2, and in Python 3.10, this returns 0. I've added a commit here to consistently return 2.
> Improved putdata() documentation and data handling

- Tests/test_image_convert.py
- src/libImaging/Convert.c
Resolves #5728 
The issue discusses a pixel in an image with the palette value `(177, 175, 175)`, and asks why converting from P to L doesn't convert it to 176. That conversion uses the L macro -
https://github.com/python-pillow/Pillow/blob/a3d1e2f85db890c6a1623e3902711863f55cc54e/src/libImaging/Convert.c#L1012-L1016
https://github.com/python-pillow/Pillow/blob/a3d1e2f85db890c6a1623e3902711863f55cc54e/src/libImaging/Convert.c#L43
Applying the L macro,
`(177*299 + 175*587 + 175*114) / 1000` = 175.598
Except the `p2l` code above rounds it down. This PR applies proper rounding to bring it to 176.
> Added rounding when converting P and PA

- Tests/test_file_libtiff.py
- src/PIL/TiffImagePlugin.py
Resolves #5843
`SAMPLEFORMAT` is currently in the `blocklist` when saving with libtiff.
https://github.com/python-pillow/Pillow/blob/ae7c2cb2e6a1d5bf3050cc0076d6155e56342c3c/src/PIL/TiffImagePlugin.py#L1687-L1689
The explanation is
https://github.com/python-pillow/Pillow/blob/ae7c2cb2e6a1d5bf3050cc0076d6155e56342c3c/src/PIL/TiffImagePlugin.py#L1679-L1680
But `SAMPLEFORMAT` doesn't only come from the user. It can also be set by TiffImagePlugin, according to the image format.
https://github.com/python-pillow/Pillow/blob/ae7c2cb2e6a1d5bf3050cc0076d6155e56342c3c/src/PIL/TiffImagePlugin.py#L1477-L1488
https://github.com/python-pillow/Pillow/blob/ae7c2cb2e6a1d5bf3050cc0076d6155e56342c3c/src/PIL/TiffImagePlugin.py#L1603-L1604
So this PR removes `SAMPLEFORMAT` from `blocklist`, allowing the value …
> Pass SAMPLEFORMAT to libtiff

- Tests/test_file_gif.py
- src/PIL/GifImagePlugin.py
Helps #4640
When saving an image as a GIF, the image passes through [`_normalize_mode`](https://github.com/python-pillow/Pillow/blob/bd00cd9214f986ceeef7d1707664f71231a5f643/src/PIL/GifImagePlugin.py#L349), to convert the image to 1, L or P.
When saving a single RGBA image as a GIF, the transparency is currently lost. This PR fixes that by setting the "transparency" key in the `info` dictionary to the first transparent palette entry (if you think that might not be very effective, since there could be many different transparent palette entries, remember #5282).
> When saving RGBA to GIF, make use of first transparent palette entry

- Tests/test_image_quantize.py
- src/libImaging/QuantOctree.c
Helps #4640
When using `quantize()`, most methods place the colors into the palette and then fill up the remaining colors with "\x00\x00\x00"
```pycon
>>> im = Image.new("RGB", (1, 1), (255, 0, 0))
>>> quantized_im = im.quantize(method=Image.MEDIANCUT)
>>> quantized_im.palette.palette
b'\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x …
```
> Fixed palette index for zeroed color in FASTOCTREE quantize

- setup.py
Resolves #5865
That issue reports an error decoding bytes. A self-contained example of that error is
```pycon
>>> bytes(list(range(46))+[231, 1]).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 46: invalid continuation byte
```
It can be fixed by using "latin1"
```pycon
>>> bytes(list(range(46))+[231, 1]).decode("latin1")
'\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\n\x0b\x0c\r\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f !"#$%&\'()*+,-ç\x01'
```
"latin1" is already used in two other places in setup.py - https://github.com/python-pillow/Pillow/blob/c5d9223a8b5e9295d15b5a9b1ef1dae44c8499f3/setup.py#L412 and https://github.com/python-pillow/Pillow/blob/c5d9223a8b5e9295d1 …
> Use latin1 encoding to decode bytes

- Tests/test_image_quantize.py
- src/PIL/Image.py
Resolves #5877
Trims the palette after `im.quantize()` to the number of colors requested.
> Limit quantized palette to number of colors

- Tests/test_file_jpeg2k.py
- Tests/test_file_png.py
- src/libImaging/Jpeg2KDecode.c
- src/libImaging/Jpeg2KEncode.c
- src/libImaging/Pack.c
Resolves #1204
Helps #3243, #3927 and #4213
> Improved I;16 operations on big endian

- Tests/test_imagefile.py
- src/_webp.c
Resolves #4745
Running code from the issue on a test image,
```python
from PIL import ImageFile
p = ImageFile.Parser()
with open("Tests/images/hopper.webp", "rb") as f:
new_data = f.read(1024)
while not p.image and new_data:
p.feed(new_data)
```
an error is triggered.
https://github.com/python-pillow/Pillow/blob/45003b78ed4003f6bf68e3a921b78539a64c7337/src/_webp.c#L398
This is effectively an error being raised because the the image is truncated, and most truncation errors are OSError. So if we change it to an OSError, then it is handled by `feed()`.
https://github.com/python-pillow/Pillow/blob/45003b78ed4003f6bf68e3a921b78539a64c7337/src/PIL/ImageFile.py#L413-L418
This fixes the problem.
> Changed error type to allow for incremental WebP parsing

- Tests/test_image.py
- setup.py
- src/Tk/tkImaging.c
- src/libImaging/ImPlatform.h
This is related to linking semantics, so Cygwin should follow the Windows codepath.
Fixes #5795 (and the bug that prompted that issue).
* Use the Windows method to get TCL functions on Cygwin, instead of the Linux method (the Linux method might also work on BSD, I haven't tested there)
> Use the Windows method to get TCL functions on Cygwin

- Tests/test_image.py
`import sys` was removed from Tests/test_image.py in #5768.
This was fine, until #5807 was merged and it was needed again - leading to main failing at the moment.
> Added sys import

- src/libImaging/TiffDecode.c
Helps #5370 (only works for uncompressed images)
> Explicitly enable strip chopping for large uncompressed TIFFs

- winbuild/build_prepare.py
Just for context, suggested in https://github.com/python-pillow/Pillow/pull/5811#discussion_r776074823
This updates libimagequant to the latest commit in the [msvc branch](https://github.com/ImageOptim/libimagequant/tree/msvc), after merging in master at [the 2.17.0 tag.](https://github.com/ImageOptim/libimagequant/tree/2.17.0)
> Updated winbuild libimagequant to 2.17.0

- src/PIL/Image.py
https://github.com/python-pillow/Pillow/blob/aa287bc9349ae298c68f875a9b9164c5bb85a1f2/src/PIL/Image.py#L806-L815
#5914 points out that `mode` will never be RGBA in the last line.
> Unless I'm reading this incorrectly, the addition of the check on mode means that this won't ever evaluate to True, because mode is set back to RGB a few lines above?
Setting RGBA modes to RGB was introduced in #5089.
This PR just removes the check for RGBA in the last line, since it is not needed.
> Removed redundant part of condition

- Tests/test_file_jpeg.py
- src/PIL/JpegImagePlugin.py
``JpegImagePlugin`` may append an EOF marker to the end of a truncated file, so that the last segment of the data will still be processed by the decoder.
If the EOF marker is not detected as such however, this could lead to an infinite loop where ``JpegImagePlugin`` keeps trying to end the file.
> Ensure JpegImagePlugin stops at the end of a truncated file

- Tests/test_imagemath.py
- docs/releasenotes/9.0.0.rst
- src/PIL/ImageMath.py
To limit `ImageMath` to working with images, Pillow will now restrict the builtins available to `ImageMath.eval()`. This will help prevent problems arising if users evaluate arbitrary expressions, such as ``ImageMath.eval("exec(exit())")``.
> Restrict builtins for ImageMath.eval()

- src/PIL/Image.py
Fixes https://github.com/python-pillow/Pillow/issues/5926.
* The `readonly` flag causes issues with `Image` equality, and is not needed for recreating pickled images (added in https://github.com/python-pillow/Pillow/pull/638)
> Remove readonly from Image.__eq__

- Tests/test_image.py
- src/PIL/Image.py
Resolves #5931
```pycon
>>> Image.new("RGB", (1, 2)).tobytes()
b'\x00\x00\x00\x00\x00\x00'
>>> Image.new("RGB", (1, 1)).tobytes()
b'\x00\x00\x00'
```
given this progression, you would expect
```pycon
>>> Image.new("RGB", (1, 0)).tobytes()
```
to give
```pycon
b''
```
However, instead it currently throws an error.
```
File "PIL/Image.py", line 748, in tobytes
e.setimage(self.im)
SystemError: tile cannot extend outside image
```
This PR returns an empty bytestring instead.
> Return an empty bytestring from tobytes() for an empty image

- CHANGES.rst
- docs/releasenotes/9.0.0.rst
CVEs received for:
* Restrict builtins for ImageMath.eval(). CVE-2022-22817 #5923
* Fixed ImagePath.Path array handling. CVE-2022-22815, CVE-2022-22816 #5920
> Add CVE IDs

- Tests/test_imagepath.py
- src/path.c
Resolves #5939
When drawing a rectangle,
```python
from PIL import Image, ImageDraw
im = Image.new("RGB", (1, 1))
draw = ImageDraw.Draw(im)
draw.rectangle((0, 0, 1, 1))
```
if the wrong coordinate type is used,
```python
from PIL import Image, ImageDraw
im = Image.new("RGB", (1, 1))
draw = ImageDraw.Draw(im)
draw.rectangle(('0', '0', '1', '1'))
```
the error given is
```
File "demo.py", line 4, in <module>
draw.rectangle(('0', '0', '1', '1'))
File "PIL/ImageDraw.py", line 259, in rectangle
self.draw.draw_rectangle(xy, ink, 0, width)
SystemError: new style getargs format but argument is not a tuple
```
The issue points out that this is not terribly clear. Instead, this PR changes it to
```
File "demo.py", line 4, in …
```
> Added specific error if ImagePath coordinate type is incorrect

- src/PIL/TiffImagePlugin.py
Resolves #5936. Ensures that the file pointer duplicated in TiffImagePlugin is closed, rather than counting on libtiff to do it.
https://github.com/python-pillow/Pillow/blob/eff6c34bd13df9cba034c54fd0c270bebfb8a270/src/PIL/TiffImagePlugin.py#L1186-L1188
I haven't added a test for this, since the issue involves hitting the limit on the number of open files.
> Ensure duplicated file pointer is closed

- src/PIL/ImageMode.py
Fixes #5933
This PR adds the modes mentioned in the docs to ImageMode. It also adds the mode `BGR` to be used as a basetype for the missing modes.
---
Sidenote: To get pillow 9.1.0.dev0 to build on Windows I had to do some modifications to the script in `winbuild\README.md`, e.g., because the script/snippet builds for python3.8, but calls python3.7 to prepare - which I don't have. I will leave my modified script here, since I don't know where else to put it, but if there is interest in a dedicated DOC PR for this, I can do that, too:
```cmd
set PYTHON=C:\Users\<username>\AppData\Local\Programs\Python\Python38
set PILLOW_REPO=<git-clone-location>\Pillow
cd /D %PILLOW_REPO%\winbuild
%PYTHON%\python.exe build_prepare.py -v --depends=%PILLOW_REPO%\depends
build\build_dep_all.cmd …
```
> Add missing ImageModes

- src/PIL/ImageMath.py
`ImageMath.VERBOSE` has been unused since PIL, so this PR removes it.
While I'm here, I've also included two cleanup changes.
- https://github.com/python-pillow/Pillow/blob/9a9afd36b41c3ff511ec2788ad657c0757e24b3e/src/PIL/ImageMath.py#L68-L73 The `ValueError` cannot be reached, so I've removed it.
- https://github.com/python-pillow/Pillow/blob/9a9afd36b41c3ff511ec2788ad657c0757e24b3e/src/PIL/ImageMath.py#L76-L83 `im1.size` will equal `size` at the end of this code, meaning that the last three lines can be simplified to a single line.
> Removed unused constant

- .github/workflows/test.yml
- docs/releasenotes/9.0.0.rst
- requirements.txt
* sphinx-issues 3.0.0 now has a CWE role for linking to https://cwe.mitre.org/
* https://github.com/sloria/sphinx-issues#usage-inside-the-documentation
* sphinx-issues 3.0.1 fixes the docs build problem in 3.0.0 (noted at https://github.com/python-pillow/Pillow/pull/5953#issuecomment-1009953021)
https://pillow--5955.org.readthedocs.build/en/5955/releasenotes/9.0.0.html#security
> Autolink CWE numbers with sphinx-issues

- src/PIL/SpiderImagePlugin.py
Resolves #2518
The issue reports that Spider images saved with Pillow have a black line at the end when opened with Fiji.
Fiji [uses bioformats as a dependency](https://github.com/fiji/fiji/blob/3428cdbb8fd6eaa6483ce1e084cc93108f6c8ca5/pom.xml#L727-L732). So https://github.com/ome/bioformats/blob/develop/components/formats-gpl/src/loci/formats/in/SpiderReader.java would be the reader that Fiji is using.
Testing, I find that doubling the length of the header fixes the display of the image in Fiji. There is [code in bioformats that looks like it could double the header length](https://github.com/ome/bioformats/blob/7dd6a1ce3aeb6bdc9d3bb5d15071c9956e4f3f62/components/formats-gpl/src/loci/formats/in/SpiderReader.java#L104-L109). This code is apparently searching for a local header for each …
> Fixed Spider images for use with Bio-formats library

- Tests/test_imageshow.py
- docs/deprecations.rst
- src/PIL/ImageShow.py
First pointed out in https://github.com/python-pillow/Pillow/pull/3450#discussion_r230547142, 
https://github.com/python-pillow/Pillow/blob/fd2b07c454b20e1e9af0cea64923b21250f8f8d6/src/PIL/ImageShow.py#L108 the `file` argument mirrors the builtin `file`.
This PR deprecates it in favour of `path`.
> Deprecated show_file "file" argument in favour of "path"

- Tests/test_decompression_bomb.py
- Tests/test_image_crop.py
- src/PIL/Image.py
Resolves #5957
At the moment, mixing up the order of the `box` values for `crop()`, so that a negative crop is performed, doesn't raise an error.
```python
im = Image.new("RGB", (10, 10))
im.crop((10, 10, 0, 0))
```
gives a (0, 0) image.
In the issue, this was done unintentionally by a user, and because no error was raised, they didn't realise their mistake.
This PR raises an error is the right of a crop region is less than the left, or if the bottom of the region is less than the top.
I am presuming that it is uncommon for users to want a negative crop, and more common for users to mix up the order of the values.
> Raise an error when performing a negative crop

- Tests/test_image.py
- src/PIL/Image.py
Fixes #5890.
Introduce `Image._repr_pretty_` as an alternative to `__repr__` for Jupyter notebook environment.
After this change `text/plain` output in Jupyter notebook will stay the same after re-running the cell:
```diff
$ git diff test.ipynb
diff --git a/test.ipynb b/test.ipynb
index f769d4b..4f8ba79 100644
--- a/test.ipynb
+++ b/test.ipynb
@@ -9,7 +9,7 @@
"data": {
"image/png": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAGUlEQVR4nGPc62fCQApgIkn1qIZRDUNKAwADRwFfBBwAnwAAAABJRU5ErkJggg==",
"text/plain": [
-       "<PIL.Image.Image image mode=RGB size=16x16 at 0x1075D8370>"
+       "<PIL.Image.Image image mode=RGB size=16x16>"
]
},
"execution_count": 1,
```
> Keep IPython/Jupyter text/plain output stable

- docs/deprecations.rst
- src/PIL/ImageShow.py
I realised I missed this in #5959
> Document when file argument will be removed

- .ci/install.sh
- depends/install_raqm.sh
- docs/installation.rst
The build commands also had to be changed, as libraqm changed to meson - https://github.com/HOST-Oman/libraqm/pull/97
> Upgraded raqm to 0.8.0

- README.md
- docs/index.rst
Two changes in this PR.
1. https://github.com/python-pillow/Pillow/actions?query=workflow%3ALint shows GHA workflows with a search query for the "Lint" workflow. https://github.com/python-pillow/Pillow/actions/workflows/lint.yml links to the dedicated page for the "Lint" workflow. This seems neater to me.
2. Adds a MinGW badge, after #5709
> Updated GitHub Actions badges

- .github/workflows/test-mingw.yml
- .github/workflows/test-windows.yml
In test.yml, we have
https://github.com/python-pillow/Pillow/blob/5fdf29f13b30b763b5b9f399ec227d76fb51f291/.github/workflows/test.yml#L12-L13
but in test-windows.yml and test-mingw.yml, we have
https://github.com/python-pillow/Pillow/blob/5fdf29f13b30b763b5b9f399ec227d76fb51f291/.github/workflows/test-windows.yml#L7
https://github.com/python-pillow/Pillow/blob/5fdf29f13b30b763b5b9f399ec227d76fb51f291/.github/workflows/test-mingw.yml#L7
This PR switches from windows-2019 to windows-latest, to ensure that we are always running the latest version, and don't have to upgrade it.
See https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners for more information about this topic.
> Switched from windows-2019 to windows-latest in GitHub Actions

- winbuild/build_prepare.py
As pointed out here: https://github.com/python-pillow/Pillow/commit/5fdf29f13b30b763b5b9f399ec227d76fb51f291#r65695669
> Fix lcms2 URL

- winbuild/build.rst
- winbuild/build_prepare.py
This patch enabled win-arm64 as a new platform for Windows.
Platform query and documentation is updated accordingly.
> Windows: Enable win-arm64 for MSVC

- Tests/test_imagemath.py
- src/PIL/ImageMath.py
https://github.com/python-pillow/Pillow/pull/5923#issuecomment-1008715242 has pointed out that #5923 does not protect against lambdas wrapping unwanted code.
> ImageMath.eval("(lambda: exit())()")
I can also imagine a lambda wrapping a lambda.
```python
ImageMath.eval("(lambda: (lambda: exit())())()")
```
This PR protects against both.
> Restrict builtins within lambdas for ImageMath.eval

- Tests/test_imageshow.py
- src/PIL/ImageShow.py
Rather than using `rm` inside a `subprocess` shell command, this PR switches to using `subprocess` without shell to open the image and then `os.remove`. This should resolve any path problems.
But there is a twist on macOS - Pillow sleeps before removing the image, and we presumably don't want to make our Python script hang for 20 seconds. Instead, this PR uses `subprocess` to start a Python process that sleeps and removes the file afterwards.
And since that makes `sleep`ing before removing the file nicer, this PR adds `sleep` for `xdg-open`,  instead of https://github.com/python-pillow/Pillow/pull/5950, to help https://github.com/python-pillow/Pillow/issues/5945 and https://github.com/python-pillow/Pillow/issues/5968
> In show_file, use os.remove to remove temporary images

- docs/releasenotes/9.0.1.rst
- docs/releasenotes/index.rst
Release notes for #6009 and #6010
> Added release notes for 9.0.1

- depends/install_imagequant.sh
- docs/installation.rst
With version 4.0, libimagequant has been [rewritten in Rust, and the Makefiles have been replaced with Cargo](https://github.com/ImageOptim/libimagequant/blob/main/CHANGELOG).
So this PR changes to the new build instructions - https://github.com/ImageOptim/libimagequant#building-with-cargo-c
> Updated libimagequant to 4.0.0

- Tests/test_imagefont.py
- src/PIL/ImageFont.py
Helps #6018 
If `layout_engine=ImageFont.LAYOUT_RAQM` is passed to `ImageFont.truetype` when `PIL.features.check_feature("raqm")` reports False, `ImageFont` currently silently falls back to basic layout. This PR adds a warning for this case.
> Issue warning if Raqm layout is requested, but Raqm is not available

- src/PIL/JpegImagePlugin.py
- src/PIL/PngImagePlugin.py
- src/PIL/TiffImagePlugin.py
* Need a newline for the `getxmp` return to render
https://pillow.readthedocs.io/en/stable/reference/plugins.html#PIL.JpegImagePlugin.JpegImageFile.getxmp
> Fix return in docs

- CHANGES.rst
- Tests/test_file_tiff.py
- docs/releasenotes/9.1.0.rst
- docs/releasenotes/index.rst
- src/PIL/TiffImagePlugin.py
Resolves #6025
TIFF tag 34377 is a ["Collection of Photoshop 'Image Resource Blocks'"](https://www.awaresystems.be/imaging/tiff/tifftags/photoshop.html). This PR adds a method, `getphotoshopblocks()`, to determine what blocks are present in an image. https://www.awaresystems.be/imaging/tiff/tifftags/docs/photoshopthumbnail.html was useful in writing this code.
This PR does not go so far as to format the information within each block. Instead, the bytes are simply deposited within a dictionary under a "data" key. This will allow us to add in more useful information in the future without breaking backwards compatibility. https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/#50577409_pgfId-1037727 will be a good resource at that time.
> Added get_photoshop_blocks() to parse Photoshop TIFF tag

- Tests/test_image_quantize.py
`test_libimagequant_quantize` is currently [skipped](https://github.com/python-pillow/Pillow/blob/cac305f8d2db5eca3ce18f8d334a9ff35f9c7fde/Tests/test_image_quantize.py#L20-L21) on ppc64le.
And for good reason, because if you [remove the skip](https://github.com/radarhere/Pillow/commit/12e2e97599209177550a8c382d64f6e03b910b29), it [fails](https://github.com/radarhere/Pillow/runs/5167378728).
Or rather, it did, because [that failure used libimagequant 2.12](https://github.com/radarhere/Pillow/runs/5167378728#step:6:82), and since https://github.com/python-pillow/docker-images/pull/138 effectively upgraded libimagequant on ppc64le to 4, it now passes, as seen in this PR.
> Only skip test if libimagequant is earlier than 4 on ppc64le

- src/libImaging/Convert.c
https://github.com/python-pillow/Pillow/blob/cac305f8d2db5eca3ce18f8d334a9ff35f9c7fde/src/libImaging/Convert.c#L1219-L1222
Collapse these two conditions into one.
> Simplified code

- Tests/test_image_putpalette.py
- src/PIL/Image.py
- src/_imaging.c
Resolves #6027
At the moment, `im.putpalette()` only results in RGB palettes, discarding alpha information. The exception to this is when [the mode is "RGBA", every 4th byte is extracted into `info`](https://github.com/python-pillow/Pillow/blob/cac305f8d2db5eca3ce18f8d334a9ff35f9c7fde/src/PIL/Image.py#L824-L829). However, that isn't a flexible way of retrieving alpha data, letting #6027 down when a user wants to retain alpha information from the more irregular "RGBA;15".
Instead, this PR changes `putpalette()` to create either RGB or RGBA palettes, moving the work of handling alpha data to Pillow's unpackers.
> Attach RGBA palettes from putpalette() when suitable

- Tests/test_image_convert.py
- src/libImaging/Convert.c
When converting P to PA, Pillow currently sets the A value from the palette.
https://github.com/python-pillow/Pillow/blob/cac305f8d2db5eca3ce18f8d334a9ff35f9c7fde/src/libImaging/Convert.c#L1029-L1039
If the palette is in RGBA mode, that makes sense. However, if the palette is in RGB mode, then that doesn't make sense, and leads to this.
```python
Image.open("Tests/images/hopper.png").convert("P").convert("PA").save("out.tiff")
```
[out.tiff.zip](https://github.com/python-pillow/Pillow/files/8058034/out.tiff.zip)
Instead, this PR checks the palette mode, and fills the alpha channel with 255 if the palette is RGB.
> Ensure image is opaque after converting P to PA with RGB palette

- Tests/test_file_icns.py
Removed details about pillow3.icns was created, since #6062 replaced the image.
> Updated comment

- docs/installation.rst
Shall we include JPEG2000 as well?
---
Whilst we're here, a line or two down we tell the user to pip install Pillow from PyPI, or instead build from source:
```rst
Now install Pillow with::
python3 -m pip install --upgrade pip
python3 -m pip install --upgrade Pillow
or from within the uncompressed source directory::
python3 -m pip install .
```
But this is the section on [Building from source](https://pillow.readthedocs.io/en/stable/installation.html#building-on-macos), we already had the [Basic installation](https://pillow.readthedocs.io/en/stable/installation.html#basic-installation) near the top of the page.
Shall we change it to this?
```rst
Now install from within the uncompressed source directory::::
python3 -m pip install --upgrade pip
python3 -m pip install .
```
> macOS: 'brew install openjpeg' for JPEG2000 support

- docs/installation.rst
When "Building From Source" as this section of the documentation is supposed to do, make sure that the user is not installing a wheel - use `--no-binary :all:`
> Use --no-binary when installing from source

- Tests/test_image_putpalette.py
- Tests/test_image_quantize.py
- src/PIL/Image.py
- src/_imaging.c
- src/libImaging/Imaging.h
- src/libImaging/Palette.c
Resolves #6046
Investigating the issue, I think it can be stated as two problems.
1. `getpalette()` returns more entries than set by `putpalette()`.
```pycon
>>> im = Image.new("P", (1, 1))
>>> im.putpalette((255, 0, 0))
>>> im.getpalette()
[255, 0, 0, 1, 1, 1, 2, 2, 2, ...]
```
This PR solves this by adding a `size` member to the C `ImagingPaletteInstance`.
Fixing this removes the need for [trimming the palette in Python in `im.load()`](https://github.com/python-pillow/Pillow/blob/10e1731149ebd6dde5f9d4e9ca502ea8a17f9955/src/PIL/Image.py#L836-L838).
2. Because C was not aware that a palette might have anything less than 256 entries, when converting an image to P, it considers all of the palette entries, rather than limiting itself to the palette size.
```python …
```
> Consider palette size when converting and in getpalette()

- Tests/test_image_mode.py
- src/PIL/Image.py
- src/PIL/ImageMode.py
Resolves #5990
https://github.com/python-pillow/Pillow/issues/5990#issuecomment-1039873428 pointed out that the second value in [`_MODE_CONV`](https://github.com/python-pillow/Pillow/blob/7b3f28047fe008d70bda1938e3178da388ecaa64/src/PIL/Image.py#L211-L239), [`extra`](https://github.com/python-pillow/Pillow/blob/7b3f28047fe008d70bda1938e3178da388ecaa64/src/PIL/Image.py#L243), is the number of bands in the mode. Rather than writing those out in `_MODE_CONV`, this could instead be derived from ImageMode.
The user in the issue would also like the NumPy typestr from `_MODE_CONV` available through a public API, and suggested ImageMode. From an organisational point of view for Pillow's code, that seems like a more logical location for that information, and it would be neater, since it then means …
> Merged _MODE_CONV typ into ImageMode as typestr

- docs/handbook/image-file-formats.rst
Alternative to #4570
https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#jpeg
> **subsampling**
>    If present, sets the subsampling for the encoder.
>
>    * ``keep``: Only valid for JPEG files, will retain the original image setting.
>    * ``4:4:4``, ``4:2:2``, ``4:2:0``: Specific sampling values
>    * ``-1``: equivalent to ``keep``
Discussion in that PR revealed that `-1` is not always equivalent to `keep`. The PR suggested fixing that discrepancy by changing Pillow to make `-1` equivalent to `keep`.
This PR instead suggests to leave Pillow behaviour unchanged, and just correct the documentation.
In Python, [-1 is just the default value to pass to C](https://github.com/python-pillow/Pillow/blob/669247cbd758acccac131daf9a2804c99f82bbca/src/PIL/JpegImagePlugin.py#L …
> Corrected JPEG subsampling documentation

- Tests/test_imageshow.py
- docs/releasenotes/9.1.0.rst
- src/PIL/ImageShow.py
Helps #5945 and #5976. Alternative to #6021
Three changes here.
1. As pointed out in #6021, `ImageShow.show()` does not return `True` and `False` like the docstring states, it returns 0 and 1. This PR updates the return values to match the docstring.
2. As suggested out in https://github.com/python-pillow/Pillow/pull/6005#discussion_r796396077, `display -title` looks preferable to `display -name`.
3. Given that there have been [requests](https://github.com/python-pillow/Pillow/issues/5945#issuecomment-1028760062) for [multiple images to be shown at once](https://github.com/python-pillow/Pillow/issues/5976#issuecomment-1017214685) and [to be viewed after 20s](https://github.com/python-pillow/Pillow/issues/5976#issuecomment-1018444936), a possible solution to these requests is to not …
> Do not automatically remove temporary ImageShow files on Unix

- Tests/test_image_quantize.py
- src/PIL/Image.py
- src/libImaging/Convert.c
https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.quantize
> **dither** – Dithering method, used when converting from mode “RGB” to “P” or from “RGB” or “L” to “1”. Available methods are [NONE](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.NONE) or [FLOYDSTEINBERG](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.FLOYDSTEINBERG) (default). Default: 1 (legacy setting)
It's weird that the documentation specified twice what the default was, but I guess that the FLOYDSTEINBERG constant has a raw value of 1. Oh wait, no, it doesn't.
https://github.com/python-pillow/Pillow/blob/29b703063134c6845d3bee333c178d9bba2ddc25/src/PIL/Image.py#L168-L172
If you search for 'dither' in …
> Changed quantize default dither to FLOYDSTEINBERG

- Tests/test_file_bufrstub.py
- Tests/test_file_gribstub.py
- Tests/test_file_hdf5stub.py
- src/PIL/BufrStubImagePlugin.py
- src/PIL/GribStubImagePlugin.py
- src/PIL/Hdf5StubImagePlugin.py
https://github.com/python-pillow/Pillow/blob/af345358e321bf3b9acc08f4f38c37d24152e470/src/PIL/BufrStubImagePlugin.py#L62-L63
`hasattr("_handler", "save")` is incorrect. We are not interested if the string `"handler"` has a `save` attribute, we are interested if the variable `_handler` has a save attribute.
This was fixed for WmfStubImageFile in https://github.com/python-pillow/Pillow/commit/751a6d1c2d13144e240ac2, but the fix wasn't applied to other stub formats.
I have not applied this fix to FITS, as the stub form of that plugin is being deprecated in #6056
> Fixed BUFR, GRIB and HDF5 stub saving

- Tests/test_bmp_reference.py
- Tests/test_file_dcx.py
- Tests/test_file_fli.py
- Tests/test_file_gif.py
- Tests/test_file_icns.py
- Tests/test_file_im.py
- Tests/test_file_jpeg.py
- Tests/test_file_mpo.py
- Tests/test_file_png.py
- Tests/test_file_psd.py
- Tests/test_file_spider.py
- Tests/test_file_tar.py
- Tests/test_file_tiff.py
- Tests/test_file_webp.py
- Tests/test_image.py
- Tests/test_imageqt.py
- Tests/test_numpy.py
A warning has started appearing.
https://github.com/python-pillow/Pillow/runs/5266944375#step:8:3064
> PytestRemovedIn8Warning: Passing None has been deprecated.
>  See https://docs.pytest.org/en/latest/how-to/capture-warnings.html#additional-use-cases-of-warnings-in-tests for alternatives in common use cases.
It is complaining about our method for checking that no warnings were raised during a test.
```python
with pytest.warns(None) as record:
...
assert not record
```
Instead, https://docs.pytest.org/en/latest/how-to/capture-warnings.html#additional-use-cases-of-warnings-in-tests suggests
```python
with warnings.catch_warnings():
warnings.simplefilter("error")
...
```
I have implemented that here, albeit without the `simplefilter`, since I presume we would also like to know if any …
> Updated checks that no warnings were raised

- docs/reference/ImageShow.rst
- src/PIL/ImageShow.py
Resolves #5976 by documenting that `ImageShow.register()` can be used to effectively change the priority of an existing viewer, and that as per #6045, temporary files are not removed on Unix.
> Improved ImageShow documentation

- .github/workflows/test-mingw.yml
- .github/workflows/test-windows.yml
GitHub Actions have started [failing in main for Windows](https://github.com/python-pillow/Pillow/runs/5299567368) at the "Enable page verification" step.
https://github.com/python-pillow/Pillow/blob/4638c4fba651025851bf1f41a28583ae11d73c3a/.github/workflows/test-windows.yml#L140-L143
The error is
> The term 'C:\Program Files (x86)\Windows Kits\10\Debuggers\x86\gflags.exe' is not recognized as a name of a cmdlet, function, script file, or executable program.
The problem started at the same time that the jobs switched from windows-2019 to windows-2022. It looks like windows-2022 does not have gflags.exe.
Taking advice from "[How to enable PageHeap in Windows registry without having access to gflags.exe](https://klaus.hohenpoelz.de/how-to-enable-pageheap-in-windows-registry-without-having-ac …
> Enable heap verification without gflags

- Tests/test_file_blp.py
- Tests/test_imagefile.py
- docs/handbook/appendices.rst
- docs/handbook/image-file-formats.rst
- docs/handbook/writing-your-own-image-plugin.rst
- docs/reference/ImageFile.rst
- src/PIL/BlpImagePlugin.py
- src/PIL/ImageFile.py
- src/encode.c
Resolves #4059
Resolves #3176
#1938 added `Image.register_encoder()`, but stopped short of creating `ImageFile.PyEncoder` to go with it.
First, however, some cleanup - tests from #4885 and #3190 were blindly appended to the end of Tests/test_imagefile.py. This incorrectly made them a part of the unrelated `TestPyDecoder` class. So I have moved them up to the `TestImageFile` class.
I've implemented a PyEncoder for BLP.
> Added PyEncoder

- Tests/test_file_mpo.py
- src/PIL/MpoImagePlugin.py
Resolves #6100
#5168 introduced a rule that MPO image size can only change for "Large Thumbnail" frames.
However, it forgot to reset the size back to the initial value when seeking to another frame after that.
> Reset size when seeking away from "Large Thumbnail" MPO frame

- docs/reference/ImageStat.rst
- src/PIL/Image.py
Resolves #3958
`im.histogram()` groups pixel counts into 256 bins per channel, even for `I` and `F` mode images (which have pixel values of 0 to 65535, meaning that you could have 65536 bins in theory).
```python
for mode in ("1", "L", "I", "F"):
im = Image.new(mode, (1, 1))
assert len(im.histogram()) == 256
```
The ImageStat module performs operations on that histogram. This means that for `I` and `F` mode images, ImageStat can only report what it has been given.
```python
from PIL import Image, ImageStat
im = Image.new("I", (100, 1))
px = im.load()
for i in range(99):
px[i, 0] = 65535 - i
stat = ImageStat.Stat(im)
print(stat.mean[0])  # 251.47
```
So I've added a note that `mean`, `median`,`rms` and the maximum `extrema` can't be more than 255.
> Document that histogram() uses 256 bins per channel

- Tests/test_file_dds.py
- Tests/test_file_ftex.py
- Tests/test_file_xbm.py
- docs/example/DdsImagePlugin.py
- src/PIL/DdsImagePlugin.py
- src/PIL/FliImagePlugin.py
- src/PIL/FtexImagePlugin.py
- src/PIL/GbrImagePlugin.py
- src/PIL/IcnsImagePlugin.py
- src/PIL/TiffImagePlugin.py
- src/PIL/WmfImagePlugin.py
- src/PIL/XbmImagePlugin.py
- Do not read data until necessary in GbrImagePlugin
- Raise SyntaxError if data is not as expected in XbmImagePlugin
- Moved FLI flags check into _accept
- Since the [prefix is 16 characters](https://github.com/python-pillow/Pillow/blob/14b9b597ffa228ac56b91dc2782199f432defa14/src/PIL/Image.py#L3064), [this check on the 15th and 16th characters](https://github.com/python-pillow/Pillow/blob/14b9b597ffa228ac56b91dc2782199f432defa14/src/PIL/FliImagePlugin.py#L49) can be run earlier
- Make code clearer by matching _accept condition.
- The `dword` condition here has the same purpose as the `prefix[:4]` check, so have them match for clarity.
https://github.com/python-pillow/Pillow/blob/14b9b597ffa228ac56b91dc2782199f432defa14/src/PIL/WmfImagePlugin.py#L115 …
> Various _accept changes

- docs/reference/PixelAccess.rst
- docs/reference/PyAccess.rst
Helps https://github.com/python-pillow/Pillow/issues/4818#issuecomment-725039803
> Document alternatives to accessing individual pixels

- Tests/test_imagefile.py
- src/PIL/ImageFile.py
In ImageFile, the encoder `cleanup()` method is not called from Python if there is an error.
https://github.com/python-pillow/Pillow/blob/2f2b48dc2c6f8907968c9deea4fb3a4be57c3c09/src/PIL/ImageFile.py#L505-L520
However, `cleanup()` would still be called from `_dealloc` in C.
https://github.com/python-pillow/Pillow/blob/2f2b48dc2c6f8907968c9deea4fb3a4be57c3c09/src/encode.c#L94-L98
Except that doesn't help a PyEncoder. So this PR ensures `cleanup()` is called from ImageFile.
> Ensure cleanup() is called for PyEncoders

- docs/handbook/writing-your-own-image-plugin.rst
- src/PIL/Image.py
- src/PIL/ImageFile.py
Helps #4818, by
- mentioning [`set_as_raw()`](https://github.com/python-pillow/Pillow/blob/6b9b392ccca040bf889e31d76d5c59e5c12164af/src/PIL/ImageFile.py#L673) in the Python decoder documentation
- removing the "Experimental" label from ``pulls_fd``. It was added in Pillow 3.3.0, and the next release is Pillow 9.1.0.
- noting that ``pulls_fd`` and ``pushes_fd`` allow more freedom, by abandoning Pillow's process of handling the file in blocks, but may lead to increase memory usage, if the codec is written to hold the everything in memory at once.
- re-iterating that ``cleanup()`` is for... cleanup tasks, but also clarifying that if ``_pulls_fd`` or ``_pushes_fd`` was used, then  the codec author probably doesn't need this, as they would have instinctively cleaned up their resources at the …
> Improved codec documentation

- Tests/test_image_access.py
- src/PIL/GifImagePlugin.py
- src/PIL/IcnsImagePlugin.py
- src/PIL/IcoImagePlugin.py
- src/PIL/Image.py
For a (0, 0) image, `im.load()` currently returns `None`.
```pycon
>>> im = Image.new("RGB", (1, 1))
>>> im.load()
<PixelAccess object at 0x103b865f0>
>>> im = Image.new("RGB", (0, 0))
>>> im.load()
>>> 
```
This is because `load()` tests if `self.im` is truthy.
https://github.com/python-pillow/Pillow/blob/92c26a77ca53a2bfbd8804f009c6c8755d0e5a43/src/PIL/Image.py#L867-L876
And the image size is what is used to determine the boolean value.
```pycon
>>> im = Image.new("RGB", (10, 10))
>>> len(im.im)
100
>>> bool(im.im)
True
>>> im = Image.new("RGB", (0, 0))
>>> len(im.im)
0
>>> bool(im.im)
False
```
So this PR instead changes the Python code to check `self.im is not None`, there and in other locations. I've added a check to `assert …
> Check if self.im is not None

- Tests/test_image_convert.py
- src/libImaging/Convert.c
Resolves #5967
```pycon
>>> Image.new("I;16", (1, 1), 65535).load()[0, 0]
65535
>>> Image.new("I;16", (1, 1), 65536).load()[0, 0]
0
```
So we can agree that the maximum for "I;16" is 65535, a.k.a 2**16 - 1, as expected.
When converting from "I" to "I;16", there is [clipping](https://github.com/python-pillow/Pillow/blob/38f4660d9ecfab74af8bad292d31e080072b25b3/src/libImaging/Convert.c#L767-L789). So you would expect that clipping to limit the values of "I", the 32-bit mode, to the maximum value of "I;16", the 16-bit mode.
Except it doesn't.
```pycon
>>> im = Image.new("I", (1, 1), 65535)
>>> im.convert("I;16").load()[0, 0]
32767
```
The following line incorrectly imagines that we need to clip to an signed range, not an unsigned range. …
> Clip I;16 to be unsigned, not signed

- src/PIL/PsdImagePlugin.py
https://github.com/python-pillow/Pillow/blob/397a9409959bccd0130d0b51820f2a94e3bf153d/src/PIL/PsdImagePlugin.py#L158-L164
is nearly identical to its super method
https://github.com/python-pillow/Pillow/blob/397a9409959bccd0130d0b51820f2a94e3bf153d/src/PIL/ImageFile.py#L280-L286
And the differences don't lead to any changes.
```pycon
>>> im = Image.core.fill("RGB", (1, 1), 0)
>>> Image.Image()._new(im).load()[0, 0]
(0, 0, 0)
>>> im = Image.core.new("RGB", (1, 1))
>>> Image.Image()._new(im).load()[0, 0]
(0, 0, 0)
```
> Removed load_prepare nearly identical to ImageFile load_prepare

- src/PIL/BlpImagePlugin.py
- src/PIL/ImageFile.py
- src/PIL/MspImagePlugin.py
I made a mistake in #6069, when I wrote that for `PyDecoder`, when `decode()` is finished, it should ["return 0 for the bytes consumed."](https://github.com/python-pillow/Pillow/pull/6069/files#diff-4668a28f508bbcb68e61f9b257415dc814c22e8bb24850629fe7788ae5b7475cR674) It should be a negative number instead.
This can be seen from the ImageFile code
https://github.com/python-pillow/Pillow/blob/397a9409959bccd0130d0b51820f2a94e3bf153d/src/PIL/ImageFile.py#L257-L259
and also from Tests/test_imagefile.py
https://github.com/python-pillow/Pillow/blob/397a9409959bccd0130d0b51820f2a94e3bf153d/Tests/test_imagefile.py#L193-L196
which causes the test suite to fail if the return value is changed to `0, 0` instead.
> decode() should return -1 when finished

- Tests/test_file_webp_animated.py
Resolves #3927
Resolves #4213
While investigating `TestFileWebpAnimation.test_write_animation_L` and `TestFileWebpAnimation.test_write_animation_RGB` failures on big-endian, I came to the conclusion that it was not a problem in our code, but in libwebp itself. I [reported](https://bugs.chromium.org/p/webp/issues/detail?id=548) this to them, it was accepted, and then fixed in libwebp 1.2.2.
This PR removes the xfails on those tests for big endian, runs the first half of them that passes before libwebp 1.2.2, and then skips the second half if libwebp 1.2.2 or greater is not available.
https://github.com/python-pillow/docker-images/pull/128 and #5982 made libwebp 1.2.2 available to the CI job.
> libwebp 1.2.2 fixed endian bugs

- docs/handbook/tutorial.rst
Alternative to #6064
Added example code to the tutorial that merges two images into a single wider image.
> Added merging images example

- Tests/test_file_ppm.py
- docs/handbook/image-file-formats.rst
- src/PIL/PpmImagePlugin.py
Resolves #5008
Resolves #5403
#5008 points out that the PPM [`maxval`](https://github.com/python-pillow/Pillow/blob/397a9409959bccd0130d0b51820f2a94e3bf153d/src/PIL/PpmImagePlugin.py#L114-L123) does not just indicate the bit depth of an image. It is an arbitrary number, that ["Must be less than 65536 and more than zero."](http://netpbm.sourceforge.net/doc/ppm.html)
The example from the issue has a `maxval` of 11 (not 2 ** 11, but just 11), and https://en.wikipedia.org/wiki/Netpbm#PGM_example shows an example where the `maxval` is 15. So when it is 15, the values range between 0 and 15, from black to white.
This PR 
- allows this value to be arbitrary for P5 (grayscale). That fixes the code example in #5008, and #5403, which features a P5 image at 10-bit depth, or 1023 maxval (2 ** 10 - …
> Added support for PPM arbitrary maxval

- Tests/test_file_webp.py
- src/PIL/WebPImagePlugin.py
Resolves #6139
When saving multiple frames to a WebP image, there is currently no default duration.
https://github.com/python-pillow/Pillow/blob/0cf072db39bf1868575c625fc4403f388e5d47d4/src/PIL/WebPImagePlugin.py#L195
But duration is added together when iterating over each frame.
https://github.com/python-pillow/Pillow/blob/0cf072db39bf1868575c625fc4403f388e5d47d4/src/PIL/WebPImagePlugin.py#L249
https://github.com/python-pillow/Pillow/blob/0cf072db39bf1868575c625fc4403f388e5d47d4/src/PIL/WebPImagePlugin.py#L289-L292
That can lead to an error, because `None` cannot be added to `0`.
This PR adds a default duration of zero.
> Added WebP default duration of zero when saving

- Tests/test_file_libtiff.py
- Tests/test_image_access.py
- Tests/test_imagewin_pointers.py
https://github.com/python-pillow/Pillow/blob/f3a3b20c51035969e585583e7340c80bf28caef3/Tests/test_image_access.py#L8
This import at the top level of test_image_access.py, but is only used on [non-CI Windows](https://github.com/python-pillow/Pillow/blob/f3a3b20c51035969e585583e7340c80bf28caef3/Tests/test_image_access.py#L402). This PR moves the import so that if a user doesn't have setuptools installed, that doesn't stop them from running our test suite.
test_image_access.py and test_imagewin_pointers.py similarly always import ctypes for tests that only run on Windows. I have moved those imports as well.
test_file_libtiff.py imports ctypes to calculate libtiff will transform a specific value into. I've just run that calculation now, recorded the value and removed the import.
> Do not always require ctypes in tests

- src/PIL/_tkinter_finder.py
In some cases, the Tk library may have been directly compiled in or bundled into the main executable by the time Pillow runs, in which case `__file__` isn't available (nor would it make sense to use, anyway).
If `__file__` is missing, then set the library path to None and rely on our Tk loader being able to find the function pointers within the main binary - we know we probably have it because we've managed to import it already.
> Support Python distributions where _tkinter is compiled in

- Tests/test_image.py
- src/PIL/Image.py
Resolves #6123
A malformed image from that issue has Exif data that stops after the header. This is the second report of this however, so this PR handles the data instead of throwing an error.
> Handle EXIF data truncated to just the header

- Tests/test_file_ico.py
- src/PIL/IcoImagePlugin.py
Resolves #6121
Two changes.
1. For `im.save("test.ico", sizes=((32, 32), (32, 32))`, only save one 32x32 frame, not two.
2. At its simplest, IcoImagePlugin resizes an image to save it at various sizes.
```python
hopper().save("test.ico", bitmap_format="bmp", sizes=[(128, 128), (64), 64)])
```
At one step more complicated, it allows users to supply the smaller images themselves, through `append_images`.
```python
hopper().save("test.ico", bitmap_format="bmp", sizes=[(128, 128), (64, 64)], append_images=[hopper().resize((64, 64))])
```
The user in the issue would like to save the image at different sizes, and also attach additional copies of certain sizes at different bit depths.
```python
hopper().save("test.ico", bitmap_format="bmp", sizes=[(128, 128), (64, 64)], …
```
> Save additional ICO frames with other bit depths if supplied

- Tests/test_file_gif.py
- src/PIL/GifImagePlugin.py
Resolves #6115
At the moment, RGBA transparency is only [retained](https://github.com/python-pillow/Pillow/blob/475b7233d6c6341f750829dbdd5123002bed57b7/src/PIL/GifImagePlugin.py#L447-L459) when saving a [single frame GIF](https://github.com/python-pillow/Pillow/blob/475b7233d6c6341f750829dbdd5123002bed57b7/src/PIL/GifImagePlugin.py#L517), not [multiple frames.](https://github.com/python-pillow/Pillow/blob/475b7233d6c6341f750829dbdd5123002bed57b7/src/PIL/GifImagePlugin.py#L548)
This PR removes the `initial_call` argument from `_normalize_mode`, allowing the transparency to be kept every time.
> Retain RGBA transparency when saving multiple GIF frames

- src/PIL/ImageShow.py
Requested in https://github.com/python-pillow/Pillow/commit/8da80130dbc747f3954b4904247d26289fe722f9#r68650261
Resolves #6146
That comment points out that https://github.com/python-pillow/Pillow/blob/6faebd3ff321e7b2dd780950858301e1b2d76db8/src/PIL/ImageShow.py#L51-L61 can set `title` to `None`, which is then passed (through [`Viewer.show`](https://github.com/python-pillow/Pillow/blob/6faebd3ff321e7b2dd780950858301e1b2d76db8/src/PIL/ImageShow.py#L71-L85) and [`show_image`](https://github.com/python-pillow/Pillow/blob/6faebd3ff321e7b2dd780950858301e1b2d76db8/src/PIL/ImageShow.py#L109-L111)) to `DisplayViewer` and `XVViewer` as `None` for one of the values passed to `subprocess.Popen`.
This problem was introduced in #6010.
> Fixed calling DisplayViewer or XVViewer without a title

- Tests/test_image.py
- src/PIL/Image.py
Helps #5944. Alternative to #5947
If an error occurs after creating a file, remove the file, rather than leaving a potentially corrupt image on disk.
> If an error occurs after creating a file, remove the file

- docs/handbook/image-file-formats.rst
Updated documentation after #6102
> Document support for RLE8 reading in BMP

- src/PIL/PdfImagePlugin.py
Resolves #6149
When saving a PDF, the `bits` setting is different for 1 and L mode images.
https://github.com/python-pillow/Pillow/blob/a6a843e5482345ffcd6cb45a534a11e839fcef43/src/PIL/PdfImagePlugin.py#L122-L135
Except that both images are encoded as JPEGs,
https://github.com/python-pillow/Pillow/blob/a6a843e5482345ffcd6cb45a534a11e839fcef43/src/PIL/PdfImagePlugin.py#L165-L166
which treats both 1 and L as L.
https://github.com/python-pillow/Pillow/blob/a6a843e5482345ffcd6cb45a534a11e839fcef43/src/PIL/JpegImagePlugin.py#L574-L578
So instructing the PDF that [`BitsPerComponent`](https://github.com/python-pillow/Pillow/blob/a6a843e5482345ffcd6cb45a534a11e839fcef43/src/PIL/PdfImagePlugin.py#L187) is different for these two images seems wrong. As a result, 1-bit PDFs from the current version …
> Do not mark L mode JPEG as 1 bit in PDF

- src/PIL/ImageGrab.py
Resolves #6144
There are two ways of looking at this change.
1. Speed improvement. Rather than grabbing the complete screen on macOS, and then cropping the result to the `bbox` requested by the user, this PR tells `screencapture` the co-ordinates that we are interested in. The image does need to be resized afterwards, to avoid returning a image twice the size of the requested `bbox`, but presumably that is still faster than loading an image the size of the screen and cropping it.
2. Since `screencapture` without arguments returns an image at double resolution, cropping to the `bbox` can produce an unexpected offset. By passing the arguments to `screencapture`, Pillow can leave the problem of calculating which portion of the screen is desired to the system.
> Use screencapture arguments to crop on macOS

- Tests/test_imagetk.py
- src/PIL/ImageTk.py
Resolves #6020
When [`PhotoImage.paste` calls "PyImagingPhoto"](https://github.com/python-pillow/Pillow/blob/ab8125fa6b8dff98b9de1a148308d40744583cca/src/PIL/ImageTk.py#L175-L199), it catches a TclError in case the tkinter hooks have not been activated yet. If they haven't, then it calls `_imagingtk.tkinit`, which [calls `TkImaging_Init`](https://github.com/python-pillow/Pillow/blob/ab8125fa6b8dff98b9de1a148308d40744583cca/src/_imagingtk.c#L55), which [creates the "PyImaging" Tcl commands.](https://github.com/python-pillow/Pillow/blob/ab8125fa6b8dff98b9de1a148308d40744583cca/src/Tk/tkImaging.c#L200-L214)
`ImageTk.getimage` does not handle the situation where the tkinter hooks have not been activated yet.
https://github.com/python-pillow/Pillow/blob/ab8125fa6b8dff98b9de1a148308d40744583cca/ …
> Ensure Tkinter hook is activated for getimage()

- src/path.c
Addresses https://github.com/python-pillow/Pillow/commit/1e092419b6806495c683043ab3feb6ce264f3b9c#commitcomment-63846366
I failed to acknowledge that `malloc` allocates a block of "size", while `calloc` allocates "nitems" blocks of "size".
> Corrected memory allocation

- Tests/test_file_tiff.py
- src/PIL/TiffImagePlugin.py
Resolves #3622
If a TIFF image is opened with "separate" [planar configuration](https://www.awaresystems.be/imaging/tiff/tifftags/planarconfiguration.html), it is successfully read.
However, if that same image is saved, Pillow tries to keep the "separate" planar configuration from the input file, and the output image is broken.
This PR simply changes Pillow to always save "contiguous", and the output image is fixed.
> Always save TIFF with contiguous planar configuration

- Tests/test_file_jpeg.py
- Tests/test_image.py
- src/PIL/JpegImagePlugin.py
Suggested in https://github.com/python-pillow/Pillow/issues/5944#issuecomment-1079934111
The JPEG format [does not support saving an image with zero width or height](https://github.com/python-pillow/Pillow/issues/5931#issuecomment-1007142950). This PR raises a ValueError for the situation, rather than the SystemError that is currently raised.
> Raise ValueError when trying to save empty JPEG

- Tests/test_imageops.py
- src/PIL/ImageOps.py
Allows `autocontrast`, `equalize`, `invert`, `posterize` and `solarize` to support 1 mode images.
Alternative to #6033
> Allow 1 mode images to be inverted

- src/thirdparty/fribidi-shim/fribidi.c
Testing https://github.com/python-pillow/pillow-wheels/pull/271, I find the tests pass, but Raqm is not enabled even when I install FriBiDi.
On Alpine, fribidi is at `/usr/lib/libfribidi.so.0`, and I can see the second `dlopen` call succeeds when using `strace`. However, the shim is still rejecting the SO. This is because the `dlerror` call returns the error for the first `dlopen` call.
This could be fixed by calling `dlerror` before retrying to clear the error, but since all `dlsym` return values are checked to be non-null, there is actually no need to check `dlerror` at all.
See PR adding tests in https://github.com/python-pillow/pillow-wheels/pull/274
> Fix loading FriBiDi on Alpine

- Tests/test_file_jpeg2k.py
- docs/handbook/image-file-formats.rst
- docs/releasenotes/9.1.0.rst
- src/PIL/Jpeg2KImagePlugin.py
- src/encode.c
- src/libImaging/Jpeg2K.h
- src/libImaging/Jpeg2KEncode.c
Closes #5485
* Add `mct` option for JPEG2000 that allows the use of multiple component transformation when encoding
* Add `no_jp2` option for JPEG2000 to allow specifying the format when not saving to file
* Updates handbook with new options and revises `irreversible` entry
OpenJPEG's `tcp_mct` is defined [here](https://github.com/uclouvain/openjpeg/blob/b6b8d28b3a85b74ff5415565cff2c20c019ca3c5/src/lib/openjp2/openjpeg.h#L522)
> Add support for multiple component transformation to JPEG2000

- .pre-commit-config.yaml
- docs/deprecations.rst
* Correct the deprecated note on  https://pillow.readthedocs.io/en/stable/deprecations.html#constants to match https://pillow.readthedocs.io/en/stable/releasenotes/9.1.0.html#constants
> DOC: the constants were deprecated in 9.1.0 not 9.2.0

- src/PIL/ImagePalette.py
The ImagePalette size parameter was deprecated in #5641.
This PR removes it from documentation so that new users will not try to use it.
> Removed documentation for deprecated size parameter

- Makefile
- RELEASING.md
Some things noticed during https://github.com/python-pillow/Pillow/issues/6110.
```console
$ # Nope
$ python3 -m check-manifest
/Library/Frameworks/Python.framework/Versions/3.10/bin/python3: No module named check-manifest
$ # Yep
$ check-manifest
$
```
And as an opposite, we can call twine via `python3 -m twine`, and for `twine check` include `--strict`:
```
--strict    Fail on warnings
```
> Release updates

- Tests/test_imagetk.py
- docs/deprecations.rst
- src/PIL/ImageTk.py
Resolves #6163
In [PhotoImage.paste()](https://github.com/python-pillow/Pillow/blob/a575ec33d2f0a04de6cde880a4163de61106b343/src/PIL/ImageTk.py#L178), the `box` parameter is unused.
This PR deprecates it.
> Deprecated PhotoImage.paste() box parameter

- Tests/test_lib_pack.py
- src/libImaging/Unpack.c
Adds support for unpacking 16-bit BGRA format. This format is used by ImageMagick 6 for many platforms - the addition of this support enables converting directly from `Magick::PixelPacket*` into PIL images.
I have used this new functionality in an example image-processing library I wrote to accompany a talk on Python APIs for CUDA-accelerated applications (see e.g. https://github.com/gmarkall/numba-accelerated-udfs/blob/main/filigree/api.py#L47), but I think it is generally useful for other applications to be able to work directly with ImageMagick 6 data.
> Add support for unpacking 16-bit BGRA

- Tests/test_image_thumbnail.py
- src/PIL/Image.py
Helps #6185
The TIFF in the issue has a tile orientation of 8, meaning that it is [rotated and the size is changed in `load_end()`](https://github.com/python-pillow/Pillow/blob/f1aeb5ea7aa7588f8b5544d8f3916c569503dd5f/src/PIL/TiffImagePlugin.py#L1192-L1196).
However, `thumbnail()` doesn't call `load()` before calculating the size that the image should become, so the calculations are incorrect. This is resolved by simply calling `load()` in `thumbnail()`.
> Load image before performing size calculations in thumbnail()

- Tests/test_image_resize.py
- src/PIL/Image.py
Like #6186, except for `resize()` instead of `thumbnail()`.
> Load before getting size in resize()

- Tests/test_image_point.py
- src/PIL/Image.py
Resolves #6187
The issue reports that float `lut` values raise an error in Python 3.10 for `im.point()`.
This would be because `_point` calls `getlist()`,
https://github.com/python-pillow/Pillow/blob/4996f84fb3fb80dc1d4e8288ff45ef11f8b162cc/src/_imaging.c#L1428
which then calls `PyLong_AsLong`.
https://github.com/python-pillow/Pillow/blob/4996f84fb3fb80dc1d4e8288ff45ef11f8b162cc/src/_imaging.c#L379-L380
https://docs.python.org/3/c-api/long.html#c.PyLong_AsLong
> Changed in version 3.10: This function will no longer use `__int__()`.
So this PR casts `lut` values to `int` first, except for the [case where `_point` uses float values instead.](https://github.com/python-pillow/Pillow/blob/4996f84fb3fb80dc1d4e8288ff45ef11f8b162cc/src/_imaging.c#L1393)
> Round lut values where necessary

- .github/workflows/stale.yml
We often get issues where we ask the OP for more info but they never reply.
Most recently, no reply in a week after four comments from us: https://github.com/python-pillow/Pillow/issues/6181. Or already closed: https://github.com/python-pillow/Pillow/issues/6154, no reply after five comments from us.
We often label them ["Awaiting OP Action"](https://github.com/python-pillow/Pillow/issues?q=label%3A%22Awaiting+OP+Action%22+sort%3Aupdated-desc+) for our own convenience.
GitHub has an action to automatically close "stale" issues: https://github.com/actions/stale
There's a whole bunch of config. It can:
* add a "stale" label and/or a comment after some time, 
* and close the issue after more time.
For example, we could have this:
* We manually add the "Awaiting OP Action". 
* If no-one …
> Use actions/stale to close 'Awaiting OP Action' with no response

- Tests/test_imagefont.py
- docs/deprecations.rst
- docs/releasenotes/9.2.0.rst
- docs/releasenotes/index.rst
- src/PIL/ImageFont.py
First part for https://github.com/python-pillow/Pillow/pull/6195#discussion_r847410876
Deprecate undocumented FreeTypeFont.getmask2 fill parameter that expects an internal function by default.
> Deprecate FreeTypeFont.getmask2 fill parameter

- docs/handbook/tutorial.rst
Reading images from URL is only documented at https://pillow.readthedocs.io/en/stable/releasenotes/2.8.0.html#open-http-response-objects-with-image-open (which uses urllib2, which is not available in Python 3).
Now, a Python3 compatible example will also appear in the PIL Tutorial section.
EDIT: Here is the link: https://pillow--6215.org.readthedocs.build/en/6215/handbook/tutorial.html#reading-from-url
> Add example to read image from URL

- docs/handbook/image-file-formats.rst
Correct Handbook documentation about encoding of GIF files from run-length to LZW.
No issue associated with this pull request.
* Pillow writes GIF files with LZW encoding since 8.2.0, but the Handbook was not updated to reflect this. It still refers to run-length encoding (which was not quite correct before).
> Update image-file-formats.rst [ci skip]

- Tests/test_image_resize.py
- Tests/test_image_thumbnail.py
#6138 has started failing on `Tests/test_image_resize.py::TestImageResize::test_load_first` with an error that `OSError: decoder libtiff not available`.
The fact that libtiff is not detected in #6138 is one problem. However, it should not cause the test suite to fail. So this PR skips the test from #6190, and also #6186, if libtiff is unavailable.
> Skip tests unless libtiff is available

- src/PIL/ImageShow.py
Increase wait time to 4 seconds from 2 seconds for the deletion of the temporary file made from .show(). The Windows default image viewer at times can take longer than 2 seconds to open and display an image causing the image to never display for the user.
Fixes # Line 144, Increase wait time
* Increase wait time to 4 seconds from 2 seconds for deletion of temporary image file
> Increase wait time of temporary file deletion on Windows

- .github/workflows/tidelift.yml
Same as and closes https://github.com/python-pillow/Pillow/pull/6221 but from a branch in this repo, instead of from a personal fork.
That one failed because it can't find the API key, likely a GitHub security precaution to prevents forks accessing secrets.
> Run Tidelift Align on Pipfile changes

- src/PIL/Image.py
Update Image.py file with  a typo in effect_mandelbrot method.
The Typo was in docstrings of the effect_mandelbrot method in Image module of PIL.
Fixes a docstring mistake in effect_mandelbrot method in Image module of PIL.
* Fixing Typo.
> Update Image.py docstring

- Tests/test_file_ppm.py
- src/PIL/PpmImagePlugin.py
Fixes a warning occurring on main.
https://github.com/python-pillow/Pillow/runs/6134877188?check_suite_focus=true#step:8:3147
```
Tests/test_file_ppm.py::test_token_too_long
/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/PIL/PpmImagePlugin.py:86: BytesWarning: str() on a bytes instance
raise ValueError(f"Token too long in file header: {token}")
```
> Decode bytes before passing to f-string

- src/PIL/ImageGrab.py
I have found a bug in ImageGrab.grab().
File "src/PIL/ImageGrab.py", line 36,
`args += ["-R", f"{left},{right},{right-left},{bottom-top}"]`
seems to be a mistake and ImageGrab.grab() does not return expected results.
As ImageGrab.grab() is implemented with "screencapture" subprocess which takes an option -R "x,y,width,height" to capture a rectangle area, it must be `args += ["-R", f"{left},{top},{right-left},{bottom-top}"]`.
> Corrected screencapture argument in ImageGrab.grab()

- Tests/test_file_webp.py
Adds a test for https://github.com/python-pillow/Pillow/blob/bcded33ceead2ae69dad602ce95d8f892ffb46df/src/PIL/WebPImagePlugin.py#L221-L229
> Test invalid WebP background colors

- Tests/test_file_ppm.py
- src/PIL/PpmImagePlugin.py
Resolves #6240
http://netpbm.sourceforge.net/doc/ppm.html states that maxval "Must be less than 65536 and more than zero". The issue found that a maxval of zero raised a ZeroDivisionError instead.
Instead, if `maxval` is outside of the valid range, this PR raises a ValueError, "Invalid maxval".
> Raise ValueError for invalid PPM maxval

- setup.py
We need to search the system paths as well from pkg-config for some packages to be found properly.
> Search pkgconf system libs/cflags

- Tests/test_imagetk.py
In main at the moment, [`tk.Frame` is failing for Python 3.7 on macOS.](https://github.com/python-pillow/Pillow/runs/6290406498?check_suite_focus=true#step:8:1230)
This PR skips test_imagetk.py if that error occurs, as it is not a problem with Pillow.
> Skip test_imagetk if tk raises a RuntimeError

- Tests/test_file_gif.py
- src/PIL/GifImagePlugin.py
Resolves #6259
If duration isn't passed in as a keyword argument when saving GIFs, default to the duration from each frame, rather than just using the duration from the first frame.
> Use durations from each frame by default when saving GIFs

- Tests/test_file_png.py
- src/PIL/PngImagePlugin.py
Resolves #6252
Some PNG chunks expect a certain amount of data.
If the chunk doesn't state that it is long enough to contain that data, then errors can occur, as reported in the issue.
Instead, this PR raises a ValueError. As with other operations in PngImagePlugin, `ImageFile.LOAD_TRUNCATED_IMAGES = True` can be used to silence these errors.
> Raise ValueError if PNG chunks are truncated

- docs/releasenotes/9.0.0.rst
Resolves #6262
The issue requests the the Pillow 9.0 release notes be updated to note that switching to libjpeg-turbo in the macOS and Linux wheels may result in different pixel values.
This was also a problem in #6113.
> libjpeg-turbo may result in different pixels

- Tests/test_image_array.py
- src/PIL/Image.py
Resolves #6210
In `fromarray`, or more specifically `frombuffer`, this PR populates the Python palette from the C palette.
This is equivalent to populating the Python palette from the C palette in `convert` (see [here](https://github.com/python-pillow/Pillow/blob/134023796e935ef79d5feb6879e9270327cfb8a2/src/PIL/Image.py#L1007) and [here](https://github.com/python-pillow/Pillow/blob/134023796e935ef79d5feb6879e9270327cfb8a2/src/PIL/Image.py#L1040)).
> Populate Python palette in fromarray()

- src/libImaging/Quant.c
First, in `quantize2`, the variable `Pixel furthest` is only used for its `v` property. So the `Pixel` can be simplified to just that [`uint32_t`.](https://github.com/python-pillow/Pillow/blob/31800a0213422aca9a83d31a4b925fd4dac8e941/src/libImaging/QuantTypes.h#L22-L30)
Second, `quantize2` sets `furthestDistance` to zero,
https://github.com/python-pillow/Pillow/blob/31800a0213422aca9a83d31a4b925fd4dac8e941/src/libImaging/Quant.c#L1579-L1583
and then runs `compute_distances`, assigning `furthest`,
https://github.com/python-pillow/Pillow/blob/31800a0213422aca9a83d31a4b925fd4dac8e941/src/libImaging/Quant.c#L1528-L1541
before it returns to `quantize2` and `p[i].v` and `data.new.v` are set to `data.furthest.v`.
What if `oldDist` was never greater than zero though? Then `furthest.v` would never …
> Ensure that furthest v is set in quantize2

- Makefile
- RELEASING.md
To make the release that little bit easier.
> Include 'twine check' in 'make sdist'

- Tests/test_image_point.py
- docs/deprecations.rst
- docs/releasenotes/9.2.0.rst
- src/PIL/Image.py
In modes I and F, Image.point only supported affine expressions of the forms (lambda x:) x * a, x + a, and x * a + b. Expressions like 1 - x had to be written x * -1 + 1.
This rewrite, though still limited to affine transformations, supports far more expression forms, including 1 - x, (2 * x + 1) / 3, etc.
> Support more affine expression forms in im.point()

- Tests/test_file_apng.py
- Tests/test_file_fli.py
- Tests/test_file_gif.py
- Tests/test_file_mpo.py
- Tests/test_file_tiff.py
- src/PIL/DcxImagePlugin.py
- src/PIL/FliImagePlugin.py
- src/PIL/GifImagePlugin.py
- src/PIL/ImImagePlugin.py
- src/PIL/Image.py
- src/PIL/MicImagePlugin.py
- src/PIL/MpoImagePlugin.py
- src/PIL/PngImagePlugin.py
- src/PIL/PsdImagePlugin.py
- src/PIL/SpiderImagePlugin.py
- src/PIL/TiffImagePlugin.py
Resolves #6205
The issue reported an unexpected error when calling `seek()` after an image had been closed, thrown when trying to use `__fp`.
This PR adds a `DeferredError` before trying to access the internal fp, like [`self.im` does after an image is closed.](https://github.com/python-pillow/Pillow/blob/0329b8fa1d7ad3ae39a171a903b328a56046003a/src/PIL/Image.py#L616)
Since this would be a further modification to `_close__fp` in multiple plugins, this PR also renames `__fp` to `_fp`, making it accessible from Image.py, and allowing `_close__fp` to be merged into Image.py
> Raise ValueError when trying to access internal fp after close

- Tests/test_imagefont.py
- src/PIL/ImageFont.py
Resolves #6209
In the issue, a user opens a font from a file-like object, and the font contents are read from that object.
Then the user tries to open a `font_variant()` and the font contents are read from the same object again, without seeking, which means that there is nothing left to read.
This PR changes `font_variant()` to just use the originally read bytes in that situation.
> If font is file-like object, do not re-read from object to get variant

- Tests/test_file_tiff.py
- src/PIL/TiffImagePlugin.py
Helps #6230 
BmpImagePlugin sets the info dictionary "compression" to an integer.
https://github.com/python-pillow/Pillow/blob/c6637bc4de33a8b85ea02378ee25353a923e1898/src/PIL/BmpImagePlugin.py#L70-L72
https://github.com/python-pillow/Pillow/blob/c6637bc4de33a8b85ea02378ee25353a923e1898/src/PIL/BmpImagePlugin.py#L95
https://github.com/python-pillow/Pillow/blob/c6637bc4de33a8b85ea02378ee25353a923e1898/src/PIL/BmpImagePlugin.py#L252
However, when TiffImagePlugin is saving, it expects a string.
https://github.com/python-pillow/Pillow/blob/c6637bc4de33a8b85ea02378ee25353a923e1898/src/PIL/TiffImagePlugin.py#L1571-L1578
This leads to an error. This PR instead ignores integer compression values from the info dictionary when saving as a TIFF.
> Ignore compression value from BMP info dictionary when saving as TIFF

- docs/handbook/image-file-formats.rst
Addresses concerns raised in https://github.com/python-pillow/Pillow/discussions/6273#discussioncomment-2694757
1. https://pillow.readthedocs.io/en/latest/handbook/image-file-formats.html#gif
> The library writes LZW encoded files in GIF87a by default, unless GIF89a features are used or GIF89a is already in use.
This could be interpreted to mean that LZW encoding is not used for GIF89a. This is not the case (and @raygard would know, as he actually wrote #5291).
2. The ["Reading local images"](https://pillow.readthedocs.io/en/latest/handbook/image-file-formats.html#reading-local-images) example relies on the ability of the user to set `im.size`. This was removed in #3203, so I've updated the example to use `crop()` instead.
3. https://pillow.readthedocs.io/en/latest/handbook/image-file-form …
> Improved image file formats documentation

- docs/handbook/image-file-formats.rst
Document the change in the reading of GIF comments from #6300
> Once a GIF comment is loaded, it is kept for subsequent frames

- docs/handbook/image-file-formats.rst
https://github.com/python-pillow/Pillow/issues/1146#issuecomment-1139624957 points out that while [WmfImagePlugin](https://github.com/python-pillow/Pillow/blob/main/src/PIL/WmfImagePlugin.py) supports WMF and EMF file equally, EMF is not mentioned in https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html
https://github.com/python-pillow/Pillow/issues/1146#issuecomment-1139652811 points out that SUN is also missing from the list.
> Added EMF and SUN to list of supported file formats

- Tests/test_imagedraw.py
- src/libImaging/Draw.c
Resolves #6290
During drawing, #5980 moves a point to join discontiguous corners to the rest of the shape. However, this has been applied too thoroughly, and in #6290, the attempt to join pixels together has ended up dragging pixels from the left hand side of the polygon all the way to the right, creating a gap instead.
Adding a condition to only try and join discontiguous corners at the end of edges fixes the problem.
> Only try to connect discontiguous corners at the end of edges

- .pre-commit-config.yaml
- winbuild/build.rst
[Sphinx Lint](https://github.com/sphinx-contrib/sphinx-lint) is an RST linter that has been spun out from a CPython tool.
It finds this bug in https://github.com/python-pillow/Pillow/blob/a50addb8e212e57dfe703b3d792691b3e18b2587/winbuild/build.rst#build-configuration
```
inline literal missing (escaped) space after literal: '``ARM64``b' (missing-space-after-literal)
```
So let's fix that, and also remove an orphaned sentence fragment.
---
And as follow on from https://github.com/python-pillow/Pillow/pull/6223, let's switch to monthly autoupdate if quarterly is too seldom.
> Add Sphinx Lint to pre-commit and fix RST bug

- Tests/test_file_libtiff.py
- src/PIL/TiffImagePlugin.py
Resolves #6230
#6060 contained a commit entitled "[Allow getpalette() to return less than 256 colors](https://github.com/python-pillow/Pillow/pull/6060/commits/948c064b282f80492f5b88d3f06a599b76516edf)"
That has that meant that there are less entries in COLORMAP.
https://github.com/python-pillow/Pillow/blob/c6637bc4de33a8b85ea02378ee25353a923e1898/src/PIL/TiffImagePlugin.py#L1677-L1679
Which then triggers the following error in the issue.
https://github.com/python-pillow/Pillow/blob/c6637bc4de33a8b85ea02378ee25353a923e1898/src/encode.c#L791-L792
This PR pads the COLORMAP entries until it reaches 768.
> Pad COLORMAP to 768 items when saving TIFF

- winbuild/build_prepare.py
Use SourceForge auto mirror capability.
Fixes #6343 .
* Use SourceForge auto mirror capability
> Use SourceForge auto mirror capability

- docs/conf.py
New in Sphinx 5:
> [#10062](https://github.com/sphinx-doc/sphinx/issues/10062): Change the default language to 'en' if any language is not set in conf.py
https://www.sphinx-doc.org/en/master/changes.html
```
Running Sphinx v5.0.1
WARNING: Invalid configuration value found: 'language = None'. Update your configuration to a valid langauge code. Falling back to 'en' (English).
making output directory... done
...
```
https://readthedocs.org/projects/pillow/builds/17091425/
```
Running Sphinx v5.0.1
making output directory... done
...
```
https://readthedocs.org/projects/pillow-hugovk/builds/17091435/
> Fix Sphinx 5 warning by setting docs language

- src/PIL/ImageDraw.py
#5510 added an ImageFont to the top of ImageDraw, not noticing that ImageDraw already imports ImageFont later on.
https://github.com/python-pillow/Pillow/blob/753da81757752457ef9faca83997be87974a1cb0/src/PIL/ImageDraw.py#L96-L98
This PR changes the import from #5510 to only run when necessary, following the original pattern.
> Only import ImageFont in ImageDraw when necessary

- Tests/test_file_libtiff.py
Reverts https://github.com/python-pillow/Pillow/commit/1a2866
> Revert "Skip test_realloc_overflow unless libtiff 4.0.4 or higher"

- Tests/test_image.py
- src/PIL/Image.py
Resolves #6349
At the moment, `remap_palette()` only returns RGB palettes. This PR allows it to return RGBA palettes if the source image has an RGBA palette.
> Allow remapping P images with RGBA palettes

- Tests/README.rst
In
https://github.com/python-pillow/Pillow/blob/638ba163f425fd586ded4780b8024536819922f8/.appveyor.yml#L46
and
https://github.com/python-pillow/Pillow/blob/638ba163f425fd586ded4780b8024536819922f8/.ci/install.sh#L34-L36
pytest-timeout is installed as a test dependency. However, it is not documented in Tests/README.rst. This PR fixes that.
> Added pytest-timeout to test dependencies

- Tests/test_image.py
- docs/reference/Image.rst
- docs/releasenotes/9.2.0.rst
- src/PIL/Image.py
Resolves #6348
Adds `apply_transparency()`, a method to take a P mode image with a "transparency" key in the `im.info` dictionary, remove the "transparency" key and apply the transparency to the palette instead.
> Added apply_transparency()

- Tests/test_imagecms.py
- src/PIL/ImageCms.py
Hi,
This pull request is a fix to a potential wrong operator bug at `src/PIL/ImageCms.py`. Please check the changes.
Best,
Jingxuan
> Fix wrong operator bug in PyCMSError exception message

- Tests/test_file_pcx.py
- src/PIL/PcxImagePlugin.py
Fixes https://github.com/python-pillow/Pillow/discussions/6388#discussioncomment-2999295
This is a regression introduced by #6060
> Pad PCX palette to 768 bytes when saving

- Tests/test_image_array.py
- src/PIL/Image.py
Resolves #5815
#5379 was created to workaround a bug in NumPy. That bug has now been fixed in NumPy 1.23, so this PR reverts the src change from #5379.
> Reverted to __array_interface__ with the release of NumPy 1.23

- Tests/test_file_gif.py
- src/PIL/GifImagePlugin.py
Palette can be optimized if number of colors can be reduced by half or more.
Fixes #6362 .
* Fix test for palette "hole" by changing comparison `max(used_palette_colors) > len(used_palette_colors)` to use `>=`
* Also allow optimize if number of used colors is not more than half the number of current colors
* Added a test for the latter that fails with current `_get_optimize()` but passes with this change.
I note that this change should obviate the condition `len(used_palette_colors) <= 128` but some tests fail if I remove it. I would rather leave it than try to update those tests in `test_file_gif.py`.
As noted in #6362, this assumes that im.palette.palette exists, is not None and is actually a byte string or array of RGB or RGBA colors. If this is …
> Improved GIF optimize condition

- docs/index.rst
Fixes #6398
* Remove the search page from the TOC
> Docs: remove redundant search page from table of contents

- src/thirdparty/fribidi-shim/fribidi.c
Fixes #6374, likely also #6314.
* Fix null check when loading the `fribidi_version_info` symbol
> Fixed null check for fribidi_version_info in FriBiDi shim

- docs/Makefile
Running `make doccheck` without furo installed leads to
```
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C docs html
/Applications/Xcode.app/Contents/Developer/usr/bin/make install-sphinx
python3 -c "import sphinx" > /dev/null 2>&1 || python3 -m pip install sphinx
python3 -m sphinx.cmd.build -b html -W --keep-going -d _build/doctrees   . _build/html
Running Sphinx v4.4.0
loading translations [en]... done
loading pickled environment... done
Theme error:
no theme named 'furo' found (missing theme.conf?)
make[1]: *** [html] Error 2
make: *** [doccheck] Error 2
```
This PR installs furo as part of `install-sphinx`.
> Install furo if it is not available

- src/PIL/ImageShow.py
There are exceptional cases in which `sys.executable` is empty or null (see [the docs](https://docs.python.org/3/library/sys.html#sys.executable)). I think it's better to just not delete the image in these cases, instead of crashing.
> Fix when `sys.executable` is empty or null

- .github/workflows/lint.yml
- .github/workflows/release-drafter.yml
- .github/workflows/test-cygwin.yml
- .github/workflows/test-docker.yml
- .github/workflows/test-mingw.yml
- .github/workflows/test-valgrind.yml
- .github/workflows/test-windows.yml
- .github/workflows/test.yml
- .github/workflows/tidelift.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: neilnaveen <42328488+neilnaveen@users.noreply.github.com>
> Set permissions for GitHub actions

- docs/handbook/image-file-formats.rst
- docs/releasenotes/9.0.0.rst
https://github.com/python-pillow/Pillow/runs/7261653289?check_suite_focus=true#step:11:571
> (    deprecations: line  253) redirect  https://www.freetype.org/ - permanently to https://freetype.org/
So I've replaced that link with https://freetype.org/
https://github.com/python-pillow/Pillow/runs/7261653289?check_suite_focus=true#step:11:582
> (handbook/image-file-formats: line  830) broken    https://spider.wadsworth.org/spider_doc/spider/docs/spider.html - HTTPSConnectionPool(host='spider.wadsworth.org', port=443): Max retries exceeded with url: /spider_doc/spider/docs/spider.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb6f707da50>, 'Connection to spider.wadsworth.org timed out. (connect timeout=None)'))
We could replace the link using the Wayback …
> Updated links

- Tests/test_file_png.py
- src/PIL/PngImagePlugin.py
Resolves #6430.
This is like #6253, only for a different PNG chunk.
> Raise ValueError if PNG sRGB chunk is truncated

- src/PIL/PSDraw.py
Resolves #6428
Uses the changes suggested in that issue. I can't see a way to add tests for this.
Moving the `neg` means that instead of going from `(0, 0)` to `(width, 0)`, `(width, -height)`, `(0, -height)` and `(0, 0)`,
it instead goes from `(0, 0)` to `(width, 0)`, `(width, height)`, `(0, height)` and `(0, 0)`,
so instead of drawing the rectangle below the starting point, it draws it above.
> Fixed PSDraw rectangle

- .ci/install.sh
Tests/test_qt_image_qapplication.py has started aborting in ubuntu-latest on main - https://github.com/python-pillow/Pillow/runs/7337854934?check_suite_focus=true#step:8:2131
Starting [QApplication with `QT_DEBUG_PLUGINS` enabled](https://github.com/radarhere/Pillow/commit/a540fb9d2c42a994a4d91fdcaab661cba45e67b0), I find the message ["libxcb-shape.so.0: cannot open shared object file: No such file or directory"](https://github.com/radarhere/Pillow/runs/7339328878?check_suite_focus=true#step:4:258)
So this PR installs libxcb-shape0.
A similar thing has happened before, with #4662
> Install libxcb-shape0

- docs/Makefile
* Allow setting the Python interpreter on the command line when building docs.
* For example: `make doc PYTHON=python3.11`
(I wanted to check 3.11 and they build fine; I have `3.11-dev` installed via pyenv and needed to do [this](https://stackoverflow.com/a/60469203/724176) first to make sure it built Python with Tk.)
> Docs: Allow setting Python interpreter via command line

- setup.cfg
- setup.py
- tox.ini
* The next quarterly release (Pillow 9.3.0) will officially support Python 3.11
* This PR is like https://github.com/python-pillow/Pillow/pull/5570 but for 3.11
* https://github.com/python-pillow/Pillow/pull/6433 has the support table update
> 3.11: Add Trove classifier and to tox.ini and update setup.py version check

- src/PIL/Image.py
There is a small typo in src/PIL/Image.py.
Should read `unpredictable` rather than `unpredicatable`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> Fix simple typo

- src/PIL/ImageFile.py
Resolves #6448
The issue reports an increase in memory usage. Testing, I find that it started with https://github.com/python-pillow/Pillow/pull/6096/commits/bb9338e34d705501b87876ebe6a8212b88b96acb. It would appear that the exception value is being held onto.
This PR moves the code into a separate function, which stops the memory problem.
> Moved tile encoding into separate function

- Tests/test_file_mpo.py
- docs/handbook/image-file-formats.rst
- docs/releasenotes/9.3.0.rst
- docs/releasenotes/index.rst
- src/PIL/JpegImagePlugin.py
- src/PIL/MpoImagePlugin.py
Addresses #6373
Adds `save_all` and `append_images` to the MPO format.
I put this together by studying the way that Pillow reads in multiple MPO frames, and by looking at the [MPO specification.](https://web.archive.org/web/20190227081740/http://www.cipa.jp/std/documents/e/DC-007_E.pdf)
> Support saving multiple MPO frames

- Tests/test_file_libtiff.py
For most macOS jobs, test_file_libtiff has started failing in main - https://github.com/python-pillow/Pillow/runs/7668608766#step:8:612
It is now using [libtiff 4.4.0_1](https://github.com/python-pillow/Pillow/runs/7668608766#step:6:8), whereas it previously used [libtiff 4.4.0](https://github.com/python-pillow/Pillow/runs/7624437043?check_suite_focus=true#step:6:8). The difference is that it [switched to libjpeg-turbo.](https://github.com/Homebrew/homebrew-core/commit/80ed02e16028cf1b576dbfbf8cf744f351d6cf0d), so it seems reasonable that there would be a change in the results.
This PR increases the test tolerance to pass again.
> Increased test tolerance to allow for libtiff with libjpeg-turbo

- Tests/test_file_libtiff.py
- Tests/test_file_pdf.py
- src/PIL/PdfImagePlugin.py
- src/PIL/TiffImagePlugin.py
Resolves #6453
The issue requests the CCITTTaxDecode filter be using to save 1 mode PDFs, to reduce file size.
> Save 1 mode PDF using CCITTFaxDecode filter

- src/PIL/ImageFont.py
Resolves #6324
It has been [requested](https://github.com/python-pillow/Pillow/issues/6324#issuecomment-1135153357) we document that on Windows, FreeType keeps the font file open while Pillow is using it.
Testing [this](https://github.com/radarhere/Pillow/commit/84438b738d993bb8e26b24f3f80ea94cf8e13b39),
```python
import shutil
shutil.copy("Tests/fonts/FreeMono.ttf", "out.ttf")
font = ImageFont.truetype("out.ttf")
os.remove("out.ttf")
```
on Windows, I see a [PermissionError.](https://github.com/radarhere/Pillow/runs/7704792192?check_suite_focus=true#step:24:1634) On [macOS and Linux, there is no problem.](https://github.com/radarhere/Pillow/actions/runs/2808890136)
The error [disappears on CPython](https://github.com/radarhere/Pillow/actions/runs/2808891207) if you [insert `del font` …
> Note to Windows users that FreeType will keep the font file open

- src/PIL/ImageOps.py
Mention in the `exif_transpose()` docstring that orientation data is removed by the operation.
Also mention that this does not happen if the orientation is 1. Requested in https://github.com/python-pillow/Pillow/issues/4124#issuecomment-1204627944
> Orientation data is removed by exif_transpose()

- Tests/test_imagedraw.py
- docs/reference/ImageDraw.rst
- docs/releasenotes/9.3.0.rst
- src/PIL/ImageDraw.py
Resolves #6480
By raising `ImageDraw.ImageDraw.font` from an instance variable to a class variable, a default ImageDraw font can be set by the user.
```python
from PIL import ImageDraw, ImageFont
ImageDraw.ImageDraw.font = ImageFont.truetype("Tests/fonts/FreeMono.ttf", 120)
```
From then on, ImageDraw operations would use that font as the default, instead of the `ImageFont.load_default()` font.
> Allow default ImageDraw font to be set

- src/libImaging/Convert.c
#6506 asked how Pillow converted images from PA to P.
The answer was because PA to P conversion doesn't exist, Pillow instead [falls back](https://github.com/python-pillow/Pillow/blob/87ecd01fc042bb67b11bfcff3db99fc2b61e702d/src/PIL/Image.py#L1034-L1040) to converting from PA to RGB, and then RGB to P.
This PR adds direct conversion from PA to P. There should be no functional change, only an increase in efficiency.
> Added direct conversion from PA to P

- docs/installation.rst
https://pillow.readthedocs.io/en/stable/installation.html#building-on-linux
> Prerequisites for Ubuntu 16.04 LTS - 20.04 LTS are installed with:
> ```
> sudo apt-get install libtiff5-dev libjpeg8-dev libopenjp2-7-dev zlib1g-dev \
>     libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python3-tk \
>     libharfbuzz-dev libfribidi-dev libxcb1-dev
> ```
All of the packages listed are still used in [our docker install of Ubuntu 22.04](https://github.com/python-pillow/docker-images/blob/main/ubuntu-22.04-jammy-amd64/Dockerfile).
The only exception is libxcb1-dev, which isn't installed anywhere in our repositories. The package is [still available in Jammy though.](https://packages.ubuntu.com/jammy/libxcb1-dev).
> Ubuntu dependencies also apply to Jammy

- .ci/install.sh
- .github/workflows/macos-install.sh
With #4135, artifacts are preferred over test-image-results on GitHub Actions.
So test-image-results does not need to be installed.
> Do not install test-image-results on GitHub Actions

- Tests/test_file_pdf.py
Temporarily skip the valgrind failure introduced by #6470, so that any new failing tests can be seen more clearly.
See https://github.com/radarhere/Pillow/runs/7962954391?check_suite_focus=true for a passing valgrind build with this change.
> Temporarily skip valgrind failure

- winbuild/build_prepare.py
"Test Windows" failure is failing in main.
The log contains https://github.com/python-pillow/Pillow/runs/7988137153?check_suite_focus=true#step:22:113
> fatal error C1047: The object or library file 'D:\a\Pillow\Pillow\winbuild\build\lib\lcms2_static.lib' was created by a different version of the compiler than other objects like 'build\temp.win32-3.7\Release\src\_imagingcms.obj'; rebuild all objects and libraries with the same compiler
So this PR switches lcms2 from VC2019 to VC2022.
> Build lcms2 VC2022

- Tests/test_file_apng.py
- Tests/test_file_container.py
- Tests/test_file_im.py
- Tests/test_file_libtiff.py
- Tests/test_file_mpo.py
- Tests/test_file_tga.py
- Tests/test_file_wmf.py
- Tests/test_image.py
- Tests/test_image_access.py
- Tests/test_image_convert.py
- Tests/test_image_copy.py
- Tests/test_image_crop.py
- Tests/test_image_resample.py
- Tests/test_image_resize.py
- Tests/test_image_rotate.py
- Tests/test_image_transpose.py
- Tests/test_imagedraw.py
- Tests/test_qt_image_toqimage.py
> Parametrized tests

- src/PIL/ImageTk.py
- src/_imagingtk.c
https://github.com/python-pillow/Pillow/blob/ad7be550aa539dc4c79da928dad071cf0150b731/src/_imagingtk.c#L26-L28
I saw "for new versions", and wondered how long this message has been there. It turns out, it has been there since the fork from PIL.
The code is used when ImageTk catches an AttributeError, which has also been present since the fork.
https://github.com/python-pillow/Pillow/blob/ad7be550aa539dc4c79da928dad071cf0150b731/src/PIL/ImageTk.py#L71-L85
`interpaddr()` added in Python 1.5.2. The last version of PIL supported Python 1.5.2, so it seems likely that the AttributeError catch was there for Python versions < 1.5.2.
We no longer support such early versions of Python, so this code can be removed.
> Removed support for Python versions before interpaddr()

- winbuild/README.md
https://github.com/python-pillow/Pillow/blob/d6e59bc750c0649ed26fc71a83e86e17ea862ec3/.appveyor.yml#L13-L18
https://www.appveyor.com/docs/windows-images-software/ lists Visual Studio 2017 as running on Windows Server 2016 and Visual Studio 2022 as running on Windows Server 2019.
As for GitHub Actions, it runs [Microsoft Windows Server 2022](https://github.com/python-pillow/Pillow/runs/8087262799?check_suite_focus=true#step:1:3) and uses [Visual Studio 2022.](https://github.com/python-pillow/Pillow/runs/8087262799?check_suite_focus=true#step:22:24)
> Updated tested Windows environment list

- Tests/test_file_pdf.py
- src/PIL/PdfImagePlugin.py
Since libtiff is an optional dependency, it should be optional where possible.
This PR reverts the change from #6470 if libtiff is missing.
> Do not use CCITTFaxDecode filter if libtiff is not available

- src/PIL/ImageTk.py
Continuing from https://github.com/python-pillow/Pillow/pull/6549, this PR removes support for old PyPy.
The function `interpaddr` was added to PyPy over 4 years ago: https://foss.heptapod.net/pypy/pypy/-/commit/8f15f623274f84bae5a4c3be914abb96b604a254
From the tags on that commit, I can see it was included in `release-pypy3.6-v7.0.0`, the [first Python 3.6 PyPy release](https://doc.pypy.org/en/latest/release-v7.0.0.html).
Since Python 3.5 is no longer supported by Pillow, the old code can be removed without deprecation.
> Removed support for PyPy before Python 3.6

- Tests/test_image_convert.py
- src/libImaging/Convert.c
Resolves #6496
At the moment. when converting from P to PA, the palette isn't copied to the new image.
> Copy palette when converting from P to PA

- src/PIL/TiffImagePlugin.py
Make further use of the constants at the beginning of TiffImagePlugin
https://github.com/python-pillow/Pillow/blob/196210bc804a4575b6cc0b1cb6c9b7b1f09e4ff9/src/PIL/TiffImagePlugin.py#L95-L110
> Use constants in TiffImagePlugin

- docs/handbook/image-file-formats.rst
Resolves #6545 by documenting #3327
> Documented TGA save keyword arguments

- Tests/test_image_thumbnail.py
- src/PIL/Image.py
https://github.com/python-pillow/Pillow/issues/6528#issuecomment-1228203478 has pointed out that by calling `load()` at the beginning of `thumbnail()`, the JPEG `draft()` method wouldn't perform any operations.
> `thumbnail` starts by calling the `load` function. Doesn't this defeat the purpose of the `draft` method ?
https://github.com/python-pillow/Pillow/blob/ba98fe782941bdc65601b65994bce6b013630e37/src/PIL/Image.py#L2476
#6186 added the line because `load()` may change the size of the image, and so change `thumbnail()` size calculations.
This PR rearranges the code to suit both scenarios, so that `load()` is called before size calculations **unless** `draft()` returns a result.
> Do not call load() before draft() in Image.thumbnail

- setup.cfg
- setup.py
Follow on from https://github.com/python-pillow/Pillow/pull/5784 to use declarative package configuration.
* Converted with https://github.com/gvalkov/setuptools-py2cfg
* Formatted with https://github.com/asottile/setup-cfg-fmt
> Move some static config to setup.cfg

- Tests/test_imagefont.py
* Use fixtures instead of classes to make `test_imagefont.py` a bit easier to read.
* Parameterize tests for `TransposedFont`.
* Combine `test_find_linux_font` and `test_find_macos_font` into a single parameterized test.
> Use fixtures instead of classes in test_imagefont

- Tests/test_file_bmp.py
- Tests/test_file_tga.py
- src/PIL/BmpImagePlugin.py
- src/PIL/TgaImagePlugin.py
Resolves #6494
Resolves #6572
#6060 contained a commit entitled "[Allow getpalette() to return less than 256 colors](https://github.com/python-pillow/Pillow/pull/6060/commits/948c064b282f80492f5b88d3f06a599b76516edf)"
That meant that when saving BMP and TGA images, the palette might be smaller than 256 colors. However, the plugins always specify the length of the palette as 256 for P images.
This PR changes them to match the length of the palette.
> Corrected BMP and TGA palette size when saving

- docs/reference/ExifTags.rst
I think #6586 is a topic for debate, so this PR copies a straightforward correction from it so that it can be merged at least.
There is no `TAG` dictionary in ExifTags.py. Only `TAGS`.
https://github.com/python-pillow/Pillow/blob/b8d96246f71753cbd8aaafc6dc633cad3aad0317/src/PIL/ExifTags.py#L18
> Corrected dictionary name

- README.md
- docs/index.rst
I started filling out the sections at https://bestpractices.coreinfrastructure.org/en/projects/6331 and we're currently at 76%:
Still some more to check, but we can already add the badge:
https://github.com/hugovk/Pillow/tree/add-openssf-best-practices-badge
https://pillow--6597.org.readthedocs.build/en/6597/
> Add OpenSSF Best Practices badge

- Tests/test_image.py
- src/PIL/Image.py
In `remap_palette()`, there is the following code.
https://github.com/python-pillow/Pillow/blob/ad7be550aa539dc4c79da928dad071cf0150b731/src/PIL/Image.py#L1947-L1950
Testing prior versions of Pillow, I can't find a time when the tests failed without this code, but the fact that #6060 contained a commit entitled "[Allow getpalette() to return less than 256 colors](https://github.com/python-pillow/Pillow/pull/6060/commits/948c064b282f80492f5b88d3f06a599b76516edf)" indicates to me that this requirement has been removed.
> Allow remap_palette() to return an image with less than 256 palette entries

- Tests/test_file_gif.py
- src/PIL/GifImagePlugin.py
Addresses #6389
`remap_palette` cannot map multiple palette indexes to the same output index, by its very definition. It accepts a list of palette indexes that it transforms to the position in the list. There cannot be more than one palette index at a given position in the list.
If a palette is supplied when saving a GIF image, `im.save("out.gif", palette=...)`, and that palette has duplicate entries, then the following GifImagePlugin code will try to prepare a list that maps the first of the duplicated entries to multiple locations, leaving the rest of the duplicate entries to be not strictly defined in the behaviour of `remap_palette`.
https://github.com/python-pillow/Pillow/blob/ad7be550aa539dc4c79da928dad071cf0150b731/src/PIL/GifImagePlugin.py#L519-L526
This PR fixes that, by leaving …
> Fixed GIF remapping to palette with duplicate entries

- src/PIL/ImageOps.py
Fixes ImageOps.contain function
I tried to use ImageOps.pad on an image of size (4307, 6030) and I needed to resize it to (50,70). The image was resized but it had extended only on the right side. But actually, these two sizes don't need any expansion since both sizes are proportional.
So I checked the pillow code and found that ImageOps.pad is using ImageOps.contain and in contain function there is a code for calculating new height or new width based on the size.
`new_height = int(image.height / image.width * size[0])`
or
`new_width = int(image.width / image.height * size[1])`
But the problem here is when I ran that function with (50,70), it gave output (49,70).
code explanation:
```python
size = (4307,6030)
new_width = int(image.width / …
```
> ImageOps.contain function finding new size

- docs/deprecations.rst
- docs/installation.rst
- docs/reference/ImageDraw.rst
- src/PIL/ImageFont.py
- src/libImaging/TiffDecode.c
- src/thirdparty/raqm/README.md
https://github.com/python-pillow/Pillow/actions/runs/3110428498/jobs/5041604517#step:11:571
> (    deprecations: line  253) redirect  https://www.freetype.org/ - permanently to https://freetype.org/
https://github.com/python-pillow/Pillow/actions/runs/3110428498/jobs/5041604517#step:11:462
> (    installation: line  183) redirect  https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#search-order-for-desktop-applications - permanently to https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#search-order-for-desktop-applications
> (reference/ImageDraw: line  347) redirect  https://docs.microsoft.com/en-us/typography/opentype/spec/featurelist - permanently to https://learn.microsoft.com/en-us/typography/opentype/spec/featurelis …
> Updated redirected URLs

- Tests/test_imagetk.py
- src/PIL/ImageTk.py
Resolves #6558
Runs [`apply_transparency()`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.apply_transparency) on P mode images when passing them to `tkinter.PhotoImage`. This will move the transparency from `info` into the palette in a P mode image, so that tkinter can understand the transparency information.
> Apply transparency to P images in ImageTk.PhotoImage

- src/PIL/ImagePalette.py
Addresses #6561
The discussion points out that `Image.fromarray(a, "P")` is slower than `Image.fromarray(a, "L")`. The difference is that when [`fromarray` calls `frombuffer`](https://github.com/python-pillow/Pillow/blob/d843759ca9e0295032c5123508798cfdc9aaf6ce/src/PIL/Image.py#L2974), for P mode [an ImagePalette instance is created](https://github.com/python-pillow/Pillow/blob/d843759ca9e0295032c5123508798cfdc9aaf6ce/src/PIL/Image.py#L2894-L2897). Once ImagePalette [assigns the initial palette](https://github.com/python-pillow/Pillow/blob/d843759ca9e0295032c5123508798cfdc9aaf6ce/src/PIL/ImagePalette.py#L40), it [parses the palette into a `colors` dictionary.](https://github.com/python-pillow/Pillow/blob/d843759ca9e0295032c5123508798cfdc9aaf6ce/src/PIL/ImagePalette.py#L56-L61) This …
> Defer parsing of palette into colors

- docs/releasenotes/5.2.0.rst
- docs/releasenotes/versioning.rst
https://github.com/python-pillow/Pillow/actions/runs/3113355066/jobs/5047881943#step:11:560
> (releasenotes/5.2.0: line  108) broken    https://pillow.readthedocs.io/en/5.1.x/about.html#why-a-fork - 404 Client Error: Not Found for url: https://pillow.readthedocs.io/en/5.1.x/about.html
The link is shown at https://pillow.readthedocs.io/en/stable/releasenotes/5.2.0.html#resolve-confusion-getting-pil-pillow-version-string. It is a deliberate example of a broken URL, so I've reworded the sentence to avoid referring to it
https://github.com/python-pillow/Pillow/actions/runs/3113355066/jobs/5047881943#step:11:515
> (releasenotes/versioning: line   24) broken    https://github.com/python-pillow/Pillow/blob/main/RELEASING.md#point-release - Anchor 'point-release' not found
> …
> Fixed broken URLs

- .github/workflows/test.yml
- Makefile
- docs/Makefile
Moves the sphinx requirements from https://github.com/python-pillow/Pillow/blob/af8260ee5505642ff7d97ff7d53660ca9a609cab/.github/workflows/test.yml#L102 to https://github.com/python-pillow/Pillow/blob/af8260ee5505642ff7d97ff7d53660ca9a609cab/docs/Makefile#L45-L47 so that `make doc` can ensure that all of the dependencies are installed.
Also ensures that Pillow and olefile are installed, two more requirements for building the docs.
> Ensure dependencies are installed when building docs

- CHANGES.rst
- src/PIL/ImageOps.py
Resolves #6595
This pull request fix `ImageOps.pad` method. In previous version of this method it doesn't copy the palette, and whats why it might change the image to full black image.
* Add copy origin image palette to pad image.
> Improved palette handling in ImageOps

- .github/workflows/cifuzz.yml
- .github/workflows/lint.yml
- .github/workflows/release-drafter.yml
- .github/workflows/stale.yml
- .github/workflows/test-cygwin.yml
- .github/workflows/test-docker.yml
- .github/workflows/test-mingw.yml
- .github/workflows/test-valgrind.yml
- .github/workflows/test-windows.yml
- .github/workflows/test.yml
- .github/workflows/tidelift.yml
This will cancel outdated jobs in favor of new jobs. So if you push some changes, and then push some more changes while the first changes are still being tested, the first tests will be cancelled in favor of the new tests.
Also if you reset to the previous commit and force push that, it will actually un-cancel the previously cancelled tests for that commit.
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
> Add "concurrency" to GitHub Actions

- docs/reference/ImageDraw.rst
> Improve documentation for ImageDraw.rectangle and rounded_rectangle

- docs/handbook/image-file-formats.rst
In #6585, a user didn't notice when the JPEG open options stopped and the JPEG saving options started in https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#jpeg
This PR adds headings before each listing of options in the document.
> Added headings before listing options

- docs/deprecations.rst
- docs/reference/ImageDraw.rst
- docs/releasenotes/9.2.0.rst
- src/PIL/ImageFont.py
> Improved documentation of ImageDraw return values

- Tests/test_000_sanity.py
Since we're [considering](https://github.com/python-pillow/Pillow/issues/6614#issuecomment-1256599460) deprecating `import PIL.Image`, this PR removes a use of that from the test suite.
> Do not import PIL.Image

- src/libImaging/Paste.c
Resolves #6649
Improves performance by running `strcmp` against `imOut->mode` once, instead of repeatedly within loops.
> Moved mode check outside of loops

- src/PIL/ImageFont.py
> Improved layout_engine documentation

- Tests/test_imagepalette.py
- src/PIL/ImagePalette.py
Fixes #6652 
Raise ValueError when a translucent or transparent RGBA color is used with `ImagePalette.getcolor` in
a RGB mode instance.
> Raise an error when allocating translucent color to RGB palette

- Tests/test_file_im.py
- src/PIL/ImImagePlugin.py
#6060 contained a commit entitled "[Allow getpalette() to return less than 256 colors](https://github.com/python-pillow/Pillow/pull/6060/commits/948c064b282f80492f5b88d3f06a599b76516edf)"
This meant that there were fewer bytes when saving in IM.
https://github.com/python-pillow/Pillow/blob/1d1a22bde37baaf162f4dd26e7b94cd96d3116a2/src/PIL/ImImagePlugin.py#L355
But IM still expected 768 bytes when reading.
https://github.com/python-pillow/Pillow/blob/1d1a22bde37baaf162f4dd26e7b94cd96d3116a2/src/PIL/ImImagePlugin.py#L220
So this PR pads the palette to 768 bytes when saving.
> Pad IM palette to 768 bytes when saving

- Tests/test_file_webp_metadata.py
- src/PIL/WebPImagePlugin.py
Resolves #6580
As seen before in #4677, WebP images do not require the `b"Exif\x00\x00"` prefix in their EXIF data.
This PR removes it when saving, for the sake of creating smaller files.
> Removed EXIF prefix when saving WebP

- Tests/test_file_gif.py
- src/PIL/GifImagePlugin.py
Resolves #6590 
At the moment, the first frame of a GIF is never RGBA.
https://github.com/python-pillow/Pillow/blob/b8d96246f71753cbd8aaafc6dc633cad3aad0317/src/PIL/GifImagePlugin.py#L302-L308
This PR changes it to be RGBA if there is transparency and `LoadingStrategy.RGB_ALWAYS` is used. In that situation, `transparency` should not be set in the `info` dictionary, because the transparency is a palette index, and the image is in RGBA mode.
> If first GIF frame has transparency for RGB_ALWAYS loading strategy, use RGBA mode

- src/PIL/ImageShow.py
Helps #6608
The issue requests that multiple frames be displayed when using ImageShow. This PR adds the `save_all` argument.
> Show all frames in ImageShow

- docs/handbook/concepts.rst
Resolves #4887 by documenting that Pillow does not yet support high bit depth multichannel images.
See also #1888
> High bit depth multichannel images are not yet supported

- Tests/test_imagemath.py
The following test function
https://github.com/python-pillow/Pillow/blob/f63cc582b7d305780762f786cf61e602f7398b0d/Tests/test_imagemath.py#L6-L12
is used like so
https://github.com/python-pillow/Pillow/blob/f63cc582b7d305780762f786cf61e602f7398b0d/Tests/test_imagemath.py#L30
If the `print` statement is reached, then the assertion will fail anyway, so it is just debugging code. This PR removes it.
> Removed print statement from tests

- src/PIL/PngImagePlugin.py
Cherry-picking a commit from #2941
https://github.com/python-pillow/Pillow/blob/bdbf59d15178633b6b492c0cd27892894d0283ab/src/PIL/PngImagePlugin.py#L160-L164
https://github.com/python-pillow/Pillow/blob/bdbf59d15178633b6b492c0cd27892894d0283ab/src/PIL/PngImagePlugin.py#L191-L192
Ok, so when it is closing, it sets `fp` and `queue` to `None`, fair enough. What is `crc`?
https://github.com/python-pillow/Pillow/blob/bdbf59d15178633b6b492c0cd27892894d0283ab/src/PIL/PngImagePlugin.py#L204
...it's a method? I don't see why this should be set to `None`.
#2935 shows that it used to be sometimes set to `crc_skip`, but that still doesn't explain it to me.
Looking at that PR, I conclude that
https://github.com/python-pillow/Pillow/blob/bdbf59d15178633b6b492c0cd27892894d0283ab/src/PIL/PngImagePlugin.py# …
> Don't reassign crc on ChunkStream close

- src/PIL/Image.py
Resolves #6658
This PR documents that when converting a PA image with an RGBA palette, the alpha values from the image are used, rather than the values from the palette.
```python
from PIL import Image, ImagePalette
im = Image.new("PA", (1, 2))
p = ImagePalette.ImagePalette("RGBA")
first = p.getcolor((1, 2, 3, 4))
second = p.getcolor((5, 6, 7, 8))
im.putpalette(p)
im.putpixel((0, 0), (first, 100))
im.putpixel((0, 1), (second, 200))
im_rgba = im.convert("RGBA")
print("(0, 0):", im_rgba.load()[0, 0])
print("(0, 1):", im_rgba.load()[0, 1])
```
gives
```
(0, 0): (1, 2, 3, 100)
(0, 1): (5, 6, 7, 200)
```
> Image channel is used when converting PA with an RGBA palette

- Tests/test_file_apng.py
- src/PIL/PngImagePlugin.py
Resolves #6608
At the moment, when saving multiple frames with PngImagePlugin, the mode of the first image is used.
https://github.com/python-pillow/Pillow/blob/af8260ee5505642ff7d97ff7d53660ca9a609cab/src/PIL/PngImagePlugin.py#L1224
However, this is not necessarily ideal. For a GIF, the first frame might be P, and subsequent frames might be RGB. Converting the RGB frames to P could result in loss of information.
This PR loops through the frames to be saved, checks if any are RGB, RGBA or P, and upgrades the mode accordingly.
> Consider all frames when selecting mode for PNG save_all

- Tests/test_image_convert.py
- src/PIL/Image.py
While investigating #6643, I found that
```pycon
>>> Image.new("RGB", (1, 1)).convert("XYZ")
File "PIL/Image.py", line 1035, in convert
ValueError: conversion from RGB to XYZ not supported
During handling of the above exception, another exception occurred:
File "PIL/Image.py", line 1040, in convert
ValueError: conversion from RGB to XYZ not supported
>>> 
```
It looks odd that "ValueError: conversion from RGB to XYZ not supported" is raised twice. One would expect the first time to be enough.
This is because of the following code. The intention is that if A -> B isn't supported, then maybe A -> C -> B will work, using the base mode as the intermediary. …
> Do not attempt normalization if mode is already normal

- Tests/test_image_convert.py
- src/PIL/Image.py
> Added conversion between RGB/RGBA/RGBX and LAB

- docs/releasenotes/9.1.0.rst
- docs/releasenotes/9.3.0.rst
Added release notes for #6449 and #6611
> Added release notes for #6449 and #6611

- Tests/helper.py
- Tests/test_file_jpeg.py
- Tests/test_file_libtiff.py
- Tests/test_file_png.py
- Tests/test_file_ppm.py
- Tests/test_file_tiff.py
- Tests/test_image.py
- Tests/test_image_access.py
- Tests/test_imagemath.py
- setup.py
Fixed some pylint issues
Fixes # unnecessary elses, conditional checks, import structure and encodings
* fixes to pylint warnings
> pylint warnings

- Tests/test_file_ppm.py
test_file_ppm.py sometimes writes in binary format
https://github.com/python-pillow/Pillow/blob/be8a28d03d8a19add45fd3c9ec57d4499c23af1d/Tests/test_file_ppm.py#L196-L197
and sometimes does not.
https://github.com/python-pillow/Pillow/blob/be8a28d03d8a19add45fd3c9ec57d4499c23af1d/Tests/test_file_ppm.py#L243-L244
This PR consistently writes in binary format in test_file_ppm.py.
> Consistently write in binary format in PPM tests

- docs/releasenotes/9.3.0.rst
Sequel to #6680
The security issue was introduced with #4685 in Pillow 9.1.0.
> Document when BLP1 JPEG data started being loaded incorrectly

- docs/reference/ExifTags.rst
- src/PIL/ExifTags.py
Alternative to #6586
This PR effectively copies the data from `ExifTags.TAGS` and `ExifTags.GPSTAGS` into two new `IntEnum` classes, `ExifTags.Base` and `ExifTags.GPS`.
The advantage of this is ease of mapping a tag name to a tag number. Rather than
```pycon
>>> from PIL.ExifTags import TAGS
>>> for value, name in TAGS.items():
...   if name == "ImageDescription":
...     print(value)
... 
270
```
users could
```pycon
>>> from PIL.ExifTags import Base
>>> Base.ImageDescription.value
270
```
> Added ExifTags enums

- docs/reference/ImageDraw.rst
- src/PIL/ImageDraw.py
For https://github.com/python-pillow/Pillow/issues/6480#issuecomment-1208658621
* Document `ImageDraw` attributes `font`, `fontmode`, `ink`, `fill`.
* Change `self.fill = 0` to `self.fill = False` to match its use as a bool.
> Document ImageDraw attributes

- src/libImaging/Matrix.c
Resolves #6520
Related to 
* https://github.com/python-pillow/Pillow/issues/2635
* https://github.com/python-pillow/Pillow/issues/2664#issuecomment-328666279
* Release python GIL when converting images using matrix operations
Thank you for reviewing!
> Release Python GIL when converting images using matrix operations

- src/_imagingft.c
Fixes possible buffer overflow.
> Fix malloc in _imagingft.c:font_setvaraxes

- docs/releasenotes/9.3.0.rst
Include https://github.com/python-pillow/Pillow/issues/6369 and https://github.com/python-pillow/Pillow/pull/6418.
> Update release notes for 9.3.0

- src/libImaging/Convert.c
Fixes link error on Visual Studio 2019 14.29.30133 with Windows 10 SDK 10.0.19041.0:
```
ucrt.lib(api-ms-win-crt-math-l1-1-0.dll) : error LNK2005: round already defined in Convert.obj
Creating library build\temp.win-amd64-3.10\Release\src\_imaging.cp310-win_amd64.lib and object build\temp.win-amd64-3.10\Release\src\_imaging.cp310-win_amd64.exp
build\lib.win-amd64-3.10\PIL\_imaging.cp310-win_amd64.pyd : fatal error LNK1169: one or more multiply defined symbols found
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\link.exe' failed with exit code 1169
```
> Remove backup implementation of Round for Windows platforms

- .github/workflows/test-windows.yml
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> GHA: replace deprecated set-output command with GITHUB_OUTPUT file

- setup.py
Fixes #6437.
@cgohlke found a failure with setuptools 65 on Python 3.7-3.8 but with `SETUPTOOLS_USE_DISTUTILS=stdlib`
Testing a CI matrix on Windows with:
```yml
python-version: ["3.7", "3.8", "3.9"]
architecture: ["x64"]
SETUPTOOLS_USE_DISTUTILS: ["", "stdlib"]
setuptools-max-version: ["60", "66"]
```
I [find](https://github.com/hugovk/Pillow/actions/runs/3344698796) that:
CPython | SETUPTOOLS_USE_DISTUTILS | setuptools | Quotes needed
-- | -- | -- | --
3.7 |   | <60 | double
3.7 |   | <66 | double
3.7 | stdlib | <60 | double
3.7 | stdlib | <66 | double
3.8 |   | <60 | double
3.8 |   | <66 | double
3.8 | stdlib | <60 | double
3.8 | stdlib | <66 | double
3.9 |   | <60 | single
3.9 |   | <66 | single
3.9 | stdlib | <60 | single
3.9 | stdlib | <66 | single
Testing this fix on the same …
> Double quotes for old CPython on Windows

- src/Tk/tkImaging.c
> Inline fname2char to fix memory leak

- Tests/test_file_pdf.py
- docs/releasenotes/9.3.0.rst
- src/libImaging/TiffDecode.c
When saving a TIFF image to a file object using libtiff, the buffer was not initialized. This behaviour introduced in Pillow 2.0.0, and has now been fixed.
> Initialize libtiff buffer when saving

- Tests/test_image_access.py
This test has been a constant annoyance: https://github.com/python-pillow/Pillow/issues/6679#issuecomment-1296068430, https://github.com/python-pillow/Pillow/pull/5811#issuecomment-965165151
This PR marks it as a "known failing test".
> Add xfail mark to TestEmbeddable

- Tests/test_imagegrab.py
Resolves #6710
#6361 added support for `gnome-screenshot` in ImageGrab on Linux, but didn't update `test_grab_no_xcb` in light of the fact that something else might be used instead of XCB on Linux.
> XCB will not be used by default on Linux if gnome-screenshot is present

- winbuild/build_prepare.py
Likely fix for #6701.
This is automatically enabled when compiling C++ with modern Visual Studio to [reduce the binary size of try/catch blocks](https://devblogs.microsoft.com/cppblog/making-cpp-exception-handling-smaller-x64/).
It uses `VCRUNTIME140_1.dll`, which is not available out-of-the-box, and needs to be included in the wheels.
However, I find there is almost no difference to the size of `_imagingft.{...}.pyd` when disabling it (disabling it actually saves 3KB), and it removes the need to include `VCRUNTIME140_1.dll` in the wheels.
> Disable __CxxFrameHandler4 when compiling HarfBuzz

- Makefile
* Ensures when developing that compilation warnings are visible
* Provides feedback that compilation has occured.
> Use verbose flag for pip install

- Tests/test_bmp_reference.py
Since #6674, Tests/test_bmp_reference.py has started [printing](https://github.com/python-pillow/Pillow/blob/86b4cb6d14553d93b65ca6fbd76c433ae515aeeb/Tests/test_bmp_reference.py#L51)
> Please add Tests/images/bmp/q/pal4rletrns.bmp to the partially supported bmp specs.
> Added file to list of partially supported BMPs

- src/_imaging.c
src/_imaging.c:1842:17: warning: ‘ImagingTransform’ accessing 64 bytes in a region of size 48 [-Wstringop-overflow=]
1842 |         imOut = ImagingTransform(
|                 ^~~~~~~~~~~~~~~~~
1843 |             imOut, imIn, IMAGING_TRANSFORM_AFFINE, 0, 0, xsize, ysize, a, filter, 1);
|             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/_imaging.c:1842:17: note: referencing argument 8 of type ‘double *’
> Fix compiler error: accessing 64 bytes in a region of size 48

- winbuild/build_prepare.py
Originally submitted in https://github.com/nulano/pypy_ext/pull/2 by @TrellixVulnTeam:
> # Patching [CVE-2007-4559](https://github.com/advisories/GHSA-gw9q-c7gh-j9vm)
> Hi, we are security researchers from the Advanced Research Center at [Trellix](https://www.trellix.com). We have began a campaign to patch a widespread bug named [CVE-2007-4559](https://github.com/advisories/GHSA-gw9q-c7gh-j9vm). [CVE-2007-4559](https://github.com/advisories/GHSA-gw9q-c7gh-j9vm) is a 15 year old bug in the Python tarfile package. By using extract() or extractall() on a tarfile object without sanitizing input, a maliciously crafted .tar file could perform a directory path traversal attack. We found at least one unsantized extractall() in your codebase and are providing a patch for you via pull request. The …
> CVE-2007-4559 patch in winbuild

- .appveyor.yml
Helps #6575
Python 3.11.0 has been deployed to AppVeyor - https://www.appveyor.com/updates/2022/11/07/
> Updated AppVeyor to Python 3.11

- docs/reference/ExifTags.rst
- src/PIL/ExifTags.py
Helps #6641
Using https://exiftool.org/TagNames/EXIF.html as a reference, adds an `Interop` enum to ExifTags.py.
> Added Interop to ExifTags

- .github/workflows/lint.yml
- .github/workflows/test-windows.yml
- .github/workflows/test.yml
Use Python 3.11 instead of 3.10 in GitHub Actions when
- running lint
- uploading Fribidi
- checking the documentation
> Update to Python 3.11 in GitHub Actions

- .github/workflows/macos-install.sh
Reverts #4711, as I find that macOS PyPy no longer fails without it.
This is likely because [NumPy 1.21 enabled Accelerate](https://numpy.org/doc/stable/release/1.21.0-notes.html#enable-accelerate-framework). This was the [motivation](https://github.com/python-pillow/Pillow/pull/4710#issuecomment-647081765) for switching to OpenBLAS, as there were [problems with it.](https://github.com/numpy/numpy/issues/15947)
> Revert "Install NumPy with OpenBLAS"

- src/PIL/PyAccess.py
- src/libImaging/Access.c
- src/libImaging/Imaging.h
This method isn't used anywhere, and PyAccess doesn't implement it (because it's not used).
> Remove ImagingAccessInit line() method

- Tests/test_file_mpo.py
- src/PIL/MpoImagePlugin.py
As noted in https://github.com/python-pillow/Pillow/issues/6720#issuecomment-1308617053, https://web.archive.org/web/20190227081740/http://www.cipa.jp/std/documents/e/DC-007_E.pdf states that
> 5.2.3.1. MP Format Version
> This tag specifies the version of the MP Extensions. An MP File that complies with this specification shall specify a 4 byte ASCII value of “0100.”
This PR adds "MP Format Version" when saving MPO images.
> Added MP Format Version when saving MPO

- Tests/test_file_webp_alpha.py
- docs/handbook/image-file-formats.rst
- docs/releasenotes/9.4.0.rst
- src/PIL/WebPImagePlugin.py
- src/_webp.c
When encoding a transparent image with WebP, even if specified to be lossless, it'll drop the information that is not visible. This is normally fine, except for applications where you need to undo the mask or make additional changes later.
There's an option in the `WebPConfig` data structure named `exact`:
```C++
int exact;           // if non-zero, preserve the exact RGB values under
// transparent area. Otherwise, discard this invisible
// RGB information for better compression. The default
// value is 0.
```
This option is not exposed to the users. In this pull request, I make this option available.
The parameter `exact` is True/False at the python level but translated to `0 or 1 (int)` to match that of `WebPConfig`.
* Updated the binding at …
> Added WebP encoding with exact config

- .github/workflows/test-cygwin.yml
Alternative to #6759
[pyroma 4.1 was released yesterday](https://github.com/regebro/pyroma/tags). It now [requires setuptools >= 61](https://github.com/regebro/pyroma/blob/28387e8c6b3dd2fa588e78fb0bf6af348d04a532/setup.cfg#L41). This has started Cygwin failing in main - https://github.com/python-pillow/Pillow/actions/runs/3544062653
This PR uses `SETUPTOOLS_USE_DISTUTILS=stdlib`, [as suggested previously.](https://github.com/python-pillow/Pillow/issues/6216#issuecomment-1122340162)
> Use stdlib for setuptools on Cygwin

- Tests/test_file_webp_metadata.py
- docs/releasenotes/9.4.0.rst
- src/PIL/WebPImagePlugin.py
> Added getxmp() to WebPImagePlugin

- docs/installation.rst
> Document how to install Pillow from a directory

- src/_webp.c
This fixes
```
src/_webp.c:494:5: warning: cast between incompatible function types from ‘PyObject * (*)(PyObject *)’ {aka ‘struct _object * (*)(struct _object *)’} to ‘void (*)(PyObject *)’ {aka ‘void (*)(struct _object *)’} [-Wcast-function-type]
494 |     (destructor)_anim_encoder_dealloc, /*tp_dealloc*/
|     ^
```
Or to put that a bit more clearly, the function type of the destructor functions should be `void (*)(PyObject *)` not `PyObject * (*)(PyObject *)`.
> Fix WebP dealloc method definitions

- .github/workflows/test-windows.yml
Most of the Windows builds have started failing in the main branch - https://github.com/python-pillow/Pillow/actions/runs/3600683266
> error C1047: The object or library file 'D:\a\Pillow\Pillow\winbuild\build\lib\lcms2_static.lib' was created by a different version of the compiler than other objects like 'build\temp.win32-3.7\Release\src\_imagingcms.obj'; rebuild all objects and libraries with the same compiler
This has occurred previously in #5051. The solution was to change the cache key for the Windows build. This PR does that by updating a comment.
In #4701, a comment was added
https://github.com/python-pillow/Pillow/blob/5bdf63e1d170e1db324c5f805c4e838e4d455e98/.github/workflows/test-windows.yml#L144
There were 9 jobs at the time, but there are now more than that.
> Remove specific number of jobs from comment

- .editorconfig
- docs/Makefile
- docs/conf.py
- docs/installation.rst
- setup.cfg
Follow on from https://github.com/python-pillow/Pillow/issues/6755 / https://github.com/python-pillow/Pillow/pull/6756
* Use [Sphinx Inline Tabs](https://sphinx-inline-tabs.readthedocs.io/) to group the installation instructions by operating system
* This helps hide irrelevant information on long, detailed page
* If, for example, you click the macOS tab in the first tab group, it also opens the macOS tab in the second group
* Because the subheaders are gone, I added in `.. _Linux Installation:` etc. to avoid linkrot
* I re-ordered them to go: Linux, macOS, Windows, [Windows variant,] FreeBSD, [Android]
* My thinking was to put the main three first, in order of "likelihood" to needs to follow these instructions, then the others afterwards, but happy …
> Use Sphinx Inline Tabs to organise installation per OS

- .github/workflows/test-windows.yml
- .github/workflows/test.yml
* PyPy v7.3.10 has been released
* https://www.pypy.org/posts/2022/12/pypy-v7310-release.html
* Includes PyPy3.9 as a non-beta release:
* "We have gained confidence in the stability of this version, and are removing the "beta" label."
* Drops PyPy3.7
Currently https://github.com/actions/setup-python is still pointing to v7.3.9 but should bump up in a day or two.
> Add support for PyPy3.9, drop PyPy3.7
