python-pillow/Pillow

- CHANGES.rst
- Tests/test_file_jpeg.py
- src/PIL/JpegImagePlugin.py
- src/encode.c
- src/libImaging/JpegEncode.c
Fixes #6773 
* a JPEG COM segment can now be written during `Image.save`
* opening a JPEG file and saving to another file will now copy any existing comment across
* user can now do `image.save(filename, format='JPEG', comment='comment to be written')` and the comment will be written to a COM segment
> Support saving JPEG comments

- .pre-commit-config.yaml
- tox.ini
Calling `make` (without `allowlist_externals = make` in `tox.ini`) gives a deprecation warning in tox 3 and an error in tox 4.
Add `allowlist_externals = make` to remove the warning and error.
Also format `tox.ini` with https://github.com/tox-dev/tox-ini-fmt
Warns about using `make` without `allowlist_externals`
```console
$ tox -e py311
GLOB sdist-make: /Users/hugo/github/Pillow/setup.py
py311 create: /Users/hugo/github/Pillow/.tox/py311
py311 installdeps: cffi, numpy
py311 inst: /Users/hugo/github/Pillow/.tox/.tmp/package/5/Pillow-9.4.0.dev0.zip
py311 installed: attrs==22.1.0,build==0.9.0,certifi==2022.12.7,cffi==1.15.1,charset-normalizer==2.1.1,check-manifest==0.49,coverage==6.5.0,defusedxml==0.7.1,docutils==0.19,idna==3.4,iniconfig==1.1.1,markdown2==2.4.6,numpy==1.23.5,olefile==0.46,pa …
```
> Add allowlist_externals=make to fix tox 4

- .pre-commit-config.yaml
- src/PIL/ImageShow.py
* Add[ Bandit](https://bandit.readthedocs.io) to the CI via pre-commit
* Let's limit to high severity in the `src` directory
* And mark the one existing finding as `nosec`
> Run Bandit on CI via pre-commit

- src/PIL/BlpImagePlugin.py
Resolves #6741
libjpeg 9e has decided to no longer detect the JPEG embedded within Tests/images/blp/blp1_jpeg.blp as being CMYK.
To allow our tests to still pass, if the BLP JPEG is in CMYK mode, this PR passes a value for [`jpegmode`](https://github.com/python-pillow/Pillow/blob/0ec32a30120cb22b533fd8563749d44bd5d3f78f/src/decode.c#L824-L833), so that [JpegDecode.c will override what libjpeg has detected.](https://github.com/python-pillow/Pillow/blob/0ec32a30120cb22b533fd8563749d44bd5d3f78f/src/libImaging/JpegDecode.c#L183-L195)
Testing in libjpeg 9d and 9e in my fork of pillow-wheels, the BLP tests [fail without this](https://github.com/radarhere/pillow-wheels/actions/runs/3579890161), and [pass with it.](https://github.com/radarhere/pillow-wheels/actions/runs/3579892207)
> When reading BLP, do not trust JPEG decoder to determine image is CMYK

- winbuild/build_prepare.py
harfbuzz 6.0.0 has been released - https://github.com/harfbuzz/harfbuzz/releases/tag/6.0.0
> Updated harfbuzz to 6.0.0

- src/PIL/PpmImagePlugin.py
https://github.com/python-pillow/Pillow/actions/runs/3745012260/jobs/6358985335#step:8:4128
> Tests/test_file_ppm.py::test_plain_invalid_data[P1\n128 128\n1009]
>   /opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/PIL/PpmImagePlugin.py:211: BytesWarning: str() on a bytes instance
>     raise ValueError(f"Invalid token for this mode: {bytes([token])}")
> 
> Tests/test_file_ppm.py::test_plain_ppm_token_too_long[P3\n128 128\n255\n012345678910]
>   /opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/PIL/PpmImagePlugin.py:245: BytesWarning: str() on a bytes instance
>     f"Token too long found in data: {half_token[:max_len + 1]}"
> 
> Tests/test_file_ppm.py::test_plain_ppm_token_too_long[P3\n128 128\n255\n012345678910 0]
> …
> Fixed BytesWarnings

- Tests/test_file_gif.py
- src/PIL/GifImagePlugin.py
Resolves #6791
The user found a WebP image with `info["background"]` of `(255, 255, 255, 0)`. When the user attempts to save this as a GIF, an error is thrown, because GifImagePlugin can't add this transparent color to the RGB palette of the GIF.
This PR solves this by simply ignoring transparent or translucent background colors when saving as GIF.
> Ignore non-opaque WebP background when saving as GIF

- Tests/test_numpy.py
https://github.com/python-pillow/Pillow/actions/runs/3730334148/jobs/6327268745#step:8:4081
> /home/runner/work/Pillow/Pillow/Tests/test_numpy.py:196: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
See also the NumPy release notes
https://numpy.org/devdocs/release/1.24.0-notes.html#np-str0-and-similar-are-now-deprecated
> The scalar type aliases ending in a 0 bit size: np.object0, np.str0, np.bytes0, np.void0, np.int0, np.uint0 as well as np.bool8 are now deprecated and will eventually be removed.
> Updated deprecated NumPy alias

- src/libImaging/Quant.c
https://github.com/python-pillow/Pillow/actions/runs/3752682144/jobs/6375115871#step:7:141
>   src/libImaging/Quant.c: In function ‘ImagingQuantize’:
>   src/libImaging/Quant.c:1720:29: warning: ‘b’ may be used uninitialized in this function [-Wmaybe-uninitialized]
>    1720 |         unsigned char r, g, b;
>         |                             ^
>   src/libImaging/Quant.c:1720:26: warning: ‘g’ may be used uninitialized in this function [-Wmaybe-uninitialized]
>    1720 |         unsigned char r, g, b;
>         |                          ^
>   src/libImaging/Quant.c:1720:23: warning: ‘r’ may be used uninitialized in this function [-Wmaybe-uninitialized]
>    1720 |         unsigned char r, g, b;
>         |                       ^
> Initialize unsigned char variables

- docs/handbook/concepts.rst
Helps #6786
Inputting HSV (359.9, 100%, 100%) into https://www.rapidtables.com/convert/color/hsv-to-rgb.html, I get RGB (255, 0, 0).
```python
>>> im = Image.new("HSV", (1, 1), (255, 255, 255))
>>> im.convert("RGB").getpixel((0, 0))
(255, 0, 0)
```
I would therefore conclude that the H value ranges from 0-360, excluding 360.
> Improved mode range documentation

- Tests/test_file_mpo.py
- src/PIL/MpoImagePlugin.py
MpoImagePlugin initially writes blank MPF data, and then returns to write out the offsets once the length of the JPEG data is known.
However, the offset for the MPF data didn't consider that EXIF data might be part of the header. This PR fixes that.
> Fixed saving EXIF data to MPO

- Tests/test_file_png.py
- src/PIL/PngImagePlugin.py
Resolves #6804
Do not use `im.info["exif"]` when saving PNG files, to be consistent with other formats - [JPEG](https://github.com/python-pillow/Pillow/blob/edcfe09f12d6113aaca3a4b3f9bad343c0ddbdb9/src/PIL/JpegImagePlugin.py#L749), [TIFF](https://github.com/python-pillow/Pillow/blob/edcfe09f12d6113aaca3a4b3f9bad343c0ddbdb9/src/PIL/TiffImagePlugin.py#L1605) and [WebP](https://github.com/python-pillow/Pillow/blob/edcfe09f12d6113aaca3a4b3f9bad343c0ddbdb9/src/PIL/WebPImagePlugin.py#L323)
> Do not use EXIF from info when saving PNG images

- Tests/test_file_ico.py
- src/PIL/IcoImagePlugin.py
As with GifImagePlugin
https://github.com/python-pillow/Pillow/blob/edcfe09f12d6113aaca3a4b3f9bad343c0ddbdb9/src/PIL/GifImagePlugin.py#L325-L333
and PngImagePlugin
https://github.com/python-pillow/Pillow/blob/edcfe09f12d6113aaca3a4b3f9bad343c0ddbdb9/src/PIL/PngImagePlugin.py#L1004-L1006
after replacing `self.im`, `self.pyaccess` should be cleared.
> Fixed PyAccess after changing ICO size

- docs/installation.rst
- winbuild/build_prepare.py
libtiff 4.5.0 has been released - http://www.simplesystems.org/libtiff/
The first patch
https://github.com/python-pillow/Pillow/blob/8bd5fbf450f9f5a03a32c7efcfb488bfc2a40d1c/winbuild/build_prepare.py#L207-L211
is now a part of libtiff, thanks to https://gitlab.com/libtiff/libtiff/-/commit/58ad3b5635896a143ad4ed9f4494a5c834098ace
> Updated libtiff to 4.5.0

- Tests/oss-fuzz/build.sh
CIFuzz haas started failing in main - https://github.com/python-pillow/Pillow/actions/runs/3779249022/jobs/6424360160
> Unable to find "/usr/local/lib/libtiff.so.5" when adding binary and data files.
> Updated libtiff shared library name

- Tests/test_image_convert.py
- src/libImaging/Convert.c
Resolves #6706. Alternative to #6707
The new conversion function is just a copy of
https://github.com/python-pillow/Pillow/blob/a4ec9f331c11cd8ad05137bc78dff8197e8af2e3/src/libImaging/Convert.c#L463-L480
except with the last channel set to 255, as happens in other conversions to RGB.
https://github.com/python-pillow/Pillow/blob/a4ec9f331c11cd8ad05137bc78dff8197e8af2e3/src/libImaging/Convert.c#L436-L446
> Added conversion from RGBa to RGB

- Tests/test_image_putdata.py
- src/_imaging.c
Helps https://github.com/python-pillow/Pillow/issues/6769#issuecomment-1364769723 by adding support for "I;16", "I;16L" and "I;16B" in `putdata()`.
The C code did not previously consider that the values had a `pixelsize` of 2.
> Added support for I;16 modes in putdata()

- src/PIL/Image.py
A user in https://github.com/python-pillow/Pillow/issues/6797#issuecomment-1345620052 thought that `apply_transparency()` did something for non-P mode images.
This clarifies that this is not the case.
> Clarify apply_transparency() docstring

- winbuild/build_prepare.py
Resolves #6679 by patching OpenJPEG to include uclouvain/openjpeg#1423
> Patch OpenJPEG to include ARM64 fix

- Tests/test_imagegrab.py
- src/PIL/ImageGrab.py
Resolves #6751, by using [`wl-paste`](https://github.com/bugaevc/wl-clipboard) or [`xclip`](https://github.com/astrand/xclip) for `ImageGrab.grabclipboard()` on Linux.
> If available, use wl-paste or xclip for grabclipboard() on Linux

- docs/handbook/concepts.rst
Helps https://github.com/python-pillow/Pillow/discussions/6828#discussioncomment-4507520
> Document the meaning of "premultiplied alpha"

- Tests/test_file_tiff_metadata.py
- src/PIL/TiffImagePlugin.py
Resolves #6799
The image from the issue has a GPSLongitudeRef tag that [should be ASCII](https://www.awaresystems.be/imaging/tiff/tifftags/privateifd/gps/gpslongituderef.html), but is instead SHORT.
The tag is loaded as an int then, not a string as expected, and when Pillow tries to save it as a string, it fails.
This PR simply changes TiffImagePlugin to convert the variable to a string.
> Fixed writing int as ASCII tag

- src/PIL/Image.py
#6748 added reading of IFD1 in `Image.Exif`.
However, I didn't consider that zero is a special value for the offset to the next IFD.
https://www.media.mit.edu/pia/Research/deepview/exif.html
> If its value is '0x00000000', it means this is the last IFD and there is no linked IFD.
So if that is the case, don't attempt to read IFD1.
This fixes some warnings that are shown at the moment - https://github.com/python-pillow/Pillow/actions/runs/3799772426/jobs/6462615701#step:8:4148
> Tests/test_file_tiff.py::TestFileTiff::test_get_child_images[Tests/images/hopper.tif-sizes0]
> Tests/test_file_tiff.py::TestFileTiff::test_get_child_images[Tests/images/child_ifd.tiff-sizes1]
> Tests/test_file_tiff.py::TestFileTiff::test_get_child_images[Tests/images/child_ifd_jpeg.tiff-sizes2]
> …
> Do not attempt to read IFD1 if absent

- Tests/test_image.py
- docs/deprecations.rst
- docs/releasenotes/9.1.0.rst
- docs/releasenotes/9.4.0.rst
- src/PIL/Image.py
Resolves #6537
The user in the issue found a warning that `Image.BILINEAR` is deprecated, and questions whether it is necessary to deprecate this.
This PR removes the deprecation warnings for `Image.*` constants added in #5954 ([and released in Pillow 9.1.0](https://pillow.readthedocs.io/en/stable/releasenotes/9.1.0.html#constants)).
However, there are three exceptions - I've left `LINEAR`, `CUBIC` (which have been duplicates of other constants since PIL) and `ANTIALIAS` (which has been a duplicate since #1028) deprecated.
I'm also leaving the deprecations for ImageCms, ImageFont, BlpImagePlugin, FtexImagePlugin and PngImagePlugin in place.
See what you think of this.
> Removed deprecations for Image constants, except for duplicate Resampling attributes

- .github/workflows/test-valgrind.yml
- Tests/test_file_pdf.py
- Tests/test_image.py
- src/libImaging/Fill.c
`ImagingAllocateArray` [returns early](https://github.com/python-pillow/Pillow/blob/8bd5fbf450f9f5a03a32c7efcfb488bfc2a40d1c/src/libImaging/Storage.c#L393-L396) when the image has zero width or height.
This PR applies that to `ImagingFill` as well.
> Return from ImagingFill early if image has a zero dimension

- docs/releasenotes/9.4.0.rst
Added release notes for
- #6842, largely copying https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#fix-memory-dos-in-imagefont, since the solution came from a new version of that problem
- #6846, which would have only been present since Pillow 8.0.0, when `FT_Bitmap_Convert` was added by https://github.com/python-pillow/Pillow/pull/4955.
> Added release notes for #6842 and #6846

- src/PIL/Image.py
Helps #6849 by specifying that `size` is a tuple of width and height.
> Updated size parameter descriptions

- Tests/test_imagepath.py
See https://docs.python.org/3/library/array.html#array.array.tobytes
> New in version 3.2: tostring() is renamed to [tobytes()](https://docs.python.org/3/library/array.html#array.array.tobytes) for clarity.
> array tobytes() always exists in Python >= 3.2

- Tests/test_imagegrab.py
Resolves #6858
When adding support for xclip in https://github.com/python-pillow/Pillow/pull/6783/commits/2ecf88eaa621266f63405ca7e1fdbdb7ed4d5c8d, I managed to update the error text in the test, but not the conditions under which the error is raised.
> NotImplementedError will not be raised by grapclipboard if xclip is available on Linux

- README.md
- RELEASING.md
- docs/index.rst
- setup.cfg
After https://fosstodon.org/@pillow/109620196925642582, it seems that we should add posting to Fosstodon to the RELEASING checklist.
I've also added the badge to the README, and the URL to setup.cfg.
> Announce releases on Mastodon

- src/PIL/__init__.py
Helps #6843
As suggested in the issue, document at https://pillow.readthedocs.io/en/stable/PIL.html#PIL.UnidentifiedImageError that `ImageFile.LOAD_TRUNCATED_IMAGES` may allow PNG images to open that would otherwise be unidentified.
> LOAD_TRUNCATED_IMAGES may allow PNG images to open

- src/Tk/tkImaging.c
Changed the TKinter module loading function for Windows to support the rare (but possible) case of having more than 1024 modules loaded. This is an adaptation of the same fix that was added to Matplotlib in [PR #22445](https://github.com/matplotlib/matplotlib/pull/22445) to solve their [issue #22378](https://github.com/matplotlib/matplotlib/issues/22378). The same issue happens with Pillow under similar circumstances (error `RuntimeError: Could not find Tcl routines` with `PIL.ImageTk` module is loaded).
> Support arbitrary number of loaded modules on Windows

- docs/handbook/concepts.rst
- docs/reference/Image.rst
- docs/releasenotes/2.7.0.rst
- src/PIL/ImageOps.py
Resolves #6867
https://pillow.readthedocs.io/en/stable/reference/Image.html#resampling-filters lists the Resampling enum values and instructs the user to "See [Filters](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#concept-filters) for details." However, in https://pillow.readthedocs.io/en/stable/handbook/concepts.html#concept-filters we then talk about the previously existing constants.
This PR changes https://pillow.readthedocs.io/en/stable/handbook/concepts.html#concept-filters to refer to the Resampling enum values as well.
> Refer to Resampling enum

- Tests/test_file_mpo.py
- Tests/test_file_png.py
- src/PIL/GifImagePlugin.py
- src/PIL/Image.py
- src/PIL/PdfParser.py
- src/PIL/PsdImagePlugin.py
- src/PIL/TiffImagePlugin.py
- winbuild/build_prepare.py
For example, instead of:
```python
isinstance(params, list) or isinstance(params, tuple)
```
Use:
```python
isinstance(params, (list, tuple))
```
Docs: "If _classinfo_ is a tuple of type objects (or recursively, other such tuples) or a Union Type of multiple types, return `True` if _object_ is an instance of any of the types."
https://docs.python.org/3/library/functions.html#isinstance
For example, instead of:
```python
key in TiffTags.TAGS_V2_GROUPS.keys()
```
Use:
```python
key in TiffTags.TAGS_V2_GROUPS
```
Docs: "For mapping objects, this should consider the keys of the mapping rather than the values or the key-item pairs."
https://docs.python.org/3/reference/datamodel.html#object.__contains__
For example, instead of:
```python
frame_number = 0
for mpentry in mpinfo[0xB002]:
... …
```
> Simplify isinstance, key in dict, enumerate

- Tests/test_file_gif.py
- Tests/test_image_mode.py
Convert a couple of internal `check()` functions to use `@pytest.mark.parametrize`.
> Tests: Convert internal check() functions to use parametrize

- docs/installation.rst
I noticed that #5365 omitted documentation for the build flags `--disable-raqm` and `--enable-raqm`.
This PR adds them to the documentation.
The order is the same as in `setup.py`.
> List Raqm build options in installation documentation

- src/PIL/EpsImagePlugin.py
EpsImagePlugin reads 160 characters from the file when finding the offset.
https://github.com/python-pillow/Pillow/blob/c2e2da4a2245dd42131fb47e19aa0ff06ee088cb/src/PIL/EpsImagePlugin.py#L319
However, it only uses 4 or 12 characters.
> Only read when necessary in EpsImagePlugin

- Tests/test_image_filter.py
- src/PIL/ImageFilter.py
- src/libImaging/BoxBlur.c
Fixes #6873.
* There's a segmentation fault when _using_ a filter with a negative radius
* A radius of zero has a special meaning (do not blur, returns identical image)
* https://pillow.readthedocs.io/en/stable/reference/ImageFilter.html#PIL.ImageFilter.BoxBlur
* So let's raise a `ValueError` when _creating_ a filter with a negative radius
* We could raise it when _using_ the filter, but why not already do so when creating?
> Raise ValueError for BoxBlur filter with negative radius

- docs/index.rst
Follow on to https://github.com/python-pillow/Pillow/pull/6861.
Add a hidden verified link to https://fosstodon.org/@pillow, following tips in this thread:  https://fosstodon.org/@readthedocs/109428014312327759
Quick test with my fork:
https://hugovk-pillow.readthedocs.io/en/rtd-verify-mastodon/ contains:
```html
<link rel="me" href="https://fosstodon.org/@pillow"></section>
```
Temporarily adding that to the profile, it verifies like:
Docs: https://docs.joinmastodon.org/user/profile/#verification
> Verify the Mastodon docs link

- depends/install_raqm.sh
- src/thirdparty/raqm/README.md
- src/thirdparty/raqm/raqm-version.h
- src/thirdparty/raqm/raqm.c
- src/thirdparty/raqm/raqm.h
raqm 0.10.0 has been released - https://github.com/HOST-Oman/libraqm/releases/tag/v0.10.0
> Updated raqm to 0.10.0

- .github/workflows/test-mingw.yml
MinGW has started [failing in main](https://github.com/python-pillow/Pillow/actions/runs/3902362791/jobs/6672642893)
> error: target not found: mingw-w64-i686-python-pyqt6
This would be because of https://github.com/msys2/MINGW-packages/commit/4ecf214bd4f045eb1b7ea66db323325f596e94b4
This PR no longer installs the python-pyqt6 package on 32-bit.
> Only install python-pyqt6 package on 64-bit

- Tests/test_file_tiff_metadata.py
- src/PIL/TiffImagePlugin.py
Resolves #6882. Similar to #6740
> Allow writing IFDRational to BYTE tag

- LICENSE
- README.md
- docs/COPYING
- docs/conf.py
- docs/index.rst
- setup.cfg
- src/PIL/__init__.py
I'm still "Alex", just on a Jeffrey A. Clark roll lately.
"Fixes" my name.
* Replace "Alex Clark" with "Jeffrey A. Clark (Alex)"
> Alex Clark -> Jeffrey A. Clark (Alex)

- depends/install_imagequant.sh
- docs/installation.rst
libimagequant 4.0.5 has been released - https://github.com/ImageOptim/libimagequant/releases/tag/4.0.5
> Updated libimagequant to 4.0.5

- src/PIL/EpsImagePlugin.py
Resolves #6877
Using the following code to check speed (based on [`test_timeout()`](https://github.com/python-pillow/Pillow/blob/50f5eade4724e83fafd791325c6bb0e69558d623/Tests/test_file_eps.py#L286-L295)),
```python
import time
import pytest
Image.init()
with open("Tests/images/timeout-d675703545fee17acab56e5fec644c19979175de.eps", "rb") as f:
start = time.time()
with pytest.raises(Image.UnidentifiedImageError):
with Image.open(f):
pass
print("Time taken", time.time() - start)
```
I get
```
Time taken 0.07753515243530273
```
In EpsImagePlugin, after each time `fp.readline()` is run, an error is raised if `fp.readline().strip("\r\n")` is longer than 255 characters. So if Pillow isn't going to use the rest of that data, we can stop reading when the line becomes too …
> Stop reading when EPS line becomes too long

- src/PIL/JpegImagePlugin.py
```python
Image.preinit()
print(Image.ID)
```
prints
```
['BMP', 'DIB', 'GIF', 'TIFF', 'JPEG', 'PPM', 'PNG']
```
But `preinit()` doesn't list TIFF. In fact, it is commented out
https://github.com/python-pillow/Pillow/blob/43bb03539e0f3dca6ee399cbb8162c21e257c05d/src/PIL/Image.py#L321-L364
So why is TIFF part of the preinit list? Because when JPEG is loaded, it imports TiffImagePlugin.
https://github.com/python-pillow/Pillow/blob/43bb03539e0f3dca6ee399cbb8162c21e257c05d/src/PIL/JpegImagePlugin.py#L44
This PR changes the import to only run when it is used, removing TIFF from the list.
> Do not unintentionally load TIFF format at first

- src/PIL/Image.py
When opening an image, Pillow loop through the different possible formats.
https://github.com/python-pillow/Pillow/blob/43bb03539e0f3dca6ee399cbb8162c21e257c05d/src/PIL/Image.py#L3242-L3244
If I add a `print` statement to see which formats it checks,
```python
def _open_core(fp, filename, prefix, formats):
for i in formats:
print(i)
i = i.upper()
```
and then attempt to open a SPIDER image, while only asking Pillow to check the JPEG format,
```python
im = Image.open("Tests/images/hopper.spider", formats=["JPEG"])
```
it prints
```
JPEG
JPEG
File "Tests/test_image.py", line 2, in <module>
im = Image.open("Tests/images/hopper.spider", formats=["JPEG"])
File "PIL/Image.py", line 3284, in open
raise UnidentifiedImageError(msg) …
```
> Do not retry specified formats if they failed when opening

- Tests/test_deprecate.py
- src/PIL/_deprecate.py
* Things usually need to be deprecated for at least a year before removal in a major version
* We're past the cutoff for things that can be removed in Pillow 10 (2023-07-01)
* Add handling for things that can be removed in Pillow 11 (2024-11-15) 
---
Relatedly, after Python 3.7 is end-of-life in June, the EOL for 3.8 and later will have aligned with CPython's annual release cycle in October.
And because Pillow aligns major versions with CPython EOLs, it'll go like something this:
* October 2024: Python 3.13 release, Python 3.8 EOL, Pillow 11.0 release
* October 2025: Python 3.14 release, Python 3.9 EOL, Pillow 12.0 release
* etc
Docs:
* https://devguide.python.org/versions/
* https://peps.python.org/topic/release/
> Handling for deprecations to be removed in Pillow 11

- src/PIL/Image.py
When opening an image, Pillow loops through the different possible formats.
https://github.com/python-pillow/Pillow/blob/0b53853941d1b133c3f0b819f5ac6335821bb084/src/PIL/Image.py#L3242-L3244
If I add a `print` statement to see which formats it checks,
```python
def _open_core(fp, filename, prefix, formats):
for i in formats:
print(i)
i = i.upper()
```
and then run
```python
Image.open("Tests/images/hopper.spider")
```
I get
```
BMP
DIB
GIF
JPEG
PPM
PNG
BMP
DIB
GIF
JPEG
PPM
PNG
BLP
BUFR
CUR
PCX
DCX
...
```
The first set of formats are checked twice - BMP, DIB, GIF, JPEG, PPM and PNG.
This is because after the preinit formats fail to load the SPIDER image, Pillow initialises the rest of the formats, and then just checks all the formats again, even the preinit ones that …
> Do not retry past formats when loading all formats for the first time

- depends/install_imagequant.sh
- docs/installation.rst
libimagequant 4.1.0 has been released - https://github.com/ImageOptim/libimagequant/releases/tag/4.1.0
> Updated libimagequant to 4.1.0

- Tests/test_image.py
- src/PIL/Image.py
> Prevent register_open from adding duplicates to ID

- Tests/test_qt_image_qapplication.py
Helps #6875
I ran the test suite repeatedly in GitHub Actions, and managed to have the [`roundtrip()`](https://github.com/python-pillow/Pillow/blob/698951e19e19972aeed56df686868f1329981c12/Tests/test_qt_image_qapplication.py#L48-L51) check fail during the RGB iteration of loop. Here is what the image looks like when it fails.
There are three short lines of incorrect pixels in the image. If that is acceptable, then this PR relaxes the check so that this image would have passed.
> Relax ImageQt roundtrip check

- setup.py
tiff (4.5.0-1) in Debian results in two include directories being returned:
```
-I/usr/include/x86_64-linux-gnu -I/usr/include
```
These were not added to the compiler include directories, causing tiff support not be enabled because `tiff.h` could not be found.
> Handle more than one directory returned by pkg-config

- .github/workflows/test-cygwin.yml
- .github/workflows/test-mingw.yml
Extracted from the draft #6918
> Sort dependencies

- winbuild/build_prepare.py
libjpeg-turbo 2.1.5 has been released - https://github.com/libjpeg-turbo/libjpeg-turbo/releases/tag/2.1.5
> Updated libjpeg-turbo to 2.1.5

- winbuild/build_prepare.py
libjpeg-turbo 2.1.5.1 has been released - https://sourceforge.net/projects/libjpeg-turbo/files/2.1.5.1/
> Updated libjpeg-turbo to 2.1.5.1

- winbuild/build_prepare.py
freetype 2.13 has been released - https://sourceforge.net/projects/freetype/files/freetype2/2.13.0/
> Updated freetype to 2.13

- .appveyor.yml
- .github/workflows/test-cygwin.yml
- .github/workflows/test-mingw.yml
- .github/workflows/test-windows.yml
- CHANGES.rst
- depends/download-and-extract.sh
- depends/install_extra_test_images.sh
GitHub is removing support for Subversion on January 8, 2024.
* https://github.blog/2023-01-20-sunsetting-subversion-support/
Why do we care?
Well, we're using `svn` in our CI to extract only the `test_images` directory from https://github.com/python-pillow/pillow-depends.
https://github.com/python-pillow/pillow-depends is a big repo full of binary files.
For our purposes, I think we're better off moving the test images into their own repo, so we can instead simply download the new repo as a zipball.
I've made a new repo at https://github.com/hugovk/test-images, which is just the relevant directory from https://github.com/python-pillow/pillow-depends, and preserves the Git history (following [these instructions](https://stackoverflow.com/a/68536044/724176)).
Let's move that repo into …
> Replace SVN with Git for installing extra test images

- Tests/test_file_jpeg.py
- src/PIL/JpegImagePlugin.py
Resolves #6932
https://en.wikipedia.org/wiki/Exif
> Exif metadata are restricted in size to 64 kB in JPEG images because according to the specification this information must be contained within a single JPEG APP1 segment.
This PR raises an error if EXIF data is too large when saving JPEG.
> Raise an error if EXIF data is too long when saving JPEG

- Tests/test_file_jpeg.py
Reported in https://github.com/conda-forge/pillow-feedstock/pull/128#issuecomment-1368705067
`test_get_child_images()` in test_file_jpeg.py is failing with libjpeg. This PR relaxes the check to test for a similarity of 2.1, instead of equality. I have confirmed this in pillow-wheels with libjpeg 9e.
> Relaxed child images check to allow for libjpeg

- src/PIL/Image.py
This PR adds description to the above public module members.
> Add description for getexif() and Exif

- winbuild/build_prepare.py
harfbuzz 7.0.0 has been released - https://github.com/harfbuzz/harfbuzz/releases/tag/7.0.0
> Updated harfbuzz to 7.0.0

- .github/workflows/test-docker.yml
I noticed we're missing code coverage for the C files on Codecov.
For example, no C files listed at:
https://app.codecov.io/gh/python-pillow/Pillow/tree/main/src
Looks like this happened when switched bumped some workflows from v1 of the Codecov Action to v3, and others from the Codecov Bash Uploader to the v3 Action in https://github.com/python-pillow/Pillow/pull/6281, and coverage increased, because there's better average coverage on the Python files (https://app.codecov.io/gh/python-pillow/Pillow/commit/53b6e5f4bf9a6a68e29109c457b12d17761d0035):
Now I remember I had earlier opened https://github.com/codecov/codecov-action/issues/566, where the v1->v2 upgrade lost C coverage. (Codecov never replied.)
Anyway, by now, the Bash Uploader has been retired …
> Enable gcov support for codecov/codecov-action

- docs/handbook/image-file-formats.rst
> Corrected documented WebP quality range

- winbuild/build_prepare.py
harfbuzz 7.0.1 has been released - https://github.com/harfbuzz/harfbuzz/releases/tag/7.0.1
> Updated harfbuzz to 7.0.1

- Tests/test_qt_image_qapplication.py
After PR #6915, the intermittent failure of #6875 has been quiet, until https://github.com/python-pillow/Pillow/actions/runs/4252238465/jobs/7395566372
This PR relaxes the roundtrip check further.
> Relax roundtrip check

- docs/handbook/image-file-formats.rst
Using the suggestion of https://github.com/python-pillow/Pillow/pull/6961#discussion_r1116215884 in another location.
> Highlight code example

- Tests/test_file_pdf.py
- docs/handbook/image-file-formats.rst
- src/PIL/PdfImagePlugin.py
This is useful for converting tiffg3 (fax) images to pdf, which have split dpi like (204,391), (204,196) or (204,98).
* Add a `dpi` parameter to the PDF save function, which accepts a tuple with X and Y dpi.
> Support saving PDF with different X and Y resolution

- Tests/test_file_fits.py
- src/PIL/FitsImagePlugin.py
Resolves #6972
https://fits.gsfc.nasa.gov/fits_primer.html states that
> Each header unit contains a sequence of fixed-length 80-character keyword records which have the general form:
>
> `KEYNAME = value / comment string`
This PR removes the comment string when determining the value.
> Allow comments in FITS images

- Tests/test_image_frombytes.py
- src/decode.c
Resolves #6933. Alternative to #6937
Adds support for using `memoryview` objects in `frombytes()`, by changing
https://github.com/python-pillow/Pillow/blob/dbcd7372e554ee420a156b968eb9a609ec66ffd1/src/decode.c#L124
to use `y*` instead. This is actually the ["recommended way to accept binary data"](https://docs.python.org/3/c-api/arg.html#strings-and-buffers).
See https://bugs.python.org/issue30625 for a discussion about why this change allows `memoryview` objects to be accepted.
> Added memoryview support to frombytes()

- docs/deprecations.rst
- docs/handbook/image-file-formats.rst
- docs/handbook/text-anchors.rst
- docs/handbook/writing-your-own-image-plugin.rst
- docs/reference/Image.rst
- docs/reference/ImageDraw.rst
- docs/reference/ImageEnhance.rst
- docs/reference/ImageFile.rst
- docs/reference/ImageFilter.rst
- docs/reference/ImageFont.rst
- docs/reference/ImageMath.rst
- docs/reference/ImagePath.rst
- docs/reference/ImageSequence.rst
- docs/reference/ImageWin.rst
- docs/reference/PixelAccess.rst
- docs/reference/PyAccess.rst
- docs/reference/open_files.rst
- docs/releasenotes/6.1.0.rst
- docs/releasenotes/6.2.0.rst
- docs/releasenotes/7.0.0.rst
- docs/releasenotes/7.1.0.rst
- docs/releasenotes/8.2.0.rst
- docs/releasenotes/8.4.0.rst
- docs/releasenotes/9.0.0.rst
- docs/releasenotes/9.1.0.rst
- docs/releasenotes/9.2.0.rst
- src/PIL/ImageChops.py
- src/PIL/ImageFont.py
- winbuild/build.rst
#6754 has pointed out that sometimes we use `.. code-block:: python` and sometimes we use `::`.
Because `::` is rendered as a single colon, perhaps `.. code-block:: python` is used where we don't want to show a colon to the reader. This PR replaces `.. code-block:: python` with `::` if it is already following a colon, making the documentation syntax consistent.
> Replace Python code-blocks with double colons

- src/decode.c
Sequel to #6974, addressing https://github.com/python-pillow/Pillow/pull/6974#issuecomment-1445131593
> I think this is missing a call to `PyBuffer_Release()`.
This makes sense, as per https://docs.python.org/3/c-api/buffer.html
> There are two ways for a consumer of the buffer interface to acquire a buffer over a target object:
>
> - call [PyObject_GetBuffer()](https://docs.python.org/3/c-api/buffer.html#c.PyObject_GetBuffer) with the right parameters;
> - call [PyArg_ParseTuple()](https://docs.python.org/3/c-api/arg.html#c.PyArg_ParseTuple) (or one of its siblings) with one of the y*, w* or s* [format codes](https://docs.python.org/3/c-api/arg.html#arg-parsing).
>
> In both cases, [PyBuffer_Release()](https://docs.python.org/3/c-api/buffer.html#c.PyBuffer_Release) must be called when …
> Release buffer

- src/_imagingcms.c
While ImageCms calls `profile_frombytes`,
https://github.com/python-pillow/Pillow/blob/1457d2c14667d9901d7bc2552beed4a1ab81742b/src/PIL/ImageCms.py#L187-L191
`profile_fromstring` is unused.
`profile_fromstring` actually calls the same code as `profile_frombytes`.
https://github.com/python-pillow/Pillow/blob/1457d2c14667d9901d7bc2552beed4a1ab81742b/src/_imagingcms.c#L963-L964
So this PR removes the `profile_fromstring` method declaration, and renames the C method to `cms_profile_frombytes` for clarity.
> Removed unused profile_fromstring method

- Tests/test_file_libtiff.py
- src/PIL/TiffImagePlugin.py
Resolves #6985
**Problem:**
When saving many tiff files with compression="group4" I get the error OSError: [Errno 24] Too many open files (after ~8000 images)
```python
def test_pil():
im_pil = Image.open("T:/test.jpg")
im_pil = im_pil.reduce(5)
im_pil = im_pil.convert("1")
for i in range(10000)
file = f"{i:03}"
out_name = os.path.join(
"T:/trash", os.path.splitext(os.path.basename(file))[0] + ".tif")
)
im_pil.save(out_name, format="TIFF", compression="group4")
```
Without compression="group4" it works fine.
This also happens when a new image is created on each iteration and with explicit close()
```python
def test_pil():
for i in range(10000):
file = f"{i:03}"
im_pil = Image.open("T:/test.jpg")
im_pil = im_pil.reduce(5)
im_pil = im_pil.convert("1")
out_name = os.path.join(
"T:/trash", …
```
> Close file pointer copy in the libtiff encoder if still open

- docs/installation.rst
When building the docs, there is an error - https://github.com/python-pillow/Pillow/actions/runs/4334555177/jobs/7568531757#step:11:504
> (    installation: line  186) broken    https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#search-order-for-desktop-applications - Anchor 'search-order-for-desktop-applications' not found
Here's the page on the Wayback Machine, demonstrating that the anchor did exist once - https://web.archive.org/web/20221204000032/https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#search-order-for-uwp-apps
This PR removes the missing anchor from the link, and also updates the link text, as comparing https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order with the …
> Removed missing anchor from link

- docs/installation.rst
#6992 removed an anchor from a link that was no longer valid, this PR restores the anchor using its new name and changes the link text to reflect that Microsoft Docs has been renamed to Microsoft Learn.
> Restore link anchor

- Tests/test_imagewin.py
- src/display.c
Resolves #6975
Allows `memoryview` objects to be passed as the `buffer` argument to `Dib.frombytes()`. Similar to #6974
> Added memoryview support to Dib.frombytes()

- Tests/test_image_convert.py
- Tests/test_imagecms.py
Testing Alpine in the docker-images repository [without lcms2-dev](https://github.com/radarhere/docker-images/commit/e48cc2d2d8c824f34332348d92648266e396beec), I found that [test_image_convert.py::test_rgb_lab failed](https://github.com/radarhere/docker-images/actions/runs/3853980188/jobs/6567496049). This makes sense, given that [it uses ImageCms.](https://github.com/python-pillow/Pillow/blob/b6c7a837bca6fef6de83bd301dd299a2f77b5b8b/src/PIL/Image.py#L1063-L1074)
This PR moves the test into test_imagecms.py, so that it is skipped if lcms2 is absent.
> Moved conversion test to test_imagecms

- Tests/helper.py
- setup.py
- src/PIL/ImageFont.py
#6847 is still in draft for Windows changes, but it also includes a bit of cleanup, removing unnecessary arguments.
This PR extracts that cleanup, so it at least can be merged.
> Remove redundant default values

- src/_webp.c
For
https://github.com/python-pillow/Pillow/blob/6b71090828a37340a4e552ad24602deb71c119aa/src/_webp.c#L956-L974
this PR rearranges the code to run the `PyType_Ready` conditional first, so it the code fails earlier, and `d` is not created for potentially no reason ([`m` isn't used if `setup_module` returns `-1`](https://github.com/python-pillow/Pillow/blob/6b71090828a37340a4e552ad24602deb71c119aa/src/_webp.c#L988-L993)).
> Move potential error earlier

- src/PIL/TiffImagePlugin.py
In Python 3.11, the following code
```python
from PIL.TiffImagePlugin import IFDRational
ifd = IFDRational(1)
int(ifd)
```
gives
```
DeprecationWarning: The delegation of int() to __trunc__ is deprecated.
int(ifd)
```
I noticed the deprecation warning in https://github.com/python-pillow/Pillow/actions/runs/4342791039/jobs/7584046826#step:8:4230
This deprecation was added in https://github.com/python/cpython/issues/89140
This PR fixes the matter by adding `__int__` to IFDRational - but only for Python >= 3.11. Below Python 3.11, this change gives
```
AttributeError: 'Fraction' object has no attribute '__int__'. Did you mean: '__init__'?
```
> Added __int__ to IFDRational for Python >= 3.11

- Tests/test_file_bufrstub.py
- Tests/test_file_fits.py
- Tests/test_file_fpx.py
- Tests/test_file_gribstub.py
- Tests/test_file_hdf5stub.py
- Tests/test_file_mic.py
- Tests/test_imageshow.py
- src/PIL/FpxImagePlugin.py
- src/PIL/MicImagePlugin.py
There are various [unclosed file warnings in GHA for main at the moment](https://github.com/python-pillow/Pillow/actions/runs/4384362988/jobs/7675750272#step:8:4182). Most of them are problems in the tests, and I've fixed those here, but there are also warnings for unclosed FPX and MIC files.
Those two formats use OleFileIO. This PR fixes those by closing `self.ole` when closing or exiting images of those formats.
> Close OleFileIO instance when closing or exiting FPX or MIC

- setup.py
Resolves #6934
https://github.com/python-pillow/Pillow/blob/7e3bed6834e639cd0f5a410abfd8224d4e5725c5/setup.py#L245-L249
presumes that `os.environ` contains a "PATH" key.
This PR changes the code no longer raise an error if it doesn't.
> Do not raise an error if os.environ does not contain PATH

- src/PIL/ImageDraw.py
A combination of https://github.com/python-pillow/Pillow/pull/1177/commits/77169b2fdba9546c9f6f3842a48c7ba2ee370b16 (which inserted private methods between a comment and `text()`) and https://github.com/python-pillow/Pillow/pull/1926/commits/934485269c4286e9e890597877d73e15a091eb22 (which moved that comment into the first method below it) led to a description for `text()` being in `_multiline_check()` instead.
This restores the docstring to `text()`, as a sequel to #7025
> Restored deleted docstring

- docs/reference/c_extension_debugging.rst
It seems better to point to the official documentation regarding those packages, that also mentions the required call to `sudo apt install ubuntu-dbgsym-keyring`
> Minor improvement made to c_extension_debugging.rst

- src/PIL/TiffImagePlugin.py
Resolves #7019
`Image.core.libtiff_support_custom_tags` may be missing, if libtiff is unavailable.
https://github.com/python-pillow/Pillow/blob/2d5f451f582262f3b26fa23ad43e1dcd69715d90/src/_imaging.c#L4256-L4272
> Allow libtiff_support_custom_tags to be missing

- src/_imaging.c
- src/_imagingcms.c
- src/_imagingft.c
- src/_imagingmorph.c
- src/_webp.c
> Decrement reference count

- Tests/test_file_webp_animated.py
- src/PIL/WebPImagePlugin.py
Helps #7015
Alternative to #6977. This uses `round()` instead of `int()` to better approximate the data, and has a test using one of our existing images.
Animated PNGs can have float durations
https://github.com/python-pillow/Pillow/blob/cdf5fd439cbe381e6c796acc3ab3150242d8e861/src/PIL/PngImagePlugin.py#L677
but when WebP goes to save the duration, it expects an integer.
https://github.com/python-pillow/Pillow/blob/cdf5fd439cbe381e6c796acc3ab3150242d8e861/src/PIL/WebPImagePlugin.py#L308
https://github.com/python-pillow/Pillow/blob/cdf5fd439cbe381e6c796acc3ab3150242d8e861/src/_webp.c#L206-L209
The WebP API itself also expects the duration to be an integer. See https://developers.google.com/speed/webp/docs/container-api#webpanimencoderadd
> int WebPAnimEncoderAdd(
WebPAnimEncoder* enc, …
> Round duration when saving animated WebP images

- .appveyor.yml
- .github/workflows/test-windows.yml
https://github.com/python-pillow/Pillow/pull/7033#issuecomment-1480327216 pointed out that despite our use of the Ghostscript installer,
https://github.com/python-pillow/Pillow/blob/4e0ac449a54539d91486d726b6ac9db948d42f06/.github/workflows/test-windows.yml#L77-L78
Ghostscript is not being detected in our CI builds, either in [GitHub Actions](https://github.com/python-pillow/Pillow/actions/runs/4508121856/jobs/7936778506#step:27:3335) or in [AppVeyor](https://ci.appveyor.com/project/Python-pillow/pillow/builds/46585687/job/pdgrtu2yo3slrfgf?fullLog=true#L6176).
This PR proposes using [Chocolately](https://chocolatey.org/) instead, a package manager already installed in our CIs.
> Install Ghostscript using Chocolatey

- Tests/test_numpy.py
- src/PIL/Image.py
Resolves #7032
Rearranges code so that the image is loaded before setting the size, as TIFF images may be [rotated and have the size changed in `load_end()`](https://github.com/python-pillow/Pillow/blob/f1aeb5ea7aa7588f8b5544d8f3916c569503dd5f/src/PIL/TiffImagePlugin.py#L1192-L1196).
This is similar to #6186 for `thumbnail()` and #6190 for `resize()`, except now for `__array_interface__`.
> Load before getting size in __array_interface__

- docs/installation.rst
Helps https://github.com/python-pillow/pillow-wheels/issues/359 by documenting how users can combine our existing wheels to create a universal2 wheel, through https://pypi.org/project/delocate/
> Document how to create universal2 wheels

- setup.py
Helps #7040
https://github.com/python-pillow/Pillow/issues/7040#issuecomment-1488664881
> the path of ldconfig is hardcoded in the setup, relying on the ldconfig from $PATH would be flexible to different systems.
> Removed absolute path to ldconfig

- src/PIL/Image.py
Resolves #5850 by documenting the available pixel types of Pillow modes, and noting that they do not always correspond to NumPy dtypes.
Helps #7045 by documenting that converting P or PA images to NumPy will not include the palette.
> Document handling of modes when converting to or from NumPy

- src/PIL/ImageFont.py
In [`FreeTypeFont.getmask2()`](https://pillow.readthedocs.io/en/stable/reference/ImageFont.html#PIL.ImageFont.FreeTypeFont.getmask2), only spend time rendering text if the image it will be rendered onto has a non-zero width or height.
> Do not render text if image has zero width or height

- Tests/test_file_ppm.py
- docs/releasenotes/9.5.0.rst
- src/PIL/PpmImagePlugin.py
Resolves #6963
When PpmImagePlugin is reading an image, it [only reads `ImageFile.SAFEBLOCK` bytes at a time.](https://github.com/python-pillow/Pillow/blob/879e77a44604b31e271711898b035a5caba8cb73/src/PIL/PpmImagePlugin.py#L151-L152)
So when looping through this data, if there is no space after the last digit, [it saves this for the next loop](https://github.com/python-pillow/Pillow/blob/879e77a44604b31e271711898b035a5caba8cb73/src/PIL/PpmImagePlugin.py#L226-L244), in case the read operation stopped partway through a series of digits.
Except that `half_token` isn't cleared after it is used. That means that it keeps getting used, and so infinite data is available to fill the image size.
> Clear PPM half token after use

- Tests/test_file_libtiff.py
- docs/releasenotes/9.5.0.rst
- src/PIL/TiffTags.py
- src/encode.c
In #7008, two images were reported to cause a RuntimeError. Testing on my machine, I found that this caused a segfault instead.
It turns out that this was due to an incorrect tag type being used for [ImageSourceData](https://www.awaresystems.be/imaging/tiff/tifftags/imagesourcedata.html).
Except then I found the RuntimeError, happening on [32-bit Windows.](https://github.com/radarhere/Pillow/actions/runs/4404887057/jobs/7715072523#step:27:726)
```
E       RuntimeError: Error setting from dictionary
C:\hostedtoolcache\windows\Python\3.7.9\x86\lib\site-packages\pillow-9.5.0.dev0-py3.7-win32.egg\PIL\Image.py:437: RuntimeError
---------------------------- Captured stderr call -----------------------------
_TIFFVSetField: C:\Users\runneradmin\AppData\Local\Temp\pytest-of-runneradmin\pytest-0\te …
```
> Added ImageSourceData to TAGS_V2

- src/PIL/ImageFont.py
- src/PIL/features.py
- src/_imagingft.c
Helps #7040 
Changes:
* use `_util.DeferredError` if `_imagingft` fails to import instead of a custom helper from before the fork (similarly to `ImageCms`, added in #600),
* if a module fails to import but is present (i.e. triggers `ImportError` but not `ModuleNotFoundError`), raise a warning in `PIL.features`,
* remove no longer needed backwards compatibility code:
* `FT_LOAD_COLOR` was added in [FreeType 2.5](https://freetype.org/freetype2/docs/reference/ft2-base_interface.html#ft_load_color), Pillow currently requires FreeType>=2.8 (#5777)
* `FT_LOAD_TARGET_MONO` version added is undocumented, but has been around since [FreeType 2.1.3](https://gitlab.freedesktop.org/freetype/freetype/-/blob/0db6997026a05798eb0cbcbb3b37bf6121fb5f6a/docs/CHANGES#L3700),
* remove `#define …
> Do not discard error message if _imagingft fails to import

- setup.py
PR #2544 resolved the immediate problem of #2563, but it also added a comment.
https://github.com/python-pillow/Pillow/blob/943a7a89c5b8b6cd3d531da756ece661f30b0c5b/setup.py#L684-L687
The user was thinking about the logic of the hardcoded paths in setup.py and our use of `pkg-config`, but it is possible for any given path to be in `self.compiler.include_dirs` from the very beginning of `build_extensions()` if the user added it in their install command, like
```
python3 -m pip install . -v --global-option=build_ext --global-option="-Iinsertedpath"
```
If the user wants to be eager in adding include directories, I don't think that is a problem. So this PR removes the comment, as it is at least misleading.
> Removed FIXME comment

- Makefile
- Tests/check_release_notes.py
To avoid mistakes like https://github.com/python-pillow/Pillow/pull/7054.
We could use something like `grep -P TODO docs/releasenotes/[1-9]*.rst` but the `-P` option isn't available in the system `grep` on macOS (see https://stackoverflow.com/a/22704387/724176), and a short script is also cross platform for Windows too.
> Add release check to make sure no TODOs remain in release notes

- .ci/install.sh
PyQt6-Qt6 6.5.0 was [released an hour ago on PyPI](https://pypi.org/project/PyQt6-Qt6/#history) (although hasn't been announced yet at https://www.riverbankcomputing.com/news), and since then, the "test" Ubuntu builds on main have [started failing](https://github.com/python-pillow/Pillow/actions/runs/4656595509/jobs/8240380107).
This PR is a temporary workaround, that skips only 6.5.0. If a new version is released and there is still a problem, the tests will start failing again to confirm that this is something to investigate.
I say PyQt6-Qt6, and not PyQt6. [Not installing PyQt6 6.5.0](https://github.com/radarhere/Pillow/commit/07295106a681496733fdccb7921af52061498f38) [does not resolve the situation](https://github.com/radarhere/Pillow/actions/runs/4656884611/jobs/8240944063).
> Do not install PyQt6-Qt6 6.5.0

- RELEASING.md
Some updates to the release checklist, I followed these for [9.5.0](https://github.com/python-pillow/Pillow/issues/6989).
---
First, I moved the `git push --all` from near the start (after removing `.dev0` from the version and updating `CHANGES.rst`), to near the end (after incrementing and adding `.dev0` to the version).
The reason: the CI does a _lot_ of building during releases and there's a lot of waiting around for the release manager. We only need the tags pushed early to build the Windows wheels via `git push --tags`. The Linux and macOS wheels are built using their own dedicated wheel builder. The `git push --all` just delays the CI from building all these wheels.
So  `git push --all` which pushes `main` and `9.5.x` can come after all the wheel building.
---
Next, during the …
> Release refinement

- .ci/install.sh
#7081 disabled installing of PyQt6-Qt6 6.5.0 because "test" Ubuntu builds had started failing in main.
Starting [QApplication with `QT_DEBUG_PLUGINS` enabled](https://github.com/radarhere/Pillow/commit/16ff78dd983764d7f76ea8ba4fe170d8441e9b16), I find the message ["libxcb-cursor.so.0: cannot open shared object file: No such file or directory"](https://github.com/radarhere/Pillow/actions/runs/4666980576/jobs/8262200783#step:4:268)
So this PR reverts #7081 and installs libxcb-cursor0.
A similar thing has happened before, with #6438 and #4662
> Install libxcb-cursor0

- .appveyor.yml
- .ci/after_success.sh
Codecov had deprecated their Python codecov package:
* https://about.codecov.io/blog/introducing-codecovs-new-uploader/
But rather than only deprecating it, they've completely deleted the package from PyPI:
* https://pypi.org/project/codecov/
* https://github.com/codecov/python-standard/issues/31
* https://community.codecov.com/t/codecov-yanked-from-pypi-all-versions/4259?u=hugovk
This is causing failures on our CI.
For AppVeyor, let's switch to the new uploader.
For others, we were pip installing codecov in `.ci/after_success.sh`, called by:
* `.github/workflows/test-docker.yml`
* `.github/workflows/test-cygwin.yml`
* `.github/workflows/test-windows.yml`
* `.github/workflows/test.yml`
We'd already moved all of these to using the Codecov GitHub Action, but were still installing the …
> Fix codecov after they deleted the Python package from PyPI

- src/thirdparty/raqm/COPYING
- src/thirdparty/raqm/NEWS
- src/thirdparty/raqm/README.md
- src/thirdparty/raqm/raqm-version.h
- src/thirdparty/raqm/raqm.c
- src/thirdparty/raqm/raqm.h
https://github.com/HOST-Oman/libraqm/releases/tag/v0.10.1
> Update vendored Raqm to 0.10.1

- depends/install_raqm.sh
raqm 0.10.1 has been released - https://github.com/HOST-Oman/libraqm/releases/tag/v0.10.1
> Updated raqm to 0.10.1

- .github/workflows/test-cygwin.yml
Cygwin started failing in main, with https://github.com/python-pillow/Pillow/actions/runs/4696586061/jobs/8329527067#step:8:157
>       gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DFFI_BUILDING=1 -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.9 -c c/_cffi_backend.c -o build/temp.cygwin-3.4.6-x86_64-cpython-39/c/_cffi_backend.o
>       c/_cffi_backend.c:2:10: fatal error: Python.h: No such file or directory
>          2 | #include <Python.h>
>            |          ^~~~~~~~~~
The above lines mention Python 3.9, but this should be a Python 3.8 build.
This PR links `python3` to the correct Python version.
However, [problems with ImageMagick started happening a day …
> Select Python version in Cygwin

- src/libImaging/Jpeg2KEncode.c
https://github.com/python-pillow/Pillow/actions/runs/4696665571/jobs/8326957733#step:6:116
>   src/libImaging/Jpeg2KEncode.c: In function ‘j2k_encode_entry’:
>  src/libImaging/Jpeg2KEncode.c:345:9: warning: ‘bpp’ is deprecated: Use prec instead [-Wdeprecated-declarations]
>    345 |         image_params[n].bpp = bpp;
We are already using `prec` just before this, so `bpp` can just be removed.
https://github.com/python-pillow/Pillow/blob/8740e3261955c70dd113e789dc12326de2e342d0/src/libImaging/Jpeg2KEncode.c#L344-L345
See https://github.com/uclouvain/openjpeg/pull/1383 for more information.
> Remove use of deprecated OpenJPEG "bpp" member

- src/PIL/ImageCms.py
https://github.com/python-pillow/Pillow/blob/a405e8406b83f8bfb8916e93971edc7407b8b1ff/src/PIL/ImageCms.py#L188-L193
The two branches of this condition were made the same in https://github.com/python-pillow/Pillow/commit/ce041fd1995fe95de868.
> Removed duplicate code

- Tests/test_numpy.py
- src/PIL/Image.py
Fixes the same what was in https://github.com/python-pillow/Pillow/issues/7032 but for `deepcopy(im)` operation.
* first we load image data in `__getstate__` and then only fill list with it's attributes.
> Load before getting size in __getstate__

- .readthedocs.yml
Resolves #7114
The issue reports that there are no downloads at https://readthedocs.org/projects/pillow/downloads/
After looking at https://docs.readthedocs.io/en/stable/config-file/v2.html#formats, I've inserted `formats: all` to .readthedocs.yml.
As evidence that this works, https://readthedocs.org/projects/pillow-radarhere/versions/ lists 'latest' and 'formats' as versions, https://readthedocs.org/projects/pillow-radarhere/builds/ shows recent builds of both, but only 'formats' is visible at https://readthedocs.org/projects/pillow-radarhere/downloads/ as downloads (while 'stable' also appears, it is very old).
> Build all readthedocs formats

- Tests/test_imagefont.py
- src/_imagingft.c
Resolves #6689
Pillow calls `FT_Set_Pixel_Sizes` [when loading a font](https://github.com/python-pillow/Pillow/blob/a405e8406b83f8bfb8916e93971edc7407b8b1ff/src/_imagingft.c#L182). [`FT_Set_Pixel_Sizes`](https://gitlab.freedesktop.org/freetype/freetype/-/blob/master/src/base/ftobjs.c#L3561-3593) takes `FT_UInt` as the width/height arguments, but then multiplies those integers by 64 before calling `FT_Request_Size`.
As [suggested](https://github.com/python-pillow/Pillow/issues/6689#issuecomment-1292365173), this PR calls `FT_Request_Size` directly instead, allowing 64 times the control over font sizes.
> Support float font sizes

- .github/workflows/test-mingw.yml
MinGW is currently failing in main - https://github.com/python-pillow/Pillow/actions/runs/4861154081
https://www.msys2.org/docs/python/ states
> [setuptools](https://github.com/pypa/setuptools) >= 60.0 is currently incompatible with MSYS2. You can set export SETUPTOOLS_USE_DISTUTILS=stdlib to work around the issue. We are currently working on restoring compatibility.
Adding in `SETUPTOOLS_USE_DISTUTILS="stdlib"` fixes the problem.
> Use stdlib for setuptools on MinGW

- depends/install_imagequant.sh
- docs/installation.rst
libimagequant 4.2.0 has been released - https://github.com/ImageOptim/libimagequant/releases/tag/4.2.0
> Updated libimagequant to 4.2.0

- src/PIL/ImageGrab.py
Resolves #7110
If the command used in `ImageGrab.grabclipboard()` on Linux (`xclip` or `wl-paste`) returns stderr content, raise that as a `ChildProcessError`.
> Raise error from stderr of Linux ImageGrab.grabclipboard() command

- docs/conf.py
- docs/deprecations.rst
- docs/releasenotes/10.0.0.rst
- docs/releasenotes/9.2.0.rst
https://github.com/python-pillow/Pillow/actions/runs/4892060254/jobs/8733344399#step:7:423
> (    deprecations: line  211) redirect  https://doc.qt.io/qtforpython/ - permanently to https://doc.qt.io/qtforpython-6/
> Updated redirected URL

- docs/reference/ImageDraw.rst
Resolves #367
#6625 documented that ImageDraw's `rectangle()` included the endpoints. This continues that clarification of the documentation for `line()` and `polygon()`.
As a demonstration, see the following code comparing the three functions.
```python
from PIL import Image, ImageDraw
img = Image.new('RGB', (10, 10), (255, 255, 255))
draw = ImageDraw.Draw(img, 'RGBA')
draw.polygon([(2,2), (2, 8), (8,8), (8, 2)], fill=(0, 255, 0, 127))
draw.rectangle([(2,2), (8,8)], fill=(255, 0, 0, 127))
draw.line([(2,2), (8,8)], fill=(0, 0, 0, 255))
img.resize((200, 200), Image.NONE).save("out.png")
```
> Clarify that line() and polygon() include xy pixels

- docs/reference/ImageGrab.rst
Helps https://github.com/python-pillow/Pillow/issues/7147#issuecomment-1540094856 by updating the documentation after #6783 added grabclipboard() support to Linux in Pillow 9.4.0.
> ImageGrab grabclipboard() is supported on Linux

- docs/reference/ImageGrab.rst
- src/PIL/ImageGrab.py
Alternative to #7139
From https://github.com/python-pillow/Pillow/pull/7100#issuecomment-1537056956
> > Is the problem just a user trying to ignore `gnome-screenshot` when it is installed in favour of `Image.core.grabscreen_x11`? If so, then `ImageGrab.grab(xdisplay=":0")` should be sufficient with the current version of Pillow.
> 
> [...] I have just tested setting `xdisplay=':0'`, and it ran on my end without any white flash. I believe this usage needs to be tested across different platforms. If the test is successful, it should be set as the default option. [...]
> Prefer screenshots using XCB over gnome-screenshot

- setup.py
Resolves #7066
Trying to handle a situation where "ldconfig" isn't detected correctly, but the absolute path used prior to #7044 works.
> Use "/sbin/ldconfig" if ldconfig is not found

- .readthedocs.yml
* https://github.com/python-pillow/Pillow/issues/7114 requested PDF (or at least zipped HTML)
* PDF was also requested in https://github.com/python-pillow/Pillow/issues/7163
* https://github.com/python-pillow/Pillow/pull/7116 added PDF, epub and htmlzip
* To save docs build time, only build PDF in addition to default HTML; skips epub and htmlzip
Build times:
* epub 34s
* htmlzip 16s
* pdf 25s
> Build only PDF in addition to default html

- Tests/test_file_jpeg.py
- docs/releasenotes/10.0.0.rst
- src/PIL/Image.py
*  Add `_repr_jpg_` and `_repr_jpeg_` method for ipython display (similar to currently existing `_repr_png_`)
> Added `_repr_jpeg_` for IPython display

- .ci/install.sh
- .github/workflows/test-windows.yml
The Windows Python 3.12 builds on main have started failing - https://github.com/python-pillow/Pillow/actions/runs/5089366014/jobs/9146907439#step:25:41
> ModuleNotFoundError: No module named 'setuptools'
This installs setuptools to fix that.
The Linux Python 3.12 build on main has also started failing with a segfault - https://github.com/python-pillow/Pillow/actions/runs/5089395395/jobs/9146969201
Skipping testing PyQt6 on Python 3.12 fixes that. I'm able to [reproduce the segfault](https://github.com/radarhere/Pillow/actions/runs/5095982782/jobs/9161438269) [without Pillow](https://github.com/radarhere/Pillow/commit/6ce891977a328b774db72880d6a2cfc563aa732f), so it is not a problem directly with our code.
> Fix Python 3.12 failures

- src/_imagingft.c
Python 3.12 reports a deprecation - https://github.com/python-pillow/Pillow/actions/runs/5105776867/jobs/9177570491#step:7:234
> warning: 'Py_FileSystemDefaultEncoding' is deprecated
https://docs.python.org/3.12/whatsnew/3.12.html#id4 instructs us to replace it with `PyConfig.filesystem_encoding`.
Using https://docs.python.org/3.12/c-api/init_config.html#example as a basis, I made that change.
However, I found [this](https://github.com/radarhere/Pillow/commit/cda44e2408d64663ac71cb8f9cc46bef1b298611) [failed on PyPy](https://github.com/radarhere/Pillow/actions/runs/5097051329/jobs/9163321558#step:7:232), with
> error: use of undeclared identifier 'PyConfig'
I asked in https://foss.heptapod.net/pypy/pypy/-/issues/3946, and PyPy has chosen not to implement PyConfig yet. So I've switched to …
> Replaced deprecated Py_FileSystemDefaultEncoding for Python >= 3.12

- .pre-commit-config.yaml
- docs/Guardfile
https://github.com/python-pillow/Pillow/blob/3ab83f22ca36dcd21fc4a28d1c93066c2da75eb9/.pre-commit-config.yaml#L7-L9
https://github.com/psf/black/issues/402 has been resolved
> Removed files and types override

- src/PIL/IcnsImagePlugin.py
- src/PIL/ImageCms.py
- src/PIL/ImageShow.py
- src/PIL/SpiderImagePlugin.py
Resolves #7172, apparently
Continuing the work of https://github.com/python-pillow/Pillow/pull/2349
> Replaced absolute PIL import with relative import

- Tests/test_file_gif.py
- src/PIL/GifImagePlugin.py
Updates GifImagePlugin so that
https://github.com/python-pillow/Pillow/blob/5aa3f2d20977673b6420f3f2c4e43ac2ca9a27a1/src/PIL/GifImagePlugin.py#L875-L882
returns an empty bytestring if there is no palette.
The test case I've added otherwise fails with `AttributeError: 'NoneType' object has no attribute 'palette'` in the above function.
> Fixed saving multiple 1 mode frames to GIF

- src/display.c
Resolves #7133
The user is intermittently hitting https://github.com/python-pillow/Pillow/blob/2467db492e7e50efaf39d445c92190c713e40f6f/src/display.c#L439-L440
https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-openclipboard states
> OpenClipboard fails if another window has the clipboard open.
If the error is hit, this PR pauses for 0.5s, and then tries again.
> If the clipboard fails to open on Windows, wait and try again

- src/PIL/ImageGrab.py
https://github.com/python-pillow/Pillow/issues/7147#issuecomment-1540087205
> Looking at the code again, I'm not sure why a temporary file is even necessary in the first place.
This PR reads the output from the subprocess command directly when grabbing the clipboard on Linux, rather than using a temporary file as an intermediate step.
> Do not use temporary file when grabbing clipboard on Linux

- src/PIL/EpsImagePlugin.py
- src/PIL/JpegImagePlugin.py
Helps #7147 by ensuring that temporary files are still removed, even if the code returns early due to an error.
> Remove temporary file when error is raised

- src/libImaging/Jpeg2KEncode.c
https://github.com/python-pillow/Pillow/actions/runs/5186598166/jobs/9347921664#step:7:118
>   src/libImaging/Jpeg2KEncode.c: In function ‘j2k_encode_entry’:
>  src/libImaging/Jpeg2KEncode.c:467:27: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]
>    467 |         while (tile_width < (1 << (params.numresolution - 1U)) || tile_height < (1 << (params.numresolution - 1U))) {
|                           ^
>  src/libImaging/Jpeg2KEncode.c:467:79: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]
>    467 |         while (tile_width < (1 << (params.numresolution - 1U)) || tile_height < (1 << (params.numresolution - 1U))) {
| …
> Fixed signedness comparison warning

- src/PIL/ImageFilter.py
Resolves #3678
https://pillow.readthedocs.io/en/stable/reference/ImageFilter.html#PIL.ImageFilter.Kernel
> kernel – A sequence containing kernel weights.
The issue notes that this doesn't specify the order. As #3134 notes, Pillow does not use convolution order or correlation order.
https://towardsdatascience.com/convolution-vs-correlation-af868b6b4fb5 has figures 5d and 6g of this,
noting that
> In Convolution operation, the kernel is first flipped by an angle of 180 degrees and is then applied to the image.
So our order, as noted by #3134, is
```python
#[[0 0 0 0 0 0 0]
```
which would be flipping the kernel vertically before applying it. I've added that note to the documentation.
> Document order of kernel weights

- src/PIL/EpsImagePlugin.py
When opening an image, if the size is missing, EpsImagePlugin sets the image size just before throwing an error.
https://github.com/python-pillow/Pillow/blob/4f7070e24c9cba8fc7ffab8d9f1c291977bbf183/src/PIL/EpsImagePlugin.py#L356-L359
But if an error is thrown when opening, there is no image afterwards. Consider this example code, derived from the test suite.
```python
import io
data = io.BytesIO(b'%!PS-Adobe-3.0 EPSF-3.0\n%%BoundingBox: a b c d\n10 setlinewidth\n10 10 moveto\n0 90 rlineto 90 0 rlineto 0 -90 rlineto closepath\nstroke')
try:
im = Image.open(data)
except OSError:
pass
print(im)
```
gives
```
File "demo.py", line 9, in <module>
print(im)
NameError: name 'im' is not defined
```
So if there is no image afterwards, why …
> Do not set size unnecessarily if image fails to open

- Tests/test_file_tiff.py
- src/PIL/TiffImagePlugin.py
Resolves #7077
The issue points out that
https://github.com/python-pillow/Pillow/blob/b0c76535022b795f2c31d725131c54e8e10d1ff7/src/PIL/TiffImagePlugin.py#L1881-L1895
does not include 'long8', which we first started supporting in #6097.
This PR adds 'long8', https://www.awaresystems.be/imaging/tiff/bigtiff.html
> TIFF_LONG8 = 16, being unsigned 8byte integer
but because `fieldSizes` is a list not a dictionary, the items between 12 ("[12 = DOUBLE](https://www.itu.int/itudoc/itu-t/com16/tiff-fx/docs/tiff6.pdf)") and 16 also need to be added.
https://www.awaresystems.be/imaging/tiff/specification/TIFFPM6.pdf
> TIFF data type 13, “IFD,” is otherwise identical to LONG
So 'ifd' has size 4, like long.
For 14 and 15, information is scarce. The best information I could find was …
> Fixed saving TIFF multiframe images with LONG8 tag types

- docs/handbook/concepts.rst
https://github.com/python-pillow/Pillow/discussions/7155#discussion-5182709
> In the docs, it says, for the [Coordinate System](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#coordinate-system):
>
> > For example, a rectangle covering all of an 800x600 pixel image is written as (0, 0, 800, 600).
>
> Is this not incorrect, as since the images are zero-based, that text ((0, 0, 800, 600)) should actually be for an image 801 x 601? And so that line of text should really be:
>
> > For example, a rectangle covering all of an 800x600 pixel image is written as (0, 0, 799, 599).
My first attempt to address this was #7156, but while ImageDraw's `rectangle()` includes endpoints, it was [pointed out](https://github.com/python-pillow/Pillow/pull/7156#issuecomment-1542959676) that …
> Removed rectangle example from co-ordinate system documentation

- Tests/test_image_putpalette.py
- src/libImaging/Unpack.c
Address the problem raised in #7186
`putpalette()`'s strategy for attaching a palette to an image is to change the mode, set the palette, and then call `load()`.
https://github.com/python-pillow/Pillow/blob/117618b01f959f016833158b7b128e896c6d38b6/src/PIL/Image.py#L1918-L1921
We have been testing this with [all of the valid modes.](https://github.com/python-pillow/Pillow/blob/117618b01f959f016833158b7b128e896c6d38b6/Tests/test_image_putpalette.py#L19-L23)
However, the user found an error when calling `putpalette()` on an image directly after opening it, before `load()` is called. This means that L and LA images are attempted to be unpacked directly into P and PA images respectively, which Unpack.c doesn't currently support.
> Fixed calling putpalette() on L and LA images before load()

- Tests/test_imagefont.py
- src/PIL/ImageFont.py
- src/_imagingft.c
Helps #6618
**Backstory**
The following is an earlier version of `ImageFont`'s `getmask2()`, as described in the quoted comment.
https://github.com/python-pillow/Pillow/blob/3cfdef395e7c57e4c88a23c7c7458a045894ffe5/src/PIL/ImageFont.py#L752-L777
https://github.com/python-pillow/Pillow/issues/6618#issuecomment-1257086823
> The function getmask2 performs the following steps:
> 
> 1. calls getsize to get the size of the text
> 2. calls Image._decompression_bomb_check to compare size with MAX_IMAGE_PIXELS
> 3. calls the fill function passed as argument to create a blank image
> 4. calls render to draw text into the blank image
> 
> After Pillow 10 the deprecated fill parameter will be replaced by a direct call to the internal function. After this, the only Python function to be called between …
> Only call text_layout once in getmask2

- src/PIL/GdImageFile.py
- src/PIL/Image.py
- src/PIL/features.py
Extracting a formatting change from #6966 that can be made independently of ruff, as we've preferred this style [in the past.](https://github.com/python-pillow/Pillow/commit/eacbd7b04abac95a2f84a3f091642530910f450f#diff-74d414aaf6e27f4f300028b1d09db57e995195807399fd96f63a207bc4f29ab9L63)
> Use "not in"

- src/_imagingft.c
Extracting a change from the draft PR #6926
https://github.com/python-pillow/Pillow/blob/599979caae111c22bd15f0103320bf74eb53d963/src/_imagingft.c#L168-L170
On first glance, the PR simply stops this value from being hardcoded, by replacing it with `FT_Err_Out_Of_Memory`, as per https://freetype.org/freetype2/docs/reference/ft2-error_code_values.html.
However, 65 is actually not the out of memory error code. 65 is 0x41, and according to that FreeType doc, 0x40 is "out of memory", while 0x41 is "unlisted object". So this change is not just stylistic, but also corrects the error code.
> Corrected error code

- docs/handbook/image-file-formats.rst
Requested in https://github.com/python-pillow/Pillow/pull/6852#issuecomment-1590764724
#6852 added QOI reading, but QOI is listed under 'Write-Only' instead of 'Read-Only'.
> Moved QOI from Write-Only to Read-Only

- .github/workflows/test-windows.yml
- .github/workflows/test.yml
PyPy 7.3.12 has been released with Python 3.9 and 3.10 - https://www.pypy.org/posts/2023/06/pypy-v7312-release.html
> Added PyPy 3.10 and removed PyPy 3.8

- CHANGES.rst
- src/PIL/ImageGrab.py
This PR changes `grabclipboard()` to use a PNG compression instead of a lossy JPG compression when reading images from he clipboard on macOS.
Fixes #7214
> Change `grabclipboard()` to use PNG compression on macOS

- docs/installation.rst
> Document how to install on MinGW when setuptools >= 60

- Tests/bench_cffi_access.py
Changed output format from
`PyAccess - get: breaking at 63 iterations, 0.160498 per iteration`
or
`PyAccess - get: 10.1114 s  0.160498 per iteration`
to
`PyAccess - get: completed 63 iterations in 10.1114s, 0.160498s per iteration`
> bench_cffi_access print formatting

- .github/workflows/test-cygwin.yml
- setup.py
Resolves #7158 by applying the part of the patch from https://github.com/pypa/distutils/pull/209, in case we wanted to avoid waiting.
The modification to setup.py added here should be able to be removed once that PR is merged and setuptools is updated to include it.
> Fixed finding dependencies on Cygwin

- src/PIL/Image.py
[ci skip]
More accurate description of how default viewer is chosen
Reference to the actual code, that registers the default viewer: https://github.com/python-pillow/Pillow/blob/73fc73038a8360d00437be062ca265a9209e866f/src/PIL/ImageShow.py#L288C1-L288C1
* Mention "xdg-open" and "gm" in Unix section of Image.show docstring
> Update Image.show docs to list all viewers used on Linux

- .github/workflows/test-mingw.yml
- MANIFEST.in
- Makefile
- _custom_build/backend.py
- docs/installation.rst
- pyproject.toml
- tox.ini
Resolves #7167
https://github.com/python-pillow/Pillow/actions/runs/4999985216/jobs/8956875899#step:7:23
> DEPRECATION: --build-option and --global-option are deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use --config-settings. Discussion can be found at https://github.com/pypa/pip/issues/11859
`--config-settings` is described at https://peps.python.org/pep-0517/#config-settings
So I think our [build options](https://pillow.readthedocs.io/en/stable/installation.html#build-options) should change from
```
python3 -m pip install --upgrade Pillow --global-option="build_ext" --global-option="--enable-[feature]"
```
to
```
python3 -m pip install --upgrade Pillow -C enable=[feature]
```
However, setuptools does not currently pass the config settings …
> Use --config-settings instead of deprecated --global-option

- codecov.yml
#7228 removed Tests/32bit_segfault_check.py, so it no longer needs to be ignored in codecov.yml
> Removed deleted file from codecov.yml and increased coverage threshold

- docs/installation.rst
- winbuild/build_prepare.py
libtiff 4.5.1 has been released - http://www.simplesystems.org/libtiff/
In https://download.osgeo.org/libtiff/tiff-4.5.1.tar.gz, test/CMakeLists.txt refers to test_write_read_tags.c, but that file is missing. It can be seen at https://gitlab.com/libtiff/libtiff/-/tree/master/test, so I presume this was a packaging error.
Since it is only a test, I've patched test/CMakeLists.txt in winbuild/build_prepare.py to remove the references to it.
> Updated libtiff to 4.5.1

- Tests/test_image_access.py
- docs/deprecations.rst
- docs/releasenotes/10.0.0.rst
- src/PIL/Image.py
- src/PIL/PyAccess.py
Resolves #7223
Pillow's C API is now faster than PyAccess on PyPy. However, PyAccess is part of our public API, so it can't be removed immediately.
This PR makes two changes.
1. `Image.USE_CFFI_ACCESS` is set to `False`,  even on PyPy, allowing the faster C API to be used by default. If users do set `Image.USE_CFFI_ACCESS` to `True` manually, then they will find that...
2. PyAccess is now deprecated, to be removed in Pillow 11.
> Do not use CFFI access by default on PyPy

- src/PIL/Image.py
Resolves #7096 by documenting that `Image.open()` seeks to the start of file objects before reading.
https://github.com/python-pillow/Pillow/blob/aec7a8d14ba7a90bbb50b4d0f6af2a805c642882/src/PIL/Image.py#L3202-L3225
> `Image.open()` seeks to the start of file objects

- src/PIL/Image.py
Resolves #7241
When ImageShow saves an image as a PNG, it uses "compress_level" of 1
https://github.com/python-pillow/Pillow/blob/1174a9e7f45d71db1771cae410ab05f12df34b23/src/PIL/ImageShow.py#L177-L178
This prioritises speed over file size, presumably because this image is intended to just be shown, not saved for later use.
That same logic would apply to `_repr_png`, so this PR adds "compress_level" of 1 to that functionality as well.
> Prioritise speed in _repr_png_

- Tests/test_imagecolor.py
- src/PIL/Image.py
- src/PIL/ImageColor.py
Resolves #7225
Currently, `ImageColor.getcolor()` returns RGB values for all modes... except for 1, L, LA, La, I and F, when it returns a single value.
This PR adds another exception for the HSV mode, so that HSV values are returned in that case.
> Convert to HSV if mode is HSV in getcolor()

- src/PIL/TiffImagePlugin.py
- src/libImaging/TiffDecode.c
Resolves #7042
libtiff closes file handles, but Pillow might still want access afterwards to seek to other frames in the file. To resolve this, TiffImagePlugin duplicates the file handle.
https://github.com/python-pillow/Pillow/blob/9a560c78a821638662206a51423f987eb095a901/src/PIL/TiffImagePlugin.py#L1256-L1258
#5936 had a problem with too many open files, so the following code was added to ensure that if libtiff did not close the file, Pillow would still close the file.
https://github.com/python-pillow/Pillow/blob/9a560c78a821638662206a51423f987eb095a901/src/PIL/TiffImagePlugin.py#L1308-L1312
#7042 doesn't like this behaviour, feeling that it is not thread-safe to close a file handle more than once.
Investigating how exactly libtiff closes file handles, I found that it is …
> Do not close provided file handles with libtiff

- docs/releasenotes/10.0.0.rst
> Added release notes for #7123

- src/PIL/ImageFont.py
- src/_imagingft.c
Corrects a problem from https://github.com/python-pillow/Pillow/pull/7206
> Fixed deallocating mask images

- winbuild/build_prepare.py
libjpeg-turbo 3.0.0 has been released - https://github.com/libjpeg-turbo/libjpeg-turbo/releases/tag/3.0.0
> Updated libjpeg-turbo to 3.0.0

- Tests/oss-fuzz/build.sh
CIFuzz has started failing in main - https://github.com/python-pillow/Pillow/actions/runs/5454631686/jobs/9925010430#step:4:10489
> Unable to find "/usr/local/lib/libjpeg.so.62.3.0" when adding binary and data files.
Earlier in the log, you see - https://github.com/python-pillow/Pillow/actions/runs/5454631686/jobs/9925010430#step:4:3597
> -- Set runtime path of "/usr/local/lib/libjpeg.so.62.4.0" to "/usr/local/lib"
So this PR updates the version.
> Updated libjpeg shared library name

- docs/handbook/image-file-formats.rst
~I didn´t generate the doc to check if the link was correct but I picked it from [here](https://github.com/python-pillow/Pillow/blob/3ee925915085ee0f7ad72fbede5d9a9e6ea902a7/src/PIL/WalImageFile.py#L65C38-L65C77).~
Works as expected: https://pillow--7262.org.readthedocs.build/en/7262/handbook/image-file-formats.html#wal
> Add link to PIL.Image.Image.putpalette in WAL documentation

- setup.py
when compiling Pillow with libtiff and libjpeg (with jpeg12 enabled - which is the default with libjpeg-3.0.0) the libtiff object tif_jpeg_12.c.o uses the following libjpeg12 functions: jpeg12_read_raw_data, jpeg12_read_scanlines, jpeg12_write_raw_data, jpeg12_write_scanlines.
update the ordering of libs.append(feature.tiff) to be before libs.append(feature.jpeg) to allow the linker to include the required functions.
this issue occurs when the libtiff and libjpeg libraries are static (not shared.)
Fixes #7269.
* reorder libraries due to dependency of tiff on jpeg
```
readelf -Ws build.LibreELEC-Generic.x86_64-12.0-devel/install_pkg/Pillow-10.0.0/usr/lib/python3.11/site-packages/PIL/_imaging.so | grep jpeg12_[rw]
10: 0000000000000000     0 NOTYPE …
```
> Fix missing symbols as libtiff can depend on libjpeg

- winbuild/build_prepare.py
harfbuzz 8.0.0 has been released - https://github.com/harfbuzz/harfbuzz/releases/tag/8.0.0
> Updated harfbuzz to 8.0.0

- docs/newer-versions.csv
- setup.cfg
- tox.ini
For https://github.com/python-pillow/Pillow/issues/6941.
* Add to support table: https://pillow--7280.org.readthedocs.build/en/7280/installation.html#python-support
* Add `"Programming Language :: Python :: 3.12"` Trove classifier
* Add to `tox.ini`
> Declare support for Python 3.12

- Tests/test_file_gif.py
- src/PIL/GifImagePlugin.py
Resolves #7279
https://github.com/python-pillow/Pillow/blob/7a1e28404d692d4a7fed33dc67019a1d8c4bf9d9/src/PIL/GifImagePlugin.py#L546-L549
When `_normalize_mode` converts the image, transparency may be removed from `im.info` by `convert()`. However, that change is not detected at the moment because the transparency is only removed for the new `im_out` image - `im` still has transparency, and when `_write_local_header` gets passed `im` a few lines later, it is detected.
https://github.com/python-pillow/Pillow/blob/7a1e28404d692d4a7fed33dc67019a1d8c4bf9d9/src/PIL/GifImagePlugin.py#L559
https://github.com/python-pillow/Pillow/blob/7a1e28404d692d4a7fed33dc67019a1d8c4bf9d9/src/PIL/GifImagePlugin.py#L683-L690
This PR simplifies matters by no longer checking `im.info` in `_write_local_header`, …
> Do not use transparency when saving GIF if it has been removed when normalizing mode

- .github/workflows/test-cygwin.yml
Resolves #7281
This will update the cache key in the Cygwin job whenever a new version of NumPy is released, keeping build times low.
> Include NumPy version in Cygwin pip cache key

- docs/handbook/image-file-formats.rst
Resolves #7297
This PR documents that Pillow can [read P1 to P6](https://github.com/python-pillow/Pillow/blob/b9451540973ca7915b0ce68e6bbacbed665caec2/src/PIL/PpmImagePlugin.py#L28-L35) PPM image formats (P1 to P3 only since Pillow 9.2.0 with #5242) and [writes images in P4 to P6.](https://github.com/python-pillow/Pillow/blob/b9451540973ca7915b0ce68e6bbacbed665caec2/src/PIL/PpmImagePlugin.py#L309-L320)
> Added more information about PPM formats

- src/libImaging/Access.c
1. The `put_pixel` function is only currently used for LA, La and PA.
https://github.com/python-pillow/Pillow/blob/b9451540973ca7915b0ce68e6bbacbed665caec2/src/libImaging/Access.c#L187-L208
https://github.com/python-pillow/Pillow/blob/b9451540973ca7915b0ce68e6bbacbed665caec2/src/libImaging/Access.c#L130-L137
Since these are [not image8 modes](https://github.com/python-pillow/Pillow/blob/b9451540973ca7915b0ce68e6bbacbed665caec2/src/libImaging/Storage.c#L75-L97), it would be simpler to just call `put_pixel_32` instead
https://github.com/python-pillow/Pillow/blob/b9451540973ca7915b0ce68e6bbacbed665caec2/src/libImaging/Access.c#L172-L175
and remove `put_pixel`.
2. `get_pixel` is similarly only currently used for LA, La and PA.
It does have unique behaviour, so we can't remove it completely. …
> Simplified access code

- docs/reference/ImageDraw.rst
- src/PIL/ImageFont.py
Fixes https://github.com/python-pillow/Pillow/issues/7304.
* Clarify that a tuple isn't returned, but a single value is (that it depends on the direction of the text)
> Docs: Clarify that a single value is returned, and depends on the text direction

- Tests/test_file_jpeg.py
- Tests/test_file_png.py
- src/PIL/Image.py
Resolves #7283
In 10.0.0 a `_repr_jpeg_` implementation was added to the Image object to enable the use of `display_jpeg()` in IPython environments. However, in some cases the implementation of this method could result in an exception being raised while trying to generate the jpeg data. The best example is if the image data is in an RGBA format as a result of the object being created by opening a PNG file. In this case trying to save the Image object as a jpeg will error because the jpeg format can't represent the transparency in the alpha channel. This results in an exception being raised in the IPython/Jupyter context when outputting the image object. However, in cases like this IPython allows the repr methods to return None to indicate there is no representation in that format …
> Handle exceptions in _repr_jpeg_ and _repr_png_

- src/PIL/PdfImagePlugin.py
Helps #7312
Pillow can convert a PNG with transparency to PDF
```python
im = Image.open("Tests/images/transparent.png")
im.save("transparent.pdf")
```
However, what does transparency mean exactly in PDF? There is debate about this in #7312, and various image viewers are discussed, so I'll try and keep it simple here by saving it that if I convert the PDF back to PNG with ImageMagick, `convert transparent.pdf out.png`, at the moment, I get a black background instead of transparency.
In https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf, under 7.4.9 'JPXDecode Filter', it states
> **SMaskInData** specifies whether soft-mask information packaged with the image samples shall be used (see 11.6.5.3, "Soft-Mask Images"); if it is, the **SMask** …
> Set SMaskInData to 1 for PDFs with alpha

- Tests/test_file_pdf.py
- docs/handbook/image-file-formats.rst
- src/PIL/PdfImagePlugin.py
- src/libImaging/Jpeg2KEncode.c
Resolves #7293
This is similar to #6925, except for LA instead of RGBA, and so uses
https://github.com/python-pillow/Pillow/blob/ea0abb94cce2aa8b6aed33f57b3871053f2aad59/src/PIL/PdfImagePlugin.py#L160-L161
instead of
https://github.com/python-pillow/Pillow/blob/ea0abb94cce2aa8b6aed33f57b3871053f2aad59/src/PIL/PdfImagePlugin.py#L174-L175
> Added saving LA images as PDFs

- src/PIL/PdfImagePlugin.py
The combination of #7299 and #7316 has led to a [lint error in main](https://github.com/python-pillow/Pillow/actions/runs/5760256344/job/15615858900#step:7:26).
This fixes that, while also applying the RGBA changes from #7316 to the new LA saving from #7299.
- `ColorSpace` is removed for LA, since [the specification](https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf) states under 7.4.9 "JPXDecode Filter" that "ColorSpace shall be optional since JPEG2000 data contain colour space specifications"
- `SMaskInData` is set to 1, allowing
```python
im = Image.open("/Users/andrewmurray/pillow/Pillow/Tests/images/transparent.png")
im.convert("LA").save("la.pdf")
```
followed by an ImageMagick `convert la.pdf la.png` to result in an image with …
> Set SMaskInData to 1 for LA PDFs

- Tests/test_image.py
`Image._new` takes an `ImagingCore` not an `Image`.
https://github.com/python-pillow/Pillow/blob/a5b025629023477ec62410ce77fd717c372d9fa2/src/PIL/Image.py#L509-L511
Also expanded the abbreviations to make this more clear.
> Fix param in test_image.py function

- Tests/test_file_gif.py
- docs/handbook/image-file-formats.rst
- src/PIL/GifImagePlugin.py
Resolves #7328
This allows `im.save("out.gif", loop=None)`, having the same effect as `im.save("out.gif")`
> Allow "loop=None" when saving GIF images

- Tests/test_file_webp.py
- src/PIL/WebPImagePlugin.py
Many WebP images don't initially have duration in their info dict.  This automatically adds that information during image open.
> Read WebP duration after opening

- docs/releasenotes/10.0.0.rst
Found a typo in last section:
interpretaton -> interpretation
> Fixed a typo in 10.0.0 release notes

- Tests/test_file_png.py
- winbuild/build_prepare.py
zlib 1.3 has been released - https://zlib.net/
> Updated zlib to 1.3

- docs/installation.rst
At https://pillow.readthedocs.io/en/latest/installation.html#basic-installation, under the 'Windows' tab, it states
> We provide Pillow binaries for Windows compiled for the matrix of supported Pythons in both 32 and 64-bit versions in the wheel format.
As of https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html#bit-wheels, we no longer provide 32-bit wheels.
This was pointed out in https://github.com/python-pillow/Pillow/issues/7341#issuecomment-1685596122
> 32-bit Windows wheels are no longer provided

- src/PIL/ImageGrab.py
Fixes #7331
* Check if current session is X11 or Wayland and decide which command to use. This is done by using `loginctl` command (based on [this](https://unix.stackexchange.com/a/371164)). If the session check failed (loginctl not available because eg. not on systemd), fall back to previous routine (assume Wayland first, if `wl-paste` unavailable then assume X11)
* Raise `NotImplementedError` if `xclip` unavailable on X11 session or `wl-paste` unavailable on Wayland session
> Added session type check in grabclipboard for Linux

- Tests/oss-fuzz/test_fuzzers.py
- Tests/test_imagedraw.py
- Tests/test_pickle.py
If I disable the optional dependency FreeType, various tests fail.
This PR skips them if FreeType is not available.
> Skip tests that require FreeType if FreeType is not available

- Tests/test_box_blur.py
- Tests/test_image_filter.py
- src/PIL/ImageFilter.py
- src/_imaging.c
- src/libImaging/BoxBlur.c
- src/libImaging/Imaging.h
- src/libImaging/UnsharpMask.c
Resolves #7321
Allows specifying a different radius for X and Y for ImageFilter's GaussianBlur and BoxBlur, e.g. `ImageFilter.GaussianBlur((32, 16))` and `ImageFilter.BoxBlur((32, 16))`.
This is in addition to the existing single number, `ImageFilter.GaussianBlur(16)` and `ImageFilter.BoxBlur(16)`.
> Allow GaussianBlur and BoxBlur to accept a sequence of x and y radii

- Tests/test_image_access.py
- src/PIL/Image.py
- src/_imaging.c
Resolves #7352
The issue points out that while `im.getpixel()` accepts a tuple, `im.getpixel((0, 0))`, it does not accept a list.
```pytb
>>> im.getpixel([0, 0])
File "PIL/Image.py", line 1568, in getpixel
TypeError: argument must be sequence of length 2
```
Even though the list supplied is still a "sequence of length 2".
It is worth noting that this error string is shared with another situation.
```pytb
>>> im.load()[0, 0, 0]
TypeError: argument must be sequence of length 2
```
So the error message cannot be simply reworded to say "tuple", as I don't think that clearly explains the problem with `im.load()[0, 0, 0]` .
Instead, this PR allows …
> Allow getpixel() to accept a list

- .ci/install.sh
Reverts part of #7188.
For whatever reason, PyQt6 no longer causes a segfault in Python 3.12 on Linux.
> Revert "Do not test PyQt6 on Python 3.12"

- src/PIL/Image.py
In `frombuffer`, Pillow maps the buffer onto a (1, 1) image.
https://github.com/python-pillow/Pillow/blob/24606216e1e5931a8fe6f41acde9e7e67489905d/src/PIL/Image.py#L3003-L3004
As a small change for the sake of performance, this PR changes it to be a (0, 0) image instead.
> Map buffer into (0, 0) image

- Tests/test_file_qoi.py
- src/PIL/QoiImagePlugin.py
Resolves #7356
The [specification](https://qoiformat.org/qoi-specification.pdf) states that for QOI_OP_DIFF,
> The alpha value remains unchanged from the previous pixel.
And we do that correctly
https://github.com/python-pillow/Pillow/blob/24606216e1e5931a8fe6f41acde9e7e67489905d/src/PIL/QoiImagePlugin.py#L66-L74
However, the specification also states the same thing for QOI_OP_RGB, and we do not use the previous pixel value for alpha.
https://github.com/python-pillow/Pillow/blob/24606216e1e5931a8fe6f41acde9e7e67489905d/src/PIL/QoiImagePlugin.py#L57-L58
> Use previous pixel alpha for QOI_OP_RGB

- winbuild/build_prepare.py
harfbuzz 8.2.0 has been released - https://github.com/harfbuzz/harfbuzz/releases/tag/8.2.0
> Updated harfbuzz to 8.2.0

- Tests/test_file_libtiff.py
- src/PIL/ImageOps.py
- src/PIL/TiffImagePlugin.py
Resolves #7381
When a TIFF image is loaded, the orientation is applied.
https://github.com/python-pillow/Pillow/blob/52c6d686135e13df23f05cfe34d393b9d6e981f6/src/PIL/TiffImagePlugin.py#L1545
https://github.com/python-pillow/Pillow/blob/52c6d686135e13df23f05cfe34d393b9d6e981f6/src/PIL/TiffImagePlugin.py#L1205-L1218
However, there is no change in Pillow's information about the image as a result of this. This is not ideal, because
1. if a user inspects the `tag_v2` orientation for an image, it may or may not have been applied already, depending on whether the image has loaded, and that could be confusing.
2. If a user runs `ImageOps.exif_transpose()` afterwards, the orientation is applied a second time.
This PR addresses 1 by deleting the `tag_v2` orientation tag, so that it is consistently …
> Prevent TIFF orientation from being applied more than once

- depends/install_imagequant.sh
- docs/installation.rst
libimagequant 4.2.1 has been released - https://github.com/ImageOptim/libimagequant/releases/tag/4.2.1
> Updated libimagequant to 4.2.1

- docs/reference/Image.rst
- src/PIL/Image.py
> Improved init(), preinit() and register_mime() documentation

- Tests/test_file_webp.py
- Tests/test_image.py
- docs/reference/Image.rst
- docs/releasenotes/10.1.0.rst
- src/PIL/Image.py
- src/PIL/WebPImagePlugin.py
Resolves #7384
Adds a method to determine if an image has transparency data - an alpha channel, an RGBA palette or "transparency" in the image's `info` directory.
I chose this method name to try and indicate that the image may still be opaque. For example, `hopper("RGB").convert("RGBA")` has an alpha channel, but has no transparent or translucent pixels.
In doing so, I found a similar check in WebPImagePlugin.
https://github.com/python-pillow/Pillow/blob/b723e9e62e4706a85f7e44cb42b3d838dae5e546/src/PIL/WebPImagePlugin.py#L335-L340
So I've changed that to use this new method.
> Added has_transparency_data

- src/PIL/BlpImagePlugin.py
`save_all` is not used in the following code.
https://github.com/python-pillow/Pillow/blob/aaa758751d0127cac40e39ecd5bdd021eab11ca5/src/PIL/BlpImagePlugin.py#L445-L463
It isn't necessary. See JpegImagePlugin for example.
https://github.com/python-pillow/Pillow/blob/aaa758751d0127cac40e39ecd5bdd021eab11ca5/src/PIL/JpegImagePlugin.py#L633
> Removed unused code

- .github/workflows/test-cygwin.yml
- .github/workflows/test-docker.yml
- .github/workflows/test-mingw.yml
- .github/workflows/test-windows.yml
- .github/workflows/test.yml
Helps #7390.
After https://github.com/python-pillow/Pillow/pull/7418 is merged, we can skip running the "normal" tests when there are changes to files matching:
```yml
- ".github/workflows/wheels*"
- ".gitmodules"
- ".travis.yml"
- "wheels/**"
```
> Don't run normal tests on changes to wheel-building files

- Tests/test_file_eps.py
- docs/handbook/image-file-formats.rst
- src/PIL/EpsImagePlugin.py
Resolves #7391 
The user in that issue would like an API to prevent Ghostscript use. Since we already have `EpsImagePlugin.gs_windows_binary` that stores the name of the Ghostscript binary on Windows,
https://github.com/python-pillow/Pillow/blob/e1889544cdd959c60e2526505053e81a8f43c7e4/src/PIL/EpsImagePlugin.py#L40
this PR suggests adding `EpsImagePlugin.gs_binary`, that stores the name of the Ghostscript binary on all platforms.
Setting it to false would result in `OSError: Unable to locate Ghostscript on paths` when trying to load an EPS image.
> Added gs_binary to control Ghostscript use on all platforms

- Tests/test_file_gif.py
- Tests/test_image.py
- Tests/test_image_convert.py
- Tests/test_image_putpalette.py
- src/PIL/BlpImagePlugin.py
- src/PIL/Image.py
- src/_imaging.c
- src/libImaging/Convert.c
- src/libImaging/Palette.c
- src/libImaging/Quant.c
Resolves #7288
The image in the issue has indexes that occur outside of the palette. This PR ensures that they are black.
> Set C palette to be empty by default

- Tests/test_file_iptc.py
- src/PIL/IptcImagePlugin.py
Resolves #7318
1. The issue has found an image where `im.info["photoshop"][0x0404]` appears to be zero padded. I've added a commit ignoring an IPTC field if it is only zero bytes, resolving the problem.
2. A later post in the issue has found an image where `tag[0]`
https://github.com/python-pillow/Pillow/blob/52206c71e4c3882d6ab0ffa8e8de986986f2fd62/src/PIL/IptcImagePlugin.py#L67
is 240. This doesn't line up with page 12 (PDF page 12, not page 12 according to the footer) of http://www.iptc.org/std/IIM/4.1/specification/IIMV4.1.pdf, which lists 1 to 9. However, https://exiftool.org/TagNames/IPTC.html lists 240, making me think that this is a proprietary extension, rather than something mentioned in the format. I've adjusted the code to also accept 240 as a value.
> Increase flexibility when reading IPTC fields

- docs/installation.rst
More documentation for #7341  .
* Add warning
> Add warning to docs: Pillow > 9.5.0 no longer includes 32-bit wheels

- README.md
- docs/conf.py
- docs/index.rst
https://bestpractices.coreinfrastructure.org/ now redirects to https://www.bestpractices.dev/
https://github.com/python-pillow/Pillow/actions/runs/6439243260/job/17486706271#step:7:371
> /home/runner/work/Pillow/Pillow/docs/index.rst:2: WARNING: redirect  https://bestpractices.coreinfrastructure.org/projects/6331/badge - with Found to https://www.bestpractices.dev/projects/6331/badge
> (           index: line    2) (    installation: line  264) ok        https://brew.sh/
> (           index: line    2) ok        https://bugs.chromium.org/p/oss-fuzz/issues/list?sort=-opened&can=1&q=proj:pillow
> /home/runner/work/Pillow/Pillow/docs/index.rst:2: WARNING: redirect  https://bestpractices.coreinfrastructure.org/projects/6331 - with Found to https://www.bestpractices.dev/en/projects/6331
> Updated redirected links

- .travis.yml
I just went to "Trigger a custom build" in Travis CI, as was [intended to be possible](https://github.com/python-pillow/Pillow/pull/7418#issuecomment-1741600488), but found it was "Skipped as per condition: IF tag IS present"
https://github.com/python-pillow/Pillow/blob/ae9a9b08f1387c07a2d88d37b66546ef6c7e8276/.travis.yml#L1
So this PR updates it to `if: tag IS present OR type = api`. See https://docs.travis-ci.com/user/conditions-v1 for documentation.
To demonstrate, I pushed the branch to this repository, and triggered a custom build - https://app.travis-ci.com/github/python-pillow/pillow/builds/266441553
> Allow custom builds to be triggered in Travis CI

- winbuild/build_prepare.py
brotli 1.1.0 has been released - https://github.com/google/brotli/releases/tag/v1.1.0
> Updated brotli to 1.1.0

- winbuild/build_prepare.py
#7451 broke FreeType support on Windows due to changing libbrotli from a static to a dynamic (dll) build, this PR fixes that change.
> Fix libbrotli build for Windows wheels

- src/PIL/Image.py
https://github.com/python-pillow/Pillow/blob/4ecf1df4ea63457040f63adaeea35996913b6ac1/src/PIL/Image.py#L983
can be replaced with
```python
trns_im = new(self.mode, (1, 1))
```
because [that is what ` new()` would do in this case.](https://github.com/python-pillow/Pillow/blob/4ecf1df4ea63457040f63adaeea35996913b6ac1/src/PIL/Image.py#L2901-L2921)
This requires variables called `new` to be renamed in the surrounding code to avoid overlap, but that sounds like a good idea anyway.
> Use new() instead of Image()._new()

- Tests/test_file_apng.py
- src/PIL/PngImagePlugin.py
Resolves #7459
Sequel to #6610
1. While that PR theoretically considers all images, and "upgrades" images to more complex modes, it did not consider the default image.
https://github.com/python-pillow/Pillow/blob/aaa758751d0127cac40e39ecd5bdd021eab11ca5/src/PIL/PngImagePlugin.py#L1230-L1239
This means that [when the default image is saved](https://github.com/python-pillow/Pillow/blob/aaa758751d0127cac40e39ecd5bdd021eab11ca5/src/PIL/PngImagePlugin.py#L1168-L1169) with the chosen mode, it may not be the ideal choice. This PR considers the mode of the default image, and converts the default image before saving if needed.
2. Because that PR made it so that P images are "upgraded" to RGB if there are any RGB images present, a RGB to P conversion will no longer occur at …
> Consider default image when selecting mode for PNG save_all

- src/_imaging.c
After #7303 was merged, I noticed a warning.
https://github.com/python-pillow/Pillow/actions/runs/6430296173/job/17461014310#step:7:231
>   src/_imaging.c: In function ‘_putdata’:
>  src/_imaging.c:1578:21: warning: ‘bigendian’ may be used uninitialized in this function [-Wmaybe-uninitialized]
>   1578 |                 int bigendian;
>        |                     ^~~~~~~~~
> Fixed "may be used uninitialized" warning

- src/PIL/Image.py
I noticed [a warning was being raised in tests](https://github.com/python-pillow/Pillow/actions/runs/6398432650/job/17370348716#step:8:4448)
> Tests/test_file_libtiff.py::TestFileLibTiff::test_multipage
> Tests/test_file_libtiff.py::TestFileLibTiff::test_multipage_seek_backwards
> Tests/test_file_libtiff.py::TestFileLibTiff::test_page_number_x_0
> Tests/test_imagesequence.py::test_libtiff
>   /opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/PIL/TiffImagePlugin.py:866: UserWarning: [Errno 22] Invalid argument
>     warnings.warn(str(msg))
A fuller traceback is
```pytb
___________________________________________________ TestFileLibTiff.test_multipage _____________________________________________________
self = <Tests.test_file_libtiff.TestFileLibTiff object at …
```
> Fixed invalid argument warning

- depends/install_imagequant.sh
- docs/installation.rst
libimagequant 4.2.2 has been released - https://github.com/ImageOptim/libimagequant/releases/tag/4.2.2
> Updated libimagequant to 4.2.2

- docs/handbook/writing-your-own-image-plugin.rst
- docs/releasenotes/10.1.0.rst
Improves documentation by
- describing how to populate mode and size when writing a plugin
- moving #7307 out of "Backwards Incompatible Changes" and into "API Changes"
> Describe how to populate mode and size when writing a plugin

- RELEASING.md
Noticed during https://github.com/python-pillow/Pillow/issues/7348, helps https://github.com/python-pillow/Pillow/issues/7390.
The Windows instructions are correct, it's artifact is "dist-x.y.z":
https://github.com/python-pillow/Pillow/blob/0be67e5544185b76a33f2adf7f34f8be20e4f262/.github/workflows/test-windows.yml#L233
https://github.com/python-pillow/Pillow/blob/0be67e5544185b76a33f2adf7f34f8be20e4f262/.github/workflows/test-windows.yml#L238-L243
* `dist-10.1.0` https://github.com/python-pillow/Pillow/actions/runs/6523153069
But macOS/Linux is simply "wheels":
https://github.com/python-pillow/Pillow/blob/0be67e5544185b76a33f2adf7f34f8be20e4f262/.github/workflows/wheels.yml#L25-L27
https://github.com/python-pillow/Pillow/blob/0be67e5544185b76a33f2adf7f34f8be20e4f262/.github/workflows/whee …
> Update release checklist: macOS/Linux artifact is called 'wheels'

- .github/workflows/cifuzz.yml
- .github/workflows/docs.yml
- .github/workflows/test-cygwin.yml
- .github/workflows/test-docker.yml
- .github/workflows/test-mingw.yml
- .github/workflows/test-valgrind.yml
- .github/workflows/test.yml
Noticed during https://github.com/python-pillow/Pillow/issues/7348, helps https://github.com/python-pillow/Pillow/issues/7390.
When making a release, and pushing a tag, all the CI workflows run:
By the time we're making a release, the CI has already tested all merges to `main`. Checking this is one of the first items in the [release checklist](https://github.com/python-pillow/Pillow/blob/main/RELEASING.md).
We can save some CI time and skip the non-wheels workflows for tag pushes.
The wheels workflows:
* wheels.yml
* test-windows.yml (for now)
* I also left lint.yml there: it's quick to run
By default, all branches and tags are run. By explicitly specifying all branches `branches: `"**"` has the same effect as not specifying a `tags:` key, and not triggering for tags. Ref: …
> Skip non-wheel CI runs for tags

- docs/releasenotes/10.1.0.rst
Like https://pillow.readthedocs.io/en/stable/releasenotes/9.3.0.html#python-3-11-wheels
> Add Python 3.12 support to Pillow 10.1.0 release notes

- Tests/test_imageops.py
- src/PIL/ImageOps.py
Added the image mode to the error message, so you can see what mode it's erroring on.
> Add mode to ImageOps._lut() error message

- Tests/oss-fuzz/build.sh
Replaces direct `setup.py` invocation with `pip install .`, as per https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html
Sequel to #5896
> Switched from direct setup.py invocation to "pip install ."

- .travis.yml
For https://github.com/python-pillow/Pillow/issues/6941.
Travis CI now has Python 3.12.
We can also bump the Ubuntu version.
> Update Travis CI to Python 3.12 and Ubuntu 22.04 Jammy Jellyfish

- .appveyor.yml
- .github/workflows/test-windows.yml
- docs/handbook/image-file-formats.rst
- Document in the 'Image file formats' that olefile is required for FPX and MIC
- Install olefile (and some other optional dependencies) on Windows CIs for better testing
> Improved olefile documentation and testing

- Tests/test_image.py
- src/PIL/Image.py
Resolves #7492
The issue found that calling `Image.frombytes` for an image with zero size and no data - e.g. `Image.frombytes("L", (0, 0), b"")` - raises an error.
This fixes that, and the corresponding situation for `im.frombytes()`.
This is the inverse of #5938
> Fixed frombytes() for images with a zero dimension

- docs/installation.rst
Alternative to #7502
Under 'Basic Installation', mention that olefile can additionally be installed to allow Pillow to read FPX and
MIC images.
> Mention defusedxml and olefile in installation instructions

- docs/releasenotes/10.0.0.rst
Document that the security fix in 10.0.0 that added `ImageFont.MAX_STRING_LENGTH` was assigned CVE-2023-44271.
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-44271
https://devhub.checkmarx.com/cve-details/CVE-2023-44271/
> Add CVE-2023-44271 to release notes

- .editorconfig
- .flake8
- .pre-commit-config.yaml
- MANIFEST.in
- Makefile
- Tests/bench_cffi_access.py
- _custom_build/backend.py
- docs/conf.py
- pyproject.toml
- src/PIL/EpsImagePlugin.py
- src/PIL/IcnsImagePlugin.py
- src/PIL/Image.py
- src/PIL/ImageFilter.py
- src/PIL/IptcImagePlugin.py
- src/PIL/PdfParser.py
- src/PIL/PyAccess.py
- winbuild/build_prepare.py
This PR switches linting (flake8, isort, <del>bandit</del>, yesqa, pygrep-hooks) for Pillow to [the `ruff` linter](https://github.com/charliermarsh/ruff).
* Running a full `pre-commit` run is much faster (45.15 seconds of CPU time to 8.62 seconds on my machine)
* It's easier to enable more rules if need be since the configuration is all in one place
* 👉  The only rule that may not be yet supported by `ruff` that had been previously enabled is `rst-backticks` from `pygrep-hooks`.
* That being said, this PR still enables _more_ lints than had been in use from `pygrep-hooks` since it enables the whole `PGH` family.
* <del>👉 Instead of touching expressions like `x, y, l, r, w, a, d, f = metrics[ix]`, I opted to adding specific `noqa` directives to quiesce Ruff's "ambiguous name" for `l` …
> Move linting to ruff

- Tests/test_file_apng.py
- src/PIL/PngImagePlugin.py
As an optimisation step, if saving a single frame PNG (or multiple identical frames) with `save_all`, do not create an APNG, but just a PNG. The resulting file is slightly smaller.
This does remove the duration from the final image, but I would suggest that single frame images don't need a duration.
> If save_all PNG only has one frame, do not create animated image

- Tests/test_file_jpeg.py
- src/libImaging/JpegEncode.c
We already support `streamtype=2` to skip producing JPEG tables, but `streamtype=1`, which skips everything but the tables, was never implemented. The `streamtype=1` stub code dates to Git pre-history, so it's not immediately clear why.  Implement the missing support.
`jpeg_write_tables()` can't resume after a full output buffer (it fails with `JERR_CANT_SUSPEND`), so it might seem that Pillow needs to pre-compute the necessary buffer size.  However, in the normal case of producing an interchange stream, the tables are written via the same libjpeg codepath during the first `jpeg_write_scanlines()` call, and table writes aren't resumable there either.  Thus, any buffer large enough for the normal case will also be large enough for a tables-only file.
I've opted to implement the early exit …
> Implement `streamtype=1` option for tables-only JPEG encoding

- .ci/install.sh
- .github/workflows/macos-install.sh
- .github/workflows/test-windows.yml
- .github/workflows/test.yml
- src/libImaging/TiffDecode.c
- src/libImaging/TiffDecode.h
* Test Python 3.13 pre-release
* Explicitly include `unistd.h` to use `lseek`
Changed in [Python 3.13](https://docs.python.org/dev/whatsnew/3.13.html#id8):
> * ``Python.h`` no longer includes the ``<unistd.h>`` standard header file. If
needed, it should now be included explicitly. For example, it provides the
functions: ``read()``, ``write()``, ``close()``, ``isatty()``, ``lseek()``,
``getpid()``, ``getcwd()``, ``sysconf()``, ``getpagesize()``, ``alarm()`` and
``pause()``.
As a consequence, ``_POSIX_SEMAPHORES`` and ``_POSIX_THREADS`` macros are no
longer defined by ``Python.h``. The ``HAVE_UNISTD_H`` and ``HAVE_PTHREAD_H``
macros defined by ``Python.h`` can be used to decide if ``<unistd.h>`` and
``<pthread.h>`` header files can be included.
So we …
> Fix for Python 3.13: explicitly include `unistd.h`

- Tests/helper.py
- Tests/test_file_iptc.py
- Tests/test_file_jpeg2k.py
- Tests/test_image.py
- Tests/test_image_resize.py
- Tests/test_image_thumbnail.py
- Tests/test_imageshow.py
`pytest.fail()` gives slightly nicer errors:
https://docs.pytest.org/en/7.1.x/reference/reference.html#pytest-fail
```python
import pytest
def test_a():
assert False
def test_b():
assert False, "abc"
def test_c():
pytest.fail()
def test_d():
pytest.fail("abc")
```
```python
============================================================================================= FAILURES =============================================================================================
______________________________________________________________________________________________ test_a ______________________________________________________________________________________________
def test_a():
>       assert False
E       assert False
1.py:5: AssertionError …
```
> Tests: Replace `assert False` with `pytest.fail()`

- .github/workflows/wheels.yml
- RELEASING.md
Next step of automation for https://github.com/python-pillow/Pillow/issues/7390.
This creates the sdist on the CI:
* No need to create it locally
* Safer to build on the CI than a potentially compromised local machine
* Better reproduciblity
The sdist is added as a new job to the `wheels.yml` workflow and added to the same GitHub artifact as the wheels, which I've renamed from `wheel` to `dist`.
---
We'll probably want to rename `wheels.yml` to something not specific to wheels (because we build a source distribution as well), I was thinking about renaming `deploy.yml` once we start publishing to PyPI, but open to renaming now as well.
> Release automation: create sdist on CI

- Tests/test_file_jpeg.py
- docs/handbook/image-file-formats.rst
- src/PIL/JpegImagePlugin.py
- src/encode.c
- src/libImaging/Jpeg.h
- src/libImaging/JpegEncode.c
If a JPEG includes restart markers, the decoder doesn't have to give up if it finds data corruption, but can scan forward to the next restart marker and resume decoding from there.  Restart markers add overhead, but are useful in applications that want to support a limited form of error recovery or random access within a JPEG.
libjpeg allows specifying the marker interval either in MCU blocks or in MCU rows.  Support both, via separate parameters, rather than requiring callers to do the math.
> Allow configuring JPEG restart marker interval on save

- winbuild/build_prepare.py
For #6679 and https://github.com/python-pillow/Pillow/issues/7390#issuecomment-1813365035
When compiling Pillow directly on an ARM64 system, I found it worked after installing the correct Visual Studio components.
Cross-compiling required a few patches to the dependencies.
* Select Visual Studio version only if it has ARM64 build tools installed (https://github.com/python-pillow/Pillow/issues/6679#issuecomment-1295644192)
* Fix ARM64 target detection when cross-compiling libjpeg-turbo (if NASM is installed) and libimagequant (https://github.com/python-pillow/Pillow/issues/6679#issuecomment-1292620454)
* Do not cross-compile FriBiDi (https://github.com/python-pillow/Pillow/issues/6679#issuecomment-1295510138)
> Windows arm64 dependency cross-compilation fixes

- docs/installation.rst
#1932 changed tcl/tk to no longer be a build dependency.
> Docs: tcl/tk is no longer a build dependency

- docs/installation.rst
These two references to the build flags were missed in #7171.
> Use --config-settings in external libraries list in installation.rst

- Tests/test_image.py
- src/PIL/Image.py
*  Closes image when they are copied
* Since image copied doesn't have 'fp' attribute, a message was logged as "error"
> If absent, do not try to close fp when closing image

- docs/handbook/image-file-formats.rst
- src/PIL/GifImagePlugin.py
https://pillow.readthedocs.io/en/latest/handbook/image-file-formats.html#gif-saving states that when saving GIF, you can specify "optimize", and that it is off by default.
> **optimize**
> If present and true, attempt to compress the palette by eliminating unused colors. This is only useful if the palette can be compressed to the next smaller power of 2 elements.
This doesn't line up with the reality - it is only off by default if "palette" is provided in `im.encoderinfo` or `im.info`.
https://github.com/python-pillow/Pillow/blob/04a4d54275bb45288e3a6057a914f667e159b348/src/PIL/GifImagePlugin.py#L653-L659
This PR corrects the documentation, and also simplifies the code by using `setdefault()`.
> "optimize" default when saving GIF images

- wheels/README.md
Documentation follow up to #7552
> Updated wheels README after cibuildwheel integration

- pyproject.toml
In thinking about #7502, it occurred to me that listing `olefile` and `defusedxml` as optional dependencies in pyproject.toml is probably helpful, as a form of documentation.
> List optional dependencies in pyproject (apart from docs and tests)

- .ci/requirements-cibw.txt
- .github/workflows/wheels.yml
- .travis.yml
Helps https://github.com/python-pillow/Pillow/issues/7390.
Switch back to the PyPI-installed cibuildwheel for GitHub Actions, also use it from Travis CI.
* https://cibuildwheel.readthedocs.io/en/stable/faq/#option-2-requirement-files
The upcoming Windows wheel build can't use the action, so Renovate can update all three at the same time.
* https://github.com/python-pillow/Pillow/pull/7580#discussion_r1406769153
> Install cibuildwheel from requirements file

- .github/workflows/test-windows.yml
- .github/workflows/wheels-test.ps1
- .github/workflows/wheels-test.sh
- .github/workflows/wheels.yml
- .travis.yml
- Tests/check_wheel.py
- Tests/helper.py
- Tests/test_imagegrab.py
- pyproject.toml
- winbuild/build_prepare.py
For #7390:
* removed wheel building on every push to simplify `test-windows.yml` so `libimagequant` can be included there,
* moved `fribidi` artifact to the wheels workflow so that both x86 and x64 versions are provided,
* moved `CIBW_CONFIG_SETTINGS` to `pyproject.toml` and added `build-verbosity = 1` so that build warnings are visible,
* moved modules/codecs/features check from `wheels-test.sh` to `Tests\check_wheel.py` so that it can also be used on Windows,
* added a Windows build to `wheels.yml`, using `winbuild\build_prepare.py` to build dependencies same as before, building with `cibuildwheel`, and testing in Docker similarly to #6847.
I've included x86 also for https://github.com/python-pillow/Pillow/issues/7443#issuecomment-1756321996; there have been several issues opened about …
> Build Windows wheels using cibuildwheel

- RELEASING.md
- docs/installation.rst
Update Windows wheels information in light of #7580 restoring 32-bit wheels for Windows and adding arm64 wheels.
This reverts #7347 and #7447
> Update Windows wheels info

- src/PIL/PdfImagePlugin.py
Resolves #7554
#7289 set the C palette to be empty by default. The issue has found that this causes P PDFs to appear blank. Testing, I find that the problem is that there can now be fewer than 256 palette entries saved to the PDF file, and that padding the palette to 256 entries fixes it.
> Correct PDF palette size when saving

- src/PIL/ImageStat.py
The optimized function improves the performance. The new implementation uses "sum" instead of the construct
"functools.reduce(operator.add, ...)". Tests showed that the new function is about three times faster than the original. Also it is shorter and easier to read and the dependency to functools and operator modules can be removed.
* Performance optimized ImageStat _getcount function
> Optimization of ImageStat.Stat._getcount method

- docs/handbook/image-file-formats.rst
`streamtype=1` is new in 10.2.0 (#7491); the other values have existed since Git pre-history.
See also [libjpeg-turbo's documentation](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/abeca1f0cc638a6492d81f4c3b956c2dec817c3e/libjpeg.txt#L2429-L2459) on abbreviated datastreams.
> Document JPEG `streamtype` option

- docs/releasenotes/10.2.0.rst
Adds release notes for #7488, #7491 and #7584 / #7587
> Added release notes

- docs/reference/ImageDraw.rst
- src/PIL/ImageFont.py
For #7586
Explicitly mention the default anchor value in the text functions using wording from the [text anchors page](https://pillow.readthedocs.io/en/stable/handbook/text-anchors.html).
> Clarify default anchor alignment

- Tests/test_imagefile.py
- docs/deprecations.rst
- docs/releasenotes/10.2.0.rst
- src/PIL/ImageFile.py
- src/PIL/_deprecate.py
When decoding, we use `raise_oserror()` to convert codec error codes to strings.  Adapt that code to be used when encoding as well.  Add a new helper function that returns the exception so we can still raise `from exc`.
Replace all callers of `raise_oserror()` with `raise _get_oserror()`.  Deprecate `raise_oserror()`, since it doesn't need to be in the public API.
Split out from https://github.com/python-pillow/Pillow/pull/7553#discussion_r1413910020.
> Translate encoder error codes to strings; deprecate `ImageFile.raise_oserror()`

- src/PIL/Image.py
Fixes #7575
*  Importing plugins from a user-specified installation directory of PIL
> Import plugins relative to the module

- src/PIL/ImageChops.py
> Added type hints to ImageChops

- src/PIL/ImageMath.py
`_isconstant()` is short and only called once, we might as well inline it, it's also quicker:
```console
❯ python -m timeit -s "def _isconstant(v): return isinstance(v, (int, float))" "_isconstant(12.34)"
5000000 loops, best of 5: 54.1 nsec per loop
❯ python -m timeit "isinstance(12.34, (int, float))"
10000000 loops, best of 5: 38.3 nsec per loop
```
History:
The current one is from 2019:
```python
def _isconstant(v):
return isinstance(v, (int, float))
```
The 2013, 2to3 version was:
```python
def _isconstant(v):
return isinstance(v, int) or isinstance(v, float)
```
The original 2006, PIL 1.1.6 version was:
```python
def _isconstant(v):
return isinstance(v, type(0)) or isinstance(v, type(0.0))
```
> ImageMath: Inline `isinstance` check

- src/PIL/Image.py
Simple change to fix over half of the `exclude`s in #7622
> Added type hints for format and format_description

- .github/workflows/lint.yml
- pyproject.toml
- tox.ini
Helps #2625.
Run mypy to check type hints:
```sh
tox -e mypy
```
Some good advice here:
* https://mypy.readthedocs.io/en/stable/existing_code.html
So let's start off small with just the `src` directory, and exclude lots of files with warnings, currently 61, so it's running on 34 to begin with.
This adds some fairly lenient settings (happy to tweak them now and later), notably `follow_imports = "silent"`.
When mypy encounters an import, it also checks the imported file, and its imports. They recommend using the default "normal", but lots of things import others which aren't ready yet, so let's change it when we can.
* https://mypy.readthedocs.io/en/stable/running_mypy.html#following-imports
> Check types with mypy

- Tests/test_file_gif.py
- src/PIL/GifImagePlugin.py
Here is one of our tests, originally added in #4003
https://github.com/python-pillow/Pillow/blob/1c2f2c79e13eebdb988e747ba7824ec9f17c6a1e/Tests/test_file_gif.py#L858-L875
Saving multiple identical GIF frames results in a single frame. That PR changed GifImagePlugin to also give that single frame the combined duration. However, if you look at the test, it is saving three frames, but adding together a sequence of four durations. This PR ignores the fourth duration, so that a merged GIF is not longer than it would have been if the frames were not identical.
A second effect of this change is that when saving multiple identical GIF frames with an integer duration (see the last parameter in the test), rather than a sequence, the duration is multiplied by the number of frames, rather than just …
> Corrected duration when combining multiple GIF frames into single frame

- src/PIL/ImageFont.py
- src/_imagingft.c
A minor cleanup.
At the moment, `getmask2` passes `mode` to the C method `font_render`, which determines if the image should be RGBA or L, and then passes that final mode back to Python.
The C method `font_render` doesn't change the value of the `mode` variable passed into it though, so rather than passing an extra piece of information back to Python, the mode can just be set in the Python layer.
> Determine mask mode in Python instead of C

- src/PIL/ImageFont.py
#7244 added `_string_length_check()` in several locations, including `TransposedFont.getlength()`. https://github.com/python-pillow/Pillow/blob/28c173f8d4767c7f6dd22dc840117fe641f4d3ee/src/PIL/ImageFont.py#L711-L716
However, `getlength()` is immediately called after the check, which itself calls `_string_length_check()`.
So this check is unnecessary and can be removed.
> Removed unnecessary string length check

- Tests/test_file_gif.py
- docs/handbook/image-file-formats.rst
- src/PIL/GifImagePlugin.py
- src/PIL/ImagePalette.py
When saving multiple GIF frames, Pillow trims identical edges of each new frame. This PR goes further, setting the pixels that are not new in the next frame as transparent if Pillow is optimizing. If there is no transparency, try and allocate one.
I started work on this after seeing https://github.com/python-pillow/Pillow/issues/6832#issuecomment-1821931777. If I remove `optimize=False` from that code, then without this change the file size is 21.5mb. With this change, the file size is 8.1mb.
For a less dramatic example, the output of https://github.com/python-pillow/Pillow/issues/617#issuecomment-1188984138 is reduced from 408kb to 345kb
Because the only difference in output should be filesize, there are no new tests to demonstrate correctness. I have added a test to cover an exception …
> Fill identical pixels with transparency in subsequent frames when saving GIF

- src/PIL/ImageFile.py
- src/PIL/WebPImagePlugin.py
Here is the logic used to determine whether or not to try memory mapping.
https://github.com/python-pillow/Pillow/blob/9694cfcfda5ca37b771caeaac260ec4d2fc09b58/src/PIL/ImageFile.py#L187-L195
It is expecting `args` to be a tuple, as in the following.
https://github.com/python-pillow/Pillow/blob/9694cfcfda5ca37b771caeaac260ec4d2fc09b58/src/PIL/SunImagePlugin.py#L125
However, here are a few place where the `args` for the "raw" tile is just a string.
https://github.com/python-pillow/Pillow/blob/9694cfcfda5ca37b771caeaac260ec4d2fc09b58/src/PIL/DdsImagePlugin.py#L163
https://github.com/python-pillow/Pillow/blob/9694cfcfda5ca37b771caeaac260ec4d2fc09b58/src/PIL/PsdImagePlugin.py#L265-L268
https://github.com/python-pillow/Pillow/blob/9694cfcfda5ca37b771caeaac260ec4d2fc09b58/src/PIL/WebPImagePlugin. …
> Attempt memory mapping when tile args is a string

- src/PIL/ImageMode.py
Helps #2625.
I also checked in strict mode:
```console
❯ mypy --strict src/PIL/ImageMode.py
Success: no issues found in 1 source file
```
We're not ready to enable strict mode for the tox check, and I don't think we need it for the first pass, but good to fix if not too tricky.
> Add type hints for ImageMode

- src/PIL/Image.py
- src/PIL/ImageSequence.py
> Added type hints to ImageSequence

- .github/workflows/wheels.yml
- winbuild/build_prepare.py
- winbuild/fribidi.cmake
Add a build of ARM64 fribidi.dll to the wheels workflow.
This will simplify manually testing the ARM64 wheels on release day as well as allow users to download a pre-compiled DLL.
Since [CMake does not support mixed host and cross compiling in the same project](https://stackoverflow.com/a/9545369/1648883), the ARM64 build of fribidi.dll is now split into two steps (inspired by [this StackOverflow answer](https://stackoverflow.com/a/36084786/1648883)):
* compile and run helper programs using x86 architecture (x86 programs can also be run on ARM64 using builtin emulation),
* compile fribidi.dll for ARM64 using generated tables from the previous step.
I've also removed the "Prepare to upload FriBiDi" step as it is no longer used with `actions/upload-artifact@v4`.
I've tested the changes as …
> Compile FriBiDi for Windows ARM64

- Tests/oss-fuzz/fuzz_font.py
- Tests/oss-fuzz/fuzz_pillow.py
oss-fuzz coverage has started failing after #7631 - https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=65341&sort=-opened&can=1&q=proj%3Apillow
> Syntax error in /src/Pillow/Tests/oss-fuzz/fuzz_font.py
>   File "/src/Pillow/Tests/oss-fuzz/fuzz_font.py", line 27
>      from \_\_future__ import annotations
>      ^
>  SyntaxError: from \_\_future__ imports must occur at the beginning of the file
> Moved __future__ import to beginning of file

- src/PIL/ContainerIO.py
- src/PIL/TarIO.py
Helps #2625
I took the `__exit__` argument type hints from https://adamj.eu/tech/2021/07/04/python-type-hints-how-to-type-a-context-manager/#class-based-context-managers
> Added TarIO type hints

- docs/conf.py
- docs/example/anchors.py
- selftest.py
Three files where the changes were minor enough that it felt worth bundling them together.
> Added type hints to selftest.py, docs/conf.py and docs/example/anchors.py

- src/PIL/ImageMode.py
Use `functools.lru_cache` instead of our own global cache, to only cache those which are requested.
With no argument, `lru_cache` defaults to `maxsize=128`, plenty for the 33 valid inputs.
https://docs.python.org/3/library/functools.html#functools.lru_cache
Performance improves for all the following cases.
Before and after:
```console
❯ python3 -m timeit -s "from PIL import ImageMode" "ImageMode.getmode('RGB')"
10000000 loops, best of 5: 33.6 nsec per loop
❯ python3 -m timeit -s "from PIL import ImageMode" "ImageMode.getmode('RGB')"
10000000 loops, best of 5: 28.5 nsec per loop
```
```console
❯ python3 -m timeit -s "from PIL import ImageMode" "ImageMode.getmode('I;16N')"
10000000 loops, best of 5: 36 nsec per loop
❯ python3 -m timeit -s "from PIL import ImageMode" …
```
> Optimise `ImageMode.getmode` using `functools.lru_cache`

- docs/handbook/image-file-formats.rst
Read support for subsampled RGB and YCbCr color channels was added in 4f4c3b34f8 and not documented at the time.  Write support for YCbCr appears to date to 61fb89ec54, the original commit.
Retain the existing language about YCbCr input conversion to RGB, even though it's not completely correct.  OpenJPEG through 2.5.0 doesn't set `color_space` in `opj_read_header()`, so we end up in our `OPJ_CLRSPC_UNSPECIFIED` fallback path, which guesses sRGB if there's no component subsampling.  This means we currently can't round-trip YCbCr via JPEG 2000.  The next OpenJPEG release will fix this (https://github.com/uclouvain/openjpeg/pull/1463) so leave the docs as is.
Also fix typo: `.j2p` -> `.jp2`.
> Document JPEG 2000 support for writing YCbCr and reading subsampled color

- Tests/test_fontfile.py
- src/PIL/BdfFontFile.py
- src/PIL/FontFile.py
- src/PIL/Image.py
- src/PIL/PcfFontFile.py
- src/PIL/_binary.py
Adds type hints to FontFile, BdfFontFile and PcfFontFile.
In doing so,
- I found that https://github.com/python-pillow/Pillow/blob/1e8bad805ec763f4bf1c265cf26a3deee4fec071/src/PIL/FontFile.py#L68
is the only time that `FontFile.compile()` returns something other than `None`. I've changed that to be consistent.
- I changed the following error
```pycon
>>> from PIL import FontFile
>>> font = FontFile.FontFile()
>>> font.save("out")
File "PIL/FontFile.py", line 97, in save
self.bitmap.save(os.path.splitext(filename)[0] + ".pbm", "PNG")
AttributeError: 'NoneType' object has no attribute 'save'
```
to "ValueError: No bitmap created" instead.
> Added type hints to FontFile and subclasses

- Tests/oss-fuzz/fuzz_font.py
- Tests/oss-fuzz/fuzz_pillow.py
- pyproject.toml
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=65341 is still open, complaining that `from __future__ imports must occur at the beginning of the file`, despite #7637 moving the imports.
I asked about this at https://github.com/google/oss-fuzz/issues/11415, and was told that oss-fuzz [prepends code to the files](https://github.com/google/oss-fuzz/blob/55650963e17693deedfe2ed86df2544cf124ab8b/infra/base-images/base-builder/compile_python_fuzzer#L56-L75).
I think the solution here is to just remove `from __future__ import annotations` from fuzz_font.py and fuzz_pillow.py. I've tested it in my oss-fuzz fork, and [it fails without this](https://github.com/radarhere/oss-fuzz/actions/runs/7352047687/job/20016249063), but [passes with.](https://github.com/radarhere/oss-fuzz/actions/runs/735 …
> Removed __future__ import from fuzz_font.py and fuzz_pillow.py

- .github/release-drafter.yml
We have a number of https://github.com/python-pillow/Pillow/labels/Type%20hints PRs in this release, and will do in the future.
Let's add it as a category for https://github.com/python-pillow/Pillow/releases
> Add 'Type hints' as a release note category

- Tests/test_imagefont.py
#7244 added the following test code
https://github.com/python-pillow/Pillow/blob/78b96c037597b56b125257f568de04b4d8921118/Tests/test_imagefont.py#L1056-L1060
At the time, this was testing the "better than nothing" font that uses ImageFont class. However, #7354 changed the default font in some environments, so the ImageFont class would no longer have been covered in this test.
This PR fixes that by creating an instance of the ImageFont class directly.
> Restored testing of ImageFont class

- Tests/test_imagemath.py
- docs/releasenotes/10.2.0.rst
- src/PIL/ImageMath.py
Prevent environment keys matching the names of builtins and keys containing double underscores from being passed to [`ImageMath.eval()`](https://pillow.readthedocs.io/en/stable/reference/ImageMath.html#PIL.ImageMath.eval), by raising a ValueError.
> Restricted environment keys for ImageMath.eval()

- src/PIL/ImageColor.py
Follow on from https://github.com/python-pillow/Pillow/pull/7632, use `functools.lru_cache` to cache the computed colours of `ImageColor.getrgb(color)` and `ImageColor.getcolor(color, mode)`.
Running these:
```sh
python3 -m timeit --unit usec -s "from PIL import ImageColor" "ImageColor.getrgb('red')"
python3 -m timeit --unit usec -s "from PIL import ImageColor" "ImageColor.getrgb('#defdef')"
python3 -m timeit --unit usec -s "from PIL import ImageColor" "ImageColor.getrgb('#00f')"
python3 -m timeit --unit usec -s "from PIL import ImageColor" "ImageColor.getrgb('rgb(0,255,0)')"
python3 -m timeit --unit usec -s "from PIL import ImageColor" "ImageColor.getrgb('rgba(255,0,0,0)')"
python3 -m timeit --unit usec -s "from PIL import ImageColor" "ImageColor.getrgb('hsl(0.1,99.2%,50.3%)')"
python3 …
```
> Optimise `ImageColor` using `functools.lru_cache`

- src/PIL/ContainerIO.py
- src/PIL/TarIO.py
The two ignore comments are required because mypy doesn't know that `"b" in self.fh.mode` if and only if `self` is a `ContainerIO[bytes]` rather than a `ContainerIO[str]`.
> Add type hints to PIL.ContainerIO

- src/PIL/IptcImagePlugin.py
- src/PIL/_binary.py
There are two tricky parts in adding type hints to `PIL._binary`:
The `i16*` and `i32*` give a "Returning Any from function declared to return int" in `--strict` mode due to the use of `struct.unpack_from`. This can be properly silenced with `#type: ignore[no-any-return]`, but that gives a "Unused type ignore comment" when running without `--strict`, so I have left it out for now.
The `i8` function distinguishes between `int` and `bytes` inputs in a way that mypy doesn't recognize. Since `i8` is called with an `int` input only from `IptcImagePlugin`, I have removed those calls there and removed `int` support as input to `i8`.
Although the values in `self.info[(3, 60)]` and `self.info[(3, 65)]` can be lists if the tags are duplicated, these tags are marked as "non-repeatable" in [the …
> Add type hints to _binary

- Tests/test_file_tiff.py
- Tests/test_file_tiff_metadata.py
- src/PIL/TiffImagePlugin.py
Resolves #6607, allowing the [ROWSPERSTRIP](https://www.awaresystems.be/imaging/tiff/tifftags/rowsperstrip.html) tag to be set by the user when saving TIFF images, instead of calculating the value.
> Support setting ROWSPERSTRIP tag

- Tests/test_image.py
- src/PIL/Image.py
At the moment,
```python
with Image.new("L", (1, 1)) as im:
print(hasattr(im, "fp"))
print(hasattr(im, "fp"))
```
gives
```
False
True
```
`im` does not have an `fp` attribute inside the context manager, but once it leaves, it is set.
This PR keeps it unset.
> Do not assign new fp attribute when exiting context manager

- Tests/test_file_iptc.py
- src/PIL/IptcImagePlugin.py
Looking at
https://github.com/python-pillow/Pillow/blob/0988703a90582540d3a2d6576cab11edd6673e5b/src/PIL/IptcImagePlugin.py#L131-L133
I find this odd, as it does not match the structure that we otherwise have for `self.tile`.
https://github.com/python-pillow/Pillow/blob/0988703a90582540d3a2d6576cab11edd6673e5b/src/PIL/ImageFile.py#L93-L97
https://github.com/python-pillow/Pillow/blob/0988703a90582540d3a2d6576cab11edd6673e5b/src/PIL/JpegImagePlugin.py#L396
The reason this problem has not been found by the test suite is that no test actually opens a valid IPTC image.
This PR changes the `self.tile` tuple to match the format used in other plugins.
```python
self.tile = [("iptc", (0, 0) + self.size, offset, compression)]
```
I've reversed-engineered test data for `_open` from the code.
> Changed IPTC tile tuple to match other plugins

- .github/problem-matchers/gcc.json
- .github/workflows/test.yml
Similar to https://github.com/python/cpython/pull/18567, but I found there are extra spaces printed before the file name.
Would help find issues like https://github.com/python-pillow/Pillow/pull/7497#discussion_r1406492621 faster.
The matcher is only run on a single Ubuntu job to prevent duplicate annotations; I found that the macOS jobs created two annotations per warning.
See https://github.com/nulano/Pillow/pull/25 for an example.
Not adding a problem matcher for MSVC yet because there are already many warnings that need to be fixed first to avoid noise.
> Add gcc problem matcher to test.yml

- Tests/test_file_iptc.py
- docs/deprecations.rst
- docs/releasenotes/10.2.0.rst
- src/PIL/Image.py
- src/PIL/IptcImagePlugin.py
For https://github.com/python-pillow/Pillow/pull/7659#issuecomment-1872956475, includes https://github.com/python-pillow/Pillow/pull/7659
> Deprecate IptcImagePlugin helpers

- .coveragerc
- Tests/test_imagemorph.py
* With recent Coverage.py, we can use `exclude_also` instead of `exclude_lines` which requires re-enabling the standard pragma
* `create_lut()` was a helper method not run anywhere, should we delete it instead?
* `class TypeGuard` is compatibility code being introduced in https://github.com/python-pillow/Pillow/pull/7642. We have a `# type: ignore[no-redef]` on it, and I don't think we need to cover it in tests either.
> Coverage: add more exclusions

- Tests/test_imagefontpil.py
- src/_imaging.c
> Trim negative glyph offsets in ImageFont.getmask()

- Tests/test_file_jpeg.py
- docs/handbook/image-file-formats.rst
- docs/releasenotes/10.2.0.rst
- src/PIL/JpegImagePlugin.py
- src/encode.c
- src/libImaging/Jpeg.h
- src/libImaging/JpegEncode.c
libjpeg automatically converts RGB to YCbCr by default.  Add a `keep_rgb` option to disable libjpeg's automatic conversion of RGB images during write.
> Add `keep_rgb` option when saving JPEG to prevent conversion of RGB colorspace

- docs/handbook/tutorial.rst
While testing https://github.com/python-pillow/Pillow/issues/7673#issuecomment-1873401715 I found that the image has moved from https://python-pillow.org/images/pillow-logo.png to https://python-pillow.org/assets/images/pillow-logo.png.
> Fix image URL in "Reading from URL" example

- RELEASING.md
When following the releasing process in https://github.com/python-pillow/Pillow/issues/7571, I found that the wheel filenames now include 'pillow' in lowercase. This is likely a result of cibuildwheel in https://github.com/python-pillow/Pillow/pull/7552
> Package name is now lowercase in wheel filenames

- .github/workflows/wheels.yml
As the PyPy3.8 wheels is skipped on macOS and Linux - https://github.com/python-pillow/Pillow/pull/7552#issuecomment-1812871988
https://github.com/python-pillow/Pillow/blob/dacd92853094414ab6a4326e7f5805666b92996c/.github/workflows/wheels.yml#L74
> Skip PyPy3.8 Windows wheel

- docs/reference/ImageGrab.rst
Resolves #7677
Improve documentation of `bbox` for `ImageGrab.grab()` on macOS.
> ImageGrab.grab() bbox on macOS is not 2x on retina screens

- docs/reference/ImageGrab.rst
> If ImageGrab.grab() bbox is omitted, screenshot is taken at 2x on Retina screens

- .github/workflows/wheels.yml
Minor suggestion.
Renames `archs` in Linux and macOS
https://github.com/python-pillow/Pillow/blob/27eacddfd51fab9b4432b3e228836b5947685763/.github/workflows/wheels.yml#L33-L46
to `cibw_arch`, to better match the variable name used in Windows
https://github.com/python-pillow/Pillow/blob/27eacddfd51fab9b4432b3e228836b5947685763/.github/workflows/wheels.yml#L83-L93
> Updated Linux and macOS wheels matrix variable name

- src/PIL/ImageFont.py
- src/_imagingft.c
* Call `Image._decompression_bomb_check` directly in `fill` rather than duplicating its code. If an error is raised, it is propagated via the `if (image == NULL)` branch.
* On error, delete the Python `image` object by releasing the only reference to it (causing Python to call its `tp_dealloc` slot, i.e. `_dealloc` in `_imaging.c`) instead of just freeing the memory it points to (added in #7218).
* Avoid nonlocal variables (to simplify adding type hints in a future PR by avoiding the need for a `typing.cast` or `assert size is not None`).
This partially reverts changes from #7246, which was connected to an oss-fuzz error, but I do not see any added tests or reproduction steps. IIUC, the original error was a memory leak, which I avoid in a different …
> Simplify FreeTypeFont.render

- .github/workflows/test-windows.yml
Like https://github.com/python-pillow/Pillow/pull/7468.
Since then, https://github.com/python-pillow/Pillow/pull/7580 moved Windows wheel building from `test-windows.yml` to `wheels.yml` so we can also skip running `test-windows.yml` for tags:
This will speed up releases, especially given https://github.com/python-pillow/Pillow/pull/7690 which needs as much CI capacity as possible.
> Skip non-wheel CI runs for tags: Windows

- docs/PIL.rst
- docs/reference/ImageTransform.rst
- docs/reference/index.rst
- src/PIL/Image.py
- src/PIL/ImageTransform.py
Helps #7683
With the exception of `ImageTransform.Transform`, the rest of the `ImageTransform` module seems to be well documented.
* Document `ImageTransform.Transform`.
* Move `ImageTransform` from the `PIL package` subheading to the main list.
* Link to `ImageTransform` from `Image.transform`.
> Improve ImageTransform documentation

- Tests/test_file_eps.py
- Tests/test_image_resample.py
- src/libImaging/GifEncode.c
- src/libImaging/Jpeg.h
"non-zero" is used in Pillow [more frequently](https://github.com/search?q=repo%3Apython-pillow%2FPillow+non-zero&type=code) than ["nonzero"](https://github.com/search?q=repo%3Apython-pillow%2FPillow+nonzero&type=code)
This PR makes some changes for consistency.
> Use "non-zero" consistently

- README.md
- docs/about.rst
- docs/index.rst
- docs/installation.rst
Because the wheels now use lowercase `pillow`, the PyPI page has changed name to also be lowercase, which causes `make doccheck` to warn on main: https://github.com/python-pillow/Pillow/actions/runs/7432229048/job/20223791525#step:7:556
> PyPI project page URL is now lowercase

- src/PIL/Image.py
- src/PIL/ImageFile.py
- src/PIL/ImagePalette.py
- src/PIL/McIdasImagePlugin.py
- src/PIL/PcdImagePlugin.py
- src/PIL/PcxImagePlugin.py
- src/PIL/PixarImagePlugin.py
- src/PIL/SunImagePlugin.py
- src/PIL/XVThumbImagePlugin.py
- src/PIL/XbmImagePlugin.py
Add type hints to seven plugins that require minimal changes to adhere to `mypy --strict`.
- McIdasImagePlugin
- PcdImagePlugin
- PcxImagePlugin
- PixarImagePlugin
- SunImagePlugin
- XVThumbImagePlugin
- XbmImagePlugin
> Added type hints to seven plugins

- src/PIL/ImageMath.py
> Changed ImageMath.ops to be static

- src/PIL/Image.py
- src/PIL/ImageFile.py
- src/PIL/PpmImagePlugin.py
Helps https://github.com/python-pillow/Pillow/issues/2625.
> Added type hints to PpmImagePlugin

- Tests/helper.py
Do not use [test-image-results](https://pypi.org/project/test-image-results/) to upload images after test failures.
Suggested in https://github.com/python-pillow/Pillow/pull/7733#discussion_r1460362160
> Do not support using test-image-results to upload images after test failures

- .github/workflows/docs.yml
- .github/workflows/test.yml
- depends/download-and-extract.sh
- depends/install_imagequant.sh
On the CI, the step to "Install Linux dependencies" takes between 6m10s and 6m30s.
The step runs `.ci/install.sh` and its slowest commands are:
```sh
pushd depends && ./install_webp.sh && popd
pushd depends && ./install_imagequant.sh && popd
pushd depends && ./install_raqm.sh && popd
```
They take ~25s, ~4m30s and ~40s respectively.
Given the Linux jobs mostly take around 8m30s, caching these steps can save up to 5m30s, and would greatly improve the CI time.
Let's start with the slowest: libimagequant.
First, add to the workflow a cache step:
```yaml
- name: Cache libimagequant
uses: actions/cache@v4
id: cache-libimagequant
with:
path: ~/cache-libimagequant
key: ${{ runner.os }}-libimagequant-${{ hashFiles('depends/install_imagequant.sh') }}
```
If there's a matching cache file, it …
> CI: Cache libimagequant on Linux builds

- .github/workflows/macos-install.sh
- .github/workflows/test.yml
GitHub Actions now has macOS M1 runners:
* https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
* https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/
Python 3.9.1 was the first to support Apple Silicon: 
* https://www.python.org/downloads/release/python-391/
But 3.9 is not currently available for M1:
* https://github.com/actions/setup-python/issues/696#issuecomment-1637587760
So let's test 3.10-3.13 on M1, and 3.8-3.9 on Intel.
I bumped the `PYTHONOPTIMIZE` jobs from 3.8/3.9 to 3.10/3.11 to avoid complicating the matrix includes/excludes. And needed to install Ghostscript, it wasn't already on the image.
Here's how long it took to test on M1 (left) and Intel (right). M1 is faster for …
> Test on macOS M1 where available

- .github/workflows/test-cygwin.yml
Our Cygwin jobs have been failing for several days - https://github.com/python-pillow/Pillow/actions/workflows/test-cygwin.yml
In looking at a discussion over at NumPy about this, there was a suggestion to use the egor-tension/setup-cygwin action and pin to Python 3.9.16-1 - https://github.com/numpy/numpy/issues/25708#issuecomment-1913885487
> Pin to Python 3.9.16-1

- src/PIL/ImageFile.py
https://github.com/python-pillow/Pillow/blob/e47877587fb8aa1853ef7473285a2964f5e98520/src/PIL/ImageFile.py#L93-L97
Because tiles can be used to indicate either how an image is to be encoded or decoded, I suggest `codec_name` instead of `encoder_name`.
> Changed name of first _Tile parameter

- .github/workflows/wheels-dependencies.sh
https://github.com/python-pillow/Pillow/issues/6862#issuecomment-1913552472 is a report from a user that Pillow 10.2.0 wheels cause the following error on macOS 10.10
```pytb
File "<string>", line 1, in <module>
File "/Users/just/code/git/drawbot/venv312/lib/python3.12/site-packages/PIL/Image.py", line 84, in <module>
from . import _imaging as core
ImportError: dlopen(/Users/just/code/git/drawbot/venv312/lib/python3.12/site-packages/PIL/_imaging.cpython-312-darwin.so, 2): Library not loaded: @loader_path/libXau.6.0.0.dylib
Referenced from: /Users/just/code/git/drawbot/venv312/lib/python3.12/site-packages/PIL/.dylibs/libxcb.1.1.0.dylib
Reason: no suitable image found.  Did find:
/Users/just/code/git/drawbot/venv312/lib/python3.12/site-packages/PIL/.dylibs/ …
```
> Fixed libXau error in wheels for macOS 10.10

- .github/workflows/test-cygwin.yml
When #7762 switched from [cygwin/cygwin-install-action](https://github.com/cygwin/cygwin-install-action) to [egor-tensin/setup-cygwin](https://github.com/egor-tensin/setup-cygwin), I didn't remove the 'platform' argument that the new action doesn't use.
This has led to a warning - https://github.com/python-pillow/Pillow/actions/runs/7764314475/job/21177567318#step:4:1
> Warning: Unexpected input(s) 'platform', valid inputs are ['install-dir', 'packages', 'env', 'hardlinks']
> Removed platform argument from setup-cygwin action

- .github/workflows/test-cygwin.yml
- .github/workflows/test-docker.yml
- .github/workflows/test-mingw.yml
- .github/workflows/test-windows.yml
- .github/workflows/test.yml
There's a breaking change in https://github.com/python-pillow/Pillow/pull/7770 from bumping codecov/codecov-action to v4 which affects us, requiring setting a token due to rate limiting:
https://github.com/codecov/codecov-action/releases/tag/v4.0.0
> Tokenless uploading is unsupported. However, PRs made from forks to the upstream public repos will support tokenless (e.g. contributors to OS projects do not need the upstream repo's Codecov token). This [doc](https://docs.codecov.com/docs/adding-the-codecov-token#github-actions) shows instructions on how to add the Codecov token.
v4 doesn't need a token for PRs from forks, but does for merges. This is why coverage has dropped to ~50% for merges, because it's only recording the coverage from AppVeyor: …
> Pin codecov/codecov-action to v3.1.5

- src/PIL/ImageGrab.py
Simpified logic and made it more robust against edge cases ( see the `allowed_errors` list ). 
Doing error checking this way, makes the behaviour of this function for x11 and wayland platforms more similar to darwin and windows systems.
> Update wl-paste handling and return None for some errors in grabclipboard() on Linux

- .coveragerc
- pyproject.toml
- src/PIL/DdsImagePlugin.py
- src/PIL/ImImagePlugin.py
- src/PIL/Image.py
- src/PIL/ImageQt.py
- src/PIL/ImageShow.py
- src/PIL/PdfParser.py
- src/PIL/PyAccess.py
- src/PIL/TiffImagePlugin.py
- src/PIL/TiffTags.py
- src/PIL/_imaging.pyi
- src/PIL/_tkinter_finder.py
- src/PIL/_webp.pyi
- tox.ini
Removes the mypy excludes, except for FpxImagePlugin.py and MicImagePlugin.py, as olefile isn't typed.
> Removed mypy excludes, except for olefile-related files

- .coveragerc
- Tests/test_image.py
- Tests/test_util.py
- docs/reference/internal_design.rst
- docs/reference/internal_modules.rst
- docs/reference/open_files.rst
- src/PIL/GdImageFile.py
- src/PIL/Image.py
- src/PIL/ImageFont.py
- src/PIL/MpegImagePlugin.py
- src/PIL/_typing.py
- src/PIL/_util.py
Alternative to and closes https://github.com/python-pillow/Pillow/pull/7737.
In type hints like `fp: io.BytesIO`, we should avoid the concrete `io.BytesIO`, and use more specific type hints to reflect what the file-like object actually does.
The one in `GdImageFile.py` is used in many ways, so has more complex hints; the one in `MpegImagePlugin.py` is used in fewer so is more focused.
This takes some type hints from typeshed:
* https://github.com/python/typeshed/blob/2168ab5ff4e40c37505b3e5048944603b71a857d/stdlib/_typeshed/__init__.pyi#L239-L257
* https://github.com/python/typeshed/blob/2168ab5ff4e40c37505b3e5048944603b71a857d/stdlib/_typeshed/__init__.pyi#L162
* (which are also in the useful_types package: https://github.com/hauntsaninja/useful_types/blob/951d36b2aaaee6ab9fa1efcb8c4f1e27 …
> Replace `io.BytesIO` in type hints

- src/PIL/ImageFile.py
- src/PIL/MspImagePlugin.py
- src/PIL/PcxImagePlugin.py
- src/PIL/PpmImagePlugin.py
- src/PIL/SgiImagePlugin.py
- src/PIL/TgaImagePlugin.py
- src/PIL/XbmImagePlugin.py
https://github.com/python-pillow/Pillow/pull/7750#issue-2096982939
> Four other plugins have BytesIO hints to replace
This PR replaces `BytesIO` in type hints with `IO[bytes]`
> Use IO[bytes] in type hints

- .github/workflows/test-windows.yml
Python 3.13 on Windows in GitHub Actions has started failing, with https://github.com/python-pillow/Pillow/actions/runs/7937029330/job/21673447008#step:25:535
> LINK : fatal error LNK1104: cannot open file 'python313t.lib'
The failure started with 3.13.0a4.
https://github.com/python/cpython/pull/109922 leads me to believe that the 't' relates to builds without gil.
So I conclude that this problem has been reported as https://github.com/python/cpython/issues/115545, which says
> It seems the free-threaded and non-free-threaded build got mixed up, and so the main executable in the package is nogil and looking for the wrong DLL.
> ...
> This needs to be fixed before the next alpha.
a5 is scheduled to be released on March 12. So this PR pins to a3 to allow our CIs to pass in the meantime.
> Pin Python 3.13 on Windows to a3

- pyproject.toml
- tox.ini
Sequel to #7790
https://pypi.org/project/types-olefile/ now exists, so this can be used to remove the last of the mypy excludes.
> Removed mypy excludes

- .github/FUNDING.yml
- README.md
- docs/conf.py
- docs/index.rst
Relates to #7681
In the README and at https://pillow.readthedocs.io/en/latest/, our Tidelift badge currently reads "not lifted!".
The image source is https://tidelift.com/badges/package/pypi/Pillow?style=flat
Changing 'Pillow' to 'pillow', I find that it works again.
Similarly, the 'Sponsor our project' sidebar item at https://github.com/python-pillow/Pillow links to https://tidelift.com/funding/github/pypi/Pillow, but redirects to https://tidelift.com/subscription/how-to-connect-tidelift-with-github.
Changing 'Pillow' to 'pillow', I find that it works again.
> Updated package name for Tidelift

- .github/workflows/docs.yml
Also run the docs workflow when Python files are updated, as this can affect Documentation if e.g. type hints are changed. This could have prevented issues such as what caused https://github.com/python-pillow/Pillow/pull/7812.
> Build docs for Python changes

- docs/releasenotes/10.3.0.rst
- src/_webp.c
`WebPAnimDecoderGetNext` is a relatively expensive pure-C call that currently holds the Python GIL. Release it!
(Haven't tested this branch but it seemed like a straightforward change.)
> Release GIL while calling `WebPAnimDecoderGetNext`

- .appveyor.yml
- .github/workflows/test-cygwin.yml
- .github/workflows/test-mingw.yml
- .github/workflows/test-windows.yml
- .github/workflows/test.yml
Python 3.12 introduced [sys.monitoring](https://docs.python.org/3/library/sys.monitoring.html), that tools like coverage.py can use to improve performance.
It's not yet the default in coverage.py. To enable, we can set a `COVERAGE_CORE=sysmon` environment variable, that will switch to the faster mode when available, that is, in Python 3.12 and newer. Older versions will stick to the older method.
For example, on my machine:
test | command | result
-|-|-
No coverage | `python3 -m pytest Tests` | 4269 passed, 224 skipped, 3 xfailed in 48.21s
Coverage: default core | `python3 -m pytest --cov PIL --cov Tests Tests` | 4269 passed, 224 skipped, 3 xfailed in 58.15s
Coverage: sysmon core | `COVERAGE_CORE=sysmon python3 -m pytest --cov PIL --cov Tests Tests` | 4269 passed, 224 skipped, 3 xfailed …
> Set `COVERAGE_CORE: sysmon` for faster tests on 3.12+

- .github/workflows/test-windows.yml
Re: https://github.com/python-pillow/Pillow/pull/7820#issuecomment-1960938189
Coverage.py 7.4.0 added support for Python 3.12's `sys.monitoring` and `COVERAGE_CORE: sysmon`, but would also enable it on older versions of Python and fail.
Coverage.py 7.4.2 only uses `sys.monitoring` when `COVERAGE_CORE: sysmon` and we're on 3.12+.
So let's make sure we have at least 7.4.2 installed.
I only set it for the workflow that started failing (probably due to caching). We could add it to the others, but I think it's fine if they're passing.
> Require coverage.py 7.4.2+ for `COVERAGE_CORE: sysmon`

- docs/deprecations.rst
- docs/installation.rst
I think we can remove the three warnings from the top of https://pillow.readthedocs.io/en/stable/installation.html
---
> Pillow and PIL cannot co-exist in the same environment. Before installing Pillow, please uninstall PIL.
I seem to remember that around ten years ago, it used to be possible to install PIL from PyPI. 
It used to be that PyPI would allow installing files hosted elsewhere, but now all files must be uploaded to PyPI, and there are no downloadable files at https://pypi.org/project/PIL/.
I don't think it's possible now to install PIL and Pillow at the same time, even if you tried installing PIL from source.
---
> Pillow >= 1.0 no longer supports `import Image`. Please use `from PIL import Image` instead.
https://pypi.org/project/pillow/1.0/ was released in 2010. I don't think …
> Remove outdated installation warnings

- docs/reference/ImageOps.rst
- src/PIL/ImageOps.py
> Changed SupportsGetMesh protocol to be public

- .github/workflows/test-mingw.yml
MinGW has started failing in main.
Looking through the output, I saw https://github.com/python-pillow/Pillow/actions/runs/8102796165/job/22146045896#step:6:3514
> ModuleNotFoundError: No module named 'pip._vendor.distlib'
Using `python3 -m ensurepip` instead of the `mingw-w64-x86_64-python3-pip` package fixes the job.
> Do not use packaged MinGW pip

- Tests/test_file_gif.py
- src/PIL/GifImagePlugin.py
Resolves #7777
When looping through images to create a GIF image, the frames may be different sizes.
At the moment, this means that
https://github.com/python-pillow/Pillow/blob/1b6723967440cf8474a9bd1e1c394c90c5c2f986/src/PIL/GifImagePlugin.py#L671
`fill` comes from the size of the new frame, whereas `mask` comes from `ImageChops.subtract_modulo()` between the new and the old frame.
This may cause a mismatch in size between the image being pasted and the mask, which can lead to an error.
> Match mask size to pasted image size in GifImagePlugin

- .github/workflows/wheels-dependencies.sh
- .github/workflows/wheels-test.sh
- .github/workflows/wheels.yml
#7766 started testing macOS CI jobs on M1 where available.
We can go further, building macOS M1 wheels natively. This also means that we can start testing macOS M1 wheels, [apart from Python 3.8.](https://github.com/pypa/cibuildwheel/blob/ae2451a199bdec6636108b1110cf633157dba7e0/cibuildwheel/macos.py#L520-L523)
> Build macOS arm64 wheels natively

- docs/installation/basic-installation.rst
- docs/installation/building-from-source.rst
- docs/installation/index.rst
- docs/installation/old-versions.rst
- docs/installation/platform-support.rst
- docs/installation/python-support.rst
Follow on from https://github.com/python-pillow/Pillow/pull/7832.
Fix:
* Move anchors back into place
* Fix reference link
* Fix tab activation per OS
* Consistent header underlines
The Old Versions section is very short, I don't think it needs its own page. How about move it to the end of the 'Building From Source' page?
> Update installation docs

- src/libImaging/Convert.c
Fixes
```
libImaging/Convert.c:513:25: error: signed shift result (0xFF000000) sets the sign bit of the shift expression's type ('int') and becomes negative [-Werror,-Wshift-sign-overflow]
UINT32 trns = (0xff << 24) | ((b & 0xff) << 16) | ((g & 0xff) << 8) | (r & 0xff);
~~~~ ^  ~~
```
> Fix shift-sign issue in Convert.c

- setup.py
Resolves #7759
The issue describes many warnings being raised when verbosely building Pillow on macOS. They are mostly warnings of "pointer is missing a nullability type specifier"
```
/Library/Developer/CommandLineTools/SDKs/MacOSX14.2.sdk/usr/include/stdlib.h:136:23: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
long     atol(const char *);
^
/Library/Developer/CommandLineTools/SDKs/MacOSX14.2.sdk/usr/include/stdlib.h:136:23: note: insert '_Nullable' if the pointer may be null
long     atol(const char *);
^
_Nullable
/Library/Developer/CommandLineTools/SDKs/MacOSX14.2.sdk/usr/include/stdlib.h:136:23: note: insert '_Nonnull' if the pointer should never be null
long     atol(const char *);
^
_Nonnull
``` …
> Turn off nullability warnings for macOS SDK

- src/PIL/EpsImagePlugin.py
- src/PIL/IcoImagePlugin.py
- src/PIL/ImageFile.py
- src/PIL/XpmImagePlugin.py
`load_read()` does not have a consistent signature across the plugins where it is used. For example,
https://github.com/python-pillow/Pillow/blob/9923531742726419732618c6f2aef0bb8c21e259/src/PIL/JpegImagePlugin.py#L411
https://github.com/python-pillow/Pillow/blob/9923531742726419732618c6f2aef0bb8c21e259/src/PIL/XpmImagePlugin.py#L106
Neither does `load_seek()`. For example,
https://github.com/python-pillow/Pillow/blob/9923531742726419732618c6f2aef0bb8c21e259/src/PIL/FtexImagePlugin.py#L105
https://github.com/python-pillow/Pillow/blob/9923531742726419732618c6f2aef0bb8c21e259/src/PIL/IcoImagePlugin.py#L342
> Use consistent arguments for load_read and load_seek

- Tests/test_font_leaks.py
Similar to https://github.com/python-pillow/Pillow/pull/7669/commits/ecd3948b45ca9c4c2e8b0b3cb58fe6af9798cfa2
This changes `TestDefaultFontLeak` to test the non-TrueType default font, as it would have been doing before #7354
> Restored testing of non-TrueType default font

- Tests/test_file_ico.py
- src/PIL/IcoImagePlugin.py
When copying image attributes from the image returned by `IcoFile.getimage()`, IcoImageFile copies the mode, but not the palette.
This fixes that.
> Use palette when loading ICO images

- Tests/test_file_jpeg.py
- Tests/test_image.py
- Tests/test_imagefile.py
- src/PIL/Image.py
`register_decoder()` and `register_encoder()` state that `decoder`/`encoder` are callables that return an object.
https://github.com/python-pillow/Pillow/blob/912a33f5e9815735d994c856fa241856e13c694c/src/PIL/Image.py#L3527-L3534
https://github.com/python-pillow/Pillow/blob/912a33f5e9815735d994c856fa241856e13c694c/src/PIL/Image.py#L3541-L3548
However, if you look at Pillow's source code, it is not a callable, it is just an object.
https://github.com/python-pillow/Pillow/blob/912a33f5e9815735d994c856fa241856e13c694c/src/PIL/BlpImagePlugin.py#L472-L476
https://github.com/python-pillow/Pillow/blob/912a33f5e9815735d994c856fa241856e13c694c/src/PIL/PpmImagePlugin.py#L362-L363
https://github.com/python-pillow/Pillow/blob/912a33f5e9815735d994c856fa241856e13c694c/src/PIL/DdsImagePlugin.py#L569 …
> Decoders and encoders subclass PyDecoder and PyEncoder

- Tests/test_file_apng.py
- src/PIL/PngImagePlugin.py
https://github.com/python-pillow/Pillow/issues/1138#issuecomment-1955716795 reported an image that `img.show()` did not successfully open.
Images are temporarily saved as PNGs when used with `show()`. The image has two frames of different sizes, and investigating, I found that https://wiki.mozilla.org/APNG_Specification states
> The boundaries of the entire animation are specified by the width and height parameters of the PNG `IHDR` chunk
and
> each frame's region (x,y,width,height) must lie completely within the parent PNG canvas
This PR expands the size in the IHDR chunk to the maximum size of all of the frames, and that fixes the problem.
> Use maximum frame size in IHDR chunk when saving APNG images

- depends/install_imagequant.sh
- docs/installation/building-from-source.rst
libimagequant 4.3.0 has been released - https://github.com/ImageOptim/libimagequant/releases/tag/4.3.0
> Updated libimagequant to 4.3.0

- src/PIL/Image.py
In main,
```python
import logging
from PIL import Image, ExifTags
im = Image.open("/Users/andrewmurray/pillow/Pillow/Tests/images/exif_gps.jpg")
exif = im.getexif()
logging.basicConfig(level=logging.DEBUG)
exif.get_ifd(ExifTags.IFD.GPSInfo)
```
gives
```
DEBUG:PIL.TiffImagePlugin:tag: unknown (0) - type: byte (1) - value: b'\x00\x00\x00\x01'
DEBUG:PIL.TiffImagePlugin:tag: unknown (2) - type: rational (5) Tag Location: 392 - Data Location: 428 - value: b'\xff\xff\xff\xff\x00\x00\x00\x01'
DEBUG:PIL.TiffImagePlugin:tag: unknown (5) - type: byte (1) - value: b'\x01'
DEBUG:PIL.TiffImagePlugin:tag: unknown (29) - type: string (2) Tag Location: 416 - Data Location: 436 - value: b'1999:99:99 99:99:99\x00'
DEBUG:PIL.TiffImagePlugin:tag: unknown (30) - type: short (3) - value: b'\xff\xff'
```
This …
> Fix logged tag name when loading Exif data

- Tests/test_file_tiff_metadata.py
- src/PIL/TiffImagePlugin.py
Resolves https://github.com/python-pillow/Pillow/issues/7839. Similar to https://github.com/python-pillow/Pillow/pull/6890
The issue provides an image where the InteropVersion tag has type RATIONAL.
https://exiftool.org/TagNames/EXIF.html states that it should have type UNDEFINED. The tag is loaded as RATIONALs, but this causes an error when Pillow tries to write it as UNDEFINED when saving the EXIF data.
This PR simply handles the IFDRational value when saving UNDEFINED tags.
> Allow writing IFDRational to UNDEFINED tag

- Tests/test_file_gif.py
- src/PIL/GifImagePlugin.py
Resolves #7787
#7568 set identical pixels in subsequent GIF frames to be transparency.
This new issue has found that for disposal 2, when GIF disposes the previous frame and restores it to the background color, filling the identical pixels with transparency results in those pixels being seen as transparent by viewers.
This PR skips the optimisation step of filling identical pixels when the previous frame is restored to the background colour, as it is unnecessary when the frame is being compared with a single color (the background). The filling of pixels that match the previous frame is only an optimisation when it is reducing multiple possible matching colors to one color.
> When saving GIF frame that restores to background color, do not fill identical pixels

- src/PIL/ImageShow.py
Resolves #7789
The user has found that calling using ImageShow from within a .pyw file on Windows causes a console to appear, as a result of calling `os.system` from `Viewer`.
https://github.com/python-pillow/Pillow/blob/6782a07b8e404271dbd2e5ddf5fbb93e575ed2bc/src/PIL/ImageShow.py#L121
The user has suggested calling subprocess with the CREATE_NO_WINDOW flag to fix this.
https://stackoverflow.com/questions/58943289 / https://stackoverflow.com/a/7006424/4093019 agree with this solution.
Because `subprocess.CREATE_NO_WINDOW` only exists on Windows, I've added a dedicated WindowsViewer `show_file()` method for this.
> Use subprocess with CREATE_NO_WINDOW flag in ImageShow WindowsViewer

- Tests/test_file_eps.py
- src/PIL/EpsImagePlugin.py
Helps #7751
In the issue, there is an EPS file that has other image data after the EOF marker. This additional data causes Pillow to fail to open the file, as [one of the lines starts with "%" and is over 255 characters](https://github.com/python-pillow/Pillow/blob/b3a7ae065c4f34b345ecaa3b019bbd1d24e7922c/src/PIL/EpsImagePlugin.py#L282-L289).
This additional image data appears to be a ["preview"](https://en.wikipedia.org/wiki/Encapsulated_PostScript#EPS_previews) - in our test images, it is seen in [illuCS6_preview.eps](https://github.com/python-pillow/Pillow/blob/main/Tests/images/illuCS6_preview.eps), but not [illuCS6_no_preview.eps](https://github.com/python-pillow/Pillow/blob/main/Tests/images/illuCS6_no_preview.eps).
Instead, this PR stops reading the data at the EOF marker.
> Stop reading EPS image at EOF marker

- .github/workflows/test-cygwin.yml
- src/PIL/Image.py
Alternative to #7875
Two Cygwin changes
1. Reverts #7762, where Python was pinned to Python 3.9.16-1
2. Removes the pinning of NumPy from #7403, but also goes further, and just uses the packaged NumPy. NumPy was originally upgraded in [a commit entitled "CI: Try to get Cygwin workflow working."](https://github.com/python-pillow/Pillow/pull/5878/commits/2d6dee1dae7c6f4ce639e1042c05152ef5d14c9e), so if there wasn't another need for this, then perhaps testing the package version is more valuable?
This also decreases the build time from [31m54s](https://github.com/python-pillow/Pillow/actions/runs/8280312072/job/22656563787) to [10m13s.](https://github.com/python-pillow/Pillow/actions/runs/8294540097/job/22699754552)
> Removed Python and NumPy pinning on Cygwin

- Tests/test_file_jpeg2k.py
- src/PIL/Jpeg2KImagePlugin.py
- src/libImaging/Jpeg2KDecode.c
Resolves #7511
This reads palette data from the JPEG2000 pclr box, and assigns it to the image's palette.
I used page 28 of https://web.archive.org/web/20230327234610/https://wiki.opf-labs.org/download/attachments/11337762/15444-1annexi.pdf as a reference.
This is a recreation of https://github.com/python-pillow/Pillow/pull/7867 after I accidentally deleted it.
> Added reading of JPEG2000 palettes

- Tests/test_file_ppm.py
- src/PIL/PpmImagePlugin.py
Helps #7876
Pillow currently raises a ValueError when a value is too large in a P1-P3 PPM image.
https://github.com/python-pillow/Pillow/blob/794a7d691fcc70ffd3f6dad58737cc1ad2b8da26/src/PIL/PpmImagePlugin.py#L273-L275
This adds another ValueError if the value is negative.
> Raise ValueError for negative values when loading P1-P3 PPM images

- Tests/test_file_libtiff.py
- src/PIL/TiffImagePlugin.py
Resolves #7892
The issue has found a TIFF image with tag 255, OSUBFILETYPE, that fails to save using libtiff.
It is described at https://www.awaresystems.be/imaging/tiff/tifftags/subfiletype.html as 'deprecated', and TiffTags.py says that we don't support it.
https://github.com/python-pillow/Pillow/blob/ca973709a079b5152b9670e5cd684003aa71f913/src/PIL/TiffTags.py#L536
So this PR simply removes it when saving using libtiff.
> Remove TIFF tag OSUBFILETYPE when saving using libtiff

- Tests/test_image_quantize.py
- src/PIL/Image.py
- src/libImaging/Quant.c
https://github.com/python-pillow/Pillow/issues/7890#issuecomment-2014337747 found that if `kmeans` if negative, `im.quantize()` can become stuck in an infinite loop.
Investigating, I was able to reproduce this for `MEDIANCUT` and `MAXCOVERAGE`.
This PR updates the docstring to specify that `kmeans` should not be negative, raises a ValueError if `kmeans` is negative, and to be safe, also updates the C code to not use negative kmeans either.
> Raise ValueError if kmeans is negative

- LICENSE
- README.md
- docs/COPYING
- docs/conf.py
- docs/index.rst
- pyproject.toml
- src/PIL/__init__.py
- `s/Jeffrey A. Clark (Alex)/Jeffrey A. Clark/g`. People can figure out that I am Alex.
- We've added "contributors" to Fredrik's copyright statements because it seems appropriate that it be there based on: https://github.com/python-pillow/Pillow/blob/main/CHANGES.rst#02b5-117.
- Fredrik is the PIL author and I am the Pillow author.
- Consistently apply all of the above everywhere.
> Clean up authors and contributors

- Tests/test_file_libtiff.py
- Tests/test_lib_pack.py
- pyproject.toml
- src/PIL/PdfParser.py
- src/PIL/TiffTags.py
- src/PIL/_imaging.pyi
- src/PIL/_imagingcms.pyi
- src/PIL/_imagingft.pyi
- src/PIL/_imagingmath.pyi
- src/PIL/_imagingmorph.pyi
- src/PIL/_webp.pyi
Add PYI to Ruff to run the flake8-pyi linting rules related to type hints and fix the errors:
```
Tests/test_file_libtiff.py:246:14: PYI024 Use `typing.NamedTuple` instead of `collections.namedtuple`
Tests/test_lib_pack.py:18:18: PYI041 Use `float` instead of `int | float`
Tests/test_lib_pack.py:242:18: PYI041 Use `float` instead of `int | float`
src/PIL/PdfParser.py:85:5: PYI024 Use `typing.NamedTuple` instead of `collections.namedtuple`
src/PIL/TarIO.py:61:9: PYI034 `__enter__` methods in classes like `TarIO` usually return `self` at runtime
src/PIL/TiffTags.py:24:15: PYI024 Use `typing.NamedTuple` instead of `collections.namedtuple`
src/PIL/_imaging.pyi:1:1: PYI044 `from __future__ import annotations` has no effect in stub files, since type checkers automatically treat stubs as having …
```
> Type hints: Add PYI (flake8-pyi) to Ruff and fix errors

- .appveyor.yml
Similar to GitHub Actions, we can skip AppVeyor builds when irrelevant files are changed.
For example, we don't need to test Windows for changes that are exclusively docs, or cibuildwheel.
This is based on GHA's `test-windows.yml`:
https://github.com/python-pillow/Pillow/blob/fac81d6228fa649d915edfa0888ed20554f1d38f/.github/workflows/test-windows.yml#L7-L12
Except widened one skip to the whole `.github` directory.
Docs: https://www.appveyor.com/docs/how-to/filtering-commits/#commit-files-github-and-bitbucket-only
> `skip_commits.files` allows skipping AppVeyor build if **all of the files** modified in push’s **head commit** match any of the file matching rules.
I've not tried this out before on AppVeyor. We only have two jobs on AppVeyor, and they run in serial (max parallel runners=1), …
> Skip AppVeyor builds for irrelevant files

- .github/workflows/wheels-dependencies.sh
xorgproto 2024.1 has been released - https://gitlab.freedesktop.org/xorg/proto/xorgproto/-/tags/xorgproto-2024.1
> Updated xorgproto to 2024.1

- Tests/test_image_fromqimage.py
This entire file is skipped if Qt isn't available. This means `teardown_module()` is also skipped. But opening the images isn't skipped because they're not in a function. By moving the image loading to `setup_module()` it will also be skipped when Qt isn't available.
> Use setup_module() to open images so they aren't opened if skipped

- Tests/test_image_convert.py
- src/PIL/Image.py
- src/libImaging/Convert.c
#7209 has started support from RGB to RGBa and La, but doesn't consider transparency.
1. Add support for conversion from RGB to RGBa
When Pillow converts from RGB to RGBA, if there is an `info["transparency"]` entry, the pixels matching that value have their alpha channel set to zero.
This PR adds support for converting from RGB to RGBa in a similar way, except that the matching pixels have all channels set to zero, because the alpha is premultiplied, and zero alpha means every channel should be zero.
https://pillow.readthedocs.io/en/stable/handbook/concepts.html#modes
> Premultiplied alpha is where the values for each other channel have been multiplied by the alpha. For example, an RGBA pixel of (10, 20, 30, 127) would convert to an RGBa pixel of (5, 10, 15, 127). The values of the R, G …
> Improved conversion from RGB to RGBa, LA and La

- Tests/helper.py
- src/libImaging/Convert.c
Instead of Tests/helper.py converting from RGB to I to I;16*,
this adds support for converting directly from RGB to I;16, I;16L and I;16B.
> Added RGB to I;16, I;16L and I;16B conversion

- Tests/test_file_jpeg.py
- src/PIL/JpegPresets.py
https://exiv2.org/tags.html no longer works.
It looks like they're aware of this - https://github.com/Exiv2/exiv2/issues/2875
This fixes the links using the Wayback Machine.
> Corrected exiv2.org links

- CHANGES.rst
- Tests/test_locale.py
- docs/releasenotes/10.3.0.rst
- src/libImaging/JpegDecode.c
Or hedge it a bit?
```diff
-Pillow now has type hints
+Pillow now mostly has type hints
```
---
And fix some typos.
> Add type hints to release notes

- src/PIL/BlpImagePlugin.py
- src/PIL/BmpImagePlugin.py
- src/PIL/DdsImagePlugin.py
- src/PIL/PpmImagePlugin.py
- src/PIL/QoiImagePlugin.py
Helps #7922 by reducing the loading time of [PNG_transparency_demonstration_1.qoi.zip](https://github.com/python-pillow/Pillow/files/14819369/PNG_transparency_demonstration_1.qoi.zip) from 5.15s to 3.89s.
> Improve speed of loading QOI images

- src/PIL/Image.py
> Add type hints to `Image.py`

- Tests/test_imagecms.py
Looking at the duplicate code in https://github.com/python-pillow/Pillow/blob/63cbfcfdea2d163ec93bae8d283fcfe4b73b5dc7/Tests/test_imagecms.py#L517-L531
I think @nulano's intention in #7913 was to test `ImageCms.core.CmsTransform` in `test_transform_typesafety()`
> Corrected ImageCms test

- docs/reference/ImageMath.rst
In the docs for ImageMath, the parameter "environment" was changed to "options". This was updated in the function descriptions but not in their parameters.
> Fix ImageMath documentation parameter names

- .appveyor.yml
It has been [noted](https://github.com/python-pillow/Pillow/pull/7933#issuecomment-2031184944) that #7909 is not causing AppVeyor to skip building as intended for irrelevant files.
Googling, I found https://help.appveyor.com/discussions/problems/31954-skip_commitsfiles-does-not-work-for-files-in-github-folder, which suggests that ".github/**/*" is the pattern to use for skipping files inside the .github directory.
> Updated pattern for skipping builds based on file changes

- docs/handbook/image-file-formats.rst
Resolves #7922
https://github.com/python-pillow/Pillow/issues/7922#issuecomment-2033336635
> That said, Pillow's processing of QOI files in Python, not C, could probably be clarified here: https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#qoi.
> Document that QoiImagePlugin uses Python for decoding

- Tests/test_file_jpeg2k.py
- src/PIL/Jpeg2KImagePlugin.py
- src/libImaging/Jpeg2KDecode.c
Resolves #7945
Requires https://github.com/python-pillow/test-images/pull/4
Pages 187 and 201-204 of https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=5db74700b2b544695273019e6b4820bc9742973a can be used as a reference for the 'colr' box that specifies the colourspace as CMYK.
> Support reading CMYK JPEG2000 images

- src/PIL/BlpImagePlugin.py
- src/PIL/BmpImagePlugin.py
- src/PIL/BufrStubImagePlugin.py
- src/PIL/CurImagePlugin.py
- src/PIL/DcxImagePlugin.py
- src/PIL/DdsImagePlugin.py
- src/PIL/EpsImagePlugin.py
- src/PIL/FliImagePlugin.py
- src/PIL/FpxImagePlugin.py
- src/PIL/FtexImagePlugin.py
- src/PIL/GbrImagePlugin.py
- src/PIL/GifImagePlugin.py
- src/PIL/GribStubImagePlugin.py
- src/PIL/Hdf5StubImagePlugin.py
- src/PIL/IcnsImagePlugin.py
- src/PIL/IcoImagePlugin.py
- src/PIL/Image.py
- src/PIL/Jpeg2KImagePlugin.py
- src/PIL/JpegImagePlugin.py
- src/PIL/MicImagePlugin.py
- src/PIL/PngImagePlugin.py
- src/PIL/PsdImagePlugin.py
- src/PIL/QoiImagePlugin.py
- src/PIL/TiffImagePlugin.py
- src/PIL/WebPImagePlugin.py
- src/PIL/WmfImagePlugin.py
- src/PIL/XpmImagePlugin.py
Fixes #7941 
While the `Image.open` function is currently marked as returning an `Image` object, it does so by calling a factory function from `OPEN`, which is marked as returning an `ImageFile`: https://github.com/python-pillow/Pillow/blob/e8ab5640774716c5486d3cb05167f74f742ad6ef/src/PIL/Image.py#L222-L228
The `accept` function usually returns a `bool`, but I found one case (webp) where it can return a `str` instead to be used as a warning.
> Add type hints for `Image.open`, `Image.init`, and `Image.Image.save`

- RELEASING.md
The "Source and Binary Distributions" section is now only one step (🎉), so we can cleanly inline it into the main instructions.
It makes it easier to follow the release checklist, no need to just to another section and then back.
> Release checklist: inline the 'Source and Binary Distributions' step

- src/PIL/ImageMode.py
This slightly simplifies the code, and adds the benefit of being a `NamedTuple`.
> Make ModeDescriptor a NamedTuple

- Makefile
During the release, the output of `make release-test` includes:
```
Successfully installed pillow-10.4.0.dev0
rm dist/*.egg
rm: dist/*.egg: No such file or directory
make: [release-test] Error 1 (ignored)
rmdir dist
rmdir: dist: No such file or directory
make: [release-test] Error 1 (ignored)
python3 -m pytest -qq
```
Eggs are no longer used: https://peps.python.org/pep-0715/
Let's remove `-rm dist/*.egg`.
> Update `make release-test`: no more eggs

- Makefile
https://github.com/python-pillow/Pillow/pull/7957#issue-2231926580
> During the release, the output of make release-test includes:
> 
>> Successfully installed pillow-10.4.0.dev0
>> rm dist/*.egg
>> rm: dist/*.egg: No such file or directory
>> make: [release-test] Error 1 (ignored)
>> rmdir dist
>> rmdir: dist: No such file or directory
This started happening due to #5896. `python3 setup.py install` creates a dist egg, but `python3 -m pip install .` does not.
#7957 removed `-rm dist/*.egg`.
If there's no dist directory, then there's no need remove it either, so `-rmdir dist` can also be removed.
> dist directory is no longer created

- README.md
- setup.py
Helps #7980
Replace https://pillow.readthedocs.io/en/latest/installation.html with https://pillow.readthedocs.io/en/latest/installation/basic-installation.html after #7832
> Updated installation links

- docs/conf.py
- pyproject.toml
https://github.com/python-pillow/Pillow/blob/0e90c1c9ae308ba768725ec1644189a942f729fb/docs/conf.py#L124-L129
A new version of Sphinx has been [released](https://github.com/sphinx-doc/sphinx/releases), so this can be removed.
> Removed nitpick_ignore by updating Sphinx to 7.3

- Tests/test_file_libtiff.py
- Tests/test_imagesequence.py
- Tests/test_tiff_ifdrational.py
https://github.com/python-pillow/Pillow/blob/db21e7de1cd56ec798f3866ffc132b6f4119b572/Tests/test_tiff_ifdrational.py#L55-L61
This is the wrong way around. `WRITE_LIBTIFF` should be `True` when libtiff is available.
To demonstrate, if I skip [building libtiff on Windows](https://github.com/radarhere/Pillow/commit/c217c6900569baf28206e87430a1b896a12863b1), it [fails](https://github.com/radarhere/Pillow/actions/runs/8673645602). With [this change](https://github.com/radarhere/Pillow/commit/94f7d1ff3915b0160c81159eabcb8021f37e720c), it [passes.](https://github.com/radarhere/Pillow/actions/runs/8673821109)
> Corrected check for libtiff feature

- docs/deprecations.rst
- docs/releasenotes/10.4.0.rst
- docs/releasenotes/index.rst
- src/PIL/TiffImagePlugin.py
libtiff 4.0 was released on 21st December 2011, 12 years ago.
I'm hoping that's long enough to not require a deprecation period for removing support for libtiff < 4.
> Deprecate support for libtiff < 4

- .github/workflows/test.yml
- .github/workflows/wheels.yml
GitHub is migrating `macos-latest` to point to `macos-14` which is (a) M1 and (b) does not have Python 3.8 or 3.9:
* https://github.blog/changelog/2024-04-01-macos-14-sonoma-is-generally-available-and-the-latest-macos-runner-image/
* https://github.com/actions/setup-python/issues/696#issuecomment-1637587760
This can cause failed builds for migrated repos.
At least during this migration, let's explicitly use `macos-13` or `macos-14` instead of `macos-latest`.
> GitHub Actions: use `macos-13` or `macos-14` instead of `macos-latest`

- Tests/test_features.py
- Tests/test_file_png.py
I created https://github.com/python-pillow/docker-images/pull/203 after the release of Fedora 40, but the tests are failing.
This is because Fedora 40 uses [zlib-ng instead of zlib](https://fedoraproject.org/wiki/Releases/40/ChangeSet#Changes/ZlibNGTransition), and [zlib-ng appends '.zlib-ng' to its version string.](https://github.com/zlib-ng/zlib-ng/blob/3f35bfccff2d1dacdfe9844712be1e042d028700/zlib.h.in#L61)
This updates our tests to allow for that suffix.
> Update tests to allow for zlib-ng

- src/libImaging/Convert.c
Discussion at https://github.com/python-pillow/Pillow/commit/fb6b8601721da507f590c85a1b9f426f6c45cca6#r141279400 has revealed that when converting from RGB to an I;16* mode, the result is not going to be larger than 8 bits, and so the code can be simplified.
> Simplified RGB to I;16, I;16L and I;16B conversion

- .readthedocs.yml
- docs/conf.py
- docs/dater.py
This adds a small Sphinx extension to add the date to the titles of the release notes, both on the page and tables of contents.
<table>
<tr>
<th>Before
<th>After
<tr>
<td><img src=https://github.com/python-pillow/Pillow/assets/1324225/20f1e2d1-2105-4c72-bb7a-2c5b6e7eac53>
<td><img src=https://github.com/python-pillow/Pillow/assets/1324225/6313b957-4e23-4fde-9d18-5fd41e0232f6>
</table>
I based this on @jaraco's nifty https://github.com/jaraco/rst.linker, and I've added you as co-author on the commit, hope that's okay?
This PR works by getting the title of pages matching `releasenotes/\d+\.\d+\.\d+"`, then looking up the timestamp from a `git log` call, and then adds "(yyyy-mm-dd)" to the title.
There's some things in rst.linker which make it not suitable to use here, and I think it might …
> Automatically add dates to release notes

- Tests/test_image.py
https://github.com/python-pillow/Pillow/blob/824db7152d1159bf3a895e7699b16ebc77298e77/Tests/helper.py#L374-L375
is not called as a function in
https://github.com/python-pillow/Pillow/blob/824db7152d1159bf3a895e7699b16ebc77298e77/Tests/test_image.py#L1052-L1053
> Corrected big-endian check

- Makefile
Addresses https://github.com/python-pillow/docker-images/pull/207#issuecomment-2081490046 and https://github.com/python-pillow/Pillow/pull/5896#issuecomment-997217443
https://github.com/python-pillow/Pillow/blob/c250a44177ac1e82d300aef702d5c2feef15fd03/Makefile#L4-L8
This removes `python3 setup.py clean`.
From https://github.com/pypa/setuptools/blob/main/setuptools/_distutils/command/clean.py, all it does is remove the 'build_temp' and 'build_base' directories. If I print those variables on my local machine, they are 'build/temp.macosx-14.0-arm64-cpython-38' and 'build', and we're already removing the 'build' directory ourselves.
> Removed direct invocation of setup.py

- Tests/test_file_eps.py
- Tests/test_image_access.py
- selftest.py
- src/PIL/IptcImagePlugin.py
- src/PIL/PdfParser.py
Fixes the failures in https://github.com/python-pillow/Pillow/pull/8044
Converts several percent format strings to f-strings.
There is also a percent format inside a multiline string - I think the neatest solution is just to break the multiline string.
> Do not use percent format in strings

- Tests/helper.py
- Tests/test_image.py
- Tests/test_image_access.py
Now that `Image.MODES` is populated with all non-deprecated modes, it seems simpler to me to remove Tests/helper.py's `modes`.
Alternatively, this can be closed, and `modes` can live on in helper.py until the deprecated modes are removed completely in Pillow 12.
> Removed helper.py modes

- src/_imagingcms.c
- src/display.c
- src/libImaging/Dib.c
- src/libImaging/TiffDecode.c
MinGW has started failing in main - https://github.com/python-pillow/Pillow/actions/runs/9108593264/job/25039692144
> Fix type errors

- src/libImaging/Dib.c
- src/libImaging/TiffDecode.c
After merging #8015, the Lint job is [failing](https://github.com/python-pillow/Pillow/actions/runs/9145658534/job/25144864620), because its run of pre-commit did not include #8064
> Lint fixes

- setup.py
Our Python 3.13 jobs have started failing in GitHub Actions - https://github.com/python-pillow/Pillow/actions/runs/9032048835/job/24819485997#step:9:46
```pytb
File "/private/var/folders/3m/p59k4qdj0f17st0gn2cmj3640000gn/T/pip-build-env-v125k6ei/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 311, in run_setup
exec(code, locals())
~~~~^^^^^^^^^^^^^^^^
File "<string>", line 33, in <module>
File "<string>", line 27, in get_version
KeyError: '__version__'
```
This is referring to https://github.com/python-pillow/Pillow/blob/0cad346fc960bc07cde9d1d9135421978e2f28e8/setup.py#L23-L27
Python 3.13 is failing to populate the local variables from `exec()` - https://github.com/python/cpython/issues/118888
We have various options at this point.
1. Presuming the bug report is …
> Parse _version contents instead of using exec()

- src/PIL/ImageFont.py
I see no reason to mention `mode` in the following docstring
https://github.com/python-pillow/Pillow/blob/3c2d36e11379a69d6bcff0ed9a02cf54deda8b19/src/PIL/ImageFont.py#L156-L172
> Removed documentation of unused argument

- src/PIL/PngImagePlugin.py
Before line 1297 `mode` is the image mode and a string, after this line `mode` is the rawmode depth and type bytes. This change uses a different variable name for the bytes.
> Don't reuse variable name

- Tests/test_imagedraw.py
- docs/reference/ImageDraw.rst
- docs/releasenotes/10.4.0.rst
- src/PIL/ImageDraw.py
Resolves #8083
Implements the ImageDraw.circle feature as described and desired in the issue
> Add function and documentation to draw circle

- src/PIL/ImageCms.py
`colorTemp` is hinted as a float,
https://github.com/python-pillow/Pillow/blob/4f4b0bc74816ac7ea7a47127905a5cba3f6067b8/src/PIL/ImageCms.py#L756-L758
but described in the docstring as an integer.
https://github.com/python-pillow/Pillow/blob/4f4b0bc74816ac7ea7a47127905a5cba3f6067b8/src/PIL/ImageCms.py#L780
I've updated the docstring to say 'float' instead. 
I've also changed the default from -1 to 0. This has [no effect](https://github.com/python-pillow/Pillow/blob/4f4b0bc74816ac7ea7a47127905a5cba3f6067b8/src/_imagingcms.c#L549-L559), it just seems simpler to me. It also matches the default in the C layer.
> Updated ImageCms.createProfile colorTemp default and docstring

- src/PIL/ImageCms.py
- src/PIL/_imagingcms.pyi
`littlecms_version` may be none, as seen here.
https://github.com/python-pillow/Pillow/blob/eeb1eeab209ac395427d269a7aecfd76d525bdc4/src/_imagingcms.c#L1513
> Corrected type hint

- src/PIL/Image.py
- src/PIL/ImageDraw.py
- src/PIL/PyAccess.py
Since there are parts of #8032 that I still have questions about, this is a PR with the parts that have my approval, as a partial merge if you will.
> Added type hints

- docs/Makefile
* Sphinx 7.3.0 (released Apr 16, 2024) introduced long option names for `sphinx-build`:
* https://www.sphinx-doc.org/en/master/changes.html#release-7-3-0-released-apr-16-2024
* The short ones are a bit cryptic, let's use the more descriptive long ones in the `Makefile`
> Use Sphinx long options in `Makefile`

- depends/install_imagequant.sh
- docs/installation/building-from-source.rst
libimagequant 4.3.1 has been released - https://github.com/ImageOptim/libimagequant/releases/tag/4.3.1
> Updated libimagequant to 4.3.1

- src/PIL/Image.py
- src/_imaging.c
There is no 'transform' or 'transform1' method, so let's rename the function to be clear about that.
> Renamed C transform2 to transform

- Tests/test_features.py
The docker-images alpine build has started failing - https://github.com/python-pillow/docker-images/actions/runs/9444260430/job/26009462397
> FAILED Tests/test_features.py::test_version - AssertionError: assert ('4.6.0t' is None or None)
This is because the libtiff version on alpine has been changed to 4.6.0t - https://git.alpinelinux.org/aports/commit/?id=7f743c559b40c7e47561f032b2cae50681e362fc
So, like #8009, let's update the tests to allow for the suffix.
> Accept 't' suffix for libtiff version

- Tests/test_imagedraw.py
- docs/deprecations.rst
- docs/releasenotes/10.4.0.rst
- src/PIL/ImageDraw.py
`ImageDraw.getdraw()` has a `hints` argument. Its purpose is to indicate whether or not `_imagingagg` should be used instead of `ImageDraw2`.
However, `_imagingagg` doesn't exist, so I suggest deprecating the `hints` argument.
> Deprecate ImageDraw.getdraw hints parameter

- .appveyor.yml
Ghostscript is not currently detected on AppVeyor - https://ci.appveyor.com/project/Python-pillow/pillow/builds/50010618/job/q3r9wd89bu5xt9l5?fullLog=true#L3964
This fixes it by correcting the Ghostscript path.
> Corrected AppVeyor Ghostscript path

- .github/workflows/macos-install.sh
The macOS 13 GitHub Actions jobs have started failing - https://github.com/python-pillow/Pillow/actions/runs/9524124798/job/26256604583#step:7:150
> ==> Pouring libraqm--0.10.1.ventura.bottle.tar.gz
> 🍺  /usr/local/Cellar/libraqm/0.10.1: 12 files, 104KB
> ==> Caveats
> ==> jpeg
> jpeg is keg-only, which means it was not symlinked into /usr/local,
> because it conflicts with `jpeg-turbo`.
> 
> If you need to have jpeg first in your PATH, run:
>   echo 'export PATH="/usr/local/opt/jpeg/bin:$PATH"' >> /Users/runner/.bash_profile
> 
> For compilers to find jpeg you may need to set:
>   export LDFLAGS="-L/usr/local/opt/jpeg/lib"
>   export CPPFLAGS="-I/usr/local/opt/jpeg/include"
> 
> For pkg-config to find jpeg you may need to set:
>   export …
> Ignore brew dependencies for libraqm on macOS 13

- Tests/test_imagefont.py
- docs/releasenotes/10.4.0.rst
- src/PIL/ImageFont.py
For `ImageFont.freetype`:
* Add support for searching fonts in the user data directory indicated by `XDG_DATA_HOME` or its default, before searching in system-wide directories.
* Update the default value for `XDG_DATA_DIRS` to include the directory for system-local fonts in `/usr/local/share/fonts`.
These changes allow searching for both user-installed fonts, and fonts that aren't managed by the system package manager, such as when Microsoft fonts are installed by `mscorefonts-installer` into `/usr/local`.
Reference: [version 0.8 of the freedesktop base directory spec](https://specifications.freedesktop.org/basedir-spec/0.8/)
> Improve `ImageFont.freetype` support for XDG directories on Linux

- Tests/test_imageqt.py
- src/PIL/ImageQt.py
https://github.com/python-pillow/Pillow/blob/4b258be3bbedbdd54ef65140a14982b086d10c7b/src/PIL/ImageQt.py#L155
https://github.com/python-pillow/Pillow/blob/4b258be3bbedbdd54ef65140a14982b086d10c7b/Tests/test_imageqt.py#L46-L48
Support for Qt 5 was [removed in Pillow 10.0.0](https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html#pyqt5-and-pyside2), so this code can be simplified.
> Removed support for Qt 5

- Tests/test_image_putpalette.py
- src/PIL/DdsImagePlugin.py
- src/PIL/GifImagePlugin.py
- src/PIL/Image.py
- src/_imaging.c
Helps #7965
At the moment, only modes that start with 'RGBA' can be unpacked to RGBA palettes. This does not allow for rawmodes such as 'ARGB'.
> Support unpacking more rawmodes to RGBA palettes

- Tests/test_imagedraw2.py
- src/PIL/ImageDraw2.py
When creating an `ImageDraw2.Draw` instance, `image` can be either an image or a mode string.
https://github.com/python-pillow/Pillow/blob/920698eea7693012d945300b2b87a16ae8f0706a/src/PIL/ImageDraw2.py#L59-L62
If you provide a mode string without a size, you get an error saying that size must be a list or a tuple.
```pytb
>>> from PIL import ImageDraw2
>>> ImageDraw2.Draw("RGB", size=None)
File "PIL/ImageDraw2.py", line 61, in __init__
image = Image.new(image, size, color)
File "PIL/Image.py", line 3061, in new
_check_size(size)
File "PIL/Image.py", line 3029, in _check_size
raise ValueError(msg)
ValueError: Size must be a list or tuple
```
Except, if you provided an image as the first argument, then `size` can be …
> Clarify ImageDraw2 error message when size is missing

- src/PIL/EpsImagePlugin.py
This is the only return statement in this function, and it appears to be unnecessary since breaking from the loop at this location accomplishes the same thing, and matches what the rest of this loop does.
The only change is that `check_required_header_comments()` is called at the end of the function. This was being skipped before due to the early return, but it will be called now that it's just breaking from the loop.
Before 8f75cc2bbf9cb274a7167f895ab0d437ddca1c07 this return was inside a nested loop, so breaking wouldn't have worked, but now it does. Also, `check_required_header_comments()` didn't exist at that time, so the early return wasn't skipping anything.
> Prevent extra EPS header validations

- Tests/test_file_tiff.py
- src/PIL/TiffImagePlugin.py
Resolves #7940
The issue contains an image where tag 33723 is specified as LONG, when it should be BYTE or UNDEFINED according to https://www.awaresystems.be/imaging/tiff/tifftags/iptc.html.
This changes Pillow to not preserve the tag automatically if it has the wrong type.
> Only preserve TIFF IPTC_NAA_CHUNK tag if type is BYTE or UNDEFINED

- src/display.c
https://github.com/python-pillow/Pillow/actions/runs/9108593264/job/25039692144#step:5:225
>   src/display.c: In function 'windowCallback':
>   src/display.c:508:20: warning: variable 'current_threadstate' set but not used [-Wunused-but-set-variable]
>     508 |     PyThreadState *current_threadstate;
>         |                    ^~~~~~~~~~~~~~~~~~~
Looking at [`windowCallback()`](https://github.com/python-pillow/Pillow/blob/0da83a1164c6663075bd313d258e671de30710b5/src/display.c#L503), I think this should be used at the end of the function to restore the original thread state.
> Restore original thread state

- Tests/test_file_psd.py
- src/PIL/PsdImagePlugin.py
When opening a PSD image, this PR skips reading and parsing the PSD layers until the user calls `im.layers`, `im.n_frames` or `im.is_animated`.
This will improve performance, and also allow users who just want to `open()` an image without seeking to workaround any errors that might be raised when parsing layers, such as in #8034
> Do not read layers immediately when opening PSD images

- src/PIL/Image.py
In `im.rotate()`, there is
https://github.com/python-pillow/Pillow/blob/5bacce9dc2c0db25822bbddadcaa07496a9ffe1b/src/PIL/Image.py#L2375-L2379
Looking through the code after that, there is no reason why they can't be floats - the numbers are simply combined with other floats.
https://github.com/python-pillow/Pillow/blob/5bacce9dc2c0db25822bbddadcaa07496a9ffe1b/src/PIL/Image.py#L2381-L2399
This also allows the rotation center to be the exact center of an image with odd dimensions - although that also sound like a good argument why the user might want to pass in floats as the `center`, so I've updated the type hint accordingly.
> Allow float center for rotate operations to resolve FIXME

- Tests/test_imagefont.py
- src/PIL/ImageFont.py
- src/PIL/_imagingft.pyi
- src/_imagingft.c
Currently, `FreeTypeFont` doesn't support bytes, while the less-used `ImageFont` does.
```pycon
>>> from PIL import ImageFont
>>> font = ImageFont.load_default()
>>> font
<PIL.ImageFont.FreeTypeFont object at 0x102bbac10>
>>> font.getlength("test")
16.0
>>> font.getlength(b"test")
File "PIL/ImageFont.py", line 353, in getlength
return self.font.getlength(text, mode, direction, features, language) / 64
TypeError: expected string
>>> from PIL import _util
>>> ImageFont.core = _util.DeferredError(ImportError)
>>> font = ImageFont.load_default()
>>> font
<PIL.ImageFont.ImageFont object at 0x102d23910>
>>> font.getlength("test")
24
>>> font.getlength(b"test")
24
```
This adds byte support to FreeTypeFont.
> Added byte support to FreeTypeFont

- Tests/test_file_png.py
- src/PIL/PngImagePlugin.py
Resolves #8081
The issue points out that `_write_multiple_frames` converts images to `rawmode`
https://github.com/python-pillow/Pillow/blob/bbe1effd63149eb3d43d59efb5fe2659f93700d0/src/PIL/PngImagePlugin.py#L1125
where `rawmode` is
https://github.com/python-pillow/Pillow/blob/bbe1effd63149eb3d43d59efb5fe2659f93700d0/src/PIL/PngImagePlugin.py#L1297
https://github.com/python-pillow/Pillow/blob/bbe1effd63149eb3d43d59efb5fe2659f93700d0/src/PIL/PngImagePlugin.py#L1052-L1069
and so may not always be a Pillow image mode.
> When saving multiple PNG frames, convert to mode rather than raw mode

- Tests/test_file_jpeg2k.py
I was just looking at
https://github.com/python-pillow/Pillow/blob/e7c1da3cc8a26b821e0a4ec2d4651d62271f00c5/Tests/test_file_jpeg2k.py#L338-L342
which triggers a SyntaxError
https://github.com/python-pillow/Pillow/blob/e7c1da3cc8a26b821e0a4ec2d4651d62271f00c5/src/PIL/Jpeg2KImagePlugin.py#L205-L207
and wondering why that didn't [lead to an UnidentifiedImageError.](https://github.com/python-pillow/Pillow/blob/e7c1da3cc8a26b821e0a4ec2d4651d62271f00c5/src/PIL/Image.py#L3463-L3504)
The answer was that it did, but `UnidentifiedImageError` inherits from `OSError`, so the test passed without a problem.
https://github.com/python-pillow/Pillow/blob/e7c1da3cc8a26b821e0a4ec2d4651d62271f00c5/src/PIL/__init__.py#L77
This PR just updated the test to check for `UnidentifiedImageError`, to be clearer.
> Use more specific error

- Tests/test_image.py
- src/PIL/Image.py
- src/PIL/JpegImagePlugin.py
Last year, we received a report of a JPEG image where [XMP data was zero-padded at the end](https://github.com/python-pillow/Pillow/issues/7273). I created a fix for that [by adjusting JpegImagePlugin.](https://github.com/python-pillow/Pillow/pull/7274/commits/2488167f33b7e357315c7052273b973fe2cad8e8)
Now https://github.com/python-pillow/Pillow/pull/8069#issuecomment-2186382029 reports that XMP data might also be zero-padded for another format.
So this PR removes zero-byte end padding from XMP data for all formats, not just JPEG.
> Remove zero-byte end padding when parsing any XMP data

- Tests/test_imageops.py
- src/PIL/ImageOps.py
#8069 changed `ImageOps.exif_transpose()` so that when updating a PNG image's `im.info["XML:com.adobe.xmp"]`, it would update the newly added `im.info["xmp"]` as well.
However, https://github.com/python-pillow/Pillow/pull/8171#issuecomment-2191625500 has pointed out that our code shouldn't presume that the user didn't manually set `im.info["XML:com.adobe.xmp"]` themselves, in which case `im.info["xmp"]` might be absent.
> Do not presume "xmp" info simply because "XML:com.adobe.xmp" info exists

- Tests/test_image.py
- docs/reference/Image.rst
- src/PIL/Image.py
> Added Image.WARN_POSSIBLE_FORMATS

- Tests/test_imagecms.py
- docs/deprecations.rst
- docs/releasenotes/10.4.0.rst
- src/PIL/ImageCms.py
- src/_imagingcms.c
Resolves #8007
https://pillow.readthedocs.io/en/stable/reference/ImageCms.html#PIL.ImageCms.buildTransform and https://pillow.readthedocs.io/en/stable/reference/ImageCms.html#PIL.ImageCms.buildProofTransform describe `inMode` and `outMode` as
> String, as a valid PIL mode that the appropriate profile also supports
However, "RGBA;16B", "L;16", "L;16B", "YCCA" and "YCC" are [modes that can be interpreted](https://github.com/python-pillow/Pillow/blob/9b1390792cb941816e59eb9c1ba009f30787b388/src/_imagingcms.c#L215), and there is a [default case](https://github.com/python-pillow/Pillow/blob/9b1390792cb941816e59eb9c1ba009f30787b388/src/_imagingcms.c#L245-L246) if the mode is not recognised.
This deprecates modes that are not Pillow modes, and also deprecates the default value if the mode is not …
> Deprecate non-image ImageCms modes

- docs/conf.py
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-28219
> NOTICE: Transition to the all-new CVE website at [WWW.CVE.ORG](https://www.cve.org/) and [CVE Record Format JSON](https://www.cve.org/Media/News/item/blog/2022/10/06/CVE-Records-Are-Now-Displayed) are underway.
This PR updates the URL for CVEs in our documentation.
> Updated CVE URL

- src/PIL/_typing.py
Fixes an incompatibility encountered in the wild when importing `Pillow==10.4.0` with `numpy==1.20.x` installed.
> Fix incompatibility with NumPy 1.20 

- docs/installation/newer-versions.csv
- docs/releasenotes/11.0.0.rst
- pyproject.toml
- setup.py
- tox.ini
Python 3.13.0 final is planned for 2024-10-01:
* https://peps.python.org/pep-0719/
Pillow 11.0.0 is planned for 2024-10-15 and will officially support Python 3.13: 
* https://github.com/python-pillow/Pillow/milestone/48
We've already released wheels for the beta, but this adds official support and the Trove classifier.
> Add support for Python 3.13

- Tests/test_image_resize.py
- Tests/test_numpy.py
- src/PIL/Image.py
> Allow size argument to resize() to be a NumPy array

- .github/workflows/wheels.yml
When [building wheels for Pillow 10.4.0](https://github.com/python-pillow/Pillow/actions/runs/9738988796), the longest job was [aarch64 pp310 manylinux_2_28](https://github.com/python-pillow/Pillow/actions/runs/9738988796/job/26873432211) at 2h 16m.
However, since there were 27 wheel building jobs, and we are limited to 20 concurrent runners, it takes longer than any single job. With the recent removal of Python 3.8, things are a bit better, but with [free-threaded wheels](https://github.com/python-pillow/Pillow/issues/8199) on the horizon, there will be more again.
It is the dependency installation that takes most of the time in the jobs, so this PR suggests grouping the aarch64 CPythons together - rather than a job per CPython version, have one job for 3.9, 3.10 and 3.11, and one job …
> Group aarch64 wheel jobs

- Tests/test_file_gif.py
- Tests/test_file_libtiff.py
- Tests/test_file_pdf.py
- Tests/test_file_tiff.py
- Tests/test_image.py
- Tests/test_imagegrab.py
- pyproject.toml
- src/PIL/Image.py
- tox.ini
After the changes in this PR, there are only half a dozen files left in Tests that do not pass mypy. So I've updated tox to also check Tests, and excluded those left with errors.
By running mypy over Tests, it better ensures that Pillow's main type hints are correct, as the test suite provides example input and handles output.
> Check test type hints

- Tests/test_file_pdf.py
The combination of https://github.com/python-pillow/Pillow/pull/8207 and https://github.com/python-pillow/Pillow/pull/8208 is causing a failure in main - https://github.com/python-pillow/Pillow/actions/runs/9819025710
> Added type hint

- .ci/install.sh
- .github/workflows/test.yml
For https://github.com/python-pillow/Pillow/issues/8199.
Currently GitHub's `actions/setup-python` does not yet support free-threading but it has been requested: https://github.com/actions/setup-python/issues/771 (give it a 👍)
However, it is available via `deadsnakes/action`:
* https://github.com/deadsnakes/action
* https://dev.to/hugovk/help-us-test-free-threaded-python-without-the-gil-1hgf
This PR adds an Ubuntu `3.13-dev` job to the matrix, to run tests with a free-threaded build.
The build actually _runs_ with the GIL enabled, we'll need to explicitly indicate in the extensions that they should run with it disabled. This will be changed in a follow-up PR.
We can check if Python is built with free-threaded mode by looking for "experimental free-threading build" in `python --version …
> Test 3.13 free-threaded build on CI

- .github/workflows/wheels-test.sh
- .github/workflows/wheels.yml
Helps #8199
Does not build free-threaded wheels for aarch64. I guess that isn't supported yet by cibuildwheel.
> Build free-threaded wheels

- src/_imaging.c
- src/_imagingcms.c
- src/_imagingft.c
- src/_imagingmath.c
- src/_imagingmorph.c
- src/_imagingtk.c
- src/_webp.c
- src/encode.c
- src/path.c
- src/thirdparty/pythoncapi_compat.h
For https://github.com/python-pillow/Pillow/issues/8199.
Make a start on making Pillow's code ready for free-threading ([PEP 703](https://peps.python.org/pep-0703/)).
This is some of the low-hanging fruit from https://docs.python.org/3.13/howto/free-threading-extensions.html.
* Declare extension modules can support running with the GIL disabled. We use [single-phase initialisation](https://docs.python.org/3.13/howto/free-threading-extensions.html#single-phase-initialization).
* Replace functions that return borrowed references [with strong references](https://docs.python.org/3.13/howto/free-threading-extensions.html#borrowed-references), using https://github.com/python/pythoncapi-compat
* Plus from @lysnikolaou: don't use `PyList_GetItemRef` immediately after `PyList_New`
> Move away from APIs that use borrowed references under the free-threaded build

- .github/workflows/cifuzz.yml
While we have [dropped support for Python 3.8](https://github.com/python-pillow/Pillow/pull/8183), the[ cifuzz base image is still using it](https://github.com/google/oss-fuzz/pull/11401#issuecomment-1872050104).
Until https://github.com/google/oss-fuzz/issues/11419 is resolved by upgrading the Python version, this skips the cifuzz job.
> Temporarily disable cifuzz

- Tests/test_file_container.py
- pyproject.toml
- src/PIL/ContainerIO.py
- src/PIL/TarIO.py
There is a mypy error on Tests/test_file_tar.py
```
Tests/test_file_tar.py:25: error: Argument 1 to "open" has incompatible type "TarIO"; expected "Union[Union[str, bytes, PathLike[str], PathLike[bytes]], IO[bytes]]" 
[arg-type]
with Image.open(tar) as im:
^~~
Found 1 error in 1 file (checked 1 source file)
```
https://github.com/python-pillow/Pillow/blob/86f4cfbbf1bbec68cc2011ee5e368e9c7b06bdbf/src/PIL/Image.py#L3357-L3358
doesn't accept `TarIO`, which subclasses from `ContainerIO`
https://github.com/python-pillow/Pillow/blob/86f4cfbbf1bbec68cc2011ee5e368e9c7b06bdbf/src/PIL/ContainerIO.py#L22
I don't think there's any reason why `ContainerIO` shouldn't subclass `IO` - it is essentially performing that role - so I've made that change here.
> Changed ContainerIO to subclass IO

- .github/workflows/wheels.yml
Related to #8199.
In order for this to work we're going to need a secret named `PILLOW_NIGHTLY_UPLOAD_TOKEN`. @hugovk Did you already create it? If so, what's its name?
> Upload wheels to scientific-python-nightly-wheels index

- Tests/test_imagemath_lambda_eval.py
- Tests/test_imagemath_unsafe_eval.py
- docs/deprecations.rst
- docs/reference/ImageMath.rst
- docs/releasenotes/11.0.0.rst
- src/PIL/ImageMath.py
Suggested in https://github.com/python-pillow/Pillow/pull/8227#discussion_r1677553779
Deprecate ImageMath lambda_eval and unsafe_eval `options` argument, in favour of providing arguments through individual keywords instead.
> Deprecate ImageMath lambda_eval and unsafe_eval options argument

- .github/workflows/wheels.yml
Skip two more wheel builds on schedule, and only run the publish jobs in the main repository.
Fixes #8253.
> Do not run scheduled wheel jobs on forks

- src/PIL/ImageDraw.py
https://github.com/python-pillow/Pillow/blob/fddc902c35ccea9a011f44d00404ec8d6f7a9f09/src/PIL/ImageDraw.py#L626
The third argument of this internal function has been unused since https://github.com/python-pillow/Pillow/pull/4930/files#diff-f5af1d5d4c3d64d24c36722596ab3b4e7787513249be6a2a297f9603da7f088aL356
> Removed unused argument

- Tests/test_file_jpeg.py
- src/PIL/JpegPresets.py
Reverts python-pillow/Pillow#7856.
https://exiv2.org/ is now back in action: https://github.com/Exiv2/exiv2/issues/2875#issuecomment-2248567366
> Restore exiv2.org links

- Tests/test_file_jpeg.py
- docs/deprecations.rst
- docs/releasenotes/11.0.0.rst
- src/PIL/JpegImagePlugin.py
These dictionaries have been unused since PIL, so let's deprecate them.
https://github.com/python-pillow/Pillow/blob/4df4df2a18ded44811be786703a43c3460cb3bc9/src/PIL/JpegImagePlugin.py#L349-L350
> Deprecate JpegImageFile huffman_ac and huffman_dc

- Tests/test_imagedraw2.py
- src/PIL/ImageDraw2.py
Some improvements to ImageDraw2.
1. You might think that ImageDraw2 `ellipse()` only requires `xy`,
https://github.com/python-pillow/Pillow/blob/8f62fbdf440b99cc087c19b58725ff266b76758d/src/PIL/ImageDraw2.py#L132
but that is not the case.
```python
from PIL import Image, ImageDraw2
im = Image.new("RGB", (100, 100))
d = ImageDraw2.Draw(im)
d.ellipse((0, 0, 100, 100))
```
gives
```pytb
File "demo.py", line 4, in <module>
d.ellipse((0, 0, 100, 100))
File "PIL/ImageDraw2.py", line 138, in ellipse
self.render("ellipse", xy, *options)
TypeError: render() missing 1 required positional argument: 'pen'
```
So I've made a change to add `pen` as a required argument to `arc()` and other methods.
Some of our test code does pass through `pen` as `None`, and uses the …
> Improve ImageDraw2 shape methods

- src/_imagingft.c
https://github.com/python-pillow/Pillow/actions/runs/10280498668/job/28447977337#step:11:240
>   src/_imagingft.c:1246:23: warning: comparison of integers of different signs: 'int' and 'FT_UInt' (aka 'unsigned int') [-Wsign-compare]
>       for (int i = 0; i < num_namedstyles; i++) {
>                       ~ ^ ~~~~~~~~~~~~~~~
>   1 warning generated.
>   src/_imagingft.c:1246:23: warning: comparison of integers of different signs: 'int' and 'FT_UInt' (aka 'unsigned int') [-Wsign-compare]
>       for (int i = 0; i < num_namedstyles; i++) {
>                       ~ ^ ~~~~~~~~~~~~~~~
> Fixed sign comparison warning

- src/libImaging/Quant.c
`root` is not currently defined here.
https://github.com/python-pillow/Pillow/blob/f2469cb1bf8edd35b89e06b0bcab2dd993038f2d/src/libImaging/Quant.c#L1041-L1046
> Fix undefined variable

- src/PIL/TiffImagePlugin.py
This is a sequel of #3817
Unpacker for this mode [is already here](https://github.com/python-pillow/Pillow/blob/2973b041c76482da213fd93e151c542577178fe3/src/libImaging/Unpack.c#L1761).
> Add missing TIFF CMYK;16B reader

- src/PIL/TiffImagePlugin.py
Move from the legacy `tag` to the more recent  `tag_v2` in a logging statement in TiffImagePlugin.
> Log value from tag_v2 instead of tag

- .pre-commit-config.yaml
- Tests/test_file_jpeg.py
- Tests/test_file_jpeg2k.py
- Tests/test_imagechops.py
- Tests/test_imagemorph.py
- Tests/test_tiff_ifdrational.py
- pyproject.toml
Expand from PT006 to all of PT:
https://docs.astral.sh/ruff/rules/#flake8-pytest-style-pt
Fix warnings for PT001, PT014 and PT018.
Exclude these which have warnings:
*  PT007 pytest-parametrize-values-wrong-type
*  PT011 pytest-raises-too-broad
*  PT012 pytest-raises-with-multiple-statements
*  PT016 pytest-fail-without-message
*  PT017 pytest-assert-in-except
I'm fine if someone wants to tackle those in another PR.
> Lint: run more flake8-pytest-style

- .github/workflows/macos-install.sh
Our macOS 13 job has started failing in main - https://github.com/python-pillow/Pillow/actions/runs/10451246000/job/28937272389
It is trying to install Python 3.12, when there is already a copy of Python present, leading to an error.
The new Python dependency is not for any packages we have requested though, but instead for gradle and maven, when brew tries to update versions already installed.
Perhaps the simplest solution is just to uninstall gradle and maven.
> Uninstall gradle and maven on macOS 13

- Tests/test_file_iptc.py
- src/PIL/IptcImagePlugin.py
Move from the legacy `tag` to the more recent  `tag_v2` when accessing TIFF data in IptcImagePlugin.
I've also added a test, that passes with or without this change.
> Get IPTC info from tag_v2

- Tests/test_file_webp_metadata.py
- Tests/test_image.py
https://github.com/python-pillow/Pillow/actions/runs/10500106794/job/29087976482#step:6:5386
> Tests/test_file_webp_metadata.py::test_getxmp
> Tests/test_image.py::TestImage::test_empty_xmp
>   /vpy3/lib64/python3.12/site-packages/PIL/Image.py:1491: UserWarning: XMP data cannot be read without defusedxml dependency
>     warnings.warn("XMP data cannot be read without defusedxml dependency")
> Catch defusedxml warnings

- Tests/test_image_array.py
- src/PIL/Image.py
If an error is raised when converting an image to a NumPy array, NumPy < 1.23 doesn't raise an error. So #6594 added a warning for that scenario.
https://github.com/python-pillow/Pillow/blob/d6cfebd016db25549d05a9c5caa2ef3b53cff5c5/src/PIL/Image.py#L742-L743
NumPy < 1.23 is [EOL](https://endoflife.date/numpy), so this explicit warning can be removed.
A caveat to this is that [Ubuntu 22.04 still has NumPy 1.21 packaged](https://packages.ubuntu.com/jammy/python3-numpy). However, that version carries its own warning - https://github.com/python-pillow/Pillow/actions/runs/10500106794/job/29087976733#step:6:5394
>   /Pillow/Tests/test_image_array.py:51: DeprecationWarning: An exception was ignored while fetching the attribute `__array_interface__` from an object of type 'JpegImageFile'.  With …
> Remove warning if NumPy failed to raise an error during conversion

- Tests/test_file_webp.py
- src/_webp.c
Resolves #8321
There is a limit on the size of WebP images.
https://developers.google.com/speed/webp/faq
> The maximum pixel dimensions of a WebP image is 16383 x 16383.
When that limit is hit, this PR changes the error message from
"encoding error 5"
to
"encoding error 5: Image size exceeds WebP limit"
> Updated error message when saving WebP with invalid width or height

- .ci/install.sh
- .github/workflows/test-windows.yml
- .github/workflows/test.yml
- .github/workflows/wheels.yml
PyPy 7.3.17 is out, including PyPy3.10 and dropping PyPy3.9:
> The keen-eyed will have noticed no mention of Python version 3.9 in the releases above. Typically we will maintain only one version of Python3, but due to PyPy3.9 support on conda-forge we maintained multiple versions from the first release of PyPy3.10 in PyPy v7.3.12 (Dec 2022). Conda-forge is [sunsetting its PyPy support](https://pypy.org/posts/2024/08/conda-forge-proposes-dropping-support-for-pypy.html), which means we can drop PyPy3.9.
https://pypy.org/posts/2024/08/pypy-v7317-release.html#pypy-versions-and-speed-pypy-org
> Drop support for EOL PyPy3.9

- winbuild/build_prepare.py
FreeType 2.13.3 has been released - https://freetype.org/
> Updated freetype to 2.13.3

- depends/install_imagequant.sh
- docs/installation/building-from-source.rst
libimagequant 4.3.3 has been released - https://github.com/ImageOptim/libimagequant/releases/tag/4.3.3
> Updated libimagequant to 4.3.3

- Tests/test_file_ico.py
- src/PIL/IcoImagePlugin.py
Investigating https://github.com/python-pillow/Pillow/issues/6507#issuecomment-2199451130, there is an ICO image with a truncated transparency mask.
This PR allows `ImageFile.LOAD_TRUNCATED_IMAGES` to skip the mask and keep the rest of the image.
> Skip truncated ICO mask if LOAD_TRUNCATED_IMAGES is enabled

- Tests/test_file_jpeg2k.py
- src/PIL/Jpeg2KImagePlugin.py
Resolves #8255
Page 7 of https://cdn.standards.iteh.ai/samples/36628/10393e6ddb5c4dbc9513ae89230d97f9/ISO-IEC-15444-1-2000-Cor-2-2002.pdf explains that `npc` is
> Number of components created by the application of the palette
When there are four components, this PR changes the palette to be RGBA.
Requires a test image from https://github.com/python-pillow/test-images/pull/5
> Support JPEG2000 RGBA palettes

- src/PIL/ImageFont.py
Currently, `font` is an optional parameter for `FreeTypeFont` and `truetype()`.
https://github.com/python-pillow/Pillow/blob/6dd4b3c826512b6e50f7343951bcb3650087119b/src/PIL/ImageFont.py#L198-L211
https://github.com/python-pillow/Pillow/blob/6dd4b3c826512b6e50f7343951bcb3650087119b/src/PIL/ImageFont.py#L758-L764
However, if it is `None`, then an error is raised.
```pytb
>>> from PIL import ImageFont
>>> ImageFont.FreeTypeFont()
File "PIL/ImageFont.py", line 261, in __init__
load_from_bytes(font)
File "PIL/ImageFont.py", line 240, in load_from_bytes
self.font_bytes = f.read()
AttributeError: 'NoneType' object has no attribute 'read'
```
```pytb
>>> from PIL import ImageFont
>>> ImageFont.truetype()
Traceback (most …
```
> Require font parameter in FreeTypeFont and truetype()

- Tests/test_file_jpeg.py
- src/PIL/JpegImagePlugin.py
Resolves #8283, allowing XMP data to be saved to JPEG files, either by
```python
im.save("out.jpg", xmp=b"test")
```
or
```python
im.info["xmp"] = b"test"
im.save("out.jpg")
```
> Added writing XMP bytes to JPEG

- Tests/oss-fuzz/python.supp
While we have [dropped support for Python 3.8](https://github.com/python-pillow/Pillow/pull/8183), the[ cifuzz base image is still using it](https://github.com/google/oss-fuzz/pull/11401#issuecomment-1872050104).
https://github.com/google/oss-fuzz/issues/11419 suggests upgrading their Python version to 3.10.
This PR updates a reference in our oss-fuzz code to use Python 3.10.
> Updated oss-fuzz to Python 3.10

- Tests/test_imagefont.py
- src/_imagingft.c
Resolves #8307
When #8141 added support for bytes in FreeTypeFont, it presumed that the text would be either a string or bytes.
This raises an error if neither are the case.
> Check text is either string or bytes

- Tests/test_box_blur.py
- src/libImaging/BoxBlur.c
Resolves #8346
If the resulting image has either a zero width or zero height, then the Box Blur will clearly have no effect on the output, and the empty image can be returned early.
> Return early from BoxBlur if either width or height is zero

- src/libImaging/Access.c
- src/libImaging/JpegDecode.c
I just happened to notice that these are the only three C functions that don't take any arguments and use `()` instead of `(void)` in their definition.
> Use (void) for empty function parameters

- Tests/test_image.py
- src/PIL/Image.py
Fixes #8348 
* Explicitly check for double exif info and drop it
> Handle duplicate EXIF header

- docs/deprecations.rst
- docs/releasenotes/11.0.0.rst
- src/PIL/TiffImagePlugin.py
This value is not used anywhere.
https://github.com/python-pillow/Pillow/blob/6377321625b93f5241305a7b301026cbbcd21e96/src/PIL/TiffImagePlugin.py#L72
> Removed unused TiffImagePlugin IFD_LEGACY_API

- Tests/test_imagefont.py
- docs/deprecations.rst
- docs/releasenotes/11.0.0.rst
- src/PIL/ImageFont.py
We need FreeType >= 2.9.1 in some places in Pillow 10.4.0.
FreeType 2.9.1 was released on 2018-05-02.
FreeType 2.10.4 fixes a severe vulnerability: "All users should update immediately".
If deprecated in Pillow 11.0.0 (2024-10), it can be removed in Pillow 12.0.0 (2025-10).
Checking some distros from https://repology.org/project/freetype/versions:
| distro | FreeType |
| - | - |
| Alpine 3.17 | 2.12.1 |
| Alpine 3.18 | 2.12.1 |
| Alpine 3.19 | 2.12.1 |
| Alpine 3.20 | 2.12.1 |
| Amazon Linux 2 | 2.8 / 2.4.11 |
| Arch | 2.13.3 |
| CentOS Stream 9 | 2.10.4 |
| Debian 11 Bullseye | 2.10.4 |
| Debian 12 Bookworm | 2.12.1 |
| Fedora 39 | 2.13.1 |
| Fedora 40 | 2.13.2 |
| Ubuntu 20.04 Focal | 2.10.1 |
| Ubuntu 22.04 Jammy | 2.11.1 |
| Ubuntu 24.04 Noble | 2.13.2 |
Removing those distros which …
> Deprecate support for FreeType 2.9.0

- src/libImaging/GetBBox.c
Code for ipython:
```python
im = Image.new('L', (2048, 2048), 0)
print('Worst case:', im.getbbox())
%timeit im.getbbox()
im = Image.open('tests/images/face1.png').resize((2048, 2048))
print('Normal case:', im.getbbox())
%timeit im.getbbox()
im = Image.open('tests/images/dices.png').resize((2048, 2048))
print('Normal case:', im.getbbox())
%timeit im.getbbox()
im = im.convert('RGB').convert('RGBA')
print('Best case:', im.getbbox())
%timeit im.getbbox()
im = im.convert('L')
print('Extrema:', im.getextrema())
%timeit im.getextrema()
```
```python
Worst case: None
2.31 ms ± 3.29 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
Normal case: (150, 474, 1802, 2048)
3.97 ms ± 519 ns per loop (mean ± std. dev. of 7 runs, 100 loops each)
Normal case: (286, 70, 1724, …
```
> Optimize getbbox() and getextrema() routines

- Tests/test_imagecms.py
- src/PIL/Image.py
> Support converting more modes to LAB by converting to RGBA first

- .github/workflows/wheels-dependencies.sh
#8344 updated harfbuzz for Windows builds. This updates it for macOS and Linux wheels, except for manylinux2014.
harfbuzz 9.0.0 has switched to meson - https://github.com/harfbuzz/harfbuzz/releases/tag/9.0.0
> Updated harfbuzz to 9.0.0 in wheels, except for manylinux2014

- Tests/test_image.py
- docs/deprecations.rst
- docs/releasenotes/11.0.0.rst
- src/PIL/Image.py
- src/PIL/ImageMath.py
Removes `isImageType()`, which relies on `hasattr(t, "im")`,
https://github.com/python-pillow/Pillow/blob/be01d536c652f2224351ad0803c92067394db1bb/src/PIL/Image.py#L125-L136
and instead uses `isinstance(im, Image)`.
I've also made a similar change in ImageMath, replacing `hasattr(v, "im")` with `isinstance(v, Image.Image)`.
> Deprecate isImageType

- Tests/test_file_gif.py
- src/PIL/GifImagePlugin.py
- src/PIL/Image.py
Resolves #8222
In the issue, two RGBA images are saved together in the GIF format. However, the transparent background is (0, 0, 0, 0) and (0, 0, 0) is also re-used at different opacities within the image. When GifImagePlugin tries to optimise the image by utilising `remap_palette()` to group multiple colours together, [it doesn't consider the A channel](https://github.com/python-pillow/Pillow/blob/22c333289e3009f8dd5f345e3328220daf11d929/src/PIL/GifImagePlugin.py#L556), and so an unexpected result occurs, where the colour information for the bottom line of the second image is lost, and then cropped out.
By improving the detection of RGBA palettes, this is fixed.
> Improved handling of RGBA palettes when saving GIF images

- Tests/test_file_icns.py
- docs/deprecations.rst
- docs/handbook/image-file-formats.rst
- docs/releasenotes/11.0.0.rst
- src/PIL/IcnsImagePlugin.py
Normally, an image size is (width, height). However, the ICNS format allows a third dimension to be added to this, scale, that only exists before loading.
https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#icns
> **sizes**
> A list of supported sizes found in this icon file; these are a 3-tuple, ``(width, height, scale)``, where ``scale`` is 2 for a retina icon and 1 for a standard icon.  You *are* permitted to use this 3-tuple format for the `size` property if you set it before calling `load()`; after loading, the size will be reset to a 2-tuple containing pixel dimensions (so, e.g. if you ask for ``(512, 512, 2)``, the final value of `size` will be ``(1024, 1024)``).
This is a brief exception to the rule that image sizes have two dimensions. As such, it complicates …
> Deprecate ICNS (width, height, scale) sizes in favour of load(scale)

- .ci/install.sh
Since #8182, cffi is no longer used, so its dependency, libffi-dev, no longer needs to be installed.
> Removed libffi-dev

- src/encode.c
- src/libImaging/Jpeg2K.h
- src/libImaging/Jpeg2KDecode.c
- src/libImaging/Jpeg2KEncode.c
Cherry-picking a commit from @homm's #8340 that is unrelated to the rest of the draft PR, and so can be included by itself.
The following comment appears in a few C files.
https://github.com/python-pillow/Pillow/blob/cb2a0c40f3760411423d09defada95c54564317a/src/encode.c#L1414-L1420
It appears to be [setting indentation for Emacs](https://www.gnu.org/software/emacs/manual/html_node/ccmode/Customizing-Indentation.html). These can be removed, if for no other reason than #4770 set the indentation instead with ClangFormat.
> Remove comments

- wheels/README.md
https://github.com/python-pillow/Pillow/blob/main/wheels/README.md
> Windows wheels are created separately. They are [GitHub Actions artifacts created on each run of the Windows workflow](https://github.com/python-pillow/Pillow/actions/workflows/test-windows.yml?query=branch%3Amain).
This is no longer true, as a result of #7580
> Windows wheels are now grouped with the others

- .ci/install.sh
https://pypi.org/project/numpy/#files now offers 313t wheels, and so we can start installing NumPy from PyPI for the free threaded job, rather than using Scientific Python Nightly Wheels.
> Install NumPy from PyPI for free threaded job

- .github/workflows/wheels-test.sh
NumPy now provides musllinux wheels on PyPi - see https://pypi.org/project/numpy/#files (and https://pypi.org/project/numpy/2.0.2/#files for Python 3.9).
So our musllinux wheels can use it for testing.
> Test NumPy with musllinux wheels

- src/path.c
https://github.com/python-pillow/Pillow/blob/c9eb14e1043f04aa0463725060cde24e2c7bea8b/src/path.c#L44-L48
`index` has been unused since PIL. I have no idea what 'decimate' is.
> Removed unused ImagePath variable

- .github/workflows/wheels.yml
cibuildwheel 2.21.0 has just been released - https://github.com/pypa/cibuildwheel#changelog
> Update CPython 3.12 to 3.12.6, which changes the macOS minimum deployment target on CPython 3.12 from macOS 10.9 to macOS 10.13
This is not just a cibuildwheel restriction - https://www.python.org/downloads/release/python-3126
> this release drops support for macOS versions 10.9 through 10.12. Versions of macOS older than 10.13 haven't been supported by Apple since 2019, and maintaining support for them has become too difficult. (All versions of Python 3.13 have already dropped support for them.)
So this PR splits our macOS Intel job into two - one for Python < 3.12 with a deployment target of macOS 10.10, and one for Python >= 3.12 with a deployment target of 10.13.
Our M1 builds already have a …
> Updated macOS deployment target for Python >= 3.12 on Intel to 10.13

- Tests/test_image.py
- Tests/test_imageshow.py
- pyproject.toml
Sequel to #8309
Enables https://docs.astral.sh/ruff/rules/pytest-fail-without-message
> Lint: Run PT016

- Tests/test_imagewin.py
- src/PIL/ImageWin.py
Resolves #8383
The `Dib` class passes `handle` to core method `getdc()` in `expose()`
https://github.com/python-pillow/Pillow/blob/b67f018c00841601d8b11a1be722b0ebffc62f54/src/PIL/ImageWin.py#L101-L102
but despite what our Python logic would lead you to expect, [it must be an integer.](https://github.com/radarhere/Pillow/actions/runs/10871220422/job/30164766681#step:27:3403) See the following code and https://docs.python.org/3/c-api/arg.html#numbers
https://github.com/python-pillow/Pillow/blob/b67f018c00841601d8b11a1be722b0ebffc62f54/src/display.c#L37-L41
https://github.com/python-pillow/Pillow/blob/b67f018c00841601d8b11a1be722b0ebffc62f54/src/display.c#L165-L169
So this PR casts it to an integer in Python first. The same logic also applies to `draw()` and `query_palette()`.
> Cast Dib handle to int

- src/PIL/PngImagePlugin.py
Resolves #8363
https://github.com/python-pillow/Pillow/blob/08d9c89d8a7db84e8145814bca36d7dd5b7465ce/src/PIL/PngImagePlugin.py#L141-L144
This PR changes the error message to "Decompressed data too large for PngImagePlugin.MAX_TEXT_CHUNK".
This is more informative. If the user [searches our docs for "PngImagePlugin.MAX_TEXT_CHUNK"](https://pillow.readthedocs.io/en/stable/search.html?q=PngImagePlugin.MAX_TEXT_CHUNK) they will find https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#png-opening
> Individual compressed chunks are limited to a decompressed size of [PngImagePlugin.MAX_TEXT_CHUNK](https://pillow.readthedocs.io/en/stable/reference/plugins.html#PIL.PngImagePlugin.MAX_TEXT_CHUNK), by default 1MB, to prevent decompression bombs.
> Mention MAX_TEXT_CHUNK limit in PNG error message

- Tests/test_image_copy.py
- Tests/test_image_resize.py
- Tests/test_image_thumbnail.py
- Tests/test_numpy.py
- src/PIL/Image.py
- src/PIL/ImageFile.py
- src/PIL/TiffImagePlugin.py
Alternative to #8387
At the moment, `load()` might change the size of a TIFF image, since TIFF images are [automatically transposed when doing so](https://github.com/python-pillow/Pillow/blob/08d9c89d8a7db84e8145814bca36d7dd5b7465ce/src/PIL/TiffImagePlugin.py#L1295).
`load()` is a method that many users are probably not even aware of, and so they might find
```python
im = Image.open("/Users/andrewmurray/pillow/Pillow/Tests/images/g4_orientation_5.tif")
print(im.size)  # (88, 590)
print(im.copy().size)  # (590, 88)
```
unexpected.
After this PR, the first `im.size` will also be (590, 88). This has means that changes from #6186 and #6190 can be removed.
#8387 solves this by making `im.size` sometimes different to `im._size`. I would like to avoid that, and have instead …
> Use transposed size after opening for TIFF images

- README.md
- docs/index.rst
The OSS Fuzz issue tracker has moved. See https://github.com/google/oss-fuzz/issues/12508
This means that our badge link to Pillow OSS Fuzz issues is no longer correct.
> Updated link to OSS Fuzz issues

- src/libImaging/Geometry.c
The `imIn` pointer is checked for `NULL`, but it seems to be dereferenced before this check. You must first make sure that the pointer is not `NULL` before using it.
Found by Linux Verification Center (linuxtesting.org) with SVACE.
Reporter: Pavel Nekrasov ([p.nekrasov@fobos-nt.ru](mailto:p.nekrasov@fobos-nt.ru)).
> Fix dereference before checking for NULL in ImagingTransformAffine

- depends/install_raqm.sh
raqm 0.10.2 has been released - https://github.com/HOST-Oman/libraqm/releases/tag/v0.10.2
> Updated raqm to 0.10.2

- winbuild/build_prepare.py
#8302 broke passing in custom properties to FreeType, fix it by using the VS project file directly instead of the solution file.
This should fix the skipped CBDT/SBIX/WOFF2 tests.
> winbuild: Build freetype.vcxproj to fix passing in custom parameters

- .appveyor.yml
- .ci/test.cmd
- .ci/test.sh
- .github/workflows/test-mingw.yml
- .github/workflows/test-windows.yml
Add a CI test script for Windows, and update appveyor, mingw, and windows to use the common test scripts.
> Use common test scripts for more tests

- depends/install_imagequant.sh
The docker-images Gentoo job can't install libimagequant at the moment - https://github.com/python-pillow/docker-images/actions/runs/10988523287/job/30505070454#step:6:1356
> cp: cannot stat 'usr/lib/libimagequant.so*': No such file or directory
Testing, I find that the shared libraries are actually within 'lib64' instead. So this updates the install script to work with either directory.
With this change, libimagequant is installed and [detected successfully.](https://github.com/radarhere/docker-images/actions/runs/10990710903/job/30511535686#step:7:643)
> Shared imagequant libraries may be located within usr/lib64

- .github/workflows/wheels.yml
https://doc.pypy.org/en/latest/release-v7.3.17.html
> Bump `MACOSX_DEPLOYMENT_TARGET` to 10.15 on x86_64 and 11.0 on arm64 ([#4975](https://github.com/pypy/pypy/issues/4975))
https://pypy.org/download.html
> MacOS x86_64 | Download | Download | MacOS >= 10.15, not for Mojave and below.
> Updated macOS deployment target for PyPy on Intel to 10.15

- Tests/test_file_tiff.py
- Tests/test_file_tiff_metadata.py
- src/PIL/TiffImagePlugin.py
The StripOffsets values don't really mean anything without associated image data, so I just did the same thing as when this tag only has one value and added the IFD offset to the values.
StripOffsets is overwritten with correct values when writing TIFF images, so this only matters when writing a non-TIFF image, where StripOffsets doesn't mean anything. The main benefit of this change is that it won't raise an exception now when saving a non-TIFF image with EXIF data copied from a TIFF image that has more than one strip.
> Fixed writing multiple StripOffsets to TIFF

- winbuild/build_prepare.py
fribidi 1.0.16 has been released - https://github.com/fribidi/fribidi/releases/tag/v1.0.16
> Updated fribidi to 1.0.16

- CHANGES.rst
- Tests/test_file_webp.py
- src/PIL/WebPImagePlugin.py
- src/_webp.c
Adoption of #8341 ideas
* Doesn't create extra image copy (`.tobytes("raw", rawmode)`)
* Uses the same more appropriate API `.has_transparency_data` for save and save_all.
* Supports saving `RGBX` mode without conversion
* Adds `ImagingSectionEnter/Leave` for `WebPAnimEncoder`
> Use Capsule for WEBP saving

- .github/workflows/wheels-dependencies.sh
Two changes here.
1. As noted in #8361, harfbuzz has switched to meson - https://github.com/harfbuzz/harfbuzz/releases/tag/9.0.0.
More specifically though, it now requires [meson >= 0.55](https://github.com/harfbuzz/harfbuzz/blob/c7ef6a2ed58ae8ec108ee0962bef46f42c73a60c/meson.build#L2).
This is a problem, as the base image for oss-fuzz uses [Ubuntu 20.04](https://github.com/google/oss-fuzz/blob/7fa4a40a8547a007bdf13c2bb391cec8c14d8dc0/infra/base-images/base-image/Dockerfile#L19), which only has [meson 0.53.2](https://packages.ubuntu.com/focal/meson)
So this PR downgrades harfuzz on OSS Fuzz to the version before meson became mandatory. I've used the environment variable 'SANITIZER' to detect OSS Fuzz.
2. I found that harfbuzz 8.5.0 was being [installed on …
> Change harfbuzz versions in wheels

- Makefile
- pyproject.toml
- Update Makefile to use `ruff check .` rather than `ruff .`, as per https://github.com/astral-sh/ruff/pull/10169
- Do not run ruff or black over the multibuild submodule. The effect of this is not usually seen, but if you were using multibuild for some reason (`git submodule update`), and then ran either ruff or black in Pillow, they would both modify the code.
> Use ruff check

- depends/install_imagequant.sh
#8407 updated the path to shared libraries in libimagequant to allow for usr/lib64.
I've made two improvements here.
1. The previous PR didn't update the path to copy from for the caching mechanism. This is inconsistent, and might cause problems one day.
2. I found that the path for Debian is usr/lib/x86_64-linux-gnu. Rather than adding a third possible path, I've used `find` to allow for the path to vary.
> Improved copying imagequant libraries

- .github/workflows/wheels-dependencies.sh
https://github.com/python-pillow/Pillow/pull/8421#issuecomment-2380419749 suggested installing meson through pip.
This works in all environments, allowing harfbuzz 10.0.1 to installed for all wheels, and on OSS Fuzz.
> Updated harfbuzz to 10.0.1 in remaining wheels

- src/libImaging/Geometry.c
Similar to https://github.com/python-pillow/Pillow/pull/8398, check the value of `imIn` before using it.
https://github.com/python-pillow/Pillow/blob/b557876ec3aa4d5d236d8044519f1c613031fbee/src/libImaging/Geometry.c#L794-L801
https://github.com/python-pillow/Pillow/blob/b557876ec3aa4d5d236d8044519f1c613031fbee/src/libImaging/Geometry.c#L709-L712
> Check image value before use

- .github/workflows/cifuzz.yml
Reverts #8239 now that https://github.com/google/oss-fuzz/pull/12546 has been merged.
> Restore cifuzz

- src/libImaging/FliDecode.c
Resolves #8405. Alternative to #8406
The issue is concerned that at
https://github.com/python-pillow/Pillow/blob/731bcda904544d9d26bce268eca3a5cb4fcc1c46/src/libImaging/FliDecode.c#L227
`state->xsize` might be zero, and so we might be dividing by zero.
However, in the context of our library as a whole, images that say one of their dimensions are zero will be stopped at https://github.com/python-pillow/Pillow/blob/731bcda904544d9d26bce268eca3a5cb4fcc1c46/src/PIL/ImageFile.py#L154-L156
Even if you consider just the C decoding process, we have
https://github.com/python-pillow/Pillow/blob/731bcda904544d9d26bce268eca3a5cb4fcc1c46/src/decode.c#L189-L192
So this is not a scenario that should actually occur. However, in order to allay concerns from a casual observer, it might be worth updating …
> Prevent division by zero

- src/libImaging/SgiRleDecode.c
Resolves #8401
`tablen` is an integer
https://github.com/python-pillow/Pillow/blob/b557876ec3aa4d5d236d8044519f1c613031fbee/src/libImaging/Sgi.h#L22
and before we set it to `im->bands * im->ysize`, we check that the value will be less than `INT_MAX`
https://github.com/python-pillow/Pillow/blob/b557876ec3aa4d5d236d8044519f1c613031fbee/src/libImaging/SgiRleDecode.c#L170-L172
but we then temporarily multiply it by 8, which might exceed `INT_MAX`.
https://github.com/python-pillow/Pillow/blob/b557876ec3aa4d5d236d8044519f1c613031fbee/src/libImaging/SgiRleDecode.c#L181-L186
So this PR casts it to `int64_t` before applying the multiplication.
> Cast int before potentially exceeding INT_MAX

- Tests/test_image_resize.py
- docs/releasenotes/11.0.0.rst
- src/PIL/Image.py
- src/_imaging.c
- src/libImaging/Resample.c
Resolves #8333 by allowing `resize()` on I;16, I;16L, I;16B and I;16N images to work with resampling filters other than `NEAREST`.
Given [the original intention](https://github.com/python-pillow/Pillow/pull/4255#issuecomment-821729238) to use `BICUBIC` as the default resampling for all modes, I've also changed the default resampling for I;16* modes to `BICUBIC` here. This will only leave the [deprecated modes BGR;15, BGR;16 and BGR;24](https://github.com/python-pillow/Pillow/pull/7978) using `NEAREST` by default.
>  Support all resampling filters when resizing I;16* images

- src/PIL/ImageEnhance.py
If an attempt is made to convert an image to its current mode [(without a matrix), a copy is simply returned.](https://github.com/python-pillow/Pillow/blob/c6b08ef32c39dc6517e9140c92dde7e10999da5e/src/PIL/Image.py#L1009-L1010)
However, `copy()` still consumes resources, and it would be ideal to avoid it where possible. In ImageEnhance, there are a few such instances.
What if the image already matches `self.intermediate_mode` in `Color`?
https://github.com/python-pillow/Pillow/blob/c6b08ef32c39dc6517e9140c92dde7e10999da5e/src/PIL/ImageEnhance.py#L58
What if the image is already L mode in `Enhance`?
https://github.com/python-pillow/Pillow/blob/c6b08ef32c39dc6517e9140c92dde7e10999da5e/src/PIL/ImageEnhance.py#L69-L72
This PR skips calling `convert()` for those scenarios.
> Do not convert images unnecessarily in ImageEnhance

- .github/workflows/cifuzz.yml
Since our cifuzz job is [a different environment to our other jobs](https://github.com/google/oss-fuzz/blob/7fa4a40a8547a007bdf13c2bb391cec8c14d8dc0/infra/base-images/base-image/Dockerfile#L19), and [calls wheels-dependencies.sh](https://github.com/google/oss-fuzz/blob/38d4a5abcb47b8257fd05b5bdd7d752ed19a0d1f/projects/pillow/build_depends.sh#L26), I think it makes sense to test cifuzz when a change is made to wheels-dependencies.sh.
A concrete demonstration of this was made in #8421, when it featured a change in wheels-dependencies.sh specifically targeted at the cifuzz job.
> Test cifuzz when wheel dependencies change

- .github/workflows/wheels.yml
PEP 740 ("Index support for digital attestations" introduces digital attestations which links the PyPI package to the GitHub repo, and helps users verify the source and authenticity of packages.
PyPI is still implementing support, but we can already start using it, which should also help them test out.
* https://peps.python.org/pep-0740/
* https://github.com/pypa/gh-action-pypi-publish#generating-and-uploading-attestations
* https://github.com/pypi/warehouse/issues/15871
> Generate and upload attestations to PyPI

- Tests/test_file_apng.py
- src/PIL/PngImagePlugin.py
Helps #8440
When subsequent frames are loaded from an APNG image, transparency is considered for RGB core images, but not for P core images.
https://github.com/python-pillow/Pillow/blob/01bb78a8e7ae7656b5abddd2d9d37f67124f8a3e/src/PIL/PngImagePlugin.py#L1061-L1066
This adds that, modelled after
https://github.com/python-pillow/Pillow/blob/01bb78a8e7ae7656b5abddd2d9d37f67124f8a3e/src/PIL/Image.py#L1100-L1103
> Use transparency when combining P frames from APNGs

- Tests/test_imageshow.py
https://github.com/python-pillow/Pillow/actions/runs/11202062547/job/31137725975#step:12:4820
> Tests/test_imageshow.py::test_ipythonviewer
>   /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/_pytest/python.py:159: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/runner/work/Pillow/Pillow/Tests/images/hopper.ppm'>
The file is opened in `hopper()`
https://github.com/python-pillow/Pillow/blob/27c1bb265432cb5a1138e39165f0610e2d8a4e94/Tests/helper.py#L252-L261
and then called in
https://github.com/python-pillow/Pillow/blob/27c1bb265432cb5a1138e39165f0610e2d8a4e94/Tests/test_imageshow.py#L120-L121
Adding a context manager fixes the warning.
> Fixed unclosed file warning in test_imageshow.py

- Tests/test_image_filter.py
- src/libImaging/Filter.c
> Support ImageFilter.BuiltinFilter for I;16* images

- Makefile
- docs/Makefile
- docs/conf.py
- pyproject.toml
* Sphinx 8.1 adds roles for referencing CVEs ([`:cve:`](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-cve)) and CWEs ([`:cwe:`](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-cwe))
* https://www.sphinx-doc.org/en/master/changes/index.html
* Let's use those instead of our own `extlinks`
* Update `Makefile` so we install Pillow for docs builds using the `docs` extra, so installs Sphinx 8.1+, and avoids defining the docs dependencies in two places
> Use CVE and CWE roles from Sphinx 8.1

- src/PIL/TiffImagePlugin.py
- src/libImaging/TiffDecode.c
Addresses https://github.com/python-pillow/Pillow/issues/7042#issuecomment-2404653713
#7199 made a change to C code so that libtiff did not always close the file handle when decoding an image, removing the need for the file handle to be duplicated in Python.
This makes the save change, but for encoding an image.
> Do not close provided file handles with libtiff when saving

- Tests/test_features.py
- src/PIL/features.py
When I run the test suite [without WebP installed](https://github.com/radarhere/Pillow/commit/d6b8c8cc4d0a45629c2ad0caf1963c420c4fb18a), it [fails.](https://github.com/radarhere/Pillow/actions/runs/11290360694/job/31402063623#step:26:143)
```
Tests/test_features.py::test_check FAILED                                [  2%]
================================== FAILURES ===================================
_________________________________ test_check __________________________________
def test_check() -> None:
for module in features.modules:
assert features.check_module(module) == features.check(module)
for codec in features.codecs:
assert features.check_codec(codec) == features.check(codec)
for feature in features.features:
if "webp" in feature:
>               with …
```
> Always raise warnings for deprecated feature checks

- src/PIL/TiffImagePlugin.py
Addresses an 'undone' that has been present since #98
https://github.com/python-pillow/Pillow/blob/08b561e25dd58daa6bc86989d1a8e55795a6b81e/src/PIL/TiffImagePlugin.py#L1940-L1941
`self.decodermaxblock` isn't necessarily available, because `im` may not be an `ImageFile` instance, but `ImageFile.MAXBLOCK` is usually the same.
https://github.com/python-pillow/Pillow/blob/08b561e25dd58daa6bc86989d1a8e55795a6b81e/src/PIL/ImageFile.py#L128
> Use ImageFile.MAXBLOCK when saving TIFF images

- Tests/test_file_tiff.py
- src/PIL/TiffImagePlugin.py
https://github.com/python-pillow/Pillow/blob/3f24276bf2ab8c29b2c3aa96f5bca2b60b9f3340/Tests/test_file_tiff.py#L110-L116
if you try and run the test without removing this tag, an error is raised from `AppendingTiffWriter`.
```
def fixOffsets(
self, count: int, isShort: bool = False, isLong: bool = False
) -> None:
if not isShort and not isLong:
msg = "offset is neither short nor long"
>           raise RuntimeError(msg)
E           RuntimeError: offset is neither short nor long
```
Extending `AppendingTiffWriter` to handle LONG8 offsets is made complicated as it explicitly only handles shorts and longs, and has duplicated code to achieve that.
https://github.com/python-pillow/Pillow/blob/3f24276bf2ab8c29b2c3aa96f5bca2b60b9f3340/src/PIL/TiffImagePlugin.py#L2143-L2151 …
> Support writing LONG8 offsets in AppendingTiffWriter

- .github/workflows/wheels-dependencies.sh
Originally added in https://github.com/python-pillow/pillow-wheels/pull/294 to solve [a build failure](https://github.com/python-pillow/pillow-wheels/pull/293#issuecomment-1126626076), I find openjpeg now builds without this custom code.
> Removed custom build_openjpeg

- src/PIL/TiffImagePlugin.py
https://github.com/python-pillow/Pillow/blob/1ee3bd1d9e1a96da01ba55aff376e214082bcba8/src/PIL/TiffImagePlugin.py#L1189-L1198
The core image instance does not need to be created here. It can be set to `None` instead, and the initialisation can delayed until `load()` (or more specifically, `load_prepare()`).
https://github.com/python-pillow/Pillow/blob/1ee3bd1d9e1a96da01ba55aff376e214082bcba8/src/PIL/TiffImagePlugin.py#L1278-L1280
> Do not create core image in TIFF seek()

- .pre-commit-config.yaml
- pyproject.toml
Closes https://github.com/python-pillow/Pillow/issues/7942.
Pending https://github.com/pypa/trove-classifiers/pull/189.
> Update licence to MIT-CMU

- docs/releasenotes/11.0.0.rst
* The final Python 3.13 release was [delayed by 6 days](https://discuss.python.org/t/incremental-gc-and-pushing-back-the-3-13-0-release/65285) but went out [successfully on 2024-10-07](https://discuss.python.org/t/python-3-13-0-final-has-been-released/66972)
* https://peps.python.org/pep-0719/
> Update Python 3.13 release date

- .github/workflows/wheels.yml
[Pillow 11.0.0](https://pypi.org/project/pillow/#files) included some pypy39 wheels, despite #8335
> Skip PyPy3.9 wheels

- LICENSE
- docs/about.rst
> Update license to MIT-CMU

- winbuild/build_prepare.py
There are several places in `winbuild/build_prepare.py` where the "filename" is replicated in the "url"
https://github.com/python-pillow/Pillow/blob/822ec3d05dfbaf2e3209c2b26e3392040e274975/winbuild/build_prepare.py#L163-L165
I wonder if
```python
"zlib": {
"url": "https://zlib.net/FILENAME",
"filename": f"zlib{V['ZLIB_DOTLESS']}.zip",
```
is neater, reducing duplication?
Feel free to reject if others think it isn't simpler.
> Added filename placeholder in winbuild URL

- Tests/test_bmp_reference.py
- Tests/test_file_dcx.py
- Tests/test_file_fli.py
- Tests/test_file_gif.py
- Tests/test_file_icns.py
- Tests/test_file_im.py
- Tests/test_file_jpeg.py
- Tests/test_file_mpo.py
- Tests/test_file_png.py
- Tests/test_file_psd.py
- Tests/test_file_spider.py
- Tests/test_file_tar.py
- Tests/test_file_tiff.py
- Tests/test_file_webp.py
- Tests/test_image.py
- Tests/test_imageqt.py
- Tests/test_numpy.py
https://docs.pytest.org/en/latest/how-to/capture-warnings.html#additional-use-cases-of-warnings-in-tests states
> To ensure that no warnings are emitted, use:
> 
> ```python
> def test_warning():
>     with warnings.catch_warnings():
>         warnings.simplefilter("error")
>         ...
> ```
However, in #6076, I decided not to add `warnings.simplefilter("error")`. I've now concluded that was a mistake, and that this doesn't turn warnings into errors as intended - if I add [`warnings.warn("This should cause a failure")`](https://github.com/radarhere/Pillow/commit/55a80c491256a90d441c494a650d84a933c80e26), the test suite [still passes](https://github.com/radarhere/Pillow/actions/runs/11529275107). Restoring [`simplefilter`](https://github.com/radarhere/Pillow/commit/ce5f5e36a450242abb2abe5 …
> Fixed catching warnings

- docs/handbook/image-file-formats.rst
Move MPO into "Fully supported formats" at https://pillow.readthedocs.io/en/latest/handbook/image-file-formats.html
> Move MPO into "Fully supported formats"

- Tests/test_file_jpeg2k.py
At the start of test_file_jpeg2k.py, an image is opened.
https://github.com/python-pillow/Pillow/blob/d59b169ed257ca14d86c90dbf3384b8b3999fc5c/Tests/test_file_jpeg2k.py#L32-L33
It is then used throughout the tests.
https://github.com/python-pillow/Pillow/blob/d59b169ed257ca14d86c90dbf3384b8b3999fc5c/Tests/test_file_jpeg2k.py#L103-L110
Rather than re-using the same image instance throughout the tests, and allowing it to be potentially modified in one test and affect all subsequent tests, this PR uses a fixture to re-open it each time, following the style of [test_image_resize.py.](https://github.com/python-pillow/Pillow/blob/d59b169ed257ca14d86c90dbf3384b8b3999fc5c/Tests/test_image_resize.py#L181-L188)
> Use fixture to re-open image for each JPEG2000 test

- Tests/test_file_wmf.py
- src/PIL/WmfImagePlugin.py
Resolves #8462
Corrects a typo when calculating the X DPI of an EMF image - `x1 - y0` should be `x1 - x0`.
https://github.com/python-pillow/Pillow/blob/331e4e751733eb0af018602ef26746a7e0571107/src/PIL/WmfImagePlugin.py#L130-L132
> Corrected EMF DPI

- src/_imagingft.c
- src/thirdparty/pythoncapi_compat.h
Fixes #8454.
* Introduce a mutex that needs to be held every time `FT_New_Face` or `FT_Done_Face` are called.
* Upgrade `pythoncapi_compat.h` to the latest version.
> Fix SEGFAULT from calling FT_New_Face/FT_Done_Face in multiple threads

- .github/workflows/wheels-dependencies.sh
An intermittent error has started appearing when building macOS < 11 wheels, due to the presence of Homebrew's libdeflate.
https://github.com/python-pillow/Pillow/actions/runs/11527160571/job/32095165039#step:5:8054
```pytb
File "/private/var/folders/nj/wh528zms06j9t8y7bmlvpmjm0000gn/T/cibw-run-lwy73nns/cp39-macosx_x86_64/build/venv/lib/python3.9/site-packages/delocate/delocating.py", line 925, in _check_and_update_wheel_name
raise DelocationError(
delocate.libsana.DelocationError: Library dependencies do not satisfy target MacOS version 10.10:
/private/var/folders/nj/wh528zms06j9t8y7bmlvpmjm0000gn/T/tmp7e9dgm3u/wheel/PIL/.dylibs/libdeflate.0.dylib has a minimum target of 13.0
Set the environment variable 'MACOSX_DEPLOYMENT_TARGET=13.0' to update minimum supported macOS for this wheel. …
```
> brew remove libdeflate

- .github/workflows/wheels-dependencies.sh
Upgrades multibuild to include https://github.com/multi-build/multibuild/pull/538, meaning that
https://github.com/python-pillow/Pillow/blob/bdd0b8630c77172245aae3b1e7902685a2d40dca/.github/workflows/wheels-dependencies.sh#L94-L96
can now be removed. Without the multibuild upgrade, the wheels [could](https://github.com/radarhere/Pillow/commit/094f2eccce716ccda8a428a35a927ad62752a454) [fail](https://github.com/radarhere/Pillow/actions/runs/11563407753) to find OpenJPEG.
> Upgraded multibuild to remove openjpeg lib64 copy

- .github/workflows/test-windows.yml
- src/PIL/ImageQt.py
Alternative to #8507
The user in that PR reported seeing corrupt output from `ImageQt.toqpixmap()` on Windows.
https://github.com/python-pillow/Pillow/blob/9a4b3e05d643c92f050df5713e48225a9f36497e/src/PIL/ImageQt.py#L214-L216
Testing, I found I was able to use GitHub Actions to reproduce the matter.
Testing further, I found that it was only happening when `qimage` was inside the function - if I unwrapped the function so that `qimage` wouldn't be garbage collected, the problem disappeared. I created a reproduction just using PyQt6 and asked about this at https://stackoverflow.com/questions/79133259/corrupted-display-from-qpixmap-fromimage. The response I received was
> This is caused by [Qt's implicit data sharing](https://doc.qt.io/qt-6/implicit-sharing.html). The QImage will be …
> Detach PyQt6 QPixmap instance before returning

- Tests/test_file_jpeg.py
https://github.com/tonybaloney/pytest-freethreaded/issues/11 noted a segfault that can occur under free-threading with `Tests/test_file_jpeg.py::test_qtables`. I can replicate this with [`--require-gil-disabled`](https://github.com/radarhere/Pillow/commit/d928ddf06c75ca8e730d52df575314fc4788e825) - https://github.com/radarhere/Pillow/actions/runs/11572743510
Changing the test to save to a BytesIO instance rather than writing repeatedly to the same temporary path fixes this specific test - https://github.com/radarhere/Pillow/actions/runs/11572819452
> Do not repeatedly save to the same path

- .github/workflows/test-docker.yml
- .github/workflows/test.yml
The `gcov` argument has been removed `codecov/codecov-action@v4` and has been replaced by an optional `plugin` that includes `gcov` by default:
Input | Description | Required
-- | -- | --
plugin | plugins to run. Options: xcode, gcov, pycoverage. The default behavior runs them all.
https://github.com/codecov/codecov-action#arguments
This will remove some warnings like:
> Unexpected input(s) 'gcov', valid inputs are ['token', 'codecov_yml_path', 'commit_parent', 'directory', 'disable_file_fixes', 'disable_search', 'disable_safe_directory', 'dry_run', 'env_vars', 'exclude', 'fail_ci_if_error', 'file', 'files', 'flags', 'git_service', 'handle_no_reports_found', 'job_code', 'name', 'network_filter', 'network_prefix', 'os', 'override_branch', 'override_build', 'override_build_url', …
> Remove unused `gcov: true` for codecov-action@v4

- .github/workflows/docs.yml
- .github/workflows/lint.yml
- .github/workflows/stale.yml
- .github/workflows/test-cygwin.yml
- .github/workflows/test-docker.yml
- .github/workflows/test-mingw.yml
- .github/workflows/test-valgrind.yml
- .github/workflows/test-windows.yml
- .github/workflows/test.yml
- .github/workflows/wheels.yml
There's a new tool that flags potential security issues in GitHub Actions workflows: https://github.com/woodruffw/zizmor
<details>
<summary>Details</summary>
```console
❯ zizmor .
🌈 completed cifuzz.yml
🌈 completed release-drafter.yml
🌈 completed stale.yml
🌈 completed docs.yml
🌈 completed test-valgrind.yml
🌈 completed test-windows.yml
🌈 completed test-mingw.yml
🌈 completed test-docker.yml
🌈 completed lint.yml
🌈 completed test.yml
🌈 completed test-cygwin.yml
🌈 completed wheels.yml
error[excessive-permissions]: overly broad workflow or job-level permissions
--> /Users/hugo/github/Pillow/.github/workflows/stale.yml:8:1
|
8 | / permissions:
9 | |   issues: write
| |_______________^ issues: write is overly broad at the workflow level
|
warning[artipacked]: credential persistence through GitHub …
```
> Apply security fixes to GitHub Actions

- setup.py
An error has started occurring in main - https://github.com/python-pillow/Pillow/actions/runs/11677258842/job/32514847792
```
setup.py:1010: error: Argument 2 to "Extension" has incompatible type
"list[str]"; expected "list[Union[str, PathLike[str]]]"  [arg-type]
Extension("PIL._imaging", files),
^~~~~
setup.py:1010: note: "List" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
setup.py:1010: note: Consider using "Sequence" instead, which is covariant
Found 1 error in 1 file (checked 294 source files)
```
> Fixed type hint

- docs/reference/ImageFile.rst
https://pillow.readthedocs.io/en/latest/reference/ImageFile.html has an example where users are invited to open "hopper.pgm".
Maybe no one else is bothered by this, but hopper.pgm doesn't exist as one of our test files, so I think the example code should be updated to refer to [hopper.ppm](https://github.com/python-pillow/Pillow/blob/main/Tests/images/hopper.ppm) instead.
> Use test image filename

- .github/workflows/test.yml
Updates the Python version running the gcc problem matcher to Python 3.13
https://github.com/python-pillow/Pillow/blob/2e7da079cdadf24a5d17cc4b0d32df434777c789/.github/workflows/test.yml#L118-L120
> Run gcc problem matcher on Python 3.13

- setup.py
This allows to link to zlib when used as shared library, in my environment I do not activate all of the external libraries so that part might influence the result, but I think it can still be valuable for others to try the same.
> Allow linking to zlib import library on Windows

- src/PIL/_typing.py
See previous discussion of this at https://github.com/python-pillow/Pillow/pull/7750#discussion_r1468360968
> Removed quotes after dropping support for Python 3.8

- src/PIL/Image.py
- src/PIL/ImageFile.py
- src/PIL/ImageFont.py
> Removed use of os.path.realpath

- .github/workflows/test-mingw.yml
- docs/installation/building-from-source.rst
MinGW has started failing in main - https://github.com/python-pillow/Pillow/actions/runs/11950775623/job/33312968743#step:4:233
> error: externally-managed-environment
> 
> This environment is externally managed
> 
> To install Python packages system-wide, try 'pacman -S
> $MINGW_PACKAGE_PREFIX-python-xyz', where xyz is the package you
> are trying to install.
> 
> If you wish to install a non-MSYS2-packaged Python package,
> create a virtual environment using 'python -m venv path/to/venv'.
> Then use path/to/venv/bin/python and path/to/venv/bin/pip.
> 
> If you wish to install a non-MSYS2 packaged Python application,
> it may be easiest to use 'pipx install xyz', which will manage a
> virtual environment for you. Make sure you have $MINGW_PACKAGE_PREFIX-python-pipx
> installed via …
> Do not install Pyroma in MinGW, to use only system packages

- .github/workflows/wheels-dependencies.sh
#8497 added
https://github.com/python-pillow/Pillow/blob/d7ffb397313e843d500816a8ac2a1f9faf0e89b5/.github/workflows/wheels-dependencies.sh#L185-L186
to the macOS and Linux wheels.
However, we still have an alternative attempt to install cmake.
https://github.com/python-pillow/Pillow/blob/d7ffb397313e843d500816a8ac2a1f9faf0e89b5/.github/workflows/wheels-dependencies.sh#L77-L82
where `get_modern_cmake` is [from multibuild](https://github.com/multi-build/multibuild/blob/9a9d1275f025f737cdaa3c451ba07129dd95f361/library_builders.sh#L199-L217).
That can now be removed.
> Do not attempt to install cmake a second time when building macOS or Linux wheels

- .github/release-drafter.yml
For #8569.
* https://github.com/python-pillow/Pillow/releases/tag/11.0.0 has the uncategorised "Changes" first, and then more important things like removals and deprecations further down
* Let's put uncategorised ones last (see https://github.com/release-drafter/release-drafter/pull/1013), and move more important Removals, Deprecations further up.
* Also moved Documentation above Dependencies
> Release drafter: move removals, deprecations, documentation up, and uncategorised changes last

- .github/CONTRIBUTING.md
- CHANGES.rst
- README.md
- RELEASING.md
- codecov.yml
- pyproject.toml
> Added link to GitHub releases in CHANGES

- docs/installation/building-from-source.rst
https://pillow.readthedocs.io/en/latest/installation/building-from-source.html
> To install libraqm on macOS use Homebrew to install its dependencies:
> 
> `brew install freetype harfbuzz fribidi`
> Then see `depends/install_raqm_cmake.sh` to install libraqm.
This documented process can be made simpler by suggesting that users just `brew install libraqm` instead.
We have been using the libraqm formula in GitHub Actions since https://github.com/python-pillow/Pillow/pull/5061.
> Use brew formula to install libraqm

- setup.py
#7171 moved Pillow build options from
```
python3 -m pip install --upgrade Pillow --global-option="build_ext" --global-option="--enable-[feature]"
```
to
```
python3 -m pip install --upgrade Pillow -C [feature]=enable
```
but did not update error and debug messages in setup.py.
> Updated build option error messages

- LICENSE
- docs/COPYING
- docs/conf.py
Over in CPython, after consulting with the PSF's legal representative, we decided to remove the end years from the copyright notices because there's no need to update them each January.
See:
* https://devguide.python.org/getting-started/pull-request-lifecycle/#copyrights
* https://github.com/python/cpython/issues/126133#issuecomment-2460824052
* https://github.com/python/release-tools/pull/196
> Only use start year in copyright, remove end years

- src/PIL/ImageFile.py
Update a docstring after #8336 changed ImageFile `tile` to never be None
> ImageFile tile is never None

- docs/handbook/tutorial.rst
- pyproject.toml
Fixes https://github.com/python-pillow/Pillow/issues/8585.
> Replace python-pillow.org with python-pillow.github.io

- .github/workflows/macos-install.sh
It would appear that libjpeg isn't actually being installed on macOS builds. There is a [conflict message](https://github.com/python-pillow/Pillow/actions/runs/12314943668/job/34372091532#step:8:126), and libjpeg-turbo is [detected](https://github.com/python-pillow/Pillow/actions/runs/12314943668/job/34372091532#step:11:42).
This explicitly installs jpeg-turbo on macOS.
> Test libjpeg-turbo on macOS

- .github/workflows/wheels-dependencies.sh
libXau 1.0.12 has been released - https://gitlab.freedesktop.org/xorg/lib/libxau/-/tags/libXau-1.0.12
> Updated libXau to 1.0.12

- winbuild/build_prepare.py
Changes
https://github.com/python-pillow/Pillow/blob/a7338f8ce7bc79b0b15df5c4711dcbebe1fbdea9/winbuild/build_prepare.py#L161-L163
to use .tar.gz, to match
https://github.com/python-pillow/Pillow/blob/a7338f8ce7bc79b0b15df5c4711dcbebe1fbdea9/.github/workflows/wheels-dependencies.sh#L73-L75
This means that only one file is needed in pillow-depends.
> Use .tar.gz zlib in Windows build to match macOS and Linux

- src/PIL/TiffImagePlugin.py
https://github.com/python-pillow/Pillow/blob/595bdf20579a68fba09d109b2a1830cdca6e82a2/src/PIL/TiffImagePlugin.py#L938-L939
If `size` is greater than 32, then this gives
> tag: unknown (8192) - type: byte (1) Tag Location: 94 - Data Location: 0 - value: <table: 159 bytes>
If it is not, then this gives
> tag: SamplesPerPixel (277) - type: long (4) - value: <table: b'\x92\x00\x12\x12' bytes>
I don't think we need to describe these bytes as a 'table'. It can be simplified to just
> tag: SamplesPerPixel (277) - type: long (4) - value: b'\x92\x00\x12\x12'>
> Do not describe raw data as a table

- .github/workflows/wheels-dependencies.sh
- winbuild/build_prepare.py
Helps #8603
It looks like https://sourceforge.net/projects/libjpeg-turbo/files/ is no longer being updated, so this switches the winbuild libjpeg-turbo URL to GitHub.
Testing further, I also found that the harfbuzz URL wasn't quite correct in the macOS and Linux dependencies script.
> Updated libjpeg-turbo and harfbuzz URLs

- winbuild/build_prepare.py
https://github.com/python-pillow/Pillow/blob/4304414473768e581bfb6cf519c8a1f9065ad1df/winbuild/build_prepare.py#L134-L135
It would seem like the "dir" could be derived from the "filename", simply by removing the file extension.
> Derive dir from filename if root is the same in winbuild

- winbuild/build_prepare.py
https://github.com/python-pillow/Pillow/actions/runs/12361558292/job/34498979321#step:11:12
> D:\a\Pillow\Pillow\winbuild\build_prepare.py:523: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
This PR sets the 'filter' argument for Python >= 3.12 (when it was [added](https://docs.python.org/3/library/tarfile.html#tarfile.TarFile.extractall)), set to 'data', the [default in Python 3.14.](https://docs.python.org/3/library/tarfile.html#extraction-filters)
> Extract tar files with "data" filter in Windows build scripts

- Tests/test_file_wmf.py
- src/PIL/WmfImagePlugin.py
Resolves #8597
The issue is concerned that a `ZeroDivisionError` may be raised if `self._inch` is zero.
https://github.com/python-pillow/Pillow/blob/a7338f8ce7bc79b0b15df5c4711dcbebe1fbdea9/src/PIL/WmfImagePlugin.py#L104-L107
This raises a `ValueError` of "Invalid inch" first.
> Raise ValueError when WMF inch is zero

- .ci/install.sh
The Ubuntu GitHub Actions builds have started failing, unable to find libjpeg - https://github.com/python-pillow/Pillow/actions/runs/12413240959/job/34674748066#step:10:326
This switches from the libjpeg-turbo-progs package to libjpeg-turbo8-dev.
> Install libjpeg-turbo8-dev

- src/PIL/Image.py
Suggested in https://github.com/python-pillow/Pillow/issues/6777#issuecomment-2555972847
> Replace constants with EXIF enums

- src/PIL/ExifTags.py
- src/PIL/Image.py
Resolves #8614
The issue has pointed out that the capitalization between
https://github.com/python-pillow/Pillow/blob/cf4110ff06b4d4e0ec43b4a9ca13a28b7d3b11d2/src/PIL/ExifTags.py#L156
and
https://github.com/python-pillow/Pillow/blob/cf4110ff06b4d4e0ec43b4a9ca13a28b7d3b11d2/src/PIL/ExifTags.py#L355
is inconsistent.
I've chosen `MakerNote`, to match https://www.loc.gov/preservation/digital/formats/content/tiff_tags.shtml
This also updates ExifTags to use hex values more consistently.
> Updated MakerNote capitalization

- src/_imagingcms.c
- src/display.c
Currently, the *_ALLOW_THREADS macros lead to odd indentation.
https://github.com/python-pillow/Pillow/blob/0e3f51dec67991e4dee53bcc149218d6c65cf820/src/_imagingcms.c#L349-L367
This PR consistently adds a semicolon after them to fix this.
> Fixed indentation

- src/PIL/SpiderImagePlugin.py
Two changes to `loadImageSeries`.
https://github.com/python-pillow/Pillow/blob/0e3f51dec67991e4dee53bcc149218d6c65cf820/src/PIL/SpiderImagePlugin.py#L214-L233
1. `convert2byte()` is a SpiderImageFile method, so the image must be a SPIDER image to call that
2. `convert2byte()` returns an `Image` instance, meaning that `loadImageSeries` returns a list of `Image`s, not `SpiderImageFile`s.
https://github.com/python-pillow/Pillow/blob/0e3f51dec67991e4dee53bcc149218d6c65cf820/src/PIL/SpiderImagePlugin.py#L189
> Corrected loadImageSeries type hint

- Tests/test_image_thumbnail.py
1. Uses monkeypatch for
https://github.com/python-pillow/Pillow/blob/f9767fb00fe78f118e36be2e7e6c816af07fe78b/Tests/test_image_thumbnail.py#L112-L120
2. Updates the type arguments in the mock method to match
https://github.com/python-pillow/Pillow/blob/f9767fb00fe78f118e36be2e7e6c816af07fe78b/src/PIL/Image.py#L1326-L1327
> Use monkeypatch

- Tests/test_pickle.py
- src/PIL/Image.py
- src/PIL/JpegImagePlugin.py
> Include JpegImageFile layers in pickle state

- Tests/test_file_bufrstub.py
- Tests/test_file_gribstub.py
- Tests/test_file_hdf5stub.py
Rather than setting the private `_handler` in our tests,
https://github.com/python-pillow/Pillow/blob/822ec3d05dfbaf2e3209c2b26e3392040e274975/Tests/test_file_bufrstub.py#L86
we can use the public method of `BufrStubImagePlugin.register_handler()`.
> Use register_handler

- src/PIL/TiffImagePlugin.py
- src/encode.c
Resolves #8522
#7053 found that "EXIFIFDOffset" tag 34665 was being unexpectedly treated as a TIFF_LONG8 by libtiff. To fix this, it cast many TIFF_LONGs to 64-bits.
This reverts that change. Instead, I found https://gitlab.com/libtiff/libtiff/-/blob/master/libtiff/tif_dirinfo.c#L152-164 explaining that this is special behaviour for the IFD tags.
>     /*--: EXIFIFD and GPSIFD specified as TIFF_LONG by Aware-Systems and not TIFF_IFD8 as in original LibTiff. However, for IFD-like tags,
>      * libtiff uses the data type TIFF_IFD8 in tiffFields[]-tag definition combined with a special handling procedure in order to write either
>      * a 32-bit value and the TIFF_IFD type-id into ClassicTIFF files or a 64-bit value and the TIFF_IFD8 type-id into BigTIFF files. */
>     {TIFFTAG_EXIFIFD, …
> Pass IFDs to libtiff as TIFF_LONG8

- Tests/test_imagefile.py
- src/PIL/TiffImagePlugin.py
Resolves #8530
#8319 changed
```python
xsize = int(self.tag_v2.get(IMAGEWIDTH))
ysize = int(self.tag_v2.get(IMAGELENGTH))
```
to
https://github.com/python-pillow/Pillow/blob/82199efbf77f369ad9b7c2c3759e08f517d9925b/src/PIL/TiffImagePlugin.py#L1436-L1440
This change seems reasonable, especially when you consider #4103.
However, if IMAGEWIDTH or IMAGELENGTH were missing, then `int(None)` previously raised a TypeError. TypeErrors are caught when opening images
https://github.com/python-pillow/Pillow/blob/82199efbf77f369ad9b7c2c3759e08f517d9925b/src/PIL/Image.py#L3497-L3506
but the ValueErrors are not.
So this change inadvertently broke feeding a TIFF image to `ImageFile.Parser`, which relies on OSError ([which UnidentifiedImageErrors …
> Raise UnidentifiedImageError when opening TIFF without dimensions

- setup.py
Despite
https://github.com/python-pillow/Pillow/blob/5bff2f3b2894ec6923c590d0c37b18177d0634bd/setup.py#L347
the `disable_platform_guessing` setting also affects macOS and Cygwin.
https://github.com/python-pillow/Pillow/blob/5bff2f3b2894ec6923c590d0c37b18177d0634bd/setup.py#L553-L566
> Platform guessing affects more than just Linux

- src/PIL/BlpImagePlugin.py
- src/PIL/DdsImagePlugin.py
- src/PIL/EpsImagePlugin.py
- src/PIL/FliImagePlugin.py
- src/PIL/FpxImagePlugin.py
- src/PIL/FtexImagePlugin.py
- src/PIL/GdImageFile.py
- src/PIL/ImageFile.py
- src/PIL/ImtImagePlugin.py
- src/PIL/MspImagePlugin.py
- src/PIL/PcdImagePlugin.py
- src/PIL/PixarImagePlugin.py
- src/PIL/QoiImagePlugin.py
- src/PIL/SpiderImagePlugin.py
- src/PIL/XVThumbImagePlugin.py
- src/PIL/XbmImagePlugin.py
- src/PIL/XpmImagePlugin.py
https://github.com/python-pillow/Pillow/blob/5bff2f3b2894ec6923c590d0c37b18177d0634bd/src/PIL/ImageFile.py#L98-L102
Adding defaults of 0 for offset and None for args will allow small simplifications to some instantiations of `ImageFile._Tile`.
An args value of `(mode, 0, 1)` can also be replaced by `mode`
https://github.com/python-pillow/Pillow/blob/5bff2f3b2894ec6923c590d0c37b18177d0634bd/src/PIL/ImageFile.py#L221-L222
> Added default values for _Tile offset and args

- src/PIL/ImageOps.py
`im.transpose()` loads the image, calls the core `transpose()` method and returns a new image instance.
https://github.com/python-pillow/Pillow/blob/5bff2f3b2894ec6923c590d0c37b18177d0634bd/src/PIL/Image.py#L2982-L2994
When `im.transpose()` is called from `ImageOps.exif_transpose()`, if it is `in_place`, then the image is already loaded, and the new image instance is quickly abandoned.
https://github.com/python-pillow/Pillow/blob/5bff2f3b2894ec6923c590d0c37b18177d0634bd/src/PIL/ImageOps.py#L701-L705
So this can be simplified to just calling the core `transpose()` method directly.
> Do not create new image when exif_transpose() is used in place

- Tests/test_file_container.py
#7656 set `ContainerIO` to receive `IO` as the type of the first argument.
https://github.com/python-pillow/Pillow/blob/f9767fb00fe78f118e36be2e7e6c816af07fe78b/src/PIL/ContainerIO.py#L29
Currently, test_file_container.py passes an image instance to it sometimes - the wrong type.
https://github.com/python-pillow/Pillow/blob/f9767fb00fe78f118e36be2e7e6c816af07fe78b/Tests/test_file_container.py#L18-L19
This PR fixes that, passing a file handle to it like the rest of the test file does.
https://github.com/python-pillow/Pillow/blob/f9767fb00fe78f118e36be2e7e6c816af07fe78b/Tests/test_file_container.py#L41-L42
> Pass file handle to ContainerIO

- src/PIL/ImageGrab.py
For `ImageGrab.grabclipboard()` on macOS, this skips writing the image to a temporary file, and instead receives the data through stdout.
> Do not use temporary file in ImageGrab.grabclipboard() on macOS

- src/libImaging/Jpeg2KDecode.c
The only time this variable is used, it is set to zero.
> Removed variable

- Tests/test_file_jpeg2k.py
- docs/releasenotes/11.1.0.rst
- src/PIL/Jpeg2KImagePlugin.py
#6909 added reading of JP2 comments. This adds reading of J2K comments as well.
JP2 comments are read from a ["Contiguous codestream box"](https://www.ics.uci.edu/~dan/class/267/papers/jpeg2000.pdf) that "contains a valid and complete JPEG 2000 codestream"
https://github.com/python-pillow/Pillow/blob/0e3f51dec67991e4dee53bcc149218d6c65cf820/src/PIL/Jpeg2KImagePlugin.py#L264-L265
and starts by skipping `hdr`.
https://github.com/python-pillow/Pillow/blob/0e3f51dec67991e4dee53bcc149218d6c65cf820/src/PIL/Jpeg2KImagePlugin.py#L298-L301
Reading from a J2K image,
https://github.com/python-pillow/Pillow/blob/0e3f51dec67991e4dee53bcc149218d6c65cf820/src/PIL/Jpeg2KImagePlugin.py#L252-L254
the `hdr` is already read.
https://github.com/python-pillow/Pillow/blob/0e3f51dec67991e4dee53bcc149218d6c65cf820 …
> Added reading of J2K comments

- docs/releasenotes/11.1.0.rst
> Added release notes for writing XMP bytes to JPEG and MPO

- Tests/test_image.py
- src/PIL/Image.py
Resolves #8634
The following code doesn't currently keep the new IFD tag when converting to bytes.
```python
exif = Image.Exif()
ifd = exif.get_ifd(0x8769)
ifd[36864] = b"0220"
exif.tobytes()
```
This is because the new IFD is added to `exif._ifds`, but not `exif._data`. It makes sense to not save it to `exif._data`, because a tag value for the IFD would indicate the IFD offset, which only has meaning in byte format. However, `exif._ifds` isn't checked when converting to bytes, so the new IFD is forgotten.
> Keep new IFDs when converting EXIF to bytes

- .github/workflows/wheels.yml
- .pre-commit-config.yaml
Follow on from https://github.com/python-pillow/Pillow/pull/8526.
Add zizmor to pre-commit, run the new version 0.10.0, and fix the one new thing it finds:
```
error[cache-poisoning]: runtime artifacts potentially vulnerable to a cache poisoning attack
--> /Users/hugo/github/Pillow/.github/workflows/wheels.yml:3:1
|
3 | / on:
4 | |   schedule:
...   |
29 | |       - "winbuild/fribidi.cmake"
30 | |   workflow_dispatch:
| |____________________^ generally used when publishing artifacts generated at runtime
31 |
...
263 |         uses: actions/setup-python@v5
264 | /       with:
265 | |         python-version: "3.x"
266 | |         cache: pip
267 | |         cache-dependency-path: "Makefile"
| |_________________________________________^ opt-in for caching here
|
= note: audit confidence → Low …
```
> Add zizmor to pre-commit and fix potential cache-poisoning in wheels workflow

- docs/deprecations.rst
- docs/releasenotes/11.1.0.rst
- src/PIL/ExifTags.py
#8615 replaced `ExifTags.IFD.Makernote` with `ExifTags.IFD.MakerNote`.
https://github.com/python-pillow/Pillow/issues/8614#issuecomment-2564126641 has requested that we keep `ExifTags.IFD.Makernote` for now, as a deprecated enum.
> Restored Makernote as a deprecated enum

- Tests/test_file_tiff.py
- docs/handbook/image-file-formats.rst
- docs/releasenotes/11.1.0.rst
- src/PIL/TiffImagePlugin.py
Resolves #4669
Adds a keyword argument to allow TIFF images to be saved as BigTIFF - `im.save("out.tiff", big_tiff=True)`
> Allow saving as BigTIFF

- docs/releasenotes/11.1.0.rst
- src/libImaging/ImPlatform.h
See #6516 for previous discussion about whether C99 can be the minimum version.
> Remove pre-C99 definitions

- Tests/test_file_blp.py
- src/PIL/BlpImagePlugin.py
Resolves #8650
https://www.hiveworkshop.com/threads/blp-specifications-wc3.279306/ describes the start of the 'BLP File Header' as
```
uint32_t magic;
uint32_t content;
if (version >= 2) {
uint8_t encodingType; // not documented
uint8_t alphaBits;
uint8_t sampleType; // not documented
uint8_t hasMipmaps;
} else {
uint32_t alphaBits;
}
```
However, we don't currently perform different behaviour for BLP1, and only treat the data as if it was BLP2.
https://github.com/python-pillow/Pillow/blob/aa0f4127b8040b82822808fa2037fea1a162d3c5/src/PIL/BlpImagePlugin.py#L300-L303
This PR fixes updates how the header data is handled for BLP1, for both reading and writing.
> Corrected BLP1 alpha depth handling

- .github/workflows/wheels-dependencies.sh
FreeType 2.13.3 is the latest version - https://freetype.org/
> Updated freetype to 2.13.3 in macOS and Linux wheels

- Tests/test_file_jpeg.py
- Tests/test_imageops.py
- src/PIL/ImageOps.py
Add overloads for `exif_transpose` to improve the return type based on the `in_place` argument.
https://github.com/python-pillow/Pillow/blob/66f5a3facc43170824eae69c7817c0ed6e2c908f/src/PIL/ImageOps.py#L682-L686
> Add overloads for exif_transpose

- .github/workflows/wheels-dependencies.sh
cifuzz is currently failing - https://github.com/python-pillow/Pillow/actions/runs/12588880904/job/35087652239#step:4:6114
> #8 198.9 make[1]: convert: Command not found
This is because I forgot to consider it in #8655
> Corrected installing ImageMagick on cifuzz

- .github/workflows/wheels-dependencies.sh
Alternative to #8658
We started mentioning giflib because it is used by `build_libwebp` - https://github.com/python-pillow/pillow-wheels/pull/98 / https://github.com/multi-build/multibuild/blob/42d761728d141d8462cd9943f4329f12fe62b155/library_builders.sh#L286-L293
However, https://developers.google.com/speed/webp/docs/compiling states
> Install the libjpeg, libpng, libtiff and libgif packages, needed to convert between JPEG, PNG, TIFF, GIF and WebP image formats.
We don't ask libwebp to convert between GIF and WebP formats, so the dependency can be removed by replacing `build_libwebp` with a direct `build_simple` call.
---
cifuzz still appears to be failing because just runs on main - https://github.com/google/oss-fuzz/blob/master/projects/pillow/Dockerfile
If I test one of our old …
> Removed giflib as webp dependency

- .ci/after_success.sh
- .github/workflows/test-docker.yml
The Ubuntu 22.04 amd64 job has started failing to report coverage - https://github.com/python-pillow/Pillow/actions/runs/12622957940/job/35171447617
> No data to report.
Thinking that `.coverage` might only exist within the Docker container, I copied `/Pillow` to the host, and that fixes it.
> Improved Docker coverage reporting

- .github/workflows/wheels.yml
In https://github.com/python-pillow/Pillow/pull/8672, I updated cibuildwheel settings in pyproject.toml, but that didn't trigger the wheels jobs.
This updates wheels.yml so that it would.
> Trigger wheel builds from changes in pyproject.toml

- Tests/test_file_jpeg.py
- src/PIL/features.py
- src/_imaging.c
- src/libImaging/JpegEncode.c
Resolves #539
Pillow will currently detect and use [MozJPEG](https://github.com/mozilla/mozjpeg) if it is installed. However,
1.  Pillow will [report](https://github.com/radarhere/Pillow/actions/runs/12558654968/job/35013138448#step:10:603)
> --- JPEG support ok, compiled for libjpeg-turbo 4.1.1
4.1.1 is not a [libjpeg-turbo version](https://github.com/libjpeg-turbo/libjpeg-turbo/releases). It is the [MozJPEG version](https://github.com/mozilla/mozjpeg/releases). So this PR detects MozJPEG, and updates the report to say 'compiled for mozjpeg 4.1.1'
I've also added `features.check_feature("mozjpeg")`
2. Testing in Ubuntu on GitHub Actions, there are currently [12 test failures](https://github.com/radarhere/Pillow/actions/runs/12558654968/job/35013138448#step:11:5915).
Our current default …
> Added compile-time mozjpeg feature flag

- Tests/test_file_png.py
https://github.com/python-pillow/Pillow/blob/aa0f4127b8040b82822808fa2037fea1a162d3c5/Tests/test_file_png.py#L617-L621
is testing
https://github.com/python-pillow/Pillow/blob/aa0f4127b8040b82822808fa2037fea1a162d3c5/src/PIL/PngImagePlugin.py#L821-L822
Since this is a `@property`, it can be accessed with just `im.text`
> PngImageFile text is a property

- Tests/test_file_ico.py
https://github.com/python-pillow/Pillow/blob/aa0f4127b8040b82822808fa2037fea1a162d3c5/Tests/test_file_ico.py#L255-L259
The result of opening hopper_mask.png is not used here, so it can be removed.
You might think that we are testing just opening the image, but that has already been done earlier in the file.
https://github.com/python-pillow/Pillow/blob/aa0f4127b8040b82822808fa2037fea1a162d3c5/Tests/test_file_ico.py#L32
> Removed unused image open

- Tests/test_file_libtiff.py
- src/PIL/TiffImagePlugin.py
OSError caused by decode error should use string argument to be in line with rest of module
* Changed an OSError raised in TiffImagePlugin.py during a decoder error to contain a str message as its argument, instead of directly passing the error code as an integer. This change brings this specific OSError in line with the way errors are raised in the rest of TiffImagePlugin.py and thus reduces surprise.
> Updated TIFF decode error message string

- Tests/test_file_spider.py
At https://app.codecov.io/gh/python-pillow/Pillow/blob/main/Tests%2Ftest_file_spider.py, you can see that the last line of
https://github.com/python-pillow/Pillow/blob/128f3f46d475de5ddf9859ae1e262287d0c126b6/Tests/test_file_spider.py#L154-L157
is not covered.
It is testing
https://github.com/python-pillow/Pillow/blob/128f3f46d475de5ddf9859ae1e262287d0c126b6/src/PIL/SpiderImagePlugin.py#L175-L178
This PR changes the test to directly call `seek()`, so all test lines are run, and test coverage is improved.
> Improved SPIDER test coverage

- Tests/test_file_tiff.py
- src/PIL/TiffImagePlugin.py
Sequel to #8642
Allows `big_tiff=True` to be used with `save_all=True` when writing TIFF images.
See https://web.archive.org/web/20240706160214/https://www.awaresystems.be/imaging/tiff/bigtiff.html for a description of the BigTIFF header structure.
> Allow saving multiple frames as BigTIFF

- .github/workflows/test-mingw.yml
MinGW has started failing on main - https://github.com/python-pillow/Pillow/actions/runs/12675616361/job/35338978926
> Run pacman -S --noconfirm \
> error: target not found: mingw-w64-x86_64-python3-pip
This PR switches from `mingw-w64-x86_64-python3-pip` to `mingw-w64-x86_64-python-pip`. See also https://packages.msys2.org/search?q=pip
> Use python-pip instead of python3-pip in MinGW

- .github/workflows/test-mingw.yml
Follow on from https://github.com/python-pillow/Pillow/pull/8678.
These aren't failing to install, but the `python3-*` names are virtual packages provided by the main, `python-*` packages:
* https://packages.msys2.org/search?t=pkg&q=numpy
* https://packages.msys2.org/packages/mingw-w64-x86_64-python-numpy provides:
* virtual package https://packages.msys2.org/packages/mingw-w64-x86_64-python3-numpy
* https://packages.msys2.org/search?q=olefile
* https://packages.msys2.org/packages/mingw-w64-x86_64-python-olefile provides:
* virtual package https://packages.msys2.org/packages/mingw-w64-x86_64-python3-olefile
Let's use the main names directly.
> Use python-numpy and python-olefile instead of virtual python3 packages

- Tests/test_image_access.py
At first, `test_embeddable` wasn't run in our CIs, only locally.
Then @nulano added the `xfail` in #6703, after reports that it didn't actually pass locally.
It has now started passing in Python 3.13 in our CIs.
> Removed xfail for test_embeddable on Python 3.13

- src/PIL/SpiderImagePlugin.py
The following check can be simplified.
https://github.com/python-pillow/Pillow/blob/8878511476959f576e50c993627fd4d6dc02d4dc/src/PIL/SpiderImagePlugin.py#L270-L271
See https://pillow.readthedocs.io/en/stable/handbook/concepts.html#modes for a list of modes.
> Only F mode starts with F

- Tests/test_image_access.py
It turns out that when `test_embeddable` was marked as passing in Python 3.13 in #8683, there was an error when using Windows x86 or AMD64 after building the wheels - https://github.com/python-pillow/Pillow/actions/runs/12721987647/job/35465533303#step:7:25500
> distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools"
Because this problem may occur in a local setup when running the test suite, this PR initializes the compiler (as seen two steps earlier in the error traceback) separately, and if that throws an error, before anything Pillow-related occurs, then the test is skipped.
With this change, the wheels start passing - https://github.com/radarhere/Pillow/actions/runs/12722505250/job/35466599838
> Skip test_embeddable if compiler cannot be initialized

- Tests/oss-fuzz/test_fuzzers.py
Two test-fuzzers.py changes
1. Improved the wording of https://github.com/python-pillow/Pillow/blob/f521a4be7db5fb1b6060d1dc48e69ee3bdec25ab/Tests/oss-fuzz/test_fuzzers.py#L42
2. Removed `UnidentifiedImageError` catching, when it would have already been caught by `OSError`, which `UnidentifiedImageError` inherits from.
> Improved comment

- Tests/test_image.py
- Tests/test_image_resize.py
1. https://github.com/python-pillow/Pillow/blob/af3b9042335a63f7c9269808c296e414d6a2a7fd/Tests/test_image.py#L670
should use a list, as per
https://github.com/python-pillow/Pillow/blob/af3b9042335a63f7c9269808c296e414d6a2a7fd/src/PIL/Image.py#L2138-L2140
2. https://github.com/python-pillow/Pillow/blob/af3b9042335a63f7c9269808c296e414d6a2a7fd/Tests/test_image.py#L773
should use a bytestring, as per https://github.com/python-pillow/Pillow/blob/af3b9042335a63f7c9269808c296e414d6a2a7fd/src/PIL/Image.py#L3952
3. https://github.com/python-pillow/Pillow/blob/af3b9042335a63f7c9269808c296e414d6a2a7fd/Tests/test_image_resize.py#L312 should use an int (or None) for the second argument, as per …
> Corrected argument types

- .github/workflows/wheels-test.ps1
Currently, Windows amd64 does not test the built wheels with NumPy - https://github.com/python-pillow/Pillow/actions/runs/12780081778/job/35625773713#step:7:7599
This adds it - https://github.com/python-pillow/Pillow/actions/runs/12807915960/job/35709512334?pr=8696#step:7:7611
> Test Windows amd64 wheels with NumPy

- .github/workflows/wheels.yml
GitHub has announced that arm64 Linux runners are now free for public repositories - https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
This means that we can use them, rather than QEMU, to build aarch64 wheels, greatly reducing the time that it takes to build all of our wheels.
While I'm here, I've also added 'pypy' to `CIBW_ENABLE`, since it will be turned off by default in cibuildwheel 3. You can see a warning about this at https://github.com/python-pillow/Pillow/actions/runs/12755221825 and read more at https://cibuildwheel.pypa.io/en/stable/options/#enable
> Use arm64 Linux runners for wheels

- Tests/test_image.py
- docs/deprecations.rst
- docs/releasenotes/11.2.0.rst
- docs/releasenotes/index.rst
- src/PIL/Image.py
- src/PIL/ImageFile.py
- src/PIL/_deprecate.py
[`get_child_images()`](https://github.com/python-pillow/Pillow/blob/3111e37bf437ecfdd19b31417aa7e843d742ed0b/src/PIL/Image.py#L1556) relies on `self.fp`, and since that only exists for an `ImageFile` and not an `Image`, I suggest moving it there. This isn't a strictly necessary change, so feel free to disagree.
After that, I've also made changes to fix two mypy errors. One is asserting that `fp` is not `None`, like #8617. The other is asserting that an Exif tag is an integer, to fix
> src/PIL/ImageFile.py:238: error: Argument 1 to "read" of "IO" has incompatible type "Optional[Any]"; expected "int"  [arg-type]
>                         data = self.fp.read(ifd.get(ExifTags.Base.JpegIFByteCount))
> …
> Moved get_child_images() to ImageFile

- .github/workflows/test-docker.yml
The ppc64le and s390x jobs have started experiencing segfaults.
https://github.com/python-pillow/Pillow/actions/runs/12938692000/job/36093724713#step:6:235
>   powerpc64le-linux-gnu-gcc: internal compiler error: Segmentation fault signal terminated program cc1
https://github.com/python-pillow/Pillow/actions/runs/12938692000/job/36093724972#step:6:249
>   s390x-linux-gnu-gcc: internal compiler error: Segmentation fault signal terminated program collect2
The problem started occurring with version 20250120.5.0 of the runner image. I've found [another user having segfaults recently](https://github.com/actions/runner-images/issues/10636#issuecomment-2610539943) who suggested switching back to Ubuntu 22.04, and changing the host does fix the problem. Perhaps this works as a temporary fix?
Edit: …
> Use Ubuntu 22.04 for 24.04 ppc64le and s390x

- depends/install_imagequant.sh
- docs/installation/building-from-source.rst
libimagequant 4.3.4 has been released - https://github.com/ImageOptim/libimagequant/releases/tag/4.3.4
> Updated libimagequant to 4.3.4

- Tests/test_file_libtiff.py
https://github.com/python-pillow/Pillow/actions/runs/12842724013/job/35813939701#step:6:5420
> Tests/test_file_libtiff.py::TestFileLibTiff::test_buffering[Tests/images/old-style-jpeg-compression-no-samplesperpixel.tif]
> Tests/test_file_libtiff.py::TestFileLibTiff::test_buffering[Tests/images/old-style-jpeg-compression-no-samplesperpixel.tif]
>   /vpy3/lib/python3.10/site-packages/_pytest/python.py:159: ResourceWarning: unclosed file <_io.BufferedReader name='Tests/images/old-style-jpeg-compression-no-samplesperpixel.tif'>
>     result = testfunction(**testargs)
>   Enable tracemalloc to get traceback where the object was allocated.
>   See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.
> 
> …
> Fixed unclosed file warnings

- src/PIL/BufrStubImagePlugin.py
- src/PIL/GribStubImagePlugin.py
- src/PIL/Hdf5StubImagePlugin.py
To restore the previous position after a read,
seek relative to the current position,
rather than using `tell()` and then seeking relative to the start of the file.
> Seek relative to current position

- Tests/test_file_tiff.py
Two exceptions are being raised in testing - https://github.com/python-pillow/Pillow/actions/runs/13051364088/job/36412180284#step:11:4911
```pytb
Tests/test_file_tiff.py::TestFileTiff::test_appending_tiff_writer_writelong
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/_pytest/unraisableexception.py:85: PytestUnraisableExceptionWarning: Exception ignored in: <PIL.TiffImagePlugin.AppendingTiffWriter object at 0x114c785e0>
File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/PIL/TiffImagePlugin.py", line 2212, in close
self.finalize()
~~~~~~~~~~~~~^^
File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/PIL/TiffImagePlugin.py", line 2082, in finalize
raise …
```
> Fixed exceptions when closing AppendingTiffWriter

- .github/workflows/macos-install.sh
#8140 added `--ignore-dependencies` when using brew to install libraqm on macos13, to avoid an error that our separate request for libjpeg was conflicting with jpeg-turbo.
Since #8596 stopping asking for libjpeg and switched to jpeg-turbo instead, the change from the first PR is no longer needed.
> Revert "Ignore brew dependencies for libraqm on macOS 13"

- Tests/test_file_gif.py
- Tests/test_image.py
- Tests/test_image_convert.py
- Tests/test_image_quantize.py
- Tests/test_imageops.py
- Tests/test_numpy.py
Updates some locations in the test suite where I think it is simpler (and clearer) to use
```python
im.getpixel((x, y))
```
rather than
```python
im.load()[x, y]
```
> Use getpixel() instead of load()

- src/PIL/ImageTransform.py
The `AffineTransform` docstring currently [states](https://pillow.readthedocs.io/en/stable/reference/ImageTransform.html#PIL.ImageTransform.AffineTransform)
> This function takes a 6-tuple (a, b, c, d, e, f) which contain the first two rows from an affine transform matrix. For each pixel (x, y) in the output image, the new value is taken from a position (a x + b y + c, d x + e y + f) in the input image, rounded to nearest pixel.
#8728 implied that this could be clearer
> Yes... I know that PIL takes the inverse
and #8731 is now requesting that we clarify that the inverse matrix is used.
For further reading, see https://stackabuse.com/affine-image-transformations-in-python-with-numpy-pillow-and-opencv/#affinetransformationswithpillow
> The `Image.transform(...)` method actually requires …
> Updated AffineTransform docstring to mention it uses the inverse matrix

- src/encode.c
Use [`p`](https://docs.python.org/3/c-api/arg.html#o-ampersand), since `irreversible` is only checking for a true value.
> Use boolean format argument for irreversible

- winbuild/build_prepare.py
Update our Windows build from 2.16.0 on the 'msvc' branch of libimagequant (which hasn't been updated in three years) to 4.3.4 on the 'main' branch.
> Updated libimagequant to 4.3.4 on Windows

- Tests/helper.py
https://github.com/python-pillow/Pillow/blob/ede46d47fc0a7352ba5d65fe031fdc77d3812b1e/Tests/helper.py#L345-L346
is never called.
> Removed unused test code

- src/PIL/BdfFontFile.py
Present since the 2010 PIL fork: https://github.com/python-pillow/Pillow/commit/9a640e3157150e35f17354517e8c6304fc428060
Commented out in 2015: https://github.com/python-pillow/Pillow/commit/cfaf95a5a44f21a1d30d84316bd74094c0b3494f https://github.com/python-pillow/Pillow/pull/1530
Commented-out code removed in 2018: https://github.com/python-pillow/Pillow/commit/37f10651bdd97df4ea907b772ead24d1c8efcea6 https://github.com/python-pillow/Pillow/pull/3333
> Remove unused `bdf_slant` and `bdf_spacing` variables

- Tests/test_file_gif.py
- Tests/test_format_hsv.py
- src/PIL/Image.py
- src/_imaging.c
The Python `Image._wedge` function is marked as "for debugging only".
The C `wedge` function does the same as the C `linear_gradient` function.
We call the Python `Image._wedge()` twice in tests. Both of these can be replaced with `Image.linear_gradient(mode="L")`.
Also a bit of test code cleanup:
* The global `data` variable isn't used in tests, let's remove it and save a redundant file load
* Rename an `open()` helper so as not to shadow the builtin
> Remove debug `Image._wedge`

- tox.ini
https://github.com/tox-dev/tox-uv is a tox plugin that uses uv instead of pip. By default, it doesn't install pip into the tox virtualenv.
We don't actually need to call `pip install .` here, because tox itself installs Pillow into its virtualenv.
And we don't need to run `make clean` either, because again tox installs into its own virtualenv, and the .so files are found at paths like:
```
./.tox/py313/lib/python3.13/site-packages/PIL/_imagingmath.cpython-313-darwin.so
./.tox/py313/lib/python3.13/site-packages/PIL/_imaging.cpython-313-darwin.so
./.tox/py313/lib/python3.13/site-packages/PIL/_webp.cpython-313-darwin.so
./.tox/py313/lib/python3.13/site-packages/PIL/_imagingcms.cpython-313-darwin.so
./.tox/py313/lib/python3.13/site-packages/PIL/_imagingft.cpython-313-darwin.so …
```
> Don't call `make clean` or `pip` in tox

- src/thirdparty/pythoncapi_compat.h
Update `pythoncapi_compat.h` to upstream commit
c84545f0e1e21757d4901f75c47333d25a3fcff0, which includes fixes necessary for Pillow to build against PyPy3.11.  Otherwise, it fails due to duplicate declarations:
```
In file included from src/encode.c:28:
src/thirdparty/pythoncapi_compat.h:295:1: error: static declaration of ‘PyThreadState_GetInterpreter’ follows non-static declaration
295 | PyThreadState_GetInterpreter(PyThreadState *tstate)
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/pypy3.11/Python.h:80,
from src/encode.c:26:
/usr/include/pypy3.11/pystate.h:35:33: note: previous declaration of ‘PyThreadState_GetInterpreter’ with type ‘PyInterpreterState *(PyThreadState *)’ {aka ‘struct _is *(struct _ts *)’}
35 | PyAPI_FUNC(PyInterpreterState*) …
```
> Update `pythoncapi_compat.h` to fix building with PyPy3.11

- .ci/install.sh
- .github/workflows/test-windows.yml
- .github/workflows/test.yml
PyPy v7.3.18 is out:
> This release includes a python 3.11 interpreter. We are labelling it "beta" because it is the first one. In the next release we will drop 3.10 and remove the "beta" label. 
https://pypy.org/posts/2025/02/pypy-v7318-release.html
---
https://github.com/python-pillow/Pillow/pull/8757 already updated `src/thirdparty/pythoncapi_compat.h`, this is how it looked without it:
https://github.com/hugovk/Pillow/actions/runs/13203645421/job/36861505207
We also need to skip NumPy for now:
```
[288/320] Compiling C object numpy/random/_mt19937.pypy311-pp73-darwin.so.p/meson-generated_numpy_random__mt19937.pyx.c.o
FAILED: numpy/random/_mt19937.pypy311-pp73-darwin.so.p/meson-generated_numpy_random__mt19937.pyx.c.o
cc -Inumpy/random/_mt19937.pypy311-pp73-darwin.so.p -Inumpy/random …
```
> Add PyPy3.11 to CI

- Tests/test_file_gif.py
- src/PIL/GifImagePlugin.py
Resolves #8746
When GIF frames are saved, Pillow crops out parts of frames i order to save space.
In #5557, I found https://legacy.imagemagick.org/Usage/anim_basics/#dispose. In the 'Dispose Background' section (a.k.a. disposal method 2), it states that
> As you can see as each overlaid frame is disposed of, that frames area is cleared to transparency, before the next image is overlaid.
> ...
> There is some thinking that rather than clearing the overlaid area to the transparent color, this disposal should clear it to the 'background' color meta-data setting stored in the GIF animation. In fact the old "Netscape" browser (version 2 and 3), did exactly that. But then it also failed to implement the 'Previous' dispose method correctly.
> On the other hand the initial canvas should also be …
> Only crop GIF frames when saving with disposal method 2 if transparency is present

- .github/workflows/wheels-dependencies.sh
Pass CFLAGS to `build_simple` directly, rather than setting it before and restoring it afterwards.
> Pass CFLAGS to build_simple directly

- src/_imaging.c
- src/_imagingcms.c
- src/_imagingft.c
- src/_webp.c
- src/decode.c
- src/display.c
- src/encode.c
- src/outline.c
- src/path.c
Borrowing an idea from #5201. Similar to #8734
As shown at https://docs.python.org/3/c-api/typeobj.html#examples, this uses member names to initialize `PyTypeObject`s, rather than being verbose and going through every member in sequence.
Also, I've removed specifying `tp_flags` as `Py_TPFLAGS_DEFAULT`, and so instead using the actual default from https://docs.python.org/3/c-api/typeobj.html#c.PyTypeObject.tp_flags, `Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE`. 
https://docs.python.org/3/c-api/typeobj.html#c.Py_TPFLAGS_BASETYPE
> **Py_TPFLAGS_BASETYPE**
> This bit is set when the type can be used as the base type of another type. If this bit is clear, the type cannot be subtyped (similar to a “final” class in Java).
I don't think we really need to specify that they can't be subtyped.
> Use member names to initialize PyTypeObjects

- Tests/test_file_tar.py
Adds tests for the uncovered errors from https://app.codecov.io/gh/python-pillow/Pillow/blob/main/src%2FPIL%2FTarIO.py
> Improve TarIO test coverage

- Tests/test_file_gbr.py
> Corrected type check

- Tests/test_file_sun.py
Adds coverage for the lines missing at https://app.codecov.io/gh/python-pillow/Pillow/blob/main/src%2FPIL%2FSunImagePlugin.py
> Improved SunImagePlugin coverage

- docs/conf.py
- pyproject.toml
#8354 added `("py:class", "_io.BytesIO")` to our Sphinx `nitpick_ignore` configuration.
I created https://github.com/sphinx-doc/sphinx/issues/12867 to ask that the need for this be investigated, and the fix has now been released in Sphinx 8.2.0.
> Update Sphinx to 8.2 to remove nitpick ignore

- Tests/test_fontfile.py
Adds coverage for the line missing at https://app.codecov.io/gh/python-pillow/Pillow/blob/main/src%2FPIL%2FFontFile.py
> Improved FontFile test coverage

- .github/workflows/wheels.yml
cibuildwheel v2.23.0 (https://github.com/python-pillow/Pillow/pull/8785) now also builds PyPy3.11 (https://github.com/pypa/cibuildwheel/releases/tag/v2.23.0).
https://github.com/python-pillow/Pillow/actions/runs/13608693136 created PyPy3.10 and 3.11 wheels for all:
```
./dist-ubuntu-24.04-arm-aarch64/pillow-11.2.0.dev0-pp310-pypy310_pp73-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
./dist-ubuntu-24.04-arm-aarch64/pillow-11.2.0.dev0-pp311-pypy311_pp73-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
./dist-ubuntu-latest-x86_64-manylinux_2_28/pillow-11.2.0.dev0-pp311-pypy311_pp73-manylinux_2_28_x86_64.whl
./dist-ubuntu-latest-x86_64-manylinux_2_28/pillow-11.2.0.dev0-pp310-pypy310_pp73-manylinux_2_28_x86_64.whl
./dist-ubuntu-24.04-arm-aarch64-manylinux_2_28/pillow-11.2.0.dev0-pp311-pypy31 …
```
> Build PyPy3.11 wheel for macOS 10.15 x86_64

- src/PIL/MicImagePlugin.py
- src/PIL/PsdImagePlugin.py
[`_seek_check`](https://github.com/python-pillow/Pillow/blob/d7d48df9af3b6177a62759cb00db391196f91f39/src/PIL/ImageFile.py#L425-L436) raises an `EOFError` if the user seeks outside of the image.
For MicImagePlugin and PsdImagePlugin, the call to that is enough, and no further error catching needs to be done to handle if seek will take us outside of the image - the `EOFError` would only be raised if a user deliberately changed `self.images` (or `self.layers` in the case of PsdImagePlugin).
https://github.com/python-pillow/Pillow/blob/d7d48df9af3b6177a62759cb00db391196f91f39/src/PIL/MicImagePlugin.py#L73-L80
> _seek_check already raises an EOFError

- .github/workflows/test-mingw.yml
Reverts #8724 
After that pull request temporarily removed mingw-w64-x86_64-libimagequant, I created https://github.com/msys2/MINGW-packages/issues/23316. That lead to https://github.com/msys2/MINGW-packages/pull/23387, and that fix has now propagated.
> Revert "Do not install libimagequant"

- src/PIL/ImageTk.py
https://github.com/python-pillow/Pillow/blob/d7d48df9af3b6177a62759cb00db391196f91f39/src/PIL/ImageTk.py#L268-L269
This helper is actually unused, so I suggest deprecating it.
> Removed ImageTk._show

- Tests/test_imagedraw.py
- src/PIL/ImageDraw.py
https://github.com/python-pillow/Pillow/blob/5d52ede584c5137f3a0b00be97dea8764404306b/src/PIL/ImageDraw.py#L44-L49
The `AttributeError` here would have happened previously if `WITH_ARROW` was not defined in C.
#8211 removed the `#ifdef WITH_ARROW` however, and so now, it is always defined.
> Image.core.outline will no longer raise an AttributeError

- Tests/test_file_gd.py
- src/PIL/GdImageFile.py
Currently,
```python
from PIL import GdImageFile
with GdImageFile.open("Tests/images/hopper.gd") as im:
im.save("out.png")
```
gives
With this PR, it gives
> Fixed loading GD images

- Tests/test_imageops.py
- src/PIL/ImageOps.py
> Corrected exif_transpose error when XMP is tuple

- docs/handbook/image-file-formats.rst
Requested in https://github.com/python-pillow/Pillow/issues/8787#issuecomment-2692681329 - a note in the documentation that JpegImagePlugin's `info["comment"]` is from the COM marker
https://github.com/python-pillow/Pillow/blob/bcdb68823330a527b88f6315ce4d7a68a8275320/src/PIL/JpegImagePlugin.py#L173-L179
and that this is distinct from the `UserComment` EXIF tag.
https://github.com/python-pillow/Pillow/blob/bcdb68823330a527b88f6315ce4d7a68a8275320/src/PIL/ExifTags.py#L157
> JPEG comments are from the COM marker

- Tests/test_font_bdf.py
Adds coverage for the lines missing at https://app.codecov.io/gh/python-pillow/Pillow/blob/main/src%2FPIL%2FBdfFontFile.py
> Improved BdfFontFile test coverage

- Tests/test_file_gif.py
- Tests/test_file_webp.py
- Tests/test_imagedraw.py
- Tests/test_imagepalette.py
- Tests/test_imagesequence.py
- Tests/test_pickle.py
- pyproject.toml
- src/PIL/IcnsImagePlugin.py
- src/PIL/Image.py
- src/PIL/ImageDraw.py
- src/PIL/ImageOps.py
- src/PIL/JpegImagePlugin.py
- src/PIL/TiffImagePlugin.py
Some small cleanups found with https://docs.astral.sh/ruff/rules/#flake8-pie-pie.
> Call `startswith`/`endswith` once with a tuple, and `range` without `start=0`

- Tests/test_file_tiff.py
- docs/handbook/image-file-formats.rst
- src/PIL/Image.py
- src/PIL/TiffImagePlugin.py
Resolves #8775
- #8627 added release notes for #8483, but this adds an example to the `save()` documentation. The issue felt that documentation could be improved for `encoderinfo`.
- Simplifies code needed to save tags to subsequent TIFF frames during `save_all` by removing the overrides for `encoderconfig` and `encoderinfo`.
> Allow encoderconfig and encoderinfo to be set for appended TIFF images

- Tests/test_file_jpeg2k.py
- src/libImaging/Jpeg2KDecode.c
> Support reading grayscale JPEG2000 images with 4 channels

- src/PIL/BlpImagePlugin.py
- src/PIL/Image.py
- src/PIL/ImageFile.py
- src/PIL/ImageFilter.py
- src/PIL/ImageShow.py
https://docs.python.org/3/library/abc.html#abc.abstractmethod
> **@abc.abstractmethod**
> A decorator indicating abstract methods.
>
> Using this decorator requires that the class’s metaclass is [ABCMeta](https://docs.python.org/3/library/abc.html#abc.ABCMeta) or is derived from it.
This is true. In main,
```pycon
>>> Image.ImagePointHandler()
<PIL.Image.ImagePointHandler object at 0x1044f93d0>
```
but once this PR changes the class to inherit from `abc.ABC`,
```pycon
>>> Image.ImagePointHandler()
TypeError: Can't instantiate abstract class ImagePointHandler with abstract method point
```
While I'm here, I'm also going to replace …
> Use ABCMeta in classes with abstractmethod

- Tests/test_file_apng.py
- Tests/test_file_fli.py
- Tests/test_file_gif.py
Three formats - [APNG](https://github.com/python-pillow/Pillow/blob/5ba72a9b54bd744724e4ec269268c16dd61bb472/src/PIL/PngImagePlugin.py#L855-L894), [FLI](https://github.com/python-pillow/Pillow/blob/5ba72a9b54bd744724e4ec269268c16dd61bb472/src/PIL/FliImagePlugin.py#L127-L147) and [GIF](https://github.com/python-pillow/Pillow/blob/5ba72a9b54bd744724e4ec269268c16dd61bb472/src/PIL/GifImagePlugin.py#L153-L186) raise an error if `_seek` is called to seek to frame that isn't the next one or the first one.
https://github.com/python-pillow/Pillow/blob/5ba72a9b54bd744724e4ec269268c16dd61bb472/src/PIL/FliImagePlugin.py#L127-L147
`_seek` shouldn't be called by end users, but ensuring it is called in the correct way internally would guard against bugs.
> Test using _seek to skip frames

- .github/renovate.json
https://docs.renovatebot.com/key-concepts/scheduling/#deprecated-breejslater-syntax says the wordy Later.js syntax is deprecated:
> This section explains the deprecated `@breejs/later` syntax. We plan to remove the `@breejs/later` library in a future major Renovate release if we can find a way to migrate all valid schedules to cron syntax. Due to this upcoming change, we strongly recommend you use `cron` schedules.
https://docs.renovatebot.com/key-concepts/scheduling/#recommended-cron-syntax says:
> For Cron schedules, you _must_ use the `*` wildcard for the minutes value, as Renovate doesn't support minute granularity. And the cron schedule must have five parts.
https://crontab.guru/#*_*_3_*_* says `* * 3 * *` is:
> “At every minute on day-of-month 3.”
> Replace deprecated Renovate schedule with cron syntax

- .ci/install.sh
The Ubuntu jobs in the 'Test' workflow don't currently have libtiff - https://github.com/python-pillow/Pillow/actions/runs/13799845698/job/38599859172#step:11:48
> Install libtiff-dev on Ubuntu GitHub Actions

- Tests/test_file_fli.py
- Tests/test_file_jpeg2k.py
- Tests/test_file_pcx.py
- Tests/test_font_bdf.py
Adds coverage for the lines missing at https://app.codecov.io/gh/python-pillow/Pillow/blob/main/src%2FPIL%2FFliImagePlugin.py
While I'm here, I've also updated some tests to move code outside of file handle context managers once we've finished interacting with the file handle.
> Improved FliImagePlugin test coverage

- docs/handbook/image-file-formats.rst
https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#dds
> Added in version 3.4.0: DXT3 images can be read in RGB mode
This is incorrect. DXT3 images are read in RGBA mode
https://github.com/python-pillow/Pillow/blob/5efcaa460372e91d9d18f2f812f590728903927a/src/PIL/DdsImagePlugin.py#L390-L391
https://github.com/python-pillow/Pillow/blob/5efcaa460372e91d9d18f2f812f590728903927a/Tests/test_file_dds.py#L68-L72
This has been the case since #2068
> DXT3 images are read in RGBA mode

- src/PIL/TiffImagePlugin.py
https://github.com/python-pillow/Pillow/pull/5919 reduced the load time for images that have consecutive tiles only differing in their offset. The test image in `test_timeout()` was a TIFF file, but the change was made more generally to ImageFile.
After https://github.com/python-pillow/docker-images/pull/232, QEMU jobs in the docker-images repository are slower, and `test_timeout()` is now timing out.
This PR adds specific logic to TiffImagePlugin. Each tile has the same width and height, so if that width and height covers the image and there are no layers involved, then only the last offset is needed.
> If every TIFF tile covers the image, only use the last offset

- Tests/test_file_dds.py
- setup.py
- src/PIL/DdsImagePlugin.py
- src/_imaging.c
- src/encode.c
- src/libImaging/BcnEncode.c
- src/libImaging/Imaging.h
Resolves #4864
Resolves #5499
With this, DXT1, DXT3, DXT5, BC2, BC3 and BC5 DDS images can be saved, with
```python
im.save("out.dds", pixel_format="DXT1")
```
rather than saving uncompressed data. I've also added the loading of BC2 and BC3 images, since they were missing.
See https://learn.microsoft.com/en-us/windows/win32/direct3d10/d3d10-graphics-programming-guide-resources-block-compression#bc1 for documentation (DXT1 is also known as BC1, DXT3 is also known as BC2 and DXT5 is also known as BC3).
For the BC2, BC3 and BC5 format, see https://learn.microsoft.com/en-us/windows/win32/direct3ddds/dx-graphics-dds-pguide#dds-file-layout
> If the DDS_PIXELFORMAT dwFlags is set to DDPF_FOURCC and dwFourCC is set to "DX10" an additional …
> Support saving DDS images with pixel formats

- src/PIL/Image.py
Removes the following comment from `Image.__init__()`
https://github.com/python-pillow/Pillow/blob/e66ebb64288f6deffe4ef54b624dcbf34570bb02/src/PIL/Image.py#L551
I think after #3203 and #7307, we've settled on the API for an image's mode and size.
> Removed FIXME

- .github/workflows/test.yml
Follow up to #8565
actions/setup-python has just been updated to include support for 3.13t, https://github.com/actions/setup-python/releases/tag/v5.5.0, so we can switch back to it instead of Quansight-Labs/setup-python
> Change back to actions/setup-python

- src/libImaging/BcnDecode.c
https://github.com/python-pillow/Pillow/blob/b8abded99b4f77db591e270836156349a074c3bc/src/libImaging/BcnDecode.c#L43-L49
https://github.com/python-pillow/Pillow/blob/b8abded99b4f77db591e270836156349a074c3bc/src/libImaging/BcnDecode.c#L106-L109
With a little maths and changing the loop of size 16 to two range loops of size 4 each, this code can be changed to avoid the UINT32. If you think that changing the size of the loop is misleading to the reality of the image, it's not - looking at https://learn.microsoft.com/en-us/windows/win32/direct3d10/d3d10-graphics-programming-guide-resources-block-compression#bc1, you can see that the LUT is actually representing a 4x4 block.
> Do not convert BC1 LUT to UINT32

- Tests/images/full_gimp_palette.gpl
- Tests/test_file_gimppalette.py
- src/PIL/GimpPaletteFile.py
Resolves #6639
#6640 has concerns about Pillow's limits when reading a Gimp palette file.
https://github.com/python-pillow/Pillow/blob/e66ebb64288f6deffe4ef54b624dcbf34570bb02/src/PIL/GimpPaletteFile.py#L33-L34
1. Pillow reads at most 256 lines after the first header line. This means that Pillow can't read more than 256 colours, which [apparently might be the case in Gimp palette files](https://github.com/jsbueno/Pillow/pull/1#discussion_r988488865) and the [spec](https://developer.gimp.org/core/standards/gpl/) doesn't say otherwise. I'm [concerned](https://github.com/python-pillow/Pillow/issues/6639#issuecomment-1269311418) about the idea of creating a "palette" that is larger than what our ImagePalette can handle.
2. The fact that only 256 lines are read after the first header line also …
>  Added GimpPaletteFile frombytes() to allow for unlimited parsing

- Tests/test_file_libtiff.py
- src/libImaging/TiffDecode.c
Resolves #8554
When a TIFF image is YCbCr, Pillow calls libtiff's `TIFFRGBAImageBegin`
https://github.com/python-pillow/Pillow/blob/5bff2f3b2894ec6923c590d0c37b18177d0634bd/src/libImaging/TiffDecode.c#L729
https://github.com/python-pillow/Pillow/blob/5bff2f3b2894ec6923c590d0c37b18177d0634bd/src/libImaging/TiffDecode.c#L739-L740
https://github.com/python-pillow/Pillow/blob/5bff2f3b2894ec6923c590d0c37b18177d0634bd/src/libImaging/TiffDecode.c#L295
Looking at that libtiff code, it then calls either [`PickContigCase` or `PickSeparateCase`](https://gitlab.com/libtiff/libtiff/-/blob/master/libtiff/tif_getimage.c#L564-574). Those set `img->get` to [`gtTileContig`, `gtStripContig`](https://gitlab.com/libtiff/libtiff/-/blob/master/libtiff/tif_getimage.c#L2935), [`gtTileSeparate` or …
> Fixed orientation when opening YCbCr TIFF images

- Tests/test_file_bmp.py
- src/PIL/BmpImagePlugin.py
Resolves #8594
https://learn.microsoft.com/en-us/windows/win32/wmdm/-bitmapinfoheader describes 32 bitcount as
> The bitmap has a maximum of 2^32 colors. If the biCompression member is BI_RGB, the bmiColors member is NULL. Each DWORD in the bitmap array represents the relative intensities of blue, green, and red, respectively, for a pixel. The high byte in each DWORD is not used.
where BI_RGB is what we call RAW compression. It is saying that the fourth channel is unused, as Pillow currently treats it as such for DIB images.
However, the issue has found that some images do not follow the documentation and store alpha data in the fourth channel anyway.
Because this is not the documented behaviour, it seems possible that using it anyway could introduce problems. If the user thinks that …
> Added USE_RAW_ALPHA for BMP images

- Tests/test_imagefile.py
- src/PIL/ImageFile.py
Resolves #8607
At the moment, ImageFile reads from files in `MAXBLOCK` chunks (unless `pulls_fd` is in use). There is no problem with this if there is only one tile. If there are multiple tiles however, that may be smaller than `MAXBLOCK`, then the size of the read operation can be reduced - by stopping the read operation before the next tile starts.
> Only read until the offset of the next tile

- Tests/test_file_palm.py
- src/PIL/PalmImagePlugin.py
Removes an xfail
https://github.com/python-pillow/Pillow/blob/8878511476959f576e50c993627fd4d6dc02d4dc/Tests/test_file_palm.py#L58-L59
with the following changes
1. Always save the colormap for a P mode image, because
https://github.com/python-pillow/Pillow/blob/8878511476959f576e50c993627fd4d6dc02d4dc/src/PIL/PalmImagePlugin.py#L118-L120
is an odd assumption.
2. Use OR instead of AND to apply the custom colormap flag
https://github.com/python-pillow/Pillow/blob/8878511476959f576e50c993627fd4d6dc02d4dc/src/PIL/PalmImagePlugin.py#L177
3. Do not presume that palettes are 256 in length.
At first glance, you might think that
https://github.com/python-pillow/Pillow/blob/8878511476959f576e50c993627fd4d6dc02d4dc/src/PIL/PalmImagePlugin.py#L209-L214
offered support for saving RGBA palettes. But …
> Corrected Palm P mode save

- src/PIL/TarIO.py
When testing TarIO errors, the file handle is not closed - https://github.com/python-pillow/Pillow/actions/runs/14155530774/job/39654267057?pr=8844#step:6:5611
```
Tests/test_file_tar.py::test_unexpected_end
/Pillow/Tests/test_file_tar.py:38: ResourceWarning: unclosed file <_io.BufferedReader name='/tmp/pytest-of-pillow/pytest-0/test_unexpected_end0/temp.tar'>
with pytest.raises(OSError, match="unexpected end of tar file"):
Enable tracemalloc to get traceback where the object was allocated.
See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.
Tests/test_file_tar.py::test_cannot_find_subfile
/Pillow/Tests/test_file_tar.py:44: ResourceWarning: unclosed file <_io.BufferedReader name='Tests/images/hopper.tar'>
with pytest.raises(OSError, …
```
> Close TarIO file handle on error

- .github/workflows/wheels-dependencies.sh
- Tests/check_wheel.py
#8500 switched to zlib-ng in our wheels. However, #8750 has reported that wheels now segfault on macOS 10.13 and 10.14.
https://github.com/zlib-ng/zlib-ng/issues/1877 was created to investigate this, and there is now a proposed fix in https://github.com/zlib-ng/zlib-ng/pull/1878.
However, in case it is not merged and released before Pillow 11.2.0, this PR temporarily reverts to using zlib on macOS < 10.15.
> Revert to zlib on macOS < 10.15

- .github/workflows/wheels-dependencies.sh
Sequel to #8836
After finding a Makefile error when updating xz to 5.8.0 on manylinux2014, I asked in the xz repository about this - https://github.com/tukaani-project/xz/issues/170#issuecomment-2763301018
The initial response suggested changing our build to handle the fact that xz 5.8.0 no longer worked out of the box for our environment. I didn't immediately consider manylinux2014 a priority, and thought we could live with the older version until Amazon Linux 2 goes EOL in [a year and a bit](https://aws.amazon.com/amazon-linux-2/faqs/) (if Amazon doesn't extend support again) and we drop manylinux2014 support.
However, it turns out that xz would [like us to use the latest version](https://github.com/tukaani-project/xz/issues/170#issuecomment-2763394507). So this PR uses one of their …
> Updated xz to 5.8.0 on manylinux2014 by removing po4a dependency

- winbuild/build_prepare.py
libtiff has started failing to build in main on WIndows - https://github.com/python-pillow/Pillow/actions/runs/14187037544/job/39744130790
This would be due to the recent release of cmake 4 - https://github.com/Kitware/CMake/releases/tag/v4.0.0
https://cmake.org/cmake/help/latest/release/4.0.html#deprecated-and-removed-features
> Compatibility with versions of CMake older than 3.5 has been removed.
> Allow cmake<4 when building libavif and libtiff

- docs/releasenotes/11.2.0.rst
This is the first paragraph of https://pillow.readthedocs.io/en/latest/reference/arrow_support.html and part of https://pillow.readthedocs.io/en/latest/reference/Image.html#PIL.Image.fromarray
> Added release notes for #8330

- Tests/test_image.py
- src/PIL/Image.py
Resolves #8828
#3724 ensured that an image was mutable when saving, to fix the scenario where a user is opening an image from a file and then saving it back to the same file.
This reverses that change slightly, only ensuring an image is mutable when saving **if it has the same filename as the opened image**.
> Only change readonly if saved filename matches opened filename

- .github/workflows/wheels-dependencies.sh
https://github.com/python-pillow/Pillow/blob/7c56b383ff3ef952854306bbe2c48c5e21066b9c/.github/workflows/wheels-dependencies.sh#L83-L87
can be replaced with
```bash
build_github zlib-ng/zlib-ng $ZLIB_NG_VERSION --zlib-compat
```
thanks to [`build_github()`](https://github.com/multi-build/multibuild/blob/42d761728d141d8462cd9943f4329f12fe62b155/library_builders.sh#L77-L92), which anticipated this scenario.
> Use multibuild build_github

- Tests/test_file_avif.py
- src/_avif.c
This implements a fix for the issue identified in AOMediaCodec/libavif#2727 and fixed in AOMediaCodec/libavif#2729. The code in Pillow that converts irot and imir properties to EXIF orientation was repurposed from libavif, so it suffers the same bug.
> Fixed conversion of AVIF image rotation property to EXIF orientation

- .github/workflows/wheels-dependencies.sh
- winbuild/build_prepare.py
xz 5.8.1 has been released - https://github.com/tukaani-project/xz/releases/tag/v5.8.1
This updates it, except for on 32-bit Windows. That would fail with https://github.com/radarhere/Pillow/actions/runs/14264115010/job/39981991680#step:30:1096
> E           OSError: decoder error -2
> 
> C:\hostedtoolcache\windows\Python\3.9.13\x86\lib\site-packages\PIL\TiffImagePlugin.py:1416: OSError
> ---------------------------- Captured stderr call -----------------------------
> LZMADecode: Decoding error at scanline 0, data is corrupt.
> LZMADecode: Not enough data at scanline 0 (short 49152 bytes).
I initially reported this to libtiff at https://gitlab.com/libtiff/libtiff/-/issues/677, but have since moved on and reported it directly to xz at https://github.com/tukaani-project/xz/issues/171
> Updated xz to 5.8.1

- docs/handbook/image-file-formats.rst
* XV Thumbnails was under "Write only formats", moved to "Read only formats"
> Move XV Thumbnails to read only section

- .github/workflows/wheels.yml
Windows arm64 runners are now in public preview - https://github.blog/changelog/2025-04-14-windows-arm64-hosted-runners-now-available-in-public-preview/
> Build Windows arm64 wheels on arm64 runner

- docs/handbook/concepts.rst
- docs/reference/block_allocator.rst
See https://pillow.readthedocs.io/en/latest/handbook/concepts.html#modes vs https://pillow--8915.org.readthedocs.build/en/8915/handbook/concepts.html#modes
and
https://pillow.readthedocs.io/en/latest/reference/block_allocator.html#memory-pools vs https://pillow--8915.org.readthedocs.build/en/8915/reference/block_allocator.html#memory-pools
> Remove indentation from lists

- docs/releasenotes/10.1.0.rst
- src/PIL/ImageFont.py
https://github.com/python-pillow/Pillow/actions/runs/14566099360/job/40855558228#step:8:727
> /home/runner/work/Pillow/Pillow/docs/reference/ImageFont.rst:1: WARNING: redirect  https://dotcolon.net/font/aileron - permanently to https://dotcolon.net/fonts/aileron/
> Update redirected URL

- docs/handbook/appendices.rst
- docs/handbook/third-party-plugins.rst
Resolves #8909
I suggest adding another appendix, 'Third Party Plugins', to sit before 'Writing Your Own Image Plugin'.
['Writing Your Own Image Plugin'](https://pillow.readthedocs.io/en/stable/handbook/writing-your-own-image-plugin.html) starts with
> Pillow uses a plugin model which allows you to add your own decoders and encoders to the library, without any changes to the library itself.
I've closely mirrored that, and then written a list with approximately the start of each project's description.
This uses the list of PyPI projects from https://github.com/python-pillow/Pillow/issues/8892, with the exceptions of
- https://pypi.org/project/pillow-stackblur/, because it doesn’t appear to offer additional format support. Feel free to tell me to rework this so that it’s not just about …
> Add list of third party plugins

- src/PIL/AvifImagePlugin.py
https://github.com/python-pillow/Pillow/blob/58e48745cc7b6c6f7dd26a50fe68d1a82ea51562/src/PIL/AvifImagePlugin.py#L19-L20
As per https://pillow.readthedocs.io/en/stable/installation/building-from-source.html#external-libraries though, Pillow only supports libavif 1.0.0 or greater.
> **libavif** provides support for the AVIF format.
> - Pillow requires libavif version **1.0.0** or greater.
So the comment can be removed.
> Remove outdated comment

- Tests/test_pickle.py
- src/PIL/ImageFile.py
Resolves #8935
A user pickled an imageFile before #8859 added `self.filename` to the state, and would like to unpickle the data with the latest version of Pillow.
> Allow loading ImageFile state from Pillow < 11.2.1

- docs/Makefile
- docs/handbook/appendices.rst
- docs/handbook/third-party-plugins.rst
Mainly to remove duplication.
Some functional changes:
* Use `--jobs auto` for all builders, not just `linkcheck`. This speeds `make -C docs clean html` for me from 25 seconds to 14 seconds.
* Use `--fail-on-warning --keep-going` for all builders, not just `html`.
> Refactor docs `Makefile`

- .github/workflows/test-windows.yml
- Tests/test_image_resample.py
- setup.py
1. A test has started failing now that an error message has changed in Python 3.14
https://github.com/python-pillow/Pillow/actions/runs/14903027962/job/41859109942#step:11:3834
> E       AssertionError: Regex pattern did not match.
> E        Regex: 'must be sequence of length 4'
> E        Input: 'argument 3 must be tuple of length 4, not 2'
2. An error has started occurring when building PyQt6 on Python 3.14 - https://github.com/python-pillow/Pillow/actions/runs/14903027971/job/41859749652#step:8:12
Let's skip it for now.
3. Those changes then triggers our [Windows message about unsupported Python versions](https://github.com/python-pillow/Pillow/blob/d02f7868732cdacc227dd794f6ff84bd6f1858c9/setup.py#L49) - https://github.com/python-pillow/Pillow/actions/runs/14906195788/job/41869036883? …
> Improved support for Python 3.14

- src/PIL/WmfImagePlugin.py
WmfImagePlugin initially reads 80 bytes.
https://github.com/python-pillow/Pillow/blob/3c71559804e661a5f727e2007a5be51f26d9af27/src/PIL/WmfImagePlugin.py#L84
However, the furthest that is used is byte 44.
https://github.com/python-pillow/Pillow/blob/3c71559804e661a5f727e2007a5be51f26d9af27/src/PIL/WmfImagePlugin.py#L116
So the number of bytes can be reduced.
> Reduced number of bytes read in WMF header

- .ci/install.sh
In #8949, I removed `CMAKE_POLICY_VERSION_MINIMUM=3.5` in winbuild, as it is no longer necessary with the updated version, but forgot about install.sh.
If you're interested in the background, see https://github.com/python-pillow/Pillow/pull/5201#issuecomment-2770692611 for a discussion between a libavif maintainer and myself.
> Removed CMAKE_POLICY_VERSION_MINIMUM=3.5 for libavif

- Tests/helper.py
- Tests/test_file_eps.py
- Tests/test_file_fli.py
- Tests/test_file_jpeg.py
- Tests/test_file_pdf.py
- Tests/test_file_tiff.py
- Tests/test_image.py
- Tests/test_imagefontpil.py
It would seem good to me to still let valgrind run its checks if we can. So rather than skipping them completely, run them, but don't timeout.
> Run slow tests on valgrind, but without timeout

- src/PIL/Image.py
Alternative to #8777
In that PR, a user read https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.tobytes
and interpreted it as "`tobytes()` will return data exactly matching Pillow's internal storage".
This isn't always true for the raw encoder, and it definitely isn't true for the other encoders.
I've tried to clarify that here by updating the documentation to say that the method returns "raw image data **derived** from Pillow's internal storage". I've also mentioned Pack.c as the user [suggested](https://github.com/python-pillow/Pillow/pull/8777#issuecomment-2689336609).
> Mention that tobytes() with the raw encoder uses Pack.c

- src/PIL/MpegImagePlugin.py
https://github.com/python-pillow/Pillow/blob/03e7871afdb8f558cddc10cc9013e1db143298d9/src/PIL/_binary.py#L21-L22
https://github.com/python-pillow/Pillow/blob/03e7871afdb8f558cddc10cc9013e1db143298d9/src/PIL/MpegImagePlugin.py#L31-L39
`c < 0` will never be True. The value can range from 0 to 255, but will never be less than zero.
> Removed unreachable code

- src/PIL/Image.py
`tobytes()` sets a buffer size when encoding.
https://github.com/python-pillow/Pillow/blob/3d4119521c853e1014012f73fdf9b2a8dc137722/src/PIL/Image.py#L803
ImageFile also does this when saving an image, but the 65536 value is configurable.
https://github.com/python-pillow/Pillow/blob/3d4119521c853e1014012f73fdf9b2a8dc137722/src/PIL/ImageFile.py#L49
https://github.com/python-pillow/Pillow/blob/3d4119521c853e1014012f73fdf9b2a8dc137722/src/PIL/ImageFile.py#L641
Perhaps we should use `ImageFile.MAXBLOCK` in `tobytes()` as well?
> Use ImageFile.MAXBLOCK in tobytes()

- Tests/test_tiff_crashes.py
- src/PIL/TiffImagePlugin.py
- src/map.c
Resolves #8961
I've used the test image from the issue, but due to a larger file size, I've placed it in https://github.com/python-pillow/test-images/pull/7. This will fail without that pull request.
Using memory mapping to load one frame, and then not using it for the next frame, is causing a problem. This would be because memory mapping is replacing the core image.
https://github.com/python-pillow/Pillow/blob/3c71559804e661a5f727e2007a5be51f26d9af27/src/PIL/ImageFile.py#L324-L326
But TiffImagePlugin tries to keep using it afterwards.
https://github.com/python-pillow/Pillow/blob/3c71559804e661a5f727e2007a5be51f26d9af27/src/PIL/TiffImagePlugin.py#L1214-L1223
> Clear TIFF core image if memory mapping was used for last load

- Tests/test_file_ppm.py
- src/PIL/PpmImagePlugin.py
Resolves #8956
https://github.com/python-pillow/Pillow/blob/3c71559804e661a5f727e2007a5be51f26d9af27/src/PIL/PpmImagePlugin.py#L97-L98
The issue found a `token` value that could not be decoded, so this PR changes the error message to use bytes instead.
> Do not decode bytes in PPM error message

- src/PIL/PcxImagePlugin.py
1. PcxImagePlugin initially reads 128 bytes
https://github.com/python-pillow/Pillow/blob/8e5a15bab746f87822b75cd47db17ae0174ed05e/src/PIL/PcxImagePlugin.py#L57
But the header only uses up to 68 bytes.
https://github.com/python-pillow/Pillow/blob/8e5a15bab746f87822b75cd47db17ae0174ed05e/src/PIL/PcxImagePlugin.py#L73
So the number of bytes can be reduced.
2. After seeking to the end of the file for one type of header, PcxImagePlugin seeks back to the start.
https://github.com/python-pillow/Pillow/blob/8e5a15bab746f87822b75cd47db17ae0174ed05e/src/PIL/PcxImagePlugin.py#L96-L105
This is unnecessary, since `load()` will seek to the tile offset.
> Reduce number of bytes read for PCX header

- .github/workflows/test-windows.yml
Re: https://github.com/python-pillow/Pillow/pull/9014#issuecomment-2969799037
Some Windows jobs are failing because it's Python 3.13.4, which incorrectly tries to link to the threaded version. See https://github.com/python/cpython/issues/135151
This has been fixed in [this week's 3.13.5 release,](https://discuss.python.org/t/python-3-13-5-is-now-available-yes-really/95211) but it's not necessarily in the default CI images yet, so let's specify `>= 3.13.5` to ensure the new one is always installed on-demand.
We can revert this at some point in the future.
> CI: Require Python >= 3.13.5 on Windows

- Tests/test_file_png.py
- docs/deprecations.rst
- docs/releasenotes/11.3.0.rst
- src/PIL/PngImagePlugin.py
- src/PIL/_deprecate.py
Resolves #9022
PNG images can only have a maximum of 16 bits per channel - https://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html
> Bit depth is a single-byte integer giving the number of bits per sample or per palette index (not per pixel). Valid values are 1, 2, 4, 8, and 16, although not all values are allowed for all color types.
However, Pillow still allows saving PNG images as I mode, by clipping the data.
The issue has requested that we prevent this automatic transformation, so this PR deprecates it.
> Deprecate saving I mode images as PNG

- winbuild/build_prepare.py
Update the winbuild libavif URL to match https://github.com/python-pillow/Pillow/blob/cda26be10e93472cca7cc2c07c045037572d9b38/.github/workflows/wheels-dependencies.sh#L135
> Use same AVIF URL when fetching dependency

- src/libImaging/TiffDecode.c
Alternative to #8992
I've found that since #8954 was merged, there have been intermittent errors.
- 'cannot identify image file' - https://github.com/python-pillow/Pillow/actions/runs/15371601710/job/43251458128
- 'attempt to seek outside sequence' - https://github.com/python-pillow/Pillow/actions/runs/15370070907/job/43247953625
- 'unrecognized data stream contents when reading image file' - https://github.com/python-pillow/Pillow/actions/runs/15370070907/job/43247953635
Testing, I find that the minimal change to fix the problem is to restore one of the calls to `TIFFCleanup`, and then to set `clientstate->tiff = NULL` to [prevent](https://github.com/python-pillow/Pillow/blob/f3b05d6fab2a8fb0db033fc507d0d6f19ed2330e/src/libImaging/TiffDecode.c#L936-L940) `ImagingLibTiffEncodeCleanup` …
> Fix libtiff cleanup

- setup.py
libtiff takes priority over tiff on Windows and macOS
https://github.com/python-pillow/Pillow/blob/2954964cd2b70c463d75bd7f828c7bb7f3802bf2/setup.py#L757-L762
This rearranges the code so that if it is found, we skip searching for tiff.
> Search for libtiff library file first on Windows and macOS

- Tests/test_file_jpeg.py
Resolves #9024
The issue found that with libjpeg, rather than libjpeg-turbo, a test checking for a DHT marker is not found.
From https://en.wikipedia.org/wiki/JPEG, a DHT marker is
> Define Huffman Table(s)
and it
> Specifies one or more Huffman tables.
From https://github.com/libjpeg-turbo/libjpeg-turbo,
> libjpeg-turbo can still outperform libjpeg by a significant amount, by virtue of its highly-optimized Huffman coding routines
It doesn't seem unreasonable that libjpeg-turbo would have different output regarding Huffman tables.
This PR skips checking that marker if libjpeg-turbo is not used.
> Only check DHT marker for libjpeg-turbo

- Tests/test_file_tiff.py
- src/PIL/TiffImagePlugin.py
https://github.com/python-pillow/Pillow/issues/861#issuecomment-2967698512 requests that we support saving I;16L TIFF images.
While there, I noticed that [`SAVE_INFO`](https://github.com/python-pillow/Pillow/blob/2e5117305b86852f3cd21fe604eb966e09ec308e/src/PIL/TiffImagePlugin.py#L1673C1-L1700) has entries for a few modes that [don't exist](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#modes) - I;16S, I;32BS, I;16BS and F;32BF. It's only use is to provide information for the mode of an image, so I've removed those entries.
> Support saving I;16L TIFF images

- .pre-commit-config.yaml
With ruff-pre-commit 0.11.10, https://github.com/astral-sh/ruff-pre-commit/pull/124 was included, which prefers `ruff-check` to the `ruff` ID in pre-commit.
> Update ruff pre-commit ID

- Tests/test_file_gif.py
- Tests/test_image.py
- Tests/test_image_quantize.py
- Tests/test_image_transform.py
This is part of https://github.com/python-pillow/Pillow/pull/8362 - I'm hoping to break down that PR into easier-to-review chunks.
Image's `palette` may be `None`
```pycon
>>> im = Image.new("RGB", (1, 1))
>>> im.palette is None
True
```
So before using it, let's assert that it isn't `None`.
> Assert palette is not None

- .coveragerc
- Makefile
- checks/check_jpeg_leaks.py
- codecov.yml
Updates after #9030 moved some scripts from the 'Tests' directory into a new 'checks' directory
> Updated check script paths

- docs/releasenotes/11.3.0.rst
As a general rule I think we should acknowledge when significant contribtions come from outside the core team. We know the core team does a lot of work (thank you!) but it's not always obvious when significant contributions come from outside the core team.
In the old change log, we had ACKs via `[radarhere]` syntax which I miss. I don't expect we'll start using the old change log again but maybe we can make a note in the release notes to include such ACKs as needed and appropriate.
Fixes missing acknowledgments.
- Acknowledge non-core team contributors for significant contributions.
> Thanks, folks!

- docs/handbook/concepts.rst
- docs/reference/ImageDraw.rst
- docs/reference/PixelAccess.rst
- src/PIL/Image.py
Resolves #9049
The user in the issue was surprised by how `putdata()` parses a single integer into pixel values for a multichannel image.
This behaviour occurs for several different methods, so I've added a new section to Concepts.
> Added "Colors" to concepts

- Tests/test_file_libtiff.py
I've noticed an unclosed file warning - https://github.com/python-pillow/Pillow/actions/runs/15993042615/job/45110055855#step:6:5751
> Tests/test_file_libtiff.py::TestFileLibTiff::test_realloc_overflow
>   <frozen abc>:117: ResourceWarning: unclosed file <_io.FileIO name='Tests/images/hopper.ppm' mode='rb' closefd=True>
> Fix unclosed file warning

- docs/deprecations.rst
- docs/installation/building-from-source.rst
- src/PIL/features.py
Sequel to #9053
1. https://pillow.readthedocs.io/en/latest/installation/building-from-source.html#external-libraries lists
> **libtiff** provides compressed TIFF functionality
> Pillow has been tested with libtiff versions **3.x** and **4.0-4.7.0**
Since support for libtiff < 4 was removed, this should be updated.
2. In the PR, I added `hints` to the removed section, but managed to leave it in the deprecated section.
3. #8213 added a bool flag value for deprecated features. I forgot to remove handling for this.
> Remove reference to libtiff 3.x

- Tests/test_imagemath_lambda_eval.py
Adds coverage for the lines missing at https://app.codecov.io/gh/python-pillow/Pillow/blob/main/src%2FPIL%2FImageMath.py
> Improve ImageMath test coverage

- .github/workflows/test-windows.yml
- .github/workflows/test.yml
PyPy3.10 has been removed from the latest PyPy release - https://pypy.org/posts/2025/07/pypy-v7320-release.html
> Drop support for PyPy3.10

- Tests/test_features.py
Another sequel to #9053
That PR removed webp-related features.
> Remove WebP feature handling

- Tests/test_image_histogram.py
- src/libImaging/Histo.c
Resolves #9050
For an `image32` image without a mask, histogram values are generated with
https://github.com/python-pillow/Pillow/blob/37cd041e5e9041b0708551c02655328e8761226d/src/libImaging/Histo.c#L136-L139
However, this doesn't consider that some images (PA, LA and La) only have two bands
https://github.com/python-pillow/Pillow/blob/37cd041e5e9041b0708551c02655328e8761226d/src/libImaging/Storage.c#L78-L80
https://github.com/python-pillow/Pillow/blob/37cd041e5e9041b0708551c02655328e8761226d/src/_imaging.c#L1360-L1361
meaning that two band histograms only have 512 values, rather than 1024. So this PR skips the middle two bands when assigning values.
> Use correct bands for two band histograms

- .ci/requirements-cibw.txt
- Tests/test_image_access.py
- Tests/test_pyroma.py
- pyproject.toml
Restores the Pyroma check on iOS.
Bumping the version of cibuildwheel ensures an updated iOS support package is used; this support package treats the installed dependencies directory as a site package, ensuring that the pyroma module can be discovered by pytest.
The change to the pyroma test itself is required because the `get_data()` call requires the use of subprocess - the test builds an entirely fresh wheel, and checks the data of *that* wheel. 
The approach proposed here uses importlib to extract the metadata of the wheel that is actually installed for testing purposes (which, really, is the wheel that we *should* be testing).
Unfortunately, the `map_metadata_keys()` method that *was* available in pyroma 4.3.3 has been removed in 5.0, and internalised into the `build_metadata()` …
> Restore pyroma test for iOS

- src/PIL/_typing.py
NumPy 1.20 became EOL on 31 January 2023.
Support for it was added afterwards at the request of #8187, but that user was happy for the [support to be removed at the same time as Python 3.9 support is removed](https://github.com/python-pillow/Pillow/pull/8187#issuecomment-2202109282), which is now due to happen in our next release.
This PR only affects the use of NumPy when type checking.
> Remove support for NumPy 1.20 when type checking

- Tests/test_imagecms.py
- src/PIL/GimpPaletteFile.py
- src/PIL/Image.py
- src/PIL/Jpeg2KImagePlugin.py
- src/PIL/JpegImagePlugin.py
- src/PIL/PngImagePlugin.py
- src/PIL/WebPImagePlugin.py
Inspired by #9119, this moves some type hint related imports within `if TYPE_CHECKING`
> Move imports into TYPE_CHECKING

- .ci/requirements-cibw.txt
- .github/workflows/wheels-dependencies.sh
- checks/check_wheel.py
* Adds build instructions to add libavif to the compiled dependencies.
* Bumps cibuildwheel to 3.1.2 to pick up bug fixes and Python 3.14 support for iOS
> Add libavif support for iOS

- depends/install_imagequant.sh
- docs/installation/building-from-source.rst
- winbuild/build_prepare.py
libimagequant 4.4.0 has been released - https://github.com/ImageOptim/libimagequant/releases/tag/4.4.0
> Updated libimagequant to 4.4.0

- checks/check_imaging_leaks.py
- checks/check_j2k_leaks.py
- checks/check_jpeg_leaks.py
- tox.ini
#9030 moved several scripts into a new 'checks' directory.
However, some of them still try to import from `Tests/helper.py`.
https://github.com/python-pillow/Pillow/blob/e786019e8304663fb41574c6f50e5724873e68fd/checks/check_imaging_leaks.py#L11
This copies the helper functions into `checks` to fix it, and adds the directory to mypy.
> Do not import from Tests directory in checks

- docs/reference/ImageFile.rst
- src/PIL/ImageFile.py
> Document ImageFile.MAXBLOCK

- src/PIL/Image.py
There's no need to set `core` in 
https://github.com/python-pillow/Pillow/blob/34c651deb8390ef752425a31e1473af4d6c9db3d/src/PIL/Image.py#L106
if we're just going to `raise` a few lines later, and not use it in between.
https://github.com/python-pillow/Pillow/blob/34c651deb8390ef752425a31e1473af4d6c9db3d/src/PIL/Image.py#L107-L120
> Do not set core to DeferredError

- Tests/helper.py
- Tests/test_file_webp_animated.py
- Tests/test_image_quantize.py
- Tests/test_imagefontctl.py
Adds `has_feature_version()` to Tests/helper.py.
This reduces some duplicate code, but also - at the moment, test_imagefontctl.py just catches a version exception
https://github.com/python-pillow/Pillow/blob/9f5d1f71a02da17061ce5acec1f1adf81913aaf0/Tests/test_imagefontctl.py#L107-L111
It is theoretically possible that our C code is throwing the exception when it shouldn't, so it is better to check the version in Python first.
> Add has_feature_version helper

- src/PIL/FliImagePlugin.py
- src/PIL/GribStubImagePlugin.py
- src/PIL/PcxImagePlugin.py
- src/PIL/PpmImagePlugin.py
This improves/adds length checks in `_accept` for several plugins.
Here are two examples of the errors this fixes.
```pycon
>>> from PIL import FliImagePlugin
>>> FliImagePlugin._accept(b"test\x11\xaf")
File "PIL/FliImagePlugin.py", line 35, in _accept
and i16(prefix, 14) in [0, 3]  # flags
File "PIL/_binary.py", line 37, in i16le
return unpack_from("<H", c, o)[0]
struct.error: unpack_from requires a buffer of at least 16 bytes for unpacking 2 bytes at offset 14 (actual buffer size is 6)
>>> from PIL import GribStubImagePlugin
>>> GribStubImagePlugin._accept(b"GRIB")
File "PIL/GribStubImagePlugin.py", line 36, in _accept
return …
```
> Improve _accept length check

- Tests/test_image.py
- src/PIL/Image.py
Resolves #9078
A user has found that after
```python
from PIL import Image, ExifTags
with Image.open("Tests/images/exif_gps.jpg") as im:
exif = im.getexif()
exif.get_ifd(ExifTags.IFD.GPSInfo)
del exif[ExifTags.IFD.GPSInfo]
im.save("out.jpg", exif=exif)
```
the saved image still has GPS data.
This is because `get_ifd()` [populates `_ifds`](https://github.com/python-pillow/Pillow/blob/d74fdc4b5de5a22b91e82c123292ff7780dd20a4/src/PIL/Image.py#L4071-L4077),  and `del exif[ExifTags.IFD.GPSInfo]` [doesn't clear it](https://github.com/python-pillow/Pillow/blob/d74fdc4b5de5a22b91e82c123292ff7780dd20a4/src/PIL/Image.py#L4213-L4217). This fixes that.
> When deleting EXIF IFD tag, delete IFD data

- Tests/test_file_pcd.py
- src/PIL/PcdImagePlugin.py
Resolves FIXME
https://github.com/python-pillow/Pillow/blob/d74fdc4b5de5a22b91e82c123292ff7780dd20a4/src/PIL/PcdImagePlugin.py#L49
by setting rotated size in `open()` instead of waiting until `load()`
> Set correct size for rotated PCD images after opening

- Tests/test_file_wal.py
- src/PIL/WalImageFile.py
Adds coverage for the line missing at https://app.codecov.io/gh/python-pillow/Pillow/blob/main/src%2FPIL%2FWalImageFile.py
While I'm here, I've also added use of the walrus operator.
> Improve WalImageFile test coverage

- .github/workflows/wheels-dependencies.sh
- wheels/dependency_licenses/ZSTD.txt
Resolves #9095
Install [zstd](https://github.com/facebook/zstd) for use with libtiff in Linux wheels
> Install zstd for libtiff on Linux wheels

- Tests/test_pyroma.py
Sequel to https://github.com/python-pillow/Pillow/pull/9116
`metadata` is both imported and a variable.
https://github.com/python-pillow/Pillow/blob/98d6c3bf8818849e2414ef4de8c9e02b03de3886/Tests/test_pyroma.py#L3
https://github.com/python-pillow/Pillow/blob/98d6c3bf8818849e2414ef4de8c9e02b03de3886/Tests/test_pyroma.py#L12
This renames the variable.
> Rename variable to not shadow import

- Tests/test_file_libtiff.py
#4605 added a check for roundtripping the XMLPacket tag through libtiff. It allowed the tag to be missing however.
https://github.com/python-pillow/Pillow/blob/7dbcb32cbe524a8ec4c12f21c762cd7153b2b03b/Tests/test_file_libtiff.py#L368-L369
This PR improves the check, by requiring that the tag be present.
> Always check XMLPacket value

- .github/workflows/wheels-dependencies.sh
- winbuild/build_prepare.py
harfbuzz 11.5.0 has been released - https://github.com/harfbuzz/harfbuzz/releases/tag/11.5.0
> Update harfbuzz to 11.5.0

- .github/workflows/wheels.yml
Python 3.9 wheels are no longer built by the macOS 10.10 wheels job - https://github.com/python-pillow/Pillow/actions/runs/17784488122/job/50549409613#step:5:22173
They are no longer needed either - https://github.com/python-pillow/Pillow/pull/9119
> Python 3.9 wheels are no longer needed

- Tests/test_imagefont.py
- Tests/test_imagefontpil.py
- src/PIL/ImageFont.py
A few `ImageFont._load_pilfont_data()` suggestions.
1. Remove an unnecessary `split()`
https://github.com/python-pillow/Pillow/blob/31eee6e5f706cd0a41ac26c45694adef1eca72a3/src/PIL/ImageFont.py#L132
2. Check `image` mode before reading from `file`, to return the error faster.
3. Rather than potentially reading an entire line,
https://github.com/python-pillow/Pillow/blob/31eee6e5f706cd0a41ac26c45694adef1eca72a3/src/PIL/ImageFont.py#L129
we can limit the length of the read operation by just using `read(8)`.
> Limit length of read operation in ImageFont._load_pilfont_data()

- .github/workflows/wheels-dependencies.sh
- winbuild/build_prepare.py
harfbuzz 12.1.0 has been released - https://github.com/harfbuzz/harfbuzz/releases/tag/12.1.0
> Update harfbuzz to 12.1.0

- Tests/test_imagefile.py
- src/PIL/ImageFile.py
Before https://github.com/python-pillow/Pillow/pull/9046 allowed memory mapping to be used with [raw_negative_stride.bin](https://github.com/python-pillow/Pillow/blob/main/Tests/images/raw_negative_stride.bin), the negative offset in the tile triggered
```pytb
File "PIL/ImageFile.py", line 341, in load
seek(offset)
OSError: [Errno 22] Invalid argument
```
Now however, it doesn't. This PR raises a specific error when a negative offset is used with memory mapping.
> Do not allow negative offset with memory mapping

- Tests/test_file_eps.py
- src/PIL/EpsImagePlugin.py
Resolves #9210
Page 44 of https://web.mit.edu/PostScript/Adobe/Documents/5001.DSC_Spec.pdf
> **%%BeginBinary:** \<bytecount>
> \<bytecount> ::= <uint>
> **%%EndBinary** (no keywords)
> These comments are used in a manner similar to the %%Begin(End)Data: comments. The %%Begin(End)Binary: comments are designed to allow a document manager to effectively ignore any binary data these comments encapsulate.
When encountering '%%BeginBinary:', rather than continuing to [loop](https://github.com/python-pillow/Pillow/blob/0013f9590a5d5b3e08c7cd152843d18ff490dd40/src/PIL/EpsImagePlugin.py#L250) through data and trying to read the mode, size and bounding box, just seek past it.
> Seek past BeginBinary data when parsing EPS metadata
